-- HAVEN_STORE.ALIGN_ALYTICS.BOOKING_ADDON_AUDIT source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.BOOKING_ADDON_AUDIT(
	START_DATE,
	END_DATE,
	BOOKING_ID,
	ADDON_CODE,
	ADDON,
	ADDON_VALUE,
	GROUP_BOOKING_ID,
	CURRENT_BOOKING_STATUS
) as SELECT START_DATE, END_DATE, BOOKING_ID, ADDON_CODE, ADDON, ADDON_VALUE, GROUP_BOOKING_ID, CURRENT_BOOKING_STATUS
FROM HAVEN_STORE.TROOPER2.BOOKING_ADDON_AUDIT;


-- HAVEN_STORE.ALIGN_ALYTICS.BOOKING_DETAIL_HISTORY source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.BOOKING_DETAIL_HISTORY(
	BOOKING_KEY,
	BOOKING_TYPE,
	BOOKING_ID,
	DELEGATE_RES_ID,
	BOOKING_STATUS_CATEGORY,
	UNIT_WEEKS,
	TOTAL_UNITS,
	PAID_GRADE,
	PAID_GRADE_DESCRIPTION,
	REQUESTED_GRADE,
	REQUESTED_GRADE_DESCRIPTION,
	ALLOCATED_GRADE,
	ALLOCATED_GRADE_DESCRIPTION,
	PITCH_CODE,
	CONTRACT_TYPE,
	TOTAL_GUESTS,
	ADULTS,
	CHILDREN,
	INFANTS,
	GROSS_BILLINGS,
	AGENCY_COMMISSION,
	NETT_BILLINGS,
	START_DATE,
	END_DATE
) as SELECT BOOKING_KEY, BOOKING_TYPE, BOOKING_ID, DELEGATE_RES_ID, BOOKING_STATUS_CATEGORY, UNIT_WEEKS, TOTAL_UNITS, PAID_GRADE, PAID_GRADE_DESCRIPTION, REQUESTED_GRADE, REQUESTED_GRADE_DESCRIPTION, ALLOCATED_GRADE, ALLOCATED_GRADE_DESCRIPTION, PITCH_CODE, CONTRACT_TYPE, TOTAL_GUESTS, ADULTS, CHILDREN, INFANTS, GROSS_BILLINGS, AGENCY_COMMISSION, NETT_BILLINGS, START_DATE, END_DATE
FROM HAVEN_STORE.TROOPER2.BOOKING_DETAIL_HISTORY;


-- HAVEN_STORE.ALIGN_ALYTICS.BOOKING_FINANCIALS source



-- HAVEN_STORE.ALIGN_ALYTICS.BOOKING_HEADER source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.BOOKING_HEADER(
	BOOKING_KEY,
	BOOKING_TYPE,
	BOOKING_ID,
	BOOKING_STATUS,
	BOOKING_STATUS_CATEGORY,
	PARK_CODE,
	SEASON,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	DURATION,
	AGENCY_ID,
	AGENCY_NAME,
	SOURCE_CHANNEL,
	SECONDARY_AGENCY_ID,
	SECONDARY_AGENCY_NAME,
	PRODUCT,
	PRIMARY_SUB_PRODUCT,
	PRIMARY_SUB_PRODUCT_UNITS,
	SECONDARY_SUB_PRODUCT,
	SECONDARY_SUB_PRODUCT_UNITS,
	BOOKING_DATE,
	FIRM_DATE,
	CANCELLATION_DATE,
	CANCELLATION_REASON,
	BOOKING_LOCATION,
	BOOKING_DATE_PY,
	ARRIVAL_DATE_PY,
	ARRIVAL_PERIOD_NUMBER,
	ARRIVAL_PERIOD_NUMBER_PY,
	GROSS_BILLINGS,
	AGENCY_COMMISSION,
	NETT_BILLINGS,
	TOTAL_UNITS,
	UNIT_WEEKS,
	TOTAL_GUESTS,
	ADULTS,
	CHILDREN,
	INFANTS
) as SELECT BOOKING_KEY, BOOKING_TYPE, BOOKING_ID, BOOKING_STATUS, BOOKING_STATUS_CATEGORY, PARK_CODE, SEASON, ARRIVAL_DATE, DEPARTURE_DATE, DURATION, AGENCY_ID, AGENCY_NAME, SOURCE_CHANNEL, SECONDARY_AGENCY_ID, SECONDARY_AGENCY_NAME, PRODUCT, PRIMARY_SUB_PRODUCT, PRIMARY_SUB_PRODUCT_UNITS, SECONDARY_SUB_PRODUCT, SECONDARY_SUB_PRODUCT_UNITS, BOOKING_DATE, FIRM_DATE, CANCELLATION_DATE, CANCELLATION_REASON, BOOKING_LOCATION, BOOKING_DATE_PY, ARRIVAL_DATE_PY, ARRIVAL_PERIOD_NUMBER, ARRIVAL_PERIOD_NUMBER_PY, GROSS_BILLINGS, AGENCY_COMMISSION, NETT_BILLINGS, TOTAL_UNITS, UNIT_WEEKS, TOTAL_GUESTS, ADULTS, CHILDREN, INFANTS
FROM HAVEN_STORE.TROOPER2.BOOKING_HEADER;


-- HAVEN_STORE.ALIGN_ALYTICS.BOOKING_HEADER_HISTORY source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.BOOKING_HEADER_HISTORY(
	BOOKING_KEY,
	BOOKING_TYPE,
	BOOKING_ID,
	BOOKING_STATUS,
	BOOKING_STATUS_CATEGORY,
	PARK_CODE,
	SEASON,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	DURATION,
	AGENCY_ID,
	AGENCY_NAME,
	SOURCE_CHANNEL,
	SECONDARY_AGENCY_ID,
	SECONDARY_AGENCY_NAME,
	PRODUCT,
	PRIMARY_SUB_PRODUCT,
	PRIMARY_SUB_PRODUCT_UNITS,
	SECONDARY_SUB_PRODUCT,
	SECONDARY_SUB_PRODUCT_UNITS,
	BOOKING_DATE,
	FIRM_DATE,
	CANCELLATION_DATE,
	CANCELLATION_REASON,
	BOOKING_LOCATION,
	BOOKING_DATE_PY,
	ARRIVAL_DATE_PY,
	ARRIVAL_PERIOD_NUMBER,
	ARRIVAL_PERIOD_NUMBER_PY,
	GROSS_BILLINGS,
	AGENCY_COMMISSION,
	NETT_BILLINGS,
	TOTAL_UNITS,
	UNIT_WEEKS,
	TOTAL_GUESTS,
	ADULTS,
	CHILDREN,
	INFANTS,
	START_DATE,
	END_DATE
) as SELECT BOOKING_KEY, BOOKING_TYPE, BOOKING_ID, BOOKING_STATUS, BOOKING_STATUS_CATEGORY, PARK_CODE, SEASON, ARRIVAL_DATE, DEPARTURE_DATE, DURATION, AGENCY_ID, AGENCY_NAME, SOURCE_CHANNEL, SECONDARY_AGENCY_ID, SECONDARY_AGENCY_NAME, PRODUCT, PRIMARY_SUB_PRODUCT, PRIMARY_SUB_PRODUCT_UNITS, SECONDARY_SUB_PRODUCT, SECONDARY_SUB_PRODUCT_UNITS, BOOKING_DATE, FIRM_DATE, CANCELLATION_DATE, CANCELLATION_REASON, BOOKING_LOCATION, BOOKING_DATE_PY, ARRIVAL_DATE_PY, ARRIVAL_PERIOD_NUMBER, ARRIVAL_PERIOD_NUMBER_PY, GROSS_BILLINGS, AGENCY_COMMISSION, NETT_BILLINGS, TOTAL_UNITS, UNIT_WEEKS, TOTAL_GUESTS, ADULTS, CHILDREN, INFANTS, START_DATE, END_DATE
FROM HAVEN_STORE.TROOPER2.BOOKING_HEADER_HISTORY;


-- HAVEN_STORE.ALIGN_ALYTICS.BOOKINGS_DAILYEXTRACT source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.BOOKINGS_DAILYEXTRACT(
	REFID,
	GROUP_ID,
	RES_ID,
	CLIENT_ID,
	SHIP_CODE,
	SOURCE_CODE,
	AGENCY_NAME,
	CABIN_CATEGORY,
	RES_INIT_DATE,
	SAIL_DATE_FROM,
	HOLIDAY_DURATION,
	BREAK_START,
	BREAK_END,
	BREAK_DURATION,
	REFERRAL_CODE,
	BOOKING_STATUS,
	RES_GUEST_COUNT,
	INVOICE_TOTAL,
	UNIT_ALLOCATED,
	AREA_CODE,
	AREA_NAME,
	ZONE_CODE,
	ZONE_NAME,
	PITCH_NUMBER,
	PITCH_CODE,
	DISCOUNTS,
	ADDONS,
	ACCOMMODATION,
	OPERATOR,
	PRODUCT,
	CANCELLATION_CHARGES,
	IS_CANCELLED,
	SEASON,
	ENDOFSEASON,
	EXTRACT_DATE
) as SELECT REFID, GROUP_ID, RES_ID, CLIENT_ID, SHIP_CODE, SOURCE_CODE, AGENCY_NAME, CABIN_CATEGORY, RES_INIT_DATE, SAIL_DATE_FROM, HOLIDAY_DURATION, BREAK_START, BREAK_END, BREAK_DURATION, REFERRAL_CODE, BOOKING_STATUS, RES_GUEST_COUNT, INVOICE_TOTAL, UNIT_ALLOCATED, AREA_CODE, AREA_NAME, ZONE_CODE, ZONE_NAME, PITCH_NUMBER, PITCH_CODE, DISCOUNTS, ADDONS, ACCOMMODATION, OPERATOR, PRODUCT, CANCELLATION_CHARGES, IS_CANCELLED, SEASON, ENDOFSEASON, EXTRACT_DATE
FROM HAVEN_STORE.OCANDC.BOOKINGS_DAILYEXTRACT;


-- HAVEN_STORE.ALIGN_ALYTICS.BUDGET_PHYSICAL_CAPACITY source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.BUDGET_PHYSICAL_CAPACITY(
	DATE_OF_STAY,
	PARK_CODE,
	GRADE_CODE,
	BUDGET_CAPACITY
) as SELECT DATE_OF_STAY, PARK_CODE, GRADE_CODE, BUDGET_CAPACITY
FROM HAVEN_STORE.OCANDC.BUDGET_PHYSICAL_CAPACITY;


-- HAVEN_STORE.ALIGN_ALYTICS.CANCELLATIONS_CURRENTSEASON source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.CANCELLATIONS_CURRENTSEASON(
	REF,
	LOAD_REF,
	RES_ID,
	BOOK_DATE,
	ARRIVAL_DATE,
	PARK_CODE,
	PRODUCT,
	CHANNEL,
	AGENCY_TYPE,
	REFERRAL_SOURCE,
	CANCELLATION_CASE,
	REASON_IS_CORONA,
	COMMENT_HAS_CORONA,
	REFUND_TO_CLIENT_BANK,
	CLIENT_BANK_SINCE_MARCH,
	CLIENT_BANK_BALANCE,
	REFUND_CASH,
	CASH_SINCE_MARCH,
	CASH_SINCE_MARCH_PENDING,
	REFUND_TO_AGENCY_BANK,
	AGENCY_BANK_SINCE_MARCH,
	CANCELLATION_DATE,
	PERFORMER,
	LOCATION,
	HAS_HPP,
	PRE_CANCELLATION_BILLINGS,
	FLAGGED_AS_REFUND,
	REFUND_REQUEST_DATE,
	FLAGGED_AS_ADJUST,
	ADJUST_REQUEST_DATE,
	CHARGES,
	PAID,
	CHARGES_PAID,
	PENDING_REFUNDS,
	CLIENT_ID,
	ZENDATA_CHOICE,
	REBOOKED,
	REBOOKED_RES_ID,
	ZENDATA_CHOICE_DATE,
	REFUND_MANUAL,
	REFUND_AUTO,
	CASH_PAID,
	ALT_RES_ID,
	REFUND_PROCESSED_DATE,
	GROUP_ID,
	RECEIVED_CASH,
	RECEIVED_CHEQUES,
	RECEIVED_CARD,
	GROUP_FUNDS_REST,
	GROUP_TO_AGENCY_BANK,
	GROUP_FUNDS_OUT,
	LAST_TRANSFER_TO_CLIENT_BANK,
	CANCELLATION_REFUND_REQUEST_DATE,
	SUN_REQUEST_DATE,
	SUN_REQUEST_ACTION,
	GROUP_CHARGES,
	TERMS_CONFIRMED,
	PURE_CASH_REFUNDS,
	FIRST_ZENDESK_CHOICE,
	FIRST_ZENDESK_DATE,
	EMAIL_ADDRESS,
	MOBILE_NUMBER,
	HIDEAWAY_TYPE,
	HAVEN10,
	PRE_CANCELLATION_COMMISSION,
	GROUP_FULLY_PAID,
	POOL10,
	PASSES_PRESENT,
	PASSES_ADDED,
	SUB_PRODUCT,
	ACTIVITY_COUNT,
	WHOSE_DEBT,
	AGENCY_NAME,
	TRANSFER_YN
) as SELECT "REF", LOAD_REF, RES_ID, BOOK_DATE, ARRIVAL_DATE, PARK_CODE, PRODUCT, CHANNEL, AGENCY_TYPE, REFERRAL_SOURCE, CANCELLATION_CASE, REASON_IS_CORONA, COMMENT_HAS_CORONA, REFUND_TO_CLIENT_BANK, CLIENT_BANK_SINCE_MARCH, CLIENT_BANK_BALANCE, REFUND_CASH, CASH_SINCE_MARCH, CASH_SINCE_MARCH_PENDING, REFUND_TO_AGENCY_BANK, AGENCY_BANK_SINCE_MARCH, CANCELLATION_DATE, PERFORMER, "LOCATION", HAS_HPP, PRE_CANCELLATION_BILLINGS, FLAGGED_AS_REFUND, REFUND_REQUEST_DATE, FLAGGED_AS_ADJUST, ADJUST_REQUEST_DATE, CHARGES, PAID, CHARGES_PAID, PENDING_REFUNDS, CLIENT_ID, ZENDATA_CHOICE, REBOOKED, REBOOKED_RES_ID, ZENDATA_CHOICE_DATE, REFUND_MANUAL, REFUND_AUTO, CASH_PAID, ALT_RES_ID, REFUND_PROCESSED_DATE, GROUP_ID, RECEIVED_CASH, RECEIVED_CHEQUES, RECEIVED_CARD, GROUP_FUNDS_REST, GROUP_TO_AGENCY_BANK, GROUP_FUNDS_OUT, LAST_TRANSFER_TO_CLIENT_BANK, CANCELLATION_REFUND_REQUEST_DATE, SUN_REQUEST_DATE, SUN_REQUEST_ACTION, GROUP_CHARGES, TERMS_CONFIRMED, PURE_CASH_REFUNDS, FIRST_ZENDESK_CHOICE, FIRST_ZENDESK_DATE, EMAIL_ADDRESS, MOBILE_NUMBER, HIDEAWAY_TYPE, HAVEN10, PRE_CANCELLATION_COMMISSION, GROUP_FULLY_PAID, POOL10, PASSES_PRESENT, PASSES_ADDED, SUB_PRODUCT, ACTIVITY_COUNT, WHOSE_DEBT, AGENCY_NAME, TRANSFER_YN
FROM HAVEN_STORE.TROOPER.CANCELLATIONS_CURRENTSEASON;


-- HAVEN_STORE.ALIGN_ALYTICS.GRADE_MAPPING source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.GRADE_MAPPING(
	REF,
	PARK,
	NEW_GRADE,
	OLD_GRADE,
	ATTRIBUTE
) as SELECT "REF", PARK, NEW_GRADE, OLD_GRADE, "ATTRIBUTE"
FROM HAVEN_STORE.TROOPER.GRADE_MAPPING;


-- HAVEN_STORE.ALIGN_ALYTICS.GRADE_PRICE_HISTORY source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.GRADE_PRICE_HISTORY(
	SNAPSHOT,
	INTEGRATION,
	SHIP_CODE,
	ARRIVAL_DATE,
	GRADE,
	DURATION,
	PACKAGE_TYPE,
	AMOUNT_TOTAL,
	CABIN_CATEGORY_DESCRIPTION
) as SELECT SNAPSHOT_TIMESTAMP, INTEGRATION_TIMESTAMP, SHIP_CODE, ARRIVAL_DATE, GRADE, DURATION, PACKAGE_TYPE, AMOUNT_TOTAL, CABIN_CATEGORY_DESCRIPTION
FROM HAVEN_STORE.AVAILABILITY.GRADE_PRICE_HISTORY;


-- HAVEN_STORE.ALIGN_ALYTICS.GROUP_FINANCIALS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.GROUP_FINANCIALS(
	GROUP_ID,
	TOTAL_ACCOMMODATION_VALUE,
	TOTAL_DEPOSIT_VALUE,
	TOTAL_DISCOUNT_VALUE,
	TOTAL_ADDON_VALUE,
	TOTAL_CHARGE_VALUE,
	TOTAL_PAID_VALUE,
	GROSS_BILLING_VALUE,
	TOTAL_COMMISSION_VALUE,
	NETT_BILLING_VALUE
) as SELECT GROUP_ID, TOTAL_ACCOMMODATION_VALUE, TOTAL_DEPOSIT_VALUE, TOTAL_DISCOUNT_VALUE, TOTAL_ADDON_VALUE, TOTAL_CHARGE_VALUE, TOTAL_PAID_VALUE, GROSS_BILLING_VALUE, TOTAL_COMMISSION_VALUE, NETT_BILLING_VALUE
FROM HAVEN_STORE.TROOPER2.GROUP_FINANCIALS;


-- HAVEN_STORE.ALIGN_ALYTICS.HAVEN_SEARCHES source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.HAVEN_SEARCHES(
	ID,
	DATE,
	TRANSACTION_PARK_CODE_H,
	TRANSACTION_ARRIVAL_DATE_H,
	TOTAL_EVENTS,
	UPDATEDDATETIME,
	UPDATEDBY
) as SELECT ID, DATE, TRANSACTION_PARK_CODE_H, TRANSACTION_ARRIVAL_DATE_H, TOTAL_EVENTS, UPDATEDDATETIME, UPDATEDBY
FROM HAVEN_STORE.OCANDC.HAVEN_SEARCHES;


-- HAVEN_STORE.ALIGN_ALYTICS.HAVEN_TRANSACTIONS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.HAVEN_TRANSACTIONS(
	ID,
	DATE,
	TRANSACTION_PARK_CODE_H,
	TRANSACTION_ARRIVAL_DATE_H,
	TRANSACTIONS,
	UPDATEDDATETIME,
	UPDATEDBY
) as SELECT ID, DATE, TRANSACTION_PARK_CODE_H, TRANSACTION_ARRIVAL_DATE_H, TRANSACTIONS, UPDATEDDATETIME, UPDATEDBY
FROM HAVEN_STORE.OCANDC.HAVEN_TRANSACTIONS;


-- HAVEN_STORE.ALIGN_ALYTICS.INVENTORY_AVAILABILITY_HISTORY source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.INVENTORY_AVAILABILITY_HISTORY(
	DATE_D,
	PARK_CODE,
	GRADE_CODE,
	PRODUCT_TYPE,
	PITCHES,
	HELD,
	FIRM,
	AVAILABLE,
	SNAPSHOT,
	INTEGRATION
) as SELECT DEPARTURE_DATE, PARK_CODE, GRADE_CODE, PRODUCT_TYPE, PITCHES, HELD, FIRM, AVAILABLE, SNAPSHOT_TIMESTAMP, INTEGRATION_TIMESTAMP
FROM HAVEN_STORE.AVAILABILITY.INVENTORY_AVAILABILITY_HISTORY;


-- HAVEN_STORE.ALIGN_ALYTICS.INVENTORY_AVAILABILITY_HISTORY_D source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.INVENTORY_AVAILABILITY_HISTORY_D(
	"Date",
	PARK_CODE,
	GRADE_CODE,
	PRODUCT_TYPE,
	PITCHES,
	HELD,
	FIRM,
	AVAILABLE,
	SNAPSHOT,
	INTEGRATION
) as SELECT DEPARTURE_DATE, PARK_CODE, GRADE_CODE, PRODUCT_TYPE, PITCHES, HELD, FIRM, AVAILABLE, SNAPSHOT_TIMESTAMP, INTEGRATION_TIMESTAMP
FROM HAVEN_STORE.AVAILABILITY.INVENTORY_AVAILABILITY_HISTORY;


-- HAVEN_STORE.ALIGN_ALYTICS.LETTING_CAPS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.LETTING_CAPS(
	PARK_CODE,
	PACKAGE_START_DT,
	PACKAGE_END_DT,
	DURATION,
	CAP_TYPE,
	CAP
) as SELECT PARK_CODE, PACKAGE_START_DT, PACKAGE_END_DT, DURATION, CAP_TYPE, CAP
FROM HAVEN_STORE.OCANDC.LETTING_CAPS;


-- HAVEN_STORE.ALIGN_ALYTICS.LETTINGS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.LETTINGS(
	PARK_CODE,
	PARK_SHORT_DESC,
	VAN_STOCK_NO,
	LETTING_CAT_CODE,
	LETTING_DESC,
	BREAK_TYPE,
	PACKAGE_START_DATE,
	PACKAGE_END_DATE,
	CHANGE_DT,
	REMOVED_YN
) as SELECT PARK_CODE, PARK_SHORT_DESC, VAN_STOCK_NO, LETTING_CAT_CODE, LETTING_DESC, BREAK_TYPE, PACKAGE_START_DATE, PACKAGE_END_DATE, CHANGE_DT, REMOVED_YN
FROM HAVEN_STORE.OCANDC.LETTINGS;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_ARRIVALS_TY_FINAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_ARRIVALS_TY_FINAL(
	SHIP_CODE,
	SOURCE,
	BREAK_DATE,
	NET_TARIFF,
	NET_RICHCORE,
	NET_DINING,
	NET_ADDONS,
	NET_ROOMSOLD,
	NET_GW,
	TABLEAU_COLUMN,
	TIME_COLUMN,
	PERIOD,
	BREAKDATE_PRIOR,
	YEAR,
	AVAILABLE_ROOMS
) as SELECT SHIP_CODE, SOURCE, BREAK_DATE, NET_TARIFF, NET_RICHCORE, NET_DINING, NET_ADDONS, NET_ROOMSOLD, NET_GW, TABLEAU_COLUMN, TIME_COLUMN, PERIOD, BREAKDATE_PRIOR, YEAR, AVAILABLE_ROOMS
FROM HAVEN_STORE.OCANDC.OCC_AGG_ARRIVALS_TY_FINAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_HOLIDAYSALES_NY_FINAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_HOLIDAYSALES_NY_FINAL(
	SHIP_CODE,
	SOURCE,
	BREAK_DATE,
	NET_TARIFF,
	NET_RICHCORE,
	NET_DINING,
	NET_ADDONS,
	NET_ROOMSOLD,
	NET_GW,
	TABLEAU_COLUMN,
	TIME_COLUMN,
	PERIOD,
	BREAKDATE_PRIOR,
	YEAR,
	AVAILABLE_ROOMS
) as SELECT SHIP_CODE, SOURCE, BREAK_DATE, NET_TARIFF, NET_RICHCORE, NET_DINING, NET_ADDONS, NET_ROOMSOLD, NET_GW, TABLEAU_COLUMN, TIME_COLUMN, PERIOD, BREAKDATE_PRIOR, YEAR, AVAILABLE_ROOMS
FROM HAVEN_STORE.OCANDC.OCC_AGG_HOLIDAYSALES_NY_FINAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_HOLIDAYSALES_TY_FINAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_HOLIDAYSALES_TY_FINAL(
	SHIP_CODE,
	SOURCE,
	BREAK_DATE,
	NET_TARIFF,
	NET_RICHCORE,
	NET_DINING,
	NET_ADDONS,
	NET_ROOMSOLD,
	NET_GW,
	TABLEAU_COLUMN,
	TIME_COLUMN,
	PERIOD,
	BREAKDATE_PRIOR,
	YEAR,
	AVAILABLE_ROOMS
) as SELECT SHIP_CODE, SOURCE, BREAK_DATE, NET_TARIFF, NET_RICHCORE, NET_DINING, NET_ADDONS, NET_ROOMSOLD, NET_GW, TABLEAU_COLUMN, TIME_COLUMN, PERIOD, BREAKDATE_PRIOR, YEAR, AVAILABLE_ROOMS
FROM HAVEN_STORE.OCANDC.OCC_AGG_HOLIDAYSALES_TY_FINAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_TARGETS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_TARGETS(
	SOURCE,
	BREAK_DATE,
	RESORT,
	LEAD_TIME_DAY,
	ACTUAL_DATE,
	DAILY_TARGET_NET_ROS,
	DAILY_TARGET_GROSS_ROS,
	DAILY_TARGET_NET_ADDONS,
	DAILY_TARGET_NET_DINING,
	DAILY_TARGET_COMPOSITE_PRICE,
	DAILY_TARGET_NET_RICHCORE,
	DAILY_TARGET_SILVER_PRICE,
	CUMULATIVE_TARGET_NET_ADDONS,
	LAST7_DAY_TARGET_NET_ADDONS,
	LAST14_DAY_TARGET_NET_ADDONS,
	LAST28_DAY_TARGET_NET_ADDONS,
	NEXT7_DAY_TARGET_NET_ADDONS,
	NEXT14_DAY_TARGET_NET_ADDONS,
	NEXT28_DAY_TARGET_NET_ADDONS,
	CUMULATIVE_TARGET_NET_DINING,
	LAST7_DAY_TARGET_NET_DINING,
	LAST14_DAY_TARGET_NET_DINING,
	LAST28_DAY_TARGET_NET_DINING,
	NEXT7_DAY_TARGET_NET_DINING,
	NEXT14_DAY_TARGET_NET_DINING,
	NEXT28_DAY_TARGET_NET_DINING,
	CUMULATIVE_TARGET_NET_RICHCORE,
	LAST7_DAY_TARGET_NET_RICHCORE,
	LAST14_DAY_TARGET_NET_RICHCORE,
	LAST28_DAY_TARGET_NET_RICHCORE,
	NEXT7_DAY_TARGET_NET_RICHCORE,
	NEXT14_DAY_TARGET_NET_RICHCORE,
	NEXT28_DAY_TARGET_NET_RICHCORE,
	CUMULATIVE_TARGET_NET_ROOMS_SOLD,
	LAST7_DAY_TARGET_NET_ROOMS_SOLD,
	LAST14_DAY_TARGET_NET_ROOMS_SOLD,
	LAST28_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT7_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT14_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT28_DAY_TARGET_NET_ROOMS_SOLD,
	CUMULATIVE_TARGET_GROSS_ROOMS_SOLD,
	LAST7_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST14_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST28_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD,
	CUMULATIVE_TARGET_NET_SILVER_PRICE,
	LAST7_DAY_TARGET_NET_SILVER_PRICE,
	LAST14_DAY_TARGET_NET_SILVER_PRICE,
	LAST28_DAY_TARGET_NET_SILVER_PRICE,
	NEXT7_DAY_TARGET_NET_SILVER_PRICE,
	NEXT14_DAY_TARGET_NET_SILVER_PRICE,
	NEXT28_DAY_TARGET_NET_SILVER_PRICE
) as SELECT SOURCE, BREAK_DATE, RESORT, LEAD_TIME_DAY, ACTUAL_DATE, DAILY_TARGET_NET_ROS, DAILY_TARGET_GROSS_ROS, DAILY_TARGET_NET_ADDONS, DAILY_TARGET_NET_DINING, DAILY_TARGET_COMPOSITE_PRICE, DAILY_TARGET_NET_RICHCORE, DAILY_TARGET_SILVER_PRICE, CUMULATIVE_TARGET_NET_ADDONS, LAST7_DAY_TARGET_NET_ADDONS, LAST14_DAY_TARGET_NET_ADDONS, LAST28_DAY_TARGET_NET_ADDONS, NEXT7_DAY_TARGET_NET_ADDONS, NEXT14_DAY_TARGET_NET_ADDONS, NEXT28_DAY_TARGET_NET_ADDONS, CUMULATIVE_TARGET_NET_DINING, LAST7_DAY_TARGET_NET_DINING, LAST14_DAY_TARGET_NET_DINING, LAST28_DAY_TARGET_NET_DINING, NEXT7_DAY_TARGET_NET_DINING, NEXT14_DAY_TARGET_NET_DINING, NEXT28_DAY_TARGET_NET_DINING, CUMULATIVE_TARGET_NET_RICHCORE, LAST7_DAY_TARGET_NET_RICHCORE, LAST14_DAY_TARGET_NET_RICHCORE, LAST28_DAY_TARGET_NET_RICHCORE, NEXT7_DAY_TARGET_NET_RICHCORE, NEXT14_DAY_TARGET_NET_RICHCORE, NEXT28_DAY_TARGET_NET_RICHCORE, CUMULATIVE_TARGET_NET_ROOMS_SOLD, LAST7_DAY_TARGET_NET_ROOMS_SOLD, LAST14_DAY_TARGET_NET_ROOMS_SOLD, LAST28_DAY_TARGET_NET_ROOMS_SOLD, NEXT7_DAY_TARGET_NET_ROOMS_SOLD, NEXT14_DAY_TARGET_NET_ROOMS_SOLD, NEXT28_DAY_TARGET_NET_ROOMS_SOLD, CUMULATIVE_TARGET_GROSS_ROOMS_SOLD, LAST7_DAY_TARGET_GROSS_ROOMS_SOLD, LAST14_DAY_TARGET_GROSS_ROOMS_SOLD, LAST28_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD, CUMULATIVE_TARGET_NET_SILVER_PRICE, LAST7_DAY_TARGET_NET_SILVER_PRICE, LAST14_DAY_TARGET_NET_SILVER_PRICE, LAST28_DAY_TARGET_NET_SILVER_PRICE, NEXT7_DAY_TARGET_NET_SILVER_PRICE, NEXT14_DAY_TARGET_NET_SILVER_PRICE, NEXT28_DAY_TARGET_NET_SILVER_PRICE
FROM HAVEN_STORE.OCANDC.OCC_AGG_TARGETS;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_TARGETS_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_AGG_TARGETS_REGIONAL(
	SOURCE,
	BREAK_DATE,
	RESORT,
	LEAD_TIME_DAY,
	ACTUAL_DATE,
	DAILY_TARGET_NET_ROS,
	DAILY_TARGET_GROSS_ROS,
	DAILY_TARGET_NET_ADDONS,
	DAILY_TARGET_NET_DINING,
	DAILY_TARGET_NET_RICHCORE,
	DAILY_TARGET_COMPOSITE_PRICE,
	DAILY_TARGET_SILVER_PRICE,
	CUMULATIVE_TARGET_NET_ADDONS,
	LAST7_DAY_TARGET_NET_ADDONS,
	LAST14_DAY_TARGET_NET_ADDONS,
	LAST28_DAY_TARGET_NET_ADDONS,
	NEXT7_DAY_TARGET_NET_ADDONS,
	NEXT14_DAY_TARGET_NET_ADDONS,
	NEXT28_DAY_TARGET_NET_ADDONS,
	CUMULATIVE_TARGET_NET_DINING,
	LAST7_DAY_TARGET_NET_DINING,
	LAST14_DAY_TARGET_NET_DINING,
	LAST28_DAY_TARGET_NET_DINING,
	NEXT7_DAY_TARGET_NET_DINING,
	NEXT14_DAY_TARGET_NET_DINING,
	NEXT28_DAY_TARGET_NET_DINING,
	CUMULATIVE_TARGET_NET_RICHCORE,
	LAST7_DAY_TARGET_NET_RICHCORE,
	LAST14_DAY_TARGET_NET_RICHCORE,
	LAST28_DAY_TARGET_NET_RICHCORE,
	NEXT7_DAY_TARGET_NET_RICHCORE,
	NEXT14_DAY_TARGET_NET_RICHCORE,
	NEXT28_DAY_TARGET_NET_RICHCORE,
	CUMULATIVE_TARGET_NET_ROOMS_SOLD,
	LAST7_DAY_TARGET_NET_ROOMS_SOLD,
	LAST14_DAY_TARGET_NET_ROOMS_SOLD,
	LAST28_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT7_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT14_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT28_DAY_TARGET_NET_ROOMS_SOLD,
	CUMULATIVE_TARGET_GROSS_ROOMS_SOLD,
	LAST7_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST14_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST28_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD,
	CUMULATIVE_TARGET_NET_SILVER_PRICE,
	LAST7_DAY_TARGET_NET_SILVER_PRICE,
	LAST14_DAY_TARGET_NET_SILVER_PRICE,
	LAST28_DAY_TARGET_NET_SILVER_PRICE,
	NEXT7_DAY_TARGET_NET_SILVER_PRICE,
	NEXT14_DAY_TARGET_NET_SILVER_PRICE,
	NEXT28_DAY_TARGET_NET_SILVER_PRICE
) as SELECT SOURCE, BREAK_DATE, RESORT, LEAD_TIME_DAY, ACTUAL_DATE, DAILY_TARGET_NET_ROS, DAILY_TARGET_GROSS_ROS, DAILY_TARGET_NET_ADDONS, DAILY_TARGET_NET_DINING, DAILY_TARGET_NET_RICHCORE, DAILY_TARGET_COMPOSITE_PRICE, DAILY_TARGET_SILVER_PRICE, CUMULATIVE_TARGET_NET_ADDONS, LAST7_DAY_TARGET_NET_ADDONS, LAST14_DAY_TARGET_NET_ADDONS, LAST28_DAY_TARGET_NET_ADDONS, NEXT7_DAY_TARGET_NET_ADDONS, NEXT14_DAY_TARGET_NET_ADDONS, NEXT28_DAY_TARGET_NET_ADDONS, CUMULATIVE_TARGET_NET_DINING, LAST7_DAY_TARGET_NET_DINING, LAST14_DAY_TARGET_NET_DINING, LAST28_DAY_TARGET_NET_DINING, NEXT7_DAY_TARGET_NET_DINING, NEXT14_DAY_TARGET_NET_DINING, NEXT28_DAY_TARGET_NET_DINING, CUMULATIVE_TARGET_NET_RICHCORE, LAST7_DAY_TARGET_NET_RICHCORE, LAST14_DAY_TARGET_NET_RICHCORE, LAST28_DAY_TARGET_NET_RICHCORE, NEXT7_DAY_TARGET_NET_RICHCORE, NEXT14_DAY_TARGET_NET_RICHCORE, NEXT28_DAY_TARGET_NET_RICHCORE, CUMULATIVE_TARGET_NET_ROOMS_SOLD, LAST7_DAY_TARGET_NET_ROOMS_SOLD, LAST14_DAY_TARGET_NET_ROOMS_SOLD, LAST28_DAY_TARGET_NET_ROOMS_SOLD, NEXT7_DAY_TARGET_NET_ROOMS_SOLD, NEXT14_DAY_TARGET_NET_ROOMS_SOLD, NEXT28_DAY_TARGET_NET_ROOMS_SOLD, CUMULATIVE_TARGET_GROSS_ROOMS_SOLD, LAST7_DAY_TARGET_GROSS_ROOMS_SOLD, LAST14_DAY_TARGET_GROSS_ROOMS_SOLD, LAST28_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD, CUMULATIVE_TARGET_NET_SILVER_PRICE, LAST7_DAY_TARGET_NET_SILVER_PRICE, LAST14_DAY_TARGET_NET_SILVER_PRICE, LAST28_DAY_TARGET_NET_SILVER_PRICE, NEXT7_DAY_TARGET_NET_SILVER_PRICE, NEXT14_DAY_TARGET_NET_SILVER_PRICE, NEXT28_DAY_TARGET_NET_SILVER_PRICE
FROM HAVEN_STORE.OCANDC.OCC_AGG_TARGETS_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_BOOKINGS_INC_CANCELLATION source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_BOOKINGS_INC_CANCELLATION(
	REPTGYEAR,
	REFID,
	RES_ID,
	GROUP_ID,
	SHIP_CODE,
	CHANNEL,
	SOURCE,
	AGENCY_NAME,
	CABIN_CATEGORY,
	RES_INIT_DATE,
	CANCELLATION_DATE,
	SAIL_FROM_DATE,
	HOLIDAY_DURATION,
	BREAK_DATE,
	DAYS_IN_BREAK,
	REFERRAL_CODE,
	BOOKING_STATUS,
	BOOKING_COUNT,
	RES_GUEST_COUNT,
	UNIT_ALLOCATED,
	INVOICE_TOTAL,
	DISCOUNTS,
	DINING_TARIFF,
	ADDON_TARIFF,
	RICH_CORE
) as SELECT REPTGYEAR, REFID, RES_ID, GROUP_ID, SHIP_CODE, CHANNEL, SOURCE, AGENCY_NAME, CABIN_CATEGORY, RES_INIT_DATE, CANCELLATION_DATE, SAIL_FROM_DATE, HOLIDAY_DURATION, BREAK_DATE, DAYS_IN_BREAK, REFERRAL_CODE, BOOKING_STATUS, BOOKING_COUNT, RES_GUEST_COUNT, UNIT_ALLOCATED, INVOICE_TOTAL, DISCOUNTS, DINING_TARIFF, ADDON_TARIFF, RICH_CORE
FROM HAVEN_STORE.OCANDC.OCC_BOOKINGS_INC_CANCELLATION;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_BUDGET source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_BUDGET(
	SOURCE,
	BREAK_DATE,
	RESORT,
	LEAD_TIME_DAY,
	ACTUAL_DATE,
	CUMULATIVE_BUDGET_GROSS_ROOMS_SOLD,
	CUMULATIVE_BUDGET_NET_ADDONS,
	CUMULATIVE_BUDGET_NET_DINING,
	CUMULATIVE_BUDGET_NET_RICHCORE,
	CUMULATIVE_BUDGET_NET_ROOMS_SOLD,
	CUMULATIVE_BUDGET_NET_SILVER_PRICE,
	LAST7_DAY_BUDGET_GROSS_ROOMS_SOLD,
	LAST7_DAY_BUDGET_NET_ADDONS,
	LAST7_DAY_BUDGET_NET_DINING,
	LAST7_DAY_BUDGET_NET_RICHCORE,
	LAST7_DAY_BUDGET_NET_ROOMS_SOLD,
	LAST7_DAY_BUDGET_NET_SILVER_PRICE,
	LAST28_DAY_BUDGET_GROSS_ROOMS_SOLD,
	LAST28_DAY_BUDGET_NET_ADDONS,
	LAST28_DAY_BUDGET_NET_DINING,
	LAST28_DAY_BUDGET_NET_RICHCORE,
	LAST28_DAY_BUDGET_NET_ROOMS_SOLD,
	LAST28_DAY_BUDGET_NET_SILVER_PRICE
) as SELECT SOURCE, BREAK_DATE, RESORT, LEAD_TIME_DAY, ACTUAL_DATE, CUMULATIVE_BUDGET_GROSS_ROOMS_SOLD, CUMULATIVE_BUDGET_NET_ADDONS, CUMULATIVE_BUDGET_NET_DINING, CUMULATIVE_BUDGET_NET_RICHCORE, CUMULATIVE_BUDGET_NET_ROOMS_SOLD, CUMULATIVE_BUDGET_NET_SILVER_PRICE, LAST7_DAY_BUDGET_GROSS_ROOMS_SOLD, LAST7_DAY_BUDGET_NET_ADDONS, LAST7_DAY_BUDGET_NET_DINING, LAST7_DAY_BUDGET_NET_RICHCORE, LAST7_DAY_BUDGET_NET_ROOMS_SOLD, LAST7_DAY_BUDGET_NET_SILVER_PRICE, LAST28_DAY_BUDGET_GROSS_ROOMS_SOLD, LAST28_DAY_BUDGET_NET_ADDONS, LAST28_DAY_BUDGET_NET_DINING, LAST28_DAY_BUDGET_NET_RICHCORE, LAST28_DAY_BUDGET_NET_ROOMS_SOLD, LAST28_DAY_BUDGET_NET_SILVER_PRICE
FROM HAVEN_STORE.OCANDC.OCC_BUDGET;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_BY_ARRIVAL_DATE_FILL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_BY_ARRIVAL_DATE_FILL(
	BREAK_DATE,
	SHIP_CODE,
	SOURCE,
	ACTUAL_AVERAGED_NET_PRICE,
	ACTUAL_GW,
	ACTUAL_NET_ADDONS,
	ACTUAL_NET_DINING,
	ACTUAL_NET_RICHCORE,
	ACTUAL_NET_ROOMS_SOLD,
	ACTUAL_NET_TARIFF,
	LAST_SALES_DATE,
	MONDAY_DATE,
	GROSS_ROOMS_SOLD_7DAYS,
	GROSS_RICHCORE_7DAYS,
	GROSS_ROOMS_SOLD_14DAYS,
	GROSS_RICHCORE_14DAYS,
	GROSS_ROOMS_SOLD_28DAYS,
	GROSS_RICHCORE_28DAYS,
	NET_ROOMS_SOLD_7DAYS,
	NET_RICHCORE_7DAYS,
	NET_ADDONS_7DAYS,
	NET_DINING_7DAYS,
	NET_ROOMS_SOLD_14DAYS,
	NET_RICHCORE_14DAYS,
	NET_ROOMS_SOLD_28DAYS,
	NET_RICHCORE_28DAYS,
	PRICE_CHANGED_BY,
	LAST_PRICE_CHANGE_DATE,
	LAST_PRICE,
	GROSS_TARIFF_LAST_PRICECHANGE,
	GROSS_RICHCORE_LAST_PRICECHANGE,
	GROSS_ROOMS_SOLD_LAST_PRICECHANGE,
	PERIOD,
	AVAILABLE_ROOMS,
	TODAY_LY_INVOICE,
	TODAY_LY_RICHCORE,
	TODAY_LY_DINING,
	TODAY_LY_ADDONS,
	TODAY_LY_ROOMS_SOLD,
	TODAY_LY_GW,
	TARGET_CURRENT_SILVER_PRICE,
	TARGET_NET_TARIFF,
	TARGET_AVERAGED_NET_PRICE,
	TARGET_NET_ADDONS,
	TARGET_7DAY_NET_ADDONS,
	TARGET_14DAY_NET_ADDONS,
	TARGET_28DAY_NET_ADDONS,
	TARGET_NEXT7DAY_NET_ADDONS,
	TARGET_NEXT14DAY_NET_ADDONS,
	TARGET_NEXT28DAY_NET_ADDONS,
	TARGET_NET_DINING,
	TARGET_7DAY_NET_DINING,
	TARGET_14DAY_NET_DINING,
	TARGET_28DAY_NET_DINING,
	TARGET_NEXT7DAY_NET_DINING,
	TARGET_NEXT14DAY_NET_DINING,
	TARGET_NEXT28DAY_NET_DINING,
	TARGET_NET_RICHCORE,
	TARGET_7DAY_NET_RICHCORE,
	TARGET_14DAY_NET_RICHCORE,
	TARGET_28DAY_NET_RICHCORE,
	TARGET_NEXT7DAY_NET_RICHCORE,
	TARGET_NEXT14DAY_NET_RICHCORE,
	TARGET_NEXT28DAY_NET_RICHCORE,
	TARGET_CUMULATIVE_NET_ROOMS,
	TARGET_7DAY_NET_ROS,
	TARGET_14DAY_NET_ROS,
	TARGET_28DAY_NET_ROS,
	TARGET_NEXT7DAY_NET_ROS,
	TARGET_NEXT14DAY_NET_ROS,
	TARGET_NEXT28DAY_NET_ROS,
	TARGET_CUMULATIVE_GROSS_ROOMS,
	TARGET_7DAY_GROSS_ROS,
	TARGET_14DAY_GROSS_ROS,
	TARGET_28DAY_GROSS_ROS,
	TARGET_NEXT7DAY_GROSS_ROS,
	TARGET_NEXT14DAY_GROSS_ROS,
	TARGET_NEXT28DAY_GROSS_ROS,
	TARGET_GROSS_RICHCORE,
	TARGET_7DAY_GROSS_RICHCORE,
	TARGET_14DAY_GROSS_RICHCORE,
	TARGET_28DAY_GROSS_RICHCORE,
	TARGET_NEXT7DAY_GROSS_RICHCORE,
	TARGET_NEXT14DAY_GROSS_RICHCORE,
	TARGET_NEXT28DAY_GROSS_RICHCORE,
	REGION,
	TTL_BOOKINGS,
	TTL_SEARCHES,
	LAST28_BOOKINGS,
	LAST28_SEARCHES,
	LAST7_BOOKINGS,
	LAST7_SEARCHES,
	TTL_BOOKINGS_LY,
	TTL_SEARCHES_LY,
	LAST28_BOOKINGS_LY,
	LAST28_SEARCHES_LY,
	LAST7_BOOKINGS_LY,
	LAST7_SEARCHES_LY,
	CURRENT_PRICE,
	BROCHURE_PRICE_3OR4NIGHTS,
	BUDGET_NET_RICHCORE,
	CUMMULATIVE_BUDGET_NET_ROOMS_SOLD,
	CUMMULATIVE_BUDGET_NET_ADDONS,
	CUMMULATIVE_BUDGET_NET_DINING,
	CUMMULATIVE_BUDGET_GROSS_ROOMS_SOLD,
	FINAL_TOTAL_GROSS_BUDGET,
	FINAL_TOTAL_NET_BUDGET,
	FINAL_TOTAL_NET_BUDGETRICHCORE
) as SELECT BREAK_DATE, SHIP_CODE, SOURCE, ACTUAL_AVERAGED_NET_PRICE, ACTUAL_GW, ACTUAL_NET_ADDONS, ACTUAL_NET_DINING, ACTUAL_NET_RICHCORE, ACTUAL_NET_ROOMS_SOLD, ACTUAL_NET_TARIFF, LAST_SALES_DATE, MONDAY_DATE, GROSS_ROOMS_SOLD_7DAYS, GROSS_RICHCORE_7DAYS, GROSS_ROOMS_SOLD_14DAYS, GROSS_RICHCORE_14DAYS, GROSS_ROOMS_SOLD_28DAYS, GROSS_RICHCORE_28DAYS, NET_ROOMS_SOLD_7DAYS, NET_RICHCORE_7DAYS, NET_ADDONS_7DAYS, NET_DINING_7DAYS, NET_ROOMS_SOLD_14DAYS, NET_RICHCORE_14DAYS, NET_ROOMS_SOLD_28DAYS, NET_RICHCORE_28DAYS, PRICE_CHANGED_BY, LAST_PRICE_CHANGE_DATE, LAST_PRICE, GROSS_TARIFF_LAST_PRICECHANGE, GROSS_RICHCORE_LAST_PRICECHANGE, GROSS_ROOMS_SOLD_LAST_PRICECHANGE, PERIOD, AVAILABLE_ROOMS, TODAY_LY_INVOICE, TODAY_LY_RICHCORE, TODAY_LY_DINING, TODAY_LY_ADDONS, TODAY_LY_ROOMS_SOLD, TODAY_LY_GW, TARGET_CURRENT_SILVER_PRICE, TARGET_NET_TARIFF, TARGET_AVERAGED_NET_PRICE, TARGET_NET_ADDONS, TARGET_7DAY_NET_ADDONS, TARGET_14DAY_NET_ADDONS, TARGET_28DAY_NET_ADDONS, TARGET_NEXT7DAY_NET_ADDONS, TARGET_NEXT14DAY_NET_ADDONS, TARGET_NEXT28DAY_NET_ADDONS, TARGET_NET_DINING, TARGET_7DAY_NET_DINING, TARGET_14DAY_NET_DINING, TARGET_28DAY_NET_DINING, TARGET_NEXT7DAY_NET_DINING, TARGET_NEXT14DAY_NET_DINING, TARGET_NEXT28DAY_NET_DINING, TARGET_NET_RICHCORE, TARGET_7DAY_NET_RICHCORE, TARGET_14DAY_NET_RICHCORE, TARGET_28DAY_NET_RICHCORE, TARGET_NEXT7DAY_NET_RICHCORE, TARGET_NEXT14DAY_NET_RICHCORE, TARGET_NEXT28DAY_NET_RICHCORE, TARGET_CUMULATIVE_NET_ROOMS, TARGET_7DAY_NET_ROS, TARGET_14DAY_NET_ROS, TARGET_28DAY_NET_ROS, TARGET_NEXT7DAY_NET_ROS, TARGET_NEXT14DAY_NET_ROS, TARGET_NEXT28DAY_NET_ROS, TARGET_CUMULATIVE_GROSS_ROOMS, TARGET_7DAY_GROSS_ROS, TARGET_14DAY_GROSS_ROS, TARGET_28DAY_GROSS_ROS, TARGET_NEXT7DAY_GROSS_ROS, TARGET_NEXT14DAY_GROSS_ROS, TARGET_NEXT28DAY_GROSS_ROS, TARGET_GROSS_RICHCORE, TARGET_7DAY_GROSS_RICHCORE, TARGET_14DAY_GROSS_RICHCORE, TARGET_28DAY_GROSS_RICHCORE, TARGET_NEXT7DAY_GROSS_RICHCORE, TARGET_NEXT14DAY_GROSS_RICHCORE, TARGET_NEXT28DAY_GROSS_RICHCORE, REGION, TTL_BOOKINGS, TTL_SEARCHES, LAST28_BOOKINGS, LAST28_SEARCHES, LAST7_BOOKINGS, LAST7_SEARCHES, TTL_BOOKINGS_LY, TTL_SEARCHES_LY, LAST28_BOOKINGS_LY, LAST28_SEARCHES_LY, LAST7_BOOKINGS_LY, LAST7_SEARCHES_LY, CURRENT_PRICE, BROCHURE_PRICE_3OR4NIGHTS, BUDGET_NET_RICHCORE, CUMMULATIVE_BUDGET_NET_ROOMS_SOLD, CUMMULATIVE_BUDGET_NET_ADDONS, CUMMULATIVE_BUDGET_NET_DINING, CUMMULATIVE_BUDGET_GROSS_ROOMS_SOLD, FINAL_TOTAL_GROSS_BUDGET, FINAL_TOTAL_NET_BUDGET, FINAL_TOTAL_NET_BUDGETRICHCORE
FROM HAVEN_STORE.OCANDC.OCC_BY_ARRIVAL_DATE_FILL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_BREAK source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_BREAK(
	RESORT,
	BREAKDATE,
	MAX_CAPACITY
) as SELECT RESORT, BREAKDATE, MAX_CAPACITY
FROM HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_BREAK;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_BREAK_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_BREAK_REGIONAL(
	RESORT,
	BREAKDATE,
	MAX_CAPACITY
) as SELECT RESORT, BREAKDATE, MAX_CAPACITY
FROM HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_BREAK_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_GRADE_TYPE_BREAK source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_GRADE_TYPE_BREAK(
	RESORT,
	BREAKDATE,
	UNITGRADE,
	ROOMTYPE,
	MAX_CAPACITY,
	L2_CAPACITY
) as SELECT RESORT, BREAKDATE, UNITGRADE, ROOMTYPE, MAX_CAPACITY, L2_CAPACITY
FROM HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_GRADE_TYPE_BREAK;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_GRADE_TYPE_BREAK_CABIN source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_GRADE_TYPE_BREAK_CABIN(
	RESORT,
	BREAKDATE,
	CABINCATEGORY,
	MAX_CAPACITY,
	UNITGRADE,
	ROOMTYPE
) as SELECT RESORT, BREAKDATE, CABINCATEGORY, MAX_CAPACITY, UNITGRADE, ROOMTYPE
FROM HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_GRADE_TYPE_BREAK_CABIN;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_GRADE_TYPE_BREAK_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_CAPACITY_BY_GRADE_TYPE_BREAK_REGIONAL(
	RESORT,
	BREAKDATE,
	UNITGRADE,
	ROOMTYPE,
	MAX_CAPACITY,
	L2_CAPACITY
) as SELECT RESORT, BREAKDATE, UNITGRADE, ROOMTYPE, MAX_CAPACITY, L2_CAPACITY
FROM HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_GRADE_TYPE_BREAK_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_DENSE_INDEX source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_DENSE_INDEX(
	BREAK_DATE,
	LEAD_TIME_DAY,
	SHIP_CODE,
	SOURCE,
	ROOMTYPE,
	UNITGRADE
) as SELECT BREAK_DATE, LEAD_TIME_DAY, SHIP_CODE, SOURCE, ROOMTYPE, UNITGRADE
FROM HAVEN_STORE.OCANDC.OCC_DENSE_INDEX;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_DENSE_LEAD_TIME_DAY_WITH_BREAKS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_DENSE_LEAD_TIME_DAY_WITH_BREAKS(
	LEAD_TIME_DAY,
	BREAK_DATE,
	SHIP_CODE,
	SOURCE
) as SELECT LEAD_TIME_DAY, BREAK_DATE, SHIP_CODE, SOURCE
FROM HAVEN_STORE.OCANDC.OCC_DENSE_LEAD_TIME_DAY_WITH_BREAKS;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_DENSE_LEAD_TIME_DAY_WITH_BREAKS_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_DENSE_LEAD_TIME_DAY_WITH_BREAKS_REGIONAL(
	SHIP_CODE,
	SOURCE,
	BREAK_DATE,
	LEAD_TIME_DAY
) as SELECT SHIP_CODE, SOURCE, BREAK_DATE, LEAD_TIME_DAY
FROM HAVEN_STORE.OCANDC.OCC_DENSE_LEAD_TIME_DAY_WITH_BREAKS_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_GA_COMBINED source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_GA_COMBINED(
	RESORT,
	SEARCH_DATE,
	BREAK_DATE,
	LEAD_TIME_DAY,
	SEARCH_COUNT,
	BOOKING_COUNT,
	CONVERSION_RATE
) as SELECT RESORT, SEARCH_DATE, BREAK_DATE, LEAD_TIME_DAY, SEARCH_COUNT, BOOKING_COUNT, CONVERSION_RATE
FROM HAVEN_STORE.OCANDC.OCC_GA_COMBINED;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_GA_COMBINED_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_GA_COMBINED_REGIONAL(
	RESORT,
	SEARCH_DATE,
	BREAK_DATE,
	LEAD_TIME_DAY,
	SEARCH_COUNT,
	BOOKING_COUNT,
	CONVERSION_RATE
) as SELECT RESORT, SEARCH_DATE, BREAK_DATE, LEAD_TIME_DAY, SEARCH_COUNT, BOOKING_COUNT, CONVERSION_RATE
FROM HAVEN_STORE.OCANDC.OCC_GA_COMBINED_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_LAST_PRICE_CHANGE source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_LAST_PRICE_CHANGE(
	CENTRECODE,
	BREAKDATE_CURRENT,
	MONDAY_DATE,
	LAST_PRICE,
	BROCHURE_PRICE,
	LAST_PRICE_CHANGE_DATE,
	PRICE_CHANGED_BY
) as SELECT CENTRECODE, BREAKDATE_CURRENT, MONDAY_DATE, LAST_PRICE, BROCHURE_PRICE, LAST_PRICE_CHANGE_DATE, PRICE_CHANGED_BY
FROM HAVEN_STORE.OCANDC.OCC_LAST_PRICE_CHANGE;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_LAST_PRICE_CHANGE_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_LAST_PRICE_CHANGE_REGIONAL(
	CENTRECODE,
	BREAKDATE_CURRENT,
	MONDAY_DATE,
	LAST_PRICE,
	LAST_PRICE_CHANGE_DATE,
	PRICE_CHANGED_BY
) as SELECT CENTRECODE, BREAKDATE_CURRENT, MONDAY_DATE, LAST_PRICE, LAST_PRICE_CHANGE_DATE, PRICE_CHANGED_BY
FROM HAVEN_STORE.OCANDC.OCC_LAST_PRICE_CHANGE_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_LEAD_TIME_SEGMENTS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_LEAD_TIME_SEGMENTS(
	LEADTIMEWEEK,
	LEADTIMESEGMENT,
	ACTION_SEGMENTS
) as SELECT LEADTIMEWEEK, LEADTIMESEGMENT, ACTION_SEGMENTS
FROM HAVEN_STORE.OCANDC.OCC_LEAD_TIME_SEGMENTS;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_LETTING_BUDGET source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_LETTING_BUDGET(
	PARK,
	DATE,
	DURATION,
	LETTING_BUDGET,
	HIREFLEET_BUDGET
) as SELECT PARK, DATE, DURATION, LETTING_BUDGET, HIREFLEET_BUDGET
FROM HAVEN_STORE.OCANDC.OCC_LETTING_BUDGET;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_LETTINGS_FINAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_LETTINGS_FINAL(
	BREAK_DATE,
	SHIP_CODE,
	LEAD_TIME_DAY,
	LETTINGS,
	BOOKINGS,
	WAITLIST,
	DAILY_TARGET_NET_ROS,
	CHANGE_DATE,
	REGION,
	PERIOD,
	BUDGET,
	MARKETING_PERIOD,
	ACTUAL_DATE,
	CUMULATIVE_LETTINGS,
	CUMULATIVE_BOOKINGS,
	CUMULATIVE_WAITLIST,
	CUMULATIVE_TARGET_BOOKINGS,
	DATE_CURRENT,
	DAY_VALUE,
	SEASON,
	LEAD_TIME,
	LOWER_QUARTILE,
	MEDIAN,
	UPPER_QUARTILE,
	MEDIAN_0_25,
	MEDIAN_25_50,
	MEDIAN_50_75,
	MEDIAN_75_100,
	SD_0_25,
	DAY_OF_WEEK,
	CAPACITY
) as SELECT BREAK_DATE, SHIP_CODE, LEAD_TIME_DAY, LETTINGS, BOOKINGS, WAITLIST, DAILY_TARGET_NET_ROS, CHANGE_DATE, REGION, PERIOD, BUDGET, MARKETING_PERIOD, ACTUAL_DATE, CUMULATIVE_LETTINGS, CUMULATIVE_BOOKINGS, CUMULATIVE_WAITLIST, CUMULATIVE_TARGET_BOOKINGS, DATE_CURRENT, DAY_VALUE, SEASON, LEAD_TIME, LOWER_QUARTILE, MEDIAN, UPPER_QUARTILE, MEDIAN_0_25, MEDIAN_25_50, MEDIAN_50_75, MEDIAN_75_100, SD_0_25, DAY_OF_WEEK, CAPACITY
FROM HAVEN_STORE.OCANDC.OCC_LETTINGS_FINAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_LETTINGS_PROBABILITY_TABLE source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_LETTINGS_PROBABILITY_TABLE(
	DAY_VALUE,
	SEASON,
	LEAD_TIME,
	LOWER_QUARTILE,
	MEDIAN,
	UPPER_QUARTILE,
	MEDIAN_0_25,
	MEDIAN_25_50,
	MEDIAN_50_75,
	MEDIAN_75_100,
	SD_0_25
) as SELECT DAY_VALUE, SEASON, LEAD_TIME, LOWER_QUARTILE, MEDIAN, UPPER_QUARTILE, MEDIAN_0_25, MEDIAN_25_50, MEDIAN_50_75, MEDIAN_75_100, SD_0_25
FROM HAVEN_STORE.OCANDC.OCC_LETTINGS_PROBABILITY_TABLE;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_MARKETING_PERIOD_MAP source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_MARKETING_PERIOD_MAP(
	STAY_NIGHT,
	START_DT,
	END_DT,
	SEASON,
	PEAKFLAG,
	MARKETING_PERIOD
) as SELECT STAY_NIGHT, START_DT, END_DT, SEASON, PEAKFLAG, MARKETING_PERIOD
FROM HAVEN_STORE.OCANDC.OCC_MARKETING_PERIOD_MAP;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_NEW_CAPACITY source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_NEW_CAPACITY(
	RESORT,
	DATE_VALUE,
	AVAILABLE_ROOMS,
	SOURCE
) as SELECT RESORT, DATE_VALUE, AVAILABLE_ROOMS, SOURCE
FROM HAVEN_STORE.OCANDC.OCC_NEW_CAPACITY;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_NEW_CAPACITY_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_NEW_CAPACITY_REGIONAL(
	RESORT,
	DATE_VALUE,
	AVAILABLE_ROOMS,
	SOURCE
) as SELECT RESORT, DATE_VALUE, AVAILABLE_ROOMS, SOURCE
FROM HAVEN_STORE.OCANDC.OCC_NEW_CAPACITY_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_PRICE_CHANGE_CLEAN source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_PRICE_CHANGE_CLEAN(
	SITECODE,
	BREAKDATE,
	DATADATE,
	ROOMTYPE,
	UNITGRADE,
	OFFER,
	BROCHURE
) as SELECT SITECODE, BREAKDATE, DATADATE, ROOMTYPE, UNITGRADE, OFFER, BROCHURE
FROM HAVEN_STORE.OCANDC.OCC_PRICE_CHANGE_CLEAN;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_PRICE_CHANGE_CLEAN_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_PRICE_CHANGE_CLEAN_REGIONAL(
	SITECODE,
	BREAKDATE,
	DATADATE,
	ROOMTYPE,
	UNITGRADE,
	OFFER
) as SELECT SITECODE, BREAKDATE, DATADATE, ROOMTYPE, UNITGRADE, OFFER
FROM HAVEN_STORE.OCANDC.OCC_PRICE_CHANGE_CLEAN_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_PRICE_SILVER_APARTMENTS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_PRICE_SILVER_APARTMENTS(
	DATADATE,
	SITECODE,
	BREAKDATE,
	DURATION,
	GRADE,
	BERTH,
	OFFER,
	BROCHURE,
	ROOMTYPE,
	UNITGRADE,
	LEAD_TIME_DAY,
	LEAD_TIME_DAY_PRICES,
	OFFER_PRICE_7NIGHTS,
	OFFER_PRICE_3OR4NIGHTS,
	BROCHURE_PRICE_3OR4NIGHTS
) as SELECT DATADATE, SITECODE, BREAKDATE, DURATION, GRADE, BERTH, OFFER, BROCHURE, ROOMTYPE, UNITGRADE, LEAD_TIME_DAY, LEAD_TIME_DAY_PRICES, OFFER_PRICE_7NIGHTS, OFFER_PRICE_3OR4NIGHTS, BROCHURE_PRICE_3OR4NIGHTS
FROM HAVEN_STORE.OCANDC.OCC_PRICE_SILVER_APARTMENTS;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_PRICE_SILVER_APARTMENTS_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_PRICE_SILVER_APARTMENTS_REGIONAL(
	SITECODE,
	BREAKDATE,
	DATADATE,
	GRADE,
	BERTH,
	DURATION,
	ROOMTYPE,
	UNITGRADE,
	OFFER,
	LEAD_TIME_DAY,
	LEAD_TIME_DAY_PRICES,
	OFFER_PRICE_7NIGHTS,
	OFFER_PRICE_3OR4NIGHTS
) as SELECT SITECODE, BREAKDATE, DATADATE, GRADE, BERTH, DURATION, ROOMTYPE, UNITGRADE, OFFER, LEAD_TIME_DAY, LEAD_TIME_DAY_PRICES, OFFER_PRICE_7NIGHTS, OFFER_PRICE_3OR4NIGHTS
FROM HAVEN_STORE.OCANDC.OCC_PRICE_SILVER_APARTMENTS_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_REGION_AGGREGATION source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_REGION_AGGREGATION(
	REGION,
	LEADTIMESEGMENT,
	PARK
) as SELECT REGION, LEADTIMESEGMENT, PARK
FROM HAVEN_STORE.OCANDC.OCC_REGION_AGGREGATION;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_RM_ALL_CUTS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_RM_ALL_CUTS(
	CENTRECODE,
	BREAK_DATE,
	SOURCE,
	CHANNEL,
	HOLIDAY_DURATION,
	MAXOCCUPANCY,
	RICHCORE,
	ADDONS,
	DINING,
	NO_BOOKINGS,
	TABLEAU_COLUMN
) as SELECT CENTRECODE, BREAK_DATE, SOURCE, CHANNEL, HOLIDAY_DURATION, MAXOCCUPANCY, RICHCORE, ADDONS, DINING, NO_BOOKINGS, TABLEAU_COLUMN
FROM HAVEN_STORE.OCANDC.OCC_RM_ALL_CUTS;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_RM_ALL_CUTS_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_RM_ALL_CUTS_REGIONAL(
	CENTRECODE,
	BREAK_DATE,
	SOURCE,
	CHANNEL,
	HOLIDAY_DURATION,
	MAXOCCUPANCY,
	RICHCORE,
	ADDONS,
	DINING,
	NO_BOOKINGS,
	TABLEAU_COLUMN
) as SELECT CENTRECODE, BREAK_DATE, SOURCE, CHANNEL, HOLIDAY_DURATION, MAXOCCUPANCY, RICHCORE, ADDONS, DINING, NO_BOOKINGS, TABLEAU_COLUMN
FROM HAVEN_STORE.OCANDC.OCC_RM_ALL_CUTS_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_ROOM_TYPE_LOOKUP source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_ROOM_TYPE_LOOKUP(
	ACCOM_CODE,
	BRAND,
	PRODUCT_DESCRIPTION,
	ROOMTYPE,
	ACCOM_GROUP,
	UNITGRADE,
	GRADE_NUMBER,
	CHECK_IN_TIME,
	BEDROOMS,
	MAXGUESTS,
	DISABLED_YN,
	SUN_CHECK_IN_TIME,
	ACTIVE_ON_SEAWARE,
	VALID_FROM_DT,
	VALID_TO_DT
) as SELECT ACCOM_CODE, BRAND, PRODUCT_DESCRIPTION, ROOMTYPE, ACCOM_GROUP, UNITGRADE, GRADE_NUMBER, CHECK_IN_TIME, BEDROOMS, MAXGUESTS, DISABLED_YN, SUN_CHECK_IN_TIME, ACTIVE_ON_SEAWARE, VALID_FROM_DT, VALID_TO_DT
FROM HAVEN_STORE.OCANDC.OCC_ROOM_TYPE_LOOKUP;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_FINAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_FINAL(
	BREAK_DATE,
	SHIP_CODE,
	LEAD_TIME_DAY,
	SOURCE,
	REPTGYEAR,
	RES_ID,
	GROUP_ID,
	CHANNEL,
	ORIGINAL_SOURCE,
	AGENCY_NAME,
	CABIN_CATEGORY,
	RES_INIT_DATE,
	CANCELLATION_DATE,
	SAIL_FROM_DATE,
	HOLIDAY_DURATION,
	DAYS_IN_BREAK,
	REFERRAL_CODE,
	BOOKING_STATUS,
	RES_GUEST_COUNT,
	UNIT_ALLOCATED,
	INVOICE_TOTAL,
	DISCOUNTS,
	DINING_TARIFF,
	ADDON_TARIFF,
	RICH_CORE,
	BREAK_END,
	SAIL_END,
	OFFER_PRICE_3OR4NIGHTS,
	BROCHURE_PRICE_3OR4NIGHTS,
	OFFER_PRICE_7NIGHTS,
	LAST_PRICE,
	LAST_PRICE_CHANGE_DATE,
	PRICE_CHANGED_BY,
	CENTRECODE,
	PERIOD,
	BREAKDATE_CURRENT,
	BREAKDATE_FUTURE,
	BREAKDATE_PRIOR,
	RESORT,
	UNITTYPE,
	UNITGRADE,
	ROOMTYPE,
	NRBEDROOMS,
	MAXOCCUPANCY,
	EDITED_HOLIDAY_DURATION,
	BOOKING_COUNT,
	GW,
	REGION,
	LY_FINAL_TARIFF,
	LY_FINAL_RICHCORE,
	LY_FINAL_DINING,
	LY_FINAL_ADDONS,
	LY_FINAL_ROOMS_SOLD,
	LY_FINAL_CUMULATIVE_TARIFF,
	LY_FINAL_CUMULATIVE_RICHCORE,
	LY_FINAL_CUMULATIVE_DINING,
	LY_FINAL_CUMULATIVE_ADDONS,
	LY_FINAL_CUMULATIVE_ROOMS_SOLD,
	LY_FINAL_CUMULATIVE_TARIFF_SILVER_APT,
	LY_FINAL_CUMULATIVE_RICHCORE_SILVER_APT,
	LY_FINAL_CUMULATIVE_DINING_SILVER_APT,
	LY_FINAL_CUMULATIVE_ADDONS_SILVER_APT,
	LY_FINAL_CUMULATIVE_ROOMS_SOLD_SILVER_APT,
	LY_LAST7DAYS_TARIFF,
	LY_LAST7DAYS_RICHCORE,
	LY_LAST7DAYS_NET_ROOMS_SOLD,
	LY_LAST7DAYS_GW,
	LY_LAST28DAYS_TARIFF,
	LY_LAST28DAYS_RICHCORE,
	LY_LAST28DAYS_NET_ROOMS_SOLD,
	LY_LAST28DAYS_GW,
	LY_TODATE_TARIFF,
	LY_TODATE_RICHCORE,
	LY_TODATE_DINING,
	LY_TODATE_ADDONS,
	LY_TODATE_ROOMS_SOLD,
	DAILY_TARGET_NET_ROS,
	DAILY_TARGET_GROSS_ROS,
	DAILY_TARGET_NET_ADDONS,
	DAILY_TARGET_NET_DINING,
	DAILY_TARGET_COMPOSITE_PRICE,
	DAILY_TARGET_NET_RICHCORE,
	DAILY_TARGET_SILVER_PRICE,
	CUMULATIVE_TARGET_NET_ADDONS,
	LAST7_DAY_TARGET_NET_ADDONS,
	LAST14_DAY_TARGET_NET_ADDONS,
	LAST28_DAY_TARGET_NET_ADDONS,
	NEXT7_DAY_TARGET_NET_ADDONS,
	NEXT14_DAY_TARGET_NET_ADDONS,
	NEXT28_DAY_TARGET_NET_ADDONS,
	CUMULATIVE_TARGET_NET_DINING,
	LAST7_DAY_TARGET_NET_DINING,
	LAST14_DAY_TARGET_NET_DINING,
	LAST28_DAY_TARGET_NET_DINING,
	NEXT7_DAY_TARGET_NET_DINING,
	NEXT14_DAY_TARGET_NET_DINING,
	NEXT28_DAY_TARGET_NET_DINING,
	CUMULATIVE_TARGET_NET_RICHCORE,
	LAST7_DAY_TARGET_NET_RICHCORE,
	LAST14_DAY_TARGET_NET_RICHCORE,
	LAST28_DAY_TARGET_NET_RICHCORE,
	NEXT7_DAY_TARGET_NET_RICHCORE,
	NEXT14_DAY_TARGET_NET_RICHCORE,
	NEXT28_DAY_TARGET_NET_RICHCORE,
	CUMULATIVE_TARGET_NET_ROOMS_SOLD,
	LAST7_DAY_TARGET_NET_ROOMS_SOLD,
	LAST14_DAY_TARGET_NET_ROOMS_SOLD,
	LAST28_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT7_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT14_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT28_DAY_TARGET_NET_ROOMS_SOLD,
	CUMULATIVE_TARGET_GROSS_ROOMS_SOLD,
	LAST7_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST14_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST28_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD,
	CUMULATIVE_TARGET_NET_SILVER_PRICE,
	LAST7_DAY_TARGET_NET_SILVER_PRICE,
	LAST14_DAY_TARGET_NET_SILVER_PRICE,
	LAST28_DAY_TARGET_NET_SILVER_PRICE,
	NEXT7_DAY_TARGET_NET_SILVER_PRICE,
	NEXT14_DAY_TARGET_NET_SILVER_PRICE,
	NEXT28_DAY_TARGET_NET_SILVER_PRICE,
	CABIN_CATEGORY_LIST_PRICE,
	BROCHURE
) as SELECT BREAK_DATE, SHIP_CODE, LEAD_TIME_DAY, SOURCE, REPTGYEAR, RES_ID, GROUP_ID, CHANNEL, ORIGINAL_SOURCE, AGENCY_NAME, CABIN_CATEGORY, RES_INIT_DATE, CANCELLATION_DATE, SAIL_FROM_DATE, HOLIDAY_DURATION, DAYS_IN_BREAK, REFERRAL_CODE, BOOKING_STATUS, RES_GUEST_COUNT, UNIT_ALLOCATED, INVOICE_TOTAL, DISCOUNTS, DINING_TARIFF, ADDON_TARIFF, RICH_CORE, BREAK_END, SAIL_END, OFFER_PRICE_3OR4NIGHTS, BROCHURE_PRICE_3OR4NIGHTS, OFFER_PRICE_7NIGHTS, LAST_PRICE, LAST_PRICE_CHANGE_DATE, PRICE_CHANGED_BY, CENTRECODE, PERIOD, BREAKDATE_CURRENT, BREAKDATE_FUTURE, BREAKDATE_PRIOR, RESORT, UNITTYPE, UNITGRADE, ROOMTYPE, NRBEDROOMS, MAXOCCUPANCY, EDITED_HOLIDAY_DURATION, BOOKING_COUNT, GW, REGION, LY_FINAL_TARIFF, LY_FINAL_RICHCORE, LY_FINAL_DINING, LY_FINAL_ADDONS, LY_FINAL_ROOMS_SOLD, LY_FINAL_CUMULATIVE_TARIFF, LY_FINAL_CUMULATIVE_RICHCORE, LY_FINAL_CUMULATIVE_DINING, LY_FINAL_CUMULATIVE_ADDONS, LY_FINAL_CUMULATIVE_ROOMS_SOLD, LY_FINAL_CUMULATIVE_TARIFF_SILVER_APT, LY_FINAL_CUMULATIVE_RICHCORE_SILVER_APT, LY_FINAL_CUMULATIVE_DINING_SILVER_APT, LY_FINAL_CUMULATIVE_ADDONS_SILVER_APT, LY_FINAL_CUMULATIVE_ROOMS_SOLD_SILVER_APT, LY_LAST7DAYS_TARIFF, LY_LAST7DAYS_RICHCORE, LY_LAST7DAYS_NET_ROOMS_SOLD, LY_LAST7DAYS_GW, LY_LAST28DAYS_TARIFF, LY_LAST28DAYS_RICHCORE, LY_LAST28DAYS_NET_ROOMS_SOLD, LY_LAST28DAYS_GW, LY_TODATE_TARIFF, LY_TODATE_RICHCORE, LY_TODATE_DINING, LY_TODATE_ADDONS, LY_TODATE_ROOMS_SOLD, DAILY_TARGET_NET_ROS, DAILY_TARGET_GROSS_ROS, DAILY_TARGET_NET_ADDONS, DAILY_TARGET_NET_DINING, DAILY_TARGET_COMPOSITE_PRICE, DAILY_TARGET_NET_RICHCORE, DAILY_TARGET_SILVER_PRICE, CUMULATIVE_TARGET_NET_ADDONS, LAST7_DAY_TARGET_NET_ADDONS, LAST14_DAY_TARGET_NET_ADDONS, LAST28_DAY_TARGET_NET_ADDONS, NEXT7_DAY_TARGET_NET_ADDONS, NEXT14_DAY_TARGET_NET_ADDONS, NEXT28_DAY_TARGET_NET_ADDONS, CUMULATIVE_TARGET_NET_DINING, LAST7_DAY_TARGET_NET_DINING, LAST14_DAY_TARGET_NET_DINING, LAST28_DAY_TARGET_NET_DINING, NEXT7_DAY_TARGET_NET_DINING, NEXT14_DAY_TARGET_NET_DINING, NEXT28_DAY_TARGET_NET_DINING, CUMULATIVE_TARGET_NET_RICHCORE, LAST7_DAY_TARGET_NET_RICHCORE, LAST14_DAY_TARGET_NET_RICHCORE, LAST28_DAY_TARGET_NET_RICHCORE, NEXT7_DAY_TARGET_NET_RICHCORE, NEXT14_DAY_TARGET_NET_RICHCORE, NEXT28_DAY_TARGET_NET_RICHCORE, CUMULATIVE_TARGET_NET_ROOMS_SOLD, LAST7_DAY_TARGET_NET_ROOMS_SOLD, LAST14_DAY_TARGET_NET_ROOMS_SOLD, LAST28_DAY_TARGET_NET_ROOMS_SOLD, NEXT7_DAY_TARGET_NET_ROOMS_SOLD, NEXT14_DAY_TARGET_NET_ROOMS_SOLD, NEXT28_DAY_TARGET_NET_ROOMS_SOLD, CUMULATIVE_TARGET_GROSS_ROOMS_SOLD, LAST7_DAY_TARGET_GROSS_ROOMS_SOLD, LAST14_DAY_TARGET_GROSS_ROOMS_SOLD, LAST28_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD, CUMULATIVE_TARGET_NET_SILVER_PRICE, LAST7_DAY_TARGET_NET_SILVER_PRICE, LAST14_DAY_TARGET_NET_SILVER_PRICE, LAST28_DAY_TARGET_NET_SILVER_PRICE, NEXT7_DAY_TARGET_NET_SILVER_PRICE, NEXT14_DAY_TARGET_NET_SILVER_PRICE, NEXT28_DAY_TARGET_NET_SILVER_PRICE, CABIN_CATEGORY_LIST_PRICE, BROCHURE
FROM HAVEN_STORE.OCANDC.OCC_SALES_CUBE_FINAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_FINAL_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_FINAL_REGIONAL(
	BREAK_DATE,
	SHIP_CODE,
	LEAD_TIME_DAY,
	SOURCE,
	REPTGYEAR,
	CHANNEL,
	CABIN_CATEGORY,
	RES_INIT_DATE,
	CANCELLATION_DATE,
	SAIL_FROM_DATE,
	HOLIDAY_DURATION,
	DAYS_IN_BREAK,
	BOOKING_STATUS,
	RES_GUEST_COUNT,
	UNIT_ALLOCATED,
	BREAK_END,
	SAIL_END,
	CENTRECODE,
	PERIOD,
	BREAKDATE_CURRENT,
	BREAKDATE_PRIOR,
	RESORT,
	UNITTYPE,
	UNITGRADE,
	ROOMTYPE,
	NRBEDROOMS,
	MAXOCCUPANCY,
	EDITED_HOLIDAY_DURATION,
	REGION,
	LAST_PRICE,
	LAST_PRICE_CHANGE_DATE,
	PRICE_CHANGED_BY,
	OFFER_PRICE_3OR4NIGHTS,
	OFFER_PRICE_7NIGHTS,
	DAILY_TARGET_SILVER_PRICE,
	DAILY_TARGET_COMPOSITE_PRICE,
	CUMULATIVE_TARGET_NET_SILVER_PRICE,
	LAST7_DAY_TARGET_NET_SILVER_PRICE,
	LAST14_DAY_TARGET_NET_SILVER_PRICE,
	LAST28_DAY_TARGET_NET_SILVER_PRICE,
	NEXT7_DAY_TARGET_NET_SILVER_PRICE,
	NEXT14_DAY_TARGET_NET_SILVER_PRICE,
	NEXT28_DAY_TARGET_NET_SILVER_PRICE,
	DAILY_TARGET_NET_ROS,
	DAILY_TARGET_GROSS_ROS,
	DAILY_TARGET_NET_ADDONS,
	DAILY_TARGET_NET_DINING,
	DAILY_TARGET_NET_RICHCORE,
	CUMULATIVE_TARGET_NET_ADDONS,
	LAST7_DAY_TARGET_NET_ADDONS,
	LAST14_DAY_TARGET_NET_ADDONS,
	LAST28_DAY_TARGET_NET_ADDONS,
	NEXT7_DAY_TARGET_NET_ADDONS,
	NEXT14_DAY_TARGET_NET_ADDONS,
	NEXT28_DAY_TARGET_NET_ADDONS,
	CUMULATIVE_TARGET_NET_DINING,
	LAST7_DAY_TARGET_NET_DINING,
	LAST14_DAY_TARGET_NET_DINING,
	LAST28_DAY_TARGET_NET_DINING,
	NEXT7_DAY_TARGET_NET_DINING,
	NEXT14_DAY_TARGET_NET_DINING,
	NEXT28_DAY_TARGET_NET_DINING,
	CUMULATIVE_TARGET_NET_RICHCORE,
	LAST7_DAY_TARGET_NET_RICHCORE,
	LAST14_DAY_TARGET_NET_RICHCORE,
	LAST28_DAY_TARGET_NET_RICHCORE,
	NEXT7_DAY_TARGET_NET_RICHCORE,
	NEXT14_DAY_TARGET_NET_RICHCORE,
	NEXT28_DAY_TARGET_NET_RICHCORE,
	CUMULATIVE_TARGET_NET_ROOMS_SOLD,
	LAST7_DAY_TARGET_NET_ROOMS_SOLD,
	LAST14_DAY_TARGET_NET_ROOMS_SOLD,
	LAST28_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT7_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT14_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT28_DAY_TARGET_NET_ROOMS_SOLD,
	CUMULATIVE_TARGET_GROSS_ROOMS_SOLD,
	LAST7_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST14_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST28_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD,
	BOOKING_COUNT,
	GW,
	INVOICE_TOTAL,
	DISCOUNTS,
	DINING_TARIFF,
	ADDON_TARIFF,
	RICH_CORE,
	LY_FINAL_TARIFF,
	LY_FINAL_RICHCORE,
	LY_FINAL_DINING,
	LY_FINAL_ADDONS,
	LY_FINAL_ROOMS_SOLD,
	LY_FINAL_CUMULATIVE_TARIFF,
	LY_FINAL_CUMULATIVE_RICHCORE,
	LY_FINAL_CUMULATIVE_DINING,
	LY_FINAL_CUMULATIVE_ADDONS,
	LY_FINAL_CUMULATIVE_ROOMS_SOLD,
	LY_FINAL_CUMULATIVE_TARIFF_SILVER_APT,
	LY_FINAL_CUMULATIVE_RICHCORE_SILVER_APT,
	LY_FINAL_CUMULATIVE_DINING_SILVER_APT,
	LY_FINAL_CUMULATIVE_ADDONS_SILVER_APT,
	LY_FINAL_CUMULATIVE_ROOMS_SOLD_SILVER_APT,
	LY_LAST7DAYS_TARIFF,
	LY_LAST7DAYS_RICHCORE,
	LY_LAST7DAYS_NET_ROOMS_SOLD,
	LY_LAST7DAYS_GW,
	LY_LAST28DAYS_TARIFF,
	LY_LAST28DAYS_RICHCORE,
	LY_LAST28DAYS_NET_ROOMS_SOLD,
	LY_LAST28DAYS_GW,
	LY_TODATE_TARIFF,
	LY_TODATE_RICHCORE,
	LY_TODATE_DINING,
	LY_TODATE_ADDONS,
	LY_TODATE_ROOMS_SOLD
) as SELECT BREAK_DATE, SHIP_CODE, LEAD_TIME_DAY, SOURCE, REPTGYEAR, CHANNEL, CABIN_CATEGORY, RES_INIT_DATE, CANCELLATION_DATE, SAIL_FROM_DATE, HOLIDAY_DURATION, DAYS_IN_BREAK, BOOKING_STATUS, RES_GUEST_COUNT, UNIT_ALLOCATED, BREAK_END, SAIL_END, CENTRECODE, PERIOD, BREAKDATE_CURRENT, BREAKDATE_PRIOR, RESORT, UNITTYPE, UNITGRADE, ROOMTYPE, NRBEDROOMS, MAXOCCUPANCY, EDITED_HOLIDAY_DURATION, REGION, LAST_PRICE, LAST_PRICE_CHANGE_DATE, PRICE_CHANGED_BY, OFFER_PRICE_3OR4NIGHTS, OFFER_PRICE_7NIGHTS, DAILY_TARGET_SILVER_PRICE, DAILY_TARGET_COMPOSITE_PRICE, CUMULATIVE_TARGET_NET_SILVER_PRICE, LAST7_DAY_TARGET_NET_SILVER_PRICE, LAST14_DAY_TARGET_NET_SILVER_PRICE, LAST28_DAY_TARGET_NET_SILVER_PRICE, NEXT7_DAY_TARGET_NET_SILVER_PRICE, NEXT14_DAY_TARGET_NET_SILVER_PRICE, NEXT28_DAY_TARGET_NET_SILVER_PRICE, DAILY_TARGET_NET_ROS, DAILY_TARGET_GROSS_ROS, DAILY_TARGET_NET_ADDONS, DAILY_TARGET_NET_DINING, DAILY_TARGET_NET_RICHCORE, CUMULATIVE_TARGET_NET_ADDONS, LAST7_DAY_TARGET_NET_ADDONS, LAST14_DAY_TARGET_NET_ADDONS, LAST28_DAY_TARGET_NET_ADDONS, NEXT7_DAY_TARGET_NET_ADDONS, NEXT14_DAY_TARGET_NET_ADDONS, NEXT28_DAY_TARGET_NET_ADDONS, CUMULATIVE_TARGET_NET_DINING, LAST7_DAY_TARGET_NET_DINING, LAST14_DAY_TARGET_NET_DINING, LAST28_DAY_TARGET_NET_DINING, NEXT7_DAY_TARGET_NET_DINING, NEXT14_DAY_TARGET_NET_DINING, NEXT28_DAY_TARGET_NET_DINING, CUMULATIVE_TARGET_NET_RICHCORE, LAST7_DAY_TARGET_NET_RICHCORE, LAST14_DAY_TARGET_NET_RICHCORE, LAST28_DAY_TARGET_NET_RICHCORE, NEXT7_DAY_TARGET_NET_RICHCORE, NEXT14_DAY_TARGET_NET_RICHCORE, NEXT28_DAY_TARGET_NET_RICHCORE, CUMULATIVE_TARGET_NET_ROOMS_SOLD, LAST7_DAY_TARGET_NET_ROOMS_SOLD, LAST14_DAY_TARGET_NET_ROOMS_SOLD, LAST28_DAY_TARGET_NET_ROOMS_SOLD, NEXT7_DAY_TARGET_NET_ROOMS_SOLD, NEXT14_DAY_TARGET_NET_ROOMS_SOLD, NEXT28_DAY_TARGET_NET_ROOMS_SOLD, CUMULATIVE_TARGET_GROSS_ROOMS_SOLD, LAST7_DAY_TARGET_GROSS_ROOMS_SOLD, LAST14_DAY_TARGET_GROSS_ROOMS_SOLD, LAST28_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD, NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD, BOOKING_COUNT, GW, INVOICE_TOTAL, DISCOUNTS, DINING_TARIFF, ADDON_TARIFF, RICH_CORE, LY_FINAL_TARIFF, LY_FINAL_RICHCORE, LY_FINAL_DINING, LY_FINAL_ADDONS, LY_FINAL_ROOMS_SOLD, LY_FINAL_CUMULATIVE_TARIFF, LY_FINAL_CUMULATIVE_RICHCORE, LY_FINAL_CUMULATIVE_DINING, LY_FINAL_CUMULATIVE_ADDONS, LY_FINAL_CUMULATIVE_ROOMS_SOLD, LY_FINAL_CUMULATIVE_TARIFF_SILVER_APT, LY_FINAL_CUMULATIVE_RICHCORE_SILVER_APT, LY_FINAL_CUMULATIVE_DINING_SILVER_APT, LY_FINAL_CUMULATIVE_ADDONS_SILVER_APT, LY_FINAL_CUMULATIVE_ROOMS_SOLD_SILVER_APT, LY_LAST7DAYS_TARIFF, LY_LAST7DAYS_RICHCORE, LY_LAST7DAYS_NET_ROOMS_SOLD, LY_LAST7DAYS_GW, LY_LAST28DAYS_TARIFF, LY_LAST28DAYS_RICHCORE, LY_LAST28DAYS_NET_ROOMS_SOLD, LY_LAST28DAYS_GW, LY_TODATE_TARIFF, LY_TODATE_RICHCORE, LY_TODATE_DINING, LY_TODATE_ADDONS, LY_TODATE_ROOMS_SOLD
FROM HAVEN_STORE.OCANDC.OCC_SALES_CUBE_FINAL_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_LY_TOTAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_LY_TOTAL(
	SHIP_CODE,
	BREAK_DATE,
	LEAD_TIME_DAY,
	SOURCE,
	LY_FINAL_TARIFF,
	LY_FINAL_RICHCORE,
	LY_FINAL_DINING,
	LY_FINAL_ADDONS,
	LY_FINAL_ROOMS_SOLD,
	LY_FINAL_GW,
	LY_FINAL_GROSS_TARIFF,
	LY_FINAL_GROSS_RICHCORE,
	LY_FINAL_GROSS_DINING,
	LY_FINAL_GROSS_ADDONS,
	LY_FINAL_GROSS_ROOMS_SOLD,
	LY_FINAL_GROSS_GW,
	LY_FINAL_CUMULATIVE_TARIFF,
	LY_FINAL_CUMULATIVE_RICHCORE,
	LY_FINAL_CUMULATIVE_DINING,
	LY_FINAL_CUMULATIVE_ADDONS,
	LY_FINAL_CUMULATIVE_ROOMS_SOLD,
	LY_FINAL_CUMULATIVE_GW,
	LY_LAST7DAYS_TARIFF,
	LY_LAST7DAYS_RICHCORE,
	LY_LAST7DAYS_NET_ROOMS_SOLD,
	LY_LAST7DAYS_GW,
	LY_LAST28DAYS_TARIFF,
	LY_LAST28DAYS_RICHCORE,
	LY_LAST28DAYS_NET_ROOMS_SOLD,
	LY_LAST28DAYS_GW
) as SELECT SHIP_CODE, BREAK_DATE, LEAD_TIME_DAY, SOURCE, LY_FINAL_TARIFF, LY_FINAL_RICHCORE, LY_FINAL_DINING, LY_FINAL_ADDONS, LY_FINAL_ROOMS_SOLD, LY_FINAL_GW, LY_FINAL_GROSS_TARIFF, LY_FINAL_GROSS_RICHCORE, LY_FINAL_GROSS_DINING, LY_FINAL_GROSS_ADDONS, LY_FINAL_GROSS_ROOMS_SOLD, LY_FINAL_GROSS_GW, LY_FINAL_CUMULATIVE_TARIFF, LY_FINAL_CUMULATIVE_RICHCORE, LY_FINAL_CUMULATIVE_DINING, LY_FINAL_CUMULATIVE_ADDONS, LY_FINAL_CUMULATIVE_ROOMS_SOLD, LY_FINAL_CUMULATIVE_GW, LY_LAST7DAYS_TARIFF, LY_LAST7DAYS_RICHCORE, LY_LAST7DAYS_NET_ROOMS_SOLD, LY_LAST7DAYS_GW, LY_LAST28DAYS_TARIFF, LY_LAST28DAYS_RICHCORE, LY_LAST28DAYS_NET_ROOMS_SOLD, LY_LAST28DAYS_GW
FROM HAVEN_STORE.OCANDC.OCC_SALES_CUBE_LY_TOTAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_LY_TOTAL_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_LY_TOTAL_REGIONAL(
	SHIP_CODE,
	BREAK_DATE,
	LEAD_TIME_DAY,
	SOURCE,
	LY_FINAL_TARIFF,
	LY_FINAL_RICHCORE,
	LY_FINAL_DINING,
	LY_FINAL_ADDONS,
	LY_FINAL_ROOMS_SOLD,
	LY_FINAL_GW,
	LY_FINAL_GROSS_TARIFF,
	LY_FINAL_GROSS_RICHCORE,
	LY_FINAL_GROSS_DINING,
	LY_FINAL_GROSS_ADDONS,
	LY_FINAL_GROSS_ROOMS_SOLD,
	LY_FINAL_GROSS_GW,
	LY_FINAL_CUMULATIVE_TARIFF,
	LY_FINAL_CUMULATIVE_RICHCORE,
	LY_FINAL_CUMULATIVE_DINING,
	LY_FINAL_CUMULATIVE_ADDONS,
	LY_FINAL_CUMULATIVE_ROOMS_SOLD,
	LY_FINAL_CUMULATIVE_GW,
	LY_LAST7DAYS_TARIFF,
	LY_LAST7DAYS_RICHCORE,
	LY_LAST7DAYS_NET_ROOMS_SOLD,
	LY_LAST7DAYS_GW,
	LY_LAST28DAYS_TARIFF,
	LY_LAST28DAYS_RICHCORE,
	LY_LAST28DAYS_NET_ROOMS_SOLD,
	LY_LAST28DAYS_GW
) as SELECT SHIP_CODE, BREAK_DATE, LEAD_TIME_DAY, SOURCE, LY_FINAL_TARIFF, LY_FINAL_RICHCORE, LY_FINAL_DINING, LY_FINAL_ADDONS, LY_FINAL_ROOMS_SOLD, LY_FINAL_GW, LY_FINAL_GROSS_TARIFF, LY_FINAL_GROSS_RICHCORE, LY_FINAL_GROSS_DINING, LY_FINAL_GROSS_ADDONS, LY_FINAL_GROSS_ROOMS_SOLD, LY_FINAL_GROSS_GW, LY_FINAL_CUMULATIVE_TARIFF, LY_FINAL_CUMULATIVE_RICHCORE, LY_FINAL_CUMULATIVE_DINING, LY_FINAL_CUMULATIVE_ADDONS, LY_FINAL_CUMULATIVE_ROOMS_SOLD, LY_FINAL_CUMULATIVE_GW, LY_LAST7DAYS_TARIFF, LY_LAST7DAYS_RICHCORE, LY_LAST7DAYS_NET_ROOMS_SOLD, LY_LAST7DAYS_GW, LY_LAST28DAYS_TARIFF, LY_LAST28DAYS_RICHCORE, LY_LAST28DAYS_NET_ROOMS_SOLD, LY_LAST28DAYS_GW
FROM HAVEN_STORE.OCANDC.OCC_SALES_CUBE_LY_TOTAL_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_LY_TOTAL_SILVER_APT source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_SALES_CUBE_LY_TOTAL_SILVER_APT(
	SHIP_CODE,
	BREAK_DATE,
	LEAD_TIME_DAY,
	SOURCE,
	LY_FINAL_TARIFF,
	LY_FINAL_RICHCORE,
	LY_FINAL_DINING,
	LY_FINAL_ADDONS,
	LY_FINAL_ROOMS_SOLD,
	LY_FINAL_GW,
	LY_FINAL_GROSS_TARIFF,
	LY_FINAL_GROSS_RICHCORE,
	LY_FINAL_GROSS_DINING,
	LY_FINAL_GROSS_ADDONS,
	LY_FINAL_GROSS_ROOMS_SOLD,
	LY_FINAL_GROSS_GW,
	LY_FINAL_CUMULATIVE_TARIFF_SILVER_APT,
	LY_FINAL_CUMULATIVE_RICHCORE_SILVER_APT,
	LY_FINAL_CUMULATIVE_DINING_SILVER_APT,
	LY_FINAL_CUMULATIVE_ADDONS_SILVER_APT,
	LY_FINAL_CUMULATIVE_ROOMS_SOLD_SILVER_APT,
	LY_FINAL_CUMULATIVE_GW_SILVER_APT
) as SELECT SHIP_CODE, BREAK_DATE, LEAD_TIME_DAY, SOURCE, LY_FINAL_TARIFF, LY_FINAL_RICHCORE, LY_FINAL_DINING, LY_FINAL_ADDONS, LY_FINAL_ROOMS_SOLD, LY_FINAL_GW, LY_FINAL_GROSS_TARIFF, LY_FINAL_GROSS_RICHCORE, LY_FINAL_GROSS_DINING, LY_FINAL_GROSS_ADDONS, LY_FINAL_GROSS_ROOMS_SOLD, LY_FINAL_GROSS_GW, LY_FINAL_CUMULATIVE_TARIFF_SILVER_APT, LY_FINAL_CUMULATIVE_RICHCORE_SILVER_APT, LY_FINAL_CUMULATIVE_DINING_SILVER_APT, LY_FINAL_CUMULATIVE_ADDONS_SILVER_APT, LY_FINAL_CUMULATIVE_ROOMS_SOLD_SILVER_APT, LY_FINAL_CUMULATIVE_GW_SILVER_APT
FROM HAVEN_STORE.OCANDC.OCC_SALES_CUBE_LY_TOTAL_SILVER_APT;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_SCATTER_BACKGROUND source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_SCATTER_BACKGROUND(
	SCATTER,
	COLOUR,
	POSITION,
	X_VALUE,
	Y_VALUE
) as SELECT SCATTER, COLOUR, POSITION, X_VALUE, Y_VALUE
FROM HAVEN_STORE.OCANDC.OCC_SCATTER_BACKGROUND;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_TRIMMED_CALENDAR source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_TRIMMED_CALENDAR(
	PERIOD,
	BREAKDATE_CURRENT,
	BREAKDATE_PRIOR,
	BREAKDATE_FUTURE
) as SELECT PERIOD, BREAKDATE_CURRENT, BREAKDATE_PRIOR, BREAKDATE_FUTURE
FROM HAVEN_STORE.OCANDC.OCC_TRIMMED_CALENDAR;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_TRIMMED_PRICE_CHANGES source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_TRIMMED_PRICE_CHANGES(
	SITECODE,
	BREAKDATE,
	DATADATE,
	LEAD_TIME_DAY,
	OFFER_PRICE_7NIGHTS,
	OFFER_PRICE_3OR4NIGHTS,
	BROCHURE_PRICE_3OR4NIGHTS
) as SELECT SITECODE, BREAKDATE, DATADATE, LEAD_TIME_DAY, OFFER_PRICE_7NIGHTS, OFFER_PRICE_3OR4NIGHTS, BROCHURE_PRICE_3OR4NIGHTS
FROM HAVEN_STORE.OCANDC.OCC_TRIMMED_PRICE_CHANGES;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_TRIMMED_PRICE_CHANGES_REGIONAL source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_TRIMMED_PRICE_CHANGES_REGIONAL(
	SITECODE,
	BREAKDATE,
	DATADATE,
	LEAD_TIME_DAY,
	OFFER_PRICE_7NIGHTS,
	OFFER_PRICE_3OR4NIGHTS
) as SELECT SITECODE, BREAKDATE, DATADATE, LEAD_TIME_DAY, OFFER_PRICE_7NIGHTS, OFFER_PRICE_3OR4NIGHTS
FROM HAVEN_STORE.OCANDC.OCC_TRIMMED_PRICE_CHANGES_REGIONAL;


-- HAVEN_STORE.ALIGN_ALYTICS.OCC_UNIT_GW_CONV source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.OCC_UNIT_GW_CONV(
	PARKCODE,
	BREAKDATE,
	UNITGWCONV
) as SELECT PARKCODE, BREAKDATE, UNITGWCONV
FROM HAVEN_STORE.OCANDC.OCC_UNIT_GW_CONV;


-- HAVEN_STORE.ALIGN_ALYTICS.PARK_CODE_TO_NAME source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.PARK_CODE_TO_NAME(
	PARK_CODE,
	PARK
) as SELECT PARK_CODE, PARK
FROM HAVEN_STORE.OCANDC.PARK_CODE_TO_NAME;


-- HAVEN_STORE.ALIGN_ALYTICS.PARKS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.PARKS(
	SHIP_ID,
	SHIP_CODE,
	SHIP_NAME,
	PARK_CODE,
	PARK_NAME,
	PARK_REGION,
	PARK_LANDING_URL,
	PARK_GENERIC_IMAGE_URL
) as SELECT SHIP_ID, SHIP_CODE, SHIP_NAME, PARK_CODE, PARK_NAME, PARK_REGION, PARK_LANDING_URL, PARK_GENERIC_IMAGE_URL
FROM HAVEN_STORE.COMMON.PARKS;


-- HAVEN_STORE.ALIGN_ALYTICS.PRICER_MINMAX source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.PRICER_MINMAX(
	PARK,
	GRADE,
	PRODUCT,
	SUBPRODUCT,
	BREAK_DATE,
	DURATION,
	MIN_PRICE,
	MAX_PRICE
) as
select 
	PARK,
	GRADE,
	PRODUCT,
	SUBPRODUCT,
	BREAK_DATE,
	DURATION,
	MIN_PRICE,
	MAX_PRICE
from  HAVEN_STORE.COMMERCIAL.PRICER_MINMAX;



-- HAVEN_STORE.ALIGN_ALYTICS.PRORATED_GROUP_REVENUE source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.PRORATED_GROUP_REVENUE(
	GROUP_ID,
	STAY_DATE,
	RES_ID,
	STATUS,
	BOOKING_DATE,
	FIRM_DATE,
	CANCELLATION_DATE,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	DURATION,
	PARK_CODE,
	PARK_REGION,
	ADULTS,
	CHILDREN,
	INFANTS,
	PRODUCT,
	SUB_PRODUCT,
	SOURCE,
	SEASON,
	PRORATED_NETT_BILLING_VALUE,
	PERIOD,
	DAY_RATIO,
	WEEK_RATIO,
	BREAK_RATIO
) as SELECT GROUP_ID, STAY_DATE, RES_ID, STATUS, BOOKING_DATE, FIRM_DATE, CANCELLATION_DATE, ARRIVAL_DATE, DEPARTURE_DATE, DURATION, PARK_CODE, PARK_REGION, ADULTS, CHILDREN, INFANTS, PRODUCT, SUB_PRODUCT, SOURCE, SEASON, PRORATED_NETT_BILLING_VALUE, PERIOD, DAY_RATIO, WEEK_RATIO, BREAK_RATIO
FROM HAVEN_STORE.TROOPER2.PRORATED_GROUP_REVENUE;


-- HAVEN_STORE.ALIGN_ALYTICS.PRORATED_RESERVATION_REVENUE source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.PRORATED_RESERVATION_REVENUE(
	RES_ID,
	STAY_DATE,
	GROUP_ID,
	BOOKING_STATUS,
	BOOKING_DATE,
	FIRM_DATE,
	CANCELLATION_DATE,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	DURATION,
	PARK_CODE,
	PARK_REGION,
	PAID_GRADE,
	PAID_GRADE_DESCRIPTION,
	REQUESTED_GRADE,
	REQUESTED_GRADE_DESCRIPTION,
	ALLOCATED_GRADE,
	ALLOCATED_GRADE_DESCRIPTION,
	PITCH_CODE,
	CONTRACT_TYPE,
	ADULTS,
	CHILDREN,
	INFANTS,
	PRODUCT,
	SUB_PRODUCT,
	SOURCE_CHANNEL,
	SEASON,
	PRORATED_NETT_BILLING_VALUE,
	PERIOD,
	DAY_RATIO,
	WEEK_RATIO,
	BREAK_RATIO
) as SELECT RES_ID, STAY_DATE, GROUP_ID, BOOKING_STATUS, BOOKING_DATE, FIRM_DATE, CANCELLATION_DATE, ARRIVAL_DATE, DEPARTURE_DATE, DURATION, PARK_CODE, PARK_REGION, PAID_GRADE, PAID_GRADE_DESCRIPTION, REQUESTED_GRADE, REQUESTED_GRADE_DESCRIPTION, ALLOCATED_GRADE, ALLOCATED_GRADE_DESCRIPTION, PITCH_CODE, CONTRACT_TYPE, ADULTS, CHILDREN, INFANTS, PRODUCT, SUB_PRODUCT, SOURCE_CHANNEL, SEASON, PRORATED_NETT_BILLING_VALUE, PERIOD, DAY_RATIO, WEEK_RATIO, BREAK_RATIO
FROM HAVEN_STORE.TROOPER2.PRORATED_RESERVATION_REVENUE;


-- HAVEN_STORE.ALIGN_ALYTICS.RES_SUMMARY source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.RES_SUMMARY(
	REF,
	RES_ID,
	RES_STATUS,
	PARK_CODE,
	PRODUCT,
	SUB_PRODUCT,
	NETT_BILLINGS,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	DURATION,
	PAID_GRADE,
	REQUESTED_GRADE,
	ALLOCATED_GRADE,
	BREAK_START,
	BREAK_END,
	BREAK_DURATION,
	DAYS_IN_BREAK,
	BILLINGS_IN_BREAK,
	BOOK_DATETIME,
	SOURCE
) as SELECT REF, RES_ID, RES_STATUS, PARK_CODE, PRODUCT, SUB_PRODUCT, NETT_BILLINGS, ARRIVAL_DATE, DEPARTURE_DATE, DURATION, PAID_GRADE, REQUESTED_GRADE, ALLOCATED_GRADE, BREAK_START, BREAK_END, BREAK_DURATION, DAYS_IN_BREAK, BILLINGS_IN_BREAK, BOOK_DATETIME, SOURCE
FROM HAVEN_STORE.OCANDC.RES_SUMMARY;


-- HAVEN_STORE.ALIGN_ALYTICS.RM_MAP source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.RM_MAP(
	PARK,
	REGION
) as SELECT PARK, REGION
FROM HAVEN_STORE.OCANDC.RM_MAP;


-- HAVEN_STORE.ALIGN_ALYTICS.ROOM_TYPE_LOOKUP source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.ROOM_TYPE_LOOKUP(
	ACCOM_CODE,
	BRAND,
	PRODUCT_DESCRIPTION,
	ACCOM_TYPES,
	ACCOM_GROUP,
	SUN_ACCOM_DESCRIPTION,
	ACCOM_DESCRIPTION,
	HAVEN_GRADE,
	GRADE_NUMBER,
	CHECK_IN_TIME,
	BEDROOMS,
	MAXGUESTS,
	DISABLED_YN,
	SUN_CHECK_IN_TIME,
	ACTIVE_ON_SEAWARE,
	VALID_FROM_DT,
	VALID_TO_DT,
	LEVEL_1_GROUPING,
	LEVEL_2_GROUPING
) as SELECT ACCOM_CODE, BRAND, PRODUCT_DESCRIPTION, ACCOM_TYPES, ACCOM_GROUP, SUN_ACCOM_DESCRIPTION, ACCOM_DESCRIPTION, HAVEN_GRADE, GRADE_NUMBER, CHECK_IN_TIME, BEDROOMS, MAXGUESTS, DISABLED_YN, SUN_CHECK_IN_TIME, ACTIVE_ON_SEAWARE, VALID_FROM_DT, VALID_TO_DT, LEVEL_1_GROUPING, LEVEL_2_GROUPING
FROM HAVEN_STORE.OCANDC.ROOM_TYPE_LOOKUP;


-- HAVEN_STORE.ALIGN_ALYTICS.TARGETS_WIDE source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.TARGETS_WIDE(
	METRIC,
	CHANNEL,
	SUBCHANNEL,
	RESORT,
	BREAK_SEGMENT,
	DATE_VALUE,
	TOTAL_TARIFF_BUDGET,
	TOTAL_GW_BUDGET,
	TOTAL_GATA_BUDGET,
	RICHCORE_TARIFF_BUDGET,
	RICHCORE_GW_BUDGET,
	RICHCORE_GATA_BUDGET,
	DINING_TARIFF_BUDGET,
	DINING_GW_BUDGET,
	DINING_GATA_BUDGET,
	ADD_ONS_TARIFF_BUDGET,
	ADD_ONS_GW_BUDGET,
	ADD_ONS_GATA_BUDGET,
	AVAILABLE_ROOMS,
	CONFERENCE_UNITS,
	SUN_UNITS,
	ADMIN_UNITS,
	CONFERENCE_TARIFF,
	SUN_TARIFF,
	ADMIN_TARIFF,
	COL_426,
	COL_425,
	COL_424,
	COL_423,
	COL_422,
	COL_421,
	COL_420,
	COL_419,
	COL_418,
	COL_417,
	COL_416,
	COL_415,
	COL_414,
	COL_413,
	COL_412,
	COL_411,
	COL_410,
	COL_409,
	COL_408,
	COL_407,
	COL_406,
	COL_405,
	COL_404,
	COL_403,
	COL_402,
	COL_401,
	COL_400,
	COL_399,
	COL_398,
	COL_397,
	COL_396,
	COL_395,
	COL_394,
	COL_393,
	COL_392,
	COL_391,
	COL_390,
	COL_389,
	COL_388,
	COL_387,
	COL_386,
	COL_385,
	COL_384,
	COL_383,
	COL_382,
	COL_381,
	COL_380,
	COL_379,
	COL_378,
	COL_377,
	COL_376,
	COL_375,
	COL_374,
	COL_373,
	COL_372,
	COL_371,
	COL_370,
	COL_369,
	COL_368,
	COL_367,
	COL_366,
	COL_365,
	COL_364,
	COL_363,
	COL_362,
	COL_361,
	COL_360,
	COL_359,
	COL_358,
	COL_357,
	COL_356,
	COL_355,
	COL_354,
	COL_353,
	COL_352,
	COL_351,
	COL_350,
	COL_349,
	COL_348,
	COL_347,
	COL_346,
	COL_345,
	COL_344,
	COL_343,
	COL_342,
	COL_341,
	COL_340,
	COL_339,
	COL_338,
	COL_337,
	COL_336,
	COL_335,
	COL_334,
	COL_333,
	COL_332,
	COL_331,
	COL_330,
	COL_329,
	COL_328,
	COL_327,
	COL_326,
	COL_325,
	COL_324,
	COL_323,
	COL_322,
	COL_321,
	COL_320,
	COL_319,
	COL_318,
	COL_317,
	COL_316,
	COL_315,
	COL_314,
	COL_313,
	COL_312,
	COL_311,
	COL_310,
	COL_309,
	COL_308,
	COL_307,
	COL_306,
	COL_305,
	COL_304,
	COL_303,
	COL_302,
	COL_301,
	COL_300,
	COL_299,
	COL_298,
	COL_297,
	COL_296,
	COL_295,
	COL_294,
	COL_293,
	COL_292,
	COL_291,
	COL_290,
	COL_289,
	COL_288,
	COL_287,
	COL_286,
	COL_285,
	COL_284,
	COL_283,
	COL_282,
	COL_281,
	COL_280,
	COL_279,
	COL_278,
	COL_277,
	COL_276,
	COL_275,
	COL_274,
	COL_273,
	COL_272,
	COL_271,
	COL_270,
	COL_269,
	COL_268,
	COL_267,
	COL_266,
	COL_265,
	COL_264,
	COL_263,
	COL_262,
	COL_261,
	COL_260,
	COL_259,
	COL_258,
	COL_257,
	COL_256,
	COL_255,
	COL_254,
	COL_253,
	COL_252,
	COL_251,
	COL_250,
	COL_249,
	COL_248,
	COL_247,
	COL_246,
	COL_245,
	COL_244,
	COL_243,
	COL_242,
	COL_241,
	COL_240,
	COL_239,
	COL_238,
	COL_237,
	COL_236,
	COL_235,
	COL_234,
	COL_233,
	COL_232,
	COL_231,
	COL_230,
	COL_229,
	COL_228,
	COL_227,
	COL_226,
	COL_225,
	COL_224,
	COL_223,
	COL_222,
	COL_221,
	COL_220,
	COL_219,
	COL_218,
	COL_217,
	COL_216,
	COL_215,
	COL_214,
	COL_213,
	COL_212,
	COL_211,
	COL_210,
	COL_209,
	COL_208,
	COL_207,
	COL_206,
	COL_205,
	COL_204,
	COL_203,
	COL_202,
	COL_201,
	COL_200,
	COL_199,
	COL_198,
	COL_197,
	COL_196,
	COL_195,
	COL_194,
	COL_193,
	COL_192,
	COL_191,
	COL_190,
	COL_189,
	COL_188,
	COL_187,
	COL_186,
	COL_185,
	COL_184,
	COL_183,
	COL_182,
	COL_181,
	COL_180,
	COL_179,
	COL_178,
	COL_177,
	COL_176,
	COL_175,
	COL_174,
	COL_173,
	COL_172,
	COL_171,
	COL_170,
	COL_169,
	COL_168,
	COL_167,
	COL_166,
	COL_165,
	COL_164,
	COL_163,
	COL_162,
	COL_161,
	COL_160,
	COL_159,
	COL_158,
	COL_157,
	COL_156,
	COL_155,
	COL_154,
	COL_153,
	COL_152,
	COL_151,
	COL_150,
	COL_149,
	COL_148,
	COL_147,
	COL_146,
	COL_145,
	COL_144,
	COL_143,
	COL_142,
	COL_141,
	COL_140,
	COL_139,
	COL_138,
	COL_137,
	COL_136,
	COL_135,
	COL_134,
	COL_133,
	COL_132,
	COL_131,
	COL_130,
	COL_129,
	COL_128,
	COL_127,
	COL_126,
	COL_125,
	COL_124,
	COL_123,
	COL_122,
	COL_121,
	COL_120,
	COL_119,
	COL_118,
	COL_117,
	COL_116,
	COL_115,
	COL_114,
	COL_113,
	COL_112,
	COL_111,
	COL_110,
	COL_109,
	COL_108,
	COL_107,
	COL_106,
	COL_105,
	COL_104,
	COL_103,
	COL_102,
	COL_101,
	COL_100,
	COL_99,
	COL_98,
	COL_97,
	COL_96,
	COL_95,
	COL_94,
	COL_93,
	COL_92,
	COL_91,
	COL_90,
	COL_89,
	COL_88,
	COL_87,
	COL_86,
	COL_85,
	COL_84,
	COL_83,
	COL_82,
	COL_81,
	COL_80,
	COL_79,
	COL_78,
	COL_77,
	COL_76,
	COL_75,
	COL_74,
	COL_73,
	COL_72,
	COL_71,
	COL_70,
	COL_69,
	COL_68,
	COL_67,
	COL_66,
	COL_65,
	COL_64,
	COL_63,
	COL_62,
	COL_61,
	COL_60,
	COL_59,
	COL_58,
	COL_57,
	COL_56,
	COL_55,
	COL_54,
	COL_53,
	COL_52,
	COL_51,
	COL_50,
	COL_49,
	COL_48,
	COL_47,
	COL_46,
	COL_45,
	COL_44,
	COL_43,
	COL_42,
	COL_41,
	COL_40,
	COL_39,
	COL_38,
	COL_37,
	COL_36,
	COL_35,
	COL_34,
	COL_33,
	COL_32,
	COL_31,
	COL_30,
	COL_29,
	COL_28,
	COL_27,
	COL_26,
	COL_25,
	COL_24,
	COL_23,
	COL_22,
	COL_21,
	COL_20,
	COL_19,
	COL_18,
	COL_17,
	COL_16,
	COL_15,
	COL_14,
	COL_13,
	COL_12,
	COL_11,
	COL_10,
	COL_9,
	COL_8,
	COL_7,
	COL_6,
	COL_5,
	COL_4,
	COL_3,
	COL_2,
	COL_1,
	COL_0,
	COL_427,
	COL_428,
	COL_429,
	COL_430,
	COL_431,
	COL_432,
	COL_433,
	COL_434,
	COL_435,
	COL_436,
	COL_437,
	COL_438,
	COL_439,
	COL_440,
	COL_441,
	COL_442,
	COL_443,
	COL_444,
	COL_445,
	COL_446,
	COL_447,
	COL_448,
	COL_449,
	COL_450,
	COL_451,
	COL_452,
	COL_453,
	COL_454,
	COL_455,
	COL_456,
	COL_457,
	COL_458,
	COL_459,
	COL_460,
	COL_461,
	COL_462,
	COL_463,
	COL_464,
	COL_465,
	COL_466,
	COL_467,
	COL_468,
	COL_469,
	COL_470,
	COL_471,
	COL_472,
	COL_473,
	COL_474,
	COL_475,
	COL_476,
	COL_477,
	COL_478,
	COL_479,
	COL_480,
	COL_481,
	COL_482,
	COL_483,
	COL_484,
	COL_485,
	COL_486,
	COL_487,
	COL_488,
	COL_489,
	COL_490,
	COL_491,
	COL_492,
	COL_493,
	COL_494,
	COL_495,
	COL_496,
	COL_497,
	COL_498,
	COL_499,
	COL_500,
	COL_501,
	COL_502,
	COL_503,
	COL_504,
	COL_505,
	COL_506,
	COL_507,
	COL_508,
	COL_509,
	COL_510,
	COL_511,
	COL_512,
	COL_513,
	COL_514,
	COL_515,
	COL_516,
	COL_517,
	COL_518,
	COL_519,
	COL_520,
	COL_521,
	COL_522,
	COL_523,
	COL_524,
	COL_525,
	COL_526,
	COL_527,
	COL_528,
	COL_529,
	COL_530,
	COL_531,
	COL_532,
	COL_533,
	COL_534,
	COL_535,
	COL_536,
	COL_537,
	COL_538,
	COL_539,
	COL_540,
	COL_541,
	COL_542,
	COL_543,
	COL_544,
	COL_545,
	COL_546,
	COL_547,
	COL_548,
	COL_549,
	COL_550,
	COL_551,
	COL_552,
	COL_553,
	COL_554,
	COL_555,
	COL_556,
	COL_557,
	COL_558,
	COL_559,
	COL_560,
	COL_561,
	COL_562,
	COL_563,
	COL_564,
	COL_565,
	COL_566,
	COL_567,
	COL_568,
	COL_569,
	COL_570,
	COL_571,
	COL_572,
	COL_573,
	COL_574,
	COL_575,
	COL_576,
	COL_577,
	COL_578,
	COL_579,
	COL_580,
	COL_581,
	COL_582,
	COL_583,
	COL_584,
	COL_585,
	COL_586,
	COL_587,
	COL_588,
	COL_589,
	COL_590,
	COL_591,
	COL_592,
	COL_593,
	COL_594,
	COL_595,
	COL_596,
	COL_597,
	COL_598,
	COL_599,
	COL_600,
	COL_601,
	COL_602,
	COL_603,
	COL_604,
	COL_605,
	COL_606,
	COL_607,
	COL_608,
	COL_609,
	COL_610,
	COL_611,
	COL_612,
	COL_613,
	COL_614,
	COL_615,
	COL_616,
	COL_617,
	COL_618,
	COL_619,
	COL_620,
	COL_621,
	COL_622,
	COL_623,
	COL_624,
	COL_625,
	COL_626,
	COL_627,
	COL_628,
	COL_629,
	COL_630,
	COL_631,
	COL_632,
	COL_633,
	COL_634,
	COL_635,
	COL_636,
	COL_637,
	COL_638,
	COL_639,
	COL_640,
	COL_641,
	COL_642,
	COL_643,
	COL_644,
	COL_645,
	COL_646,
	COL_647,
	COL_648,
	COL_649,
	COL_650,
	COL_651,
	COL_652,
	COL_653,
	COL_654,
	COL_655,
	COL_656,
	COL_657,
	COL_658,
	COL_659,
	COL_660,
	COL_661,
	COL_662,
	COL_663,
	COL_664,
	COL_665,
	COL_666,
	COL_667,
	COL_668,
	COL_669,
	COL_670,
	COL_671,
	COL_672,
	COL_673,
	COL_674,
	COL_675,
	COL_676,
	COL_677,
	COL_678,
	COL_679,
	COL_680,
	COL_681,
	COL_682,
	COL_683,
	COL_684,
	COL_685,
	COL_686,
	COL_687,
	COL_688,
	COL_689,
	COL_690,
	COL_691,
	COL_692,
	COL_693,
	COL_694,
	COL_695,
	COL_696,
	COL_697,
	COL_698,
	COL_699,
	DATE_UPDATE
) as SELECT METRIC, CHANNEL, SUBCHANNEL, RESORT, BREAK_SEGMENT, DATE_VALUE, TOTAL_TARIFF_BUDGET, TOTAL_GW_BUDGET, TOTAL_GATA_BUDGET, RICHCORE_TARIFF_BUDGET, RICHCORE_GW_BUDGET, RICHCORE_GATA_BUDGET, DINING_TARIFF_BUDGET, DINING_GW_BUDGET, DINING_GATA_BUDGET, ADD_ONS_TARIFF_BUDGET, ADD_ONS_GW_BUDGET, ADD_ONS_GATA_BUDGET, AVAILABLE_ROOMS, CONFERENCE_UNITS, SUN_UNITS, ADMIN_UNITS, CONFERENCE_TARIFF, SUN_TARIFF, ADMIN_TARIFF, COL_426, COL_425, COL_424, COL_423, COL_422, COL_421, COL_420, COL_419, COL_418, COL_417, COL_416, COL_415, COL_414, COL_413, COL_412, COL_411, COL_410, COL_409, COL_408, COL_407, COL_406, COL_405, COL_404, COL_403, COL_402, COL_401, COL_400, COL_399, COL_398, COL_397, COL_396, COL_395, COL_394, COL_393, COL_392, COL_391, COL_390, COL_389, COL_388, COL_387, COL_386, COL_385, COL_384, COL_383, COL_382, COL_381, COL_380, COL_379, COL_378, COL_377, COL_376, COL_375, COL_374, COL_373, COL_372, COL_371, COL_370, COL_369, COL_368, COL_367, COL_366, COL_365, COL_364, COL_363, COL_362, COL_361, COL_360, COL_359, COL_358, COL_357, COL_356, COL_355, COL_354, COL_353, COL_352, COL_351, COL_350, COL_349, COL_348, COL_347, COL_346, COL_345, COL_344, COL_343, COL_342, COL_341, COL_340, COL_339, COL_338, COL_337, COL_336, COL_335, COL_334, COL_333, COL_332, COL_331, COL_330, COL_329, COL_328, COL_327, COL_326, COL_325, COL_324, COL_323, COL_322, COL_321, COL_320, COL_319, COL_318, COL_317, COL_316, COL_315, COL_314, COL_313, COL_312, COL_311, COL_310, COL_309, COL_308, COL_307, COL_306, COL_305, COL_304, COL_303, COL_302, COL_301, COL_300, COL_299, COL_298, COL_297, COL_296, COL_295, COL_294, COL_293, COL_292, COL_291, COL_290, COL_289, COL_288, COL_287, COL_286, COL_285, COL_284, COL_283, COL_282, COL_281, COL_280, COL_279, COL_278, COL_277, COL_276, COL_275, COL_274, COL_273, COL_272, COL_271, COL_270, COL_269, COL_268, COL_267, COL_266, COL_265, COL_264, COL_263, COL_262, COL_261, COL_260, COL_259, COL_258, COL_257, COL_256, COL_255, COL_254, COL_253, COL_252, COL_251, COL_250, COL_249, COL_248, COL_247, COL_246, COL_245, COL_244, COL_243, COL_242, COL_241, COL_240, COL_239, COL_238, COL_237, COL_236, COL_235, COL_234, COL_233, COL_232, COL_231, COL_230, COL_229, COL_228, COL_227, COL_226, COL_225, COL_224, COL_223, COL_222, COL_221, COL_220, COL_219, COL_218, COL_217, COL_216, COL_215, COL_214, COL_213, COL_212, COL_211, COL_210, COL_209, COL_208, COL_207, COL_206, COL_205, COL_204, COL_203, COL_202, COL_201, COL_200, COL_199, COL_198, COL_197, COL_196, COL_195, COL_194, COL_193, COL_192, COL_191, COL_190, COL_189, COL_188, COL_187, COL_186, COL_185, COL_184, COL_183, COL_182, COL_181, COL_180, COL_179, COL_178, COL_177, COL_176, COL_175, COL_174, COL_173, COL_172, COL_171, COL_170, COL_169, COL_168, COL_167, COL_166, COL_165, COL_164, COL_163, COL_162, COL_161, COL_160, COL_159, COL_158, COL_157, COL_156, COL_155, COL_154, COL_153, COL_152, COL_151, COL_150, COL_149, COL_148, COL_147, COL_146, COL_145, COL_144, COL_143, COL_142, COL_141, COL_140, COL_139, COL_138, COL_137, COL_136, COL_135, COL_134, COL_133, COL_132, COL_131, COL_130, COL_129, COL_128, COL_127, COL_126, COL_125, COL_124, COL_123, COL_122, COL_121, COL_120, COL_119, COL_118, COL_117, COL_116, COL_115, COL_114, COL_113, COL_112, COL_111, COL_110, COL_109, COL_108, COL_107, COL_106, COL_105, COL_104, COL_103, COL_102, COL_101, COL_100, COL_99, COL_98, COL_97, COL_96, COL_95, COL_94, COL_93, COL_92, COL_91, COL_90, COL_89, COL_88, COL_87, COL_86, COL_85, COL_84, COL_83, COL_82, COL_81, COL_80, COL_79, COL_78, COL_77, COL_76, COL_75, COL_74, COL_73, COL_72, COL_71, COL_70, COL_69, COL_68, COL_67, COL_66, COL_65, COL_64, COL_63, COL_62, COL_61, COL_60, COL_59, COL_58, COL_57, COL_56, COL_55, COL_54, COL_53, COL_52, COL_51, COL_50, COL_49, COL_48, COL_47, COL_46, COL_45, COL_44, COL_43, COL_42, COL_41, COL_40, COL_39, COL_38, COL_37, COL_36, COL_35, COL_34, COL_33, COL_32, COL_31, COL_30, COL_29, COL_28, COL_27, COL_26, COL_25, COL_24, COL_23, COL_22, COL_21, COL_20, COL_19, COL_18, COL_17, COL_16, COL_15, COL_14, COL_13, COL_12, COL_11, COL_10, COL_9, COL_8, COL_7, COL_6, COL_5, COL_4, COL_3, COL_2, COL_1, COL_0, COL_427, COL_428, COL_429, COL_430, COL_431, COL_432, COL_433, COL_434, COL_435, COL_436, COL_437, COL_438, COL_439, COL_440, COL_441, COL_442, COL_443, COL_444, COL_445, COL_446, COL_447, COL_448, COL_449, COL_450, COL_451, COL_452, COL_453, COL_454, COL_455, COL_456, COL_457, COL_458, COL_459, COL_460, COL_461, COL_462, COL_463, COL_464, COL_465, COL_466, COL_467, COL_468, COL_469, COL_470, COL_471, COL_472, COL_473, COL_474, COL_475, COL_476, COL_477, COL_478, COL_479, COL_480, COL_481, COL_482, COL_483, COL_484, COL_485, COL_486, COL_487, COL_488, COL_489, COL_490, COL_491, COL_492, COL_493, COL_494, COL_495, COL_496, COL_497, COL_498, COL_499, COL_500, COL_501, COL_502, COL_503, COL_504, COL_505, COL_506, COL_507, COL_508, COL_509, COL_510, COL_511, COL_512, COL_513, COL_514, COL_515, COL_516, COL_517, COL_518, COL_519, COL_520, COL_521, COL_522, COL_523, COL_524, COL_525, COL_526, COL_527, COL_528, COL_529, COL_530, COL_531, COL_532, COL_533, COL_534, COL_535, COL_536, COL_537, COL_538, COL_539, COL_540, COL_541, COL_542, COL_543, COL_544, COL_545, COL_546, COL_547, COL_548, COL_549, COL_550, COL_551, COL_552, COL_553, COL_554, COL_555, COL_556, COL_557, COL_558, COL_559, COL_560, COL_561, COL_562, COL_563, COL_564, COL_565, COL_566, COL_567, COL_568, COL_569, COL_570, COL_571, COL_572, COL_573, COL_574, COL_575, COL_576, COL_577, COL_578, COL_579, COL_580, COL_581, COL_582, COL_583, COL_584, COL_585, COL_586, COL_587, COL_588, COL_589, COL_590, COL_591, COL_592, COL_593, COL_594, COL_595, COL_596, COL_597, COL_598, COL_599, COL_600, COL_601, COL_602, COL_603, COL_604, COL_605, COL_606, COL_607, COL_608, COL_609, COL_610, COL_611, COL_612, COL_613, COL_614, COL_615, COL_616, COL_617, COL_618, COL_619, COL_620, COL_621, COL_622, COL_623, COL_624, COL_625, COL_626, COL_627, COL_628, COL_629, COL_630, COL_631, COL_632, COL_633, COL_634, COL_635, COL_636, COL_637, COL_638, COL_639, COL_640, COL_641, COL_642, COL_643, COL_644, COL_645, COL_646, COL_647, COL_648, COL_649, COL_650, COL_651, COL_652, COL_653, COL_654, COL_655, COL_656, COL_657, COL_658, COL_659, COL_660, COL_661, COL_662, COL_663, COL_664, COL_665, COL_666, COL_667, COL_668, COL_669, COL_670, COL_671, COL_672, COL_673, COL_674, COL_675, COL_676, COL_677, COL_678, COL_679, COL_680, COL_681, COL_682, COL_683, COL_684, COL_685, COL_686, COL_687, COL_688, COL_689, COL_690, COL_691, COL_692, COL_693, COL_694, COL_695, COL_696, COL_697, COL_698, COL_699, DATE_UPDATE
FROM HAVEN_STORE.OCANDC.TARGETS_WIDE;


-- HAVEN_STORE.ALIGN_ALYTICS.UNALLOCATED_GROUP_UNITS source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.UNALLOCATED_GROUP_UNITS(
	REFID,
	GROUP_ID,
	RES_ID,
	CLIENT_ID,
	SHIP_CODE,
	AGENCY_NAME,
	CABIN_CATEGORY,
	HOLIDAYYEAR,
	SAIL_DATE_FROM,
	DURATION,
	REFERRAL_CODE,
	BOOKING_STATUS,
	RES_GUEST_COUNT,
	INVOICE_TOTAL,
	UNIT_ALLOCATED,
	AREA_CODE,
	AREA_NAME,
	ZONE_CODE,
	ZONE_NAME,
	PITCH_NUMBER,
	PITCH_CODE,
	DISCOUNTS,
	ADDONS,
	OPERATOR,
	VALIDFROM,
	NEWVALIDTO,
	UNITSALLOCATED
) as SELECT REFID, GROUP_ID, RES_ID, CLIENT_ID, SHIP_CODE, AGENCY_NAME, CABIN_CATEGORY, HOLIDAYYEAR, SAIL_DATE_FROM, DURATION, REFERRAL_CODE, BOOKING_STATUS, RES_GUEST_COUNT, INVOICE_TOTAL, UNIT_ALLOCATED, AREA_CODE, AREA_NAME, ZONE_CODE, ZONE_NAME, PITCH_NUMBER, PITCH_CODE, DISCOUNTS, ADDONS, OPERATOR, VALIDFROM, NEWVALIDTO, UNITSALLOCATED
FROM HAVEN_STORE.OCANDC.UNALLOCATED_GROUP_UNITS;


-- HAVEN_STORE.ALIGN_ALYTICS.VRES_GRADE_PRICE source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.VRES_GRADE_PRICE(
	PACKAGE_ID,
	GRADE,
	CABINS,
	ASSIGNED_ABS,
	ASSIGNED_WGT,
	GTY_WGT,
	GTY_ABS,
	WTL_ABS,
	WTL_WGT,
	AVAIL_PHYS,
	AVAIL_ABS,
	AVAIL_WGT,
	RESERVE_TOTAL,
	RESULT,
	CABIN_CAPACITY,
	RESERVE_USED,
	RESERVE_AVAIL,
	AMOUNT_TOTAL,
	AMOUNT_DISCOUNT,
	AMOUNT_1,
	AMOUNT_2,
	AMOUNT_3,
	AMOUNT_4,
	AMOUNT_5,
	AMOUNT_6,
	AMOUNT_7,
	AMOUNT_8,
	AMOUNT_9,
	AMOUNT_10,
	CABIN_CATEGORY_RANK,
	CABIN_CATEGORY_DESC,
	ROLLAWAY,
	REAL_CABIN_RESULT,
	SHIP_CODE,
	EFF_DATE,
	DATE_CREATED,
	ERROR_MESSAGE,
	ARRIVALDATE,
	LENGTH,
	PACKAGETYPE,
	PROMOTION,
	EXT_PACKAGE_ID,
	EXT_SELLING_ID
) as SELECT PACKAGE_ID, GRADE, CABINS, ASSIGNED_ABS, ASSIGNED_WGT, GTY_WGT, GTY_ABS, WTL_ABS, WTL_WGT, AVAIL_PHYS, AVAIL_ABS, AVAIL_WGT, RESERVE_TOTAL, RESULT, CABIN_CAPACITY, RESERVE_USED, RESERVE_AVAIL, AMOUNT_TOTAL, AMOUNT_DISCOUNT, AMOUNT_1, AMOUNT_2, AMOUNT_3, AMOUNT_4, AMOUNT_5, AMOUNT_6, AMOUNT_7, AMOUNT_8, AMOUNT_9, AMOUNT_10, CABIN_CATEGORY_RANK, CABIN_CATEGORY_DESC, ROLLAWAY, REAL_CABIN_RESULT, SHIP_CODE, EFF_DATE, DATE_CREATED, ERROR_MESSAGE, ARRIVALDATE, LENGTH, PACKAGETYPE, PROMOTION, EXT_PACKAGE_ID, EXT_SELLING_ID 
FROM HAVEN_BASE.SEAWARE.VRES_GRADE_PRICE;


-- HAVEN_STORE.ALIGN_ALYTICS.VRES_WEB_PRICE source

create or replace secure view HAVEN_STORE.ALIGN_ALYTICS.VRES_WEB_PRICE(
	PACKAGE_ID,
	GRADE,
	CABINS,
	ASSIGNED_ABS,
	ASSIGNED_WGT,
	GTY_WGT,
	GTY_ABS,
	WTL_ABS,
	WTL_WGT,
	AVAIL_PHYS,
	AVAIL_ABS,
	AVAIL_WGT,
	RESERVE_TOTAL,
	RESULT,
	CABIN_CAPACITY,
	RESERVE_USED,
	RESERVE_AVAIL,
	AMOUNT_TOTAL,
	AMOUNT_DISCOUNT,
	AMOUNT_1,
	AMOUNT_2,
	AMOUNT_3,
	AMOUNT_4,
	AMOUNT_5,
	AMOUNT_6,
	AMOUNT_7,
	AMOUNT_8,
	AMOUNT_9,
	AMOUNT_10,
	CABIN_CATEGORY_RANK,
	CABIN_CATEGORY_DESC,
	ROLLAWAY,
	REAL_CABIN_RESULT,
	SHIP_CODE,
	EFF_DATE,
	DATE_CREATED,
	ERROR_MESSAGE,
	ARRIVALDATE,
	LENGTH,
	PACKAGETYPE,
	PROMOTION,
	EXT_PACKAGE_ID,
	EXT_SELLING_ID
) as SELECT PACKAGE_ID, GRADE, CABINS, ASSIGNED_ABS, ASSIGNED_WGT, GTY_WGT, GTY_ABS, WTL_ABS, WTL_WGT, AVAIL_PHYS, AVAIL_ABS, AVAIL_WGT, RESERVE_TOTAL, RESULT, CABIN_CAPACITY, RESERVE_USED, RESERVE_AVAIL, AMOUNT_TOTAL, AMOUNT_DISCOUNT, AMOUNT_1, AMOUNT_2, AMOUNT_3, AMOUNT_4, AMOUNT_5, AMOUNT_6, AMOUNT_7, AMOUNT_8, AMOUNT_9, AMOUNT_10, CABIN_CATEGORY_RANK, CABIN_CATEGORY_DESC, ROLLAWAY, REAL_CABIN_RESULT, SHIP_CODE, EFF_DATE, DATE_CREATED, ERROR_MESSAGE, ARRIVALDATE, LENGTH, PACKAGETYPE, PROMOTION, EXT_PACKAGE_ID, EXT_SELLING_ID 
FROM HAVEN_BASE.SEAWARE.VRES_WEB_PRICE;