USE ROLE dba;

USE schema bourne_master.alation_metadata;

CREATE VIEW BOURNE_MASTER.ALATION_METADATA.POLICY_REFERENCES AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES;
CREATE VIEW BOURNE_MASTER.ALATION_METADATA.MASKING_POLICIES AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.MASKING_POLICIES;
CREATE VIEW BOURNE_MASTER.ALATION_METADATA.ROW_ACCESS_POLICIES AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.ROW_ACCESS_POLICIES;
