USE ROLE haven_batch_dataload;
USE DATABASE haven_raw;
USE SCHEMA pricer;

-- HAVEN_RAW.PRICER.M01_BOOKING_CURVE_EBO_MODEL definition

create TABLE HAVEN_RAW.PRICER.M01_BOOKING_CURVE_EBO_MODEL (
	SEGMENT_SEASON VARCHAR(256),
	YEAR NUMBER(4,0),
	NEXT_YEAR NUMBER(5,0),
	PARK_CLUSTER NUMBER(1,0),
	EBO_OFFSET_DAY VARIANT,
	EBO_OFFSET_WEEK FLOAT,
	EBO_UNPF_FCS_CM_GRO_UNCN NUMBER(38,15),
	EBO_UNPF_FCS_DL_GRO_UNCN NUMBER(38,15)
);


-- HAVEN_RAW.PRICER.M01_BOOKING_CURVE_MODEL definition

create TABLE HAVEN_RAW.PRICER.M01_BOOKING_CURVE_MODEL (
	PARK_CLUSTER NUMBER(1,0),
	YEAR NUMBER(4,0),
	SEGMENT_SEASON VARCHAR(256),
	SEASON_FORECAST_SEGMENT VARCHAR(256),
	BREAK_DOW VARCHAR(3),
	TIME_TO_OCCUPANCY NUMBER(10,0),
	UNPF_FCS_CM_GRO_CONS NUMBER(38,15)
);


-- HAVEN_RAW.PRICER.M06_CANCELLATIONS_DYNAMIC_UD definition

create TABLE HAVEN_RAW.PRICER.M06_CANCELLATIONS_DYNAMIC_UD (
	BOOKING_DVTP_ID NUMBER(38,0),
	CANCELLATION_DVTP_ID NUMBER(38,0),
	AVG_DAYS_IN_PERIOD NUMBER(38,6),
	UNITS_ACT_FN_GRO_CONS NUMBER(31,0),
	UNIT_ACT_FN_CAN_CONS NUMBER(31,0),
	SURVIVAL_RATE NUMBER(38,6),
	LOG_SURVIVAL_RATE FLOAT,
	LOG_SURVIVAL_RATE_DAILY FLOAT
);


-- HAVEN_RAW.PRICER.M06_CANCELLATIONS_STATIC_UD definition

create TABLE HAVEN_RAW.PRICER.M06_CANCELLATIONS_STATIC_UD (
	BOOKING_DVTP_ID NUMBER(38,0),
	UNITS_ACTUAL_GRO_CONS NUMBER(13,0),
	UNITS_ACTUAL_CAN_CONS NUMBER(13,0),
	UNPC_FCS_FN_CAN_UNCN NUMBER(19,6)
);


-- HAVEN_RAW.PRICER.UPLIFT_FACTORS_V5 definition

create TABLE HAVEN_RAW.PRICER.UPLIFT_FACTORS_V5 (
	PARK_CODE VARCHAR(10),
	YEAR NUMBER(4,0),
	_VERSION_BM VARCHAR(3),
	SEGMENT_SEASON VARCHAR(256),
	UPLIFT_FACTOR NUMBER(3,2)
);

------------------------------------

create TABLE HAVEN_RAW.PRICER.IMPORT_PUBLIC_HOLIDAYS (
	HOL_DATE DATE,
	DAY_OF_WEEK VARCHAR(16777216),
	HOLIDAY VARCHAR(16777216),
	SCOTLAND_FLAG NUMBER(1,0),
	ENGLAND_WALES_FLAG NUMBER(1,0),
	NON_RECURRING_FLAG NUMBER(1,0)
);


-- HAVEN_RAW.PRICER.IMPORT_SCHOOL_HOLIDAYS definition

create TABLE HAVEN_RAW.PRICER.IMPORT_SCHOOL_HOLIDAYS (
	SEASON_YEAR VARCHAR(16777216),
	DATE_FROM DATE,
	DATE_TO DATE,
	HOLIDAY_DESC VARCHAR(16777216),
	ENGLAND_WALES_FLAG NUMBER(1,0),
	SCOTLAND_FLAG NUMBER(1,0)
);


-- HAVEN_RAW.PRICER.META_DVTP_GLOBAL_V2 definition

create TABLE HAVEN_RAW.PRICER.META_DVTP_GLOBAL_V2 (
	DVTP_L1_ID NUMBER(38,0),
	DVTP_ID NUMBER(38,0),
	TIMETOOCCUPANCY_FROM NUMBER(38,0),
	TIMETOOCCUPANCY_TO NUMBER(38,0),
	DVTP_LENGTH NUMBER(38,0)
);

-- HAVEN_RAW.PRICER.GRADE_MAPPING_ADDITIONAL definition

create TABLE HAVEN_RAW.PRICER.GRADE_MAPPING_ADDITIONAL (
	PARK_CODE VARCHAR(256),
	OLD_GRADE VARCHAR(4),
	NEW_GRADE VARCHAR(16777216),
	MAPPED_GRADES ARRAY
);

USE ROLE dba;
USE DATABASE haven_base;
USE SCHEMA pricer;


CREATE VIEW HAVEN_BASE.PRICER.GRADE_MAPPING_ADDITIONAL
( PARK_CODE, OLD_GRADE, NEW_GRADE, MAPPED_GRADES )
AS SELECT PARK_CODE, OLD_GRADE, NEW_GRADE, MAPPED_GRADES
FROM HAVEN_RAW.PRICER.GRADE_MAPPING_ADDITIONAL;

CREATE VIEW HAVEN_BASE.PRICER.IMPORT_PUBLIC_HOLIDAYS
( HOL_DATE, DAY_OF_WEEK, HOLIDAY, SCOTLAND_FLAG, ENGLAND_WALES_FLAG, NON_RECURRING_FLAG )
AS SELECT HOL_DATE, DAY_OF_WEEK, HOLIDAY, SCOTLAND_FLAG, ENGLAND_WALES_FLAG, NON_RECURRING_FLAG
FROM HAVEN_RAW.PRICER.IMPORT_PUBLIC_HOLIDAYS;

CREATE VIEW HAVEN_BASE.PRICER.IMPORT_SCHOOL_HOLIDAYS
( SEASON_YEAR, DATE_FROM, DATE_TO, HOLIDAY_DESC, ENGLAND_WALES_FLAG, SCOTLAND_FLAG )
AS SELECT SEASON_YEAR, DATE_FROM, DATE_TO, HOLIDAY_DESC, ENGLAND_WALES_FLAG, SCOTLAND_FLAG
FROM HAVEN_RAW.PRICER.IMPORT_SCHOOL_HOLIDAYS;

CREATE VIEW HAVEN_BASE.PRICER.META_DVTP_GLOBAL_V2
( DVTP_L1_ID, DVTP_ID, TIMETOOCCUPANCY_FROM, TIMETOOCCUPANCY_TO, DVTP_LENGTH )
AS SELECT DVTP_L1_ID, DVTP_ID, TIMETOOCCUPANCY_FROM, TIMETOOCCUPANCY_TO, DVTP_LENGTH
FROM HAVEN_RAW.PRICER.META_DVTP_GLOBAL_V2;

CREATE VIEW HAVEN_BASE.PRICER.M01_BOOKING_CURVE_EBO_MODEL
( SEGMENT_SEASON, YEAR, NEXT_YEAR, PARK_CLUSTER, EBO_OFFSET_DAY, EBO_OFFSET_WEEK, EBO_UNPF_FCS_CM_GRO_UNCN, EBO_UNPF_FCS_DL_GRO_UNCN )
AS SELECT SEGMENT_SEASON, "YEAR", NEXT_YEAR, PARK_CLUSTER, EBO_OFFSET_DAY, EBO_OFFSET_WEEK, EBO_UNPF_FCS_CM_GRO_UNCN, EBO_UNPF_FCS_DL_GRO_UNCN
FROM HAVEN_RAW.PRICER.M01_BOOKING_CURVE_EBO_MODEL;

CREATE VIEW HAVEN_BASE.PRICER.M01_BOOKING_CURVE_MODEL
( PARK_CLUSTER, YEAR, SEGMENT_SEASON, SEASON_FORECAST_SEGMENT, BREAK_DOW, TIME_TO_OCCUPANCY, UNPF_FCS_CM_GRO_CONS )
AS SELECT PARK_CLUSTER, "YEAR", SEGMENT_SEASON, SEASON_FORECAST_SEGMENT, BREAK_DOW, TIME_TO_OCCUPANCY, UNPF_FCS_CM_GRO_CONS
FROM HAVEN_RAW.PRICER.M01_BOOKING_CURVE_MODEL;

CREATE VIEW HAVEN_BASE.PRICER.M06_CANCELLATIONS_DYNAMIC_UD
( BOOKING_DVTP_ID, CANCELLATION_DVTP_ID, AVG_DAYS_IN_PERIOD, UNITS_ACT_FN_GRO_CONS, UNIT_ACT_FN_CAN_CONS, SURVIVAL_RATE, LOG_SURVIVAL_RATE, LOG_SURVIVAL_RATE_DAILY )
AS SELECT BOOKING_DVTP_ID, CANCELLATION_DVTP_ID, AVG_DAYS_IN_PERIOD, UNITS_ACT_FN_GRO_CONS, UNIT_ACT_FN_CAN_CONS, SURVIVAL_RATE, LOG_SURVIVAL_RATE, LOG_SURVIVAL_RATE_DAILY
FROM HAVEN_RAW.PRICER.M06_CANCELLATIONS_DYNAMIC_UD;

CREATE VIEW HAVEN_BASE.PRICER.M06_CANCELLATIONS_STATIC_UD
( BOOKING_DVTP_ID, UNITS_ACTUAL_GRO_CONS, UNITS_ACTUAL_CAN_CONS, UNPC_FCS_FN_CAN_UNCN )
AS SELECT BOOKING_DVTP_ID, UNITS_ACTUAL_GRO_CONS, UNITS_ACTUAL_CAN_CONS, UNPC_FCS_FN_CAN_UNCN
FROM HAVEN_RAW.PRICER.M06_CANCELLATIONS_STATIC_UD;

CREATE VIEW HAVEN_BASE.PRICER.UPLIFT_FACTORS_V5
( PARK_CODE, YEAR, _VERSION_BM, SEGMENT_SEASON, UPLIFT_FACTOR )
AS SELECT PARK_CODE, "YEAR", _VERSION_BM, SEGMENT_SEASON, UPLIFT_FACTOR
FROM HAVEN_RAW.PRICER.UPLIFT_FACTORS_V5;

