--ALIGN_ALYTICS.AA_RM_GRADE_STORAGE.MANUAL_OFFSET_BLOCKS
--ALIGN_ALYTICS.AA_RM_GRADE_STORAGE.MANUAL_OFFSET_CHANGES
--ALIGN_ALYTICS.AA_RM_GRADE_STORAGE.MANUAL_OFFSET_CORRECTIONS
--ALIGN_ALYTICS.AA_RM_GRADE_STORAGE.S5_BREAKCORE_GRADE_ANCHOR_OFFSET
--ALIGN_ALYTICS.AA_RM_GRADE_STORAGE.S5_BREAKCORE_PRODUCT_MIX_DECISION_ENGINE_HISTORY
--ALIGN_ALYTICS.AA_RM_GRADE_STORAGE.S5_STAYDATE_GRADE_FINAL_OFFSET_HISTORY


SHOW ROLES;
SHOW USERS;

USE ROLE ALIGNALYTICS_PRICING_DATA;

USE SCHEMA ALIGN_ALYTICS.AA_RM_GRADE_STORAGE;

SHOW TABLES;

select get_ddl('SCHEMA', 'AA_RM_GRADE_STORAGE');