-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.BREAK_LOOKUP_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.BREAK_LOOKUP_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	BREAKID DATE,
	RESORT_NAME VARCHAR(256),
	SHIP_CODE VARCHAR(256),
	BREAK_TYPE VARCHAR(256),
	TARGET_FILL_BREAK_SEGMENT VARCHAR(256),
	MATCHED_DATE DATE,
	LOOKUP VARCHAR(256),
	MATCHED_LOOKUP VARCHAR(256),
	DELUXE_AVG_PRICE_ACHD FLOAT
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.BREAK_SEGMENTATION_LOOKUP_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.BREAK_SEGMENTATION_LOOKUP_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	BREAKID DATE,
	RESORT_NAME VARCHAR(256),
	SHIP_CODE VARCHAR(256),
	BREAK_TYPE VARCHAR(256),
	TARGET_FILL_BREAK_SEGMENT VARCHAR(256),
	LOOKUP VARCHAR(256)
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.BUDGET_INPUTS_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.BUDGET_INPUTS_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	HAVEN_SHIP_CODE VARCHAR(256),
	SEASON VARCHAR(256),
	BREAK_DATE DATE,
	WEEK_DATE DATE,
	BREAK_AND_HAVEN_CODE VARCHAR(256),
	OCC_CODE VARCHAR(256),
	PERIOD VARCHAR(256),
	ARRIVAL_DAY VARCHAR(256),
	HIREFLEET_BREAKS NUMBER(38,0),
	LETTING_BREAKS NUMBER(38,0),
	FINAL_BILLINGS FLOAT,
	FINAL_BREAKS FLOAT,
	WEEKS FLOAT,
	UNIT_CONVERSION FLOAT,
	BREAK_AND_OCC_CODE VARCHAR(256),
	UNIT_NO FLOAT,
	SUN_UNITS FLOAT,
	SUN_REV FLOAT,
	DIRECT_UNITS FLOAT,
	DIRECT_REV FLOAT
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.CALENDAR_LOOKUP_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.CALENDAR_LOOKUP_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	PERIOD VARCHAR(256),
	BREAKDATE_CURRENT DATE,
	BREAKDATE_PRIOR DATE,
	WEEKDAY VARCHAR(256),
	PERIOD2 VARCHAR(256),
	DATE1 DATE,
	DATE2 DATE
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.CANCELLATIONS_DATA_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.CANCELLATIONS_DATA_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	BOOKING_STATUS VARCHAR(16777216),
	BREAK_DATE DATE,
	SHIP_CODE VARCHAR(16777216),
	LEAD_TIME_DAY NUMBER(38,0),
	RES_INIT_DATE DATE,
	CANCELLATION_DATE DATE,
	SOURCE VARCHAR(16777216),
	SAIL_FROM_DATE DATE,
	EDITED_HOLIDAY_DURATION NUMBER(38,0),
	TOTAL_RICHCORE FLOAT,
	TOTAL_TARIFF FLOAT,
	TOTAL_BOOKINGS FLOAT,
	DELUXE_6BERTH_RICHCORE FLOAT,
	DELUXE_6BERTH_BOOKINGS FLOAT,
	DELUXE_LIST_PRICE FLOAT
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.DELUXE_PRICE_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.DELUXE_PRICE_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	LOOKUP VARCHAR(16777216),
	PARK VARCHAR(16777216),
	WEEKDAY VARCHAR(16777216),
	PERIOD VARCHAR(16777216),
	OPTIMAL FLOAT,
	WEEKDAY_DOW NUMBER(38,0),
	PARK2 VARCHAR(16777216)
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.OPTIMISER_INPUTS_PRICE_SHAPE_CHANGE_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.OPTIMISER_INPUTS_PRICE_SHAPE_CHANGE_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	BREAK_SEGMENT VARCHAR(256),
	PERIOD_1 FLOAT,
	PERIOD_2 FLOAT,
	PERIOD_3 FLOAT,
	PERIOD_4 FLOAT,
	PERIOD_5 FLOAT,
	PERIOD_6 FLOAT,
	PERIOD_7 FLOAT,
	PERIOD_8 FLOAT,
	PERIOD_9 FLOAT,
	EBO FLOAT,
	WEIGHTED_AVG FLOAT
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.OPTIMISER_INPUTS_VOLUME_PERC_SHAPE_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.OPTIMISER_INPUTS_VOLUME_PERC_SHAPE_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	SEGMENT VARCHAR(256),
	BREAK_DATE DATE,
	LOOKUP VARCHAR(256),
	WEEK_60 FLOAT,
	WEEK_59 FLOAT,
	WEEK_58 FLOAT,
	WEEK_57 FLOAT,
	WEEK_56 FLOAT,
	WEEK_55 FLOAT,
	WEEK_54 FLOAT,
	WEEK_53 FLOAT,
	WEEK_52 FLOAT,
	WEEK_51 FLOAT,
	WEEK_50 FLOAT,
	WEEK_49 FLOAT,
	WEEK_48 FLOAT,
	WEEK_47 FLOAT,
	WEEK_46 FLOAT,
	WEEK_45 FLOAT,
	WEEK_44 FLOAT,
	WEEK_43 FLOAT,
	WEEK_42 FLOAT,
	WEEK_41 FLOAT,
	WEEK_40 FLOAT,
	WEEK_39 FLOAT,
	WEEK_38 FLOAT,
	WEEK_37 FLOAT,
	WEEK_36 FLOAT,
	WEEK_35 FLOAT,
	WEEK_34 FLOAT,
	WEEK_33 FLOAT,
	WEEK_32 FLOAT,
	WEEK_31 FLOAT,
	WEEK_30 FLOAT,
	WEEK_29 FLOAT,
	WEEK_28 FLOAT,
	WEEK_27 FLOAT,
	WEEK_26 FLOAT,
	WEEK_25 FLOAT,
	WEEK_24 FLOAT,
	WEEK_23 FLOAT,
	WEEK_22 FLOAT,
	WEEK_21 FLOAT,
	WEEK_20 FLOAT,
	WEEK_19 FLOAT,
	WEEK_18 FLOAT,
	WEEK_17 FLOAT,
	WEEK_16 FLOAT,
	WEEK_15 FLOAT,
	WEEK_14 FLOAT,
	WEEK_13 FLOAT,
	WEEK_12 FLOAT,
	WEEK_11 FLOAT,
	WEEK_10 FLOAT,
	WEEK_9 FLOAT,
	WEEK_8 FLOAT,
	WEEK_7 FLOAT,
	WEEK_6 FLOAT,
	WEEK_5 FLOAT,
	WEEK_4 FLOAT,
	WEEK_3 FLOAT,
	WEEK_2 FLOAT,
	WEEK_1 FLOAT,
	WEEK_0 FLOAT
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.SHIP_LOOKUP definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.SHIP_LOOKUP (
	OC_C_CODES VARCHAR(256),
	OC_C_LOCATION VARCHAR(256),
	HAVEN_CODE VARCHAR(256),
	SAME VARCHAR(256)
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.SOURCE_LOOKUP_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.SOURCE_LOOKUP_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	ORIGINALS VARCHAR(14),
	MAPPING VARCHAR(6)
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.STAY_PRICE_ADJUSTMENT_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_INPUTS.STAY_PRICE_ADJUSTMENT_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	LOOKUP VARCHAR(16777216),
	BASE_LOOKUP VARCHAR(16777216),
	OCC_PARK VARCHAR(16777216),
	RESORT_NAME VARCHAR(16777216),
	ARRIVAL DATE,
	GRADE VARCHAR(16777216),
	PACKAGE VARCHAR(16777216),
	PARK VARCHAR(16777216),
	PLAY_UPGRADE_PRICE FLOAT,
	STAY_DISCOUNT FLOAT
);


-- ALIGN_ALYTICS.TARGET_BREAK_STORAGE.BREAK_TARGET_OUTPUT_HISTORY definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_STORAGE.BREAK_TARGET_OUTPUT_HISTORY (
	VERSION_ID NUMBER(38,0),
	BREAK_DATE DATE,
	SHIP_CODE VARCHAR(256),
	TARGET_FILL_BREAK_SEGMENT VARCHAR(256),
	LEAD_TIME_WEEKS FLOAT,
	LEAD_TIME_DAYS VARIANT,
	ADJUSTED_GROSS_ROS FLOAT,
	ADJUSTED_NET_ROS FLOAT,
	PRICE FLOAT,
	SILVER_PRICE FLOAT,
	RICHCORE FLOAT
);


-- ALIGN_ALYTICS.TARGET_BREAK_STORAGE.INPUT_MODEL_META definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_STORAGE.INPUT_MODEL_META (
	INPUT_NAME VARCHAR(256),
	DATA_VERSION_ID NUMBER(38,0),
	DESCRIPTION VARCHAR(256),
	DATE_RANGE VARCHAR(256)
);


-- ALIGN_ALYTICS.TARGET_BREAK_STORAGE.PROCESS_CONTROL_HEADER definition

create or replace TABLE ALIGN_ALYTICS.TARGET_BREAK_STORAGE.PROCESS_CONTROL_HEADER (
	VERSION_ID NUMBER(38,0),
	RUN_DATE TIMESTAMP_NTZ(9),
	PROPERTIES OBJECT
);

-- ALIGN_ALYTICS.RM_STAGING.S1_DIM_BREAKS_CORE definition

create or replace TRANSIENT TABLE ALIGN_ALYTICS.RM_STAGING.S1_DIM_BREAKS_CORE (
	PARK_CODE VARCHAR(10),
	BREAK_ID VARCHAR(16777216),
	BREAK_DATE_FROM DATE,
	BREAK_DATE_TO DATE,
	BREAK_SAMPLE_DATE DATE,
	DURATION NUMBER(18,0),
	RELATIVE_DATE NUMBER(9,0),
	RELATIVE_OUTLOOK VARCHAR(6),
	BREAK_DOW VARCHAR(3),
	BREAK_YEAR_NUMBER NUMBER(4,0),
	BREAK_YEAR DATE,
	BREAK_MONTH DATE,
	SEGMENT_SEASON VARCHAR(256),
	SEGMENT_BREAK VARCHAR(256),
	SEGMENT_GROUP VARCHAR(256),
	TARGET_FILL_BREAK_SEGMENT VARCHAR(256),
	BREAK_PERIOD VARCHAR(50),
	PACKAGE_DETAIL ARRAY,
	CORE_PACKAGE_DETAIL ARRAY
);

---------------------------------

-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.IMPORT_PUBLIC_HOLIDAYS definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.IMPORT_PUBLIC_HOLIDAYS (
	HOL_DATE DATE,
	DAY_OF_WEEK VARCHAR(16777216),
	HOLIDAY VARCHAR(16777216),
	SCOTLAND_FLAG NUMBER(1,0),
	ENGLAND_WALES_FLAG NUMBER(1,0),
	NON_RECURRING_FLAG NUMBER(1,0)
);


-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.IMPORT_SCHOOL_HOLIDAYS definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.IMPORT_SCHOOL_HOLIDAYS (
	SEASON_YEAR VARCHAR(16777216),
	DATE_FROM DATE,
	DATE_TO DATE,
	HOLIDAY_DESC VARCHAR(16777216),
	ENGLAND_WALES_FLAG NUMBER(1,0),
	SCOTLAND_FLAG NUMBER(1,0)
);


-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.META_DVTP_GLOBAL_V2 definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.META_DVTP_GLOBAL_V2 (
	DVTP_L1_ID NUMBER(38,0),
	DVTP_ID NUMBER(38,0),
	TIMETOOCCUPANCY_FROM NUMBER(38,0),
	TIMETOOCCUPANCY_TO NUMBER(38,0),
	DVTP_LENGTH NUMBER(38,0)
);

-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.GRADE_MAPPING_ADDITIONAL definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.GRADE_MAPPING_ADDITIONAL (
	PARK_CODE VARCHAR(256),
	OLD_GRADE VARCHAR(4),
	NEW_GRADE VARCHAR(16777216),
	MAPPED_GRADES ARRAY
);

-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.M01_BOOKING_CURVE_EBO_MODEL definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.M01_BOOKING_CURVE_EBO_MODEL (
	SEGMENT_SEASON VARCHAR(256),
	YEAR NUMBER(4,0),
	NEXT_YEAR NUMBER(5,0),
	PARK_CLUSTER NUMBER(1,0),
	EBO_OFFSET_DAY VARIANT,
	EBO_OFFSET_WEEK FLOAT,
	EBO_UNPF_FCS_CM_GRO_UNCN NUMBER(38,15),
	EBO_UNPF_FCS_DL_GRO_UNCN NUMBER(38,15)
);


-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.M01_BOOKING_CURVE_MODEL definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.M01_BOOKING_CURVE_MODEL (
	PARK_CLUSTER NUMBER(1,0),
	YEAR NUMBER(4,0),
	SEGMENT_SEASON VARCHAR(256),
	SEASON_FORECAST_SEGMENT VARCHAR(256),
	BREAK_DOW VARCHAR(3),
	TIME_TO_OCCUPANCY NUMBER(10,0),
	UNPF_FCS_CM_GRO_CONS NUMBER(38,15)
);


-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.M06_CANCELLATIONS_DYNAMIC_UD definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.M06_CANCELLATIONS_DYNAMIC_UD (
	BOOKING_DVTP_ID NUMBER(38,0),
	CANCELLATION_DVTP_ID NUMBER(38,0),
	AVG_DAYS_IN_PERIOD NUMBER(38,6),
	UNITS_ACT_FN_GRO_CONS NUMBER(31,0),
	UNIT_ACT_FN_CAN_CONS NUMBER(31,0),
	SURVIVAL_RATE NUMBER(38,6),
	LOG_SURVIVAL_RATE FLOAT,
	LOG_SURVIVAL_RATE_DAILY FLOAT
);


-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.M06_CANCELLATIONS_STATIC_UD definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.M06_CANCELLATIONS_STATIC_UD (
	BOOKING_DVTP_ID NUMBER(38,0),
	UNITS_ACTUAL_GRO_CONS NUMBER(13,0),
	UNITS_ACTUAL_CAN_CONS NUMBER(13,0),
	UNPC_FCS_FN_CAN_UNCN NUMBER(19,6)
);


-- ALIGN_ALYTICS.HAVEN_DBT_STORAGE.UPLIFT_FACTORS_V5 definition

create or replace TABLE ALIGN_ALYTICS.HAVEN_DBT_STORAGE.UPLIFT_FACTORS_V5 (
	PARK_CODE VARCHAR(10),
	YEAR NUMBER(4,0),
	_VERSION_BM VARCHAR(3),
	SEGMENT_SEASON VARCHAR(256),
	UPLIFT_FACTOR NUMBER(3,2)
);