USE ROLE useradmin;

CREATE ROLE warner_aps_share;

USE ROLE accountadmin;

CREATE SHARE warner_aps_share;

USE ROLE sysadmin;

CREATE DATABASE ROLE warner_store.aps_share;

USE ROLE securityadmin;

GRANT USAGE ON DATABASE warner_store TO DATABASE ROLE warner_store.aps_share;

GRANT USAGE ON SCHEMA warner_store.aps_share TO DATABASE ROLE warner_store.aps_share;

GRANT SELECT ON  VIEW WARNER_STORE.APS_SHARE.COMMISSION_CODE to database role warner_store.aps_share;
GRANT SELECT ON  VIEW WARNER_STORE.APS_SHARE.GROUP_COMMISSION_DETAIL to database role warner_store.aps_share;
GRANT SELECT ON  VIEW WARNER_STORE.APS_SHARE.GROUP_PAY_DUE_ITEM to database role warner_store.aps_share;
GRANT SELECT ON  VIEW WARNER_STORE.APS_SHARE.GROUP_PROMOTION to database role warner_store.aps_share;
GRANT SELECT ON  VIEW WARNER_STORE.APS_SHARE.RES_COMMISSION_DETAIL to database role warner_store.aps_share;
GRANT SELECT ON  VIEW WARNER_STORE.APS_SHARE.RES_PAYMENT_DUE_ITEM to database role warner_store.aps_share;

grant select on view WARNER_STORE.APS_SHARE.CLIENT to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.SHIP to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.BLL_RM_PRICE to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.CABIN_ATTRIBUTE to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.CABIN_CATEGORY to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.CABIN_CATEGORY_COMMENTS to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.CABIN_LAYOUT to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.AM_CODE to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.USER_LOGIN to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.USER_GROUP to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.USER_GROUP_MEMBER to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.SHIP_INVENTORY_ALLOC to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.RES_HEADER to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.RES_ADDON to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.RES_INVOICE_ITEM to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.VCS_ADDITIONAL_FIELD_VALUE to database role warner_store.aps_share;
grant select on view WARNER_STORE.APS_SHARE.CABIN_ATTRIBUTE_LINK to database role warner_store.aps_share;

GRANT USAGE ON DATABASE warner_store TO SHARE warner_aps_share;
GRANT reference_usage ON DATABASE warner_base TO SHARE warner_aps_share;
GRANT reference_usage ON DATABASE warner_raw TO SHARE warner_aps_share;

GRANT DATABASE ROLE warner_store.aps_share TO SHARE warner_aps_share;

REVOKE DATABASE ROLE warner_store.aps_share FROM SHARE warner_aps_share;

USE ROLE accountadmin;

ALTER SHARE warner_aps_share ADD ACCOUNTS = FN75496;

CREATE SHARE aps_share;


-- WARNER_BASE.SEAWARE.SHIP source

USE ROLE dba;
USE SCHEMA warner_store.aps_share;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.COMMISSION_CODE
(  COMMISS_CODE_ID, COMMISS_CODE, COMMISS_NAME, COMMISS_TYPE, BASIS_TYPE, EXPRESSION_ID, COMMENTS )
 AS SELECT  COMMISS_CODE_ID, COMMISS_CODE, COMMISS_NAME, COMMISS_TYPE, BASIS_TYPE, EXPRESSION_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.COMMISSION_CODE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.GROUP_COMMISSION_DETAIL
(  RECORD_ID, AMOUNT, COMMISS_FARE, COMMISS_CODE, COMMISS_SOURCE, INVOICE_ITEM_TYPE, "PERCENT", GROUP_ID, PACKAGE_ID, IS_MANUAL_ADJUSTMENT )
 AS SELECT  RECORD_ID, AMOUNT, COMMISS_FARE, COMMISS_CODE, COMMISS_SOURCE, INVOICE_ITEM_TYPE, "PERCENT", GROUP_ID, PACKAGE_ID, IS_MANUAL_ADJUSTMENT
FROM WARNER_BASE.SEAWARE.GROUP_COMMISSION_DETAIL;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.GROUP_PAY_DUE_ITEM
(  RECORD_ID, GROUP_ID, PMNT_DUE_ITEM_TYPE, DUE_DATE, GRACE_PERIOD, AMOUNT, ACTIVITY_TYPE, ACTIVITY_DATE, ACTIVITY_EFFECTIVE_DATE, ACTIVITY_INFO, DELEGATE_RES_ID, CABIN_NUMBER, IS_ADJUSTMENT, CABIN_CATEGORY, OCCUPANCY, SHIP_CODE, EXPIRATION_DATE )
 AS SELECT  RECORD_ID, GROUP_ID, PMNT_DUE_ITEM_TYPE, DUE_DATE, GRACE_PERIOD, AMOUNT, ACTIVITY_TYPE, ACTIVITY_DATE, ACTIVITY_EFFECTIVE_DATE, ACTIVITY_INFO, DELEGATE_RES_ID, CABIN_NUMBER, IS_ADJUSTMENT, CABIN_CATEGORY, OCCUPANCY, SHIP_CODE, EXPIRATION_DATE
FROM WARNER_BASE.SEAWARE.GROUP_PAY_DUE_ITEM;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.GROUP_PROMOTION
(  GROUP_PROMOTION_ID, GROUP_ID, GROUP_SHIP_REQ_ID, PROMO_CODE, GUEST_MASK, REQUESTED_COUNT, UNASSIGNED_QTY )
 AS SELECT  GROUP_PROMOTION_ID, GROUP_ID, GROUP_SHIP_REQ_ID, PROMO_CODE, GUEST_MASK, REQUESTED_COUNT, UNASSIGNED_QTY
FROM WARNER_BASE.SEAWARE.GROUP_PROMOTION;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.RES_COMMISSION_DETAIL
(  RES_COMMISS_DETAIL_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, COMMISS_SOURCE, COMMISS_CODE, "PERCENT", AMOUNT, INVOICE_ITEM_TYPE, COMMISS_FARE, IS_MANUAL_ADJUSTMENT )
 AS SELECT  RES_COMMISS_DETAIL_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, COMMISS_SOURCE, COMMISS_CODE, "PERCENT", AMOUNT, INVOICE_ITEM_TYPE, COMMISS_FARE, IS_MANUAL_ADJUSTMENT
FROM WARNER_BASE.SEAWARE.RES_COMMISSION_DETAIL;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.RES_PAYMENT_DUE_ITEM
(  RES_PAYMENT_DUE_ITEM_ID, PMNT_DUE_ITEM_TYPE, GUEST_ID, RES_ID, DUE_DATE, GRACE_PERIOD, AMOUNT, EXPIRATION_DATE, PAYMENT_SEQN )
 AS SELECT  RES_PAYMENT_DUE_ITEM_ID, PMNT_DUE_ITEM_TYPE, GUEST_ID, RES_ID, DUE_DATE, GRACE_PERIOD, AMOUNT, EXPIRATION_DATE, PAYMENT_SEQN
FROM WARNER_BASE.SEAWARE.RES_PAYMENT_DUE_ITEM;

SELECT COMMISS_CODE_ID, COMMISS_CODE, COMMISS_NAME, COMMISS_TYPE, BASIS_TYPE, EXPRESSION_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.COMMISSION_CODE;
SELECT RECORD_ID, AMOUNT, COMMISS_FARE, COMMISS_CODE, COMMISS_SOURCE, INVOICE_ITEM_TYPE, "PERCENT", GROUP_ID, PACKAGE_ID, IS_MANUAL_ADJUSTMENT
FROM WARNER_BASE.SEAWARE.GROUP_COMMISSION_DETAIL;
SELECT RECORD_ID, GROUP_ID, PMNT_DUE_ITEM_TYPE, DUE_DATE, GRACE_PERIOD, AMOUNT, ACTIVITY_TYPE, ACTIVITY_DATE, ACTIVITY_EFFECTIVE_DATE, ACTIVITY_INFO, DELEGATE_RES_ID, CABIN_NUMBER, IS_ADJUSTMENT, CABIN_CATEGORY, OCCUPANCY, SHIP_CODE, EXPIRATION_DATE
FROM WARNER_BASE.SEAWARE.GROUP_PAY_DUE_ITEM;
SELECT GROUP_PROMOTION_ID, GROUP_ID, GROUP_SHIP_REQ_ID, PROMO_CODE, GUEST_MASK, REQUESTED_COUNT, UNASSIGNED_QTY
FROM WARNER_BASE.SEAWARE.GROUP_PROMOTION;
SELECT RES_COMMISS_DETAIL_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, COMMISS_SOURCE, COMMISS_CODE, "PERCENT", AMOUNT, INVOICE_ITEM_TYPE, COMMISS_FARE, IS_MANUAL_ADJUSTMENT
FROM WARNER_BASE.SEAWARE.RES_COMMISSION_DETAIL;
SELECT RES_PAYMENT_DUE_ITEM_ID, PMNT_DUE_ITEM_TYPE, GUEST_ID, RES_ID, DUE_DATE, GRACE_PERIOD, AMOUNT, EXPIRATION_DATE, PAYMENT_SEQN
FROM WARNER_BASE.SEAWARE.RES_PAYMENT_DUE_ITEM;


SELECT RECORD_ID, AGENCY_ID, COMMISS_CODE, DATE_FROM, DATE_TO, USE_FOR_CHILDREN, USE_FROM_ABOVE
FROM WARNER_BASE.SEAWARE.AGENCY_COMMISSION;
SELECT AGENCY_TYPE_ID, AGENCY_TYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.AGENCY_TYPE;
SELECT AM_DELVR_TYPE, RECORD_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.AM_DELVR_TYPE;
SELECT AM_ORDER_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, AM_REQSTER_TYPE, AGENCY_ID, AGENT_ID, CLIENT_ID, AM_BOOKING_TYPE, RES_ID, GROUP_ID, DISPATCHED_DATE, DISPATCHED_OK, GIFT_CARD_TO, GIFT_CARD_MSG, COMPLIMENTS_OF, ORDER_VALID, TERMINATION_COMPLETED, CREATED_FROM_ADDON, CANCEL_REFUND_DONE, FREE_OF_CHARGE, GROUP_DISTRIBUTION_OK, SHOW_ITEM_LIST, CURRENCY_CODE, AM_ENTITY_TYPE, INVOICE_VALID
FROM WARNER_BASE.SEAWARE.AM_ORDER_HEADER;
SELECT ORD_STATUS_CODE, RECORD_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.AM_ORDER_STATUS;
SELECT RECORD_ID, AM_PLACE_CODE, COMPONENT_TYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.AM_PLACE_COMPTYPE_LINK;
SELECT AM_REQ_TYPE, RECORD_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.AM_REQSTER_TYPE;
SELECT PROVIDER_CODE, RECORD_ID, PROVIDER_TYPE, PROVIDER_NAME, COMMENTS, PROVIDER_CODE_EXTERNAL
FROM WARNER_BASE.SEAWARE.AM_SRVCE_PROVIDER;
SELECT DATE_, PARK_CODE, GRADE_CODE, PRODUCT_TYPE, PITCHES, NA_ABS, HELD, RSRV_UA, RSRV_OL, RSRV_OB, ALLOC, CAP, AVAIL, FIRM, ASGN_ABS, GTY_ABS, "TIMESTAMP", BK, OFR, RSRV_SP
FROM WARNER_BASE.SEAWARE.BLL_INV_AVAILABILITY;
SELECT COMMISS_CODE_ID, COMMISS_CODE, COMMISS_NAME, COMMISS_TYPE, BASIS_TYPE, EXPRESSION_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.COMMISSION_CODE;
SELECT COMMISS_TYPE_ID, COMMISS_TYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.COMMISSION_TYPE;
SELECT COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE
FROM WARNER_BASE.SEAWARE.COMPONENT_TYPE;
SELECT RECORD_ID, INVOICE_ITEM_TYPE, INV_ITEM_GROUP, COMMENTS, INV_ITEM_GROUP_TYPE, OFFICE_CODE
FROM WARNER_BASE.SEAWARE.INV_ITEM_GROUP_MATCH;
SELECT INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST
FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_GROUP;
SELECT INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_GROUP_TYPE;
SELECT INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_SUBTYPE;
SELECT INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC
FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_TYPE;
SELECT RES_ADDON_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, RES_ADDON_CODE, START_DATE, END_DATE, EFFECTIVE_DATE, AM_ORDER_ID, IS_DEFAULT, PAP_CODE, AMENITY_CODE, DELIVERY_PLACE, QUANTITY, IS_AUTO, COMMENTS, "TIMESTAMP"
FROM WARNER_BASE.SEAWARE.RES_ADDON;
SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID
FROM WARNER_BASE.SEAWARE.RES_INVOICE_CANC;
SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID
FROM WARNER_BASE.SEAWARE.RES_INVOICE_ITEM;
SELECT RECORD_ID, SHIP_CODE, CABIN_NUMBER, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, RESERVE_TYPE, COMMENTS, GUEST_COUNT
FROM WARNER_BASE.SEAWARE.SHIP_CABIN_RESERVE;
SELECT RECORD_ID, RESERVE_TYPE, DECREMENTS_INVENTORY, ALLOWS_BOOKING, IS_RESTRICTED, IS_SAIL_RESERVE
FROM WARNER_BASE.SEAWARE.SHIP_CABIN_RESERVE_TYPE;
SELECT SP_REQ_CODE, REQ_CODE_ID, SP_REQ_TYPE, PROVIDER_CODE, SP_REQ_NAME, COMMENTS, WDW_CODED_REMARK
FROM WARNER_BASE.SEAWARE.SP_REQ_CODE;
SELECT SP_ORD_ITEM_ID, SP_REQ_ID, SP_REQ_CODE, AM_PLACE_CODE, DELIVERY_DATE, DELIVERY_TIME, QUANTITY, COMMENTS, GUEST_FULL_NAME, GUEST_ID, ITEM_VALID
FROM WARNER_BASE.SEAWARE.SP_REQ_ORD_ITEM;
SELECT SP_REQ_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, ORDER_VALID, AM_BOOKING_TYPE, GROUP_ID, RES_ID, AM_REQ_TYPE, AGENCY_ID, CLIENT_ID, AM_PLACE_CODE, AGENT_ID, DELIVERY_TIME, DISPATCHED_DATE, DISPATCHED_OK, COMMENTS, TERMINATION_COMPLETED
FROM WARNER_BASE.SEAWARE.SP_REQ_ORDER;
SELECT SP_REQ_TYPE_ID, SP_REQ_TYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.SP_REQ_TYPE;
SELECT RECORD_ID, USAGE_AREA, COMMENTS
FROM WARNER_BASE.SEAWARE.SP_REQ_USAGE_AREA;


CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.CABIN_ATTRIBUTE_LINK
(SHIP_CODE, CABIN_NUMBER, CABIN_ATTR_ID, SEQ_NUMBER, CABIN_ATTR_COUNTER, CABIN_ATTR_EXT_INFO, RECORD_ID, EFF_SAIL_FROM, EFF_SAIL_TO)
AS SELECT SHIP_CODE, CABIN_NUMBER, CABIN_ATTR_ID, SEQ_NUMBER, CABIN_ATTR_COUNTER, CABIN_ATTR_EXT_INFO, RECORD_ID, EFF_SAIL_FROM, EFF_SAIL_TO
FROM WARNER_RAW.SEAWARE.CABIN_ATTRIBUTE_LINK;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.VCS_ADDITIONAL_FIELD_VALUE
(ID, ROW_TYPE, FIELD_NAME, RECORD_ID, NUMBER_VALUE, DATE_VALUE, STR_VALUE)
AS SELECT ID, ROW_TYPE, FIELD_NAME, RECORD_ID, NUMBER_VALUE, DATE_VALUE, STR_VALUE
FROM WARNER_RAW.SEAWARE.VCS_ADDITIONAL_FIELD_VALUE;


create or replace view WARNER_STORE.APS_SHARE.SHIP(
	SHIP_ID,
	SHIP_CODE,
	SHIP_NAME,
	SHIP_REGISTRY,
	SHIP_BUILT_DATE,
	SHIP_CREW_SIZE,
	SHIP_PAX_CAPACITY,
	SHIP_CRUISING_SPEED,
	SHIP_MAX_SPEED,
	SHIP_LENGTH,
	SHIP_BEAM,
	SHIP_DRAUGHT,
	SHIP_TONNAGE,
	SHIP_STABILIZER,
	COMMENTS,
	IMAGE_ID,
	CRUISE_LINE_CODE,
	SHIP_BRAND
) as SELECT SHIP_ID, SHIP_CODE, SHIP_NAME, SHIP_REGISTRY, SHIP_BUILT_DATE, SHIP_CREW_SIZE, SHIP_PAX_CAPACITY, SHIP_CRUISING_SPEED, SHIP_MAX_SPEED, SHIP_LENGTH, SHIP_BEAM, SHIP_DRAUGHT, SHIP_TONNAGE, SHIP_STABILIZER, COMMENTS, IMAGE_ID, CRUISE_LINE_CODE, SHIP_BRAND FROM WARNER_BASE.SEAWARE.SHIP;

-- WARNER_STORE.APS_SHARE.BLL_RM_PRICE source

create or replace view WARNER_STORE.APS_SHARE.BLL_RM_PRICE(
	RM_PRICE_ID,
	PARK_CODE,
	ARRIVAL_DATE,
	PACKAGE_TYPE,
	GRADE,
	PRICE,
	EFFECTIVE_FROM,
	INSERT_DATE,
	BLL_RM_PRICE_TYPE,
	PERCENT,
	GENERIC_GRADE,
	DESCRIPTION,
	ATTRIBUTE_CODE,
	ATTRIBUTE_VALUE
) as SELECT RM_PRICE_ID, PARK_CODE, ARRIVAL_DATE, PACKAGE_TYPE, GRADE, PRICE, EFFECTIVE_FROM, INSERT_DATE, BLL_RM_PRICE_TYPE, PERCENT, GENERIC_GRADE, DESCRIPTION, ATTRIBUTE_CODE, ATTRIBUTE_VALUE FROM WARNER_BASE.SEAWARE.BLL_RM_PRICE;

-- WARNER_STORE.APS_SHARE.CABIN_ATTRIBUTE source

create or replace view WARNER_STORE.APS_SHARE.CABIN_ATTRIBUTE(
	CABIN_ATTR_ID,
	CABIN_ATTR_CODE,
	CABIN_ATTR_NAME,
	IS_ATTR_UNIQUE,
	IS_ATTR_COUNTABLE,
	IS_ATTR_EXTENDED,
	IS_ATTR_MANDATORY,
	COMMENTS,
	IMAGE_ID,
	USE_FOR_SHOPPING
) as SELECT CABIN_ATTR_ID, CABIN_ATTR_CODE, CABIN_ATTR_NAME, IS_ATTR_UNIQUE, IS_ATTR_COUNTABLE, IS_ATTR_EXTENDED, IS_ATTR_MANDATORY, COMMENTS, IMAGE_ID, USE_FOR_SHOPPING FROM WARNER_BASE.SEAWARE.CABIN_ATTRIBUTE;

-- WARNER_STORE.APS_SHARE.CABIN_CATEGORY source

create or replace view WARNER_STORE.APS_SHARE.CABIN_CATEGORY(
	CABIN_CATEGORY,
	CABIN_CATEGORY_ID,
	COMMENTS,
	IMAGE_ID,
	CABIN_CAPACITY,
	CABIN_CATEGORY_RANK,
	SHIP_CODE,
	IS_ACTIVE,
	ALLOW_AUTO_ASGN
) as SELECT CABIN_CATEGORY, CABIN_CATEGORY_ID, COMMENTS, IMAGE_ID, CABIN_CAPACITY, CABIN_CATEGORY_RANK, SHIP_CODE, IS_ACTIVE, ALLOW_AUTO_ASGN FROM WARNER_BASE.SEAWARE.CABIN_CATEGORY;

-- WARNER_STORE.APS_SHARE.CABIN_CATEGORY_COMMENTS source

create or replace view WARNER_STORE.APS_SHARE.CABIN_CATEGORY_COMMENTS(
	RECORD_ID,
	SHIP_CODE,
	CABIN_CATEGORY,
	EFF_FROM,
	EFF_TO,
	COMMENTS
) as SELECT RECORD_ID, SHIP_CODE, CABIN_CATEGORY, EFF_FROM, EFF_TO, COMMENTS FROM WARNER_BASE.SEAWARE.CABIN_CATEGORY_COMMENTS;

-- WARNER_STORE.APS_SHARE.CABIN_LAYOUT source

create or replace view WARNER_STORE.APS_SHARE.CABIN_LAYOUT(
	CABIN_LAYOUT_ID,
	DECK_ID,
	OBJECT,
	CABIN_ID
) as SELECT CABIN_LAYOUT_ID, DECK_ID, OBJECT, CABIN_ID FROM WARNER_BASE.SEAWARE.CABIN_LAYOUT;

-- WARNER_STORE.APS_SHARE.AM_CODE source

create or replace view WARNER_STORE.APS_SHARE.AM_CODE(
	AMENITY_CODE,
	RECORD_ID,
	AM_CATEGORY,
	AMENITY_TYPE,
	PROVIDER_CODE,
	AMENITY_NAME,
	COMMENTS,
	USE_TAX,
	SUBCODE_MANDATORY,
	MANDATORY_BEFORE_DLV,
	CODE_ACTIVE,
	ADDON_RESTRICTED,
	ADDON_ORDER_BASIS,
	ADDON_INV_ITEM_TYPE,
	ADDON_COMPONENT_TYPE,
	INCLUDE_IN_ORDER,
	DISPLAY_PER_PACKAGE,
	IMAGE_ID,
	APPLY_TO_ALL_GUESTS,
	SELL_LIMIT_WEIGHT,
	VEHICLE_TYPE
) as SELECT AMENITY_CODE, RECORD_ID, AM_CATEGORY, AMENITY_TYPE, PROVIDER_CODE, AMENITY_NAME, COMMENTS, USE_TAX, SUBCODE_MANDATORY, MANDATORY_BEFORE_DLV, CODE_ACTIVE, ADDON_RESTRICTED, ADDON_ORDER_BASIS, ADDON_INV_ITEM_TYPE, ADDON_COMPONENT_TYPE, INCLUDE_IN_ORDER, DISPLAY_PER_PACKAGE, IMAGE_ID, APPLY_TO_ALL_GUESTS, SELL_LIMIT_WEIGHT, VEHICLE_TYPE FROM WARNER_BASE.SEAWARE.AM_CODE;

-- WARNER_STORE.APS_SHARE.USER_LOGIN source

create or replace view WARNER_STORE.APS_SHARE.USER_LOGIN(
	USER_ID,
	USER_LOGIN_NAME,
	USER_PASSWORD,
	USER_FIRST_NAME,
	USER_MIDDLE_NAME,
	USER_LAST_NAME,
	USER_FULL_NAME,
	COMMENTS,
	OFFICE_CODE,
	ADMINISTRATIVE_OFFICE,
	OFFICE_LOCATION_CODE
) as SELECT USER_ID, USER_LOGIN_NAME, USER_PASSWORD, USER_FIRST_NAME, USER_MIDDLE_NAME, USER_LAST_NAME, USER_FULL_NAME, COMMENTS, OFFICE_CODE, ADMINISTRATIVE_OFFICE, OFFICE_LOCATION_CODE FROM WARNER_BASE.SEAWARE.USER_LOGIN;

-- WARNER_STORE.APS_SHARE.USER_GROUP source

create or replace view WARNER_STORE.APS_SHARE.USER_GROUP(
	USER_GROUP_ID,
	USER_GROUP_NAME,
	COMMENTS,
	MENU_ID,
	START_PARAMS
) as SELECT USER_GROUP_ID, USER_GROUP_NAME, COMMENTS, MENU_ID, START_PARAMS FROM WARNER_BASE.SEAWARE.USER_GROUP;

-- WARNER_STORE.APS_SHARE.USER_GROUP_MEMBER source

create or replace view WARNER_STORE.APS_SHARE.USER_GROUP_MEMBER(
	USER_ID,
	USER_GROUP_ID,
	IS_DEFAULT,
	RECORD_ID
) as SELECT USER_ID, USER_GROUP_ID, IS_DEFAULT, RECORD_ID FROM WARNER_BASE.SEAWARE.USER_GROUP_MEMBER;

-- WARNER_STORE.APS_SHARE.SHIP_INVENTORY_ALLOC source

create or replace view WARNER_STORE.APS_SHARE.SHIP_INVENTORY_ALLOC(
	ALLOCATION_ID,
	ALLOCATION_OWNER_TYPE,
	ALLOCATION_OWNER_ID,
	OPERATOR_ID,
	ALLOCATION_TIMESTAMP,
	PRIORITY,
	SHIP_CODE,
	REL_DAY_FROM,
	REL_DAY_TO,
	SAIL_DATE_FROM,
	SAIL_DATE_TO,
	CABIN_CATEGORY,
	DEPENDS_ON_ID,
	INVENTORY_REQUEST_TYPE,
	INVENTORY_RESULT_TYPE,
	CABIN_NUMBER,
	PROBABILITY,
	DECLINE_REASON,
	RELEASE_TIMESTAMP,
	OCCUPANCY,
	PRICE_CATEGORY,
	ROLLAWAY_BEDS_REQUESTED,
	RESERVE_TYPE,
	WTL_OWNER_FLAG,
	DLGT_RES_ID,
	IS_DLGT_OBJ,
	OVERLAY_DAY_FROM,
	OVERLAY_DAY_TO,
	IS_SOFT_ASSIGN,
	IS_FIXED_ASSIGN
) as SELECT ALLOCATION_ID, ALLOCATION_OWNER_TYPE, ALLOCATION_OWNER_ID, OPERATOR_ID, ALLOCATION_TIMESTAMP, PRIORITY, SHIP_CODE, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, CABIN_CATEGORY, DEPENDS_ON_ID, INVENTORY_REQUEST_TYPE, INVENTORY_RESULT_TYPE, CABIN_NUMBER, PROBABILITY, DECLINE_REASON, RELEASE_TIMESTAMP, OCCUPANCY, PRICE_CATEGORY, ROLLAWAY_BEDS_REQUESTED, RESERVE_TYPE, WTL_OWNER_FLAG, DLGT_RES_ID, IS_DLGT_OBJ, OVERLAY_DAY_FROM, OVERLAY_DAY_TO, IS_SOFT_ASSIGN, IS_FIXED_ASSIGN FROM WARNER_BASE.SEAWARE.SHIP_INVENTORY_ALLOC;

-- WARNER_STORE.APS_SHARE.RES_HEADER source

create or replace view WARNER_STORE.APS_SHARE.RES_HEADER(
	RES_ID,
	RES_INIT_DATE,
	RES_GUEST_COUNT,
	AGENCY_ID,
	AGENT_ID,
	CABIN_CATEGORY,
	RES_STATUS,
	PROBABILITY,
	GROUP_ID,
	DELEGATE_HEADER_ID,
	COMMENTS,
	CRS_STATUS,
	DPMS_STATUS,
	TERMINATION_COMPLETED,
	SHIP_CODE,
	PACKAGE_TYPE,
	SAIL_DATE_FROM,
	SAIL_DATE_TO,
	REL_DAY_FROM,
	REL_DAY_TO,
	SOURCE_CODE,
	ALT_RES_ID,
	SEC_AGENCY_ID,
	OFFICE_CODE,
	CURRENCY_RATE,
	CURRENCY_CODE,
	RH_ENTITY_TYPE,
	AM_ORDER_ID,
	CANCELLATION_CASE,
	OFFICE_LOCATION,
	CHANNEL_CODE
) as SELECT RES_ID, RES_INIT_DATE, RES_GUEST_COUNT, AGENCY_ID, AGENT_ID, CABIN_CATEGORY, RES_STATUS, PROBABILITY, GROUP_ID, DELEGATE_HEADER_ID, COMMENTS, CRS_STATUS, DPMS_STATUS, TERMINATION_COMPLETED, SHIP_CODE, PACKAGE_TYPE, SAIL_DATE_FROM, SAIL_DATE_TO, REL_DAY_FROM, REL_DAY_TO, SOURCE_CODE, ALT_RES_ID, SEC_AGENCY_ID, OFFICE_CODE, CURRENCY_RATE, CURRENCY_CODE, RH_ENTITY_TYPE, AM_ORDER_ID, CANCELLATION_CASE, OFFICE_LOCATION, CHANNEL_CODE FROM WARNER_BASE.SEAWARE.RES_HEADER;

-- WARNER_STORE.APS_SHARE.RES_ADDON source

create or replace view WARNER_STORE.APS_SHARE.RES_ADDON(
	RES_ADDON_ID,
	RES_PACKAGE_ID,
	GUEST_ID,
	RES_ID,
	RES_ADDON_CODE,
	START_DATE,
	END_DATE,
	EFFECTIVE_DATE,
	AM_ORDER_ID,
	IS_DEFAULT,
	PAP_CODE,
	AMENITY_CODE,
	DELIVERY_PLACE,
	QUANTITY,
	IS_AUTO,
	COMMENTS,
	TIMESTAMP
) as SELECT RES_ADDON_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, RES_ADDON_CODE, START_DATE, END_DATE, EFFECTIVE_DATE, AM_ORDER_ID, IS_DEFAULT, PAP_CODE, AMENITY_CODE, DELIVERY_PLACE, QUANTITY, IS_AUTO, COMMENTS, TIMESTAMP FROM WARNER_BASE.SEAWARE.RES_ADDON;

-- WARNER_STORE.APS_SHARE.RES_INVOICE_ITEM source

create or replace view WARNER_STORE.APS_SHARE.RES_INVOICE_ITEM(
	RES_INVOICE_ITEM_ID,
	RES_ID,
	GUEST_ID,
	RES_PACKAGE_ID,
	INVOICE_ITEM_TYPE,
	PRICE_PER_UNIT,
	N_OF_UNITS,
	PERCENT,
	AMOUNT,
	INVOICE_ITEM_SUBTYPE,
	INVOICE_ITEM_SUBTYPE2,
	INVOICE_ITEM_SUBTYPE3,
	PRICE_PROGRAM,
	HOTEL_REQUEST_ID,
	COMMISSION_PERCENT,
	SHIP_ROOM_REQUEST_ID
) as SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, PRICE_PER_UNIT, N_OF_UNITS, PERCENT, AMOUNT, INVOICE_ITEM_SUBTYPE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID FROM WARNER_BASE.SEAWARE.RES_INVOICE_ITEM;

-- WARNER_BASE.SEAWARE.CLIENT source

USE ROLE dba;
USE SCHEMA WARNER_STORE.APS_SHARE;

create or replace view WARNER_STORE.APS_SHARE.CLIENT (
	CLIENT_ID,
	HOUSEHOLD_ID,
	SALUTATION,
	TITLE,
	OCCUPATION,
	IS_ACTIVE,
	BIRTH_PLACE,
	SEX,
	LANGUAGE,
	PASSPORT_ISSUE_PLACE,
	PASSPORT_ISSUE_DATE,
	PASSPORT_EXP_DATE,
	NATIONALITY,
	CITIZENSHIP,
	REFERRAL_TYPE,
	REFERRAL_DATE,
	REFERRAL_CLIENT_ID,
	REFERRAL_HOUSEHOLD_ID,
	REFERRAL_SOURCE,
	CLIENT_TYPE,
	GUEST_TYPE,
	DIRECTORY_NAME,
	CLIENT_CLASS_CODE,
	COUNTRY_OF_BIRTH,
	WEB_PASSWORD,
	WEB_LAST_LOGIN,
	SSN,
	LANGUAGE_CODE,
	HISTORICAL_CRUISES_NUM,
	HISTORICAL_DAYS_NUM,
	ALLOW_WEB_ACCESS,
	CL_ENTITY_TYPE,
	SEND_PROMOTIONAL_MAIL,
	SEND_PROMOTIONAL_EMAIL,
	SEND_PROMOTIONAL_SMS,
	NOTIF_DFLT_DISTR_TYPE,
	SEND_PROMOTIONAL_PHONE
) as SELECT "CLIENT_ID", "HOUSEHOLD_ID", "SALUTATION", "TITLE", "OCCUPATION", "IS_ACTIVE", "BIRTH_PLACE", "SEX", 
"LANGUAGE","PASSPORT_ISSUE_PLACE", "PASSPORT_ISSUE_DATE", "PASSPORT_EXP_DATE", "NATIONALITY", "CITIZENSHIP", "REFERRAL_TYPE", "REFERRAL_DATE", 
"REFERRAL_CLIENT_ID", "REFERRAL_HOUSEHOLD_ID", "REFERRAL_SOURCE", "CLIENT_TYPE", "GUEST_TYPE", "DIRECTORY_NAME", "CLIENT_CLASS_CODE", 
"COUNTRY_OF_BIRTH", "WEB_PASSWORD", "WEB_LAST_LOGIN", "SSN", "LANGUAGE_CODE", "HISTORICAL_CRUISES_NUM", "HISTORICAL_DAYS_NUM", "ALLOW_WEB_ACCESS", 
"CL_ENTITY_TYPE", "SEND_PROMOTIONAL_MAIL", "SEND_PROMOTIONAL_EMAIL", "SEND_PROMOTIONAL_SMS", "NOTIF_DFLT_DISTR_TYPE", "SEND_PROMOTIONAL_PHONE" 
FROM "WARNER_BASE"."SEAWARE"."CLIENT";

alter view WARNER_STORE.APS_SHARE.CLIENT set secure;
alter view WARNER_STORE.APS_SHARE.SHIP set secure;
alter view WARNER_STORE.APS_SHARE.BLL_RM_PRICE set secure;
alter view WARNER_STORE.APS_SHARE.CABIN_ATTRIBUTE set secure;
alter view WARNER_STORE.APS_SHARE.CABIN_CATEGORY set secure;
alter view WARNER_STORE.APS_SHARE.CABIN_CATEGORY_COMMENTS set secure;
alter view WARNER_STORE.APS_SHARE.CABIN_LAYOUT set secure;
alter view WARNER_STORE.APS_SHARE.AM_CODE set secure;
alter view WARNER_STORE.APS_SHARE.USER_LOGIN set secure;
alter view WARNER_STORE.APS_SHARE.USER_GROUP set secure;
alter view WARNER_STORE.APS_SHARE.USER_GROUP_MEMBER set secure;
alter view WARNER_STORE.APS_SHARE.SHIP_INVENTORY_ALLOC set secure;
alter view WARNER_STORE.APS_SHARE.RES_HEADER set secure;
alter view WARNER_STORE.APS_SHARE.RES_ADDON set secure;
alter view WARNER_STORE.APS_SHARE.RES_INVOICE_ITEM set secure;




-- WARNER_STORE.APS_SHARE.VW_RESERVATION_DETAILS source

USE ROLE warner_store_dev_dbt_rw;

create or replace secure view WARNER_STORE.APS_SHARE.VW_RESERVATION_DETAILS(
	RES_ID,
	AGREEMENTCODE,
	BEGINDATE,
	CHANNELCODE,
	CHECKINDATE,
	CHECKOUTDATE,
	CREATIONCHANNELCODE,
	SOURCELOCATIONCODE,
	SOURCELOCATIONSUBCODE,
	CREATIONDATE,
	DESTINATIONLOCATIONCODE,
	DESTINATIONLOCATIONTIMEZONE,
	ORIGINLOCATIONCODE,
	ORIGINLOCATIONTIMEZONE,
	DURATION,
	EXTERNALRESERVATIONNUMBER,
	LASTMODIFIED,
	ONREQUEST,
	ORDERBY,
	RESERVATIONNUMBER,
	LANGUAGE,
	SESSIONID,
	STATUS,
	TRANSACTIONREFERENCE,
	CANCELNUMBER,
	CANCELDATE,
	EXTERNALCANCELNUMBER,
	CANCELREASON,
	RESERVATIONNAME,
	AFFILIATECODE,
	TRACE
) as (select rh.Res_id,
'' as agreementCode,
rh.SAIL_DATE_FROM as beginDate,
ag.agency_type as channelCode,
rh.SAIL_DATE_FROM as checkinDate,
rh.SAIL_DATE_TO as checkoutDate,
'' as creationChannelCode,
rh.SOURCE_CODE as sourceLocationCode,
 '' as sourceLocationSubCode,
rh.res_init_date as creationDate,
rh.ship_code as destinationLocationCode,
'UK' as destinationLocationTimeZone,
rh.ship_code as originLocationCode,
'GMT' as originLocationTimeZone,
datediff(day,rh.sail_date_from::date,rh.sail_date_to::date) as duration,
rh.Res_id as externalReservationNumber,
max(re.event_timestamp) as lastModified,
'' as onRequest,
'' as orderBy,
'' as reservationNumber,
cl.language as language,
'' as sessionID,
rh.res_status as status,
'' as transactionReference,
'' as cancelNumber,
'' as cancelDate,
'' as externalCancelNumber,
'' as cancelReason,
rh.res_id as reservationName,
'' as affiliateCode,
'' as trace
from warner_base.seaware.res_header rh
left join warner_base.seaware.res_event re on rh.res_id=re.res_id
left join warner_base.seaware.agency ag on rh.agency_id=ag.agency_id 
left join warner_base.seaware.res_guest rg on rh.res_id=rg.res_id 
left join warner_base.seaware.client cl on rg.client_id=cl.client_id
group by rh.Res_id, rh.SAIL_DATE_FROM,
ag.agency_type,
rh.SAIL_DATE_FROM,
rh.SAIL_DATE_TO,
creationChannelCode,
rh.SOURCE_CODE,
sourceLocationSubCode,
rh.res_init_date,
rh.ship_code ,
destinationLocationTimeZone,
rh.ship_code,
originLocationTimeZone,
duration,
cl.language,
sessionID,
res_status,
transactionReference,
cancelNumber,
cancelDate,
externalCancelNumber,
cancelReason,
reservationName,
affiliateCode,
trace);

GRANT SELECT ON  VIEW WARNER_STORE.APS_SHARE.VW_RESERVATION_DETAILS to database role warner_store.aps_share;

USE SCHEMA warner_store.aps_share;

show VIEWs LIKE 'VW_%';

USE ROLE dba;

USE SCHEMA warner_raw.seaware_aps;

--DROP VIEW WARNER_STORE.SEAWARE_APS.AM_CODE;
DROP VIEW WARNER_STORE.SEAWARE_APS.CLIENT_TYPE;
DROP VIEW WARNER_STORE.SEAWARE_APS.COMPONENT_TYPE;
DROP VIEW WARNER_STORE.SEAWARE_APS.PACKAGE_ITINERARY;
DROP VIEW WARNER_STORE.SEAWARE_APS.PRODUCT_TYPE;
DROP VIEW WARNER_STORE.SEAWARE_APS.PREFERENCE_TYPE;

--DROP SECURE VIEW WARNER_BASE.SEAWARE_APS.AM_CODE;
DROP VIEW WARNER_BASE.SEAWARE_APS.CLIENT_TYPE;
DROP VIEW WARNER_BASE.SEAWARE_APS.COMPONENT_TYPE;
DROP VIEW WARNER_BASE.SEAWARE_APS.PACKAGE_ITINERARY;
DROP VIEW WARNER_BASE.SEAWARE_APS.PRODUCT_TYPE;
DROP VIEW WARNER_BASE.SEAWARE_APS.PREFERENCE_TYPE;

--CREATE VIEW WARNER_BASE.SEAWARE_APS.AM_CODE
--( AMENITY_CODE, RECORD_ID, AM_CATEGORY, AMENITY_TYPE, PROVIDER_CODE, AMENITY_NAME, COMMENTS, USE_TAX, SUBCODE_MANDATORY, MANDATORY_BEFORE_DLV, CODE_ACTIVE, ADDON_RESTRICTED, ADDON_ORDER_BASIS, ADDON_INV_ITEM_TYPE, ADDON_COMPONENT_TYPE, INCLUDE_IN_ORDER, DISPLAY_PER_PACKAGE, IMAGE_ID, APPLY_TO_ALL_GUESTS, SELL_LIMIT_WEIGHT, VEHICLE_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE ) 
--AS SELECT AMENITY_CODE, RECORD_ID, AM_CATEGORY, AMENITY_TYPE, PROVIDER_CODE, AMENITY_NAME, COMMENTS, USE_TAX, SUBCODE_MANDATORY, MANDATORY_BEFORE_DLV, CODE_ACTIVE, ADDON_RESTRICTED, ADDON_ORDER_BASIS, ADDON_INV_ITEM_TYPE, ADDON_COMPONENT_TYPE, INCLUDE_IN_ORDER, DISPLAY_PER_PACKAGE, IMAGE_ID, APPLY_TO_ALL_GUESTS, SELL_LIMIT_WEIGHT, VEHICLE_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
--FROM WARNER_RAW.SEAWARE_APS.AM_CODE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.CLIENT_TYPE
( CLIENT_TYPE, COMMENTS, CLIENT_TYPE_ID, POINTS_REQUIRED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CLIENT_TYPE, COMMENTS, CLIENT_TYPE_ID, POINTS_REQUIRED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CLIENT_TYPE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.COMPONENT_TYPE
( COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.COMPONENT_TYPE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.PACKAGE_ITINERARY
( ITIN_RECORD_ID, PACKAGE_TYPE, DAY_NUM_FROM, TIME_FROM, DAY_NUM_TO, TIME_TO, LOCATION_TYPE_FROM, LOCATION_CODE_FROM, LOCATION_TYPE_TO, LOCATION_CODE_TO, COMPONENT_TYPE, COMPONENT_CODE, COMPONENT_SUBCODE1, COMPONENT_SUBCODE2, COMPONENT_SUBCODE3, CAN_BE_EXCLUDED, IS_OPTIONAL, PACKAGE_LINKS_INCLUSIVE, COMMENTS, DESCRIPTION, SEQ_NUM, CITY_FROM, CITY_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ITIN_RECORD_ID, PACKAGE_TYPE, DAY_NUM_FROM, TIME_FROM, DAY_NUM_TO, TIME_TO, LOCATION_TYPE_FROM, LOCATION_CODE_FROM, LOCATION_TYPE_TO, LOCATION_CODE_TO, COMPONENT_TYPE, COMPONENT_CODE, COMPONENT_SUBCODE1, COMPONENT_SUBCODE2, COMPONENT_SUBCODE3, CAN_BE_EXCLUDED, IS_OPTIONAL, PACKAGE_LINKS_INCLUSIVE, COMMENTS, DESCRIPTION, SEQ_NUM, CITY_FROM, CITY_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.PACKAGE_ITINERARY;

CREATE VIEW WARNER_BASE.SEAWARE_APS.PRODUCT_TYPE
( PRODUCT_TYPE_ID, PRODUCT_TYPE, COMMENTS, IS_DAILY, IS_ACTIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE, COMMENTS, IS_DAILY, IS_ACTIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.PRODUCT_TYPE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.PREFERENCE_TYPE
( PREFERENCE_TYPE, COMMENTS, PREFERENCE_TYPE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT PREFERENCE_TYPE, COMMENTS, PREFERENCE_TYPE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.PREFERENCE_TYPE;


--CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.AM_CODE
--( AMENITY_CODE, RECORD_ID, AM_CATEGORY, AMENITY_TYPE, PROVIDER_CODE, AMENITY_NAME, COMMENTS, USE_TAX, SUBCODE_MANDATORY, MANDATORY_BEFORE_DLV, CODE_ACTIVE, ADDON_RESTRICTED, ADDON_ORDER_BASIS, ADDON_INV_ITEM_TYPE, ADDON_COMPONENT_TYPE, INCLUDE_IN_ORDER, DISPLAY_PER_PACKAGE, IMAGE_ID, APPLY_TO_ALL_GUESTS, SELL_LIMIT_WEIGHT, VEHICLE_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE ) 
--AS SELECT AMENITY_CODE, RECORD_ID, AM_CATEGORY, AMENITY_TYPE, PROVIDER_CODE, AMENITY_NAME, COMMENTS, USE_TAX, SUBCODE_MANDATORY, MANDATORY_BEFORE_DLV, CODE_ACTIVE, ADDON_RESTRICTED, ADDON_ORDER_BASIS, ADDON_INV_ITEM_TYPE, ADDON_COMPONENT_TYPE, INCLUDE_IN_ORDER, DISPLAY_PER_PACKAGE, IMAGE_ID, APPLY_TO_ALL_GUESTS, SELL_LIMIT_WEIGHT, VEHICLE_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
--FROM WARNER_BASE.SEAWARE_APS.AM_CODE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CLIENT_TYPE
( CLIENT_TYPE, COMMENTS, CLIENT_TYPE_ID, POINTS_REQUIRED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CLIENT_TYPE, COMMENTS, CLIENT_TYPE_ID, POINTS_REQUIRED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CLIENT_TYPE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.COMPONENT_TYPE
( COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.COMPONENT_TYPE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.PACKAGE_ITINERARY
( ITIN_RECORD_ID, PACKAGE_TYPE, DAY_NUM_FROM, TIME_FROM, DAY_NUM_TO, TIME_TO, LOCATION_TYPE_FROM, LOCATION_CODE_FROM, LOCATION_TYPE_TO, LOCATION_CODE_TO, COMPONENT_TYPE, COMPONENT_CODE, COMPONENT_SUBCODE1, COMPONENT_SUBCODE2, COMPONENT_SUBCODE3, CAN_BE_EXCLUDED, IS_OPTIONAL, PACKAGE_LINKS_INCLUSIVE, COMMENTS, DESCRIPTION, SEQ_NUM, CITY_FROM, CITY_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ITIN_RECORD_ID, PACKAGE_TYPE, DAY_NUM_FROM, TIME_FROM, DAY_NUM_TO, TIME_TO, LOCATION_TYPE_FROM, LOCATION_CODE_FROM, LOCATION_TYPE_TO, LOCATION_CODE_TO, COMPONENT_TYPE, COMPONENT_CODE, COMPONENT_SUBCODE1, COMPONENT_SUBCODE2, COMPONENT_SUBCODE3, CAN_BE_EXCLUDED, IS_OPTIONAL, PACKAGE_LINKS_INCLUSIVE, COMMENTS, DESCRIPTION, SEQ_NUM, CITY_FROM, CITY_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.PACKAGE_ITINERARY;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.PRODUCT_TYPE
( PRODUCT_TYPE_ID, PRODUCT_TYPE, COMMENTS, IS_DAILY, IS_ACTIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE, COMMENTS, IS_DAILY, IS_ACTIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.PRODUCT_TYPE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.PREFERENCE_TYPE
( PREFERENCE_TYPE, COMMENTS, PREFERENCE_TYPE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT PREFERENCE_TYPE, COMMENTS, PREFERENCE_TYPE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.PREFERENCE_TYPE;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.AM_CODE to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CLIENT_TYPE to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.COMPONENT_TYPE to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.PACKAGE_ITINERARY to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.PRODUCT_TYPE to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.PREFERENCE_TYPE to database role warner_store.aps_share;


--More bloody tables

USE ROLE DBA;

CREATE VIEW WARNER_BASE.SEAWARE_APS.CABIN_ATTRIBUTE
( CABIN_ATTR_ID, CABIN_ATTR_CODE, CABIN_ATTR_NAME, IS_ATTR_UNIQUE, IS_ATTR_COUNTABLE, IS_ATTR_EXTENDED, IS_ATTR_MANDATORY, COMMENTS, IMAGE_ID, USE_FOR_SHOPPING, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CABIN_ATTR_ID, CABIN_ATTR_CODE, CABIN_ATTR_NAME, IS_ATTR_UNIQUE, IS_ATTR_COUNTABLE, IS_ATTR_EXTENDED, IS_ATTR_MANDATORY, COMMENTS, IMAGE_ID, USE_FOR_SHOPPING, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_ATTRIBUTE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.CABIN_ATTRIBUTE_LINK
( SHIP_CODE, CABIN_NUMBER, CABIN_ATTR_ID, SEQ_NUMBER, CABIN_ATTR_COUNTER, CABIN_ATTR_EXT_INFO, RECORD_ID, EFF_SAIL_FROM, EFF_SAIL_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SHIP_CODE, CABIN_NUMBER, CABIN_ATTR_ID, SEQ_NUMBER, CABIN_ATTR_COUNTER, CABIN_ATTR_EXT_INFO, RECORD_ID, EFF_SAIL_FROM, EFF_SAIL_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_ATTRIBUTE_LINK;

CREATE VIEW WARNER_BASE.SEAWARE_APS.CABIN_CAT_GEN_LNK_CABIN_CAT
( RECORD_ID, CABIN_CATEGORY_GENERIC, SHIP_CODE, CABIN_CATEGORY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, CABIN_CATEGORY_GENERIC, SHIP_CODE, CABIN_CATEGORY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_CAT_GEN_LNK_CABIN_CAT;

CREATE VIEW WARNER_BASE.SEAWARE_APS.CABIN_CATEGORY
( CABIN_CATEGORY, CABIN_CATEGORY_ID, COMMENTS, IMAGE_ID, CABIN_CAPACITY, CABIN_CATEGORY_RANK, SHIP_CODE, IS_ACTIVE, ALLOW_AUTO_ASGN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CABIN_CATEGORY, CABIN_CATEGORY_ID, COMMENTS, IMAGE_ID, CABIN_CAPACITY, CABIN_CATEGORY_RANK, SHIP_CODE, IS_ACTIVE, ALLOW_AUTO_ASGN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_CATEGORY;

CREATE VIEW WARNER_BASE.SEAWARE_APS.CABIN_CATEGORY_COMMENTS
( RECORD_ID, SHIP_CODE, CABIN_CATEGORY, EFF_FROM, EFF_TO, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, SHIP_CODE, CABIN_CATEGORY, EFF_FROM, EFF_TO, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_CATEGORY_COMMENTS;

CREATE VIEW WARNER_BASE.SEAWARE_APS.CABIN_CATEGORY_GENERIC
( RECORD_ID, CABIN_CATEGORY_GENERIC, COMMENTS, "RANK", HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, CABIN_CATEGORY_GENERIC, COMMENTS, "RANK", HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_CATEGORY_GENERIC;

CREATE VIEW WARNER_BASE.SEAWARE_APS.CABIN_LAYOUT
( CABIN_LAYOUT_ID, DECK_ID, "OBJECT", CABIN_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CABIN_LAYOUT_ID, DECK_ID, "OBJECT", CABIN_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_LAYOUT;

CREATE VIEW WARNER_BASE.SEAWARE_APS.SHIP_CABIN
( SHIP_CODE, CABIN_NUMBER, CABIN_ID, DECK_NUMBER, CABIN_NAME, COMMENTS, IMAGE_ID, CABIN_RANK, FIREZONE_CODE, EXT_CABIN_ID, RECORD_ADDED_MANUALLY, IS_SPARE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SHIP_CODE, CABIN_NUMBER, CABIN_ID, DECK_NUMBER, CABIN_NAME, COMMENTS, IMAGE_ID, CABIN_RANK, FIREZONE_CODE, EXT_CABIN_ID, RECORD_ADDED_MANUALLY, IS_SPARE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.SHIP_CABIN;

CREATE VIEW WARNER_BASE.SEAWARE_APS.SHIP_CABIN_CTG_LINK
( RECORD_ID, SHIP_CODE, CABIN_NUMBER, CABIN_CATEGORY, EFF_SAIL_FROM, EFF_SAIL_TO, ROLLAWAY_BEDS, CABIN_CAPACITY, IS_ACTIVE, EXT_CABIN_CONTRACT_TYPE, ACCOUNT_NUMBER, DUPLEX_STATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, SHIP_CODE, CABIN_NUMBER, CABIN_CATEGORY, EFF_SAIL_FROM, EFF_SAIL_TO, ROLLAWAY_BEDS, CABIN_CAPACITY, IS_ACTIVE, EXT_CABIN_CONTRACT_TYPE, ACCOUNT_NUMBER, DUPLEX_STATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.SHIP_CABIN_CTG_LINK;

CREATE VIEW WARNER_BASE.SEAWARE_APS.SHIP_DECK
( SHIP_CODE, DECK_NUMBER, DECK_ID, DECK_NAME, IS_DECK_PAX, IMAGE_ID, DECK_CODE, LAYOUT_IMAGE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SHIP_CODE, DECK_NUMBER, DECK_ID, DECK_NAME, IS_DECK_PAX, IMAGE_ID, DECK_CODE, LAYOUT_IMAGE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.SHIP_DECK;

-----

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CABIN_ATTRIBUTE
( CABIN_ATTR_ID, CABIN_ATTR_CODE, CABIN_ATTR_NAME, IS_ATTR_UNIQUE, IS_ATTR_COUNTABLE, IS_ATTR_EXTENDED, IS_ATTR_MANDATORY, COMMENTS, IMAGE_ID, USE_FOR_SHOPPING, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CABIN_ATTR_ID, CABIN_ATTR_CODE, CABIN_ATTR_NAME, IS_ATTR_UNIQUE, IS_ATTR_COUNTABLE, IS_ATTR_EXTENDED, IS_ATTR_MANDATORY, COMMENTS, IMAGE_ID, USE_FOR_SHOPPING, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CABIN_ATTRIBUTE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CABIN_ATTRIBUTE_LINK
( SHIP_CODE, CABIN_NUMBER, CABIN_ATTR_ID, SEQ_NUMBER, CABIN_ATTR_COUNTER, CABIN_ATTR_EXT_INFO, RECORD_ID, EFF_SAIL_FROM, EFF_SAIL_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SHIP_CODE, CABIN_NUMBER, CABIN_ATTR_ID, SEQ_NUMBER, CABIN_ATTR_COUNTER, CABIN_ATTR_EXT_INFO, RECORD_ID, EFF_SAIL_FROM, EFF_SAIL_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CABIN_ATTRIBUTE_LINK;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CABIN_CAT_GEN_LNK_CABIN_CAT
( RECORD_ID, CABIN_CATEGORY_GENERIC, SHIP_CODE, CABIN_CATEGORY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, CABIN_CATEGORY_GENERIC, SHIP_CODE, CABIN_CATEGORY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CABIN_CAT_GEN_LNK_CABIN_CAT;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CABIN_CATEGORY
( CABIN_CATEGORY, CABIN_CATEGORY_ID, COMMENTS, IMAGE_ID, CABIN_CAPACITY, CABIN_CATEGORY_RANK, SHIP_CODE, IS_ACTIVE, ALLOW_AUTO_ASGN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CABIN_CATEGORY, CABIN_CATEGORY_ID, COMMENTS, IMAGE_ID, CABIN_CAPACITY, CABIN_CATEGORY_RANK, SHIP_CODE, IS_ACTIVE, ALLOW_AUTO_ASGN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CABIN_CATEGORY;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CABIN_CATEGORY_COMMENTS
( RECORD_ID, SHIP_CODE, CABIN_CATEGORY, EFF_FROM, EFF_TO, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, SHIP_CODE, CABIN_CATEGORY, EFF_FROM, EFF_TO, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CABIN_CATEGORY_COMMENTS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CABIN_CATEGORY_GENERIC
( RECORD_ID, CABIN_CATEGORY_GENERIC, COMMENTS, "RANK", HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, CABIN_CATEGORY_GENERIC, COMMENTS, "RANK", HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CABIN_CATEGORY_GENERIC;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CABIN_LAYOUT
( CABIN_LAYOUT_ID, DECK_ID, "OBJECT", CABIN_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CABIN_LAYOUT_ID, DECK_ID, "OBJECT", CABIN_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CABIN_LAYOUT;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.SHIP_CABIN
( SHIP_CODE, CABIN_NUMBER, CABIN_ID, DECK_NUMBER, CABIN_NAME, COMMENTS, IMAGE_ID, CABIN_RANK, FIREZONE_CODE, EXT_CABIN_ID, RECORD_ADDED_MANUALLY, IS_SPARE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SHIP_CODE, CABIN_NUMBER, CABIN_ID, DECK_NUMBER, CABIN_NAME, COMMENTS, IMAGE_ID, CABIN_RANK, FIREZONE_CODE, EXT_CABIN_ID, RECORD_ADDED_MANUALLY, IS_SPARE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.SHIP_CABIN;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.SHIP_CABIN_CTG_LINK
( RECORD_ID, SHIP_CODE, CABIN_NUMBER, CABIN_CATEGORY, EFF_SAIL_FROM, EFF_SAIL_TO, ROLLAWAY_BEDS, CABIN_CAPACITY, IS_ACTIVE, EXT_CABIN_CONTRACT_TYPE, ACCOUNT_NUMBER, DUPLEX_STATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, SHIP_CODE, CABIN_NUMBER, CABIN_CATEGORY, EFF_SAIL_FROM, EFF_SAIL_TO, ROLLAWAY_BEDS, CABIN_CAPACITY, IS_ACTIVE, EXT_CABIN_CONTRACT_TYPE, ACCOUNT_NUMBER, DUPLEX_STATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.SHIP_CABIN_CTG_LINK;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.SHIP_DECK
( SHIP_CODE, DECK_NUMBER, DECK_ID, DECK_NAME, IS_DECK_PAX, IMAGE_ID, DECK_CODE, LAYOUT_IMAGE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SHIP_CODE, DECK_NUMBER, DECK_ID, DECK_NAME, IS_DECK_PAX, IMAGE_ID, DECK_CODE, LAYOUT_IMAGE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.SHIP_DECK;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CABIN_ATTRIBUTE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CABIN_ATTRIBUTE_LINK TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CABIN_CAT_GEN_LNK_CABIN_CAT TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CABIN_CATEGORY TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CABIN_CATEGORY_COMMENTS TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CABIN_CATEGORY_GENERIC TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CABIN_LAYOUT TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.SHIP_CABIN TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.SHIP_CABIN_CTG_LINK TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.SHIP_DECK TO DATABASE ROLE WARNER_STORE.APS_SHARE;

--22/05/2024

USE ROLE DBA;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_HISTORY_HEADER
(GROUP_ID, GROUP_UPDATE_ID, OPERATOR_ID, TIME_STAMP, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE)
AS SELECT GROUP_ID, GROUP_UPDATE_ID, OPERATOR_ID, TIME_STAMP, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_HISTORY_HEADER;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_HISTORY_HEADER
(GROUP_ID, GROUP_UPDATE_ID, OPERATOR_ID, TIME_STAMP, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE)
AS SELECT GROUP_ID, GROUP_UPDATE_ID, OPERATOR_ID, TIME_STAMP, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_HISTORY_HEADER;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_HISTORY_HEADER TO DATABASE ROLE WARNER_STORE.APS_SHARE;

--17/06/2024

USE ROLE DBA;

CREATE VIEW WARNER_BASE.SEAWARE_APS.UNIT_CATEGORY_ATTR_LINK
( RECORD_ID, SHIP_CODE, CABIN_CATEGORY, ATTRIBUTE_CODE, ATTRIBUTE_VALUE_STR, ATTRIBUTE_VALUE_INT, VALUE_SEQN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, SHIP_CODE, CABIN_CATEGORY, ATTRIBUTE_CODE, ATTRIBUTE_VALUE_STR, ATTRIBUTE_VALUE_INT, VALUE_SEQN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.UNIT_CATEGORY_ATTR_LINK;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.UNIT_CATEGORY_ATTR_LINK
( RECORD_ID, SHIP_CODE, CABIN_CATEGORY, ATTRIBUTE_CODE, ATTRIBUTE_VALUE_STR, ATTRIBUTE_VALUE_INT, VALUE_SEQN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, SHIP_CODE, CABIN_CATEGORY, ATTRIBUTE_CODE, ATTRIBUTE_VALUE_STR, ATTRIBUTE_VALUE_INT, VALUE_SEQN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.UNIT_CATEGORY_ATTR_LINK;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.UNIT_CATEGORY_ATTR_LINK TO DATABASE ROLE WARNER_STORE.APS_SHARE;

-- 13/09/2024

USE ROLE dba;


CREATE VIEW WARNER_BASE.SEAWARE_APS.FERRY_REQUEST
( REQUEST_ID, ENTITY_TYPE, ENTITY_ID, STATUS, CONFIRMATION_NUMBER, PROVIDER_ID, VEHICLE_TYPE, N_OF_PEOPLE, ROUTE_DEP, ROUTE_RET, DATE_DEP, DATE_RET, TIME_DEP, TIME_RET, VEHICLE_MAKE, VEHICLE_LENGTH, VEHICLE_REGISTRATION, CHANGES, COMMENTS, COST, COST_CURRENCY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT REQUEST_ID, ENTITY_TYPE, ENTITY_ID, STATUS, CONFIRMATION_NUMBER, PROVIDER_ID, VEHICLE_TYPE, N_OF_PEOPLE, ROUTE_DEP, ROUTE_RET, DATE_DEP, DATE_RET, TIME_DEP, TIME_RET, VEHICLE_MAKE, VEHICLE_LENGTH, VEHICLE_REGISTRATION, CHANGES, COMMENTS, COST, COST_CURRENCY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.FERRY_REQUEST;

CREATE VIEW WARNER_BASE.SEAWARE_APS.FERRY_ROUTE
( ROUTE_ID, ROUTE_CODE, PORT_FROM, PORT_TO, COMMENTS, DISPLAY_ORDER, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ROUTE_ID, ROUTE_CODE, PORT_FROM, PORT_TO, COMMENTS, DISPLAY_ORDER, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.FERRY_ROUTE;;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.FERRY_REQUEST
( REQUEST_ID, ENTITY_TYPE, ENTITY_ID, STATUS, CONFIRMATION_NUMBER, PROVIDER_ID, VEHICLE_TYPE, N_OF_PEOPLE, ROUTE_DEP, ROUTE_RET, DATE_DEP, DATE_RET, TIME_DEP, TIME_RET, VEHICLE_MAKE, VEHICLE_LENGTH, VEHICLE_REGISTRATION, CHANGES, COMMENTS, COST, COST_CURRENCY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT REQUEST_ID, ENTITY_TYPE, ENTITY_ID, STATUS, CONFIRMATION_NUMBER, PROVIDER_ID, VEHICLE_TYPE, N_OF_PEOPLE, ROUTE_DEP, ROUTE_RET, DATE_DEP, DATE_RET, TIME_DEP, TIME_RET, VEHICLE_MAKE, VEHICLE_LENGTH, VEHICLE_REGISTRATION, CHANGES, COMMENTS, COST, COST_CURRENCY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.FERRY_REQUEST;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.FERRY_ROUTE
( ROUTE_ID, ROUTE_CODE, PORT_FROM, PORT_TO, COMMENTS, DISPLAY_ORDER, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ROUTE_ID, ROUTE_CODE, PORT_FROM, PORT_TO, COMMENTS, DISPLAY_ORDER, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.FERRY_ROUTE;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.FERRY_REQUEST TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.FERRY_ROUTE TO DATABASE ROLE WARNER_STORE.APS_SHARE;


-- 29/11/2024

USE ROLE DBA;

CREATE VIEW WARNER_BASE.SEAWARE_APS.RES_PARAM
( RES_PARAM_ID, PARAM_VALUE, RES_ID, PARAM_CODE, IS_CASE_SENSITIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_PARAM_ID, PARAM_VALUE, RES_ID, PARAM_CODE, IS_CASE_SENSITIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_PARAM;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_PARAM
( RES_PARAM_ID, PARAM_VALUE, RES_ID, PARAM_CODE, IS_CASE_SENSITIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_PARAM_ID, PARAM_VALUE, RES_ID, PARAM_CODE, IS_CASE_SENSITIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_PARAM;

USE ROLE securityadmin;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_PARAM TO DATABASE ROLE WARNER_STORE.APS_SHARE;

-- 13/01/2025

USE ROLE securityadmin;

GRANT reference_usage ON DATABASE warner_dwh_dev TO SHARE warner_aps_share;


-- 10/02/2025

use ROLE dba;

USE SCHEMA warner_store.seaware_aps;

SHOW views;

CREATE VIEW WARNER_BASE.SEAWARE_APS.REFERRAL_SOURCE
( REFERRAL_SOURCE_ID, REFERRAL_SOURCE, REFERRAL_TYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT REFERRAL_SOURCE_ID, REFERRAL_SOURCE, REFERRAL_TYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.REFERRAL_SOURCE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.REFERRAL_SOURCE
( REFERRAL_SOURCE_ID, REFERRAL_SOURCE, REFERRAL_TYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT REFERRAL_SOURCE_ID, REFERRAL_SOURCE, REFERRAL_TYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.REFERRAL_SOURCE;

USE ROLE securityadmin;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.REFERRAL_SOURCE TO DATABASE ROLE WARNER_STORE.APS_SHARE;

-- 13/03/2025

USE ROLE DBA;

CREATE VIEW WARNER_BASE.SEAWARE_APS.ACC_INVOICE_DETAIL
( ENTITY_TYPE, ENTITY_ID, PARAM_NAME, PARAM_VALUE, "TIMESTAMP", RECORD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ENTITY_TYPE, ENTITY_ID, PARAM_NAME, PARAM_VALUE, "TIMESTAMP", RECORD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.ACC_INVOICE_DETAIL;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_ACC_RES_GRP_CONSORTIUM_ID
( AGRID, CRID, ALRID, ARID, HRID, UNIONID, TRANS_ID, SEASON, U_CONSORTIUM_ID, U_ABTA_NUMBER, U_CONSORTIUM_NAME, AGENCY_ID, ABTA_NUMBER, AGENCY_TYPE, AGENCY_NAME, CONSORTIUM_ABTA, CONSORTIUM_TYPE, CONSORTIUM_NAME, AGENCY_LINK_ID, CONSORTIUM_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGRID, CRID, ALRID, ARID, HRID, UNIONID, TRANS_ID, SEASON, U_CONSORTIUM_ID, U_ABTA_NUMBER, U_CONSORTIUM_NAME, AGENCY_ID, ABTA_NUMBER, AGENCY_TYPE, AGENCY_NAME, CONSORTIUM_ABTA, CONSORTIUM_TYPE, CONSORTIUM_NAME, AGENCY_LINK_ID, CONSORTIUM_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_ACC_RES_GRP_CONSORTIUM_ID;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_ACC_TRANS_AGEN_TERMS
( TRANS_ID, AGENCY_ID, IS_VALID_TERMS, IS_VALID_TERMS_F, IS_VALID_TERMS_G, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TRANS_ID, AGENCY_ID, IS_VALID_TERMS, IS_VALID_TERMS_F, IS_VALID_TERMS_G, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_ACC_TRANS_AGEN_TERMS;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_ACC_TRANS_DETAIL_AGENBNK
( ARID, UNION_ID, TRANS_ID, TRANS_TIME_STAMP, TRANS_TYPE, AR_AP_SEQ_ID, AR_AP_DUE_DATE, RES_ID, AGENCY_ID, GROUP_ID, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID, ENTITY_TYPE, ENTITY_ID, SOURCE_ENTITY_KEY, ENTITY_KEY, JOIN_KEY, JOIN_TRANS_TYPE_KEY, DEBIT, DEBIT_LEFT, CREDIT, CREDIT_LEFT, DEBIT_BASE, CREDIT_BASE, BALANCE, NET_DEPTOR, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE ) 
AS SELECT ARID, UNION_ID, TRANS_ID, TRANS_TIME_STAMP, TRANS_TYPE, AR_AP_SEQ_ID, AR_AP_DUE_DATE, RES_ID, AGENCY_ID, GROUP_ID, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID, ENTITY_TYPE, ENTITY_ID, SOURCE_ENTITY_KEY, ENTITY_KEY, JOIN_KEY, JOIN_TRANS_TYPE_KEY, DEBIT, DEBIT_LEFT, CREDIT, CREDIT_LEFT, DEBIT_BASE, CREDIT_BASE, BALANCE, NET_DEPTOR, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_ACC_TRANS_DETAIL_AGENBNK;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_AGENCY_ADDRESS
( ARID, AARID, ERID, PRID, FRID, RID2, RID3, RID4, RID5, AGENCY_ID, AGENCY_NAME, AGENCY_NAME_TYPED, AGENCY_TYPE, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, COMMENTS, AGENCY_EMAIL, AGENCY_PHONE, AGENCY_FAX, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ARID, AARID, ERID, PRID, FRID, RID2, RID3, RID4, RID5, AGENCY_ID, AGENCY_NAME, AGENCY_NAME_TYPED, AGENCY_TYPE, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, COMMENTS, AGENCY_EMAIL, AGENCY_PHONE, AGENCY_FAX, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_AGENCY_ADDRESS;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_GRP_CHG_BY_SEASON
( HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_GRP_CHG_BY_SEASON;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_GRP_INV_BY_SEASON
( HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_GRP_INV_BY_SEASON;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_GRP_NET_DUE_BY_SEASON
( HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_GRP_NET_DUE_BY_SEASON;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_GRP_PAYMENT_DUE
( GROUP_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT GROUP_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_GRP_PAYMENT_DUE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_RES_CHG_BY_SEASON
( HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_CHG_BY_SEASON;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_RES_FIRST_CLIENT
( GRID, CRID, RES_ID, GUEST_ID, GUEST_SEQN, CLIENT_ID, FULL_NAME, LAST_NAME, FIRST_NAME, MIDDLE_NAME, TITLE, HOUSEHOLD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT GRID, CRID, RES_ID, GUEST_ID, GUEST_SEQN, CLIENT_ID, FULL_NAME, LAST_NAME, FIRST_NAME, MIDDLE_NAME, TITLE, HOUSEHOLD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_FIRST_CLIENT;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_RES_INV_BY_SEASON
( HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_INV_BY_SEASON;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_RES_NET_DUE_BY_SEASON
( HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_NET_DUE_BY_SEASON;

CREATE VIEW WARNER_BASE.SEAWARE_APS.MV_RES_PAYMENT_DUE
( RES_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_PAYMENT_DUE;



CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.ACC_INVOICE_DETAIL
( ENTITY_TYPE, ENTITY_ID, PARAM_NAME, PARAM_VALUE, "TIMESTAMP", RECORD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ENTITY_TYPE, ENTITY_ID, PARAM_NAME, PARAM_VALUE, "TIMESTAMP", RECORD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.ACC_INVOICE_DETAIL;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_ACC_RES_GRP_CONSORTIUM_ID
( AGRID, CRID, ALRID, ARID, HRID, UNIONID, TRANS_ID, SEASON, U_CONSORTIUM_ID, U_ABTA_NUMBER, U_CONSORTIUM_NAME, AGENCY_ID, ABTA_NUMBER, AGENCY_TYPE, AGENCY_NAME, CONSORTIUM_ABTA, CONSORTIUM_TYPE, CONSORTIUM_NAME, AGENCY_LINK_ID, CONSORTIUM_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGRID, CRID, ALRID, ARID, HRID, UNIONID, TRANS_ID, SEASON, U_CONSORTIUM_ID, U_ABTA_NUMBER, U_CONSORTIUM_NAME, AGENCY_ID, ABTA_NUMBER, AGENCY_TYPE, AGENCY_NAME, CONSORTIUM_ABTA, CONSORTIUM_TYPE, CONSORTIUM_NAME, AGENCY_LINK_ID, CONSORTIUM_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_ACC_RES_GRP_CONSORTIUM_ID;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_ACC_TRANS_AGEN_TERMS
( TRANS_ID, AGENCY_ID, IS_VALID_TERMS, IS_VALID_TERMS_F, IS_VALID_TERMS_G, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TRANS_ID, AGENCY_ID, IS_VALID_TERMS, IS_VALID_TERMS_F, IS_VALID_TERMS_G, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_ACC_TRANS_AGEN_TERMS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_ACC_TRANS_DETAIL_AGENBNK
( ARID, UNION_ID, TRANS_ID, TRANS_TIME_STAMP, TRANS_TYPE, AR_AP_SEQ_ID, AR_AP_DUE_DATE, RES_ID, AGENCY_ID, GROUP_ID, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID, ENTITY_TYPE, ENTITY_ID, SOURCE_ENTITY_KEY, ENTITY_KEY, JOIN_KEY, JOIN_TRANS_TYPE_KEY, DEBIT, DEBIT_LEFT, CREDIT, CREDIT_LEFT, DEBIT_BASE, CREDIT_BASE, BALANCE, NET_DEPTOR, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE ) 
AS SELECT ARID, UNION_ID, TRANS_ID, TRANS_TIME_STAMP, TRANS_TYPE, AR_AP_SEQ_ID, AR_AP_DUE_DATE, RES_ID, AGENCY_ID, GROUP_ID, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID, ENTITY_TYPE, ENTITY_ID, SOURCE_ENTITY_KEY, ENTITY_KEY, JOIN_KEY, JOIN_TRANS_TYPE_KEY, DEBIT, DEBIT_LEFT, CREDIT, CREDIT_LEFT, DEBIT_BASE, CREDIT_BASE, BALANCE, NET_DEPTOR, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_ACC_TRANS_DETAIL_AGENBNK;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_AGENCY_ADDRESS
( ARID, AARID, ERID, PRID, FRID, RID2, RID3, RID4, RID5, AGENCY_ID, AGENCY_NAME, AGENCY_NAME_TYPED, AGENCY_TYPE, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, COMMENTS, AGENCY_EMAIL, AGENCY_PHONE, AGENCY_FAX, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ARID, AARID, ERID, PRID, FRID, RID2, RID3, RID4, RID5, AGENCY_ID, AGENCY_NAME, AGENCY_NAME_TYPED, AGENCY_TYPE, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, COMMENTS, AGENCY_EMAIL, AGENCY_PHONE, AGENCY_FAX, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_AGENCY_ADDRESS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_GRP_CHG_BY_SEASON
( HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_GRP_CHG_BY_SEASON;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_GRP_INV_BY_SEASON
( HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_GRP_INV_BY_SEASON;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_GRP_NET_DUE_BY_SEASON
( HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_GRP_NET_DUE_BY_SEASON;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_GRP_PAYMENT_DUE
( GROUP_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT GROUP_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_GRP_PAYMENT_DUE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_RES_CHG_BY_SEASON
( HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_RES_CHG_BY_SEASON;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_RES_FIRST_CLIENT
( GRID, CRID, RES_ID, GUEST_ID, GUEST_SEQN, CLIENT_ID, FULL_NAME, LAST_NAME, FIRST_NAME, MIDDLE_NAME, TITLE, HOUSEHOLD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT GRID, CRID, RES_ID, GUEST_ID, GUEST_SEQN, CLIENT_ID, FULL_NAME, LAST_NAME, FIRST_NAME, MIDDLE_NAME, TITLE, HOUSEHOLD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_RES_FIRST_CLIENT;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_RES_INV_BY_SEASON
( HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_RES_INV_BY_SEASON;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_RES_NET_DUE_BY_SEASON
( HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_RES_NET_DUE_BY_SEASON;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.MV_RES_PAYMENT_DUE
( RES_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.MV_RES_PAYMENT_DUE;



