use role dba;

use schema haven_raw.playsafe;

with cte as (
SELECT SITECODE, SITENAME, REGION, MACHINEREF, INDEX, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_COLLECTIONS
qualify row_number () over (partition by sitecode, machineref, collectionid order by index) = 1)
select SITECODE, SITENAME, REGION,  MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
from cte
group by SITECODE, SITENAME, REGION, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
having count(*) > 1;
;

SELECT SITECODE, SITENAME, REGION, MACHINEREF, INDEX, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_COLLECTIONS
qualify row_number () over (partition by sitecode, sitename, machineref, collectionid order by index) = 1;


SELECT SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE
from haven_raw.playsafe.namco_machine_inventory_list
qualify row_number() over (partition by sitecode, machineref, serialnumber, _etleap_lookback_date order by index) = 1;

SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, count(*)
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_COLLECTIONS
GROUP BY SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
having count(*) > 1
order by collectiondatetime, collectionid
;

select * from namco_machine_collections
where collectionid = 'C0240BCHU000608549';

select  * 
-- exclude collectiondaysonsite 
from haven_raw.playsafe.crown_machine_inventory_list 
where 
    sitecode = 2608 and
    machineref = 'MC002240'
order by _etleap_lookback_date;

select  * 
-- exclude collectiondaysonsite 
from haven_raw.playsafe.namco_machine_inventory_list 
--where 
--    sitecode = 2608 and
--    machineref = 'MC002240'
order by _etleap_lookback_date
limit 1000;


selecT get_ddl('vieW', 'haven_base.playsafe.namco_machine_inventory_LIST');




create or replace view NAMCO_MACHINE_INVENTORY_LIST(
	SITECODE,
	SITENAME,
	REGION,
	INDEX,
	MACHINEREF,
	MACHINENAME,
	CLASS,
	TYPE,
	GENERATESINCOME,
	POP,
	JACKPOT,
	LOCATION,
	ZONE,
	SERIALNUMBER,
	INSTALLATIONDATE,
	REMOVALDATE,
	COLLECTIONDAYSONSITE
) as SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST
GROUP BY SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE;



