SELECT TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, COMMENT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG = 'haven_raw' AND NOT ENDSWITH(TABLE_NAME, '__B') AND NOT ENDSWITH(TABLE_NAME, '_STAGE') AND NOT ENDSWITH(TABLE_NAME, '_CLONE')AND NOT STARTSWITH(TABLE_NAME, 'HVR_ST') ORDER BY TABLE_NAME, ORDINAL_POSITION;


use database haven_base;
use schema aztec_complex;

select
    xx.table_name,
    xx.column_name original_column_name, 
    
    upper(trim(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(xx.column_name, ' ', '_'), '.', '_'), '-','_'), '&','_AND_'), '(','_'), ')','_'), '#', '_NUMBER_'), '+', '_PLUS_'), '/', '_'), '%', '_PERCENT_'), '__', '_'), ' _')) normalised_column_name
        
from haven_base.information_Schema.columns xx
where 
    -- filter anything that does not contain alphanumeric or underscore
    column_name not rlike '[A-Z0-9_]*'
;


select trim('_bob_', ' _');



CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_COMPLEX.PAYMENTS ( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", PAYMENT, AMOUNT, CHANGE, PAYMENTMETHOD, RECEIPTNO, CORRECTEDORDER, MOVETYPE, TIP, PAYMENTCOUNT, LMDT, CASH_BACK, ISEFT, PROCESSED, PAYOUT, ISCASHBACK, OWNERID, AUTHORISER, ACCOUNTNUMBER, REPORTINGEMPLOYEEID, AMOUNTINTENDEREDCURRENCY, FORFEITAMOUNT, TERMINALSESSIONID, MONEYBELTPAYMENT, ORIGINALDATETIME ) AS SELECT "TRANSACTIONID", "DATE", "BUSINESSDATE", "TERMINALID", "EMPLOYEEID", "ACCOUNTID", "TRANSACTION NUMBER", "ORDER", "PAYMENT", "AMOUNT", "CHANGE", "PAYMENTMETHOD", "RECEIPTNO", "CORRECTEDORDER", "MOVETYPE", "TIP", "PAYMENTCOUNT", "LMDT", "CASH BACK", "ISEFT", "PROCESSED", "PAYOUT", "ISCASHBACK", "OWNERID", "AUTHORISER", "ACCOUNTNUMBER", "REPORTINGEMPLOYEEID", "AMOUNTINTENDEREDCURRENCY", "FORFEITAMOUNT", "TERMINALSESSIONID", "MONEYBELTPAYMENT", "ORIGINALDATETIME" FROM "HAVEN_RAW"."AZTEC_COMPLEX"."PAYMENTS";


CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_COMPLEX.AC_STAFFMESSAGE ( ID, NAME, ACTIONTYPEID, INTERVALTYPEID, "FROM", SUBJECT, BODY, MINIMUMAGECHECK, STARTDATE, ENDDATE, CREATIONDATE, CREATEDBY, ISSITEMESSAGE, DELETED ) AS SELECT "ID", "NAME", "ACTIONTYPEID", "INTERVALTYPEID", "FROM", "SUBJECT", "BODY", "MINIMUMAGECHECK", "STARTDATE", "ENDDATE", "CREATIONDATE", "CREATEDBY", "ISSITEMESSAGE", "DELETED" FROM "HAVEN_RAW"."AZTEC_COMPLEX"."AC_STAFFMESSAGE";

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_COMPLEX.BILLDISCOUNTLINE ( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", MOVETYPE, BILLDISCOUNTLINE, BILLPROMOTION, AMOUNT, CORRECTEDORDER, ACCOUNTNUMBER, AUTHORISATIONREFERENCE, MANUALLYKEYED, EXTERNALMODEID, EXTERNALQUALIFYINGPRODUCT, PERCENTAGE, CANCELLINGINCREASEBALANCEDISCOUNT, LMDT, OWNERID, AUTHORISER, ORIGINALDATETIME, DISCOUNTREASON, APPLIESTOORDERLINEFAMILY ) AS SELECT "TRANSACTIONID", "DATE", "BUSINESSDATE", "TERMINALID", "EMPLOYEEID", "ACCOUNTID", "TRANSACTION NUMBER", "ORDER", "MOVETYPE", "BILLDISCOUNTLINE", "BILLPROMOTION", "AMOUNT", "CORRECTEDORDER", "ACCOUNTNUMBER", "AUTHORISATIONREFERENCE", "MANUALLYKEYED", "EXTERNALMODEID", "EXTERNALQUALIFYINGPRODUCT", "PERCENTAGE", "CANCELLINGINCREASEBALANCEDISCOUNT", "LMDT", "OWNERID", "AUTHORISER", "ORIGINALDATETIME", "DISCOUNTREASON", "APPLIESTOORDERLINEFAMILY" FROM "HAVEN_RAW"."AZTEC_COMPLEX"."BILLDISCOUNTLINE";


CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_COMPLEX.PRODUCTLINE ( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", ORDERLINE, CORRECTEDORDERLINE, QUANTITY, PRICE, MOVETYPE, PRODUCT, HALF, RATIO, PORTION, CORRECTIONMETHOD, CORRECTIONREASON, TARIFFPRICE, LMDT, OWNERID, UNITPRICE, AUTHORISER, SPECIALVOUCHERSALE, ORDERDESTINATION, MULTICHOICEMODE, PRICETYPE, ORIGINALDATETIME ) AS SELECT "TRANSACTIONID", "DATE", "BUSINESSDATE", "TERMINALID", "EMPLOYEEID", "ACCOUNTID", "TRANSACTION NUMBER", "ORDER", "ORDERLINE", "CORRECTEDORDERLINE", "QUANTITY", "PRICE", "MOVETYPE", "PRODUCT", "HALF", "RATIO", "PORTION", "CORRECTIONMETHOD", "CORRECTIONREASON", "TARIFFPRICE", "LMDT", "OWNERID", "UNITPRICE", "AUTHORISER", "SPECIALVOUCHERSALE", "ORDERDESTINATION", "MULTICHOICEMODE", "PRICETYPE", "ORIGINALDATETIME" FROM "HAVEN_RAW"."AZTEC_COMPLEX"."PRODUCTLINE";

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_COMPLEX.THEMEBUTTONMENU ( "ORDER", LEVEL, BUTTONSQL, MENUTITLE, MENUTITLESQL, MULTITITLE, MULTITITLEFILTERFIELD ) AS SELECT "ORDER", "LEVEL", "BUTTONSQL", "MENUTITLE", "MENUTITLESQL", "MULTITITLE", "MULTITITLEFILTERFIELD" FROM "HAVEN_RAW"."AZTEC_COMPLEX"."THEMEBUTTONMENU";