use role dba;
use database haven_base;
use schema bigquery;

--HAV001_Tables.01a_sessions_by_date_with_flags
--HAV001_Tables.02_events_by_date
--HAV001_Tables.03_Holiday_Ecom
--HAV001_Tables.04_transactions_by_date
--HAV001_Tables.11_ecom_action_types
--HAV002_Dashboard_Tables.01_daily_trading_dashboard_with_arrays
--HAV003_Tableau_Tables.01_searches_and_bookings_summary
--HAV003_Tableau_Tables.02_weekly_summary
--HAV003_Tableau_Tables.03_booking_ids_by_channel
--HAV003_Tableau_Tables.05a_product_impressions_period_only_QA
--HAV003_Tableau_Tables.06_product_impressions_and_bookings_by_week
--HAV003_Tableau_Tables.07_product_impressions_and_bookings_by_period


--haven_base

create or replace view HAVEN_BASE.BIGQUERY.GA_SESSIONS AS 
SELECT GEONETWORK, SESSION_TOTALS, VISITNUMBER, CHANNELGROUPING, VISITORID, PRIVACYINFO, CLIENTID, VISITID, CUSTOMDIMENSIONS, USERID, DEVICE, FULLVISITORID, VISITSTARTTIME, SESSION_DATE, SOCIALENGAGEMENTTYPE, SESSION_HITS, TRAFFICSOURCE
FROM HAVEN_RAW.BIGQUERY.GA_SESSIONS;

CREATE OR REPLACE VIEW HAVEN_BASE.BIGQUERY.SESSIONS_BY_DATE_WITH_FLAGS AS
SELECT NEWVISITS, ISTRUEDIRECT, REFERRALPATH, "SOURCE", MEDIUM, CAMPAIGN, ADCONTENT, SESSION_DATE, FULLVISITORID, VISITID, VISITNUMBER, VISITSTARTTIME, PAGEVIEWS, TIMEONSITE, BOUNCES, FLAG_TOURING_BOOKINGS, FLAG_OWNERSHIP, FLAG_OWNERSHIP_SEARCH, FLAG_OWNERSHIP_HOME_DETAILS, FLAG_ACTIVITIES_BOOKINGS, FLAG_POST_BOOKING, FLAG_TOURING_SEARCH, FLAG_TOURING_CHECKOUT_EXTRAS, FLAG_TOURING_CHECKOUT_IDENTITY, FLAG_TOURING_CHECKOUT_GUEST_DETAILS, FLAG_TOURING_CHECKOUT_PAYMENT_OPTIONS, FLAG_TOURING_CHECKOUT_PAYMENT_DETAILS, FLAG_TOURING_CHECKOUT_BOOKING_CONFIRMATION, FLAG_DISCOVER_FOOD_DRINK, FLAG_DISCOVER, FLAG_SUPPORT, FLAG_SUPPORT_ARRIVAL_INFO, FLAG_MY_ACCOUNT, FLAG_HELP_CENTRE, FLAG_ABOUT_US, FLAG_COVID, FLAG_HOLS_CHECKOUT_EXTRAS, FLAG_HOLS_CHECKOUT_IDENTITY, FLAG_HOLS_CHECKOUT_GUEST_DETAILS, FLAG_HOLS_CHECKOUT_PAYMENT_OPTIONS, FLAG_HOLS_CHECKOUT_PAYMENT_DETAILS, FLAG_HOLS_CHECKOUT_BOOKING_CONFIRMATION, FLAG_HOLS_BOOKINGS, FLAG_TOURING_SESSION, SESSION_KEYWORD, LANDING_PAGE, DEVICECATEGORY, BROWSER, BROWSERSIZE, BROWSERVERSION, OPERATINGSYSTEM, OPERATINGSYSTEMVERSION, COUNTRY, LATITUDE, LONGITUDE, FLAG_TRANSACTIONAL, FLAG_HOLS_SEARCH, FLAG_HOLS_CURATED_SEARCH
FROM HAVEN_RAW.BIGQUERY.SESSIONS_BY_DATE_WITH_FLAGS;


create or replace view HAVEN_BASE.BIGQUERY.EVENTS_BY_DATE AS
SELECT EVENT, EVENT_DATE, FULLVISITORID, VISITID, EVENT_TIMESTAMP_RAW, DURATION, ARRIVAL_DATE, WEEKS_TO_ARRIVAL, GUESTS_ADULTS, GUESTS_CHILDREN, CS_FILTER_BEDROOMS, CS_FILTER_MANUFACTURER, CS_LIST_NUMBER_OF_RESULTS, VALID_SEARCH_RESULT_VIEWS, CONTENTGROUP_PAGE_REFERRER, HOL_BOOKING_ID, REVENUE, CS_VISIT_DATE, CS_VISIT_TIME, CS_ENQUIRY_ID, CS_FILTER_PRICE, TIMESTAMP_READABLE, PAGEPATH, FRIENDLY_PAGE_NAME, NUM_RESULTS, HOLIDAY_TYPE, CONTENTGROUP_PAGE_TYPE_SUBTYPE, CONTENTGROUP_PAGE_FULL_URL, CONTENTGROUP_PAGE_FRIENDLY_NAME, CONTENTGROUP_PAGE_TYPE, GUESTS_INFANTS, GUESTS_DOGS, GUESTS_TOTAL, GUEST_NEW_REPEAT, HOLIDAY_PACKAGE, PARK_COUNTRY, PARK_REGION, PARK_NAME, PARK_CODE
FROM HAVEN_RAW.BIGQUERY.EVENTS_BY_DATE;

create or replace view HAVEN_BASE.BIGQUERY.HOLIDAY_ECOM AS
SELECT SORT_ORDER, FILTER_PACKAGE_TYPE, FILTER_BEDROOMS, FILTER_ACCOM_TYPE, PRODUCT_LIST_NAME, PRODUCT_LIST_POSITION, PRODUCT_CATEGORY, HOLIDAY_DATE, DEVICE_CATEGORY, OPERATING_SYSTEM, BROWSER, HOLIDAY_TYPE, SEARCH_PARK_COUNTRY, SEARCH_WEEKS_TO_ARRIVAL, SEARCH_NUM_ADULTS, SEARCH_NUM_CHILDREN, SEARCH_NUM_INFANTS, SEARCH_NUM_DOGS, SEARCH_NUM_GUESTS, SEARCH_NUM_UNDER_16S, PRODUCT_PARK_NAME, PRODUCT_PARK_CODE, PRODUCT_GRADE, PRODUCT_BEDROOMS, PRODUCT_SLEEPS, PRODUCT_OFFER_FLAG, SEARCH_YEAR_PERIOD, SEARCH_ARRIVAL_DATE, SEARCH_ARRIVAL_MONTH, SEARCH_ARRIVAL_YEAR, SEARCH_ARRIVAL_YEAR_FLAG, SEARCH_ARRIVAL_DAY_OF_WEEK, SEARCH_DAYS_TO_ARRIVAL, PRODUCT_PRE_DISCOUNT_PRICE, PRODUCT_DISCOUNT_AMOUNT, PRODUCT_GRADE_CODE, PRODUCT_PACKAGE_TYPE, PRODUCT_IMPRESSIONS, PRODUCT_MORE_DETAILS, PRODUCT_CLICKS, PRODUCT_NAME, PRODUCT_VARIANT, PRODUCT_ID, PRODUCT_PRICE, PRODUCT_PRICE_BAND, PRODUCT_PARK_COUNTRY, PRODUCT_PARK_REGION, SEARCH_PARK_REGION, SEARCH_PARK_NAME, SEARCH_PARK_CODE, SEARCH_DURATION, SEARCH_DURATION_TOP, SEARCH_PARTY_COMP, SEARCH_PACKAGE_ID, SEARCH_PERIOD
FROM HAVEN_RAW.BIGQUERY.HOLIDAY_ECOM;

create or replace view HAVEN_BASE.BIGQUERY.TRANSACTIONS_BY_DATE AS
SELECT TRANSACTIONID, TRANSACTION_DATE, HIT_TIME, FULLVISITORID, VISITID, TRANSACTIONREVENUE, VISITSTARTTIME, TIMESTAMP_RAW, BUSINESS_AREA, ACT_TIME, PARK_CODE, PARK_NAME, ACT_NAME, ACT_DATE, FRIENDLY_PAGE_NAME, GUEST_TYPE, ACT_CATEGORY, HOLIDAY_PACKAGE, GUESTS_TOTAL, HOL_BOOKING_ID, DURATION, ARRIVAL_DATE, GUESTS_DOGS, GUESTS_CHILDREN, GUESTS_INFANTS, GUEST_NEW_REPEAT, GUESTS_ADULTS
FROM HAVEN_RAW.BIGQUERY.TRANSACTIONS_BY_DATE;

create or replace view HAVEN_BASE.BIGQUERY.ECOM_ACTION_TYPES AS
SELECT PRODUCT_PARK_CODE, FULLVISITORID, FILTER_PACKAGE_TYPE, TRANSACTION_ID, FILTER_ACCOM_TYPE, NUM_RESULTS, RESULTS_BATCH, PRODUCT_IMPRESSIONS, ECOM_ACTION_TYPE, SEARCH_NUM_INFANTS, OPERATING_SYSTEM, BROWSER, SEARCH_NUM_DOGS, SEARCH_NUM_GUESTS, DATA_LAYER_EVENT, PRODUCT_PRE_DISCOUNT_PRICE, PRODUCT_DISCOUNT_AMOUNT, PRODUCT_CLICKS, HOL_BOOKING_ID, DEVICE_CATEGORY, SEARCH_NUM_UNDER_16S, SORT_ORDER, FILTER_BEDROOMS, PRODUCT_ARRIVAL_DATE_STRING, PRODUCT_ARRIVAL_DATE, PRODUCT_ID, PRODUCT_PRICE, HOLIDAY_TYPE, FRIENDLY_PAGE_NAME, SEARCH_DURATION, PRODUCT_BEDROOMS, SEARCH_NUM_ADULTS, SEARCH_NUM_CHILDREN, PRODUCT_SLEEPS, PRODUCT_OFFER_FLAG, PRODUCT_GRADE_CODE, PRODUCT_PACKAGE_TYPE, PRODUCT_LIST_NAME, VISITID, ACTION_TYPE_DATE, TIMESTAMP_RAW, SEARCH_PARK_NAME, PRODUCT_LIST_POSITION, PRODUCT_VARIANT, SEARCH_PARTY_COMP, SEARCH_PACKAGE_ID, PRODUCT_DURATION, PRODUCT_GRADE, PRODUCT_CATEGORY, PRODUCT_NAME, SEARCH_PARK_CODE, SEARCH_ARRIVAL_DATE_STRING, SEARCH_ARRIVAL_DATE
FROM HAVEN_RAW.BIGQUERY.ECOM_ACTION_TYPES;

create or replace view HAVEN_BASE.BIGQUERY.DAILY_TRADING_DASHBOARD_WITH_ARRAYS AS
SELECT DAILY_TRADING_DATE, DAILY_TRADING_CHANNEL, DAILY_TRADING_CHANNEL_LEVEL_2, DAILY_TRADING_CHANNEL_LEVEL_3, DAILY_TRADING_KEYWORD, LANDING_PAGE, BOOKINGS_ACTIVITIES, REVENUE_ACTIVITIES, BOOKINGS_NEW, BOOKINGS_REPEAT, BOOKINGS_THIS_YEAR, BOOKINGS_NEXT_YEAR, SESSIONS_WITH_CHECKOUT_GUEST_DETAILS, SESSIONS_WITH_CHECKOUT_PAYMENT_OPTIONS, SESSIONS_WITH_CHECKOUT_PAYMENT_DETAILS, SESSIONS_WITH_CHECKOUT_BOOKING_CONFIRMATION, SESSIONS_WITH_OWNERSHIP_SEARCH, SESSIONS_WITH_OWNERSHIP_HOME_DETAILS, SESSIONS_WITH_POST_BOOKING_ACTIVITY, TIMEONSITE, SESSIONS_WITH_SEARCH, SESSIONS_WITH_CURATED_SEARCH, SESSIONS_WITH_CHECKOUT_EXTRAS, SESSIONS_WITH_CHECKOUT_IDENTITY, SESSIONS_WITH_HELP_CENTRE_ACTIVITY, COST_RAW, COST_INCL_AD_SERVING, COST_TARGET, SEARCHES_THIS_YEAR, SEARCHES_NEXT_YEAR, SEARCH_SUMMARY, TRANSACTION_DETAILS, ENQUIRY_DETAILS, SESSION_WITH_CS_WEB_LEAD, SESSION_WITH_CS_WEB_BROCHURE, SESSION_WITH_CS_WEB_VISIT, FB_LEADS, BOOKINGS_HOLIDAYS, REVENUE_HOLIDAYS, BOOKINGS_SELFCATERING, REVENUE_SELFCATERING, BOOKINGS_TOURING, REVENUE_TOURING, FLAG_TRANSACTIONAL, FLAG_OWNERSHIP, LANDING_PAGE_GRP, LANDING_PAGE_PARK, DAILY_TRADING_SESSIONS, DAILY_TRADING_BOUNCES, DAILY_TRADING_PAGEVIEWS
FROM HAVEN_RAW.BIGQUERY.DAILY_TRADING_DASHBOARD_WITH_ARRAYS;

create or replace view HAVEN_BASE.BIGQUERY.TARGET_01_SEARCHES_AND_BOOKINGS_SUMMARY AS
SELECT "DATE", SEARCHES, ARRIVAL_PERIOD, PARK_CODE, BOOKINGS, ARRIVAL_DATE, HOLIDAY_TYPE, MATILLION_BATCH_ID, MATILLION_UPDATED_TIMESTAMP
FROM HAVEN_RAW.BIGQUERY.TARGET_01_SEARCHES_AND_BOOKINGS_SUMMARY;

create or replace view HAVEN_BASE.BIGQUERY.TARGET_02_WEEKLY_SUMMARY AS
SELECT PARKCODE, SEARCHES, ARRIVAL_WEEK, BOOKINGS, HOLIDAY_TYPE, BOOK_WEEK, MATILLION_BATCH_ID, MATILLION_UPDATED_TIMESTAMP
FROM HAVEN_RAW.BIGQUERY.TARGET_02_WEEKLY_SUMMARY;

create or replace view HAVEN_BASE.BIGQUERY.BOOKING_IDS_BY_CHANNEL AS
SELECT BOOKING_ID_BY_CHANNEL_DATE, CHANNEL_LEVEL_3, CHANNEL, CHANNEL_LEVEL_2, HOL_BOOKING_ID, REVENUE
FROM HAVEN_RAW.BIGQUERY.BOOKING_IDS_BY_CHANNEL;

create or replace VIEW HAVEN_BASE.BIGQUERY.PRODUCT_IMPRESSIONS_PERIOD_ONLY_QA AS
SELECT PRODUCT_LIST_NAME, BOOKINGS, ARRIVAL_PERIOD, HOLIDAY_TYPE, SEARCHES, BOOK_WEEK
FROM HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_PERIOD_ONLY_QA;

create or replace view HAVEN_BASE.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_WEEK AS
SELECT BOOK_WEEK, CHANNEL, HOLIDAY_TYPE, SEARCHES, ARRIVAL_WEEK, PRODUCT_LIST_NAME, BOOKINGS, PARK_CODE
FROM HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_WEEK;

create or replace view HAVEN_BASE.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_PERIOD AS
SELECT BOOK_WEEK, HOLIDAY_TYPE, CHANNEL, ARRIVAL_PERIOD, PRODUCT_LIST_NAME, SEARCHES, BOOKINGS
FROM HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_PERIOD;


use role securityadmin;
grant role _haven_base__bigquery__reader to role haven_commercial;

--haven_store
create or replace view HAVEN_BASE.BIGQUERY.GA_SESSIONS AS 
SELECT GEONETWORK, SESSION_TOTALS, VISITNUMBER, CHANNELGROUPING, VISITORID, PRIVACYINFO, CLIENTID, VISITID, CUSTOMDIMENSIONS, USERID, DEVICE, FULLVISITORID, VISITSTARTTIME, SESSION_DATE, SOCIALENGAGEMENTTYPE, SESSION_HITS, TRAFFICSOURCE
FROM HAVEN_RAW.BIGQUERY.GA_SESSIONS;

create or replace view HAVEN_BASE.BIGQUERY.EVENTS_BY_DATE AS
SELECT EVENT, EVENT_DATE, FULLVISITORID, VISITID, EVENT_TIMESTAMP_RAW, DURATION, ARRIVAL_DATE, WEEKS_TO_ARRIVAL, GUESTS_ADULTS, GUESTS_CHILDREN, CS_FILTER_BEDROOMS, CS_FILTER_MANUFACTURER, CS_LIST_NUMBER_OF_RESULTS, VALID_SEARCH_RESULT_VIEWS, CONTENTGROUP_PAGE_REFERRER, HOL_BOOKING_ID, REVENUE, CS_VISIT_DATE, CS_VISIT_TIME, CS_ENQUIRY_ID, CS_FILTER_PRICE, TIMESTAMP_READABLE, PAGEPATH, FRIENDLY_PAGE_NAME, NUM_RESULTS, HOLIDAY_TYPE, CONTENTGROUP_PAGE_TYPE_SUBTYPE, CONTENTGROUP_PAGE_FULL_URL, CONTENTGROUP_PAGE_FRIENDLY_NAME, CONTENTGROUP_PAGE_TYPE, GUESTS_INFANTS, GUESTS_DOGS, GUESTS_TOTAL, GUEST_NEW_REPEAT, HOLIDAY_PACKAGE, PARK_COUNTRY, PARK_REGION, PARK_NAME, PARK_CODE
FROM HAVEN_RAW.BIGQUERY.EVENTS_BY_DATE;

create or replace view HAVEN_BASE.BIGQUERY.HOLIDAY_ECOM AS
SELECT SORT_ORDER, FILTER_PACKAGE_TYPE, FILTER_BEDROOMS, FILTER_ACCOM_TYPE, PRODUCT_LIST_NAME, PRODUCT_LIST_POSITION, PRODUCT_CATEGORY, HOLIDAY_DATE, DEVICE_CATEGORY, OPERATING_SYSTEM, BROWSER, HOLIDAY_TYPE, SEARCH_PARK_COUNTRY, SEARCH_WEEKS_TO_ARRIVAL, SEARCH_NUM_ADULTS, SEARCH_NUM_CHILDREN, SEARCH_NUM_INFANTS, SEARCH_NUM_DOGS, SEARCH_NUM_GUESTS, SEARCH_NUM_UNDER_16S, PRODUCT_PARK_NAME, PRODUCT_PARK_CODE, PRODUCT_GRADE, PRODUCT_BEDROOMS, PRODUCT_SLEEPS, PRODUCT_OFFER_FLAG, SEARCH_YEAR_PERIOD, SEARCH_ARRIVAL_DATE, SEARCH_ARRIVAL_MONTH, SEARCH_ARRIVAL_YEAR, SEARCH_ARRIVAL_YEAR_FLAG, SEARCH_ARRIVAL_DAY_OF_WEEK, SEARCH_DAYS_TO_ARRIVAL, PRODUCT_PRE_DISCOUNT_PRICE, PRODUCT_DISCOUNT_AMOUNT, PRODUCT_GRADE_CODE, PRODUCT_PACKAGE_TYPE, PRODUCT_IMPRESSIONS, PRODUCT_MORE_DETAILS, PRODUCT_CLICKS, PRODUCT_NAME, PRODUCT_VARIANT, PRODUCT_ID, PRODUCT_PRICE, PRODUCT_PRICE_BAND, PRODUCT_PARK_COUNTRY, PRODUCT_PARK_REGION, SEARCH_PARK_REGION, SEARCH_PARK_NAME, SEARCH_PARK_CODE, SEARCH_DURATION, SEARCH_DURATION_TOP, SEARCH_PARTY_COMP, SEARCH_PACKAGE_ID, SEARCH_PERIOD
FROM HAVEN_RAW.BIGQUERY.HOLIDAY_ECOM;

create or replace view HAVEN_BASE.BIGQUERY.TRANSACTIONS_BY_DATE AS
SELECT TRANSACTIONID, TRANSACTION_DATE, HIT_TIME, FULLVISITORID, VISITID, TRANSACTIONREVENUE, VISITSTARTTIME, TIMESTAMP_RAW, BUSINESS_AREA, ACT_TIME, PARK_CODE, PARK_NAME, ACT_NAME, ACT_DATE, FRIENDLY_PAGE_NAME, GUEST_TYPE, ACT_CATEGORY, HOLIDAY_PACKAGE, GUESTS_TOTAL, HOL_BOOKING_ID, DURATION, ARRIVAL_DATE, GUESTS_DOGS, GUESTS_CHILDREN, GUESTS_INFANTS, GUEST_NEW_REPEAT, GUESTS_ADULTS
FROM HAVEN_RAW.BIGQUERY.TRANSACTIONS_BY_DATE;

create or replace view HAVEN_BASE.BIGQUERY.ECOM_ACTION_TYPES AS
SELECT PRODUCT_PARK_CODE, FULLVISITORID, FILTER_PACKAGE_TYPE, TRANSACTION_ID, FILTER_ACCOM_TYPE, NUM_RESULTS, RESULTS_BATCH, PRODUCT_IMPRESSIONS, ECOM_ACTION_TYPE, SEARCH_NUM_INFANTS, OPERATING_SYSTEM, BROWSER, SEARCH_NUM_DOGS, SEARCH_NUM_GUESTS, DATA_LAYER_EVENT, PRODUCT_PRE_DISCOUNT_PRICE, PRODUCT_DISCOUNT_AMOUNT, PRODUCT_CLICKS, HOL_BOOKING_ID, DEVICE_CATEGORY, SEARCH_NUM_UNDER_16S, SORT_ORDER, FILTER_BEDROOMS, PRODUCT_ARRIVAL_DATE_STRING, PRODUCT_ARRIVAL_DATE, PRODUCT_ID, PRODUCT_PRICE, HOLIDAY_TYPE, FRIENDLY_PAGE_NAME, SEARCH_DURATION, PRODUCT_BEDROOMS, SEARCH_NUM_ADULTS, SEARCH_NUM_CHILDREN, PRODUCT_SLEEPS, PRODUCT_OFFER_FLAG, PRODUCT_GRADE_CODE, PRODUCT_PACKAGE_TYPE, PRODUCT_LIST_NAME, VISITID, ACTION_TYPE_DATE, TIMESTAMP_RAW, SEARCH_PARK_NAME, PRODUCT_LIST_POSITION, PRODUCT_VARIANT, SEARCH_PARTY_COMP, SEARCH_PACKAGE_ID, PRODUCT_DURATION, PRODUCT_GRADE, PRODUCT_CATEGORY, PRODUCT_NAME, SEARCH_PARK_CODE, SEARCH_ARRIVAL_DATE_STRING, SEARCH_ARRIVAL_DATE
FROM HAVEN_RAW.BIGQUERY.ECOM_ACTION_TYPES;

create or replace view HAVEN_BASE.BIGQUERY.DAILY_TRADING_DASHBOARD_WITH_ARRAYS AS
SELECT DAILY_TRADING_DATE, DAILY_TRADING_CHANNEL, DAILY_TRADING_CHANNEL_LEVEL_2, DAILY_TRADING_CHANNEL_LEVEL_3, DAILY_TRADING_KEYWORD, LANDING_PAGE, BOOKINGS_ACTIVITIES, REVENUE_ACTIVITIES, BOOKINGS_NEW, BOOKINGS_REPEAT, BOOKINGS_THIS_YEAR, BOOKINGS_NEXT_YEAR, SESSIONS_WITH_CHECKOUT_GUEST_DETAILS, SESSIONS_WITH_CHECKOUT_PAYMENT_OPTIONS, SESSIONS_WITH_CHECKOUT_PAYMENT_DETAILS, SESSIONS_WITH_CHECKOUT_BOOKING_CONFIRMATION, SESSIONS_WITH_OWNERSHIP_SEARCH, SESSIONS_WITH_OWNERSHIP_HOME_DETAILS, SESSIONS_WITH_POST_BOOKING_ACTIVITY, TIMEONSITE, SESSIONS_WITH_SEARCH, SESSIONS_WITH_CURATED_SEARCH, SESSIONS_WITH_CHECKOUT_EXTRAS, SESSIONS_WITH_CHECKOUT_IDENTITY, SESSIONS_WITH_HELP_CENTRE_ACTIVITY, COST_RAW, COST_INCL_AD_SERVING, COST_TARGET, SEARCHES_THIS_YEAR, SEARCHES_NEXT_YEAR, SEARCH_SUMMARY, TRANSACTION_DETAILS, ENQUIRY_DETAILS, SESSION_WITH_CS_WEB_LEAD, SESSION_WITH_CS_WEB_BROCHURE, SESSION_WITH_CS_WEB_VISIT, FB_LEADS, BOOKINGS_HOLIDAYS, REVENUE_HOLIDAYS, BOOKINGS_SELFCATERING, REVENUE_SELFCATERING, BOOKINGS_TOURING, REVENUE_TOURING, FLAG_TRANSACTIONAL, FLAG_OWNERSHIP, LANDING_PAGE_GRP, LANDING_PAGE_PARK, DAILY_TRADING_SESSIONS, DAILY_TRADING_BOUNCES, DAILY_TRADING_PAGEVIEWS
FROM HAVEN_RAW.BIGQUERY.DAILY_TRADING_DASHBOARD_WITH_ARRAYS;

create or replace view HAVEN_BASE.BIGQUERY.SEARCHES_AND_BOOKINGS_SUMMARY AS
SELECT BOOKINGS, ARRIVAL_DATE, PARK_CODE, SEARCHES, ARRIVAL_PERIOD, SEARCHES_AND_BOOKINGS_DATE, HOLIDAY_TYPE
FROM HAVEN_RAW.BIGQUERY.SEARCHES_AND_BOOKINGS_SUMMARY;

drop view HAVEN_BASE.BIGQUERY.TARGET_01_SEARCHES_AND_BOOKINGS_SUMMARY;

create or replace view HAVEN_BASE.BIGQUERY.WEEKLY_SUMMARY AS
SELECT PARKCODE, SEARCHES, ARRIVAL_WEEK, BOOKINGS, HOLIDAY_TYPE, BOOK_WEEK, MATILLION_BATCH_ID, MATILLION_UPDATED_TIMESTAMP
FROM HAVEN_RAW.BIGQUERY.TARGET_02_WEEKLY_SUMMARY;


drop view HAVEN_BASE.BIGQUERY.TARGET_02_WEEKLY_SUMMARY;

create or replace view HAVEN_BASE.BIGQUERY.BOOKING_IDS_BY_CHANNEL AS
SELECT BOOKING_ID_BY_CHANNEL_DATE, CHANNEL_LEVEL_3, CHANNEL, CHANNEL_LEVEL_2, HOL_BOOKING_ID, REVENUE
FROM HAVEN_RAW.BIGQUERY.BOOKING_IDS_BY_CHANNEL;

create or replace VIEW HAVEN_BASE.BIGQUERY.PRODUCT_IMPRESSIONS_PERIOD_ONLY_QA AS
SELECT PRODUCT_LIST_NAME, BOOKINGS, ARRIVAL_PERIOD, HOLIDAY_TYPE, SEARCHES, BOOK_WEEK
FROM HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_PERIOD_ONLY_QA;

create or replace view HAVEN_BASE.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_WEEK AS
SELECT BOOK_WEEK, CHANNEL, HOLIDAY_TYPE, SEARCHES, ARRIVAL_WEEK, PRODUCT_LIST_NAME, BOOKINGS, PARK_CODE
FROM HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_WEEK;

create or replace view HAVEN_BASE.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_PERIOD AS
SELECT BOOK_WEEK, HOLIDAY_TYPE, CHANNEL, ARRIVAL_PERIOD, PRODUCT_LIST_NAME, SEARCHES, BOOKINGS
FROM HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_PERIOD;


use role haven_commercial;

SELECT DAILY_TRADING_DATE, DAILY_TRADING_CHANNEL, DAILY_TRADING_CHANNEL_LEVEL_2, DAILY_TRADING_CHANNEL_LEVEL_3, DAILY_TRADING_KEYWORD, LANDING_PAGE, BOOKINGS_ACTIVITIES, REVENUE_ACTIVITIES, BOOKINGS_NEW, BOOKINGS_REPEAT, BOOKINGS_THIS_YEAR, BOOKINGS_NEXT_YEAR, SESSIONS_WITH_CHECKOUT_GUEST_DETAILS, SESSIONS_WITH_CHECKOUT_PAYMENT_OPTIONS, SESSIONS_WITH_CHECKOUT_PAYMENT_DETAILS, SESSIONS_WITH_CHECKOUT_BOOKING_CONFIRMATION, SESSIONS_WITH_OWNERSHIP_SEARCH, SESSIONS_WITH_OWNERSHIP_HOME_DETAILS, SESSIONS_WITH_POST_BOOKING_ACTIVITY, TIMEONSITE, SESSIONS_WITH_SEARCH, SESSIONS_WITH_CURATED_SEARCH, SESSIONS_WITH_CHECKOUT_EXTRAS, SESSIONS_WITH_CHECKOUT_IDENTITY, SESSIONS_WITH_HELP_CENTRE_ACTIVITY, COST_RAW, COST_INCL_AD_SERVING, COST_TARGET, SEARCHES_THIS_YEAR, SEARCHES_NEXT_YEAR, SEARCH_SUMMARY, TRANSACTION_DETAILS, ENQUIRY_DETAILS, SESSION_WITH_CS_WEB_LEAD, SESSION_WITH_CS_WEB_BROCHURE, SESSION_WITH_CS_WEB_VISIT, FB_LEADS, BOOKINGS_HOLIDAYS, REVENUE_HOLIDAYS, BOOKINGS_SELFCATERING, REVENUE_SELFCATERING, BOOKINGS_TOURING, REVENUE_TOURING, FLAG_TRANSACTIONAL, FLAG_OWNERSHIP, LANDING_PAGE_GRP, LANDING_PAGE_PARK, DAILY_TRADING_SESSIONS, DAILY_TRADING_BOUNCES, DAILY_TRADING_PAGEVIEWS
FROM HAVEN_RAW.BIGQUERY.DAILY_TRADING_DASHBOARD_WITH_ARRAYS;
SELECT "date", "channel", "channel_level_2", "channel_level_3", "keyword", "landing_page", "bookings_activities", "revenue_activities", "bookings_new", "bookings_repeat", "bookings_this_year", "bookings_next_year", "sessions_with_checkout_guest_details", "sessions_with_checkout_payment_options", "sessions_with_checkout_payment_details", "sessions_with_checkout_booking_confirmation", "sessions_with_ownership_search", "sessions_with_ownership_home_details", "sessions_with_post_booking_activity", "timeOnSite", "sessions_with_search", "sessions_with_curated_search", "sessions_with_checkout_extras", "sessions_with_checkout_identity", "sessions_with_help_centre_activity", "cost_raw", "cost_incl_ad_serving", "cost_target", "searches_this_year", "searches_next_year", "search_summary", "transaction_details", "enquiry_details", "session_with_cs_web_lead", "session_with_cs_web_brochure", "session_with_cs_web_visit", "fb_leads", "bookings_holidays", "revenue_holidays", "bookings_selfcatering", "revenue_selfcatering", "bookings_touring", "revenue_touring", "flag_transactional", "flag_ownership", "landing_page_grp", "landing_page_park", "sessions", "bounces", "pageviews"
FROM HAVEN_RAW.BIGQUERY.DAILY_TRADING_DASHBOARD_WITH_ARRAYS_STAGE;



1111