use ROLE accountadmin;


--arn:aws:iam::445123880475:role/blg-havprodserv-snowflake-kappture-role
--blg-havprodserv-kappture-s3 
--BD78472_SFCRole=2_Bo0AxE4Bn/xypSFy1E/HSso0W+M=


create storage integration blg_havprodserv_kappture_s3_integration
  type = external_stage
  storage_provider = s3
  storage_aws_role_arn = 'arn:aws:iam::445123880475:role/blg-havprodserv-snowflake-kappture-role'
  enabled = TRUE
  storage_aws_external_id = 'BD78472_SFCRole=2_Bo0AxE4Bn/xypSFy1E/HSso0W+M='
  storage_allowed_locations = ('s3://blg-havprodserv-kappture-s3/');

 
DESC integration blg_havprodserv_kappture_s3_integration;

USE ROLE securityadmin;

GRANT USAGE ON integration blg_havprodserv_kappture_s3_integration TO ROLE dba;
GRANT USAGE ON integration blg_havprodserv_kappture_s3_integration TO ROLE HAVEN_batch_dataload;

use ROLE dba;

create or replace stage  haven_raw.kappture.blg_havprodserv_kappture_s3_integration_stage
  STORAGE_INTEGRATION = blg_havprodserv_kappture_s3_integration
  URL = 's3://blg-havprodserv-kappture-s3/';

ls @haven_raw.kappture.blg_havprodserv_kappture_s3_integration_stage;
ls @haven_raw.kappture.blg_havdevserv_kappture_s3_integration_stage;

use ROLE dba;

create OR replace view haven_base.kappture.product_data
( LINETYPE, ORDERID, LOCALORDERID, ORDERTYPEID, DATETIME, SITEID, SITE, OUTLETID, OUTLET, OUTLETEXTERNALREFERENCE1, OUTLETEXTERNALREFERENCE2, OUTLETEXTERNALREFERENCE3, TERMINALID, TERMINAL, TERMINALREFERENCE, OPERATORID, OPERATOR, PRODUCTID, PRODUCT, REFERENCE, EXTERNALREFERENCE1, EXTERNALREFERENCE2, PRODUCTGROUPID, PRODUCTGROUP, PRODUCTGROUPS, PRODUCTGROPEXTERNALREFERENCE1, PRODUCTGROPEXTERNALREFERENCE2, PRODUCTGROPEXTERNALREFERENCE3, LINE, QUANTITY, GROSS, TOTALGROSS, NET, TOTALNET, TOTALTAX, TAX, TAXRATEN )
AS SELECT LINETYPE, ORDERID, LOCALORDERID, ORDERTYPEID, "DATETIME", SITEID, SITE, OUTLETID, OUTLET, OUTLETEXTERNALREFERENCE1, OUTLETEXTERNALREFERENCE2, OUTLETEXTERNALREFERENCE3, TERMINALID, TERMINAL, TERMINALREFERENCE, OPERATORID, OPERATOR, PRODUCTID, PRODUCT, "REFERENCE", EXTERNALREFERENCE1, EXTERNALREFERENCE2, PRODUCTGROUPID, PRODUCTGROUP, PRODUCTGROUPS, PRODUCTGROPEXTERNALREFERENCE1, PRODUCTGROPEXTERNALREFERENCE2, PRODUCTGROPEXTERNALREFERENCE3, LINE, QUANTITY, GROSS, TOTALGROSS, NET, TOTALNET, TOTALTAX, TAX, TAXRATE
FROM HAVEN_RAW.KAPPTURE.PRODUCT_TENDER_DATA
where linetype = 'P';

create OR replace view haven_base.kappture.tender_data
( LINETYPE, ORDERID, LOCALORDERID, ORDERTYPEID, DATETIME, SITEID, SITE, OUTLETID, OUTLET, OUTLETEXTERNALREFERENCE1, OUTLETEXTERNALREFERENCE2, OUTLETEXTERNALREFERENCE3, TERMINALID, TERMINAL, TERMINALREFERENCE, OPERATORID, OPERATOR, 
TenderId, Tender, TenderExternalReference1, TenderExternalReference2, TenderValue, TenderOver)
AS SELECT LINETYPE, ORDERID, LOCALORDERID, ORDERTYPEID, DATETIME, SITEID, SITE, OUTLETID, OUTLET, OUTLETEXTERNALREFERENCE1, OUTLETEXTERNALREFERENCE2, OUTLETEXTERNALREFERENCE3, TERMINALID, TERMINAL, TERMINALREFERENCE, OPERATORID, OPERATOR, 
PRODUCTID, PRODUCT, "REFERENCE", EXTERNALREFERENCE1, EXTERNALREFERENCE2, PRODUCTGROUPID
FROM HAVEN_RAW.KAPPTURE.PRODUCT_TENDER_DATA
where linetype = 'T';

SELECT * FROM haven_base.kappture.product_data LIMIT 20;
SELECT * FROM haven_base.kappture.tender_data LIMIT 20;

-- 16/07/2025

use ROLE dba;

USE DATABASE HAVEN_RAW;
USE SCHEMA KAPPTURE;

create OR replace file format haven_raw.kappture.BLG_HAVPRODSERV_KAPPTURE_S3_INTEGRATION_file_format
type = csv
EMPTY_FIELD_AS_NULL = true
ERROR_ON_COLUMN_COUNT_MISMATCH = false
;

create or replace stage  haven_raw.kappture.blg_havprodserv_kappture_s3_integration_stage
  STORAGE_INTEGRATION = blg_havprodserv_kappture_s3_integration
  URL = 's3://blg-havprodserv-kappture-s3/'
  file_format = (format_name = 'haven_raw.kappture.BLG_HAVPRODSERV_KAPPTURE_S3_INTEGRATION_file_format');

TRUNCATE TABLE HAVEN_RAW.KAPPTURE.product_data_test;

copy into HAVEN_RAW.KAPPTURE.product_data_test
from @BLG_HAVPRODSERV_KAPPTURE_S3_INTEGRATION_STAGE/to_snowflake;

TRUNCATE TABLE HAVEN_RAW.KAPPTURE.product_tender_data;

copy into HAVEN_RAW.KAPPTURE.product_tender_data
from @BLG_HAVPRODSERV_KAPPTURE_S3_INTEGRATION_STAGE/to_snowflake;

-- 17/07/2025

use ROLE dba;

use SCHEMA haven_raw.kappture;

ls @BLG_HAVPRODSERV_KAPPTURE_S3_INTEGRATION_STAGE;

copy into HAVEN_RAW.KAPPTURE.product_tender_data
from @BLG_HAVPRODSERV_KAPPTURE_S3_INTEGRATION_STAGE/to_snowflake;

SELECT count(*) FROM HAVEN_RAW.KAPPTURE.product_tender_data;


-- 25/07/2025

use role dba;

use SCHEMA haven_base.Kappture;

SELECT get_ddl('view', 'product_data');

create or replace view haven_base.Kappture.PRODUCT_DATA(
	LINETYPE,
	ORDERID,
	LOCALORDERID,
	ORDERTYPEID,
	DATETIME,
	SITEID,
	SITE,
	OUTLETID,
	OUTLET,
	OUTLETEXTERNALREFERENCE1,
	OUTLETEXTERNALREFERENCE2,
	OUTLETEXTERNALREFERENCE3,
	TERMINALID,
	TERMINAL,
	TERMINALREFERENCE,
	OPERATORID,
	OPERATOR,
	PRODUCTID,
	PRODUCT,
	REFERENCE,
	EXTERNALREFERENCE1,
	EXTERNALREFERENCE2,
	PRODUCTGROUPID,
	PRODUCTGROUP,
	PRODUCTGROUPS,
	PRODUCTGROPEXTERNALREFERENCE1,
	PRODUCTGROPEXTERNALREFERENCE2,
	PRODUCTGROPEXTERNALREFERENCE3,
	LINE, 
	QUANTITY, 
	UNITPRICE, 
	LINEGROSS, 
	LINENET, 
	LINETAX, 
	TAXRATE, 
	LINEDISCOUNTGROSS, 
	LINEDISCOUNTTAX
) as SELECT LINETYPE, ORDERID, LOCALORDERID, ORDERTYPEID, "DATETIME", SITEID, SITE, OUTLETID, OUTLET, OUTLETEXTERNALREFERENCE1, OUTLETEXTERNALREFERENCE2, OUTLETEXTERNALREFERENCE3, 
TERMINALID, TERMINAL, TERMINALREFERENCE, OPERATORID, OPERATOR, PRODUCTID, PRODUCT, "REFERENCE", EXTERNALREFERENCE1, EXTERNALREFERENCE2, PRODUCTGROUPID, PRODUCTGROUP, PRODUCTGROUPS, 
PRODUCTGROPEXTERNALREFERENCE1, PRODUCTGROPEXTERNALREFERENCE2, PRODUCTGROPEXTERNALREFERENCE3, LINE, QUANTITY, UNITPRICE, LINEGROSS, LINENET, LINETAX, TAXRATE, LINEDISCOUNTGROSS, LINEDISCOUNTTAX
FROM HAVEN_RAW.KAPPTURE.PRODUCT_TENDER_DATA
where linetype = 'P';

SELECT LINETYPE, ORDERID, LOCALORDERID, ORDERTYPEID, "DATETIME", SITEID, SITE, OUTLETID, OUTLET, OUTLETEXTERNALREFERENCE1, OUTLETEXTERNALREFERENCE2, OUTLETEXTERNALREFERENCE3, 
TERMINALID, TERMINAL, TERMINALREFERENCE, OPERATORID, OPERATOR, PRODUCTID, PRODUCT, "REFERENCE", EXTERNALREFERENCE1, EXTERNALREFERENCE2, PRODUCTGROUPID, PRODUCTGROUP, PRODUCTGROUPS, 
PRODUCTGROPEXTERNALREFERENCE1, PRODUCTGROPEXTERNALREFERENCE2, PRODUCTGROPEXTERNALREFERENCE3, LINE, QUANTITY, UNITPRICE, LINEGROSS, LINENET, LINETAX, TAXRATE, LINEDISCOUNTGROSS, LINEDISCOUNTTAX
FROM HAVEN_RAW.KAPPTURE.PRODUCT_TENDER_DATA;

SELECT * from haven_base.Kappture.PRODUCT_DATA
LIMIT 100;

SELECT * from haven_base.Kappture.TENDER_DATA
LIMIT 100;