USE ROLE dba;

create or replace view HAVEN_STORE.COMMERCIAL.BOOKING_IDS_BY_CHANNEL(
	DATE,
	CHANNEL,
	CHANNEL_LEVEL_2,
	CHANNEL_LEVEL_3,
	HOL_BOOKING_ID,
	REVENUE
) as 
SELECT DATE(BOOKING_ID_BY_CHANNEL_DATE), CHANNEL, CHANNEL_LEVEL_2, CHANNEL_LEVEL_3, HOL_BOOKING_ID, REVENUE
FROM HAVEN_BASE.BIGQUERY.BOOKING_IDS_BY_CHANNEL;

USE ROLE sysadmin;
DROP VIEW HAVEN_STORE.COMMERCIAL.HITS_HOL_SEARCH_RESULTS;
USE ROLE dba;

CREATE OR REPLACE VIEW HAVEN_BASE.BIGQUERY.HITS_HOL_SEARCH_RESULTS
(ARRIVAL_DATE, ARRIVAL_MONTH, ARRIVAL_YEAR, ARRIVAL_YEAR_FLAG, VALID_SEARCH_RESULT_VIEWS_NO_RESULTS, 
VALID_SEARCH_RESULT_VIEWS_W_RESULTS, PARK_COUNTRY, PARK_REGION, PARK_NAME, PARK_CODE, DURATION, TOTAL_SEARCH_RESULT_VIEWS, 
VALID_SEARCH_RESULT_VIEWS, INVALID_SEARCH_RESULT_VIEWS, HITS_HOL_SEARCH_DATE, NUM_RESULTS_GROUPED, HOLIDAY_TYPE,
ARRIVAL_DAY_OF_WEEK, DAYS_TO_ARRIVAL, WEEKS_TO_ARRIVAL, DURATION_GROUPED, PERIOD, YEAR_PERIOD)
AS SELECT ARRIVAL_DATE, 
ARRIVAL_MONTH, 
ARRIVAL_YEAR,
ARRIVAL_YEAR_FLAG, 
VALID_SEARCH_RESULT_VIEWS_NO_RESULTS, 
VALID_SEARCH_RESULT_VIEWS_W_RESULTS, PARK_COUNTRY, PARK_REGION, PARK_NAME, PARK_CODE, DURATION, TOTAL_SEARCH_RESULT_VIEWS, VALID_SEARCH_RESULT_VIEWS, INVALID_SEARCH_RESULT_VIEWS, HITS_HOL_SEARCH_DATE, NUM_RESULTS_GROUPED, HOLIDAY_TYPE, ARRIVAL_DAY_OF_WEEK, DAYS_TO_ARRIVAL, WEEKS_TO_ARRIVAL, DURATION_GROUPED, PERIOD, YEAR_PERIOD
FROM HAVEN_RAW.BIGQUERY.HITS_HOL_SEARCH_RESULTS;

USE ROLE sysadmin;
DROP VIEW HAVEN_STORE.COMMERCIAL.HITS_HOL_SEARCH_RESULTS;
USE ROLE dba;

create or replace view HAVEN_STORE.COMMERCIAL.HITS_HOL_SEARCH_RESULTS (
	DATE,
	PERIOD,
	VALID_SEARCH_RESULT_VIEWS_NO_RESULTS,
	VALID_SEARCH_RESULT_VIEWS,
	DAYS_TO_ARRIVAL,
	ARRIVAL_YEAR_FLAG,
	TOTAL_SEARCH_RESULT_VIEWS,
	PARK_CODE,
	PARK_NAME,
	DURATION,
	ARRIVAL_YEAR,
	PARK_COUNTRY,
	ARRIVAL_DAY_OF_WEEK,
	DURATION_GROUPED,
	VALID_SEARCH_RESULT_VIEWS_W_RESULTS,
	PARK_REGION,
	YEAR_PERIOD,
	WEEKS_TO_ARRIVAL,
	NUM_RESULTS_GROUPED,
	INVALID_SEARCH_RESULT_VIEWS,
	ARRIVAL_MONTH,
	ARRIVAL_DATE,
	HOLIDAY_TYPE
) AS
SELECT DATE(HITS_HOL_SEARCH_DATE), PERIOD, VALID_SEARCH_RESULT_VIEWS_NO_RESULTS, VALID_SEARCH_RESULT_VIEWS, 
DAYS_TO_ARRIVAL, ARRIVAL_YEAR_FLAG, TOTAL_SEARCH_RESULT_VIEWS, PARK_CODE, PARK_NAME, DURATION, 
ARRIVAL_YEAR, PARK_COUNTRY, ARRIVAL_DAY_OF_WEEK, DURATION_GROUPED, 
VALID_SEARCH_RESULT_VIEWS_W_RESULTS, PARK_REGION, YEAR_PERIOD, WEEKS_TO_ARRIVAL, 
NUM_RESULTS_GROUPED, INVALID_SEARCH_RESULT_VIEWS, ARRIVAL_MONTH, ARRIVAL_DATE, HOLIDAY_TYPE
FROM HAVEN_BASE.BIGQUERY.HITS_HOL_SEARCH_RESULTS;

USE ROLE sysadmin;
DROP VIEW HAVEN_STORE.COMMERCIAL.HOLIDAY_SEARCHES;
USE ROLE dba;

create or replace view HAVEN_BASE.BIGQUERY.HOLIDAY_SEARCHES(
	SEARCHES,
	DATE_YYYY_MM_DD,
	ARRIVAL_DATE_YYYY_MM_DD,
	HOLIDAY_TYPE,
	PARKNAME
) as
SELECT SEARCHES, DATE_YYYY_MM_DD, ARRIVAL_DATE_YYYY_MM_DD, HOLIDAY_TYPE, PARKNAME
FROM HAVEN_RAW.BIGQUERY.TARGET_HOLIDAY_SEARCHES;

create or replace view HAVEN_STORE.COMMERCIAL.HOLIDAY_SEARCHES(
	SEARCHES,
	DATE_YYYY_MM_DD,
	ARRIVAL_DATE_YYYY_MM_DD,
	HOLIDAY_TYPE,
	PARKNAME
) as
SELECT SEARCHES, DATE_YYYY_MM_DD, ARRIVAL_DATE_YYYY_MM_DD, HOLIDAY_TYPE, PARKNAME
FROM HAVEN_BASE.BIGQUERY.HOLIDAY_SEARCHES;

USE ROLE sysadmin;
DROP VIEW HAVEN_STORE.COMMERCIAL.SEARCHES_AND_BOOKINGS_SUMMARY;
USE ROLE dba;

create or replace view HAVEN_STORE.COMMERCIAL.SEARCHES_AND_BOOKINGS_SUMMARY(
	DATE,
	SEARCHES,
	ARRIVAL_PERIOD,
	PARK_CODE,
	BOOKINGS,
	ARRIVAL_DATE,
	HOLIDAY_TYPE
) as
SELECT DATE(SEARCHES_AND_BOOKINGS_DATE), SEARCHES, ARRIVAL_PERIOD, PARK_CODE, BOOKINGS, DATE(ARRIVAL_DATE), HOLIDAY_TYPE
FROM HAVEN_BASE.BIGQUERY.SEARCHES_AND_BOOKINGS_SUMMARY;

create or replace view HAVEN_STORE.COMMERCIAL.TRANSACTIONS_BY_DATE (
	TRANS_DATE,
	FULLVISITORID,
	VISITID,
	VISITSTARTTIME,
	HIT_TIME,
	TRANSACTIONID,
	TRANSACTIONREVENUE,
	HOL_BOOKING_ID,
	TIMESTAMP_RAW,
	BUSINESS_AREA,
	FRIENDLY_PAGE_NAME,
	PARK_NAME,
	PARK_CODE,
	HOLIDAY_PACKAGE,
	DURATION,
	ARRIVAL_DATE,
	GUEST_NEW_REPEAT,
	GUESTS_ADULTS,
	GUESTS_CHILDREN,
	GUESTS_INFANTS,
	GUESTS_DOGS,
	GUESTS_TOTAL,
	GUEST_TYPE,
	ACT_CATEGORY,
	ACT_NAME,
	ACT_DATE,
	ACT_TIME
) as
SELECT DATE(TRANSACTION_DATE), FULLVISITORID, VISITID, VISITSTARTTIME, HIT_TIME, TRANSACTIONID, TRANSACTIONREVENUE, HOL_BOOKING_ID, TIMESTAMP_RAW, BUSINESS_AREA, FRIENDLY_PAGE_NAME, PARK_NAME, PARK_CODE, HOLIDAY_PACKAGE, DURATION, ARRIVAL_DATE, GUEST_NEW_REPEAT, GUESTS_ADULTS, GUESTS_CHILDREN, GUESTS_INFANTS, GUESTS_DOGS, 
GUESTS_TOTAL, GUEST_TYPE, ACT_CATEGORY, ACT_NAME, ACT_DATE, ACT_TIME
FROM HAVEN_BASE.BIGQUERY.TRANSACTIONS_BY_DATE;

create or replace view HAVEN_BASE.BIGQUERY.WEEKLY_SUMMARY(
	PARKCODE,
	SEARCHES,
	ARRIVAL_WEEK,
	BOOKINGS,
	HOLIDAY_TYPE,
	BOOK_WEEK
) as
SELECT PARKCODE, SEARCHES, ARRIVAL_WEEK, BOOKINGS, HOLIDAY_TYPE, BOOK_WEEK
FROM HAVEN_RAW.BIGQUERY.TARGET_02_WEEKLY_SUMMARY;

USE ROLE sysadmin;
DROP VIEW HAVEN_STORE.COMMERCIAL.WEEKLY_SUMMARY;
USE ROLE dba;

create or replace view HAVEN_STORE.COMMERCIAL.WEEKLY_SUMMARY(
	PARKCODE,
	SEARCHES,
	ARRIVAL_WEEK,
	BOOKINGS,
	HOLIDAY_TYPE,
	BOOK_WEEK
) as
SELECT PARKCODE, SEARCHES, ARRIVAL_WEEK, BOOKINGS, HOLIDAY_TYPE, BOOK_WEEK
FROM HAVEN_BASE.BIGQUERY.WEEKLY_SUMMARY;

