use role dba;

use schema training.training;

create or replace TABLE CLIENT_tagged (
	CLIENT_ID NUMBER(9,0),
	HOUSEHOLD_ID NUMBER(9,0),
	LAST_NAME VARCHAR(120) with tag (haven_master.tag_admin.pii='name',haven_master.tag_admin.NAME='last name', haven_master.tag_admin.lastname='surname'),
	FIRST_NAME VARCHAR(120) with tag (haven_master.tag_admin.pii='name',haven_master.tag_admin.NAME='first name', haven_master.tag_admin.firstname='forename'),
	MIDDLE_NAME VARCHAR(120) with tag (haven_master.tag_admin.pii='name',haven_master.tag_admin.NAME='middle name', haven_master.tag_admin.middlename='middile initial'),
	FULL_NAME VARCHAR(240) with tag (haven_master.tag_admin.pii='name',haven_master.tag_admin.NAME='full name', haven_master.tag_admin.fullname='full name'),
	SALUTATION VARCHAR(400) with tag (haven_master.tag_admin.pii='personal',haven_master.tag_admin.personal='title', haven_master.tag_admin.title='title'),
	TITLE VARCHAR(200) with tag (haven_master.tag_admin.pii='personal',haven_master.tag_admin.personal='title', haven_master.tag_admin.title='title'),
	OCCUPATION VARCHAR(120),
	IS_ACTIVE VARCHAR(4),
	BIRTHDAY TIMESTAMP_NTZ(9) with tag (haven_master.tag_admin.pii='personal',haven_master.tag_admin.personal='date of birth', haven_master.tag_admin.dateofbirth='dob'),
	BIRTH_PLACE VARCHAR(120) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	SEX VARCHAR(4) with tag (haven_master.tag_admin.pii='personal',haven_master.tag_admin.personal='gender', haven_master.tag_admin.gender='gender'),
	IS_HANDICAPPED VARCHAR(4),
	IS_SMOKER VARCHAR(4),
	SOUVENIR_FNAME VARCHAR(120),
	SOUVENIR_LNAME VARCHAR(120),
	LANGUAGE VARCHAR(80) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	PASSPORT_NUMBER VARCHAR(120),
	PASSPORT_ISSUE_PLACE VARCHAR(120) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	PASSPORT_ISSUE_DATE TIMESTAMP_NTZ(9),
	PASSPORT_EXP_DATE TIMESTAMP_NTZ(9),
	NATIONALITY VARCHAR(120) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	CITIZENSHIP VARCHAR(120) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	REFERRAL_TYPE VARCHAR(60),
	REFERRAL_DATE TIMESTAMP_NTZ(9),
	REFERRAL_CLIENT_ID NUMBER(9,0),
	REFERRAL_HOUSEHOLD_ID NUMBER(9,0),
	REFERRAL_SOURCE VARCHAR(120) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	COMMENTS VARCHAR(1020) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	CLIENT_TYPE VARCHAR(60),
	GUEST_TYPE VARCHAR(80),
	DIRECTORY_NAME VARCHAR(400) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	CLIENT_CLASS_CODE VARCHAR(120),
	EMAIL VARCHAR(320) WITH TAG (haven_master.tag_admin.pii='email', HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address'),
	COUNTRY_OF_BIRTH VARCHAR(12) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	WEB_PASSWORD VARCHAR(120) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	WEB_LOGIN_NAME VARCHAR(320) WITH TAG (haven_master.tag_admin.pii='email', HAVEN_MASTER.TAG_ADMIN.EMAIL='web_login_address'),
	WEB_LAST_LOGIN TIMESTAMP_NTZ(9),
	SSN NUMBER(9,0),
	LANGUAGE_CODE VARCHAR(12) with tag (haven_master.tag_admin.pii='address',haven_master.tag_admin.address='location', haven_master.tag_admin.location='location'),
	HISTORICAL_CRUISES_NUM NUMBER(5,0),
	HISTORICAL_DAYS_NUM NUMBER(5,0),
	ALLOW_WEB_ACCESS VARCHAR(4),
	CL_ENTITY_TYPE VARCHAR(60),
	SEND_PROMOTIONAL_MAIL VARCHAR(4),
	SEND_PROMOTIONAL_EMAIL VARCHAR(4),
	SEND_PROMOTIONAL_SMS VARCHAR(4),
	NOTIF_DFLT_DISTR_TYPE VARCHAR(60),
	LAST_NAME_UPPER VARCHAR(120) with tag (haven_master.tag_admin.pii='name',haven_master.tag_admin.NAME='last name', haven_master.tag_admin.lastname='surname'),
	SEND_PROMOTIONAL_PHONE VARCHAR(4)
);


select system$get_tag('haven_master.tag_admin.pii', 'client_tagged.email', 'column');

select get_ddl('table', 'client_tagged');




create or replace TABLE CLIENT_TAGGED (
	CLIENT_ID NUMBER(9,0),
	HOUSEHOLD_ID NUMBER(9,0),
	LAST_NAME VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='surname', HAVEN_MASTER.TAG_ADMIN.NAME='last name', HAVEN_MASTER.TAG_ADMIN.PII='name'),
	FIRST_NAME VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.FIRSTNAME='forename', HAVEN_MASTER.TAG_ADMIN.NAME='first name', HAVEN_MASTER.TAG_ADMIN.PII='name'),
	MIDDLE_NAME VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.MIDDLENAME='middile initial', HAVEN_MASTER.TAG_ADMIN.NAME='middle name', HAVEN_MASTER.TAG_ADMIN.PII='name'),
	FULL_NAME VARCHAR(240) WITH TAG (HAVEN_MASTER.TAG_ADMIN.FULLNAME='full name', HAVEN_MASTER.TAG_ADMIN.NAME='full name', HAVEN_MASTER.TAG_ADMIN.PII='name'),
	SALUTATION VARCHAR(400) WITH TAG (HAVEN_MASTER.TAG_ADMIN.PERSONAL='title', HAVEN_MASTER.TAG_ADMIN.PII='personal', HAVEN_MASTER.TAG_ADMIN.TITLE='title'),
	TITLE VARCHAR(200) WITH TAG (HAVEN_MASTER.TAG_ADMIN.PERSONAL='title', HAVEN_MASTER.TAG_ADMIN.PII='personal', HAVEN_MASTER.TAG_ADMIN.TITLE='title'),
	OCCUPATION VARCHAR(120),
	IS_ACTIVE VARCHAR(4),
	BIRTHDAY TIMESTAMP_NTZ(9) WITH TAG (HAVEN_MASTER.TAG_ADMIN.DATEOFBIRTH='dob', HAVEN_MASTER.TAG_ADMIN.PERSONAL='date of birth', HAVEN_MASTER.TAG_ADMIN.PII='personal'),
	BIRTH_PLACE VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	SEX VARCHAR(4) WITH TAG (HAVEN_MASTER.TAG_ADMIN.GENDER='gender', HAVEN_MASTER.TAG_ADMIN.PERSONAL='gender', HAVEN_MASTER.TAG_ADMIN.PII='personal'),
	IS_HANDICAPPED VARCHAR(4),
	IS_SMOKER VARCHAR(4),
	SOUVENIR_FNAME VARCHAR(120),
	SOUVENIR_LNAME VARCHAR(120),
	LANGUAGE VARCHAR(80) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	PASSPORT_NUMBER VARCHAR(120),
	PASSPORT_ISSUE_PLACE VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	PASSPORT_ISSUE_DATE TIMESTAMP_NTZ(9),
	PASSPORT_EXP_DATE TIMESTAMP_NTZ(9),
	NATIONALITY VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	CITIZENSHIP VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	REFERRAL_TYPE VARCHAR(60),
	REFERRAL_DATE TIMESTAMP_NTZ(9),
	REFERRAL_CLIENT_ID NUMBER(9,0),
	REFERRAL_HOUSEHOLD_ID NUMBER(9,0),
	REFERRAL_SOURCE VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	COMMENTS VARCHAR(1020) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	CLIENT_TYPE VARCHAR(60),
	GUEST_TYPE VARCHAR(80),
	DIRECTORY_NAME VARCHAR(400) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	CLIENT_CLASS_CODE VARCHAR(120),
	EMAIL VARCHAR(320) WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address', HAVEN_MASTER.TAG_ADMIN.PII='email'),
	COUNTRY_OF_BIRTH VARCHAR(12) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	WEB_PASSWORD VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	WEB_LOGIN_NAME VARCHAR(320) WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='web_login_address', HAVEN_MASTER.TAG_ADMIN.PII='email'),
	WEB_LAST_LOGIN TIMESTAMP_NTZ(9),
	SSN NUMBER(9,0),
	LANGUAGE_CODE VARCHAR(12) WITH TAG (HAVEN_MASTER.TAG_ADMIN.ADDRESS='location', HAVEN_MASTER.TAG_ADMIN.LOCATION='location', HAVEN_MASTER.TAG_ADMIN.PII='address'),
	HISTORICAL_CRUISES_NUM NUMBER(5,0),
	HISTORICAL_DAYS_NUM NUMBER(5,0),
	ALLOW_WEB_ACCESS VARCHAR(4),
	CL_ENTITY_TYPE VARCHAR(60),
	SEND_PROMOTIONAL_MAIL VARCHAR(4),
	SEND_PROMOTIONAL_EMAIL VARCHAR(4),
	SEND_PROMOTIONAL_SMS VARCHAR(4),
	NOTIF_DFLT_DISTR_TYPE VARCHAR(60),
	LAST_NAME_UPPER VARCHAR(120) WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='surname', HAVEN_MASTER.TAG_ADMIN.NAME='last name', HAVEN_MASTER.TAG_ADMIN.PII='name'),
	SEND_PROMOTIONAL_PHONE VARCHAR(4)
);
