use ROLE dba;

use SCHEMA haven_base.customer_verification;

CREATE VIEW HAVEN_BASE.CUSTOMER_VERIFICATION.CROSSCOREREQUESTS
( ID, HID, ADDRESSID, EXPERIANREQUESTID, DECISION, DECISIONREASONS, EXPERIANRESPONSE, DECISIONELEMENTS, REQUESTTYPE, ORIGINALREQUESTDATA )
AS SELECT ID, HID, ADDRESSID, EXPERIANREQUESTID, DECISION, DECISIONREASONS, EXPERIANRESPONSE, DECISIONELEMENTS, REQUESTTYPE, ORIGINALREQUESTDATA
FROM HAVEN_RAW.CUSTOMER_VERIFICATION.CROSSCOREREQUESTS;

CREATE VIEW HAVEN_BASE.CUSTOMER_VERIFICATION.PARKS
( NID, NAME, SHORTNAME )
AS SELECT ID, NAME, SHORTNAME
FROM HAVEN_RAW.CUSTOMER_VERIFICATION.PARKS;

-- 04/11/2025

use ROLE dba;

use SCHEMA haven_base.customer_verification;

CREATE VIEW haven_base.CUSTOMER_VERIFICATION.TEMPCROSSCOREIDENTITY
( ID, HID, CREATEDAT, LASTCHECKEDAT, COMPLETEDAT )
AS SELECT ID, HID, CREATEDAT, LASTCHECKEDAT, COMPLETEDAT
FROM HAVEN_RAW.CUSTOMER_VERIFICATION.TEMPCROSSCOREIDENTITY;

