use role dba;

use warehouse dba_wh;

use schema haven_store_dev.cyhh_reporting_pitch_bookings_by_price;

show roles like '%cyhh_reporting_pitch_bookings_by_price%';

create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.decision_matrix clone haven_revenue_management.ds_dev.decision_matrix;
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.decision_matrix_pg1 clone haven_revenue_management.ds_dev.decision_matrix_pg1;
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.pricer_wait_days clone haven_revenue_management.ds_dev.pricer_wait_days;
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.decision_matrix_rule_translation  clone haven_revenue_management.ds_dev.decision_matrix_rule_translation;    
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.decision_wait_rules clone haven_revenue_management.ds_dev.decision_wait_rules;
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.CYHH_2024_BREAK_DATES clone haven_revenue_management.ds_dev.CYHH_2024_BREAK_DATES;
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.cyhh_break_to_period clone haven_revenue_management.ds_dev.cyhh_break_to_period;
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.cyhh_p1_park_price_split clone haven_revenue_management.ds_dev.cyhh_p1_park_price_split;
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.CYHH_P7_PARK_PRICE_SPLIT clone haven_revenue_management.ds_dev.CYHH_P7_PARK_PRICE_SPLIT;
create table haven_store_dev.cyhh_reporting_pitch_bookings_by_price.CYHH_PARK_ENTRY_PRICE_SPLIT clone haven_revenue_management.ds_dev.CYHH_PARK_ENTRY_PRICE_SPLIT;



use schema haven_store_qat.cyhh_reporting_pitch_bookings_by_price;

create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.decision_matrix clone haven_revenue_management.ds_dev.decision_matrix;
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.decision_matrix_pg1 clone haven_revenue_management.ds_dev.decision_matrix_pg1;
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.pricer_wait_days clone haven_revenue_management.ds_dev.pricer_wait_days;
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.decision_matrix_rule_translation  clone haven_revenue_management.ds_dev.decision_matrix_rule_translation;    
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.decision_wait_rules clone haven_revenue_management.ds_dev.decision_wait_rules;
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.CYHH_2024_BREAK_DATES clone haven_revenue_management.ds_dev.CYHH_2024_BREAK_DATES;
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.cyhh_break_to_period clone haven_revenue_management.ds_dev.cyhh_break_to_period;
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.cyhh_p1_park_price_split clone haven_revenue_management.ds_dev.cyhh_p1_park_price_split;
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.CYHH_P7_PARK_PRICE_SPLIT clone haven_revenue_management.ds_dev.CYHH_P7_PARK_PRICE_SPLIT;
create table haven_store_qat.cyhh_reporting_pitch_bookings_by_price.CYHH_PARK_ENTRY_PRICE_SPLIT clone haven_revenue_management.ds_dev.CYHH_PARK_ENTRY_PRICE_SPLIT;

