use ROLE dba;

use SCHEMA haven_base.dig_digital_pass;

CREATE VIEW HAVEN_BASE.DIG_DIGITAL_PASS.ACCOUNT
( ID, HID, CONSUMER_ID, CREATED_AT, UPDATED_AT, DELETED_AT )
AS SELECT ID, HID, CONSUMER_ID, CREATED_AT, UPDATED_AT, DELETED_AT
FROM HAVEN_RAW.DIG_DIGITAL_PASS."ACCOUNT";

CREATE VIEW HAVEN_BASE.DIG_DIGITAL_PASS.DIGITAL_PASS
( ID, HID, COUPON_ID, BOOKING_ID, TYPE, STATE, CREATED_AT, UPDATED_AT, DELETED_AT, CONSUMER_ID, REDEEMED_AT )
AS SELECT ID, HID, COUPON_ID, BOOKING_ID, "TYPE", STATE, CREATED_AT, UPDATED_AT, DELETED_AT, CONSUMER_ID, REDEEMED_AT
FROM HAVEN_RAW.DIG_DIGITAL_PASS.DIGITAL_PASS;


SELECT count(*) FROM ACCOUNT;
SELECT count(*) FROM digital_pass;

