USE ROLE dba;

USE SCHEMA haven_base.dig_activities;

CREATE OR REPLACE VIEW haven_base.DIG_ACTIVITIES.ACTIVITIES 
( ZAMID, ZAMDURATION, ZAMNAME, ZAMCATEGORYID, ATECOST, TITLE, COSTUNITDEFINITION, INDOOROUTDOOR, ISLIVE, GENERICADVISORY, BOOKINGLIMIT, CREATEDAT, UPDATEDAT, DELETEDAT, IMAGELANDSCAPEASSETID, IMAGEPORTRAITASSETID, OWNERBOOKINGLIMIT, "TYPE", BOOKINGMODE, BOOKINGMODEACTIVITIESINPARKS, ID, COSTUNITDEFINITIONID, ISOWNER, CATEGORYID, ISRETAIL, WAIVERLEVEL, ISASSETNUMBERREQUIRED, ISADDGUESTALLOWED, ENDORSEMENTID, CONTENTFULID, ISHIRE )
AS SELECT ZAMID, ZAMDURATION, ZAMNAME, ZAMCATEGORYID, ATECOST, TITLE, COSTUNITDEFINITION, INDOOROUTDOOR, ISLIVE, GENERICADVISORY, BOOKINGLIMIT, CREATEDAT, UPDATEDAT, DELETEDAT, IMAGELANDSCAPEASSETID, IMAGEPORTRAITASSETID, OWNERBOOKINGLIMIT, "TYPE", BOOKINGMODE, BOOKINGMODEACTIVITIESINPARKS, ID, COSTUNITDEFINITIONID, ISOWNER, CATEGORYID, ISRETAIL, WAIVERLEVEL, ISASSETNUMBERREQUIRED, ISADDGUESTALLOWED, ENDORSEMENTID, CONTENTFULID, ISHIRE
FROM HAVEN_RAW.DIG_ACTIVITIES.ACTIVITIES;


SELECT ZAMID, ZAMDURATION, ZAMNAME, ZAMCATEGORYID, ATECOST, TITLE, COSTUNITDEFINITION, INDOOROUTDOOR, ISLIVE, GENERICADVISORY, BOOKINGLIMIT, CREATEDAT, UPDATEDAT, DELETEDAT, IMAGELANDSCAPEASSETID, IMAGEPORTRAITASSETID, OWNERBOOKINGLIMIT, "TYPE", BOOKINGMODE, BOOKINGMODEACTIVITIESINPARKS, ID, COSTUNITDEFINITIONID, ISOWNER, CATEGORYID, ISRETAIL, WAIVERLEVEL, ISASSETNUMBERREQUIRED, ISADDGUESTALLOWED, ENDORSEMENTID, CONTENTFULID, ISHIRE
FROM HAVEN_RAW.DIG_ACTIVITIES.ACTIVITIES;