use ROLE dba;

use SCHEMA haven_base.dig_fb_eagleeye;

CREATE VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.COUPON
( ID, CODE, OWNER_CARD_ID, EAGLE_EYE_ACCOUNT_ID, EAGLE_EYE_CAMPAIGN_ID, "TYPE", VALID_FROM, VALID_TO, CREATED_AT, UPDATED_AT, DELETED_AT )
AS SELECT ID, CODE, OWNER_CARD_ID, EAGLE_EYE_ACCOUNT_ID, EAGLE_EYE_CAMPAIGN_ID, "TYPE", VALID_FROM, VALID_TO, CREATED_AT, UPDATED_AT, DELETED_AT
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.COUPON;

CREATE VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.INVITATION
( INVITATION_ID, OWNER_CARD_ID, CREATED_AT, UPDATED_AT, INVITED_BY, OWNER_ACCOUNT_NUMBER, ID, EXPIRY_DATE, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT INVITATION_ID, OWNER_CARD_ID, CREATED_AT, UPDATED_AT, INVITED_BY, OWNER_ACCOUNT_NUMBER, ID, EXPIRY_DATE, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.INVITATION;

CREATE VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.OWNER_ACCOUNT
( ACCOUNT_NUMBER, IS_CHARITY, IS_DEBTOR, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT ACCOUNT_NUMBER, IS_CHARITY, IS_DEBTOR, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.OWNER_ACCOUNT;

CREATE VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.OWNER_CARD
( ID, FIRST_NAME, LAST_NAME, DOB, EMAIL, PHONE_NUMBER, OWNER_ACCOUNT_NUMBER, EAGLEEYE_WALLET_ID, CREATED_AT, UPDATED_AT, PARK_CODE, CARD_HOLDER_TYPE, CARD_STATUS, PARENT_EAGLEEYE_WALLET_ID, CARD_NUMBER, MOBILE_WALLET_URL, PHYSICAL_CARD_STATUS, CARD_TYPE, PARENT_CARD_IDENTIFIER, EXPIRATION_DATE, RECEIVE_EMAIL_MARKETING, CARD_IDENTIFIER, IS_WALLET_REGISTERED, PITCH_NUMBER, AREA_CODE, ZONE_CODE, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT ID, FIRST_NAME, LAST_NAME, DOB, EMAIL, PHONE_NUMBER, OWNER_ACCOUNT_NUMBER, EAGLEEYE_WALLET_ID, CREATED_AT, UPDATED_AT, PARK_CODE, CARD_HOLDER_TYPE, CARD_STATUS, PARENT_EAGLEEYE_WALLET_ID, CARD_NUMBER, MOBILE_WALLET_URL, PHYSICAL_CARD_STATUS, CARD_TYPE, PARENT_CARD_IDENTIFIER, EXPIRATION_DATE, RECEIVE_EMAIL_MARKETING, CARD_IDENTIFIER, IS_WALLET_REGISTERED, PITCH_NUMBER, AREA_CODE, ZONE_CODE, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.OWNER_CARD;

CREATE VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.OWNER_CARD_AUDIT
( ID, OWNER_CARD_ID, CHANGED_BY_USER_TYPE, CHANGED_BY_OWNER_CARD_ID, CHANGE_TYPE, CHANGE_DETAILS, CREATED_AT, UPDATED_AT, CHANGED_BY_HAVEN_TEAM_MEMBER_ID, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT ID, OWNER_CARD_ID, CHANGED_BY_USER_TYPE, CHANGED_BY_OWNER_CARD_ID, CHANGE_TYPE, CHANGE_DETAILS, CREATED_AT, UPDATED_AT, CHANGED_BY_HAVEN_TEAM_MEMBER_ID, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.OWNER_CARD_AUDIT;

CREATE VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.PARK
( PARK_CODE, PARK_NAME, PHONE_NUMBER, CREATED_AT, DELETED_AT, UPDATED_AT, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT PARK_CODE, PARK_NAME, PHONE_NUMBER, CREATED_AT, DELETED_AT, UPDATED_AT, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.PARK;

CREATE VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.PARK_REWARD
( CATEGORY, TYPE, PARK_CODE, EMAIL, ADDRESS, PHONE_NUMBER, WEBSITE, FRONT_TITLE, BACK_TEXT, IS_ARCHIVED, CREATED_AT, UPDATED_AT, MANAGED_BY, ID, OFFER, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT CATEGORY, "TYPE", PARK_CODE, EMAIL, ADDRESS, PHONE_NUMBER, WEBSITE, FRONT_TITLE, BACK_TEXT, IS_ARCHIVED, CREATED_AT, UPDATED_AT, MANAGED_BY, ID, OFFER, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.PARK_REWARD;

DROP VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.OWNERSCARDHOLDERDETAILS ;

-- 06/06/06

USE ROLE DBA;

CREATE VIEW HAVEN_BASE.DIG_FB_EAGLEEYE.OWNERSCARDHOLDERDETAILS 
( ID, FIRSTNAME, LASTNAME, DOB, EMAIL, PHONENUMBER, OWNERACCOUNTNUMBER, EAGLEEYEWALLETID, CREATEDAT, UPDATEDAT, PARKCODE, CARDHOLDERTYPE, CARDSTATUS, PARENTEAGLEEYEWALLETID, CARDNUMBER, MOBILEWALLETURL, PHYSICALCARDSTATUS, CARDTYPE, PARENTCARDHOLDERDETAILSID, EXPIRATIONDATE, RECEIVEEMAILMARKETING, CARDIDENTIFIER, ISWALLETREGISTERED, PITCHNUMBER, AREACODE, ZONECODE ) 
AS SELECT ID, FIRSTNAME, LASTNAME, DOB, EMAIL, PHONENUMBER, OWNERACCOUNTNUMBER, EAGLEEYEWALLETID, CREATEDAT, UPDATEDAT, PARKCODE, CARDHOLDERTYPE, CARDSTATUS, PARENTEAGLEEYEWALLETID, CARDNUMBER, MOBILEWALLETURL, PHYSICALCARDSTATUS, CARDTYPE, PARENTCARDHOLDERDETAILSID, EXPIRATIONDATE, RECEIVEEMAILMARKETING, CARDIDENTIFIER, ISWALLETREGISTERED, PITCHNUMBER, AREACODE, ZONECODE
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.OWNERSCARDHOLDERDETAILS;

