use ROLE dba;

USE SCHEMA HAVEN_RAW.ENERGY_METERS;

SHOW TABLES;

USE ROLE HAVEN_BATCH_DATALOAD;

CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_ECBOURNEGAS
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNEGAS;


CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES;


CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_ECBOURNEWATER
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNEWATER;


CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY;


CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_GAS
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_GAS;


CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_WATER
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_WATER;


CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER;


CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_READING_EXTRACT_BOURNE_EVC
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_READING_EXTRACT_BOURNE_EVC;


CREATE OR replace view HAVEN_BASE.ENERGY_METERS.METERED_USAGE_READING_EXTRACT_BOURNE_EVC_EXPANDED;
SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, SERIAL_NUMBER, READING_DATE, READING_TIME, RATE1_KWH, RATE2_KWH, RATE3_KWH, RATE4_KWH, REVERSE_KWH, TOTAL_KWH, GROUPNAME
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_READING_EXTRACT_BOURNE_EVC_EXPANDED;