use role dba;

CREATE OR REPLACE VIEW HAVEN_BASE.CONSENT_AND_PREFERENCE_ETLEAP.TOPIC
AS SELECT KEY, NAME, DESCRIPTION, PROMPTTEXT, ISACTIVE, CREATEDAT, UPDATEDAT, "order" as ORDERS, AUDIENCE
FROM HAVEN_RAW.CONSENT_AND_PREFERENCE_ETLEAP.TOPIC;

SELECT * FROM HAVEN_BASE.CONSENT_AND_PREFERENCE_ETLEAP.TOPIC;


CREATE OR REPLACE VIEW HAVEN_BASE.DIG_ACTIVITIES_ETLEAP.PRODUCTAVAILABILITIES 
AS SELECT ID, NAME, "from" as FROM_date, "to" as TO_date, ISPEAK, ISLIVE, CREATEDAT, UPDATEDAT, DELETEDAT 
FROM HAVEN_RAW.DIG_ACTIVITIES_ETLEAP.PRODUCTAVAILABILITIES;

select * FROM HAVEN_base."DIG_ACTIVITIES_ETLEAP"."PRODUCTAVAILABILITIES";

use schema haven_base.dig_owners_arrivals_etleap;

show views;

use schema haven_raw.dig_owners_arrivals_etleap;

show tables;

CREATE OR REPLACE VIEW HAVEN_BASE.IDENTITY_ETLEAP.HID_AUDIT 
AS SELECT TX, SOURCE, TYPE, "from" as FROM_DATE, "to" AS TO_DATE, HID, TIMESTAMP, HID_AUDIT_ID 
FROM HAVEN_RAW.IDENTITY_ETLEAP.HID_AUDIT