USE ROLE dba;

USE SCHEMA haven_base.consent_and_preference;

SELECT get_ddl('VIEW', 'TOPIC');

desc table "HAVEN_RAW"."CONSENT_AND_PREFERENCE_ETLEAP"."TOPIC";

create or replace view HAVEN_BASE_ETLEAP.CONSENT_AND_PREFERENCE.TOPIC (
	KEY,
	NAME,
	DESCRIPTION,
	PROMPTTEXT,
	ISACTIVE,
	CREATEDAT,
	UPDATEDAT,
	"ORDER"
) as SELECT "KEY", "NAME", "DESCRIPTION", "PROMPTTEXT", "ISACTIVE", "CREATEDAT", "UPDATEDAT", "order" FROM "HAVEN_RAW"."CONSENT_AND_PREFERENCE_ETLEAP"."TOPIC";

use schema haven_base_etleap.dig_activities;

SELECT get_ddl('VIEW', 'PRODUCTAVAILABILITIES');

create or replace view PRODUCTAVAILABILITIES(
	ID,
	NAME,
	"FROM",
	"TO",
	ISPEAK,
	ISLIVE,
	CREATEDAT,
	UPDATEDAT,
	DELETEDAT
) as SELECT ID, NAME, "from" as FROM_date, "to" as TO_date, ISPEAK, ISLIVE, CREATEDAT, UPDATEDAT, DELETEDAT 
FROM HAVEN_RAW.DIG_ACTIVITIES_ETLEAP.PRODUCTAVAILABILITIES;

use schema haven_base_etleap.identity;

SELECT get_ddl('VIEW', 'HID_AUDIT');

create or replace view HID_AUDIT(
	TX,
	SOURCE,
	TYPE,
	FROM_value,
	TO_value,
	HID,
	AUDIT_TIMESTAMP,
	HID_AUDIT_ID
) as SELECT TX, SOURCE, TYPE, "from" as FROM_DATE, "to" AS TO_DATE, HID, TIMESTAMP, HID_AUDIT_ID 
FROM HAVEN_RAW.IDENTITY_ETLEAP.HID_AUDIT;

select * from haven_base.identity.hid_audit limit 5;

use schema haven_base.seaware;

SELECT get_ddl('VIEW', 'PACKAGE_DEFINITION');

create or replace view HAVEN_BASE_ETLEAP.SEAWARE.PACKAGE_DEFINITION(
	PACKAGE_ID,
	PACKAGE_CODE,
	VACATION_DATE,
	PACKAGE_TYPE,
	SAIL_ID,
	SEASON_CODE,
	GEOG_AREA_CODE,
	IS_ACTIVE,
	COMMENTS,
	SORT_SEQN,
	SHOREX_MODE,
	SHOREX_TIMING,
	ALT_PACKAGE_ID,
	PRODUCT
) as 
SELECT PACKAGE_ID, PACKAGE_CODE, VACATION_DATE, PACKAGE_TYPE, SAIL_ID, SEASON_CODE, GEOG_AREA_CODE, IS_ACTIVE, COMMENTS, 
SORT_SEQN, SHOREX_MODE, SHOREX_TIMING, ALT_PACKAGE_ID ,
iff(season_code = 'TOURING', 'TOURING', 'SELF CATER') as product
FROM HAVEN_RAW.SEAWARE_ETLEAP.PACKAGE_DEFINITION
;

use schema haven_base_etleap.dig_arrivals;

SELECT get_ddl('VIEW', 'ARRIVAL');

create or replace view ARRIVAL(
	ID,
	PARK_CODE,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	HOLDER_ID,
	HOLDER_TYPE,
	ARRIVAL_TIME,
	ARRIVING_LATE,
	ARRIVED_AT,
	CANCELLED_AT,
	CREATED_AT,
	UPDATED_AT,
	IS_SURVEY_COMPLETED,
	SHORT_CODE,
	HOLIDAY_TYPE,
	ARRIVAL_SLOT,
	ADDED_TO_MY_HAVEN_APP,
	DELETED_DATE,
	IS_DELETED
) as SELECT "ID", "PARK_CODE", "ARRIVAL_DATE", "DEPARTURE_DATE", "HOLDER_ID", "HOLDER_TYPE", TRY_CAST("ARRIVAL_TIME" AS TIME), "ARRIVING_LATE", "ARRIVED_AT", "CANCELLED_AT", "CREATED_AT", "UPDATED_AT", "IS_SURVEY_COMPLETED", "SHORT_CODE", "HOLIDAY_TYPE", "ARRIVAL_SLOT", "ADDED_TO_MY_HAVEN_APP", "END_DATE", DECODE(END_DATE, NULL, FALSE, TRUE) 
FROM "HAVEN_RAW"."DIG_ARRIVALS_ETLEAP"."ARRIVAL";

desc view arrival;