-- 11/02/2025 
-- Playsafe

USE ROLE dba;

USE SCHEMA haven_base.playsafe;

CREATE VIEW haven_base.playsafe.MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, MACHINES, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, MACHINES, _ETLEAP_LOOKBACK_DATE
FROM haven_raw.playsafe.MACHINE_COLLECTIONS;

CREATE VIEW haven_base.playsafe.MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM haven_raw.playsafe.MACHINE_INVENTORY_LIST;

-- Team Card

USE ROLE dba;

USE SCHEMA haven_base.dig_team_card;

USE WAREHOUSE dba_wh;

CREATE VIEW HAVEN_BASE.DIG_TEAM_CARD.COUPON
( ID, SSOID, EAGLEEYECAMPAIGNID, "TYPE", CODE, PHYSICALCARDREQUESTED, PHYSICALCARDSENT, VALIDFROM, VALIDTO, CREATEDAT, UPDATEDAT, DELETEDAT, EAGLEEYEACCOUNTID, CREATEDBY, UPDATEDBY, DELETEDBY, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT ID, SSOID, EAGLEEYECAMPAIGNID, "TYPE", CODE, PHYSICALCARDREQUESTED, PHYSICALCARDSENT, VALIDFROM, VALIDTO, CREATEDAT, UPDATEDAT, DELETEDAT, EAGLEEYEACCOUNTID, CREATEDBY, UPDATEDBY, DELETEDBY, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_TEAM_CARD.COUPON;

CREATE VIEW HAVEN_BASE.DIG_TEAM_CARD.TEAMCARD
( SSOID, PARKCODE, EMAIL, FULLNAME, COMPANY, PATHTOIMAGE, CREATEDAT, UPDATEDAT, DELETEDAT, EAGLEEYEWALLETID, JOBTITLE, CREATEDBY, UPDATEDBY, DELETEDBY, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT SSOID, PARKCODE, EMAIL, FULLNAME, COMPANY, PATHTOIMAGE, CREATEDAT, UPDATEDAT, DELETEDAT, EAGLEEYEWALLETID, JOBTITLE, CREATEDBY, UPDATEDBY, DELETEDBY, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_TEAM_CARD.TEAMCARD;

-- Team Comms

USE ROLE dba;

USE SCHEMA haven_base.dig_team_comms;

USE WAREHOUSE dba_wh;

CREATE VIEW HAVEN_BASE.DIG_TEAM_COMMS.CATEGORY
( ID, NAME, CREATEDAT, DELETEDAT, KEY, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT ID, "NAME", CREATEDAT, DELETEDAT, "KEY", FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_TEAM_COMMS.CATEGORY;

CREATE VIEW HAVEN_BASE.DIG_TEAM_COMMS.ISSUE
( ID, SENTTOOWNERS, SENTTOGUESTS, PARKCODE, PLACEHOLDERVALUES, CREATEDBY, RESOLVEDBY, CREATEDAT, RESOLVEDAT, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT ID, SENTTOOWNERS, SENTTOGUESTS, PARKCODE, PLACEHOLDERVALUES, CREATEDBY, RESOLVEDBY, CREATEDAT, RESOLVEDAT, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_TEAM_COMMS.ISSUE;

CREATE VIEW HAVEN_BASE.DIG_TEAM_COMMS.MESSAGELOG
( ID, ISSUEID, TEMPLATEID, MESSAGETEXT, CREATEDAT, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT ID, ISSUEID, TEMPLATEID, MESSAGETEXT, CREATEDAT, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_TEAM_COMMS.MESSAGELOG;

CREATE VIEW HAVEN_BASE.DIG_TEAM_COMMS.TEMPLATE
( ID, NAME, CATEGORYID, TEXT, UNIQUENESSKEY, TEMPLATETYPE, CREATEDAT, DELETEDAT, FILE_MODIFICATION_TIME, END_DATE )
AS SELECT ID, "NAME", CATEGORYID, "TEXT", UNIQUENESSKEY, TEMPLATETYPE, CREATEDAT, DELETEDAT, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_TEAM_COMMS.TEMPLATE;

-- Venue Disruption

USE ROLE dba;

USE SCHEMA haven_base.dig_venue_disruption;

USE WAREHOUSE dba_wh;

CREATE VIEW HAVEN_BASE.DIG_VENUE_DISRUPTION.DISRUPTION_EXPIRY
( ID, DISRUPTIONID, EXPIRY, CREATEDBY, CREATEDAT, DELETEDAT )
AS SELECT ID, DISRUPTIONID, EXPIRY, CREATEDBY, CREATEDAT, DELETEDAT
FROM HAVEN_RAW.DIG_VENUE_DISRUPTION.DISRUPTION_EXPIRY;

CREATE VIEW HAVEN_BASE.DIG_VENUE_DISRUPTION.DISRUPTION_REASON
( ID, DISRUPTIONID, REASONID, CREATEDBY, CREATEDAT, DELETEDAT )
AS SELECT ID, DISRUPTIONID, REASONID, CREATEDBY, CREATEDAT, DELETEDAT
FROM HAVEN_RAW.DIG_VENUE_DISRUPTION.DISRUPTION_REASON;

CREATE VIEW HAVEN_BASE.DIG_VENUE_DISRUPTION.REASON
( ID, REASON, CREATEDBY, CREATEDAT, DELETEDAT, TEMPLATE )
AS SELECT ID, REASON, CREATEDBY, CREATEDAT, DELETEDAT, TEMPLATE
FROM HAVEN_RAW.DIG_VENUE_DISRUPTION.REASON;

-- 12/02/2025

-- haven experience arrivals

USE ROLE dba;

USE SCHEMA haven_base.dig_arrivals;


SELECT ID, PARK_CODE, ARRIVAL_DATE, DEPARTURE_DATE, HOLDER_ID, HOLDER_TYPE, ARRIVAL_TIME, ARRIVING_LATE, ARRIVED_AT, CANCELLED_AT, CREATED_AT, UPDATED_AT, IS_SURVEY_COMPLETED, SHORT_CODE, HOLIDAY_TYPE, ARRIVAL_SLOT, ADDED_TO_MY_HAVEN_APP, END_DATE
FROM HAVEN_RAW.DIG_ARRIVALS.ARRIVAL;

SELECT CODE, "NUMBER", STATUS, CREATED_AT, UPDATED_AT, ID, ARRIVAL_HOLDER_ID, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_ARRIVALS.CARAVAN;

SELECT ID, "TIMESTAMP", "NAME", FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_ARRIVALS.MIGRATIONS;

SELECT "TYPE", STATUS, LICENSE_PLATE, CREATED_AT, UPDATED_AT, ARRIVAL_ID, ID, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_ARRIVALS.TRANSPORTATION;



