USE ROLE securityadmin;

SHOW ROLES LIKE '_haven_store__experian%';

SHOW GRANTS OF ROLE _HAVEN_STORE__EXPERIAN__READER;

REVOKE ROLE _HAVEN_STORE__EXPERIAN__READER FROM ROLE ALATION_INTEGRATION;
REVOKE ROLE _HAVEN_STORE__EXPERIAN__READER FROM ROLE BOURNE_GOVERNANCE;
REVOKE ROLE _HAVEN_STORE__EXPERIAN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE__EXPERIAN__READER FROM ROLE HAVEN_DBT_TRANSFORM;
--REVOKE ROLE _HAVEN_STORE__EXPERIAN__READER FROM ROLE _HAVEN_STORE__EXPERIAN__WRITER

USE ROLE useradmin;

DROP ROLE _HAVEN_STORE__EXPERIAN__CREATOR;
DROP ROLE _HAVEN_STORE__EXPERIAN__OWNER;
DROP ROLE _HAVEN_STORE__EXPERIAN__READER;
DROP ROLE _HAVEN_STORE__EXPERIAN__USAGE;
DROP ROLE _HAVEN_STORE__EXPERIAN__WRITER;

USE ROLE sysadmin;

DROP SCHEMA haven_store.experian;

USE ROLE dba;
USE SCHEMA haven_base.experian;

CREATE VIEW haven_base.experian.CLIENT_HAVEN_PC_DIRECTORY
( POSTCODE_STANDARD_8_BYTES, POSTCODE_7_BYTE, POSTCODE_FORMAT3, POSTCODE_FORMAT4, POSTCODE_FORMAT5, POSTCODE_FORMAT6, COMPRESSED_POSTCODE_STANDARD_8_BYTES, EQUIVALENT_EXPERIAN_2023_POSTCODE, FLAG_EXPERIAN_2023_LIST_POSTCODE, PC_MOSAIC_UK7_GROUP, PC_MOSAIC_UK7_GROUP_NUMERIC, PC_MOSAIC_UK7_GROUP_LABEL, PC_MOSAIC_UK7_TYPE, PC_MOSAIC_UK7_TYPE_LABEL, BBC_TV_CODE, CHANNEL_4_AREA, EXPERIAN_POSTCODE_WGS84_LONGITUDE, EXPERIAN_POSTCODE_WGS84_LATITUDE )
AS SELECT POSTCODE_STANDARD_8_BYTES, POSTCODE_7_BYTE, POSTCODE_FORMAT3, POSTCODE_FORMAT4, POSTCODE_FORMAT5, POSTCODE_FORMAT6, COMPRESSED_POSTCODE_STANDARD_8_BYTES, EQUIVALENT_EXPERIAN_2023_POSTCODE, FLAG_EXPERIAN_2023_LIST_POSTCODE, PC_MOSAIC_UK7_GROUP, PC_MOSAIC_UK7_GROUP_NUMERIC, PC_MOSAIC_UK7_GROUP_LABEL, PC_MOSAIC_UK7_TYPE, PC_MOSAIC_UK7_TYPE_LABEL, BBC_TV_CODE, CHANNEL_4_AREA, EXPERIAN_POSTCODE_WGS84_LONGITUDE, EXPERIAN_POSTCODE_WGS84_LATITUDE
FROM EXPERIAN."PUBLIC".CLIENT_HAVEN_PC_DIRECTORY;

USE ROLE haven_data_transform;
USE WAREHOUSE haven_data_transform_warehouse_xsmall;

USE ROLE sysadmin;

SELECT POSTCODE_STANDARD_8_BYTES, POSTCODE_7_BYTE, POSTCODE_FORMAT3, POSTCODE_FORMAT4, POSTCODE_FORMAT5, POSTCODE_FORMAT6, COMPRESSED_POSTCODE_STANDARD_8_BYTES, EQUIVALENT_EXPERIAN_2023_POSTCODE, FLAG_EXPERIAN_2023_LIST_POSTCODE, PC_MOSAIC_UK7_GROUP, PC_MOSAIC_UK7_GROUP_NUMERIC, PC_MOSAIC_UK7_GROUP_LABEL, PC_MOSAIC_UK7_TYPE, PC_MOSAIC_UK7_TYPE_LABEL, BBC_TV_CODE, CHANNEL_4_AREA, EXPERIAN_POSTCODE_WGS84_LONGITUDE, EXPERIAN_POSTCODE_WGS84_LATITUDE
FROM HAVEN_STORE.EXPERIAN.CLIENT_HAVEN_PC_DIRECTORY
LIMIT 10;

