USE ROLE securityadmin;

GRANT ROLE _haven_raw__facebook__creator TO ROLE haven_etleap_dataload;

USE ROLE haven_stitch_integration;

SHOW WAREHOUSES;

USE WAREHOUSE bourne_stitch_warehouse_xsmall;

USE SCHEMA haven_raw.facebook;

SELECT 'ADCREATIVE', max(_sdc_received_at) FROM ADCREATIVE
UNION
SELECT 'ADS', max(_sdc_received_at) FROM ADS
UNION
SELECT 'ADSETS', max(_sdc_received_at) FROM ADSETS
UNION
SELECT 'ADS_INSIGHTS', max(_sdc_received_at) FROM ADS_INSIGHTS
UNION
SELECT 'ADS_INSIGHTS_AGE_AND_GENDER', max(_sdc_received_at) FROM ADS_INSIGHTS_AGE_AND_GENDER
UNION
SELECT 'ADS_INSIGHTS_COUNTRY', max(_sdc_received_at) FROM ADS_INSIGHTS_COUNTRY
UNION
SELECT 'ADS_INSIGHTS_DMA', max(_sdc_received_at) FROM ADS_INSIGHTS_DMA
UNION
SELECT 'ADS_INSIGHTS_HOURLY_ADVERTISER', max(_sdc_received_at) FROM ADS_INSIGHTS_HOURLY_ADVERTISER
UNION
SELECT 'ADS_INSIGHTS_PLATFORM_AND_DEVICE', max(_sdc_received_at) FROM ADS_INSIGHTS_PLATFORM_AND_DEVICE
UNION
SELECT 'ADS_INSIGHTS_REGION', max(_sdc_received_at) FROM ADS_INSIGHTS_REGION
UNION
SELECT 'CAMPAIGNS', max(_sdc_received_at) FROM CAMPAIGNS
UNION
SELECT 'CUSTOMERS', max(_sdc_received_at) FROM CUSTOMERS
UNION
SELECT 'CUSTOMERS1', max(_sdc_received_at) FROM CUSTOMERS1
UNION
SELECT 'FFFFF', max(_sdc_received_at) FROM FFFFF
UNION
SELECT 'LEADS', max(_sdc_received_at) FROM LEADS
UNION
SELECT 'LEADS_NEW', max(_sdc_received_at) FROM LEADS_NEW
UNION
SELECT 'ORDERS', max(_sdc_received_at) FROM ORDERS;



SHOW TABLES;

ALTER TABLE HAVEN_RAW.FACEBOOK.ADCREATIVE RENAME TO _ADCREATIVE_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADS RENAME TO _ADS_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADSETS RENAME TO _ADSETS_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADS_INSIGHTS RENAME TO _ADS_INSIGHTS_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADS_INSIGHTS_AGE_AND_GENDER RENAME TO _ADS_INSIGHTS_AGE_AND_GENDER_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADS_INSIGHTS_COUNTRY RENAME TO _ADS_INSIGHTS_COUNTRY_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADS_INSIGHTS_DMA RENAME TO _ADS_INSIGHTS_DMA_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADS_INSIGHTS_HOURLY_ADVERTISER RENAME TO _ADS_INSIGHTS_HOURLY_ADVERTISER_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADS_INSIGHTS_PLATFORM_AND_DEVICE RENAME TO _ADS_INSIGHTS_PLATFORM_AND_DEVICE_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ADS_INSIGHTS_REGION RENAME TO _ADS_INSIGHTS_REGION_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.CAMPAIGNS RENAME TO _CAMPAIGNS_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.CUSTOMERS RENAME TO _CUSTOMERS_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.CUSTOMERS1 RENAME TO _CUSTOMERS1_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.FFFFF RENAME TO _FFFFF_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.LEADS RENAME TO _LEADS_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.LEADS_NEW RENAME TO _LEADS_NEW_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK.ORDERS RENAME TO _ORDERS_STITCH_15012025;
ALTER TABLE HAVEN_RAW.FACEBOOK._SDC_REJECTED RENAME TO __SDC_REJECTED_STITCH_15012025;

SHOW TABLES;

USE ROLE HAVEN_ETLEAP_DATALOAD;

USE WAREHOUSE HAVEN_ETLEAP_DATALOAD_WAREHOUSE_XSMALL;

USE SCHEMA HAVEN_RAW.FACEBOOK;

CREATE TABLE HAVEN_RAW.FACEBOOK.INSIGHTS_BY_AD_ETLEAP_16012024 AS SELECT * FROM HAVEN_RAW.FACEBOOK_ETLEAP.INSIGHTS_BY_AD;
CREATE TABLE HAVEN_RAW.FACEBOOK.INSIGHTS_BY_ADSET_ETLEAP_16012024 AS SELECT * FROM HAVEN_RAW.FACEBOOK_ETLEAP.INSIGHTS_BY_ADSET;
CREATE TABLE HAVEN_RAW.FACEBOOK.INSIGHTS_BY_AD_2_ETLEAP_16012024 AS SELECT * FROM HAVEN_RAW.FACEBOOK_ETLEAP.INSIGHTS_BY_AD_2;
CREATE TABLE HAVEN_RAW.FACEBOOK.INSIGHTS_BY_CAMPAIGN_ETLEAP_16012024 AS SELECT * FROM HAVEN_RAW.FACEBOOK_ETLEAP.INSIGHTS_BY_CAMPAIGN;
CREATE TABLE HAVEN_RAW.FACEBOOK.LEAD_ADS_ETLEAP_16012024 AS SELECT * FROM HAVEN_RAW.FACEBOOK_ETLEAP.LEAD_ADS;
CREATE OR REPLACE TABLE HAVEN_RAW.FACEBOOK."_etleap" AS SELECT * FROM HAVEN_RAW.FACEBOOK_ETLEAP."_etleap";

DROP TABLE HAVEN_RAW.FACEBOOK.INSIGHTS_BY_AD;
DROP TABLE HAVEN_RAW.FACEBOOK.INSIGHTS_BY_ADSET;
DROP TABLE HAVEN_RAW.FACEBOOK.INSIGHTS_BY_AD_2;
DROP TABLE HAVEN_RAW.FACEBOOK.INSIGHTS_BY_CAMPAIGN;
DROP TABLE HAVEN_RAW.FACEBOOK.LEAD_ADS;



USE ROLE dba;

USE WAREHOUSE dba_wh;

USE SCHEMA haven_base.facebook;

DROP TABLE HAVEN_BASE.FACEBOOK.INSIGHTS_BY_AD;
CREATE VIEW HAVEN_BASE.FACEBOOK.INSIGHTS_BY_AD
( DATE_START, ACCOUNT_ID, AD_ID, VIDEO_THRUPLAY_WATCHED_ACTIONS, REACH, SOCIAL_SPEND, OBJECTIVE, BUYING_TYPE, ACTION_VALUES, VIDEO_30_SEC_WATCHED_ACTIONS, UNIQUE_OUTBOUND_CLICKS, UNIQUE_CLICKS, VIDEO_P75_WATCHED_ACTIONS, CAMPAIGN_ID, VIDEO_AVG_TIME_WATCHED_ACTIONS, VIDEO_P95_WATCHED_ACTIONS, INLINE_POST_ENGAGEMENT, ADSET_ID, ESTIMATED_AD_RECALLERS, ACTIONS, CONVERSIONS, ACCOUNT_CURRENCY, INLINE_LINK_CLICKS, ESTIMATED_AD_RECALL_RATE, CONVERTED_PRODUCT_VALUE, UNIQUE_ACTIONS, SPEND, VIDEO_PLAY_ACTIONS, DATE_STOP, UNIQUE_INLINE_LINK_CLICKS, VIDEO_P25_WATCHED_ACTIONS, VIDEO_P100_WATCHED_ACTIONS, VIDEO_P50_WATCHED_ACTIONS, OUTBOUND_CLICKS, QUALITY_RANKING, IMPRESSIONS, CLICKS, ENGAGEMENT_RATE_RANKING, ACCOUNT_NAME, AD_NAME, ADSET_NAME, CAMPAIGN_NAME )
AS SELECT DATE_START, ACCOUNT_ID, AD_ID, VIDEO_THRUPLAY_WATCHED_ACTIONS, REACH, SOCIAL_SPEND, OBJECTIVE, BUYING_TYPE, ACTION_VALUES, VIDEO_30_SEC_WATCHED_ACTIONS, UNIQUE_OUTBOUND_CLICKS, UNIQUE_CLICKS, VIDEO_P75_WATCHED_ACTIONS, CAMPAIGN_ID, VIDEO_AVG_TIME_WATCHED_ACTIONS, VIDEO_P95_WATCHED_ACTIONS, INLINE_POST_ENGAGEMENT, ADSET_ID, ESTIMATED_AD_RECALLERS, ACTIONS, CONVERSIONS, ACCOUNT_CURRENCY, INLINE_LINK_CLICKS, ESTIMATED_AD_RECALL_RATE, CONVERTED_PRODUCT_VALUE, UNIQUE_ACTIONS, SPEND, VIDEO_PLAY_ACTIONS, DATE_STOP, UNIQUE_INLINE_LINK_CLICKS, VIDEO_P25_WATCHED_ACTIONS, VIDEO_P100_WATCHED_ACTIONS, VIDEO_P50_WATCHED_ACTIONS, OUTBOUND_CLICKS, QUALITY_RANKING, IMPRESSIONS, CLICKS, ENGAGEMENT_RATE_RANKING, ACCOUNT_NAME, AD_NAME, ADSET_NAME, CAMPAIGN_NAME
FROM HAVEN_RAW.FACEBOOK.INSIGHTS_BY_AD;

DROP TABLE HAVEN_BASE.FACEBOOK.INSIGHTS_BY_AD_2;
CREATE VIEW HAVEN_BASE.FACEBOOK.INSIGHTS_BY_AD_2
( DATE_START, ACCOUNT_ID, AD_ID, COST_PER_ESTIMATED_AD_RECALLERS, VIDEO_THRUPLAY_WATCHED_ACTIONS, INSTANT_EXPERIENCE_CLICKS_TO_OPEN, REACH, ADSET_NAME, VIDEO_PLAY_CURVE_ACTIONS, SOCIAL_SPEND, COST_PER_UNIQUE_ACTION_TYPE, PLACE_PAGE_NAME, OBJECTIVE, FREQUENCY, BUYING_TYPE, ACTION_VALUES, VIDEO_30_SEC_WATCHED_ACTIONS, COST_PER_THRUPLAY, UNIQUE_OUTBOUND_CLICKS, UNIQUE_CLICKS, VIDEO_P75_WATCHED_ACTIONS, CPC, COST_PER_UNIQUE_INLINE_LINK_CLICK, CANVAS_AVG_VIEW_TIME, CAMPAIGN_ID, INLINE_LINK_CLICK_CTR, CTR, INSTAGRAM_UPCOMING_EVENT_REMINDERS_SET, CPM, CPP, CONVERSION_RATE_RANKING, VIDEO_AVG_TIME_WATCHED_ACTIONS, COST_PER_INLINE_LINK_CLICK, VIDEO_P95_WATCHED_ACTIONS, UNIQUE_LINK_CLICKS_CTR, SHOPS_ASSISTED_PURCHASES, FULL_VIEW_REACH, CONVERSION_VALUES, CATALOG_SEGMENT_VALUE, COST_PER_UNIQUE_OUTBOUND_CLICK, INLINE_POST_ENGAGEMENT, ADSET_ID, MARKETING_MESSAGES_SPEND, PURCHASE_ROAS, ESTIMATED_AD_RECALLERS, ACTIONS, COST_PER_UNIQUE_CLICK, CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS, UNIQUE_OUTBOUND_CLICKS_CTR, CONVERSIONS, ACCOUNT_CURRENCY, WEBSITE_CTR, INLINE_LINK_CLICKS, ESTIMATED_AD_RECALL_RATE, CONVERTED_PRODUCT_VALUE, COST_PER_ACTION_TYPE, OUTBOUND_CLICKS_CTR, CAMPAIGN_NAME, UNIQUE_INLINE_LINK_CLICK_CTR, COST_PER_INLINE_POST_ENGAGEMENT, UNIQUE_ACTIONS, MARKETING_MESSAGES_COST_PER_DELIVERED, SPEND, ACCOUNT_NAME, VIDEO_PLAY_ACTIONS, DATE_STOP, UNIQUE_INLINE_LINK_CLICKS, VIDEO_P25_WATCHED_ACTIONS, COST_PER_OUTBOUND_CLICK, VIDEO_P100_WATCHED_ACTIONS, CANVAS_AVG_VIEW_PERCENT, VIDEO_P50_WATCHED_ACTIONS, COST_PER_CONVERSION, OUTBOUND_CLICKS, QUALITY_RANKING, UNIQUE_CTR, CONVERTED_PRODUCT_QUANTITY, QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE, INSTANT_EXPERIENCE_CLICKS_TO_START, AD_NAME, IMPRESSIONS, FULL_VIEW_IMPRESSIONS, WEBSITE_PURCHASE_ROAS, CLICKS, ENGAGEMENT_RATE_RANKING, MARKETING_MESSAGES_WEBSITE_PURCHASE_VALUES, MOBILE_APP_PURCHASE_ROAS )
AS SELECT DATE_START, ACCOUNT_ID, AD_ID, COST_PER_ESTIMATED_AD_RECALLERS, VIDEO_THRUPLAY_WATCHED_ACTIONS, INSTANT_EXPERIENCE_CLICKS_TO_OPEN, REACH, ADSET_NAME, VIDEO_PLAY_CURVE_ACTIONS, SOCIAL_SPEND, COST_PER_UNIQUE_ACTION_TYPE, PLACE_PAGE_NAME, OBJECTIVE, FREQUENCY, BUYING_TYPE, ACTION_VALUES, VIDEO_30_SEC_WATCHED_ACTIONS, COST_PER_THRUPLAY, UNIQUE_OUTBOUND_CLICKS, UNIQUE_CLICKS, VIDEO_P75_WATCHED_ACTIONS, CPC, COST_PER_UNIQUE_INLINE_LINK_CLICK, CANVAS_AVG_VIEW_TIME, CAMPAIGN_ID, INLINE_LINK_CLICK_CTR, CTR, INSTAGRAM_UPCOMING_EVENT_REMINDERS_SET, CPM, CPP, CONVERSION_RATE_RANKING, VIDEO_AVG_TIME_WATCHED_ACTIONS, COST_PER_INLINE_LINK_CLICK, VIDEO_P95_WATCHED_ACTIONS, UNIQUE_LINK_CLICKS_CTR, SHOPS_ASSISTED_PURCHASES, FULL_VIEW_REACH, CONVERSION_VALUES, CATALOG_SEGMENT_VALUE, COST_PER_UNIQUE_OUTBOUND_CLICK, INLINE_POST_ENGAGEMENT, ADSET_ID, MARKETING_MESSAGES_SPEND, PURCHASE_ROAS, ESTIMATED_AD_RECALLERS, ACTIONS, COST_PER_UNIQUE_CLICK, CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS, UNIQUE_OUTBOUND_CLICKS_CTR, CONVERSIONS, ACCOUNT_CURRENCY, WEBSITE_CTR, INLINE_LINK_CLICKS, ESTIMATED_AD_RECALL_RATE, CONVERTED_PRODUCT_VALUE, COST_PER_ACTION_TYPE, OUTBOUND_CLICKS_CTR, CAMPAIGN_NAME, UNIQUE_INLINE_LINK_CLICK_CTR, COST_PER_INLINE_POST_ENGAGEMENT, UNIQUE_ACTIONS, MARKETING_MESSAGES_COST_PER_DELIVERED, SPEND, ACCOUNT_NAME, VIDEO_PLAY_ACTIONS, DATE_STOP, UNIQUE_INLINE_LINK_CLICKS, VIDEO_P25_WATCHED_ACTIONS, COST_PER_OUTBOUND_CLICK, VIDEO_P100_WATCHED_ACTIONS, CANVAS_AVG_VIEW_PERCENT, VIDEO_P50_WATCHED_ACTIONS, COST_PER_CONVERSION, OUTBOUND_CLICKS, QUALITY_RANKING, UNIQUE_CTR, CONVERTED_PRODUCT_QUANTITY, QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE, INSTANT_EXPERIENCE_CLICKS_TO_START, AD_NAME, IMPRESSIONS, FULL_VIEW_IMPRESSIONS, WEBSITE_PURCHASE_ROAS, CLICKS, ENGAGEMENT_RATE_RANKING, MARKETING_MESSAGES_WEBSITE_PURCHASE_VALUES, MOBILE_APP_PURCHASE_ROAS
FROM HAVEN_RAW.FACEBOOK.INSIGHTS_BY_AD_2;

CREATE VIEW HAVEN_BASE.FACEBOOK.INSIGHTS_BY_ADSET
( DATE_START, ACCOUNT_ID, ADSET_ID, COST_PER_ESTIMATED_AD_RECALLERS, VIDEO_THRUPLAY_WATCHED_ACTIONS, INSTANT_EXPERIENCE_CLICKS_TO_OPEN, REACH, ADSET_NAME, VIDEO_PLAY_CURVE_ACTIONS, SOCIAL_SPEND, COST_PER_UNIQUE_ACTION_TYPE, PLACE_PAGE_NAME, OBJECTIVE, FREQUENCY, BUYING_TYPE, ACTION_VALUES, VIDEO_30_SEC_WATCHED_ACTIONS, COST_PER_THRUPLAY, UNIQUE_OUTBOUND_CLICKS, UNIQUE_CLICKS, VIDEO_P75_WATCHED_ACTIONS, CPC, COST_PER_UNIQUE_INLINE_LINK_CLICK, CANVAS_AVG_VIEW_TIME, CAMPAIGN_ID, INLINE_LINK_CLICK_CTR, CTR, CPM, CPP, CONVERSION_RATE_RANKING, VIDEO_AVG_TIME_WATCHED_ACTIONS, COST_PER_INLINE_LINK_CLICK, VIDEO_P95_WATCHED_ACTIONS, UNIQUE_LINK_CLICKS_CTR, AD_ID, SHOPS_ASSISTED_PURCHASES, FULL_VIEW_REACH, CONVERSION_VALUES, CATALOG_SEGMENT_VALUE, COST_PER_UNIQUE_OUTBOUND_CLICK, INLINE_POST_ENGAGEMENT, MARKETING_MESSAGES_SPEND, PURCHASE_ROAS, ESTIMATED_AD_RECALLERS, ACTIONS, COST_PER_UNIQUE_CLICK, CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS, UNIQUE_OUTBOUND_CLICKS_CTR, CONVERSIONS, ACCOUNT_CURRENCY, WEBSITE_CTR, INLINE_LINK_CLICKS, ESTIMATED_AD_RECALL_RATE, CONVERTED_PRODUCT_VALUE, COST_PER_ACTION_TYPE, OUTBOUND_CLICKS_CTR, CAMPAIGN_NAME, UNIQUE_INLINE_LINK_CLICK_CTR, COST_PER_INLINE_POST_ENGAGEMENT, UNIQUE_ACTIONS, MARKETING_MESSAGES_COST_PER_DELIVERED, SPEND, ACCOUNT_NAME, VIDEO_PLAY_ACTIONS, DATE_STOP, UNIQUE_INLINE_LINK_CLICKS, VIDEO_P25_WATCHED_ACTIONS, COST_PER_OUTBOUND_CLICK, VIDEO_P100_WATCHED_ACTIONS, CANVAS_AVG_VIEW_PERCENT, VIDEO_P50_WATCHED_ACTIONS, COST_PER_CONVERSION, OUTBOUND_CLICKS, QUALITY_RANKING, UNIQUE_CTR, CONVERTED_PRODUCT_QUANTITY, QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE, INSTANT_EXPERIENCE_CLICKS_TO_START, AD_NAME, IMPRESSIONS, FULL_VIEW_IMPRESSIONS, WEBSITE_PURCHASE_ROAS, CLICKS, ENGAGEMENT_RATE_RANKING, MARKETING_MESSAGES_WEBSITE_PURCHASE_VALUES, MOBILE_APP_PURCHASE_ROAS )
AS SELECT DATE_START, ACCOUNT_ID, ADSET_ID, COST_PER_ESTIMATED_AD_RECALLERS, VIDEO_THRUPLAY_WATCHED_ACTIONS, INSTANT_EXPERIENCE_CLICKS_TO_OPEN, REACH, ADSET_NAME, VIDEO_PLAY_CURVE_ACTIONS, SOCIAL_SPEND, COST_PER_UNIQUE_ACTION_TYPE, PLACE_PAGE_NAME, OBJECTIVE, FREQUENCY, BUYING_TYPE, ACTION_VALUES, VIDEO_30_SEC_WATCHED_ACTIONS, COST_PER_THRUPLAY, UNIQUE_OUTBOUND_CLICKS, UNIQUE_CLICKS, VIDEO_P75_WATCHED_ACTIONS, CPC, COST_PER_UNIQUE_INLINE_LINK_CLICK, CANVAS_AVG_VIEW_TIME, CAMPAIGN_ID, INLINE_LINK_CLICK_CTR, CTR, CPM, CPP, CONVERSION_RATE_RANKING, VIDEO_AVG_TIME_WATCHED_ACTIONS, COST_PER_INLINE_LINK_CLICK, VIDEO_P95_WATCHED_ACTIONS, UNIQUE_LINK_CLICKS_CTR, AD_ID, SHOPS_ASSISTED_PURCHASES, FULL_VIEW_REACH, CONVERSION_VALUES, CATALOG_SEGMENT_VALUE, COST_PER_UNIQUE_OUTBOUND_CLICK, INLINE_POST_ENGAGEMENT, MARKETING_MESSAGES_SPEND, PURCHASE_ROAS, ESTIMATED_AD_RECALLERS, ACTIONS, COST_PER_UNIQUE_CLICK, CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS, UNIQUE_OUTBOUND_CLICKS_CTR, CONVERSIONS, ACCOUNT_CURRENCY, WEBSITE_CTR, INLINE_LINK_CLICKS, ESTIMATED_AD_RECALL_RATE, CONVERTED_PRODUCT_VALUE, COST_PER_ACTION_TYPE, OUTBOUND_CLICKS_CTR, CAMPAIGN_NAME, UNIQUE_INLINE_LINK_CLICK_CTR, COST_PER_INLINE_POST_ENGAGEMENT, UNIQUE_ACTIONS, MARKETING_MESSAGES_COST_PER_DELIVERED, SPEND, ACCOUNT_NAME, VIDEO_PLAY_ACTIONS, DATE_STOP, UNIQUE_INLINE_LINK_CLICKS, VIDEO_P25_WATCHED_ACTIONS, COST_PER_OUTBOUND_CLICK, VIDEO_P100_WATCHED_ACTIONS, CANVAS_AVG_VIEW_PERCENT, VIDEO_P50_WATCHED_ACTIONS, COST_PER_CONVERSION, OUTBOUND_CLICKS, QUALITY_RANKING, UNIQUE_CTR, CONVERTED_PRODUCT_QUANTITY, QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE, INSTANT_EXPERIENCE_CLICKS_TO_START, AD_NAME, IMPRESSIONS, FULL_VIEW_IMPRESSIONS, WEBSITE_PURCHASE_ROAS, CLICKS, ENGAGEMENT_RATE_RANKING, MARKETING_MESSAGES_WEBSITE_PURCHASE_VALUES, MOBILE_APP_PURCHASE_ROAS
FROM HAVEN_RAW.FACEBOOK.INSIGHTS_BY_ADSET;

CREATE VIEW HAVEN_BASE.FACEBOOK.INSIGHTS_BY_CAMPAIGN 
( DATE_START, ACCOUNT_ID, CAMPAIGN_ID, COST_PER_ESTIMATED_AD_RECALLERS, VIDEO_THRUPLAY_WATCHED_ACTIONS, INSTANT_EXPERIENCE_CLICKS_TO_OPEN, REACH, ADSET_NAME, VIDEO_PLAY_CURVE_ACTIONS, SOCIAL_SPEND, COST_PER_UNIQUE_ACTION_TYPE, PLACE_PAGE_NAME, OBJECTIVE, FREQUENCY, BUYING_TYPE, ACTION_VALUES, VIDEO_30_SEC_WATCHED_ACTIONS, COST_PER_THRUPLAY, UNIQUE_OUTBOUND_CLICKS, UNIQUE_CLICKS, VIDEO_P75_WATCHED_ACTIONS, CPC, COST_PER_UNIQUE_INLINE_LINK_CLICK, CANVAS_AVG_VIEW_TIME, INLINE_LINK_CLICK_CTR, CTR, CPM, CPP, CONVERSION_RATE_RANKING, VIDEO_AVG_TIME_WATCHED_ACTIONS, COST_PER_INLINE_LINK_CLICK, VIDEO_P95_WATCHED_ACTIONS, UNIQUE_LINK_CLICKS_CTR, AD_ID, SHOPS_ASSISTED_PURCHASES, FULL_VIEW_REACH, CONVERSION_VALUES, CATALOG_SEGMENT_VALUE, COST_PER_UNIQUE_OUTBOUND_CLICK, INLINE_POST_ENGAGEMENT, ADSET_ID, MARKETING_MESSAGES_SPEND, PURCHASE_ROAS, ESTIMATED_AD_RECALLERS, ACTIONS, COST_PER_UNIQUE_CLICK, CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS, UNIQUE_OUTBOUND_CLICKS_CTR, CONVERSIONS, ACCOUNT_CURRENCY, WEBSITE_CTR, INLINE_LINK_CLICKS, ESTIMATED_AD_RECALL_RATE, CONVERTED_PRODUCT_VALUE, COST_PER_ACTION_TYPE, OUTBOUND_CLICKS_CTR, CAMPAIGN_NAME, UNIQUE_INLINE_LINK_CLICK_CTR, COST_PER_INLINE_POST_ENGAGEMENT, UNIQUE_ACTIONS, MARKETING_MESSAGES_COST_PER_DELIVERED, SPEND, ACCOUNT_NAME, VIDEO_PLAY_ACTIONS, DATE_STOP, UNIQUE_INLINE_LINK_CLICKS, VIDEO_P25_WATCHED_ACTIONS, COST_PER_OUTBOUND_CLICK, VIDEO_P100_WATCHED_ACTIONS, CANVAS_AVG_VIEW_PERCENT, VIDEO_P50_WATCHED_ACTIONS, COST_PER_CONVERSION, OUTBOUND_CLICKS, QUALITY_RANKING, UNIQUE_CTR, CONVERTED_PRODUCT_QUANTITY, QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE, INSTANT_EXPERIENCE_CLICKS_TO_START, AD_NAME, IMPRESSIONS, FULL_VIEW_IMPRESSIONS, WEBSITE_PURCHASE_ROAS, CLICKS, ENGAGEMENT_RATE_RANKING, MARKETING_MESSAGES_WEBSITE_PURCHASE_VALUES, MOBILE_APP_PURCHASE_ROAS )
AS SELECT DATE_START, ACCOUNT_ID, CAMPAIGN_ID, COST_PER_ESTIMATED_AD_RECALLERS, VIDEO_THRUPLAY_WATCHED_ACTIONS, INSTANT_EXPERIENCE_CLICKS_TO_OPEN, REACH, ADSET_NAME, VIDEO_PLAY_CURVE_ACTIONS, SOCIAL_SPEND, COST_PER_UNIQUE_ACTION_TYPE, PLACE_PAGE_NAME, OBJECTIVE, FREQUENCY, BUYING_TYPE, ACTION_VALUES, VIDEO_30_SEC_WATCHED_ACTIONS, COST_PER_THRUPLAY, UNIQUE_OUTBOUND_CLICKS, UNIQUE_CLICKS, VIDEO_P75_WATCHED_ACTIONS, CPC, COST_PER_UNIQUE_INLINE_LINK_CLICK, CANVAS_AVG_VIEW_TIME, INLINE_LINK_CLICK_CTR, CTR, CPM, CPP, CONVERSION_RATE_RANKING, VIDEO_AVG_TIME_WATCHED_ACTIONS, COST_PER_INLINE_LINK_CLICK, VIDEO_P95_WATCHED_ACTIONS, UNIQUE_LINK_CLICKS_CTR, AD_ID, SHOPS_ASSISTED_PURCHASES, FULL_VIEW_REACH, CONVERSION_VALUES, CATALOG_SEGMENT_VALUE, COST_PER_UNIQUE_OUTBOUND_CLICK, INLINE_POST_ENGAGEMENT, ADSET_ID, MARKETING_MESSAGES_SPEND, PURCHASE_ROAS, ESTIMATED_AD_RECALLERS, ACTIONS, COST_PER_UNIQUE_CLICK, CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS, UNIQUE_OUTBOUND_CLICKS_CTR, CONVERSIONS, ACCOUNT_CURRENCY, WEBSITE_CTR, INLINE_LINK_CLICKS, ESTIMATED_AD_RECALL_RATE, CONVERTED_PRODUCT_VALUE, COST_PER_ACTION_TYPE, OUTBOUND_CLICKS_CTR, CAMPAIGN_NAME, UNIQUE_INLINE_LINK_CLICK_CTR, COST_PER_INLINE_POST_ENGAGEMENT, UNIQUE_ACTIONS, MARKETING_MESSAGES_COST_PER_DELIVERED, SPEND, ACCOUNT_NAME, VIDEO_PLAY_ACTIONS, DATE_STOP, UNIQUE_INLINE_LINK_CLICKS, VIDEO_P25_WATCHED_ACTIONS, COST_PER_OUTBOUND_CLICK, VIDEO_P100_WATCHED_ACTIONS, CANVAS_AVG_VIEW_PERCENT, VIDEO_P50_WATCHED_ACTIONS, COST_PER_CONVERSION, OUTBOUND_CLICKS, QUALITY_RANKING, UNIQUE_CTR, CONVERTED_PRODUCT_QUANTITY, QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE, INSTANT_EXPERIENCE_CLICKS_TO_START, AD_NAME, IMPRESSIONS, FULL_VIEW_IMPRESSIONS, WEBSITE_PURCHASE_ROAS, CLICKS, ENGAGEMENT_RATE_RANKING, MARKETING_MESSAGES_WEBSITE_PURCHASE_VALUES, MOBILE_APP_PURCHASE_ROAS
FROM HAVEN_RAW.FACEBOOK.INSIGHTS_BY_CAMPAIGN;

CREATE VIEW HAVEN_BASE.FACEBOOK.LEAD_ADS
( ID, CREATED_TIME, PARTNER_NAME, HOME_LISTING, ADSET_NAME, FORM_ID, AD_NAME, PLATFORM, VEHICLE, RETAILER_ITEM_ID, CAMPAIGN_NAME, AD_ID, POST, IS_ORGANIC, FIELD_NAME, FIELD_VALUES, CUSTOM_DISCLAIMER_RESPONSES, ADSET_ID, CAMPAIGN_ID )
AS SELECT ID, CREATED_TIME, PARTNER_NAME, HOME_LISTING, ADSET_NAME, FORM_ID, AD_NAME, PLATFORM, VEHICLE, RETAILER_ITEM_ID, CAMPAIGN_NAME, AD_ID, POST, IS_ORGANIC, FIELD_NAME, FIELD_VALUES, CUSTOM_DISCLAIMER_RESPONSES, ADSET_ID, CAMPAIGN_ID
FROM HAVEN_RAW.FACEBOOK.LEAD_ADS;

