USE ROLE dba;

SHOW ROLES LIKE '_haven_%sales%__reader';

USE ROLE securityadmin;

GRANT ROLE _HAVEN_BASE__FACEBOOK_CARAVAN_SALES_LEADS__READER TO ROLE haven_data_transform;
GRANT ROLE _HAVEN_BASE__FACEBOOK_CARAVAN_SALES__READER TO ROLE haven_data_transform;
GRANT ROLE _HAVEN_BASE__FACEBOOK_HOLIDAY_SALES__READER TO ROLE haven_data_transform;

GRANT ROLE _HAVEN_RAW__FACEBOOK_CARAVAN_SALES_LEADS__READER TO ROLE haven_data_integrate;
GRANT ROLE _HAVEN_RAW__FACEBOOK_CARAVAN_SALES__READER TO ROLE haven_data_integrate;
GRANT ROLE _HAVEN_RAW__FACEBOOK_HOLIDAY_SALES__READER TO ROLE haven_data_integrate;

GRANT ROLE _HAVEN_RAW__FACEBOOK_CARAVAN_SALES_LEADS__CREATOR TO ROLE haven_stitch_integration; 
GRANT ROLE _HAVEN_RAW__FACEBOOK_CARAVAN_SALES__CREATOR TO ROLE haven_stitch_integration;
GRANT ROLE _HAVEN_RAW__FACEBOOK_HOLIDAY_SALES__CREATOR TO ROLE haven_stitch_integration;
