use role securityadmin;

REVOKE SELECT ON VIEW HAVEN_STORE_DEV.SAS_SCV.BOOKING_APC_SCHEDULE FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_DEV.SAS_SCV.BOOKING_CURRENT FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_DEV.SAS_SCV.BOOKING_HIST FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_DEV.SAS_SCV.BOOKING_ORIGINAL FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_DEV.SAS_SCV.SN_CAMPAIGN FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_DEV.SAS_SCV.SN_COMMUNICATION FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_DEV.SAS_SCV.SN_CONTACT_HISTORY FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;

REVOKE SELECT ON VIEW HAVEN_STORE_QAT.SAS_SCV.BOOKING_APC_SCHEDULE FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_QAT.SAS_SCV.BOOKING_CURRENT FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_QAT.SAS_SCV.BOOKING_HIST FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_QAT.SAS_SCV.BOOKING_ORIGINAL FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_QAT.SAS_SCV.SN_CAMPAIGN FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_QAT.SAS_SCV.SN_COMMUNICATION FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_QAT.SAS_SCV.SN_CONTACT_HISTORY FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;

REVOKE SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.BOOKING_APC_SCHEDULE FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.BOOKING_CURRENT FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.BOOKING_HIST FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.BOOKING_ORIGINAL FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.SN_CAMPAIGN FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.SN_COMMUNICATION FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;
REVOKE SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.SN_CONTACT_HISTORY FROM ROLE _HAVEN_COMMERCIAL__HAVEN_STORE__SAS_SCV__READER;


use role useradmin;

create role _HAVEN_COMMERCIAL__HAVEN_STORE_UAT__SAS_SCV__READER;

use role securityadmin;

GRANT SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.BOOKING_APC_SCHEDULE TO ROLE _HAVEN_COMMERCIAL__HAVEN_STORE_UAT__SAS_SCV__READER;
GRANT SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.BOOKING_CURRENT TO ROLE _HAVEN_COMMERCIAL__HAVEN_STORE_UAT__SAS_SCV__READER;
GRANT SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.BOOKING_HIST TO ROLE _HAVEN_COMMERCIAL__HAVEN_STORE_UAT__SAS_SCV__READER;
GRANT SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.BOOKING_ORIGINAL TO ROLE _HAVEN_COMMERCIAL__HAVEN_STORE_UAT__SAS_SCV__READER;
GRANT SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.SN_CAMPAIGN TO ROLE _HAVEN_COMMERCIAL__HAVEN_STORE_UAT__SAS_SCV__READER;
GRANT SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.SN_COMMUNICATION TO ROLE _HAVEN_COMMERCIAL__HAVEN_STORE_UAT__SAS_SCV__READER;
GRANT SELECT ON VIEW HAVEN_STORE_UAT.SAS_SCV.SN_CONTACT_HISTORY TO ROLE _HAVEN_COMMERCIAL__HAVEN_STORE_UAT__SAS_SCV__READER;
