USE ROLE dba;

USE SCHEMA warner_raw.ma_mart;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_EM_BAU_SEEDS
( SUBJECT_ID, PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS )
AS SELECT SUBJECT_ID, PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS
FROM WARNER_RAW.MA_MART.D_WRN_EM_BAU_SEEDS
;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_EMAIL_SEEDS
( ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE )
AS SELECT ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE
FROM WARNER_RAW.MA_MART.D_WRN_EMAIL_SEEDS
;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_CANOPY_SEEDS
( ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE )
AS SELECT ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE
FROM WARNER_RAW.MA_MART.D_WRN_CANOPY_SEEDS;


USE ROLE WARNER_TERRAFORM_TRANSFORM_DEV;
USE WAREHOUSE WARNER_TERRAFORM_TRANSFORM_DEV_warehouse_xsmall;

USE SCHEMA warner_cust.ma_mart;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_HOUSEHOLD
( ADDRESS_ID )
AS SELECT ADDRESS_ID
FROM WARNER_BASE.MA_MART.D_WRN_HOUSEHOLD;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_CONTACT_RESPONSE
( TASK_NAME, TASK_CODE, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, SEGMENT_MAP_NAME, CONTACT_DATE, CONTACT_DTTM, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, EMAIL_CLICK_DTTM)
AS SELECT TASK_NAME, TASK_CODE, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, SEGMENT_MAP_NAME, CONTACT_DATE, CONTACT_DTTM, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, EMAIL_CLICK_DTTM
FROM WARNER_BASE.MA_MART.D_WRN_CONTACT_RESPONSE;

CREATE OR REPLACE VIEW WARNER_CUST.MA_MART.D_WRN_CANOPY_SEEDS
( ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE )
AS SELECT ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE
FROM WARNER_BASE.MA_MART.D_WRN_CANOPY_SEEDS;




SHOW views;

SELECT count(*) FROM D_WRN_EM_BAU_SEEDS;
SELECT count(*) FROM D_WRN_EMAIL_SEEDS;
SELECT count(*) FROM warner_cust.MA_MART.D_WRN_CANOPY_SEEDS;

