-- 13/11/2025

select * from HAVEN_BASE.Aztec_RETAIL.messageline limit 10; --'DATE_VALUE'          
select * from HAVEN_BASE.Aztec_RETAIL.productline limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.apportionedtax limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.payments limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.accountnumberassigned limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.orderlinediscounted limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.orderlinepromoted limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.billdiscountline limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.promotionline limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.loyaltyaccountassigned limit 10; --'DATE_VALUE'
select * from HAVEN_BASE.Aztec_RETAIL.products limit 10; --'IMPORT_EXPORT_REFERENCE'
select * from HAVEN_BASE.Aztec_RETAIL.draweropened limit 10; --'DATE_VALUE'
 


desc view HAVEN_BASE.AZTEC_RETAIL.ACCOUNTNUMBERASSIGNED

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.ACCOUNTNUMBERASSIGNED
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, ACCOUNT_NUMBER, SEAT_NUMBER, ISDRIVETHRUACCOUNT, ISDELAYEDORDERACCOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, ACCOUNT_NUMBER, SEAT_NUMBER, ISDRIVETHRUACCOUNT, ISDELAYEDORDERACCOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.ACCOUNTNUMBERASSIGNED;

DESC VIEW HAVEN_BASE.AZTEC_RETAIL.APPORTIONEDTAX

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.APPORTIONEDTAX
( TERMINALID, ORDERLINE, TAX, TRANSACTION_NUMBER, ACCOUNTID, DATE, TAXPAID, EXCLUSIVE, SERVICECHARGE, TAXONSERVICECHARGE, LMDT )
AS SELECT TERMINALID, ORDERLINE, TAX, TRANSACTION_NUMBER, ACCOUNTID, "DATE", TAXPAID, "Exclusive", SERVICECHARGE, TAXONSERVICECHARGE, LMDT
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.APPORTIONEDTAX;

DESC VIEW HAVEN_BASE.AZTEC_RETAIL.BILLDISCOUNTLINE;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.BILLDISCOUNTLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", MOVETYPE, BILLDISCOUNTLINE, BILLPROMOTION, AMOUNT, CORRECTEDORDER, ACCOUNTNUMBER, AUTHORISATIONREFERENCE, MANUALLYKEYED, EXTERNALMODEID, EXTERNALQUALIFYINGPRODUCT, PERCENTAGE, CANCELLINGINCREASEBALANCEDISCOUNT, LMDT, OWNERID, AUTHORISER, ORIGINALDATETIME, DISCOUNTREASON, APPLIESTOORDERLINEFAMILY )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", MOVETYPE, BILLDISCOUNTLINE, BILLPROMOTION, AMOUNT, CORRECTEDORDER, ACCOUNTNUMBER, AUTHORISATIONREFERENCE, MANUALLYKEYED, EXTERNALMODEID, EXTERNALQUALIFYINGPRODUCT, PERCENTAGE, CANCELLINGINCREASEBALANCEDISCOUNT, LMDT, OWNERID, AUTHORISER, ORIGINALDATETIME, DISCOUNTREASON, APPLIESTOORDERLINEFAMILY
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.BILLDISCOUNTLINE;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.DRAWEROPENED
( TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, ACCOUNTID, LMDT, AUTHORISER, TRAINING )
AS SELECT TRANSACTIONID, "DATE", TERMINALID, EMPLOYEEID, ACCOUNTID, LMDT, AUTHORISER, TRAINING
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.DRAWEROPENED;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.LOYALTYACCOUNTASSIGNED
( TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, LOYALTYACCOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, LOYALTYACCOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.LOYALTYACCOUNTASSIGNED;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.MESSAGELINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", ORDERLINE, CORRECTEDORDERLINE, MOVETYPE, MESSAGELINE, LMDT, OWNERID, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", ORDERLINE, CORRECTEDORDERLINE, MOVETYPE, MESSAGELINE, LMDT, OWNERID, AUTHORISER
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.MESSAGELINE;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.ORDERLINEDISCOUNTED
( TRANSACTIONID, DATE, BUSINESSDATE, EMPLOYEEID, AUTHORISER, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, BILLDISCOUNTLINE, ORDERLINE, AMOUNTDISCOUNTED, LMDT )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, EMPLOYEEID, AUTHORISER, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, BILLDISCOUNTLINE, ORDERLINE, AMOUNTDISCOUNTED, LMDT
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.ORDERLINEDISCOUNTED;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.ORDERLINEPROMOTED
( TRANSACTIONID, DATE, BUSINESSDATE, EMPLOYEEID, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, PROMOTIONLINE, ORDERLINE, DISTRIBUTEDQUANTITY, AMOUNTDISCOUNTED, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, EMPLOYEEID, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, PROMOTIONLINE, ORDERLINE, DISTRIBUTEDQUANTITY, AMOUNTDISCOUNTED, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.ORDERLINEPROMOTED;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.PAYMENTS
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", PAYMENT, AMOUNT, CHANGE, PAYMENTMETHOD, RECEIPTNO, CORRECTEDORDER, MOVETYPE, TIP, PAYMENTCOUNT, LMDT, CASH_BACK, ISEFT, PROCESSED, PAYOUT, ISCASHBACK, OWNERID, AUTHORISER, ACCOUNTNUMBER, REPORTINGEMPLOYEEID, AMOUNTINTENDEREDCURRENCY, FORFEITAMOUNT, TERMINALSESSIONID, MONEYBELTPAYMENT, ORIGINALDATETIME )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", PAYMENT, AMOUNT, "CHANGE", PAYMENTMETHOD, RECEIPTNO, CORRECTEDORDER, MOVETYPE, TIP, PAYMENTCOUNT, LMDT, CASH_BACK, ISEFT, PROCESSED, PAYOUT, ISCASHBACK, OWNERID, AUTHORISER, ACCOUNTNUMBER, REPORTINGEMPLOYEEID, AMOUNTINTENDEREDCURRENCY, FORFEITAMOUNT, TERMINALSESSIONID, MONEYBELTPAYMENT, ORIGINALDATETIME
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.PAYMENTS;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.PRODUCTLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", ORDERLINE, CORRECTEDORDERLINE, QUANTITY, PRICE, MOVETYPE, PRODUCT, HALF, RATIO, PORTION, CORRECTIONMETHOD, CORRECTIONREASON, TARIFFPRICE, LMDT, OWNERID, UNITPRICE, AUTHORISER, SPECIALVOUCHERSALE, ORDERDESTINATION, MULTICHOICEMODE, PRICETYPE, ORIGINALDATETIME )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", ORDERLINE, CORRECTEDORDERLINE, QUANTITY, PRICE, MOVETYPE, PRODUCT, HALF, RATIO, PORTION, CORRECTIONMETHOD, CORRECTIONREASON, TARIFFPRICE, LMDT, OWNERID, UNITPRICE, AUTHORISER, SPECIALVOUCHERSALE, ORDERDESTINATION, MULTICHOICEMODE, PRICETYPE, ORIGINALDATETIME
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.PRODUCTLINE;

DESC VIEW HAVEN_BASE.AZTEC_RETAIL.PRODUCTS;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.PRODUCTS
( ENTITYCODE, RETAIL_NAME, RETAIL_DESCRIPTION, ENTITY_TYPE, IMPORT_EXPORT_REFERENCE, SUB_CATEGORY_NAME, DEFAULT_PRINTER_STREAM, PERCENT_ALCOHOL, WHETHER_SALES_TAXABLE, WHETHER_OPEN_PRICED, PURCHASE_NAME, PURCHASE_UNIT, DEFAULT_SUPPLIER, BUDGETED_COST_PRICE, LMDT, MODIFIED_BY, CREATION_DATE, DELETED, AZTECEPOSBUTTON1, AZTECEPOSBUTTON2, AZTECEPOSBUTTON3, EXTENDED_RTL_NAME, SPECIALRECIPE, TRUEHALFALLOWED, COURSEID, PRINTSTREAMWHENCHILD, ROLLUPPRICEWHENCHILD, FOLLOWCOURSEWHENCHILD, ISGIFTCARD, DISCONTINUE, SOLDBYWEIGHT, B2BNAME )
AS SELECT ENTITYCODE, RETAIL_NAME, RETAIL_DESCRIPTION, ENTITY_TYPE, "Import/Export_Reference", "Sub-Category_Name", DEFAULT_PRINTER_STREAM, "%_Alcohol", WHETHER_SALES_TAXABLE, WHETHER_OPEN_PRICED, PURCHASE_NAME, PURCHASE_UNIT, DEFAULT_SUPPLIER, BUDGETED_COST_PRICE, LMDT, MODIFIED_BY, CREATION_DATE, DELETED, AZTECEPOSBUTTON1, AZTECEPOSBUTTON2, AZTECEPOSBUTTON3, EXTENDED_RTL_NAME, SPECIALRECIPE, TRUEHALFALLOWED, COURSEID, PRINTSTREAMWHENCHILD, ROLLUPPRICEWHENCHILD, FOLLOWCOURSEWHENCHILD, ISGIFTCARD, DISCONTINUE, SOLDBYWEIGHT, B2BNAME
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.PRODUCTS;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_RETAIL.PROMOTIONLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, PROMOTIONLINE, PROMOTION, AMOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, PROMOTIONLINE, PROMOTION, AMOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_RETAIL_ETLEAP.PROMOTIONLINE;




-- 06/11/2025

use ROLE dba;

use SCHEMA haven_base.dig_playpass;

SHOW views;

-- HAVEN_BASE.DIG_DIGITAL_PASS.DIGITAL_PASS source

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_PLAYPASS.CLAIM
( CREATEDAT, UPDATEDAT, DELETEDAT, ID, ISLEADGUEST, ISCLAIMED, HID, PURCHASEID, LASTNAME )
AS SELECT CREATEDAT, UPDATEDAT, DELETEDAT, ID, ISLEADGUEST, ISCLAIMED, HID, PURCHASEID, LASTNAME
FROM HAVEN_RAW.DIG_PLAYPASS.CLAIM;

use ROLE dba;

use SCHEMA haven_base.dig_arrivals;

SELECT * FROM anpr_device LIMIT 50;


SELECT *
FROM HAVEN_RAW.DIG_ARRIVALS_ETLEAP.ANPR_DEVICE
LIMIT 50;

SELECT get_ddl('view', 'anpr_device');

create or replace view ANPR_DEVICE(
	ID,
	PARK_CODE,
	MAC_ADDRESS,
	CREATED_AT,
	UPDATED_AT,
	FILE_MODIFICATION_TIME,
	DELETED_DATE,
	IS_DELETED
) as SELECT "ID", "PARK_CODE", "MAC_ADDRESS", "CREATED_AT", "UPDATED_AT", "FILE_MODIFICATION_TIME", "END_DATE", DECODE(END_DATE, NULL, FALSE, TRUE) 
FROM "HAVEN_RAW"."DIG_ARRIVALS_ETLEAP"."ANPR_DEVICE";


-- 17/11/2025

use ROLE dba;

use SCHEMA haven_base.freshsales;

CREATE OR replace VIEW haven_base.freshsales.deals
( ID, NAME, AMOUNT, RECORD_TYPE_ID, CURRENCY_ID, BASE_CURRENCY_AMOUNT, DEAL_STAGE_ID, DEAL_REASON_ID, DEAL_TYPE_ID, OWNER_ID, EXPECTED_CLOSE, CLOSED_DATE, LEAD_SOURCE_ID, CAMPAIGN_ID, DEAL_PRODUCT_ID, DEAL_PAYMENT_STATUS_ID, PROBABILITY, CREATED_AT, UPDATED_AT, TERRITORY_ID, DEAL_PIPELINE_ID, STAGE_UPDATED_TIME, AGE, LINKS_NOTES, LINKS_CONVERSATIONS, LINKS_APPOINTMENTS, LINKS_TASKS, LINKS_DOCUMENT_ASSOCIATIONS, RECENT_NOTE, COMPLETED_SALES_SEQUENCES, ACTIVE_SALES_SEQUENCES, WEB_FORM_ID, UPCOMING_ACTIVITIES_TIME, LAST_ASSIGNED_AT, LAST_CONTACTED_SALES_ACTIVITY_MODE, LAST_CONTACTED_VIA_SALES_ACTIVITY, EXPECTED_DEAL_VALUE, IS_DELETED, TEAM_USER_IDS, AVATAR, FC_WIDGET_COLLABORATION_AUTH_TOKEN, FC_WIDGET_COLLABORATION_CONVO_TOKEN, FC_WIDGET_COLLABORATION_ENCODED_JWT_TOKEN, FORECAST_CATEGORY, DEAL_PREDICTION, DEAL_PREDICTION_LAST_UPDATED_AT, FREDDY_FORECAST_METRICS, LAST_DEAL_PREDICTION, HAS_PRODUCTS, ROTTEN_DAYS, CUSTOM_FIELD_CF_APPT_TIME, CUSTOM_FIELD_CF_VISIT_HOUR, CUSTOM_FIELD_CF_MINS, CUSTOM_FIELD_CF_ENQ_TITLE_DEAL, CUSTOM_FIELD_CF_ENQ_FIRST_NAME_DEAL, CUSTOM_FIELD_CF_ENQ_LAST_NAME_DEAL, CUSTOM_FIELD_CF_ENQ_MOBILE_DEAL, CUSTOM_FIELD_CF_ORIGINAL_PARK_INTEREST, CUSTOM_FIELD_CF_DISTANCE_TO_PARK_IN_KM, CUSTOM_FIELD_CF_ENQ_POSTCODE_DEAL, CUSTOM_FIELD_CF_INTENT_SCORE, CUSTOM_FIELD_CF_PREFERRED_DATE_OF_VISIT, CUSTOM_FIELD_CF_NEXT_CONTACT_DATE, CUSTOM_FIELD_CF_EMAIL, CUSTOM_FIELD_CF_ASSIGNED_BY_HHHR, CUSTOM_FIELD_CF_DATE_ORIGINAL_TELESALES_APPT_CREATED, CUSTOM_FIELD_CF_ORIGINAL_VAN_OF_INTEREST, CUSTOM_FIELD_CF_BEEN_TO_THE_PARK, CUSTOM_FIELD_CF_TELESALES_REBOOKING, CUSTOM_FIELD_CF_AAV, CUSTOM_FIELD_CF_HAVE_YOU_BEEN_ON_A_HAVEN_HOLIDAY, CUSTOM_FIELD_CF_BUDGET, CUSTOM_FIELD_CF_NUMBER_OF_BEDROOMS, CUSTOM_FIELD_CF_WHATS_YOUR_MONTHLY_BUDGET, CUSTOM_FIELD_CF_CENTRAL_HEATING_DOUBLE_GLAZING, CUSTOM_FIELD_CF_NEW_USED, CUSTOM_FIELD_CF_ARE_YOU_INTERESTED_IN_LET_TO_OWN, CUSTOM_FIELD_CF_WOULD_YOU_LIKE_TO_OFF_SET_THE_COSTS, CUSTOM_FIELD_CF_OPT_IN, CUSTOM_FIELD_CF_HAS_A_PET__DOGS_CATS_ETC_, CUSTOM_FIELD_CF_NO_OF_ADULTS, CUSTOM_FIELD_CF_NUMBER_OF_KIDS, CUSTOM_FIELD_CF_ENQ_OWNER_DEAL, CUSTOM_FIELD_CF_ENQ_ALLOCATED_DEAL, CUSTOM_FIELD_CF_LATEST_SOURCE, CUSTOM_FIELD_CF_DATE_OF_BROCHURE_DOWNLOAD, CUSTOM_FIELD_CF_ENQ_CITY_DEAL, CUSTOM_FIELD_CF_ENQ_ADDRESS_DEAL, CUSTOM_FIELD_CF_CUSTOMER_ANSWERED_TM_CALL, CUSTOM_FIELD_CF_VISIT_SCHEDULED_ON, CUSTOM_FIELD_CF_APPT_OUTCOME, CUSTOM_FIELD_CF_APPT_NO_SHOW, CUSTOM_FIELD_CF_HOUR, CUSTOM_FIELD_CF_MINUTES, CUSTOM_FIELD_CF_DATE_OF_APPOINTMENT_MADE, CUSTOM_FIELD_CF_ENQ_COUNTY, CUSTOM_FIELD_CF_CALLBACK_HOUR, CUSTOM_FIELD_CF_VISIT_FOLLOW_UP, CUSTOM_FIELD_CF_QUOTE_FOLLOW_UP, CUSTOM_FIELD_CF_CANCELLED_FOLLOW_UP, CUSTOM_FIELD_CF_LEAD_FOLLOW_UP, CUSTOM_FIELD_CF_PLOT_EMAIL, CUSTOM_FIELD_CF_PARK_BOOKED_VISIT_MINS, CUSTOM_FIELD_CF_PARK_BOOKED_VISIT_HOUR, CUSTOM_FIELD_CF_PLOT_FIRST_NAME, CUSTOM_FIELD_CF_TELESALES_APPT_SHOW_CHECK, CUSTOM_FIELD_CF_PLOT_LAST_NAME, CUSTOM_FIELD_CF_PLOT_POSTCODE, CUSTOM_FIELD_CF_PLOT_TITLE, CUSTOM_FIELD_CF_CALLBACK_DATE, CUSTOM_FIELD_CF_PARK_BOOKED_VISIT_DATE, CUSTOM_FIELD_CF_DID_THE_APPOINTMENT_SHOW_ON_PARK, CUSTOM_FIELD_CF_USER_INPUT_FOR_PARK_INFO, CUSTOM_FIELD_CF_APPOINTMENT_BOOKING_CHANNEL, CUSTOM_FIELD_CF_APPOINTMENT_MADE_ON_PARK, CUSTOM_FIELD_CF_PARK_INFO, CUSTOM_FIELD_CF_APPOINTMENT_CONFIRMED, CUSTOM_FIELD_CF_OWNERSHIP_JOURNEY_STAGE, CUSTOM_FIELD_CF_ORIGINAL_APPT_DATE, CUSTOM_FIELD_CF_TELESALES_FIRST_CONTACTED_AT, CUSTOM_FIELD_CF_TELESALES_CALL_ATTEMPTS, CUSTOM_FIELD_CF_LATEST_SOURCE_UPDATED_AT, CUSTOM_FIELD_CF_CONVERTED_BY_TELEMARKTING, CUSTOM_FIELD_CF_APPOINTMENT_CONFIRMED_DATE, CUSTOM_FIELD_CF_APPOINTMENT_SHOW_DATE, CUSTOM_FIELD_CF_APPOINTMENT_NO_SHOW_DATE, CUSTOM_FIELD_CF_ORIGINAL_VISIT_DATE, CUSTOM_FIELD_CF_OPT_OUT_OF_CALLS__REASONS, CUSTOM_FIELD_CF_OTHER_PLEASE_SPECIFY__OPT_OUT_REASONS, CUSTOM_FIELD_CF_REGION, CUSTOM_FIELD_CF_WALK_IN_DATE, CUSTOM_FIELD_CF_GETTING_TO_KNOW_YOU, CUSTOM_FIELD_CF_EXPLAINING_HOW_WE_CAN_HELP, CUSTOM_FIELD_CF_DATA_TYPE, CUSTOM_FIELD_CF_7_DAY_COUNTDOWN_SET, CUSTOM_FIELD_CF_APPOINTMENT_BOOKED_BY, CUSTOM_FIELD_CF_TEAM_BOOKED_BY, CUSTOM_FIELD_CF_DISTANCE_SCORE, CUSTOM_FIELD_CF_FUNNEL_SCORE, CUSTOM_FIELD_CF_PARK_SCORE, CUSTOM_FIELD_CF_SOURCE_SCORE, CUSTOM_FIELD_CF_CALL_SCORE, CUSTOM_FIELD_CF_VISIT_ALREADY_BOOKED, CUSTOM_FIELD_CF_FIRST_CONTACT_MADE, CUSTOM_FIELD_CF_TENTATIVE_TIME_TO_BUY, CUSTOM_FIELD_CF_WHATS_YOU_CURRENT_STAGE_IN_BUYING_A_CARAVAN_, CUSTOM_FIELD_CF_OTHER_PLEASE_SPECIFY, CUSTOM_FIELD_CF_AUDIENCE, CUSTOM_FIELD_CF_FOLLOW_UP_DEAL, CUSTOM_FIELD_CF_TELEMARKETING_INFLUENCED_BY, CUSTOM_FIELD_CF_ORIGINAL_PREBOOKED_SOURCE, CUSTOM_FIELD_CF_WORKED_BY_TELEMARKETING, CUSTOM_FIELD_CF_TELEMARKETING_LAST_CONTACTED, CUSTOM_FIELD_CF_POSTCODE_LENGTH, CUSTOM_FIELD_CF_ASSIGNED_BY_HHHR_AT, CUSTOM_FIELD_CF_PARK_CODE, CUSTOM_FIELD_CF_ARRIVED_WITH_NO_APPOINTMENT_BOOKED, CUSTOM_FIELD_CF_AMPLITUDE_SESSION_ID, CUSTOM_FIELD_CF_REBOOK_CALL_ATTEMPTS, CUSTOM_FIELD_CF_QUEUE_ID, CUSTOM_FIELD_CF_SESSION_ID, CUSTOM_FIELD_CF_DEVICE_ID, CUSTOM_FIELD_CF_ENQUIRY_ID, CUSTOM_FIELD_CF_ORIGINAL_SHOW_DATE, CUSTOM_FIELD_CF_PLOT_ID, CUSTOM_FIELD_CF_PLOT_QUOTE_CREATED_DATE, CUSTOM_FIELD_CF_PLOT_QUOTE_VAN_ID, CUSTOM_FIELD_CF_PLOT_QUOTE_PITCH_ID, CUSTOM_FIELD_CF_PLOT_QUOTE_VALUE, CUSTOM_FIELD_CF_PLOT_QUOTE_STATUS, CUSTOM_FIELD_CF_PLOT_SALE_VALIDATED_DATE, CUSTOM_FIELD_CF_PLOT_EXPECTED_COMPLETION_DATE, CUSTOM_FIELD_CF_PLOT_SALE_VAN_ID, CUSTOM_FIELD_CF_PLOT_SALE_PITCH_ID, CUSTOM_FIELD_CF_PLOT_SALE_VALUE, CUSTOM_FIELD_CF_ORIGINAL_VALIDATED_SALE_DATE, CUSTOM_FIELD_CF_PLOT_CANCELLATION_DATE, CUSTOM_FIELD_CF_PLOT_CANCELLATION_REASON, CUSTOM_FIELD_CF_COMPLETION_DATE, CUSTOM_FIELD_CF_PLOT_KEY_HANDOVER_DATE, COLLABORATION, CUSTOM_FIELD_CF_TM__CONFIRMED, CUSTOM_FIELD_CF_TM_TEAM_DEAL, CUSTOM_FIELD_CF_TM__CONFIRMED_TAG, CUSTOM_FIELD_CF_TM__CONF_TAG, CUSTOM_FIELD_CF_TM__PROMOTION_CAMPAIGN, CUSTOM_FIELD_CF_TM__PROMOTION_AGENT_NAME, CUSTOM_FIELD_CF_TM__PROMOTIONS_AGENT_NAME, CUSTOM_FIELD_CF_TM__PROMOTION_CAMPAIGNS, CUSTOM_FIELD_CF_DEAL__QR_CODE, CUSTOM_FIELD_CF_TRIGGER_UPDATE, CUSTOM_FIELD_CF_FORCE_UPDATE, CUSTOM_FIELD_CF_TM__ORIGINAL_DEAL_AGENT, CUSTOM_FIELD_CF_PARK_QR_CODE, UPDATER_ID_DISPLAY_NAME, CONTACT_IDS, CREATER_ID_DISPLAY_NAME, UPDATER_ID_EMAIL, CREATER_ID_EMAIL, UPDATER_ID_WORK_NUMBER, CREATER_ID_IS_ACTIVE, SALES_ACCOUNT_ID, CREATER_ID_WORK_NUMBER, UPDATER_ID_IS_ACTIVE, CREATER_ID_ID, UPDATER_ID_ID, SALES_ACTIVITY_IDS, UPDATER_ID_MOBILE_NUMBER, CREATER_ID_MOBILE_NUMBER, DEAL_STAGE_FORECAST_TYPE, CREATER_MOBILE_NUMBER, CURRENCY_CURRENCY_CODE, CAMPAIGN, OWNER_EMAIL, DEAL_TYPE, CURRENCY_SCHEDULE_INFO, SALES_ACCOUNT, DEAL_REASON_ID1, DEAL_STAGE_PROBABILITY, CREATER_EMAIL, CREATER_ID, OWNER_ID1, DEAL_STAGE_PARTIAL, LEAD_SOURCE_PARTIAL, CREATER_WORK_NUMBER, CURRENCY_PARTIAL, OWNER_MOBILE_NUMBER, OWNER_WORK_NUMBER, CREATER_DISPLAY_NAME, DEAL_STAGE_DEAL_PIPELINE_ID, DEAL_STAGE_NAME, DEAL_PAYMENT_STATUS, CURRENCY_RATE_CHANGE_IDS, CURRENCY_IS_ACTIVE, DEAL_STAGE_POSITION, DEAL_REASON_PARTIAL, DEAL_REASON_NAME, DEAL_STAGE_UPDATED_AT, UPDATER_EMAIL, DEAL_STAGE_CHOICE_TYPE, LEAD_SOURCE_NAME, LEAD_SOURCE_ID1, DEAL_PRODUCT, DEAL_STAGE_ID1, OWNER_DISPLAY_NAME, UPDATER_ID, OWNER_IS_ACTIVE, CURRENCY_CURRENCY_TYPE, DEAL_REASON_POSITION, CURRENCY_ID1, CONTACT, CURRENCY_EXCHANGE_RATE, UPDATER_WORK_NUMBER, UPDATER_MOBILE_NUMBER, UPDATER_DISPLAY_NAME, UPDATER_IS_ACTIVE, CREATER_IS_ACTIVE, LEAD_SOURCE_POSITION, CUSTOM_FIELD_CF_SEAWARE_HOLIDAY_DATES, CUSTOM_FIELD_CF_LATEST_SEAWARE_RES_ID, CUSTOM_FIELD_CF_SEAWARE_ALLOCATED_VAN, OWNER_UUID, OWNER_TYPE, OWNER_AVATAR, CUSTOM_FIELD_CF_SEAWARE_BOOKED_CHANNEL, CUSTOM_FIELD_CF_SEAWARE_BOOKED_GRADE, CUSTOM_FIELD_CF_SEAWARE_REQUEST_GRADE, CUSTOM_FIELD_CF_SEAWARE_BOOKING_INVOICE, CUSTOM_FIELD_CF_SEAWARE_RES_STATUS, CUSTOM_FIELD_CF_SEAWARE_PACKAGE_TYPE, CUSTOM_FIELD_CF_AVG_APPT_UPDATE, CUSTOM_FIELD_CF_QUALTRICS_NVR, CUSTOM_FIELD_CF_QUALTRICS_CARAVAN_MODEL, CUSTOM_FIELD_CF_QUALTRICS_DISTANCE, CUSTOM_FIELD_CF_QUALTRICS_PARK, CUSTOM_FIELD_CF_QUALTRICS_BOOKING_PRODUCT, CUSTOM_FIELD_CF_QUALTRICS_CARAVAN_MAKE, CUSTOM_FIELD_CF_QUALTRICS_COMMENTS, CUSTOM_FIELD_CF_QUALTRICS_BOOKED_GRADE, CUSTOM_FIELD_CF_QUALTRICS_BOOKING_NIGHTS, CUSTOM_FIELD_CF_QUALTRICS_BOOKING_PRICE, CUSTOM_FIELD_CF_QUALTRICS_BOOKING_REF, CUSTOM_FIELD_CF_QUALTRICS_CHILDREN_MAKEUP, CUSTOM_FIELD_CF_QUALTRICS_NPS, CUSTOM_FIELD_CF_HOLIDAY_BOOKED, CUSTOM_FIELD_CF_HO_CLOSE_DATE, CUSTOM_FIELD_CF_HO_COMMENTS, CUSTOM_FIELD_CF_HO_CONTACT_CHANNEL, CUSTOM_FIELD_CF_BOOKING_REFERENCE, CUSTOM_FIELD_CF_HOLIDAY_ARRIVAL_DATE, CUSTOM_FIELD_CF_HO_CANCELLED_REASON, CUSTOM_FIELD_CF_IS_DUPLICATED, CUSTOM_FIELD_CF_OTHER_PARKS_VISITED, CUSTOM_FIELD_CF_VISITING_OTHER_PARKS, CUSTOM_FIELD_CF_QUOTE_OUTCOME_DETAIL, CUSTOM_FIELD_CF_APPOINTMENT_OUTCOME_DETAIL, CUSTOM_FIELD_CF_DATE_OF_QUOTE, CUSTOM_FIELD_CF_8X8ENDTIME, CUSTOM_FIELD_CF_8X8CALLTERMINATIONSTATE, CUSTOM_FIELD_CF_8X8CALLRECORDINGURL, CUSTOM_FIELD_CF_8X8CALLDIRECTION, CUSTOM_FIELD_CF_8X8STARTTIME, CUSTOM_FIELD_CF_8X8AGENT, CUSTOM_FIELD_CF_8X8CALLDURATION, CUSTOM_FIELD_CF_8X8CHANNEL, CUSTOM_FIELD_CF_PARK_FACILITIES, CUSTOM_FIELD_CF_NEARBY_ACTIVITIES, CUSTOM_FIELD_CF_OWNERSHIP_EXPERIENCE, CUSTOM_FIELD_CF_PITCH_PREFERENCE, CUSTOM_FIELD_CF_DRIVE_TIME, CUSTOM_FIELD_CF_PITCH_PREF, CUSTOM_FIELD_CF_QUOTE_FOLLOW_UP_DETAIL, CUSTOM_FIELD_CF_QUOTE_FOLLOW_UP_NOTES, CUSTOM_FIELD_CF_DM_TEST, CUSTOM_FIELD_CF_APPT_OUTCOME_NOTES, CUSTOM_FIELD_CF_TEST_ACCOUNT, CUSTOM_FIELD_CF_DID_THE_CUSTOMER_ASK_ABOUT_SITE_FEES, CUSTOM_FIELD_CF_APPT_OUTCOME_FEEDBACK, CUSTOM_FIELD_CF_TPS, CUSTOM_FIELD_CF_ENQUIRY_KIND, CUSTOM_FIELD_CF_PX_SUITABLE_TO_LET_DATE_CHANGE, CUSTOM_FIELD_CF_PX_CURRENT_EST_VALUE, CUSTOM_FIELD_CF_PX_YEARS_OF_OWNERSHIP, CUSTOM_FIELD_CF_PX_PITCH_GRADE, CUSTOM_FIELD_CF_PX_MAKE, CUSTOM_FIELD_CF_PX_VAN_GRADE, CUSTOM_FIELD_CF_PX_VALUE, CUSTOM_FIELD_CF_PX_VAN_AGE, CUSTOM_FIELD_CF_PX_CURRENT_PITCH_SITE_FEES, CUSTOM_FIELD_CF_CSN_NUMBER, CUSTOM_FIELD_CF_PX_LETTING_STATUS, CUSTOM_FIELD_CF_PARK_CODE_FORMULA, CUSTOM_FIELD_CF_OWNER_IDPARK_CODE, CUSTOM_FIELD_CF_SALE_MANAGER, CUSTOM_FIELD_CF_SOURCE_CODE, CUSTOM_FIELD_CF_SOURCE_SUBCODE, CUSTOM_FIELD_CF_ORIGINAL_SALES_OWNER, CUSTOM_FIELD_CF_FIRST_SALES_OWNER, CUSTOM_FIELD_CF_SMS_APPT_CONFIRMED, CUSTOM_FIELD_CF_SMS, CUSTOM_FIELD_CF_CONTACT_CENTRE_INTENT_SCORE, CUSTOM_FIELD_CF_SMS_SENT, CUSTOM_FIELD_CF_APPOINTMENT_TRAVEL_ARRANGEMENTS, CUSTOM_FIELD_CF_CAR_REG, CUSTOM_FIELD_CF_REENGAGEMENT_ONLINE, CUSTOM_FIELD_CF_REENGAGEMENT_LOST_REASON, CUSTOM_FIELD_CF_SMS_SENT_DATE, CUSTOM_FIELD_CF_DEAL_CREATED_VIA_SMS, CUSTOM_FIELD_CF_TM_RECONTACT_PHONE, CUSTOM_FIELD_CF_TM_RECONTACT_DATE, CUSTOM_FIELD_CF_TMFCNOTES, CUSTOM_FIELD_CF_ARRIVING_VIA, CUSTOM_FIELD_CF_CAR_REG_ID )
AS SELECT ID, NAME, AMOUNT, RECORD_TYPE_ID, CURRENCY_ID, BASE_CURRENCY_AMOUNT, DEAL_STAGE_ID, DEAL_REASON_ID, DEAL_TYPE_ID, OWNER_ID, EXPECTED_CLOSE, CLOSED_DATE, LEAD_SOURCE_ID, CAMPAIGN_ID, DEAL_PRODUCT_ID, DEAL_PAYMENT_STATUS_ID, PROBABILITY, CREATED_AT, UPDATED_AT, TERRITORY_ID, DEAL_PIPELINE_ID, STAGE_UPDATED_TIME, AGE, LINKS_NOTES, LINKS_CONVERSATIONS, LINKS_APPOINTMENTS, LINKS_TASKS, LINKS_DOCUMENT_ASSOCIATIONS, RECENT_NOTE, COMPLETED_SALES_SEQUENCES, ACTIVE_SALES_SEQUENCES, WEB_FORM_ID, UPCOMING_ACTIVITIES_TIME, LAST_ASSIGNED_AT, LAST_CONTACTED_SALES_ACTIVITY_MODE, LAST_CONTACTED_VIA_SALES_ACTIVITY, EXPECTED_DEAL_VALUE, IS_DELETED, TEAM_USER_IDS, AVATAR, FC_WIDGET_COLLABORATION_AUTH_TOKEN, FC_WIDGET_COLLABORATION_CONVO_TOKEN, FC_WIDGET_COLLABORATION_ENCODED_JWT_TOKEN, FORECAST_CATEGORY, DEAL_PREDICTION, DEAL_PREDICTION_LAST_UPDATED_AT, FREDDY_FORECAST_METRICS, LAST_DEAL_PREDICTION, HAS_PRODUCTS, ROTTEN_DAYS, CUSTOM_FIELD_CF_APPT_TIME, CUSTOM_FIELD_CF_VISIT_HOUR, CUSTOM_FIELD_CF_MINS, CUSTOM_FIELD_CF_ENQ_TITLE_DEAL, CUSTOM_FIELD_CF_ENQ_FIRST_NAME_DEAL, CUSTOM_FIELD_CF_ENQ_LAST_NAME_DEAL, CUSTOM_FIELD_CF_ENQ_MOBILE_DEAL, CUSTOM_FIELD_CF_ORIGINAL_PARK_INTEREST, CUSTOM_FIELD_CF_DISTANCE_TO_PARK_IN_KM, CUSTOM_FIELD_CF_ENQ_POSTCODE_DEAL, CUSTOM_FIELD_CF_INTENT_SCORE, CUSTOM_FIELD_CF_PREFERRED_DATE_OF_VISIT, CUSTOM_FIELD_CF_NEXT_CONTACT_DATE, CUSTOM_FIELD_CF_EMAIL, CUSTOM_FIELD_CF_ASSIGNED_BY_HHHR, CUSTOM_FIELD_CF_DATE_ORIGINAL_TELESALES_APPT_CREATED, CUSTOM_FIELD_CF_ORIGINAL_VAN_OF_INTEREST, CUSTOM_FIELD_CF_BEEN_TO_THE_PARK, CUSTOM_FIELD_CF_TELESALES_REBOOKING, CUSTOM_FIELD_CF_AAV, CUSTOM_FIELD_CF_HAVE_YOU_BEEN_ON_A_HAVEN_HOLIDAY, CUSTOM_FIELD_CF_BUDGET, CUSTOM_FIELD_CF_NUMBER_OF_BEDROOMS, CUSTOM_FIELD_CF_WHATS_YOUR_MONTHLY_BUDGET, CUSTOM_FIELD_CF_CENTRAL_HEATING_DOUBLE_GLAZING, CUSTOM_FIELD_CF_NEW_USED, CUSTOM_FIELD_CF_ARE_YOU_INTERESTED_IN_LET_TO_OWN, CUSTOM_FIELD_CF_WOULD_YOU_LIKE_TO_OFF_SET_THE_COSTS, CUSTOM_FIELD_CF_OPT_IN, CUSTOM_FIELD_CF_HAS_A_PET__DOGS_CATS_ETC_, CUSTOM_FIELD_CF_NO_OF_ADULTS, CUSTOM_FIELD_CF_NUMBER_OF_KIDS, CUSTOM_FIELD_CF_ENQ_OWNER_DEAL, CUSTOM_FIELD_CF_ENQ_ALLOCATED_DEAL, CUSTOM_FIELD_CF_LATEST_SOURCE, CUSTOM_FIELD_CF_DATE_OF_BROCHURE_DOWNLOAD, CUSTOM_FIELD_CF_ENQ_CITY_DEAL, CUSTOM_FIELD_CF_ENQ_ADDRESS_DEAL, CUSTOM_FIELD_CF_CUSTOMER_ANSWERED_TM_CALL, CUSTOM_FIELD_CF_VISIT_SCHEDULED_ON, CUSTOM_FIELD_CF_APPT_OUTCOME, CUSTOM_FIELD_CF_APPT_NO_SHOW, CUSTOM_FIELD_CF_HOUR, CUSTOM_FIELD_CF_MINUTES, CUSTOM_FIELD_CF_DATE_OF_APPOINTMENT_MADE, CUSTOM_FIELD_CF_ENQ_COUNTY, CUSTOM_FIELD_CF_CALLBACK_HOUR, CUSTOM_FIELD_CF_VISIT_FOLLOW_UP, CUSTOM_FIELD_CF_QUOTE_FOLLOW_UP, CUSTOM_FIELD_CF_CANCELLED_FOLLOW_UP, CUSTOM_FIELD_CF_LEAD_FOLLOW_UP, CUSTOM_FIELD_CF_PLOT_EMAIL, CUSTOM_FIELD_CF_PARK_BOOKED_VISIT_MINS, CUSTOM_FIELD_CF_PARK_BOOKED_VISIT_HOUR, CUSTOM_FIELD_CF_PLOT_FIRST_NAME, CUSTOM_FIELD_CF_TELESALES_APPT_SHOW_CHECK, CUSTOM_FIELD_CF_PLOT_LAST_NAME, CUSTOM_FIELD_CF_PLOT_POSTCODE, CUSTOM_FIELD_CF_PLOT_TITLE, CUSTOM_FIELD_CF_CALLBACK_DATE, CUSTOM_FIELD_CF_PARK_BOOKED_VISIT_DATE, CUSTOM_FIELD_CF_DID_THE_APPOINTMENT_SHOW_ON_PARK, CUSTOM_FIELD_CF_USER_INPUT_FOR_PARK_INFO, CUSTOM_FIELD_CF_APPOINTMENT_BOOKING_CHANNEL, CUSTOM_FIELD_CF_APPOINTMENT_MADE_ON_PARK, CUSTOM_FIELD_CF_PARK_INFO, CUSTOM_FIELD_CF_APPOINTMENT_CONFIRMED, CUSTOM_FIELD_CF_OWNERSHIP_JOURNEY_STAGE, CUSTOM_FIELD_CF_ORIGINAL_APPT_DATE, CUSTOM_FIELD_CF_TELESALES_FIRST_CONTACTED_AT, CUSTOM_FIELD_CF_TELESALES_CALL_ATTEMPTS, CUSTOM_FIELD_CF_LATEST_SOURCE_UPDATED_AT, CUSTOM_FIELD_CF_CONVERTED_BY_TELEMARKTING, CUSTOM_FIELD_CF_APPOINTMENT_CONFIRMED_DATE, CUSTOM_FIELD_CF_APPOINTMENT_SHOW_DATE, CUSTOM_FIELD_CF_APPOINTMENT_NO_SHOW_DATE, CUSTOM_FIELD_CF_ORIGINAL_VISIT_DATE, CUSTOM_FIELD_CF_OPT_OUT_OF_CALLS__REASONS, CUSTOM_FIELD_CF_OTHER_PLEASE_SPECIFY__OPT_OUT_REASONS, CUSTOM_FIELD_CF_REGION, CUSTOM_FIELD_CF_WALK_IN_DATE, CUSTOM_FIELD_CF_GETTING_TO_KNOW_YOU, CUSTOM_FIELD_CF_EXPLAINING_HOW_WE_CAN_HELP, CUSTOM_FIELD_CF_DATA_TYPE, CUSTOM_FIELD_CF_7_DAY_COUNTDOWN_SET, CUSTOM_FIELD_CF_APPOINTMENT_BOOKED_BY, CUSTOM_FIELD_CF_TEAM_BOOKED_BY, CUSTOM_FIELD_CF_DISTANCE_SCORE, CUSTOM_FIELD_CF_FUNNEL_SCORE, CUSTOM_FIELD_CF_PARK_SCORE, CUSTOM_FIELD_CF_SOURCE_SCORE, CUSTOM_FIELD_CF_CALL_SCORE, CUSTOM_FIELD_CF_VISIT_ALREADY_BOOKED, CUSTOM_FIELD_CF_FIRST_CONTACT_MADE, CUSTOM_FIELD_CF_TENTATIVE_TIME_TO_BUY, CUSTOM_FIELD_CF_WHATS_YOU_CURRENT_STAGE_IN_BUYING_A_CARAVAN_, CUSTOM_FIELD_CF_OTHER_PLEASE_SPECIFY, CUSTOM_FIELD_CF_AUDIENCE, CUSTOM_FIELD_CF_FOLLOW_UP_DEAL, CUSTOM_FIELD_CF_TELEMARKETING_INFLUENCED_BY, CUSTOM_FIELD_CF_ORIGINAL_PREBOOKED_SOURCE, CUSTOM_FIELD_CF_WORKED_BY_TELEMARKETING, CUSTOM_FIELD_CF_TELEMARKETING_LAST_CONTACTED, CUSTOM_FIELD_CF_POSTCODE_LENGTH, CUSTOM_FIELD_CF_ASSIGNED_BY_HHHR_AT, CUSTOM_FIELD_CF_PARK_CODE, CUSTOM_FIELD_CF_ARRIVED_WITH_NO_APPOINTMENT_BOOKED, CUSTOM_FIELD_CF_AMPLITUDE_SESSION_ID, CUSTOM_FIELD_CF_REBOOK_CALL_ATTEMPTS, CUSTOM_FIELD_CF_QUEUE_ID, CUSTOM_FIELD_CF_SESSION_ID, CUSTOM_FIELD_CF_DEVICE_ID, CUSTOM_FIELD_CF_ENQUIRY_ID, CUSTOM_FIELD_CF_ORIGINAL_SHOW_DATE, CUSTOM_FIELD_CF_PLOT_ID, CUSTOM_FIELD_CF_PLOT_QUOTE_CREATED_DATE, CUSTOM_FIELD_CF_PLOT_QUOTE_VAN_ID, CUSTOM_FIELD_CF_PLOT_QUOTE_PITCH_ID, CUSTOM_FIELD_CF_PLOT_QUOTE_VALUE, CUSTOM_FIELD_CF_PLOT_QUOTE_STATUS, CUSTOM_FIELD_CF_PLOT_SALE_VALIDATED_DATE, CUSTOM_FIELD_CF_PLOT_EXPECTED_COMPLETION_DATE, CUSTOM_FIELD_CF_PLOT_SALE_VAN_ID, CUSTOM_FIELD_CF_PLOT_SALE_PITCH_ID, CUSTOM_FIELD_CF_PLOT_SALE_VALUE, CUSTOM_FIELD_CF_ORIGINAL_VALIDATED_SALE_DATE, CUSTOM_FIELD_CF_PLOT_CANCELLATION_DATE, CUSTOM_FIELD_CF_PLOT_CANCELLATION_REASON, CUSTOM_FIELD_CF_COMPLETION_DATE, CUSTOM_FIELD_CF_PLOT_KEY_HANDOVER_DATE, COLLABORATION, CUSTOM_FIELD_CF_TM__CONFIRMED, CUSTOM_FIELD_CF_TM_TEAM_DEAL, CUSTOM_FIELD_CF_TM__CONFIRMED_TAG, CUSTOM_FIELD_CF_TM__CONF_TAG, CUSTOM_FIELD_CF_TM__PROMOTION_CAMPAIGN, CUSTOM_FIELD_CF_TM__PROMOTION_AGENT_NAME, CUSTOM_FIELD_CF_TM__PROMOTIONS_AGENT_NAME, CUSTOM_FIELD_CF_TM__PROMOTION_CAMPAIGNS, CUSTOM_FIELD_CF_DEAL__QR_CODE, CUSTOM_FIELD_CF_TRIGGER_UPDATE, CUSTOM_FIELD_CF_FORCE_UPDATE, CUSTOM_FIELD_CF_TM__ORIGINAL_DEAL_AGENT, CUSTOM_FIELD_CF_PARK_QR_CODE, UPDATER_ID_DISPLAY_NAME, CONTACT_IDS, CREATER_ID_DISPLAY_NAME, UPDATER_ID_EMAIL, CREATER_ID_EMAIL, UPDATER_ID_WORK_NUMBER, CREATER_ID_IS_ACTIVE, SALES_ACCOUNT_ID, CREATER_ID_WORK_NUMBER, UPDATER_ID_IS_ACTIVE, CREATER_ID_ID, UPDATER_ID_ID, SALES_ACTIVITY_IDS, UPDATER_ID_MOBILE_NUMBER, CREATER_ID_MOBILE_NUMBER, DEAL_STAGE_FORECAST_TYPE, CREATER_MOBILE_NUMBER, CURRENCY_CURRENCY_CODE, CAMPAIGN, OWNER_EMAIL, DEAL_TYPE, CURRENCY_SCHEDULE_INFO, SALES_ACCOUNT, DEAL_REASON_ID1, DEAL_STAGE_PROBABILITY, CREATER_EMAIL, CREATER_ID, OWNER_ID1, DEAL_STAGE_PARTIAL, LEAD_SOURCE_PARTIAL, CREATER_WORK_NUMBER, CURRENCY_PARTIAL, OWNER_MOBILE_NUMBER, OWNER_WORK_NUMBER, CREATER_DISPLAY_NAME, DEAL_STAGE_DEAL_PIPELINE_ID, DEAL_STAGE_NAME, DEAL_PAYMENT_STATUS, CURRENCY_RATE_CHANGE_IDS, CURRENCY_IS_ACTIVE, DEAL_STAGE_POSITION, DEAL_REASON_PARTIAL, DEAL_REASON_NAME, DEAL_STAGE_UPDATED_AT, UPDATER_EMAIL, DEAL_STAGE_CHOICE_TYPE, LEAD_SOURCE_NAME, LEAD_SOURCE_ID1, DEAL_PRODUCT, DEAL_STAGE_ID1, OWNER_DISPLAY_NAME, UPDATER_ID, OWNER_IS_ACTIVE, CURRENCY_CURRENCY_TYPE, DEAL_REASON_POSITION, CURRENCY_ID1, CONTACT, CURRENCY_EXCHANGE_RATE, UPDATER_WORK_NUMBER, UPDATER_MOBILE_NUMBER, UPDATER_DISPLAY_NAME, UPDATER_IS_ACTIVE, CREATER_IS_ACTIVE, LEAD_SOURCE_POSITION, CUSTOM_FIELD_CF_SEAWARE_HOLIDAY_DATES, CUSTOM_FIELD_CF_LATEST_SEAWARE_RES_ID, CUSTOM_FIELD_CF_SEAWARE_ALLOCATED_VAN, OWNER_UUID, OWNER_TYPE, OWNER_AVATAR, CUSTOM_FIELD_CF_SEAWARE_BOOKED_CHANNEL, CUSTOM_FIELD_CF_SEAWARE_BOOKED_GRADE, CUSTOM_FIELD_CF_SEAWARE_REQUEST_GRADE, CUSTOM_FIELD_CF_SEAWARE_BOOKING_INVOICE, CUSTOM_FIELD_CF_SEAWARE_RES_STATUS, CUSTOM_FIELD_CF_SEAWARE_PACKAGE_TYPE, CUSTOM_FIELD_CF_AVG_APPT_UPDATE, CUSTOM_FIELD_CF_QUALTRICS_NVR, CUSTOM_FIELD_CF_QUALTRICS_CARAVAN_MODEL, CUSTOM_FIELD_CF_QUALTRICS_DISTANCE, CUSTOM_FIELD_CF_QUALTRICS_PARK, CUSTOM_FIELD_CF_QUALTRICS_BOOKING_PRODUCT, CUSTOM_FIELD_CF_QUALTRICS_CARAVAN_MAKE, CUSTOM_FIELD_CF_QUALTRICS_COMMENTS, CUSTOM_FIELD_CF_QUALTRICS_BOOKED_GRADE, CUSTOM_FIELD_CF_QUALTRICS_BOOKING_NIGHTS, CUSTOM_FIELD_CF_QUALTRICS_BOOKING_PRICE, CUSTOM_FIELD_CF_QUALTRICS_BOOKING_REF, CUSTOM_FIELD_CF_QUALTRICS_CHILDREN_MAKEUP, CUSTOM_FIELD_CF_QUALTRICS_NPS, CUSTOM_FIELD_CF_HOLIDAY_BOOKED, CUSTOM_FIELD_CF_HO_CLOSE_DATE, CUSTOM_FIELD_CF_HO_COMMENTS, CUSTOM_FIELD_CF_HO_CONTACT_CHANNEL, CUSTOM_FIELD_CF_BOOKING_REFERENCE, CUSTOM_FIELD_CF_HOLIDAY_ARRIVAL_DATE, CUSTOM_FIELD_CF_HO_CANCELLED_REASON, CUSTOM_FIELD_CF_IS_DUPLICATED, CUSTOM_FIELD_CF_OTHER_PARKS_VISITED, CUSTOM_FIELD_CF_VISITING_OTHER_PARKS, CUSTOM_FIELD_CF_QUOTE_OUTCOME_DETAIL, CUSTOM_FIELD_CF_APPOINTMENT_OUTCOME_DETAIL, CUSTOM_FIELD_CF_DATE_OF_QUOTE, CUSTOM_FIELD_CF_8X8ENDTIME, CUSTOM_FIELD_CF_8X8CALLTERMINATIONSTATE, CUSTOM_FIELD_CF_8X8CALLRECORDINGURL, CUSTOM_FIELD_CF_8X8CALLDIRECTION, CUSTOM_FIELD_CF_8X8STARTTIME, CUSTOM_FIELD_CF_8X8AGENT, CUSTOM_FIELD_CF_8X8CALLDURATION, CUSTOM_FIELD_CF_8X8CHANNEL, CUSTOM_FIELD_CF_PARK_FACILITIES, CUSTOM_FIELD_CF_NEARBY_ACTIVITIES, CUSTOM_FIELD_CF_OWNERSHIP_EXPERIENCE, CUSTOM_FIELD_CF_PITCH_PREFERENCE, CUSTOM_FIELD_CF_DRIVE_TIME, CUSTOM_FIELD_CF_PITCH_PREF, CUSTOM_FIELD_CF_QUOTE_FOLLOW_UP_DETAIL, CUSTOM_FIELD_CF_QUOTE_FOLLOW_UP_NOTES, CUSTOM_FIELD_CF_DM_TEST, CUSTOM_FIELD_CF_APPT_OUTCOME_NOTES, CUSTOM_FIELD_CF_TEST_ACCOUNT, CUSTOM_FIELD_CF_DID_THE_CUSTOMER_ASK_ABOUT_SITE_FEES, CUSTOM_FIELD_CF_APPT_OUTCOME_FEEDBACK, CUSTOM_FIELD_CF_TPS, CUSTOM_FIELD_CF_ENQUIRY_KIND, CUSTOM_FIELD_CF_PX_SUITABLE_TO_LET_DATE_CHANGE, CUSTOM_FIELD_CF_PX_CURRENT_EST_VALUE, CUSTOM_FIELD_CF_PX_YEARS_OF_OWNERSHIP, CUSTOM_FIELD_CF_PX_PITCH_GRADE, CUSTOM_FIELD_CF_PX_MAKE, CUSTOM_FIELD_CF_PX_VAN_GRADE, CUSTOM_FIELD_CF_PX_VALUE, CUSTOM_FIELD_CF_PX_VAN_AGE, CUSTOM_FIELD_CF_PX_CURRENT_PITCH_SITE_FEES, CUSTOM_FIELD_CF_CSN_NUMBER, CUSTOM_FIELD_CF_PX_LETTING_STATUS, CUSTOM_FIELD_CF_PARK_CODE_FORMULA, CUSTOM_FIELD_CF_OWNER_IDPARK_CODE, CUSTOM_FIELD_CF_SALE_MANAGER, CUSTOM_FIELD_CF_SOURCE_CODE, CUSTOM_FIELD_CF_SOURCE_SUBCODE, CUSTOM_FIELD_CF_ORIGINAL_SALES_OWNER, CUSTOM_FIELD_CF_FIRST_SALES_OWNER, CUSTOM_FIELD_CF_SMS_APPT_CONFIRMED, CUSTOM_FIELD_CF_SMS, CUSTOM_FIELD_CF_CONTACT_CENTRE_INTENT_SCORE, CUSTOM_FIELD_CF_SMS_SENT, CUSTOM_FIELD_CF_APPOINTMENT_TRAVEL_ARRANGEMENTS, CUSTOM_FIELD_CF_CAR_REG, CUSTOM_FIELD_CF_REENGAGEMENT_ONLINE, CUSTOM_FIELD_CF_REENGAGEMENT_LOST_REASON, CUSTOM_FIELD_CF_SMS_SENT_DATE, CUSTOM_FIELD_CF_DEAL_CREATED_VIA_SMS, CUSTOM_FIELD_CF_TM_RECONTACT_PHONE, CUSTOM_FIELD_CF_TM_RECONTACT_DATE, CUSTOM_FIELD_CF_TMFCNOTES, CUSTOM_FIELD_CF_ARRIVING_VIA, CUSTOM_FIELD_CF_CAR_REG_ID
FROM HAVEN_RAW.FRESHSALES.DEALS;

create or replace view ANPR_DEVICE(
	ID,
	PARK_CODE,
	MAC_ADDRESS,
	CREATED_AT,
	UPDATED_AT,
	FILE_MODIFICATION_TIME,
	DELETED_DATE,
	IS_DELETED
) as SELECT "ID", "PARK_CODE", "MAC_ADDRESS", "CREATED_AT", "UPDATED_AT", "FILE_MODIFICATION_TIME", "END_DATE", DECODE(END_DATE, NULL, FALSE, TRUE) 
FROM "HAVEN_RAW"."DIG_ARRIVALS_ETLEAP"."ANPR_DEVICE";

create or replace view haven_base.dig_arrivals.ANPR_DEVICE                                                                                            
( ID, PARK_CODE, MAC_ADDRESS, CREATED_AT, UPDATED_AT, NAME, DIRECTION, ENABLED, DELETED_DATE, is_deleted )                                            
AS SELECT ID, PARK_CODE, MAC_ADDRESS, CREATED_AT, UPDATED_AT, NAME, DIRECTION, ENABLED, END_DATE, DECODE(END_DATE, NULL, FALSE, TRUE)  
FROM HAVEN_RAW.DIG_ARRIVALS_ETLEAP.ANPR_DEVICE;                                                                                                       
                                                                                                                                       
-- 06/01/2026

USE ROLE dba;

use SCHEMA haven_base.plot;

CREATE VIEW haven_base.plot.PARK_LETTING_PACKAGES_PEAK_TYPES_AUDIT
( PARK_LETTING_PACKAGES_PEAK_TYPES_AUDIT_ID, CHANGE_DT, CHANGE_TYPE, PARK_LETTING_PACKAGES_PEAK_TYPE_ID, PARK_LETTING_PACKAGE_ID, LETTING_PEAK_TYPE_ENUM, LETTING_CONTRACT_TYPE_ENUM, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT )
AS SELECT PARK_LETTING_PACKAGES_PEAK_TYPES_AUDIT_ID, CHANGE_DT, CHANGE_TYPE, PARK_LETTING_PACKAGES_PEAK_TYPE_ID, PARK_LETTING_PACKAGE_ID, LETTING_PEAK_TYPE_ENUM, LETTING_CONTRACT_TYPE_ENUM, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT
FROM HAVEN_RAW.PLOT_RDS_TEST.PARK_LETTING_PACKAGES_PEAK_TYPES_AUDIT;

-- 19/01/2026

use ROLE dba;

SELECT get_ddl('view', 'haven_base.DIG_PLAYPASS.PURCHASE' );

CREATE OR replace VIEW haven_base.DIG_PLAYPASS.PURCHASE
( ID, SHORTCODE, PAYMENTID, ISREEDEMED, ISREFUNDED, CREATEDAT, UPDATEDAT, ARRIVALDATE, PARKCODE, LEADGUESTNAME, REFUNDEDAT, ADULT, CHILD, CURRENCY, GROSSPRICE, NETPRICE, VATRATE, 
DEPARTUREDATE, TYPE, EMAIL, PARKNAME, INFANT, DELETEDAT )
AS SELECT ID, SHORTCODE, PAYMENTID, ISREEDEMED, ISREFUNDED, CREATEDAT, UPDATEDAT, ARRIVALDATE, PARKCODE, LEADGUESTNAME, REFUNDEDAT, ADULT, CHILD, CURRENCY, GROSSPRICE, NETPRICE, VATRATE, 
DEPARTUREDATE, "TYPE", EMAIL, PARKNAME, INFANT, DELETEDAT
FROM HAVEN_RAW.DIG_PLAYPASS.PURCHASE;

SELECT * FROM haven_base.DIG_PLAYPASS.PURCHASE
LIMIT 20;
                                       
create or replace view PURCHASE(
	ID,
	SHORTCODE,
	PAYMENTID,
	ISREEDEMED,
	ISREFUNDED,
	CREATEDAT,
	UPDATEDAT,
	ARRIVALDATE,
	PARKCODE,
	LEADGUESTNAME,
	REFUNDEDAT,
	ADULT,
	CHILD,
	CURRENCY,
	GROSSPRICE,
	NETPRICE,
	VATRATE,
	DEPARTUREDATE,
	TYPE,
	EMAIL,
	PARKNAME,
	REFERENCEID,
	INFANT
) COMMENT='HAVEN_BASE.DIG_PLAYPASS.PURCHASE stores detailed information on each playpass purchase, including departure date, ID, shortcode, number of adults and children, net and gross prices, currency, park name, and payment ID. It also tracks ISREDEemed and ISREFUNDED statuses, as well as relevant timestamps and park codes. No direct references to related tables are present in the schema.'
 as SELECT ID, SHORTCODE, PAYMENTID, ISREEDEMED, ISREFUNDED, CREATEDAT, UPDATEDAT, ARRIVALDATE, PARKCODE, LEADGUESTNAME, REFUNDEDAT, ADULT, CHILD, CURRENCY, GROSSPRICE, NETPRICE, VATRATE, DEPARTUREDATE, "TYPE", EMAIL, PARKNAME, REFERENCEID, INFANT
FROM HAVEN_RAW.DIG_PLAYPASS.PURCHASE;