use ROLE haven_etleap_dataload;

use SCHEMA haven_raw.prime;



use ROLE dba;

use SCHEMA haven_base.prime;

show views;

CREATE VIEW haven_base.prime.PRIME_RESPONSE
( DOCID, INCIDENT_DATE, INCIDENT_TIME, REPORT_TYPE, RIDDOR, "TYPE", CAUSE, REPORTED_DATE, "Delay_(days)", SITE, REGION, AREA, LOCATION, SUB_LOCATION, VENUE, DETAILS, "Comment_History_(last_entry_shown)", CREATED_BY, REF_NO, "Photos_Attached?", DOC_STATUS, STAFF_TYPE, INJURY_SUB_CAUSE, "Business_Related?", RISK_RATING, AFFECTED_BY_INCIDENT, PERSON_TYPE, PERSON_NAME, PERSON_CONTACT_DETAILS, LOCATION_CHECKED, CHECKED_BY, CONTRIBUTORY_FACTORS, PHOTOS_TAKEN, PHOTOS_UPLOADED, CHECKS_IN_PLACE, WHICH_CHECKS, CHECKS_UPLOADED, MEASUREMENTS, MEASUREMENTS_UPLOADED, LIGHTING, LIGHTING_UPLOADED, RISK_ASSESSMENT, RA_UPLOADED, RA_REVIEWED, REVIEWED_RA_UPLOADED, RECORDED_NO_EVIDENCE, BODY_CAM_FOOTAGE, STATEMENTS_REQUIRED, STATEMENTS_UPLOADED, INFORMATION_CASCADED, ACCOM_ADDRESS, AGE, "Evicted?", "Safeguarding_Concerns?", SAFEGUARDING_COMMENTS, "Was_any_physical_intervention_used_by_team_members?", "Security_Officer(s)_involved", "SIA_badge_number(s)", "Individual_statement(s)_completed_by_security_officers", "Are_the_statement(s)_attached_to_this_Prime_report", "Were_any_of_the_security_officers_assaulted_by_the_subject?", PRIMARY_CONDUCT_OF_THE_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION, PRIMARY_IMPACT_FACTOR_OF_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION, PRIMARY_REASON_PHYSICAL_INTERVENTION_WAS_USED, "How_many_team_were_involved_in_the_physical_intervention?", "How_many_were_SIA_Door_Supervisor_trained?", PRIMARY_PHYSICAL_INTERVENTION_TACTIC_USED, SECONDARY_PHYSICAL_INTERVENTION_TACTIC_USED, PRIMARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON, SECONDARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON )
AS SELECT DOCID, INCIDENT_DATE, INCIDENT_TIME, REPORT_TYPE, RIDDOR, "TYPE", CAUSE, REPORTED_DATE, "Delay_(days)", SITE, REGION, AREA, LOCATION, SUB_LOCATION, VENUE, DETAILS, "Comment_History_(last_entry_shown)", CREATED_BY, REF_NO, "Photos_Attached?", DOC_STATUS, STAFF_TYPE, INJURY_SUB_CAUSE, "Business_Related?", RISK_RATING, AFFECTED_BY_INCIDENT, PERSON_TYPE, PERSON_NAME, PERSON_CONTACT_DETAILS, LOCATION_CHECKED, CHECKED_BY, CONTRIBUTORY_FACTORS, PHOTOS_TAKEN, PHOTOS_UPLOADED, CHECKS_IN_PLACE, WHICH_CHECKS, CHECKS_UPLOADED, MEASUREMENTS, MEASUREMENTS_UPLOADED, LIGHTING, LIGHTING_UPLOADED, RISK_ASSESSMENT, RA_UPLOADED, RA_REVIEWED, REVIEWED_RA_UPLOADED, RECORDED_NO_EVIDENCE, BODY_CAM_FOOTAGE, STATEMENTS_REQUIRED, STATEMENTS_UPLOADED, INFORMATION_CASCADED, ACCOM_ADDRESS, AGE, "Evicted?", "Safeguarding_Concerns?", SAFEGUARDING_COMMENTS, "Was_any_physical_intervention_used_by_team_members?", "Security_Officer(s)_involved", "SIA_badge_number(s)", "Individual_statement(s)_completed_by_security_officers", "Are_the_statement(s)_attached_to_this_Prime_report", "Were_any_of_the_security_officers_assaulted_by_the_subject?", PRIMARY_CONDUCT_OF_THE_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION, PRIMARY_IMPACT_FACTOR_OF_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION, PRIMARY_REASON_PHYSICAL_INTERVENTION_WAS_USED, "How_many_team_were_involved_in_the_physical_intervention?", "How_many_were_SIA_Door_Supervisor_trained?", PRIMARY_PHYSICAL_INTERVENTION_TACTIC_USED, SECONDARY_PHYSICAL_INTERVENTION_TACTIC_USED, PRIMARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON, SECONDARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON
FROM HAVEN_RAW.PRIME.PRIME_RESPONSE;


SELECT * FROM prime_response LIMIT 50;

-- 01/09/2025

use ROLE dba;

use SCHEMA training.training;

-- HAVEN_RAW.PRIME.PRIME_RESPONSE definition

SELECT * FROM prime_response limit 20;

create or replace TABLE training.training.PRIME_RESPONSE (
	DOCID VARCHAR(),
	INCIDENT_DATE date,
	INCIDENT_TIME varchar(),
	REPORT_TYPE VARCHAR(),
	RIDDOR VARCHAR(),
	TYPE VARCHAR(),
	CAUSE VARCHAR(),
	REPORTED_DATE date,
	"Delay_(days)" integer,
	SITE VARCHAR(),
	REGION VARCHAR(),
	AREA VARCHAR(),
	LOCATION VARCHAR(),
	SUB_LOCATION VARCHAR(),
	VENUE VARCHAR(),
	DETAILS VARCHAR(),
	"Comment_History_(last_entry_shown)" VARCHAR(),
	CREATED_BY VARCHAR(),
	REF_NO VARCHAR(),
	"Photos_Attached?" VARCHAR(),
	DOC_STATUS VARCHAR(),
	STAFF_TYPE VARCHAR(),
	INJURY_SUB_CAUSE VARCHAR(),
	"Business_Related?" VARCHAR(),
	RISK_RATING VARCHAR(),
	AFFECTED_BY_INCIDENT VARCHAR(),
	PERSON_TYPE VARCHAR(),
	PERSON_NAME VARCHAR(),
	PERSON_CONTACT_DETAILS VARCHAR(),
	LOCATION_CHECKED VARCHAR(),
	CHECKED_BY VARCHAR(),
	CONTRIBUTORY_FACTORS VARCHAR(),
	PHOTOS_TAKEN VARCHAR(),
	PHOTOS_UPLOADED VARCHAR(),
	CHECKS_IN_PLACE VARCHAR(),
	WHICH_CHECKS VARCHAR(),
	CHECKS_UPLOADED VARCHAR(),
	MEASUREMENTS VARCHAR(),
	MEASUREMENTS_UPLOADED VARCHAR(),
	LIGHTING VARCHAR(),
	LIGHTING_UPLOADED VARCHAR(),
	RISK_ASSESSMENT VARCHAR(),
	RA_UPLOADED VARCHAR(),
	RA_REVIEWED VARCHAR(),
	REVIEWED_RA_UPLOADED VARCHAR(),
	RECORDED_NO_EVIDENCE VARCHAR(),
	BODY_CAM_FOOTAGE VARCHAR(),
	STATEMENTS_REQUIRED VARCHAR(),
	STATEMENTS_UPLOADED VARCHAR(),
	INFORMATION_CASCADED VARCHAR(),
	ACCOM_ADDRESS VARCHAR(),
	AGE VARCHAR(),
	"Evicted?" VARCHAR(),
	"Safeguarding_Concerns?" VARCHAR(),
	SAFEGUARDING_COMMENTS VARCHAR(),
	"Was_any_physical_intervention_used_by_team_members?" VARCHAR(),
	"Security_Officer(s)_involved" VARCHAR(),
	"SIA_badge_number(s)" VARCHAR(),
	"Individual_statement(s)_completed_by_security_officers" VARCHAR(),
	"Are_the_statement(s)_attached_to_this_Prime_report" VARCHAR(),
	"Were_any_of_the_security_officers_assaulted_by_the_subject?" VARCHAR(),
	PRIMARY_CONDUCT_OF_THE_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION VARCHAR(),
	PRIMARY_IMPACT_FACTOR_OF_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION VARCHAR(),
	PRIMARY_REASON_PHYSICAL_INTERVENTION_WAS_USED VARCHAR(),
	"How_many_team_were_involved_in_the_physical_intervention?" VARCHAR(),
	"How_many_were_SIA_Door_Supervisor_trained?" VARCHAR(),
	PRIMARY_PHYSICAL_INTERVENTION_TACTIC_USED VARCHAR(),
	SECONDARY_PHYSICAL_INTERVENTION_TACTIC_USED VARCHAR(),
	PRIMARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON VARCHAR(),
	SECONDARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON VARCHAR()
);


copy into prime_response from @%prime_response/
file_format = 
(type = CSV, 
compression = gzip, 
multi_line = true, 
field_optionally_enclosed_by = '"', 
field_delimiter = ',', 
skip_header = 1,
date_format = 'DD-MM-YYYY')
validation_mode = return_all_errors
;

-- 05/11/2025

use ROLE dba;

use SCHEMA haven_base.prime;
 
create or replace view PRIME_RESPONSE(
    FILE_MODIFICATION_TIME,
	DOCID,
	INCIDENT_DATE,
	INCIDENT_TIME,
	REPORT_TYPE,
	RIDDOR,
	TYPE,
	CAUSE,
	REPORTED_DATE,
	DELAY_DAYS,
	SITE,
	REGION,
	AREA,
	LOCATION,
	SUB_LOCATION,
	VENUE,
	DETAILS,
	COMMENT_HISTORY_LAST_ENTRY_SHOWN,
	CREATED_BY,
	REF_NO,
	PHOTOS_ATTACHED,
	DOC_STATUS,
	STAFF_TYPE,
	INJURY_SUB_CAUSE,
	BUSINESS_RELATED,
	RISK_RATING,
	AFFECTED_BY_INCIDENT,
	PERSON_TYPE,
	PERSON_NAME,
	PERSON_CONTACT_DETAILS,
	LOCATION_CHECKED,
	CHECKED_BY,
	CONTRIBUTORY_FACTORS,
	PHOTOS_TAKEN,
	PHOTOS_UPLOADED,
	CHECKS_IN_PLACE,
	WHICH_CHECKS,
	CHECKS_UPLOADED,
	MEASUREMENTS,
	MEASUREMENTS_UPLOADED,
	LIGHTING,
	LIGHTING_UPLOADED,
	RISK_ASSESSMENT,
	RA_UPLOADED,
	RA_REVIEWED,
	REVIEWED_RA_UPLOADED,
	RECORDED_NO_EVIDENCE,
	BODY_CAM_FOOTAGE,
	STATEMENTS_REQUIRED,
	STATEMENTS_UPLOADED,
	INFORMATION_CASCADED,
	ACCOM_ADDRESS,
	AGE,
	EVICTED,
	SAFEGUARDING_CONCERNS,
	SAFEGUARDING_COMMENTS,
	PHYSICAL_INTERVENTION_BY_TEAM,
	SECURITY_OFFICERS_INVOLVED,
	SIA_BADGE_NUMBERS,
	STATEMENTS_COMPLETED_SECURITY_OFFICERS,
	STATEMENTS_ATTACHED,
	SECURITY_OFFICERS_ASSAULTED,
	PRIMARY_CONDUCT_OF_THE_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION,
	PRIMARY_IMPACT_FACTOR_OF_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION,
	PRIMARY_REASON_PHYSICAL_INTERVENTION_WAS_USED,
	TEAM_INVOLVED_TOTAL,
	SIA_DOOR_SUPERVISOR_TRAINED_TOTAL,
	PRIMARY_PHYSICAL_INTERVENTION_TACTIC_USED,
	SECONDARY_PHYSICAL_INTERVENTION_TACTIC_USED,
	PRIMARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON,
	SECONDARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON
) as
select 
FILE_MODIFICATION_TIME
,DOCID
,TO_DATE(incident_date, 'DD-MM-YYYY') as INCIDENT_DATE
,TO_TIME(case when incident_time =':' then '00:00' else incident_time end, 'HH:mi') as INCIDENT_TIME
,REPORT_TYPE
,RIDDOR
,TYPE
,CAUSE
,TO_DATE(REPORTED_DATE, 'DD-MM-YYYY') as REPORTED_DATE
,"Delay_(days)"::int as "Delay_(days)"
,SITE
,REGION
,AREA
,LOCATION
,SUB_LOCATION
,VENUE
,DETAILS
,"Comment_History_(last_entry_shown)"
,CREATED_BY
,REF_NO
,"Photos_Attached?"::boolean as "Photos_Attached?"
,DOC_STATUS
,STAFF_TYPE
,INJURY_SUB_CAUSE
,"Business_Related?"
,RISK_RATING
,AFFECTED_BY_INCIDENT
,PERSON_TYPE
,PERSON_NAME
,PERSON_CONTACT_DETAILS
,LOCATION_CHECKED
,CHECKED_BY
,CONTRIBUTORY_FACTORS
,PHOTOS_TAKEN
,PHOTOS_UPLOADED
,CHECKS_IN_PLACE
,WHICH_CHECKS
,CHECKS_UPLOADED
,MEASUREMENTS
,MEASUREMENTS_UPLOADED
,LIGHTING
,LIGHTING_UPLOADED
,RISK_ASSESSMENT
,RA_UPLOADED
,RA_REVIEWED
,REVIEWED_RA_UPLOADED
,RECORDED_NO_EVIDENCE
,BODY_CAM_FOOTAGE
,STATEMENTS_REQUIRED
,STATEMENTS_UPLOADED
,INFORMATION_CASCADED
,ACCOM_ADDRESS
,AGE
,"Evicted?"
,"Safeguarding_Concerns?"
,SAFEGUARDING_COMMENTS
,"Was_any_physical_intervention_used_by_team_members?"
,"Security_Officer(s)_involved"
,"SIA_badge_number(s)"
,"Individual_statement(s)_completed_by_security_officers"
,"Are_the_statement(s)_attached_to_this_Prime_report"
,"Were_any_of_the_security_officers_assaulted_by_the_subject?"
,PRIMARY_CONDUCT_OF_THE_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION
,PRIMARY_IMPACT_FACTOR_OF_INDIVIDUAL_SUBJECT_TO_PHYSICAL_INTERVENTION
,PRIMARY_REASON_PHYSICAL_INTERVENTION_WAS_USED
,"How_many_team_were_involved_in_the_physical_intervention?"
,"How_many_were_SIA_Door_Supervisor_trained?"
,PRIMARY_PHYSICAL_INTERVENTION_TACTIC_USED
,SECONDARY_PHYSICAL_INTERVENTION_TACTIC_USED
,PRIMARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON
,SECONDARY_PART_OF_THE_BODY_PHYSICAL_INTERVENTION_WAS_USED_ON
from HAVEN_RAW.PRIME.PRIME_RESPONSE;

 
