use ROLE sysadmin;

CREATE WAREHOUSE haven_dbt_transform_pricer_warehouse_xsmall WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE haven_dbt_transform_pricer_warehouse_medium WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

use ROLE useradmin;

CREATE ROLE haven_dbt_transform_pricer;

create role _haven_dbt_transform_pricer_warehouse_xsmall__operator;
create role _haven_dbt_transform_pricer_warehouse_xsmall__USAGE;

create role _haven_dbt_transform_pricer_warehouse_MEDIUM__operator;
create role _haven_dbt_transform_pricer_warehouse_MEDIUM__USAGE;

use ROLE securityadmin;

GRANT usage, monitor on warehouse haven_dbt_transform_pricer_warehouse_xsmall TO ROLE _haven_dbt_transform_pricer_warehouse_xsmall__USAGE;
GRANT ROLE _haven_dbt_transform_pricer_warehouse_xsmall__USAGE TO ROLE _haven_dbt_transform_pricer_warehouse_xsmall__operator;
GRANT operate, MODIFY ON warehouse haven_dbt_transform_pricer_warehouse_xsmall TO ROLE _haven_dbt_transform_pricer_warehouse_xsmall__operator;

GRANT usage, monitor on warehouse haven_dbt_transform_pricer_warehouse_medium TO ROLE _haven_dbt_transform_pricer_warehouse_medium__USAGE;
GRANT ROLE _haven_dbt_transform_pricer_warehouse_medium__USAGE TO ROLE _haven_dbt_transform_pricer_warehouse_medium__operator;
GRANT operate, MODIFY ON warehouse haven_dbt_transform_pricer_warehouse_medium TO ROLE _haven_dbt_transform_pricer_warehouse_medium__operator;

GRANT ROLE _haven_dbt_transform_pricer_warehouse_XSMALL__USAGE TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _haven_dbt_transform_pricer_warehouse_medium__USAGE TO ROLE haven_dbt_transform_pricer;


GRANT ROLE _BOURNE_BASE__AZTECACTIVITYMANAGEMENT__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__AZTEC__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__BRAINTREE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__CONCUR__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__COUPA__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__DREAM__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__FINANCIAL_CUBE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__KMSREPORTING__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__QUALTRICS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_BASE__ZBSDATA__READER TO ROLE haven_dbt_transform_pricer;

GRANT ROLE _HAVEN_BASE__ACTIVITIES__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ADTHENA__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__AMPLITUDE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ARCADES__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__AWIN__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__AZTECACTIVITYMANAGEMENT_COMPLEX__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__AZTEC_COMPLEX__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__AZTEC_RETAIL__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__BIGQUERY__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__BLAPI_HID__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__BLOOMREACH_INTEGRATION__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__BLOOMREACH__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__BLUEYONDER__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__BRAINTREE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__COMMON__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__COMPETITOR__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__CONSENT_AND_PREFERENCE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__COUPA__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__CYHH__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_AAC_ONPARKWIFI__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_ACCEPTANCE_OF_RISK__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_ACTIVITIES__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_ARRIVALS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_BOOKINGS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_CAPACITY__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_FB_EAGLEEYE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_FB_ENTERTAINMENT__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_FB_TABLE_BOOKING__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_OWNERSHIP_OWNERS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_OWNERS_ARRIVALS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_PARK_AREAS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_PAYMENTS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_PLAYPASS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_PRICING__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_TEAM_CARD__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_TEAM_COMMS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DIG_VENUE_DISRUPTION__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DREAM_EVERGREEN__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DREAM_ROCKLEYBOATPARK__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__DREAM__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ECLIENT__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ENERGY_METERS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__EQUALISER__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ERPX__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__EXPERIAN__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__FACEBOOK_CARAVAN_SALES_LEADS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__FACEBOOK_CARAVAN_SALES__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__FACEBOOK_HOLIDAY_SALES__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__FACEBOOK__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__FINANCIAL_CUBE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__FREEDOMPAY__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__FRESHSALES__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__GOOGLE_INTEGRATION__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__HIT_ADMIN__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ICLEAN__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__IDENTITY__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__JDAADMIN__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__KMSREPORTING_COMPLEX__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__MARINER__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__MATTERPORT_IMAGES__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__PLAYSAFE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__PLOT_ARCHIVE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__PLOT_DREAM__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__PLOT__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__PRICER__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__QUALTRICS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__SAGACITY__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__SAS_COMMON__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__SAS_SCV__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__SEAWARE__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__SKI_LIFT__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__TIKTOK_ADS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__WETHERSPOONS__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__WORKFORCE_SAM__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ZBSDATA_COMPLEX__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ZBSDATA_RETAIL__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_BASE__ZONAL__READER TO ROLE haven_dbt_transform_pricer;

GRANT ROLE _HAVEN_MASTER__COMMON__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_MASTER__NOTEBOOK_SANDBOX__READER TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_MASTER__REVENUE_MANAGEMENT_STORAGE__READER TO ROLE haven_dbt_transform_pricer;

GRANT ROLE _BOURNE_STORE__FINANCE_SHARED_SERVICES__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_STORE__KMSREPORTING__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_STORE__SAS_COMMON__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_STORE__SAS_SCV__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_STORE__ZBSDATA__CREATOR TO ROLE haven_dbt_transform_pricer;

GRANT ROLE _HAVEN_PIPELINE__BLOOMREACH__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__BLUEYONDER__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__CRM_DATA__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__ESSENCEMEDIA__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__FINANCE_CUBE_ERPX__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__FRESHSALES__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__PRICING_TACTICAL_PROCESS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__PX0007_PITCH_PERFECT__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__RETAIL_SALES__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__SAGACITY__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__SURVEY__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__SYSTEM_FUNCTIONS__CREATOR TO ROLE haven_dbt_transform_pricer;

GRANT ROLE _HAVEN_STAGING__ADHOC__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STAGING__DMS_STAGING__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STAGING__REVENUE_MANAGEMENT_OUTPUT__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STAGING__REVENUE_MANAGEMENT_STAGING__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STAGING__RM_STAGING__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STAGING__TROOPER2__CREATOR TO ROLE haven_dbt_transform_pricer;

GRANT ROLE _HAVEN_STORE__ACTIVITIES__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__ALIGN_ALYTICS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__ARRIVAL__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__AVAILABILITY__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__BUDGET_DATA__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__CARAVANS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__CARAVAN_SALES__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__COMMERCIAL__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__COMMON_RESTRICTED__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__COMMON__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__COMPETITOR__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__CONSENT_AND_PREFERENCE__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__COUPA_CUBE__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__DIGITAL__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__FINANCE_CUBE_ERPX__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__FINANCE_SHARED_SERVICES__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__FINANCE_UAT__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__FINANCIAL_CUBE__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__HAVEN_ACCOUNTANTS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__HAVEN_STAGING__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__HOLIDAYS_UAT__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__HOLIDAY__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__IDENTITY__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__INTEGRATION__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__JDAADMIN__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__JDAPREP__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__KMSREPORTING_COMPLEX__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__KPMG_UAT__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__KPMG_VIEWS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__MA_MART__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__OCANDC__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PARK_OPERATIONS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PAYMENTS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PERFORMANCE_MARKETING__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PITCH_PERFECT__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PLAYPASS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PLOTREPRS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PLOT_REPORTING__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PRICER_DECISION_MATRIX__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PRICER_FORECAST__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PRICER__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PROCUREMENT__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__PROSPECTS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__RETAIL_FRANCHISE__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__RETAIL__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__REVENUE_MANAGEMENT_REPORTING__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__REVENUE_MANAGEMENT__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__SALES_PLANNER__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__SASMART__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__SAS_SCV__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__SEAWARE__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__SURVEY__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__TROOPER2__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__TROOPER__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__TRPREPRS__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__WORKFORCE__CREATOR TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STORE__ZONAL_STOCK_REPORTS__CREATOR TO ROLE haven_dbt_transform_pricer;

GRANT ROLE _HAVEN_STORE__SCHEMA TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_STAGING__SCHEMA TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _HAVEN_PIPELINE__SCHEMA TO ROLE haven_dbt_transform_pricer;
GRANT ROLE _BOURNE_STORE__SCHEMA TO ROLE haven_dbt_transform_pricer;

GRANT ROLE haven_dbt_transform_pricer TO USER HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE haven_dbt_transform_pricer TO USER HAVEN_DBT_TRANSFORM;
