
use ROLE dba;

use SCHEMA haven_base.dig_fb_entertainment;

SHOW VIEWS;

SELECT * FROM EVENT LIMIT 10;
--SELECT * FROM EVENT_SESSION LIMIT 10;
--SELECT * FROM MIGRATIONS LIMIT 10;
SELECT * FROM PARK LIMIT 10;
SELECT * FROM SCHEDULE LIMIT 10;
SELECT * FROM SCHEDULE_SESSION LIMIT 10;
SELECT * FROM SESSION LIMIT 10;
--SELECT * FROM SESSION_TIME LIMIT 10;
SELECT * FROM VENUE LIMIT 10;

DROP VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.MIGRATIONS;
DROP VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.EVENT_SESSION;
DROP VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.SESSION_TIME;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.EVENT
( ID, DOC_DB_ID, NAME, DESCRIPTION, IMAGE_URL, FEATURED_IMAGE_URL, ACTIVITY_ID, IS_NAME_CUSTOMISABLE, IS_DELETED )
AS SELECT ID, DOC_DB_ID, NAME, DESCRIPTION, IMAGE_URL, FEATURED_IMAGE_URL, ACTIVITY_ID, IS_NAME_CUSTOMISABLE, IS_DELETED
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT.EVENT;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.FAVOURITE
( ID, DOC_DB_ID, FAVOURITER_ID, SCHEDULE_SESSION_ID )
AS SELECT ID, DOC_DB_ID, FAVOURITER_ID, SCHEDULE_SESSION_ID
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT.FAVOURITE;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.PARK
( ID, DOC_DB_ID, NAME, CODE, TYPE, REGION, MIN_DAILY_EVENT_COUNT, MIN_DAILY_SESSION_COUNT )
AS SELECT ID, DOC_DB_ID, NAME, CODE, "TYPE", REGION, MIN_DAILY_EVENT_COUNT, MIN_DAILY_SESSION_COUNT
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT.PARK;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.SCHEDULE
( ID, DOC_DB_ID, DATE, PARK_CODE, COMPLETED )
AS SELECT ID, DOC_DB_ID, "DATE", PARK_CODE, COMPLETED
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT.SCHEDULE;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.SCHEDULE_EVENT
( ID, EVENT_ID, SORT_ORDER, SCHEDULE_SESSION_ID, UNMISSABLE, IS_DOUBLE_THE_FUN, CUSTOM_NAME )
AS SELECT ID, EVENT_ID, SORT_ORDER, SCHEDULE_SESSION_ID, UNMISSABLE, IS_DOUBLE_THE_FUN, CUSTOM_NAME
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT.SCHEDULE_EVENT;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.SCHEDULE_SESSION
( ID, SCHEDULE_ID, SESSION_ID, "START", END, VENUE_ID )
AS SELECT ID, SCHEDULE_ID, SESSION_ID, "start", "END", VENUE_ID
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT.SCHEDULE_SESSION;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.SESSION
( ID, DOC_DB_ID, NAME, DESCRIPTION, IMAGE_URL, IS_DELETED )
AS SELECT ID, DOC_DB_ID, NAME, DESCRIPTION, IMAGE_URL, IS_DELETED
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT."SESSION";

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.VENUE
( ID, DOC_DB_ID, NAME, PARK_ID, IS_DELETED )
AS SELECT ID, DOC_DB_ID, NAME, PARK_ID, IS_DELETED
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT.VENUE;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_FB_ENTERTAINMENT.WEEKLY_SCHEDULE_INFO
( ID, DATE, PARK_CODE, DAYTIME_HIGHLIGHTED_EVENT_ID, EVENING_HIGHLIGHTED_EVENT_ID )
AS SELECT ID, "DATE", PARK_CODE, DAYTIME_HIGHLIGHTED_EVENT_ID, EVENING_HIGHLIGHTED_EVENT_ID
FROM HAVEN_RAW.DIG_FB_ENTERTAINMENT.WEEKLY_SCHEDULE_INFO;

-- 08/04/2025

use ROLE dba;

use SCHEMA haven_base.dig_fb_entertainment;

show views;

SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.EVENT LIMIT 10;
SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.FAVOURITE LIMIT 10;
SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.PARK LIMIT 10;
SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.SCHEDULE LIMIT 10;
SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.SCHEDULE_EVENT LIMIT 10;
SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.SCHEDULE_SESSION LIMIT 10;
SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.SESSION LIMIT 10;
SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.VENUE LIMIT 10;
SELECT * FROM HAVEN_BASE.DIG_FB_ENTERTAINMENT.WEEKLY_SCHEDULE_INFO LIMIT 10;

