use ROLE dba;
use SCHEMA HAVEN_STORE.HAVEN_ACCOUNTANTS;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.CARAVAN_SALES_DETAIL source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.CARAVAN_SALES_DETAIL(
	PARK_CODE,
	ACCOUNT_NO,
	CSI_NO,
	VAN_STOCK_NO,
	DATE_SOLD,
	SALE_TYPE_CODE,
	SALE_STATUS_CODE,
	VALIDATION_DATE,
	CANCELLATION_DATE,
	COMPLETION_DATE,
	STATYEAR,
	STATPERIOD,
	TWIN_YN,
	NEW_VAN_YN,
	PRIVATE_SALE_VALUE,
	PRIVATE_SALE_COMMISSION,
	COMMISSION_PAID_YN,
	COMMISSION_PAID_DATE,
	VAN_STOCK_NO_2,
	PEX1_BOTTOM_BOOK_VALUE,
	PEX1_DISCOUNT,
	VAN_STOCK_NO_3,
	PEX2_BOTTOM_BOOK_VALUE,
	PEX2_DISCOUNT,
	GLB_AMOUNT,
	GLB_AMOUNT_NEXT_YEAR,
	RL_AMOUNT,
	GLA_PX_AMOUNT_VAN_1,
	GLA_PX_AMOUNT_VAN_2,
	GLA_PX_AMOUNT_VAN_1_NEXT_YEAR,
	GLA_PX_AMOUNT_VAN_2_NEXT_YEAR,
	NEW_GLA_TOTAL,
	NEW_GLA_TOTAL_NEXT_YEAR,
	DUE_ON_ACCOUNT,
	SUBLET_AMOUNT,
	FINANCE_AMOUNT,
	DEPOSIT_AMOUNT,
	VOUCHER_AMOUNT,
	AMOUNT_DUE_LATER_DATE,
	AMOUNT_DUE_LATER,
	PROFIT_CONFIRMED_YN,
	PROFIT_CONFIRMED_DATE,
	SVL_PRICE_SUB_TOTAL,
	SVL_VAT_AMOUNT,
	ORIGINAL_COST,
	VALUE_STANDARD_RATED,
	VALUE_ZERO_RATED,
	GROSS_PRICE_TOTAL,
	VANVALUE,
	SUBS,
	ADDONS,
	SPDISC,
	PRODISC,
	HP_RATE_PERCENTAGE,
	MONTHLY_PAYMENTS,
	YEARS,
	FIN_COMPANY_CODE,
	FIN_CO_ACCOUNT,
	FIN_DUE_FROM,
	FIN_DUE_TO,
	SOURCE_DESC,
	CSP_DESC,
	WM_DESC,
	KEY_HANDOVER_DATE,
	EXPECTED_HANDOVER_DT,
	KEY_HANDOVER_BY,
	DESTINATION_PITCH,
	VAN_PITCH,
	VAN_BBV,
	KEY_HANDOVER_DONE_YN,
	YIELD_TEAM_OVERRIDE_YN,
	YIELD_TEAM_OVERRIDE_BY,
	NAME,
	MAKE,
	MODEL,
	LENGTH,
	WIDTH,
	NO_OF_BED_CODES,
	YEAR_MADE,
	MAKE_2,
	MODEL_2,
	LENGTH_2,
	WIDTH_2,
	NO_OF_BED_CODES_2,
	YEAR_MADE_2,
	MAKE_3,
	MODEL_3,
	LENGTH_3,
	WIDTH_3,
	NO_OF_BED_CODES_3,
	YEAR_MADE_3,
	LETTING_CAT_DESC,
	LETTING_CAT_CODE,
	VAN_GRADE_DESC,
	HO_TELEMARKETER
) as
with fn_SalesValuesBreakDown as (
select
    sale_id,
    sum( case when PRICE_TYPE_ENUM = 1  then gross_price else 0 end )                                     as vanValue,
    sum( case when PRICE_TYPE_ENUM NOT IN ( 1, 2, 3, 4, 5, 21, 22, 23 )  then gross_price else 0 end )    as addons,
    sum( case when PRICE_TYPE_ENUM = 22 then gross_price else 0 end )                                     as SpDisc,
    sum( case when PRICE_TYPE_ENUM = 23 then gross_price else 0 end )                                     as ProDisc,
    sum( case when PRICE_TYPE_ENUM IN ( 2, 3, 4, 5, 21 ) then gross_price else 0 end )                    as Subs
from haven_base.PLOT.prices
group by sale_id
),
c_LETTING_CAT_HISTORY as (
    SELECT
     *
          FROM
          haven_base.PLOT.LETTING_CAT_HISTORY LCH2
          WHERE
          LCH2.EFFECTIVE_DT <= GETDATE() AND
          LCH2.GRADE_APPROVED_YN = 1
    qualify
        row_number() over (partition by van_id order by effective_dt desc) = 1
),
c_appointment as (
    select
        ac.account_no,
        pd.prospect_detail_id,
        us.forenames || ' ' || us.surname as ho_telemarketer
    from
        haven_base.PLOT.accounts ac
    join
        haven_base.PLOT.owners ow
        on ow.owner_id = ac.owner_id
    join
        haven_base.PLOT.prospect_details pd
        on pd.owner_id = ow.owner_id and
           pd.park_id = ac.park_id
    join
        haven_base.PLOT.users us
        on us.user_id = pd.appointment_made_by_user_id
    where
        us.ho_user_yn
    )
SELECT DISTINCT
PK.PARK_CODE ,
AC.ACCOUNT_NO ,
S.CSI_NO ,
V.VAN_STOCK_NO ,
S.DATE_SOLD ,
ST.SALE_TYPE_CODE ,
SS.SALE_STATUS_CODE ,
S.VALIDATION_DATE ,
S.CANCELLATION_DATE ,
S.COMPLETION_DATE ,
WEEK_NO.StatYear ,
WEEK_NO.StatPeriod ,
S.TWIN_YN ,
S.NEW_VAN_YN ,
S.PRIVATE_SALE_VALUE ,
S.PRIVATE_SALE_COMMISSION ,
S.COMMISSION_PAID_YN ,
S.COMMISSION_PAID_DATE ,
VP1.VAN_STOCK_NO van_stock_no_2 ,
S.PEX1_BOTTOM_BOOK_VALUE ,
S.PEX1_DISCOUNT ,
VP2.VAN_STOCK_NO van_stock_no_3,
S.PEX2_BOTTOM_BOOK_VALUE ,
S.PEX2_DISCOUNT ,
S.GLB_AMOUNT ,
S.GLB_AMOUNT_NEXT_YEAR ,
S.RL_AMOUNT ,
S.GLA_PX_AMOUNT_VAN_1 ,
S.GLA_PX_AMOUNT_VAN_2 ,
S.GLA_PX_AMOUNT_VAN_1_NEXT_YEAR ,
S.GLA_PX_AMOUNT_VAN_2_NEXT_YEAR ,
S.NEW_GLA_TOTAL ,
s.NEW_GLA_TOTAL_NEXT_YEAR ,
S.DUE_ON_ACCOUNT ,
S.SUBLET_AMOUNT ,
S.FINANCE_AMOUNT ,
S.DEPOSIT_AMOUNT ,
S.VOUCHER_AMOUNT ,
S.AMOUNT_DUE_LATER_DATE ,
S.AMOUNT_DUE_LATER ,
S.PROFIT_CONFIRMED_YN ,
S.PROFIT_CONFIRMED_DATE ,
S.SVL_PRICE_SUB_TOTAL ,
S.SVL_VAT_AMOUNT ,
S.ORIGINAL_COST ,
S.VALUE_STANDARD_RATED ,
S.VALUE_ZERO_RATED ,
S.GROSS_PRICE_TOTAL ,
--MRRP.BaseRetailValue ,
--mrrp.UsedCurr ,
--mrrp.markupPercentage ,
vals.VANVALUE ,
vals.SUBS ,
vals.ADDONS ,
vals.SPDISC ,
vals.PRODISC ,
S.HP_RATE_PERCENTAGE ,
S.MONTHLY_PAYMENTS ,
S.YEARS ,
FC.FIN_COMPANY_CODE ,
S.FIN_CO_ACCOUNT ,
S.FIN_DUE_FROM ,
S.FIN_DUE_TO ,
SRC.SOURCE_DESC ,
CSP.CSP_DESC ,
WM.WM_DESC ,
S.KEY_HANDOVER_DATE ,
S.EXPECTED_HANDOVER_DT ,
S.KEY_HANDOVER_BY ,
PK.PARK_CODE || AR.AREA_CODE || Z.ZONE_CODE || PIT.PITCH_NO AS DESTINATION_PITCH,
PK.PARK_CODE || AR2.AREA_CODE || Z2.ZONE_CODE || PIT2.PITCH_NO AS VAN_PITCH,
S.VAN_BBV ,
S.KEY_HANDOVER_DONE_YN ,
S.YIELD_TEAM_OVERRIDE_YN ,
S.YIELD_TEAM_OVERRIDE_BY ,
OW.NAME,
V.MAKE ,
V.MODEL ,
V.LENGTH ,
V.WIDTH ,
V.NO_OF_BED_CODES ,
V.YEAR_MADE ,
VP1.MAKE  make_2,
VP1.MODEL  model_2,
VP1.LENGTH  length_2 ,
VP1.WIDTH  width_2,
VP1.NO_OF_BED_CODES no_of_bed_codes_2  ,
VP1.YEAR_MADE  year_made_2,
VP2.MAKE  make_3,
VP2.MODEL  model_3,
VP2.LENGTH  length_3,
VP2.WIDTH  width_3,
VP2.NO_OF_BED_CODES  no_of_bed_codes_3,
VP2.YEAR_MADE year_made_3,
LC.LETTING_CAT_DESC ,
LC.LETTING_CAT_CODE ,
vg.VAN_GRADE_DESC,
ap.ho_telemarketer
FROM haven_base.PLOT.SALES S
JOIN haven_base.PLOT.SALES_STATUSES SS ON S.SALE_STATUS_ENUM = SS.SALE_STATUS_ENUM
JOIN haven_base.PLOT.ACCOUNTS AC ON S.ACCOUNT_ID = AC.ACCOUNT_ID
LEFT JOIN haven_base.PLOT.OWNERS OW ON OW.OWNER_ID = AC.OWNER_ID
JOIN haven_base.PLOT.VANS V ON S.VAN_ID = V.VAN_ID
--OUTER APPLY plotreprs.dbo.fn_GetVanValuation(v.VAN_ID) AS MRRP
JOIN haven_base.PLOT.SALES_TYPES ST ON S.SALE_TYPE_ENUM = ST.SALE_TYPE_ENUM
JOIN haven_base.PLOT.PARKS PK ON S.PARK_ID = PK.PARK_ID
LEFT JOIN haven_store.common.Dates_And_Periods WEEK_NO ( NOLOCK ) ON YEAR(WEEK_NO.ActualDate) = YEAR(S.COMPLETION_DATE)
AND MONTH(WEEK_NO.ActualDate) = MONTH(S.COMPLETION_DATE)
AND DAY(WEEK_NO.ActualDate) = DAY(S.COMPLETION_DATE)
LEFT JOIN haven_base.PLOT.CSPS CSP ON CSP.CSP_ID = S.CSP_ID
LEFT JOIN haven_base.PLOT.FINANCE_COMPANIES FC ON S.FIN_COMPANY_ID = FC.FIN_COMPANY_ID
LEFT JOIN haven_base.PLOT.VANS VP1 ON VP1.VAN_ID = S.PEX1_VAN_ID
LEFT JOIN haven_base.PLOT.VANS VP2 ON VP2.VAN_ID = S.PEX2_VAN_ID
LEFT JOIN haven_base.PLOT.SOURCES SRC ON S.SOURCE_ID = SRC.SOURCE_ID
LEFT JOIN haven_base.PLOT.WELCOME_MEETERS WM ON WM.WM_ID = S.WELCOME_MEETER_ID
LEFT JOIN haven_base.PLOT.PITCHES PIT ON S.DESTINATION_PITCH_ID = PIT.PITCH_ID
LEFT JOIN haven_base.PLOT.ZONES Z ON PIT.ZONE_ID = Z.ZONE_ID
LEFT JOIN haven_base.PLOT.AREAS AR ON PIT.AREA_ID = AR.AREA_ID
LEFT JOIN haven_base.PLOT.PITCHES PIT2 ON V.PITCH_ID = PIT2.PITCH_ID
LEFT JOIN haven_base.PLOT.ZONES Z2 ON PIT2.ZONE_ID = Z2.ZONE_ID
LEFT JOIN haven_base.PLOT.AREAS AR2 ON PIT2.AREA_ID = AR2.AREA_ID
LEFT JOIN fn_SalesValuesBreakDown vals on vals.sale_id = s.sale_id
LEFT JOIN c_LETTING_CAT_HISTORY LCH ON LCH.VAN_ID = V.VAN_ID
LEFT JOIN haven_base.PLOT.LETTING_CAT AS LC ON LCH.LETTING_CAT_ID = LC.LETTING_CAT_ID
left join haven_base.PLOT.van_grades vg on v.VAN_GRADE_ID = vg.van_grade_id and vg.ACTIVE_YN =1
left join c_appointment ap on ap.account_no = ac.account_no
WHERE VALIDATION_DATE IS NOT NULL
AND CANCELLATION_DATE IS NULL
AND YEAR(DATE_SOLD) >= 2021;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM
) as        
SELECT NOMINAL
      ,ACCOUNT
      ,XLEDGER
      ,XACCOUNT
      ,DOCDATE
      ,YEARCODE
      ,PERIOD
      ,VALUE
      ,DESCRIPTION
      ,DOCTYPE
      ,DOCNUM
        FROM haven_base.PLOT_DREAM.D_DETAILS
where YEARCODE = 2023
and (NOMINAL like '%YRLC' );

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_2022 source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_2022(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM
) as        
SELECT NOMINAL
      ,ACCOUNT
      ,XLEDGER
      ,XACCOUNT
      ,DOCDATE
      ,YEARCODE
      ,PERIOD
      ,VALUE
      ,DESCRIPTION
      ,DOCTYPE
      ,DOCNUM
        FROM haven_base.PLOT_DREAM.D_DETAILS
where YEARCODE = 2022
--and (NOMINAL like '%YRLC' );

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_2023 source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_2023(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM
) as        
SELECT NOMINAL
      ,ACCOUNT
      ,XLEDGER
      ,XACCOUNT
      ,DOCDATE
      ,YEARCODE
      ,PERIOD
      ,VALUE
      ,DESCRIPTION
      ,DOCTYPE
      ,DOCNUM
        FROM haven_base.PLOT_DREAM.D_DETAILS
where YEARCODE = 2023;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_2024 source

create OR replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_2024(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM
) as        
SELECT NOMINAL
      ,ACCOUNT
      ,XLEDGER
      ,XACCOUNT
      ,DOCDATE
      ,YEARCODE
      ,PERIOD
      ,VALUE
      ,DESCRIPTION
      ,DOCTYPE
      ,DOCNUM
        FROM haven_base.PLOT_DREAM.D_DETAILS
where YEARCODE = 2024;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_2025 source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_2025(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM
) as        
SELECT NOMINAL
      ,ACCOUNT
      ,XLEDGER
      ,XACCOUNT
      ,DOCDATE
      ,YEARCODE
      ,PERIOD
      ,VALUE
      ,DESCRIPTION
      ,DOCTYPE
      ,DOCNUM
        FROM haven_base.PLOT_DREAM.D_DETAILS
where YEARCODE = 2025;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_FULL_2022 source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_FULL_2022(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	NOMCURRENCY,
	ACCCURRENCY,
	DOCCURRENCY,
	USERVALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM,
	DETAILSTATUS,
	REFNO,
	PAYLIST,
	ALLOCATION,
	DUEDATE,
	DISCOUNT,
	HIGHDATE,
	HIGHYEAR,
	HIGHPERIOD,
	LEDGER,
	INPUTDATE,
	INPUTTIME,
	USERFIELD1,
	USERFIELD2,
	USERFIELD3,
	COMPANYCODE,
	ALTHOMEVAL,
	L3LEDGER,
	L3ACCOUNT,
	L3CURRENCY,
	ROWNO,
	UNALLOCATED,
	RECTYPE,
	USERVALUEFIELD1,
	USERVALUEFIELD2,
	USERVALUEFIELD3,
	USERVALUEFIELD4,
	TRANTYPE,
	ROWNAME,
	PERIODDATE
) as        
SELECT *
        FROM haven_base.PLOT_DREAM.D_DETAILS
where YEARCODE = 2022;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_FULL_2023 source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_FULL_2023(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	NOMCURRENCY,
	ACCCURRENCY,
	DOCCURRENCY,
	USERVALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM,
	DETAILSTATUS,
	REFNO,
	PAYLIST,
	ALLOCATION,
	DUEDATE,
	DISCOUNT,
	HIGHDATE,
	HIGHYEAR,
	HIGHPERIOD,
	LEDGER,
	INPUTDATE,
	INPUTTIME,
	USERFIELD1,
	USERFIELD2,
	USERFIELD3,
	COMPANYCODE,
	ALTHOMEVAL,
	L3LEDGER,
	L3ACCOUNT,
	L3CURRENCY,
	ROWNO,
	UNALLOCATED,
	RECTYPE,
	USERVALUEFIELD1,
	USERVALUEFIELD2,
	USERVALUEFIELD3,
	USERVALUEFIELD4,
	TRANTYPE,
	ROWNAME,
	PERIODDATE
) as        
SELECT *
        FROM haven_base.PLOT_DREAM.D_DETAILS
where YEARCODE = 2023;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_FULL_2024 source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_FULL_2024(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	NOMCURRENCY,
	ACCCURRENCY,
	DOCCURRENCY,
	USERVALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM,
	DETAILSTATUS,
	REFNO,
	PAYLIST,
	ALLOCATION,
	DUEDATE,
	DISCOUNT,
	HIGHDATE,
	HIGHYEAR,
	HIGHPERIOD,
	LEDGER,
	INPUTDATE,
	INPUTTIME,
	USERFIELD1,
	USERFIELD2,
	USERFIELD3,
	COMPANYCODE,
	ALTHOMEVAL,
	L3LEDGER,
	L3ACCOUNT,
	L3CURRENCY,
	ROWNO,
	UNALLOCATED,
	RECTYPE,
	USERVALUEFIELD1,
	USERVALUEFIELD2,
	USERVALUEFIELD3,
	USERVALUEFIELD4,
	TRANTYPE,
	ROWNAME,
	PERIODDATE
) as        
SELECT *
        FROM haven_base.PLOT_DREAM.D_DETAILS
where YEARCODE = 2024;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_FULL_2025 source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.PLOT_DREAM_D_DETAILS_FULL_2025(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	NOMCURRENCY,
	ACCCURRENCY,
	DOCCURRENCY,
	USERVALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM,
	DETAILSTATUS,
	REFNO,
	PAYLIST,
	ALLOCATION,
	DUEDATE,
	DISCOUNT,
	HIGHDATE,
	HIGHYEAR,
	HIGHPERIOD,
	LEDGER,
	INPUTDATE,
	INPUTTIME,
	USERFIELD1,
	USERFIELD2,
	USERFIELD3,
	COMPANYCODE,
	ALTHOMEVAL,
	L3LEDGER,
	L3ACCOUNT,
	L3CURRENCY,
	ROWNO,
	UNALLOCATED,
	RECTYPE,
	USERVALUEFIELD1,
	USERVALUEFIELD2,
	USERVALUEFIELD3,
	USERVALUEFIELD4,
	TRANTYPE,
	ROWNAME,
	PERIODDATE
) as        
SELECT *
        FROM haven_base.plot_dream.D_DETAILS
where YEARCODE = 2025
    ;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.SALES_BREAKDOWN_VALUES source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.SALES_BREAKDOWN_VALUES(
	SALE_ID,
	VANVALUE,
	ADDONS,
	SPDISC,
	PRODISC,
	SUBS
) as
select
    sale_id,
    sum( case when PRICE_TYPE_ENUM = 1  then gross_price else 0 end )                                     as vanValue,
    sum( case when PRICE_TYPE_ENUM NOT IN ( 1, 2, 3, 4, 5, 21, 22, 23 )  then gross_price else 0 end )    as addons,
    sum( case when PRICE_TYPE_ENUM = 22 then gross_price else 0 end )                                     as SpDisc,
    sum( case when PRICE_TYPE_ENUM = 23 then gross_price else 0 end )                                     as ProDisc,
    sum( case when PRICE_TYPE_ENUM IN ( 2, 3, 4, 5, 21 ) then gross_price else 0 end )                    as Subs
from haven_base.PLOT.prices
group by sale_id;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.SALES_CANCELLATIONS source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.SALES_CANCELLATIONS(
	PARK_CODE,
	ACCOUNT_NO,
	CSI_NO,
	VAN_STOCK_NO,
	DATE_SOLD,
	SALE_TYPE_CODE,
	SALE_STATUS_CODE,
	VALIDATION_DATE,
	CANCELLATION_DATE,
	COMPLETION_DATE,
	STATYEAR,
	STATPERIOD,
	TWIN_YN,
	NEW_VAN_YN,
	PRIVATE_SALE_VALUE,
	PRIVATE_SALE_COMMISSION,
	COMMISSION_PAID_YN,
	COMMISSION_PAID_DATE,
	VAN_STOCK_NO_2,
	PEX1_BOTTOM_BOOK_VALUE,
	PEX1_DISCOUNT,
	VAN_STOCK_NO_3,
	PEX2_BOTTOM_BOOK_VALUE,
	PEX2_DISCOUNT,
	GLB_AMOUNT,
	GLB_AMOUNT_NEXT_YEAR,
	RL_AMOUNT,
	GLA_PX_AMOUNT_VAN_1,
	GLA_PX_AMOUNT_VAN_2,
	GLA_PX_AMOUNT_VAN_1_NEXT_YEAR,
	GLA_PX_AMOUNT_VAN_2_NEXT_YEAR,
	NEW_GLA_TOTAL,
	NEW_GLA_TOTAL_NEXT_YEAR,
	DUE_ON_ACCOUNT,
	SUBLET_AMOUNT,
	FINANCE_AMOUNT,
	DEPOSIT_AMOUNT,
	VOUCHER_AMOUNT,
	AMOUNT_DUE_LATER_DATE,
	AMOUNT_DUE_LATER,
	PROFIT_CONFIRMED_YN,
	PROFIT_CONFIRMED_DATE,
	SVL_PRICE_SUB_TOTAL,
	SVL_VAT_AMOUNT,
	ORIGINAL_COST,
	VALUE_STANDARD_RATED,
	VALUE_ZERO_RATED,
	GROSS_PRICE_TOTAL,
	VANVALUE,
	SUBS,
	ADDONS,
	SPDISC,
	PRODISC,
	HP_RATE_PERCENTAGE,
	MONTHLY_PAYMENTS,
	YEARS,
	FIN_COMPANY_CODE,
	FIN_CO_ACCOUNT,
	FIN_DUE_FROM,
	FIN_DUE_TO,
	SOURCE_DESC,
	CSP_DESC,
	WM_DESC,
	KEY_HANDOVER_DATE,
	EXPECTED_HANDOVER_DT,
	KEY_HANDOVER_BY,
	DESTINATION_PITCH,
	VAN_PITCH,
	VAN_BBV,
	KEY_HANDOVER_DONE_YN,
	YIELD_TEAM_OVERRIDE_YN,
	YIELD_TEAM_OVERRIDE_BY,
	NAME,
	MAKE,
	MODEL,
	LENGTH,
	WIDTH,
	NO_OF_BED_CODES,
	YEAR_MADE,
	MAKE_2,
	MODEL_2,
	LENGTH_2,
	WIDTH_2,
	NO_OF_BED_CODES_2,
	YEAR_MADE_2,
	MAKE_3,
	MODEL_3,
	LENGTH_3,
	WIDTH_3,
	NO_OF_BED_CODES_3,
	YEAR_MADE_3,
	LETTING_CAT_DESC,
	LETTING_CAT_CODE,
	VAN_GRADE_DESC
) as
SELECT DISTINCT
PK.PARK_CODE ,
AC.ACCOUNT_NO ,
S.CSI_NO ,
V.VAN_STOCK_NO ,
S.DATE_SOLD ,
ST.SALE_TYPE_CODE ,
SS.SALE_STATUS_CODE ,
S.VALIDATION_DATE ,
S.CANCELLATION_DATE ,
S.COMPLETION_DATE ,
WEEK_NO.StatYear ,
WEEK_NO.StatPeriod ,
S.TWIN_YN ,
S.NEW_VAN_YN ,
S.PRIVATE_SALE_VALUE ,
S.PRIVATE_SALE_COMMISSION ,
S.COMMISSION_PAID_YN ,
S.COMMISSION_PAID_DATE ,
VP1.VAN_STOCK_NO van_stock_no_2,
S.PEX1_BOTTOM_BOOK_VALUE ,
S.PEX1_DISCOUNT ,
VP2.VAN_STOCK_NO van_stock_no_3,
S.PEX2_BOTTOM_BOOK_VALUE ,
S.PEX2_DISCOUNT ,
S.GLB_AMOUNT ,
S.GLB_AMOUNT_NEXT_YEAR ,
S.RL_AMOUNT ,
S.GLA_PX_AMOUNT_VAN_1 ,
S.GLA_PX_AMOUNT_VAN_2 ,
S.GLA_PX_AMOUNT_VAN_1_NEXT_YEAR ,
S.GLA_PX_AMOUNT_VAN_2_NEXT_YEAR ,
S.NEW_GLA_TOTAL ,
s.NEW_GLA_TOTAL_NEXT_YEAR ,
S.DUE_ON_ACCOUNT ,
S.SUBLET_AMOUNT ,
S.FINANCE_AMOUNT ,
S.DEPOSIT_AMOUNT ,
S.VOUCHER_AMOUNT ,
S.AMOUNT_DUE_LATER_DATE ,
S.AMOUNT_DUE_LATER ,
S.PROFIT_CONFIRMED_YN ,
S.PROFIT_CONFIRMED_DATE ,
S.SVL_PRICE_SUB_TOTAL ,
S.SVL_VAT_AMOUNT ,
S.ORIGINAL_COST ,
S.VALUE_STANDARD_RATED ,
S.VALUE_ZERO_RATED ,
S.GROSS_PRICE_TOTAL ,
--MRRP.BaseRetailValue ,
--mrrp.UsedCurr ,
--mrrp.markupPercentage ,
vals.VANVALUE ,
vals.SUBS ,
vals.ADDONS ,
vals.SPDISC ,
vals.PRODISC ,
S.HP_RATE_PERCENTAGE ,
S.MONTHLY_PAYMENTS ,
S.YEARS ,
FC.FIN_COMPANY_CODE ,
S.FIN_CO_ACCOUNT ,
S.FIN_DUE_FROM ,
S.FIN_DUE_TO ,
SRC.SOURCE_DESC ,
CSP.CSP_DESC ,
WM.WM_DESC ,
S.KEY_HANDOVER_DATE ,
S.EXPECTED_HANDOVER_DT ,
S.KEY_HANDOVER_BY ,
PK.PARK_CODE || AR.AREA_CODE || Z.ZONE_CODE || PIT.PITCH_NO AS DESTINATION_PITCH,
PK.PARK_CODE || AR2.AREA_CODE || Z2.ZONE_CODE || PIT2.PITCH_NO AS VAN_PITCH,
S.VAN_BBV ,
S.KEY_HANDOVER_DONE_YN ,
S.YIELD_TEAM_OVERRIDE_YN ,
S.YIELD_TEAM_OVERRIDE_BY ,
OW.NAME,
V.MAKE ,
V.MODEL ,
V.LENGTH ,
V.WIDTH ,
V.NO_OF_BED_CODES ,
V.YEAR_MADE ,
VP1.MAKE  make_2,
VP1.MODEL  model_2,
VP1.LENGTH  length_2 ,
VP1.WIDTH  width_2,
VP1.NO_OF_BED_CODES no_of_bed_codes_2  ,
VP1.YEAR_MADE  year_made_2,
VP2.MAKE  make_3,
VP2.MODEL  model_3,
VP2.LENGTH  length_3,
VP2.WIDTH  width_3,
VP2.NO_OF_BED_CODES  no_of_bed_codes_3,
VP2.YEAR_MADE year_made_3,
LC.LETTING_CAT_DESC ,
LC.LETTING_CAT_CODE ,
vg.VAN_GRADE_DESC
FROM haven_base.PLOT.SALES S
JOIN haven_base.PLOT.SALES_STATUSES SS ON S.SALE_STATUS_ENUM = SS.SALE_STATUS_ENUM
JOIN haven_base.PLOT.ACCOUNTS AC ON S.ACCOUNT_ID = AC.ACCOUNT_ID
LEFT JOIN haven_base.PLOT.OWNERS OW ON OW.OWNER_ID = AC.OWNER_ID
JOIN haven_base.PLOT.VANS V ON S.VAN_ID = V.VAN_ID
--OUTER APPLY plotreprs.dbo.fn_GetVanValuation(v.VAN_ID) AS MRRP
JOIN haven_base.PLOT.SALES_TYPES ST ON S.SALE_TYPE_ENUM = ST.SALE_TYPE_ENUM
JOIN haven_base.PLOT.PARKS PK ON S.PARK_ID = PK.PARK_ID
LEFT JOIN haven_store.common.Dates_And_Periods WEEK_NO  ON YEAR(WEEK_NO.ActualDate) = YEAR(S.COMPLETION_DATE)
AND MONTH(WEEK_NO.ActualDate) = MONTH(S.COMPLETION_DATE)
AND DAY(WEEK_NO.ActualDate) = DAY(S.COMPLETION_DATE)
LEFT JOIN haven_base.PLOT.CSPS CSP ON CSP.CSP_ID = S.CSP_ID
LEFT JOIN haven_base.PLOT.FINANCE_COMPANIES FC ON S.FIN_COMPANY_ID = FC.FIN_COMPANY_ID
LEFT JOIN haven_base.PLOT.VANS VP1 ON VP1.VAN_ID = S.PEX1_VAN_ID
LEFT JOIN haven_base.PLOT.VANS VP2 ON VP2.VAN_ID = S.PEX2_VAN_ID
LEFT JOIN haven_base.PLOT.SOURCES SRC ON S.SOURCE_ID = SRC.SOURCE_ID
LEFT JOIN haven_base.PLOT.WELCOME_MEETERS WM ON WM.WM_ID = S.WELCOME_MEETER_ID
LEFT JOIN haven_base.PLOT.PITCHES PIT ON S.DESTINATION_PITCH_ID = PIT.PITCH_ID
LEFT JOIN haven_base.PLOT.ZONES Z ON PIT.ZONE_ID = Z.ZONE_ID
LEFT JOIN haven_base.PLOT.AREAS AR ON PIT.AREA_ID = AR.AREA_ID
LEFT JOIN haven_base.PLOT.PITCHES PIT2 ON V.PITCH_ID = PIT2.PITCH_ID
LEFT JOIN haven_base.PLOT.ZONES Z2 ON PIT2.ZONE_ID = Z2.ZONE_ID
LEFT JOIN haven_base.PLOT.AREAS AR2 ON PIT2.AREA_ID = AR2.AREA_ID
LEFT JOIN SALES_BREAKDOWN_VALUES as vals on vals.sale_id = s.sale_id
LEFT JOIN haven_base.PLOT.LETTING_CAT_HISTORY LCH ON LCH.VAN_ID = V.VAN_ID
                                                     AND LCH.EFFECTIVE_DT = ( SELECT
                                                              MAX(LCH2.EFFECTIVE_DT)
                                                              FROM
                                                              haven_base.PLOT.LETTING_CAT_HISTORY LCH2
                                                              WHERE
                                                              LCH2.VAN_ID = V.VAN_ID
                                                              AND LCH2.EFFECTIVE_DT <= GETDATE()
                                                                                                         AND LCH2.GRADE_APPROVED_YN = 1
                                                              )
LEFT JOIN haven_base.PLOT.LETTING_CAT AS LC ON LCH.LETTING_CAT_ID = LC.LETTING_CAT_ID
left join haven_base.PLOT.van_grades vg on v.VAN_GRADE_ID = vg.van_grade_id and vg.ACTIVE_YN =1
WHERE VALIDATION_DATE IS NOT NULL
AND YEAR(DATE_SOLD) >= 2021;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.SALES_CANCELLATIONS_HISTORICAL source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.SALES_CANCELLATIONS_HISTORICAL(
	PARK_CODE,
	ACCOUNT_NO,
	CSI_NO,
	VAN_STOCK_NO,
	DATE_SOLD,
	SALE_TYPE_CODE,
	SALE_STATUS_CODE,
	VALIDATION_DATE,
	CANCELLATION_DATE,
	COMPLETION_DATE,
	STATYEAR,
	STATPERIOD,
	TWIN_YN,
	NEW_VAN_YN,
	PRIVATE_SALE_VALUE,
	PRIVATE_SALE_COMMISSION,
	COMMISSION_PAID_YN,
	COMMISSION_PAID_DATE,
	VAN_STOCK_NO_2,
	PEX1_BOTTOM_BOOK_VALUE,
	PEX1_DISCOUNT,
	VAN_STOCK_NO_3,
	PEX2_BOTTOM_BOOK_VALUE,
	PEX2_DISCOUNT,
	GLB_AMOUNT,
	GLB_AMOUNT_NEXT_YEAR,
	RL_AMOUNT,
	GLA_PX_AMOUNT_VAN_1,
	GLA_PX_AMOUNT_VAN_2,
	GLA_PX_AMOUNT_VAN_1_NEXT_YEAR,
	GLA_PX_AMOUNT_VAN_2_NEXT_YEAR,
	NEW_GLA_TOTAL,
	NEW_GLA_TOTAL_NEXT_YEAR,
	DUE_ON_ACCOUNT,
	SUBLET_AMOUNT,
	FINANCE_AMOUNT,
	DEPOSIT_AMOUNT,
	VOUCHER_AMOUNT,
	AMOUNT_DUE_LATER_DATE,
	AMOUNT_DUE_LATER,
	PROFIT_CONFIRMED_YN,
	PROFIT_CONFIRMED_DATE,
	SVL_PRICE_SUB_TOTAL,
	SVL_VAT_AMOUNT,
	ORIGINAL_COST,
	VALUE_STANDARD_RATED,
	VALUE_ZERO_RATED,
	GROSS_PRICE_TOTAL,
	VANVALUE,
	SUBS,
	ADDONS,
	SPDISC,
	PRODISC,
	HP_RATE_PERCENTAGE,
	MONTHLY_PAYMENTS,
	YEARS,
	FIN_COMPANY_CODE,
	FIN_CO_ACCOUNT,
	FIN_DUE_FROM,
	FIN_DUE_TO,
	SOURCE_DESC,
	CSP_DESC,
	WM_DESC,
	KEY_HANDOVER_DATE,
	EXPECTED_HANDOVER_DT,
	KEY_HANDOVER_BY,
	DESTINATION_PITCH,
	VAN_PITCH,
	VAN_BBV,
	KEY_HANDOVER_DONE_YN,
	YIELD_TEAM_OVERRIDE_YN,
	YIELD_TEAM_OVERRIDE_BY,
	NAME,
	MAKE,
	MODEL,
	LENGTH,
	WIDTH,
	NO_OF_BED_CODES,
	YEAR_MADE,
	MAKE_2,
	MODEL_2,
	LENGTH_2,
	WIDTH_2,
	NO_OF_BED_CODES_2,
	YEAR_MADE_2,
	MAKE_3,
	MODEL_3,
	LENGTH_3,
	WIDTH_3,
	NO_OF_BED_CODES_3,
	YEAR_MADE_3,
	LETTING_CAT_DESC,
	LETTING_CAT_CODE,
	VAN_GRADE_DESC
) as
SELECT DISTINCT
PK.PARK_CODE ,
AC.ACCOUNT_NO ,
S.CSI_NO ,
V.VAN_STOCK_NO ,
S.DATE_SOLD ,
ST.SALE_TYPE_CODE ,
SS.SALE_STATUS_CODE ,
S.VALIDATION_DATE ,
S.CANCELLATION_DATE ,
S.COMPLETION_DATE ,
WEEK_NO.StatYear ,
WEEK_NO.StatPeriod ,
S.TWIN_YN ,
S.NEW_VAN_YN ,
S.PRIVATE_SALE_VALUE ,
S.PRIVATE_SALE_COMMISSION ,
S.COMMISSION_PAID_YN ,
S.COMMISSION_PAID_DATE ,
VP1.VAN_STOCK_NO van_stock_no_2 ,
S.PEX1_BOTTOM_BOOK_VALUE ,
S.PEX1_DISCOUNT ,
VP2.VAN_STOCK_NO van_stock_no_3,
S.PEX2_BOTTOM_BOOK_VALUE ,
S.PEX2_DISCOUNT ,
S.GLB_AMOUNT ,
S.GLB_AMOUNT_NEXT_YEAR ,
S.RL_AMOUNT ,
S.GLA_PX_AMOUNT_VAN_1 ,
S.GLA_PX_AMOUNT_VAN_2 ,
S.GLA_PX_AMOUNT_VAN_1_NEXT_YEAR ,
S.GLA_PX_AMOUNT_VAN_2_NEXT_YEAR ,
S.NEW_GLA_TOTAL ,
s.NEW_GLA_TOTAL_NEXT_YEAR ,
S.DUE_ON_ACCOUNT ,
S.SUBLET_AMOUNT ,
S.FINANCE_AMOUNT ,
S.DEPOSIT_AMOUNT ,
S.VOUCHER_AMOUNT ,
S.AMOUNT_DUE_LATER_DATE ,
S.AMOUNT_DUE_LATER ,
S.PROFIT_CONFIRMED_YN ,
S.PROFIT_CONFIRMED_DATE ,
S.SVL_PRICE_SUB_TOTAL ,
S.SVL_VAT_AMOUNT ,
S.ORIGINAL_COST ,
S.VALUE_STANDARD_RATED ,
S.VALUE_ZERO_RATED ,
S.GROSS_PRICE_TOTAL ,
--MRRP.BaseRetailValue ,
--mrrp.UsedCurr ,
--mrrp.markupPercentage ,
vals.VANVALUE ,
vals.SUBS ,
vals.ADDONS ,
vals.SPDISC ,
vals.PRODISC ,
S.HP_RATE_PERCENTAGE ,
S.MONTHLY_PAYMENTS ,
S.YEARS ,
FC.FIN_COMPANY_CODE ,
S.FIN_CO_ACCOUNT ,
S.FIN_DUE_FROM ,
S.FIN_DUE_TO ,
SRC.SOURCE_DESC ,
CSP.CSP_DESC ,
WM.WM_DESC ,
S.KEY_HANDOVER_DATE ,
S.EXPECTED_HANDOVER_DT ,
S.KEY_HANDOVER_BY ,
PK.PARK_CODE || AR.AREA_CODE || Z.ZONE_CODE || PIT.PITCH_NO AS DESTINATION_PITCH,
PK.PARK_CODE || AR2.AREA_CODE || Z2.ZONE_CODE || PIT2.PITCH_NO AS VAN_PITCH,
S.VAN_BBV ,
S.KEY_HANDOVER_DONE_YN ,
S.YIELD_TEAM_OVERRIDE_YN ,
S.YIELD_TEAM_OVERRIDE_BY ,
OW.NAME,
V.MAKE ,
V.MODEL ,
V.LENGTH ,
V.WIDTH ,
V.NO_OF_BED_CODES ,
V.YEAR_MADE ,
VP1.MAKE  make_2,
VP1.MODEL  model_2,
VP1.LENGTH  length_2 ,
VP1.WIDTH  width_2,
VP1.NO_OF_BED_CODES no_of_bed_codes_2  ,
VP1.YEAR_MADE  year_made_2,
VP2.MAKE  make_3,
VP2.MODEL  model_3,
VP2.LENGTH  length_3,
VP2.WIDTH  width_3,
VP2.NO_OF_BED_CODES  no_of_bed_codes_3,
VP2.YEAR_MADE year_made_3,
LC.LETTING_CAT_DESC ,
LC.LETTING_CAT_CODE ,
vg.VAN_GRADE_DESC
FROM haven_base.PLOT.SALES S
JOIN haven_base.PLOT.SALES_STATUSES SS ON S.SALE_STATUS_ENUM = SS.SALE_STATUS_ENUM
JOIN haven_base.PLOT.ACCOUNTS AC ON S.ACCOUNT_ID = AC.ACCOUNT_ID
LEFT JOIN haven_base.PLOT.OWNERS OW ON OW.OWNER_ID = AC.OWNER_ID
JOIN haven_base.PLOT.VANS V ON S.VAN_ID = V.VAN_ID
--OUTER APPLY plotreprs.dbo.fn_GetVanValuation(v.VAN_ID) AS MRRP
JOIN haven_base.PLOT.SALES_TYPES ST ON S.SALE_TYPE_ENUM = ST.SALE_TYPE_ENUM
JOIN haven_base.PLOT.PARKS PK ON S.PARK_ID = PK.PARK_ID
LEFT JOIN haven_store.common.Dates_And_Periods WEEK_NO  ON YEAR(WEEK_NO.ActualDate) = YEAR(S.COMPLETION_DATE)
AND MONTH(WEEK_NO.ActualDate) = MONTH(S.COMPLETION_DATE)
AND DAY(WEEK_NO.ActualDate) = DAY(S.COMPLETION_DATE)
LEFT JOIN haven_base.PLOT.CSPS CSP ON CSP.CSP_ID = S.CSP_ID
LEFT JOIN haven_base.PLOT.FINANCE_COMPANIES FC ON S.FIN_COMPANY_ID = FC.FIN_COMPANY_ID
LEFT JOIN haven_base.PLOT.VANS VP1 ON VP1.VAN_ID = S.PEX1_VAN_ID
LEFT JOIN haven_base.PLOT.VANS VP2 ON VP2.VAN_ID = S.PEX2_VAN_ID
LEFT JOIN haven_base.PLOT.SOURCES SRC ON S.SOURCE_ID = SRC.SOURCE_ID
LEFT JOIN haven_base.PLOT.WELCOME_MEETERS WM ON WM.WM_ID = S.WELCOME_MEETER_ID
LEFT JOIN haven_base.PLOT.PITCHES PIT ON S.DESTINATION_PITCH_ID = PIT.PITCH_ID
LEFT JOIN haven_base.PLOT.ZONES Z ON PIT.ZONE_ID = Z.ZONE_ID
LEFT JOIN haven_base.PLOT.AREAS AR ON PIT.AREA_ID = AR.AREA_ID
LEFT JOIN haven_base.PLOT.PITCHES PIT2 ON V.PITCH_ID = PIT2.PITCH_ID
LEFT JOIN haven_base.PLOT.ZONES Z2 ON PIT2.ZONE_ID = Z2.ZONE_ID
LEFT JOIN haven_base.PLOT.AREAS AR2 ON PIT2.AREA_ID = AR2.AREA_ID
LEFT JOIN SALES_BREAKDOWN_VALUES as vals on vals.sale_id = s.sale_id
LEFT JOIN haven_base.PLOT.LETTING_CAT_HISTORY LCH ON LCH.VAN_ID = V.VAN_ID
                                                     AND LCH.EFFECTIVE_DT = ( SELECT
                                                              MAX(LCH2.EFFECTIVE_DT)
                                                              FROM
                                                              haven_base.PLOT.LETTING_CAT_HISTORY LCH2
                                                              WHERE
                                                              LCH2.VAN_ID = V.VAN_ID
                                                              AND LCH2.EFFECTIVE_DT <= GETDATE()
                                                                                                         AND LCH2.GRADE_APPROVED_YN = 1
                                                              )
LEFT JOIN haven_base.PLOT.LETTING_CAT AS LC ON LCH.LETTING_CAT_ID = LC.LETTING_CAT_ID
left join haven_base.PLOT.van_grades vg on v.VAN_GRADE_ID = vg.van_grade_id and vg.ACTIVE_YN =1
WHERE VALIDATION_DATE IS NOT NULL
AND YEAR(DATE_SOLD) >= 2010;

-- HAVEN_STORE.HAVEN_ACCOUNTANTS.SALES_HISTORICAL source

create or replace view HAVEN_STORE.HAVEN_ACCOUNTANTS.SALES_HISTORICAL(
	PARK_CODE,
	ACCOUNT_NO,
	CSI_NO,
	VAN_STOCK_NO,
	DATE_SOLD,
	SALE_TYPE_CODE,
	SALE_STATUS_CODE,
	VALIDATION_DATE,
	CANCELLATION_DATE,
	COMPLETION_DATE,
	STATYEAR,
	STATPERIOD,
	TWIN_YN,
	NEW_VAN_YN,
	PRIVATE_SALE_VALUE,
	PRIVATE_SALE_COMMISSION,
	COMMISSION_PAID_YN,
	COMMISSION_PAID_DATE,
	VAN_STOCK_NO_2,
	PEX1_BOTTOM_BOOK_VALUE,
	PEX1_DISCOUNT,
	VAN_STOCK_NO_3,
	PEX2_BOTTOM_BOOK_VALUE,
	PEX2_DISCOUNT,
	GLB_AMOUNT,
	GLB_AMOUNT_NEXT_YEAR,
	RL_AMOUNT,
	GLA_PX_AMOUNT_VAN_1,
	GLA_PX_AMOUNT_VAN_2,
	GLA_PX_AMOUNT_VAN_1_NEXT_YEAR,
	GLA_PX_AMOUNT_VAN_2_NEXT_YEAR,
	NEW_GLA_TOTAL,
	NEW_GLA_TOTAL_NEXT_YEAR,
	DUE_ON_ACCOUNT,
	SUBLET_AMOUNT,
	FINANCE_AMOUNT,
	DEPOSIT_AMOUNT,
	VOUCHER_AMOUNT,
	AMOUNT_DUE_LATER_DATE,
	AMOUNT_DUE_LATER,
	PROFIT_CONFIRMED_YN,
	PROFIT_CONFIRMED_DATE,
	SVL_PRICE_SUB_TOTAL,
	SVL_VAT_AMOUNT,
	ORIGINAL_COST,
	VALUE_STANDARD_RATED,
	VALUE_ZERO_RATED,
	GROSS_PRICE_TOTAL,
	VANVALUE,
	SUBS,
	ADDONS,
	SPDISC,
	PRODISC,
	HP_RATE_PERCENTAGE,
	MONTHLY_PAYMENTS,
	YEARS,
	FIN_COMPANY_CODE,
	FIN_CO_ACCOUNT,
	FIN_DUE_FROM,
	FIN_DUE_TO,
	SOURCE_DESC,
	CSP_DESC,
	WM_DESC,
	KEY_HANDOVER_DATE,
	EXPECTED_HANDOVER_DT,
	KEY_HANDOVER_BY,
	DESTINATION_PITCH,
	VAN_PITCH,
	VAN_BBV,
	KEY_HANDOVER_DONE_YN,
	YIELD_TEAM_OVERRIDE_YN,
	YIELD_TEAM_OVERRIDE_BY,
	NAME,
	MAKE,
	MODEL,
	LENGTH,
	WIDTH,
	NO_OF_BED_CODES,
	YEAR_MADE,
	MAKE_2,
	MODEL_2,
	LENGTH_2,
	WIDTH_2,
	NO_OF_BED_CODES_2,
	YEAR_MADE_2,
	MAKE_3,
	MODEL_3,
	LENGTH_3,
	WIDTH_3,
	NO_OF_BED_CODES_3,
	YEAR_MADE_3,
	LETTING_CAT_DESC,
	LETTING_CAT_CODE,
	VAN_GRADE_DESC
) as
SELECT DISTINCT
PK.PARK_CODE ,
AC.ACCOUNT_NO ,
S.CSI_NO ,
V.VAN_STOCK_NO ,
S.DATE_SOLD ,
ST.SALE_TYPE_CODE ,
SS.SALE_STATUS_CODE ,
S.VALIDATION_DATE ,
S.CANCELLATION_DATE ,
S.COMPLETION_DATE ,
WEEK_NO.StatYear ,
WEEK_NO.StatPeriod ,
S.TWIN_YN ,
S.NEW_VAN_YN ,
S.PRIVATE_SALE_VALUE ,
S.PRIVATE_SALE_COMMISSION ,
S.COMMISSION_PAID_YN ,
S.COMMISSION_PAID_DATE ,
VP1.VAN_STOCK_NO van_stock_no_2,
S.PEX1_BOTTOM_BOOK_VALUE ,
S.PEX1_DISCOUNT ,
VP2.VAN_STOCK_NO van_stock_no_3,
S.PEX2_BOTTOM_BOOK_VALUE ,
S.PEX2_DISCOUNT ,
S.GLB_AMOUNT ,
S.GLB_AMOUNT_NEXT_YEAR ,
S.RL_AMOUNT ,
S.GLA_PX_AMOUNT_VAN_1 ,
S.GLA_PX_AMOUNT_VAN_2 ,
S.GLA_PX_AMOUNT_VAN_1_NEXT_YEAR ,
S.GLA_PX_AMOUNT_VAN_2_NEXT_YEAR ,
S.NEW_GLA_TOTAL ,
s.NEW_GLA_TOTAL_NEXT_YEAR ,
S.DUE_ON_ACCOUNT ,
S.SUBLET_AMOUNT ,
S.FINANCE_AMOUNT ,
S.DEPOSIT_AMOUNT ,
S.VOUCHER_AMOUNT ,
S.AMOUNT_DUE_LATER_DATE ,
S.AMOUNT_DUE_LATER ,
S.PROFIT_CONFIRMED_YN ,
S.PROFIT_CONFIRMED_DATE ,
S.SVL_PRICE_SUB_TOTAL ,
S.SVL_VAT_AMOUNT ,
S.ORIGINAL_COST ,
S.VALUE_STANDARD_RATED ,
S.VALUE_ZERO_RATED ,
S.GROSS_PRICE_TOTAL ,
--MRRP.BaseRetailValue ,
--mrrp.UsedCurr ,
--mrrp.markupPercentage ,
vals.VANVALUE ,
vals.SUBS ,
vals.ADDONS ,
vals.SPDISC ,
vals.PRODISC ,
S.HP_RATE_PERCENTAGE ,
S.MONTHLY_PAYMENTS ,
S.YEARS ,
FC.FIN_COMPANY_CODE ,
S.FIN_CO_ACCOUNT ,
S.FIN_DUE_FROM ,
S.FIN_DUE_TO ,
SRC.SOURCE_DESC ,
CSP.CSP_DESC ,
WM.WM_DESC ,
S.KEY_HANDOVER_DATE ,
S.EXPECTED_HANDOVER_DT ,
S.KEY_HANDOVER_BY ,
PK.PARK_CODE || AR.AREA_CODE || Z.ZONE_CODE || PIT.PITCH_NO AS DESTINATION_PITCH,
PK.PARK_CODE || AR2.AREA_CODE || Z2.ZONE_CODE || PIT2.PITCH_NO AS VAN_PITCH,
S.VAN_BBV ,
S.KEY_HANDOVER_DONE_YN ,
S.YIELD_TEAM_OVERRIDE_YN ,
S.YIELD_TEAM_OVERRIDE_BY ,
OW.NAME,
V.MAKE ,
V.MODEL ,
V.LENGTH ,
V.WIDTH ,
V.NO_OF_BED_CODES ,
V.YEAR_MADE ,
VP1.MAKE  make_2,
VP1.MODEL  model_2,
VP1.LENGTH  length_2 ,
VP1.WIDTH  width_2,
VP1.NO_OF_BED_CODES no_of_bed_codes_2  ,
VP1.YEAR_MADE  year_made_2,
VP2.MAKE  make_3,
VP2.MODEL  model_3,
VP2.LENGTH  length_3,
VP2.WIDTH  width_3,
VP2.NO_OF_BED_CODES  no_of_bed_codes_3,
VP2.YEAR_MADE year_made_3,
LC.LETTING_CAT_DESC ,
LC.LETTING_CAT_CODE ,
vg.VAN_GRADE_DESC
FROM haven_base.PLOT.SALES S
JOIN haven_base.PLOT.SALES_STATUSES SS ON S.SALE_STATUS_ENUM = SS.SALE_STATUS_ENUM
JOIN haven_base.PLOT.ACCOUNTS AC ON S.ACCOUNT_ID = AC.ACCOUNT_ID
LEFT JOIN haven_base.PLOT.OWNERS OW ON OW.OWNER_ID = AC.OWNER_ID
JOIN haven_base.PLOT.VANS V ON S.VAN_ID = V.VAN_ID
--OUTER APPLY plotreprs.dbo.fn_GetVanValuation(v.VAN_ID) AS MRRP
JOIN haven_base.PLOT.SALES_TYPES ST ON S.SALE_TYPE_ENUM = ST.SALE_TYPE_ENUM
JOIN haven_base.PLOT.PARKS PK ON S.PARK_ID = PK.PARK_ID
LEFT JOIN haven_store.common.Dates_And_Periods WEEK_NO  ON YEAR(WEEK_NO.ActualDate) = YEAR(S.COMPLETION_DATE)
AND MONTH(WEEK_NO.ActualDate) = MONTH(S.COMPLETION_DATE)
AND DAY(WEEK_NO.ActualDate) = DAY(S.COMPLETION_DATE)
LEFT JOIN haven_base.PLOT.CSPS CSP ON CSP.CSP_ID = S.CSP_ID
LEFT JOIN haven_base.PLOT.FINANCE_COMPANIES FC ON S.FIN_COMPANY_ID = FC.FIN_COMPANY_ID
LEFT JOIN haven_base.PLOT.VANS VP1 ON VP1.VAN_ID = S.PEX1_VAN_ID
LEFT JOIN haven_base.PLOT.VANS VP2 ON VP2.VAN_ID = S.PEX2_VAN_ID
LEFT JOIN haven_base.PLOT.SOURCES SRC ON S.SOURCE_ID = SRC.SOURCE_ID
LEFT JOIN haven_base.PLOT.WELCOME_MEETERS WM ON WM.WM_ID = S.WELCOME_MEETER_ID
LEFT JOIN haven_base.PLOT.PITCHES PIT ON S.DESTINATION_PITCH_ID = PIT.PITCH_ID
LEFT JOIN haven_base.PLOT.ZONES Z ON PIT.ZONE_ID = Z.ZONE_ID
LEFT JOIN haven_base.PLOT.AREAS AR ON PIT.AREA_ID = AR.AREA_ID
LEFT JOIN haven_base.PLOT.PITCHES PIT2 ON V.PITCH_ID = PIT2.PITCH_ID
LEFT JOIN haven_base.PLOT.ZONES Z2 ON PIT2.ZONE_ID = Z2.ZONE_ID
LEFT JOIN haven_base.PLOT.AREAS AR2 ON PIT2.AREA_ID = AR2.AREA_ID
LEFT JOIN SALES_BREAKDOWN_VALUES as vals on vals.sale_id = s.sale_id
LEFT JOIN haven_base.PLOT.LETTING_CAT_HISTORY LCH ON LCH.VAN_ID = V.VAN_ID
                                                     AND LCH.EFFECTIVE_DT = ( SELECT
                                                              MAX(LCH2.EFFECTIVE_DT)
                                                              FROM
                                                              haven_base.PLOT.LETTING_CAT_HISTORY LCH2
                                                              WHERE
                                                              LCH2.VAN_ID = V.VAN_ID
                                                              AND LCH2.EFFECTIVE_DT <= GETDATE()
                                                                                                         AND LCH2.GRADE_APPROVED_YN = 1
                                                              )
LEFT JOIN haven_base.PLOT.LETTING_CAT AS LC ON LCH.LETTING_CAT_ID = LC.LETTING_CAT_ID
left join haven_base.PLOT.van_grades vg on v.VAN_GRADE_ID = vg.van_grade_id and vg.ACTIVE_YN =1
WHERE VALIDATION_DATE IS NOT NULL
AND CANCELLATION_DATE IS NULL
AND YEAR(DATE_SOLD) >= 2010;
