USE ROLE useradmin;

create role haven_revenue_management_pricer;

CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__PRICER__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__AVAILABILITY__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__COMMERCIAL__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__SEAWARE__READER;
CREATE ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__COMMON__READER;

USE ROLE securityadmin;

GRANT ROLE _HAVEN_STORE__OCANDC__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
GRANT ROLE _HAVEN_STORE__TROOPER2__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
GRANT ROLE _HAVEN_STORE__PRICER__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__PRICER__READER;
GRANT ROLE _HAVEN_STORE__TROOPER__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER__READER;
GRANT ROLE _HAVEN_BASE__PRICER__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
GRANT ROLE _HAVEN_STORE__AVAILABILITY__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__AVAILABILITY__READER;
GRANT ROLE _HAVEN_STORE__COMMERCIAL__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__COMMERCIAL__READER;
GRANT ROLE _HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__READER;
GRANT ROLE _HAVEN_BASE__SEAWARE__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__SEAWARE__READER;
GRANT ROLE _HAVEN_STORE__COMMON__USAGE TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__COMMON__READER;

grant select on table HAVEN_STORE.OCANDC.BOOKINGS_DAILYEXTRACT to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.TROOPER2.BOOKING_ADDON_AUDIT to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.TROOPER2.BOOKING_DETAIL_HISTORY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.TROOPER2.BOOKING_FINANCIALS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.TROOPER2.BOOKING_FINANCIALS_PRE_CANCELLATION to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.TROOPER2.BOOKING_HEADER to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.PRICER.BREAK_SEGMENTATION_LOOKUP_HISTORY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__PRICER__READER;
grant select on table HAVEN_STORE.PRICER.BUDGET_INPUTS_HISTORY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__PRICER__READER;
grant select on table HAVEN_STORE.OCANDC.BUDGET_PHYSICAL_CAPACITY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.TROOPER.CANCELLATIONS_CURRENTSEASON to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER__READER;
grant select on table HAVEN_STORE.TROOPER.GRADE_MAPPING to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER__READER;
grant select on table HAVEN_STORE.TROOPER2.BOOKING_HEADER_HISTORY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_BASE.PRICER.GRADE_MAPPING_ADDITIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_STORE.TROOPER2.GROUP_FINANCIALS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.OCANDC.HAVEN_SEARCHES to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.HAVEN_TRANSACTIONS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.AVAILABILITY.INVENTORY_AVAILABILITY_HISTORY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__AVAILABILITY__READER;
grant select on table HAVEN_STORE.OCANDC.LETTINGS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.LETTING_CAPS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_BASE.PRICER.M01_BOOKING_CURVE_EBO_MODEL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_BASE.PRICER.M01_BOOKING_CURVE_MODEL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_BASE.PRICER.M06_CANCELLATIONS_DYNAMIC_UD to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_BASE.PRICER.M06_CANCELLATIONS_STATIC_UD to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_BASE.PRICER.META_DVTP_GLOBAL_V2 to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_AGG_HOLIDAYSALES_TY_FINAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_AGG_TARGETS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_AGG_TARGETS_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_GRADE_TYPE_BREAK to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_GRADE_TYPE_BREAK_CABIN to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_DENSE_LEAD_TIME_DAY_WITH_BREAKS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_BREAK_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_LAST_PRICE_CHANGE_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_LETTINGS_FINAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_LETTINGS_PROBABILITY_TABLE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_LETTING_BUDGET to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_MARKETING_PERIOD_MAP to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_PRICE_CHANGE_CLEAN to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_PRICE_CHANGE_CLEAN_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_RM_ALL_CUTS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_SALES_CUBE_FINAL_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_TRIMMED_PRICE_CHANGES_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.PARK_CODE_TO_NAME to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.COMMERCIAL.PRICER_MINMAX to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__COMMERCIAL__READER;
grant select on table HAVEN_STORE.TROOPER2.PRORATED_GROUP_REVENUE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.TROOPER2.PRORATED_RESERVATION_REVENUE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.OCANDC.ROOM_TYPE_LOOKUP to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_PIPELINE.PX0006_BLUEYONDER_PRICER.SHIP_LOOKUP to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__READER;
grant select on table HAVEN_STORE.OCANDC.TARGETS_WIDE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_BASE.SEAWARE.VRES_WEB_PRICE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__SEAWARE__READER;
grant select on table HAVEN_STORE.AVAILABILITY.GRADE_PRICE_HISTORY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__AVAILABILITY__READER;
grant select on table HAVEN_BASE.PRICER.IMPORT_PUBLIC_HOLIDAYS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_BASE.PRICER.IMPORT_SCHOOL_HOLIDAYS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_STORE.AVAILABILITY.INVENTORY_AVAILABILITY_HISTORY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__AVAILABILITY__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_AGG_ARRIVALS_TY_FINAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_AGG_HOLIDAYSALES_NY_FINAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_BOOKINGS_INC_CANCELLATION to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_BUDGET to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_BY_ARRIVAL_DATE_FILL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_BREAK to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_CAPACITY_BY_GRADE_TYPE_BREAK_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_DENSE_INDEX to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_DENSE_LEAD_TIME_DAY_WITH_BREAKS_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_GA_COMBINED to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_GA_COMBINED_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_LAST_PRICE_CHANGE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_LEAD_TIME_SEGMENTS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_NEW_CAPACITY_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_PRICE_SILVER_APARTMENTS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_PRICE_SILVER_APARTMENTS_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_RM_ALL_CUTS_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_ROOM_TYPE_LOOKUP to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_SALES_CUBE_LY_TOTAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_SALES_CUBE_LY_TOTAL_SILVER_APT to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_SCATTER_BACKGROUND to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_TRIMMED_CALENDAR to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_UNIT_GW_CONV to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.COMMON.PARKS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__COMMON__READER;
grant select on table HAVEN_STORE.TROOPER2.PRORATED_BOOKING_REVENUE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER;
grant select on table HAVEN_STORE.OCANDC.RES_SUMMARY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.UNALLOCATED_GROUP_UNITS to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_BASE.PRICER.UPLIFT_FACTORS_V5 to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;
grant select on table HAVEN_BASE.SEAWARE.VRES_GRADE_PRICE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__SEAWARE__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_NEW_CAPACITY to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_REGION_AGGREGATION to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_SALES_CUBE_FINAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_SALES_CUBE_LY_TOTAL_REGIONAL to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.OCC_TRIMMED_PRICE_CHANGES to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;
grant select on table HAVEN_STORE.OCANDC.RM_MAP to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER;


grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__OCANDC__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER2__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__PRICER__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__TROOPER__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__AVAILABILITY__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__COMMERCIAL__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__SEAWARE__READER to role haven_revenue_management_pricer;
grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE__COMMON__READER to role haven_revenue_management_pricer;




use role haven_revenue_management_pricer;

use role dba;

show grants to role haven_revenue_management_pricer;

show grants to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_BASE__PRICER__READER;

use role securityadmin;

revoke role _HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__USAGE from ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUvEYONDER_PRICER__READER;

use role useradmin;

create role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__USAGE;

use role securityadmin;

grant usage on database haven_pipeline to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__USAGE;

grant usage on schema haven_pipeline.PX0006_BLUEYONDER_PRICER to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__USAGE;

grant role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__USAGE to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__READER;

show grants to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__READER;

show grants to role _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__USAGE;

show grants to role haven_revenue_management_pricer;

------------

USE ROLE sysadmin;

CREATE WAREHOUSE haven_revenue_management_pricer_warehouse_xsmall WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

use role useradmin;

create role _haven_revenue_management_pricer_warehouse_xsmall__warehouse__operator;
create role _haven_revenue_management_pricer_warehouse_xsmall__warehouse__usage;

USE ROLE securityadmin;

grant usage, monitor on warehouse haven_revenue_management_pricer_warehouse_xsmall to role _haven_revenue_management_pricer_warehouse_xsmall__warehouse__usage;
grant role _haven_revenue_management_pricer_warehouse_xsmall__warehouse__usage to role _haven_revenue_management_pricer_warehouse_xsmall__warehouse__operator;
grant operate, modify on warehouse haven_revenue_management_pricer_warehouse_xsmall to role _haven_revenue_management_pricer_warehouse_xsmall__warehouse__operator;

GRANT ROLE _haven_revenue_management_pricer_warehouse_xsmall__warehouse__usage TO ROLE haven_revenue_management_pricer; 

GRANT ROLE haven_revenue_management_pricer TO USER donovanransome;

________

--haven_revenue_management

USE ROLE sysadmin;
CREATE DATABASE haven_revenue_management;

USE ROLE useradmin;
CREATE ROLE _haven_revenue_management__usage;
CREATE ROLE _haven_revenue_management__schema;

CREATE ROLE haven_revenue_management_dillonsim;

USE ROLE securityadmin;
GRANT USAGE ON DATABASE haven_revenue_management TO ROLE _haven_revenue_management__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_revenue_management TO ROLE _haven_revenue_management__usage;
GRANT ROLE _haven_revenue_management__usage TO ROLE _haven_revenue_management__schema;
GRANT CREATE SCHEMA ON DATABASE haven_revenue_management TO ROLE _haven_revenue_management__schema;
GRANT SELECT ON future TABLES IN DATABASE haven_revenue_management TO ROLE _haven_revenue_management__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_revenue_management TO ROLE _haven_revenue_management__usage;
GRANT SELECT ON all VIEWS IN DATABASE haven_revenue_management TO ROLE _haven_revenue_management__usage;

--DESCRIBE USER dillonsim;
--REVOKE ROLE haven_revenue_management FROM USER dillonsim;

GRANT ROLE _haven_revenue_management__usage TO ROLE haven_revenue_management;

--Current grants
--_HAVEN_BASE__SEAWARE__USAGE
--_HAVEN_REVENUE_MANAGEMENT_WAREHOUSE_XSMALL__WAREHOUSE__USAGE
--_HAVEN_REVENUE_MANAGEMENT__HAVEN_BASE__SEAWARE__READER
--_HAVEN_REVENUE_MANAGEMENT__HAVEN_STORE__MA_MART__READER
--_HAVEN_REVENUE_MANAGEMENT__HAVEN_STORE__SAS_SCV__READER
--_HAVEN_STORE__ACTIVITIES__READER
--_HAVEN_STORE__AVAILABILITY__READER
--_HAVEN_STORE__CARAVANS__READER
--_HAVEN_STORE__COMMON__READER
--_HAVEN_STORE__COMPETITOR__READER
--_HAVEN_STORE__MA_MART__USAGE
--_HAVEN_STORE__OCANDC__READER
--_HAVEN_STORE__PAYMENTS__READER
--_HAVEN_STORE__PITCH_PERFECT__READER
--_HAVEN_STORE__REVENUE_MANAGEMENT__READER
--_HAVEN_STORE__SASMART__READER
--_HAVEN_STORE__SAS_SCV__USAGE
--_HAVEN_STORE__TROOPER__READER
--_HAVEN_STORE__TRPREPRS__READER

--Revoke current grants, excluding warehouse

revoke role _HAVEN_BASE__SEAWARE__USAGE from ROLE haven_revenue_management;
revoke role _HAVEN_REVENUE_MANAGEMENT__HAVEN_BASE__SEAWARE__READER from ROLE haven_revenue_management;
revoke role _HAVEN_REVENUE_MANAGEMENT__HAVEN_STORE__MA_MART__READER from ROLE haven_revenue_management;
revoke role _HAVEN_REVENUE_MANAGEMENT__HAVEN_STORE__SAS_SCV__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__ACTIVITIES__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__AVAILABILITY__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__CARAVANS__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__COMMON__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__COMPETITOR__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__MA_MART__USAGE from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__OCANDC__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__PAYMENTS__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__PITCH_PERFECT__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__REVENUE_MANAGEMENT__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__SASMART__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__SAS_SCV__USAGE from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__TROOPER__READER from ROLE haven_revenue_management;
revoke role _HAVEN_STORE__TRPREPRS__READER from ROLE haven_revenue_management;

--Add new grants to role

grant role _HAVEN_STORE__PRICER_FORECAST__READER TO ROLE haven_revenue_management;
grant role _haven_store__retail__READER TO ROLE haven_revenue_management;
grant role _haven_base__seaware__READER TO ROLE haven_revenue_management;
grant role _haven_base__zonal__READER TO ROLE haven_revenue_management;
grant role _HAVEN_BASE__PRICER__READER TO ROLE haven_revenue_management;
grant role _haven_store__availability__READER TO ROLE haven_revenue_management;
grant role _haven_store__holiday__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__COMMON__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__PRICER__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__PRICER_FORECAST__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__ALIGN_ALYTICS__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__COMMERCIAL__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__DIGITAL__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__OCANDC__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__PITCH_PERFECT__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__TROOPER__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__TROOPER2__READER TO ROLE haven_revenue_management;

grant role _HAVEN_STORE__CARAVANS__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__PAYMENTS__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__TRPREPRS__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__ACTIVITIES__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__COMPETITOR__READER TO ROLE haven_revenue_management;
grant role _HAVEN_STORE__SASMART__READER TO ROLE haven_revenue_management;


GRANT ROLE haven_revenue_management TO ROLE haven_revenue_management_dillonsim;
GRANT ROLE _haven_revenue_management__schema TO ROLE haven_revenue_management_dillonsim; 
GRANT ROLE haven_revenue_management_dillonsim TO USER dillonsim;
GRANT ROLE haven_revenue_management TO ROLE dba;
GRANT ROLE haven_revenue_management TO USER donovanransome;


USE ROLE securityadmin;

SHOW ROLES LIKE '_haven_revenue_mana%';

--29/05/2024

USE ROLE useradmin;

--jesson.patel@bourne-leisure.co.uk
--Jesson Patel
--Head of Commercial Strategy

CREATE ROLE haven_revenue_management_JessonPatel;

create user JessonPatel
login_name = 'jesson.patel@bourne-leisure.co.uk'
display_name = 'Jesson Patel'
email = 'jesson.patel@bourne-leisure.co.uk'
comment = 'Head of Commercial Strategy'
default_role = haven_revenue_management_JessonPatel
default_warehouse = HAVEN_REVENUE_MANAGEMENT_WAREHOUSE_XSMALL;

USE ROLE securityadmin;

GRANT ROLE haven_revenue_management TO ROLE haven_revenue_management_JessonPatel;
GRANT ROLE _haven_revenue_management__schema TO ROLE haven_revenue_management_JessonPatel; 
GRANT ROLE haven_revenue_management_JessonPatel TO USER JessonPatel;

USE ROLE useradmin;

-- 02/08/2024

-- jaypanchal
-- jay.panchal@haven.com
-- Commercial Strategy Analyst


CREATE ROLE haven_revenue_management_jaypanchal;

create user jaypanchal
login_name = 'jay.panchal@haven.com'
display_name = 'Jay Panchal'
email = 'jay.panchal@haven.com'
comment = 'Commercial Strategy Analyst'
default_role = haven_revenue_management_jaypanchal
default_warehouse = HAVEN_REVENUE_MANAGEMENT_WAREHOUSE_XSMALL;

ALTER USER jaypanchal
SET display_name = 'Jay Panchal';

USE ROLE securityadmin;

GRANT ROLE haven_revenue_management TO ROLE haven_revenue_management_jaypanchal;
GRANT ROLE _haven_revenue_management__schema TO ROLE haven_revenue_management_jaypanchal; 
GRANT ROLE haven_revenue_management_jaypanchal TO USER jaypanchal;

-- 02/05/2025

use ROLE useradmin;

show roles LIKE ''