use ROLE dba;

CREATE OR replace VIEW HAVEN_STORE.PROCUREMENT.DIM_PROCUREMENT_SUPPLIER_ITEM
( PROCUREMENT_SUPPLIER_ITEM_XID, PROCUREMENT_SUPPLIER_ITEM_ID, PROCUREMENT_SUPPLIER_ITEM_CONTRACT_NUMBER, PROCUREMENT_SUPPLIER_ITEM_PART_NUM, PROCUREMENT_SUPPLIER_ITEM_MANUFACTURER, PROCUREMENT_ITEM_DESCRIPTION, PROCUREMENT_ITEM_STATE, COMPOSITE_KEY )
AS SELECT PROCUREMENT_SUPPLIER_ITEM_XID, PROCUREMENT_SUPPLIER_ITEM_ID, PROCUREMENT_SUPPLIER_ITEM_CONTRACT_NUMBER, PROCUREMENT_SUPPLIER_ITEM_PART_NUM, PROCUREMENT_SUPPLIER_ITEM_MANUFACTURER, PROCUREMENT_ITEM_DESCRIPTION, PROCUREMENT_ITEM_STATE, COMPOSITE_KEY
FROM HAVEN_STORE_UAT.PROCUREMENT.DIM_PROCUREMENT_SUPPLIER_ITEM;


CREATE VIEW HAVEN_STORE.PROCUREMENT.FCT_PROCUREMENT_INVOICE
( PROCUREMENT_INVOICE_DATE_XID, PROCUREMENT_INVOICE_CREATED_DATE_XID, PROCUREMENT_INVOICE_ATTRIBUTE_XID, PROCUREMENT_SUPPLIER_XID, PROCUREMENT_COMMODITY_XID, PROCUREMENT_USER_XID, PROCUREMENT_INVOICE_NOMINAL_XID, PROCUREMENT_SUPPLIER_ITEM_XID, PROCUREMENT_INVOICE_METADATA_XID, PROCUREMENT_INVOICE_NET_DUE_DATE_XID, INVOICE_LINE_NUMBER, INVOICE_ITEM_PRICE, ITEM_QUANTITY, ITEM_NET_VALUE, ITEM_TAX_VALUE, ITEM_GROSS_VALUE )
AS SELECT PROCUREMENT_INVOICE_DATE_XID, PROCUREMENT_INVOICE_CREATED_DATE_XID, PROCUREMENT_INVOICE_ATTRIBUTE_XID, PROCUREMENT_SUPPLIER_XID, PROCUREMENT_COMMODITY_XID, PROCUREMENT_USER_XID, PROCUREMENT_INVOICE_NOMINAL_XID, PROCUREMENT_SUPPLIER_ITEM_XID, PROCUREMENT_INVOICE_METADATA_XID, PROCUREMENT_INVOICE_NET_DUE_DATE_XID, INVOICE_LINE_NUMBER, INVOICE_ITEM_PRICE, ITEM_QUANTITY, ITEM_NET_VALUE, ITEM_TAX_VALUE, ITEM_GROSS_VALUE
FROM HAVEN_STORE_UAT.PROCUREMENT.FCT_PROCUREMENT_INVOICE;

use ROLE sysadmin;

CREATE WAREHOUSE haven_procurement_sigma_warehouse_small WITH WAREHOUSE_SIZE = 'SMALL' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';


USE ROLE useradmin;

create role _haven_procurement_sigma_warehouse_small__operator;
create role _haven_procurement_sigma_warehouse_small__usage;

CREATE ROLE haven_procurement_sigma;

create OR replace user haven_procurement_sigma_service_account
LOGIN_NAME = 'haven.procurement.sigma.service.account'
default_warehouse = haven_procurement_warehouse_small
default_role = haven_procurement_sigma
rsa_public_key = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2gB8xP+DiN00JTuTAw2T
HAiQpdqH0+ouak5VPVnHrRoWLDjJgMnhYnCS2AeOZNuXezItWOKVSSza+Xtjjwuc
aXDPa9v0UfH3BNJNbJuHdMdmtB5G4RJ2iGTsiAsWLfq3mHjDc44bTqlDnaxE8qRK
t0UvnpSLf3GoMX5d6q0ODBA2f8qNkX2PNor4sbW/QRheVE51J/7MEx+iO++Da7kx
E+Geb/TBBAHm4WoDaujyhqei/1Fe6pINsyRnCc5cyuM7j2PU1DlV181Hso0ivthB
6fCZTmrracpv7B+elLCYNUO8IYENJXt2SdKTOV1iV0U4QaVLwv/mNlhj5VI4ezDQ
iQIDAQAB';

use ROLE securityadmin;

grant usage, monitor on warehouse haven_procurement_sigma_warehouse_small to role _haven_procurement_sigma_warehouse_small__usage;
grant role _haven_procurement_sigma_warehouse_small__usage to role _haven_procurement_sigma_warehouse_small__operator;
grant operate, modify on warehouse haven_procurement_sigma_warehouse_small to role _haven_procurement_sigma_warehouse_small__operator;

GRANT ROLE _haven_procurement_sigma_warehouse_small__usage TO ROLE haven_procurement_sigma;

GRANT ROLE _haven_store__procurement__reader TO ROLE haven_procurement_sigma;
GRANT ROLE _haven_store__financial_cube__reader TO ROLE haven_procurement_sigma;

GRANT ROLE haven_procurement_sigma TO USER haven_procurement_sigma_service_account;
GRANT ROLE haven_procurement_sigma TO USER donovanransome;
GRANT ROLE haven_procurement_sigma TO ROLE dba;

use ROLE haven_procurement_sigma;

use DATABASE haven_store;

show schemas;

show warehouses;

-- 29/04/2025

use ROLE dba;

CREATE VIEW HAVEN_STORE.PROCUREMENT.DIM_PROCUREMENT_INVOICE_ATTRIBUTE
( PROCUREMENT_INVOICE_ATTRIBUTE_XID, PROCUREMENT_INVOICE_STATUS, PROCURMENT_INVOICE_LINE_STATUS, DATA_SOURCE )
AS SELECT PROCUREMENT_INVOICE_ATTRIBUTE_XID, PROCUREMENT_INVOICE_STATUS, PROCURMENT_INVOICE_LINE_STATUS, DATA_SOURCE
FROM HAVEN_STORE_UAT.PROCUREMENT.DIM_PROCUREMENT_INVOICE_ATTRIBUTE;

CREATE VIEW HAVEN_STORE.PROCUREMENT.DIM_PROCUREMENT_INVOICE_COMMODITY
( PROCUREMENT_COMMODITY_XID, COMMODITY_LEVEL_1, COMMODITY_LEVEL_2, COMMODITY_LEVEL_3, COMMODITY_LEVEL_4, COMMODITY_LEVEL_LOWEST )
AS SELECT PROCUREMENT_COMMODITY_XID, COMMODITY_LEVEL_1, COMMODITY_LEVEL_2, COMMODITY_LEVEL_3, COMMODITY_LEVEL_4, COMMODITY_LEVEL_LOWEST
FROM HAVEN_STORE_UAT.PROCUREMENT.DIM_PROCUREMENT_INVOICE_COMMODITY;

CREATE VIEW HAVEN_STORE.PROCUREMENT.DIM_PROCUREMENT_INVOICE_METADATA
( NPROCUREMENT_INVOICE_METADATA_XID, PROCUREMENT_INVOICE_NUMBER, PROCUREMENT_INVOICE_ID, PO_NUMBER, PO_NUMBER_STATE )
AS SELECT PROCUREMENT_INVOICE_METADATA_XID, PROCUREMENT_INVOICE_NUMBER, PROCUREMENT_INVOICE_ID, PO_NUMBER, PO_NUMBER_STATE
FROM HAVEN_STORE_UAT.PROCUREMENT.DIM_PROCUREMENT_INVOICE_METADATA;

CREATE VIEW HAVEN_STORE.PROCUREMENT.DIM_PROCUREMENT_SUPPLIER
( MPROCUREMENT_SUPPLIER_XID, PROCUREMENT_SUPPLIER_NUMBER, PROCUREMENT_SUPPLIER_NAME )
AS SELECT PROCUREMENT_SUPPLIER_XID, PROCUREMENT_SUPPLIER_NUMBER, PROCUREMENT_SUPPLIER_NAME
FROM HAVEN_STORE_UAT.PROCUREMENT.DIM_PROCUREMENT_SUPPLIER;

CREATE VIEW HAVEN_STORE.PROCUREMENT.DIM_PROCUREMENT_USER
( PROCUREMENT_USER_XID, PROCUREMENT_USER_NAME, PROCUREMENT_USER_EMAIL )
AS SELECT PROCUREMENT_USER_XID, PROCUREMENT_USER_NAME, PROCUREMENT_USER_EMAIL
FROM HAVEN_STORE_UAT.PROCUREMENT.DIM_PROCUREMENT_USER;


use ROLE haven_procurement_sigma;

use DATABASE haven_store;

show schemas;

show warehouses;

USE SCHEMA PROCUREMENT;

SHOW VIEWS;

use SCHEMA haven_store.finance_cube_erpx; 


show views; 

-- 29/04/2025

use ROLE securityadmin;

REVOKE ROLE _haven_store__financial_cube__reader FROM ROLE haven_procurement_sigma;
GRANT ROLE _haven_store__finance_cube_erpx__reader TO  ROLE haven_procurement_sigma;

-- 30/04/2025

use role useradmin;

CREATE ROLE _haven_procurement_sigma__haven_store__common__reader;

use ROLE securityadmin;

GRANT ROLE _haven_store__common__usage TO ROLE _haven_procurement_sigma__haven_store__common__reader;
GRANT SELECT ON TABLE haven_store.common.dim_calendar TO ROLE _haven_procurement_sigma__haven_store__common__reader;

GRANT ROLE _haven_procurement_sigma__haven_store__common__reader TO ROLE haven_procurement_sigma;

use ROLE haven_procurement_sigma;

use SCHEMA haven_store.common;

show tables;
 	
show grants TO ROLE _HAVEN_PROCUREMENT_SIGMA__HAVEN_STORE__COMMON__READER;
show grants TO ROLE HAVEN_PROCUREMENT_SIGMA;

-- 14/05/2025

use ROLE securityadmin;

GRANT SELECT ON TABLE haven_store.common.dim_park TO ROLE _haven_procurement_sigma__haven_store__common__reader;
