use ROLE dba;

use SCHEMA haven_base.dig_aac_onparkwifi;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI.ANPR
( ID, LICENSE_PLATE, MAC_ADDRESS, CHANNEL_ID, DATE_TIME, EVENT_TYPE, COUNTRY, LANE, DIRECTION, CONFIDENCE_LEVEL, DETECTION_PICTURE, VEHICLE_PICTURE, LICENSE_PLATE_PICTURE, CREATED_AT, UPDATED_AT )
AS SELECT ID, LICENSE_PLATE, MAC_ADDRESS, CHANNEL_ID, DATE_TIME, EVENT_TYPE, COUNTRY, LANE, DIRECTION, CONFIDENCE_LEVEL, DETECTION_PICTURE, VEHICLE_PICTURE, LICENSE_PLATE_PICTURE, CREATED_AT, UPDATED_AT
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI.ANPR;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI.AUDIT_LOG
( ID, LOG_TYPE, ENTRY_ID, ENTRY_TYPE, DIFF, USER_NAME, USER_ID, CREATED_AT, UPDATED_AT, DELETED_AT )
AS SELECT ID, LOG_TYPE, ENTRY_ID, ENTRY_TYPE, DIFF, USER_NAME, USER_ID, CREATED_AT, UPDATED_AT, DELETED_AT
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI.AUDIT_LOG;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI.CONFIGURATION
( ID, ORDER_ID, PASSWORD, STATUS, DEVICE_PITCH_ID, START_DATE, END_DATE, CREATED_AT, UPDATED_AT, DELETED_AT )
AS SELECT ID, ORDER_ID, PASSWORD, STATUS, DEVICE_PITCH_ID, START_DATE, END_DATE, CREATED_AT, UPDATED_AT, DELETED_AT
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI.CONFIGURATION;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI.DEVICE
( ID, MAC_ADDRESS, ICCID, STATUS, MODEL, CREATED_AT, UPDATED_AT, DELETED_AT, LAST_PING, LOCATION, LAST_PING_SUCCESSFUL, LAST_PROVISION )
AS SELECT ID, MAC_ADDRESS, ICCID, STATUS, MODEL, CREATED_AT, UPDATED_AT, DELETED_AT, LAST_PING, LOCATION, LAST_PING_SUCCESSFUL, LAST_PROVISION
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI.DEVICE;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI.DEVICE_PITCH
( ID, DEVICE_ID, PITCH_ID, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, NOTES )
AS SELECT ID, DEVICE_ID, PITCH_ID, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, NOTES
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI.DEVICE_PITCH;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI."ORDER"
( ID, HOLIDAY_REFERENCE_ID, PACKAGE_ID, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, HOLIDAY_START_DATE, HOLIDAY_END_DATE, EMAIL_ADDRESS, FIRST_NAME, LAST_NAME )
AS SELECT ID, HOLIDAY_REFERENCE_ID, PACKAGE_ID, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, HOLIDAY_START_DATE, HOLIDAY_END_DATE, EMAIL_ADDRESS, FIRST_NAME, LAST_NAME
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI."ORDER";

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI."PACKAGE"
( ID, DURATION, PRICE, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, NAME, NET_VALUE, VAT, VISIBLE, "TYPE" )
AS SELECT ID, DURATION, PRICE, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, NAME, NET_VALUE, VAT, VISIBLE, "TYPE"
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI."PACKAGE";

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI.PAYMENT
( ID, ORDER_ID, TRANSACTION_ID, PAYLOAD, PAYMENT_PROVIDER, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, AMOUNT )
AS SELECT ID, ORDER_ID, TRANSACTION_ID, PAYLOAD, PAYMENT_PROVIDER, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, AMOUNT
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI.PAYMENT;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI.PITCH
( ID, CODE, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, PARK_CODE, OWNER_PASSWORD, NAME, "TYPE" )
AS SELECT ID, CODE, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, PARK_CODE, OWNER_PASSWORD, NAME, "TYPE"
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI.PITCH;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_AAC_ONPARKWIFI.REFUND
( ID, PAYMENT_ID, TRANSACTION_ID, PAYLOAD, PAYMENT_PROVIDER, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, AMOUNT )
AS SELECT ID, PAYMENT_ID, TRANSACTION_ID, PAYLOAD, PAYMENT_PROVIDER, STATUS, CREATED_AT, UPDATED_AT, DELETED_AT, AMOUNT
FROM HAVEN_RAW.DIG_AAC_ONPARKWIFI.REFUND;

use ROLE securityadmin;

GRANT ROLE _haven_base__dig_aac_onparkwifi__reader TO ROLE haven_commercial;

REVOKE ROLE _haven_base__dig_aac_onparkwifi_etleap__reader TO ROLE haven_commercial;