USE ROLE sysadmin;

CREATE WAREHOUSE haven_dbt_transform_rms_core_warehouse_xsmall WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE haven_dbt_transform_rms_core_warehouse_medium WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

use ROLE useradmin;

CREATE ROLE haven_dbt_transform_rms_core;

create role _haven_dbt_transform_rms_core_warehouse_xsmall__operator;
create role _haven_dbt_transform_rms_core_warehouse_xsmall__usage;

create role _haven_dbt_transform_rms_core_warehouse_medium__operator;
create role _haven_dbt_transform_rms_core_warehouse_medium__usage;

--CREATE special access roles

--CREATE ROLE _haven_dbt_transform_rms_core__HAVEN_STORE__COMMON__READER;
--CREATE ROLE _haven_dbt_transform_rms_core__HAVEN_STORE__PERFORMANCE_MARKETING__READER;
--CREATE ROLE _haven_dbt_transform_rms_core__HAVEN_BASE__HIT_ADMIN__READER;

use ROLE securityadmin;

grant usage, monitor on warehouse haven_dbt_transform_rms_core_warehouse_xsmall to role _haven_dbt_transform_rms_core_warehouse_xsmall__usage;
grant role _haven_dbt_transform_rms_core_warehouse_xsmall__usage to role _haven_dbt_transform_rms_core_warehouse_xsmall__operator;
grant operate, modify on warehouse haven_dbt_transform_rms_core_warehouse_xsmall to role _haven_dbt_transform_rms_core_warehouse_xsmall__operator;

grant usage, monitor on warehouse haven_dbt_transform_rms_core_warehouse_medium to role _haven_dbt_transform_rms_core_warehouse_medium__usage;
grant role _haven_dbt_transform_rms_core_warehouse_medium__usage to role _haven_dbt_transform_rms_core_warehouse_medium__operator;
grant operate, modify on warehouse haven_dbt_transform_rms_core_warehouse_medium to role _haven_dbt_transform_rms_core_warehouse_medium__operator;

GRANT ROLE _haven_dbt_transform_rms_core_warehouse_xsmall__usage TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _haven_dbt_transform_rms_core_warehouse_medium__usage TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;

GRANT ROLE _HAVEN_BASE__AMPLITUDE__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_BASE__BIGQUERY__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_BASE__BLUEYONDER__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_BASE__CYHH__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_BASE__DREAM__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_BASE__PLOT__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_BASE__PRICER__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_BASE__SEAWARE__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_BASE__ZONAL__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;

--GRANT ROLE _HAVEN_PIPELINE__BLUEYONDER__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
--revoke ROLE _HAVEN_PIPELINE__BLUEYONDER__READER from ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
--GRANT ROLE _HAVEN_PIPELINE_UAT__BLUEYONDER__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;

GRANT ROLE _HAVEN_PIPELINE__BLUEYONDER__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_PIPELINE__PX0007_PITCH_PERFECT__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__ACTIVITIES__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__ALIGN_ALYTICS__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__AVAILABILITY__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__CARAVANS__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__CARAVAN_SALES_PRICING_APPLICATION__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__CARAVAN_SALES__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__COMMERCIAL__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__COMMON__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__COMPETITOR__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__DIGITAL__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__FINANCIAL_CUBE__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__HOLIDAY__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__MA_MART__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__OCANDC__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__PAYMENTS__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__PITCH_PERFECT__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__PRICER_DECISION_MATRIX__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__PRICER_FORECAST__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__PRICER__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__PROSPECTS__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__RETAIL__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__REVENUE_MANAGEMENT_REPORTING__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__SASMART__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__SAS_SCV__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__SURVEY__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__TROOPER2__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__TROOPER__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _HAVEN_STORE__TRPREPRS__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;


--GRANT ROLE _haven_store__common__usage TO ROLE _haven_dbt_transform_rms_core__HAVEN_STORE__COMMON__READER;
--GRANT select ON TABLE HAVEN_STORE.COMMON.DIM_PARK TO ROLE _haven_dbt_transform_rms_core__HAVEN_STORE__COMMON__READER;
grant ROLE _haven_dbt_transform_rms_core__HAVEN_STORE__COMMON__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;

--GRANT ROLE _haven_store__performance_marketing__usage TO ROLE _haven_dbt_transform_rms_core__HAVEN_STORE__PERFORMANCE_MARKETING__READER;
--GRANT SELECT ON TABLE HAVEN_STORE.PERFORMANCE_MARKETING.DIM_BLOOMREACH_CUSTOMER TO ROLE _haven_dbt_transform_rms_core__HAVEN_STORE__PERFORMANCE_MARKETING__READER;
grant ROLE _haven_dbt_transform_rms_core__HAVEN_STORE__PERFORMANCE_MARKETING__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;

--GRANT ROLE _HAVEN_BASE__HIT_ADMIN__USAGE TO ROLE _haven_dbt_transform_rms_core__HAVEN_BASE__HIT_ADMIN__READER;
--GRANT SELECT ON view HAVEN_BASE.HIT_ADMIN.VRES_CYHH_PITCH_COST TO ROLE _haven_dbt_transform_rms_core__HAVEN_BASE__HIT_ADMIN__READER;
grant ROLE _haven_dbt_transform_rms_core__HAVEN_BASE__HIT_ADMIN__READER TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;

grant ROLE HAVEN_DBT_TRANSFORM_RMS_CORE TO USER haven_dbt_transform;

grant role _haven_store__pricer_decision_matrix__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_staging__pricer_decision_matrix_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;

grant role _haven_pipeline__cyhh_pricing_pilot__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_staging__cyhh_pricing_pilot_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__cyhh_pricing_pilot_reporting__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_staging__decision_matrix_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__flex_calculator__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_staging__flex_calculator_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;

grant role _haven_pipeline__Employees_Member_Benefit__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_staging__Employees_Member_Benefit_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__Caravan_sales_Pricing_application__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_staging__caravan_sales_pricing_application_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__part_exchange_model__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_staging__part_exchange_model_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__decision_matrix_reporting__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_staging__decision_matrix_reporting_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__rms_shared_resources__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;

GRANT ROLE _haven_store__schema TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _haven_staging__schema TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;
GRANT ROLE _haven_pipeline__schema TO ROLE HAVEN_DBT_TRANSFORM_RMS_CORE;





-- below are either wrong, not needed, or need to be created properly;


grant role _haven_staging__pricer_decision_matrix__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__cyhh_pricing_pilot__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__cyhh_pricing_pilot_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__cyhh_pricing_pilot_reporting__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__decision_matrix_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__flex_calculator__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__flex_calculator_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__emb__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__emb_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__staff_pricing__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__staff_pricing_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__Caravan_Pricing__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__caravan_sales_pricing_app_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__pex_model__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__pex_model_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__decision_matrix_reporting_staging__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__decision_matrix_reporting__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;
grant role _haven_store__rms_shared_resources__creator to role HAVEN_DBT_TRANSFORM_RMS_CORE;

grant role HAVEN_DBT_TRANSFORM_RMS_CORE to user haven_dbt_transform;