use ROLE dba;

use SCHEMA haven_base.IDENTITY;

show views;

CREATE VIEW HAVEN_BASE.IDENTITY.HID_TO_ADDRESS
( ID, HID, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_CITY, ADDRESS_COUNTY, ADDRESS_POSTCODE, ADDRESS_COUNTRY, ADDRESS_EFFECTIVE_FROM )
AS SELECT ID, HID, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_CITY, ADDRESS_COUNTY, ADDRESS_POSTCODE, ADDRESS_COUNTRY, ADDRESS_EFFECTIVE_FROM
FROM HAVEN_RAW.IDENTITY_ETLEAP.HID_TO_ADDRESS;

USE ROLE HAVEN_ETLEAP_DATALOAD;

use SCHEMA haven_RAW.IDENTITY_ETLEAP;

SHOW TABLES;

DROP TABLE hid_to_address;