
USE ROLE HAVEN_DBT_TRANSFORM_ALIGN_ALYTICS_DEV;

USE SCHEMA HAVEN_STAGING_AA_DEV.RM_STAGING;


create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_BOOKING_ADDON_AUDIT(
	PURCHASE_DATE,
	CANCEL_DATE,
	BOOKING_ID,
	ADDON_CODE,
	ADDON_VALUE,
	UNIQUE_BK_ID
) as (
    SELECT
    PURCHASE_DATE::DATE AS PURCHASE_DATE
    ,CANCEL_DATE::DATE AS CANCEL_DATE
    ,BOOKING_ID
    ,ADDON_CODE
    -- ,ADDON
    ,ADDON_VALUE
    -- ,GROUP_BOOKING_ID
    -- ,CONCAT(BOOKING_ID, CASE WHEN GROUP_BOOKING_ID IS NULL then '' ELSE CONCAT('-', GROUP_BOOKING_ID) END) AS UNIQUE_BK_ID
    ,CAST(BOOKING_ID AS STRING) AS UNIQUE_BK_ID
    -- ,CURRENT_BOOKING_STATUS
FROM
    HAVEN_STORE.holiday.fct_holiday_addons 
WHERE
    SNAPSHOT_DATE = CURRENT_DATE
    -- START_DATE >= '2018-01-01'::date
    AND ADDON_CODE='CYHH'
    -- AND END_DATE::DATE='9999-12-31'
QUALIFY
    ROW_NUMBER() OVER (PARTITION BY BOOKING_ID ORDER BY PURCHASE_DATE::DATE DESC) = 1
  )
  
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_BREAK_MAPPING_OVERRIDE(
	PARK_CODE,
	BREAK_DATE,
	MAPPED_PARK_CODE,
	MAPPED_BREAK_DATE,
	SCALING_FACTOR
) as (
    SELECT
*
FROM HAVEN_MASTER.REVENUE_MANAGEMENT_STORAGE.break_mapping_override_v3
)
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_BREAK_TARGET_PROCESS_CONTROL_HEADER(
	VERSION_ID,
	RUN_DATE,
	BREAK_SEGMENTATION_LOOKUP_VERSION_ID
) as (
    with c_prod_version as (
    select
        break_targets_version_id as prod_version
    from
        HAVEN_STORE.pricer.deploy_break_version 
    qualify row_number() over(order by run_date desc) = 1
),
final as (
    select
        aa.version_id,
        aa.run_date,
        cast(aa.properties['break_segmentation_lookup_version_id'] as integer) as break_segmentation_lookup_version_id
    from
        HAVEN_STORE.pricer.process_control_header aa
        inner join c_prod_version bb on aa.version_id = bb.prod_version
)
select * from final
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_BREAK_SEGMENTATION_LOOKUP_HISTORY(
	BREAK_DATE,
	BREAK_DAY,
	SHIP_CODE,
	BREAK_TYPE,
	SEGMENT_SEASON,
	SEGMENT_BREAK,
	SEGMENT_GROUP,
	TARGET_FILL_BREAK_SEGMENT
) as (
    WITH seg1 AS (
SELECT
     BREAKID::DATE as BREAK_DATE
    ,DAYNAME(BREAKID) as BREAK_DAY
    ,SHIP_CODE -- OCC CODE (DIFFERENT TO HAVEN CODE)
    ,BREAK_TYPE
    ,NULLIF(SPLIT_PART(TARGET_FILL_BREAK_SEGMENT, '|', 1),'') AS SEGMENT_SEASON
    ,NULLIF(SPLIT_PART(TARGET_FILL_BREAK_SEGMENT, '|', 2),'') AS SEGMENT_BREAK
    ,NULLIF(SPLIT_PART(TARGET_FILL_BREAK_SEGMENT, '|', 3),'') AS SEGMENT_GROUP
    ,TARGET_FILL_BREAK_SEGMENT
FROM
    HAVEN_STORE.pricer.break_segmentation_lookup_history a
INNER JOIN 
    HAVEN_STAGING_AA_DEV.RM_STAGING.s0_break_target_process_control_header pch 
    ON pch.break_segmentation_lookup_version_id = a.DATA_VERSION_ID
)
,seg2 as (
SELECT
     BREAKID::DATE as BREAK_DATE
    ,DAYNAME(BREAKID) as BREAK_DAY
    ,SHIP_CODE 
    ,BREAK_TYPE
    ,NULLIF(SPLIT_PART(TARGET_FILL_BREAK_SEGMENT, '|', 1),'') AS SEGMENT_SEASON
    ,NULLIF(SPLIT_PART(TARGET_FILL_BREAK_SEGMENT, '|', 2),'') AS SEGMENT_BREAK
    ,NULLIF(SPLIT_PART(TARGET_FILL_BREAK_SEGMENT, '|', 3),'') AS SEGMENT_GROUP
    ,TARGET_FILL_BREAK_SEGMENT
FROM
  HAVEN_MASTER.REVENUE_MANAGEMENT_STORAGE.break_segmentation_legacy_v1
WHERE 
    DATA_VERSION_ID = 1
    AND BREAK_DATE < (Select MIN(BREAK_DATE) FROM seg1)
)
, seg_union AS 
(
Select * from  seg1
UNION ALL 
Select * from  seg2
)
Select * 
FROM 
seg_union
  )
  ;


create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_COVID_REBOOKINGS(
	REBOOKED_RES_ID,
	CANCELLATION_CASE,
	COVID_FLAG,
	COVID_FLAG_2,
	RECORD_COUNT
) as (
    Select 
     REBOOKED_RES_ID
    ,ANY_VALUE(CANCELLATION_CASE) AS CANCELLATION_CASE
    ,MAX(CASE WHEN REASON_IS_CORONA = 'Y' THEN 1 ELSE 0 END) AS COVID_FLAG
    ,MAX(CASE 
            WHEN CANCELLATION_CASE IN ('Coronavirus' , 'Covid 19 Auo Cancellation', 'Covid ALL', 'CV19 Guarantee', 'Transfer to Client Bank-COVID')
            THEN 1 ELSE 0 END
        ) AS COVID_FLAG_2

    ,SUM(1) AS RECORD_COUNT
FROM
HAVEN_STORE.trooper.cancellations_currentseason
WHERE  True
-- AND REBOOKED_RES_ID = 12906387
AND REBOOKED = 'Y'
GROUP BY 
    REBOOKED_RES_ID
  );

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_DECISION_MATRIX(
	PARK,
	PRODUCT,
	BREAK_DATE,
	DURATION,
	TARGET_OCC,
	CURR_OCC,
	REQUIRED_ROS,
	CURR_ROS,
	TOTAL_TARGET_OCC,
	FORECAST,
	DTA,
	WTA,
	LEAD_TIME_SEGMENT,
	OCCDIFFP,
	ROSDIFFP,
	DECISION_QUADRANT,
	DECISION_SEGMENT,
	DECMRULEID,
	ACTION,
	ACTION_FORECAST_CONST,
	ACTION_PCT,
	ACTION_SPECIAL,
	AUTO_APPROVAL,
	DAYS_TO_WAIT,
	SEGMENT,
	ROS_USED,
	WAIT_DAYS,
	LAST_PRICE_CHANGE_DATE,
	TARGET_CURRENT_SILVER_PRICE,
	DAYSSINCEPRCCHG,
	CURRENT_PRICE,
	MIN_PRICE,
	MAX_PRICE,
	ACTION_NAME,
	PROPOSED_BRO2_PRICE,
	EXPPRICE,
	PRICE_CHANGE_LABEL,
	UPLOAD_DATE
) as (
    SELECT
      *
FROM
     HAVEN_STORE.pricer_decision_matrix.pricer_decision_matrix_output
  );

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_DECISION_MATRIX_BLOCKERS(
	PARK,
	PRODUCT,
	BREAK_DATE,
	DURATION,
	TARGET_OCC,
	CURR_OCC,
	REQUIRED_ROS,
	CURR_ROS,
	TOTAL_TARGET_OCC,
	FORECAST,
	DTA,
	WTA,
	LEAD_TIME_SEGMENT,
	OCCDIFFP,
	ROSDIFFP,
	DECISION_QUADRANT,
	DECISION_SEGMENT,
	DECMRULEID,
	ACTION,
	ACTION_FORECAST_CONST,
	ACTION_PCT,
	ACTION_SPECIAL,
	AUTO_APPROVAL,
	DAYS_TO_WAIT,
	SEGMENT,
	ROS_USED,
	WAIT_DAYS,
	LAST_PRICE_CHANGE_DATE,
	TARGET_CURRENT_SILVER_PRICE,
	DAYSSINCEPRCCHG,
	CURRENT_PRICE,
	MIN_PRICE,
	MAX_PRICE,
	ACTION_NAME,
	PROPOSED_BRO2_PRICE,
	EXPPRICE,
	PRICE_CHANGE_LABEL,
	UPLOAD_DATE,
	ROS_ALGO_ACTION,
	BLOCKED_WAIT_DAYS,
	BLOCKED_FORECAST,
	BLOCKED_MIN,
	BLOCKED_MAX,
	BREAK_PRICE_ACTION_DESCRIPTION
) as (
    --Dependancy for pricer update
--HAVEN_STORE.pricer_decision_matrix.pricer_decision_matrix_output 

SELECT
      *
FROM
     HAVEN_STORE.pricer_decision_matrix.pricer_decision_matrix_blockers
  )
;  


create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_DECISION_MATRIX_HIST(
	PARK,
	PRODUCT,
	BREAK_DATE,
	DURATION,
	TARGET_OCC,
	CURR_OCC,
	REQUIRED_ROS,
	CURR_ROS,
	TOTAL_TARGET_OCC,
	FORECAST,
	DTA,
	WTA,
	LEAD_TIME_SEGMENT,
	OCCDIFFP,
	ROSDIFFP,
	DECISION_QUADRANT,
	DECISION_SEGMENT,
	DECMRULEID,
	ACTION,
	ACTION_FORECAST_CONST,
	ACTION_PCT,
	ACTION_SPECIAL,
	AUTO_APPROVAL,
	DAYS_TO_WAIT,
	SEGMENT,
	ROS_USED,
	WAIT_DAYS,
	LAST_PRICE_CHANGE_DATE,
	TARGET_CURRENT_SILVER_PRICE,
	DAYSSINCEPRCCHG,
	CURRENT_PRICE,
	MIN_PRICE,
	MAX_PRICE,
	ACTION_NAME,
	PROPOSED_BRO2_PRICE,
	EXPPRICE,
	PRICE_CHANGE_LABEL,
	UPLOAD_DATE
) as (
    SELECT
      *
FROM
     HAVEN_STORE.pricer_decision_matrix.pricer_decision_matrix_hist
  );

  create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_DECISION_MATRIX_OUTPUT(
	PARK,
	PRODUCT,
	BREAK_DATE,
	DURATION,
	TARGET_OCC,
	CURR_OCC,
	REQUIRED_ROS,
	CURR_ROS,
	TOTAL_TARGET_OCC,
	FORECAST,
	DTA,
	WTA,
	LEAD_TIME_SEGMENT,
	OCCDIFFP,
	ROSDIFFP,
	DECISION_QUADRANT,
	DECISION_SEGMENT,
	DECMRULEID,
	ACTION,
	ACTION_FORECAST_CONST,
	ACTION_PCT,
	ACTION_SPECIAL,
	AUTO_APPROVAL,
	DAYS_TO_WAIT,
	SEGMENT,
	ROS_USED,
	WAIT_DAYS,
	LAST_PRICE_CHANGE_DATE,
	TARGET_CURRENT_SILVER_PRICE,
	DAYSSINCEPRCCHG,
	CURRENT_PRICE,
	MIN_PRICE,
	MAX_PRICE,
	ACTION_NAME,
	PROPOSED_BRO2_PRICE,
	EXPPRICE,
	PRICE_CHANGE_LABEL,
	UPLOAD_DATE
) as (
    SELECT
      *
FROM
     HAVEN_STORE.pricer_decision_matrix.pricer_decision_matrix_output
  );

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_DIM_PARK(
	PARK_CODE,
	PARK_NAME,
	PARK_REGION,
	DIRECTOR_NAME,
	DIRECTOR_REGION,
	PARK_CLUSTER_CODE,
	PARK_CLUSTER_NAME
) as (
    SELECT
     PARK_CODE
    ,PARK_NAME
    ,CARAVAN_SALES_REGION_NAME AS PARK_REGION
    ,DIRECTOR_NAME
    ,DIRECTOR_REGION
    ,PARK_CLUSTER_CODE
    ,PARK_CLUSTER_NAME
FROM
    HAVEN_STORE.common.dim_park
  );


  create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_DMS_FORECAST_HISTORY_STAYID(
	RUN_ID,
	MASTER_VERSION_ID,
	MASTER_VERSION_LABEL,
	MASTER_VERSION_DESC,
	PROPERTIES,
	RUN_DATE,
	MASTER_FORECAST_DATE,
	FORECAST_DATE,
	FORECAST_TIME_TO_OCCUPANCY,
	ISCURRENT,
	ISBASELINE,
	STAY_ID,
	PARK_CODE,
	STAY_DATE,
	UPLIFT_FACTOR,
	AUTOMATIC_UPLIFT_MODEL,
	MANUAL_UPLIFT_FACTOR,
	BASELINE_UNIT_FCS_FN_GRO_UNCN,
	BASELINE_UNIT_FCS_DL_GRO_UNCN,
	BASELINE_UNIT_FCS_TD_GRO_UNCN,
	PACE_ADJUSTMENT_FACTOR,
	ROSW_VALID_FLAG,
	DAYS_ROSW,
	UNIT_ACT_FN_GRO_CONS_EXCGROUP_ROSW,
	UNIT_FCS_DL_GRO_UNCN_ROSW,
	UNIT_FCS_FN_GRO_UNCN,
	UNIT_FCS_DL_GRO_UNCN,
	DMS_UNIT_FCS_FN_GRO_UNCN,
	BASE_PICKUP_ADJUSTMENT,
	PACE_PICKUP_ADJUSTMENT,
	UNPF_ARR_FN_GRO_UNCN,
	UNPF_RMSERR_GRO_UNCN,
	UNIT_ACT_FN_GRO_CONS,
	SPILL1,
	UNIT_ACT_FN_GRO_UNCN,
	DMS_UNIT_ACT_FN_GRO_UNCN,
	MAPPED_STAY_DATE,
	MAPPED_UNIT_ACT_FN_GRO_UNCN,
	MAPPED_UNIT_ACT_FN_GRO_CONS,
	UNIT_FCS_DL_CRD_CONS,
	UNIT_FCS_DL_CUD_UNCN,
	UNIT_FCS_DL_CAN_UNCN,
	UNIT_FCS_FN_CAN_UNCN,
	UNIT_FCS_FN_NET_UNCN,
	UNPC_FCS_FN_CAN_UNCN,
	UNIT_ACT_FN_CAN_CONS,
	UNIT_ACT_FN_CAN_UNCN,
	UNIT_ACT_FN_NET_CONS,
	UNIT_ACT_FN_NET_UNCN,
	UNPC_ACT_FN_CAN_CONS,
	UNPC_NRR_FN_CAN_CONS,
	UNPC_ARR_FN_CAN_CONS,
	SALEABLE_CAPACITY_CURRENT,
	UNIT_FCS_FN_NET_CONS,
	CONFIDENCE_BAND,
	MAPPED_PARK_CODE
) as (
    SELECT
 *
FROM
    HAVEN_STAGING.REVENUE_MANAGEMENT_OUTPUT.DMS_FORECAST_HISTORY_STAYID
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_GRADE_MAPPING(
	PARK_CODE,
	OLD_GRADE,
	NEW_GRADE
) as (
    SELECT
     PARK_CODE
    ,GRADE_CODE AS OLD_GRADE 
    ,NEW_GRADE_CODE AS NEW_GRADE
FROM
    HAVEN_STORE.common.grade_mapping
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_GRADE_PRICE_HISTORY(
	SNAPSHOT_DATE,
	INTEGRATION,
	PARK_CODE,
	ARRIVAL_DATE,
	GRADE_CODE,
	GRADE_CODE_MAPPED,
	DURATION,
	PACKAGE_TYPE,
	PACKAGE_ID,
	PACKAGE_TYPE_MAPPED,
	PRICE,
	CABIN_CATEGORY_DESCRIPTION,
	INTEGRATION_DATE
) as (
    SELECT
     SNAPSHOT_TIMESTAMP AS SNAPSHOT_DATE
    ,INTEGRATION_TIMESTAMP as INTEGRATION
    ,TRIM(SHIP_CODE) AS PARK_CODE
    ,ARRIVAL_DATE::DATE AS ARRIVAL_DATE
    ,TRIM(GRADE) AS GRADE_CODE
    ,CASE
        WHEN EXTRACT(YEAR FROM ARRIVAL_DATE)<2022 AND TRIM(GRADE)='SI2'
        THEN 'BRO2'
        ELSE TRIM(GRADE)
     END AS GRADE_CODE_MAPPED
    ,DURATION
    ,PACKAGE_TYPE
    ,PACKAGE_ID
    /*,CASE
        WHEN EXTRACT(YEAR FROM ARRIVAL_DATE)<2022 AND PACKAGE_TYPE LIKE '%STAY+PLAY%' 
        THEN REPLACE(PACKAGE_TYPE,'STAY+PLAY','HAVEN HOLIDAY')
        WHEN EXTRACT(YEAR FROM ARRIVAL_DATE)<2022 AND PACKAGE_TYPE LIKE '%STAY%' 
        THEN REPLACE(PACKAGE_TYPE,'STAY','HIDEAWAY')
        ELSE PACKAGE_TYPE
     END AS PACKAGE_TYPE_MAPPED*/
    ,REPLACE(REPLACE(PACKAGE_TYPE,'STAY+PLAY','HAVEN HOLIDAY'),'STAY','HIDEAWAY') AS PACKAGE_TYPE_MAPPED 
    ,AMOUNT_TOTAL AS PRICE
    ,CABIN_CATEGORY_DESCRIPTION
    ,DATE(INTEGRATION_TIMESTAMP) AS INTEGRATION_DATE
    -- Logic changes to deduplicate within Snapshot (this is the the date the snapshot from Pricer was taken.  Integration Date is time integrated into DWH)
    -- The last integration for the snapshot should show us the last registered price on that snapshot date
    --,ROW_NUMBER() OVER(PARTITION BY SHIP_CODE, ARRIVAL_DATE, GRADE, PACKAGE_TYPE, DURATION, SNAPSHOT_TIMESTAMP ORDER BY INTEGRATION_TIMESTAMP DESC) AS SNAPSHOT_DEDUP
FROM
    HAVEN_STORE.availability.grade_price_history

WHERE
    ARRIVAL_DATE >= '2018-01-01'::date
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_INVENTORY_AVAILABILITY_HISTORY(
	STAY_DATE,
	PARK_CODE,
	GRADE_CODE,
	PRODUCT_TYPE,
	PITCHES,
	HELD,
	FIRM,
	AVAILABLE,
	INTEGRATION,
	INTEGRATION_DATE,
	SNAPSHOT_DATE
) as (
    SELECT
     DEPARTURE_DATE::DATE AS STAY_DATE
    ,PARK_CODE
    ,GRADE_CODE
    ,PRODUCT_TYPE
    ,PITCHES
    ,HELD
    ,FIRM
    ,AVAILABLE
    ,INTEGRATION_TIMESTAMP as INTEGRATION
    ,INTEGRATION_TIMESTAMP::DATE AS INTEGRATION_DATE
    ,SNAPSHOT_TIMESTAMP::DATE AS SNAPSHOT_DATE
    -- Logic changed to reflect that snapshot date is date of Plot snapshot.  We take the latest integration assuming that where there are multiple these are corrections
    --,ROW_NUMBER() OVER(PARTITION BY DEPARTURE_DATE, PARK_CODE, GRADE_CODE, SNAPSHOT_DATE ORDER BY INTEGRATION DESC) AS SNAPSHOT_DEDUP
FROM
    HAVEN_STORE.availability.inventory_availability_history

WHERE
    DEPARTURE_DATE >= '2018-01-01'::date
    AND PRODUCT_TYPE <> 'TOURING'
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_OCC_AGG_TARGETS(
	SOURCE,
	BREAK_DATE,
	RESORT,
	LEAD_TIME_DAY,
	ACTUAL_DATE,
	DAILY_TARGET_NET_ROS,
	DAILY_TARGET_GROSS_ROS,
	DAILY_TARGET_NET_ADDONS,
	DAILY_TARGET_NET_DINING,
	DAILY_TARGET_COMPOSITE_PRICE,
	DAILY_TARGET_NET_RICHCORE,
	DAILY_TARGET_SILVER_PRICE,
	CUMULATIVE_TARGET_NET_ADDONS,
	LAST7_DAY_TARGET_NET_ADDONS,
	LAST14_DAY_TARGET_NET_ADDONS,
	LAST28_DAY_TARGET_NET_ADDONS,
	NEXT7_DAY_TARGET_NET_ADDONS,
	NEXT14_DAY_TARGET_NET_ADDONS,
	NEXT28_DAY_TARGET_NET_ADDONS,
	CUMULATIVE_TARGET_NET_DINING,
	LAST7_DAY_TARGET_NET_DINING,
	LAST14_DAY_TARGET_NET_DINING,
	LAST28_DAY_TARGET_NET_DINING,
	NEXT7_DAY_TARGET_NET_DINING,
	NEXT14_DAY_TARGET_NET_DINING,
	NEXT28_DAY_TARGET_NET_DINING,
	CUMULATIVE_TARGET_NET_RICHCORE,
	LAST7_DAY_TARGET_NET_RICHCORE,
	LAST14_DAY_TARGET_NET_RICHCORE,
	LAST28_DAY_TARGET_NET_RICHCORE,
	NEXT7_DAY_TARGET_NET_RICHCORE,
	NEXT14_DAY_TARGET_NET_RICHCORE,
	NEXT28_DAY_TARGET_NET_RICHCORE,
	CUMULATIVE_TARGET_NET_ROOMS_SOLD,
	LAST7_DAY_TARGET_NET_ROOMS_SOLD,
	LAST14_DAY_TARGET_NET_ROOMS_SOLD,
	LAST28_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT7_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT14_DAY_TARGET_NET_ROOMS_SOLD,
	NEXT28_DAY_TARGET_NET_ROOMS_SOLD,
	CUMULATIVE_TARGET_GROSS_ROOMS_SOLD,
	LAST7_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST14_DAY_TARGET_GROSS_ROOMS_SOLD,
	LAST28_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT7_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT14_DAY_TARGET_GROSS_ROOMS_SOLD,
	NEXT28_DAY_TARGET_GROSS_ROOMS_SOLD,
	CUMULATIVE_TARGET_NET_SILVER_PRICE,
	LAST7_DAY_TARGET_NET_SILVER_PRICE,
	LAST14_DAY_TARGET_NET_SILVER_PRICE,
	LAST28_DAY_TARGET_NET_SILVER_PRICE,
	NEXT7_DAY_TARGET_NET_SILVER_PRICE,
	NEXT14_DAY_TARGET_NET_SILVER_PRICE,
	NEXT28_DAY_TARGET_NET_SILVER_PRICE
) as (
    SELECT
*
FROM HAVEN_STORE.pricer.occ_agg_targets
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_OCC_BY_ARRIVAL_DATE_FILL(
	BREAK_DATE,
	SHIP_CODE,
	SOURCE,
	ACTUAL_AVERAGED_NET_PRICE,
	ACTUAL_GW,
	ACTUAL_NET_ADDONS,
	ACTUAL_NET_DINING,
	ACTUAL_NET_RICHCORE,
	ACTUAL_NET_ROOMS_SOLD,
	ACTUAL_NET_TARIFF,
	LAST_SALES_DATE,
	MONDAY_DATE,
	GROSS_ROOMS_SOLD_7DAYS,
	GROSS_RICHCORE_7DAYS,
	GROSS_ROOMS_SOLD_14DAYS,
	GROSS_RICHCORE_14DAYS,
	GROSS_ROOMS_SOLD_28DAYS,
	GROSS_RICHCORE_28DAYS,
	NET_ROOMS_SOLD_7DAYS,
	NET_RICHCORE_7DAYS,
	NET_ADDONS_7DAYS,
	NET_DINING_7DAYS,
	NET_ROOMS_SOLD_14DAYS,
	NET_RICHCORE_14DAYS,
	NET_ROOMS_SOLD_28DAYS,
	NET_RICHCORE_28DAYS,
	PRICE_CHANGED_BY,
	LAST_PRICE_CHANGE_DATE,
	LAST_PRICE,
	GROSS_TARIFF_LAST_PRICECHANGE,
	GROSS_RICHCORE_LAST_PRICECHANGE,
	GROSS_ROOMS_SOLD_LAST_PRICECHANGE,
	PERIOD,
	AVAILABLE_ROOMS,
	TODAY_LY_INVOICE,
	TODAY_LY_RICHCORE,
	TODAY_LY_DINING,
	TODAY_LY_ADDONS,
	TODAY_LY_ROOMS_SOLD,
	TODAY_LY_GW,
	TARGET_CURRENT_SILVER_PRICE,
	TARGET_NET_TARIFF,
	TARGET_AVERAGED_NET_PRICE,
	TARGET_NET_ADDONS,
	TARGET_7DAY_NET_ADDONS,
	TARGET_14DAY_NET_ADDONS,
	TARGET_28DAY_NET_ADDONS,
	TARGET_NEXT7DAY_NET_ADDONS,
	TARGET_NEXT14DAY_NET_ADDONS,
	TARGET_NEXT28DAY_NET_ADDONS,
	TARGET_NET_DINING,
	TARGET_7DAY_NET_DINING,
	TARGET_14DAY_NET_DINING,
	TARGET_28DAY_NET_DINING,
	TARGET_NEXT7DAY_NET_DINING,
	TARGET_NEXT14DAY_NET_DINING,
	TARGET_NEXT28DAY_NET_DINING,
	TARGET_NET_RICHCORE,
	TARGET_7DAY_NET_RICHCORE,
	TARGET_14DAY_NET_RICHCORE,
	TARGET_28DAY_NET_RICHCORE,
	TARGET_NEXT7DAY_NET_RICHCORE,
	TARGET_NEXT14DAY_NET_RICHCORE,
	TARGET_NEXT28DAY_NET_RICHCORE,
	TARGET_CUMULATIVE_NET_ROOMS,
	TARGET_7DAY_NET_ROS,
	TARGET_14DAY_NET_ROS,
	TARGET_28DAY_NET_ROS,
	TARGET_NEXT7DAY_NET_ROS,
	TARGET_NEXT14DAY_NET_ROS,
	TARGET_NEXT28DAY_NET_ROS,
	TARGET_CUMULATIVE_GROSS_ROOMS,
	TARGET_7DAY_GROSS_ROS,
	TARGET_14DAY_GROSS_ROS,
	TARGET_28DAY_GROSS_ROS,
	TARGET_NEXT7DAY_GROSS_ROS,
	TARGET_NEXT14DAY_GROSS_ROS,
	TARGET_NEXT28DAY_GROSS_ROS,
	TARGET_GROSS_RICHCORE,
	TARGET_7DAY_GROSS_RICHCORE,
	TARGET_14DAY_GROSS_RICHCORE,
	TARGET_28DAY_GROSS_RICHCORE,
	TARGET_NEXT7DAY_GROSS_RICHCORE,
	TARGET_NEXT14DAY_GROSS_RICHCORE,
	TARGET_NEXT28DAY_GROSS_RICHCORE,
	REGION,
	TTL_BOOKINGS,
	TTL_SEARCHES,
	LAST28_BOOKINGS,
	LAST28_SEARCHES,
	LAST7_BOOKINGS,
	LAST7_SEARCHES,
	TTL_BOOKINGS_LY,
	TTL_SEARCHES_LY,
	LAST28_BOOKINGS_LY,
	LAST28_SEARCHES_LY,
	LAST7_BOOKINGS_LY,
	LAST7_SEARCHES_LY,
	CURRENT_PRICE,
	BROCHURE_PRICE_3OR4NIGHTS,
	BUDGET_NET_RICHCORE,
	CUMULATIVE_BUDGET_NET_ROOMS_SOLD,
	CUMULATIVE_BUDGET_NET_ADDONS,
	CUMULATIVE_BUDGET_NET_DINING,
	CUMULATIVE_BUDGET_GROSS_ROOMS_SOLD,
	FINAL_TOTAL_GROSS_BUDGET,
	FINAL_TOTAL_NET_BUDGET,
	FINAL_TOTAL_NET_BUDGETRICHCORE
) as (
    SELECT

    * RENAME "Available Rooms" AS AVAILABLE_ROOMS
FROM 
    HAVEN_STORE.pricer.occ_by_arrival_date_fill
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_PARKS(
	PARK_CODE,
	PARK_NAME,
	PARK_REGION
) as (
    SELECT
     PARK_CODE
    ,PARK_NAME
    ,PARK_REGION
FROM
    HAVEN_STORE.common.parks
  );

  
create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_PRICER_MINMAX(
	PARK,
	GRADE,
	BREAK_DATE,
	PRODUCT,
	SUBPRODUCT,
	DURATION,
	MIN_PRICE,
	MAX_PRICE,
	RECORD_COUNT,
	DEDUPLICATION_PREFERENCE
) as (
    with base as (
SELECT
     PARK
    ,GRADE
    ,BREAK_DATE
    ,PRODUCT
    ,SUBPRODUCT
    ,DURATION
    ,MIN_PRICE
    ,MAX_PRICE    
    ,SUM(1) OVER(PARTITION BY PARK, GRADE, BREAK_DATE) AS RECORD_COUNT
    ,ROW_NUMBER() OVER(PARTITION BY PARK, GRADE, BREAK_DATE ORDER BY DURATION ASC, MAX_PRICE DESC) AS Deduplication_preference

FROM
HAVEN_STORE.commercial.pricer_minmax 

WHERE DURATION >=3
    AND SUBPRODUCT='HIDEAWAY'
)
Select *
FROM
base
WHERE Deduplication_preference = 1
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_PRICER_PARK(
	PARK,
	NAME,
	REGION,
	REVENUE_MANAGER,
	ACTIVE,
	EXPORT,
	PARK_GROUP
) as (
    SELECT
     PARK
    ,NAME
    ,REGION
    ,REVENUE_MANAGER
    ,ACTIVE
    ,EXPORT
    ,"GROUP" AS PARK_GROUP
FROM
    HAVEN_PIPELINE.PX0006_BLUEYONDER_PRICER.pricer__park
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_PRICER_SEGMENT(
	SEGMENT,
	FROM_DL,
	TO_DL,
	ROS_WINDOW
) as (
    SELECT
     SEGMENT
    ,FROM_DL
    ,TO_DL
    ,ROS_WINDOW
FROM
    HAVEN_PIPELINE.PX0006_BLUEYONDER_PRICER.pricer__segment
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_PRORATED_BOOKING_REVENUE(
	BOOKING_ID,
	DELEGATE_RES_ID,
	UNIQUE_BK_ID,
	BOOKING_TYPE,
	BREAK_DATE,
	STAY_DATE,
	BOOKING_DATE,
	FIRM_DATE,
	CANCELLATION_DATE,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	BOOKING_STATUS,
	BOOKING_STATUS_CATEGORY,
	DURATION,
	PITCH_CODE,
	PRODUCT,
	SUB_PRODUCT,
	SOURCE,
	IN_SCOPE_FLAG,
	PARK_CODE,
	PARK_REGION,
	PAID_GRADE,
	REQUESTED_GRADE,
	ALLOCATED_GRADE,
	ADULTS,
	CHILDREN,
	INFANTS,
	PRORATED_NETT_BILLING_VALUE,
	DAY_RATIO,
	PRORATED_BROCHURE_PRICE,
	PRORATED_ACCOMMODATION_VALUE
) as (
    SELECT
    a.BOOKING_ID
    ,a.GROUP_ID AS DELEGATE_RES_ID
    ,CONCAT(a.BOOKING_ID, CASE WHEN a.GROUP_ID IS NULL then '' ELSE CONCAT('-', a.GROUP_ID) END) AS UNIQUE_BK_ID
    ,a.BOOKING_TYPE
    ,DATE(a.BREAK_DATE_XID, 'YYYYMMDD') AS BREAK_DATE
    ,DATE(a.STAY_DATE_XID, 'YYYYMMDD') AS STAY_DATE
    ,DATE(a.BOOKING_DATE_XID, 'YYYYMMDD') AS BOOKING_DATE
    ,DATE(a.BOOKING_DATE_XID, 'YYYYMMDD') AS FIRM_DATE
    ,DATE(NULLIF(a.CANCELLATION_DATE_XID,-1), 'YYYYMMDD') AS CANCELLATION_DATE
    ,DATE(a.ARRIVAL_DATE_XID, 'YYYYMMDD') AS ARRIVAL_DATE
    ,DATE(a.DEPARTURE_DATE_XID, 'YYYYMMDD') AS DEPARTURE_DATE
    ,b.BOOKING_STATUS_CODE AS BOOKING_STATUS
    ,b.BOOKING_STATUS_CATEGORY
    ,a.DURATION
    ,NULL AS PITCH_CODE
    ,f.PRODUCT_CODE AS PRODUCT
    ,f.SUB_PRODUCT_CODE AS SUB_PRODUCT
    ,g.BOOKING_SOURCE_CHANNEL_GROUP AS SOURCE
    ,CASE WHEN SOURCE = 'NEWSPAPER (SUN)' THEN FALSE ELSE TRUE END AS IN_SCOPE_FLAG
    ,d1.PARK_CODE
    ,d2.PARK_REGION
    ,CASE WHEN a.PAID_GRADE_XID='-1' THEN NULL ELSE e1.GRADE_CODE END AS PAID_GRADE
    ,CASE WHEN a.REQUESTED_GRADE_XID='-1' THEN NULL ELSE e2.GRADE_CODE END AS REQUESTED_GRADE
    ,CASE WHEN a.ALLOCATED_GRADE_XID='-1' THEN NULL ELSE e3.GRADE_CODE END AS ALLOCATED_GRADE
    ,a.ADULTS
    ,a.CHILDREN
    ,a.INFANTS
    ,COALESCE(NULLIF(a.PRORATED_NETT_BILLING_VALUE,0),a.PRORATED_DELEGATE_CHARGE_VALUE) AS PRORATED_NETT_BILLING_VALUE
    ,1 AS DAY_RATIO
    ,a.PRORATED_BROCHURE_PRICE
    ,a.PRORATED_ACCOMMODATION_VALUE
FROM
    HAVEN_STORE.holiday.fct_holiday_bookings_prorated a 

    INNER JOIN HAVEN_STORE.holiday.dim_booking_status b
    ON a.BOOKING_STATUS_XID = b.BOOKING_STATUS_XID

    INNER JOIN HAVEN_STORE.holiday.dim_booking_source_channel c
    ON a.BOOKING_SOURCE_CHANNEL_XID = c.BOOKING_SOURCE_CHANNEL_XID

    INNER JOIN HAVEN_STORE.common.dim_park d1
    ON a.PARK_XID = d1.PARK_XID

    LEFT JOIN HAVEN_STORE.common.parks d2
    ON d1.PARK_CODE = d2.PARK_CODE

    INNER JOIN HAVEN_STORE.holiday.dim_grade e1
    ON a.PAID_GRADE_XID = e1.GRADE_XID

    INNER JOIN HAVEN_STORE.holiday.dim_grade e2
    ON a.REQUESTED_GRADE_XID = e2.GRADE_XID

    INNER JOIN HAVEN_STORE.holiday.dim_grade e3
    ON a.ALLOCATED_GRADE_XID = e3.GRADE_XID

    INNER JOIN HAVEN_STORE.holiday.dim_package_type f
    ON a.PACKAGE_TYPE_XID = f.PACKAGE_TYPE_XID    

    INNER JOIN HAVEN_STORE.holiday.dim_booking_source_channel g
    ON a.BOOKING_SOURCE_CHANNEL_XID = g.BOOKING_SOURCE_CHANNEL_XID
    
WHERE
    a.SNAPSHOT_DATE = (SELECT MAX(SNAPSHOT_DATE) FROM HAVEN_STORE.holiday.fct_holiday_bookings_prorated)
    AND DATE(a.STAY_DATE_XID, 'YYYYMMDD') >= '2018-01-01'::DATE
    AND f.PRODUCT_CODE <> 'TOURING'
    AND b.BOOKING_STATUS_CATEGORY IN ('FIRM', 'CANCELLED')
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_ROOM_TYPE_LOOKUP(
	ACCOM_CODE,
	PRODUCT_DESCRIPTION,
	GRADE_LEVEL_IND,
	ACCOM_DESCRIPTION,
	ACCOM_TYPES,
	ACCOM_GROUP,
	HAVEN_GRADE,
	LEVEL_1_GROUPING,
	LEVEL_2_GROUPING,
	PET_FRIENDLY,
	ROOM_SIZE
) as (
    WITH active AS (
SELECT
     ACCOM_CODE
    ,PRODUCT_DESCRIPTION
    ,CASE 
        WHEN PRODUCT_DESCRIPTION = 'Saver' THEN 0
        WHEN PRODUCT_DESCRIPTION = 'Bronze' THEN 1 
        WHEN PRODUCT_DESCRIPTION = 'Silver' THEN 2 
        WHEN PRODUCT_DESCRIPTION = 'Gold' THEN 3 
        WHEN PRODUCT_DESCRIPTION = 'Signature/Lodge' THEN 4
     END AS GRADE_LEVEL_IND
    ,ACCOM_DESCRIPTION
    ,ACCOM_TYPES
    ,ACCOM_GROUP
    ,HAVEN_GRADE
    ,LEVEL_1_GROUPING
    ,LEVEL_2_GROUPING
    ,CASE 
        WHEN ACCOM_DESCRIPTION LIKE '%Pet Friendly%' THEN 'Pet Friendly' 
        ELSE 'Standard' 
     END AS PET_FRIENDLY
    ,CASE 
        WHEN ACCOM_DESCRIPTION LIKE '%2 Bedroom%' THEN '2 Bedroom' 
        WHEN ACCOM_DESCRIPTION LIKE '%3 Bedroom%' THEN '3 Bedroom' 
        WHEN ACCOM_DESCRIPTION LIKE '%4 Bedroom%' THEN '4 Bedroom' 
        ELSE 'Other' 
     END AS ROOM_SIZE
FROM
    HAVEN_STORE.ocandc.room_type_lookup
WHERE
    VALID_TO_DT::DATE='0099-12-31'
    AND ACTIVE_ON_SEAWARE='Active'
    AND ACCOM_CODE IS NOT NULL
QUALIFY ROW_NUMBER() OVER(PARTITION BY ACCOM_CODE ORDER BY VALID_FROM_DT DESC) = 1
) 
SELECT * FROM active 
UNION ALL 
SELECT
     ACCOM_CODE
    ,PRODUCT_DESCRIPTION
    ,CASE 
        WHEN PRODUCT_DESCRIPTION = 'Saver' THEN 0
        WHEN PRODUCT_DESCRIPTION = 'Bronze' THEN 1 
        WHEN PRODUCT_DESCRIPTION = 'Silver' THEN 2 
        WHEN PRODUCT_DESCRIPTION = 'Gold' THEN 3 
        WHEN PRODUCT_DESCRIPTION = 'Signature/Lodge' THEN 4
     END AS GRADE_LEVEL_IND
    ,ACCOM_DESCRIPTION
    ,ACCOM_TYPES
    ,ACCOM_GROUP
    ,HAVEN_GRADE
    ,LEVEL_1_GROUPING
    ,LEVEL_2_GROUPING
    ,CASE 
        WHEN ACCOM_DESCRIPTION LIKE '%Pet Friendly%' THEN 'Pet Friendly' 
        ELSE 'Standard' 
     END AS PET_FRIENDLY
    ,CASE 
        WHEN ACCOM_DESCRIPTION LIKE '%2 Bedroom%' THEN '2 Bedroom' 
        WHEN ACCOM_DESCRIPTION LIKE '%3 Bedroom%' THEN '3 Bedroom' 
        WHEN ACCOM_DESCRIPTION LIKE '%4 Bedroom%' THEN '4 Bedroom' 
        ELSE 'Other' 
     END AS ROOM_SIZE
FROM
    HAVEN_STORE.ocandc.room_type_lookup 
WHERE
    ACTIVE_ON_SEAWARE<>'Active'
    AND ACCOM_CODE IS NOT NULL
    AND ACCOM_CODE NOT IN (SELECT DISTINCT ACCOM_CODE FROM active)
QUALIFY ROW_NUMBER() OVER(PARTITION BY ACCOM_CODE ORDER BY VALID_FROM_DT DESC) = 1
);

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_SHIP_LOOKUP(
	PARK_CODE,
	OC_C_CODES,
	OC_C_LOCATION
) as (
    SELECT
     HAVEN_CODE AS PARK_CODE
    ,OC_C_CODES
    ,OC_C_LOCATION
FROM
    HAVEN_PIPELINE.PX0006_BLUEYONDER_PRICER.ship_lookup
  )
;

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_TARGET_BUDGET_HISTORY(
	DATA_VERSION_ID,
	PARK_CODE,
	BREAK_DATE,
	BREAK_ID,
	BREAK_YEAR,
	DIRECT_UNITS,
	DIRECT_REV
) as (
    SELECT 
    DATA_VERSION_ID
   ,HAVEN_SHIP_CODE AS PARK_CODE
   ,BREAK_DATE
   ,CONCAT(HAVEN_SHIP_CODE, '_', BREAK_DATE) as BREAK_ID
   ,EXTRACT(YEAR FROM BREAK_DATE) as BREAK_YEAR
   ,DIRECT_UNITS

   ,DIRECT_REV

FROM HAVEN_STORE.pricer.BUDGET_INPUTS_HISTORY
WHERE DATA_VERSION_ID = 1
);

create or replace view HAVEN_STAGING_AA_DEV.RM_STAGING.S0_TRIMMED_CALENDAR(
	PERIOD,
	BREAKDATE_CURRENT,
	BREAKDATE_PRIOR,
	BREAKDATE_FUTURE
) as (
    SELECT
     a.PERIOD
     --- Temporary override of date mapping to match to irregular Christmas breaks in 2025
    ,CASE 
        WHEN a.BREAKDATE_CURRENT = '2025-12-26'::date THEN '2025-12-27'::date  
        WHEN a.BREAKDATE_CURRENT = '2025-12-29'::date THEN '2025-12-30'::date
        ELSE a.BREAKDATE_CURRENT
    END AS  BREAKDATE_CURRENT         
    ,a.BREAKDATE_PRIOR
    ,a.BREAKDATE_FUTURE

FROM HAVEN_STORE.ocandc.occ_trimmed_calendar a
);

