USE ROLE sysadmin;

-- Development

CREATE DATABASE haven_store_dev;
CREATE DATABASE haven_staging_dev;
CREATE DATABASE haven_pipeline_dev;

CREATE WAREHOUSE haven_dbt_transform_dev_warehouse_xsmall WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

-- Quality assurance

CREATE DATABASE haven_store_qat;
CREATE DATABASE haven_staging_qat;
CREATE DATABASE haven_pipeline_qat;

CREATE WAREHOUSE haven_dbt_transform_qat_warehouse_xsmall WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

-- Production

CREATE DATABASE haven_store_prod;
CREATE DATABASE haven_staging_prod;
CREATE DATABASE haven_pipeline_prod;

CREATE WAREHOUSE haven_dbt_transform_prod_warehouse_xsmall WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

use role useradmin;

-- Development

CREATE ROLE haven_dbt_transform_dev;

create role _haven_dbt_transform_dev_warehouse_xsmall__operator;
create role _haven_dbt_transform_dev_warehouse_xsmall__usage;

CREATE ROLE _haven_store_dev__usage;
CREATE ROLE _haven_store_dev__schema;

CREATE ROLE _haven_staging_dev__usage;
CREATE ROLE _haven_staging_dev__schema;

CREATE ROLE _haven_pipeline_dev__usage;
CREATE ROLE _haven_pipelin_dev__schema;

--create user haven_dbt_transform_dev
--login_name = 'haven.dbt.transform.dev'
--display_name = 'Haven DBT Development'
--email = 'sarunas.jatautis@bourne-leisure.co.uk'
--comment = 'Haven DBT Development Model Development'
--default_role = haven_dbt_transform_dev
--default_warehouse = haven_dbt_transform_dev_warehouse_xsmall
--RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtIuFuAmhB6gkIdU2A+l/
--abiV8z3KlH9ElZKTkE1lxfH0avhZdWEBrf+unWEuINDFI3Xx1LyBGEeFci3Mk1kf
--XZ/QiM6AlYw9cAIgVlw/ap6EnNCFyWVoAizw1R0Cs0Y1x5ZCKImpaY8bZCG9fvqO
--GzNiop7KvVkgpUn+VV7exr3o5xEg2myxEHHNwHAXzazOYc3de7y9lubfGL3I8ajW
--v60QVOnbBYST6sbASxFDBqSWqgG8VvT05qTmta1fsvmEDq2TCu3F9VZdLn4nM0xd
--HeAjmzeuqJ9kNOnH6EPRWzYUH+/4KJcha5l6o7uiPjByfTdngvHmWm65aCtXGugv
--xwIDAQAB';

ALTER user haven_dbt_transform_dev
SET email = 'sarunas.jatautis@bourne-leisure.co.uk',
comment = 'Haven DBT Development Model Development',
default_role = haven_dbt_transform_dev,
default_warehouse = haven_dbt_transform_dev_warehouse_xsmall,
RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtIuFuAmhB6gkIdU2A+l/
abiV8z3KlH9ElZKTkE1lxfH0avhZdWEBrf+unWEuINDFI3Xx1LyBGEeFci3Mk1kf
XZ/QiM6AlYw9cAIgVlw/ap6EnNCFyWVoAizw1R0Cs0Y1x5ZCKImpaY8bZCG9fvqO
GzNiop7KvVkgpUn+VV7exr3o5xEg2myxEHHNwHAXzazOYc3de7y9lubfGL3I8ajW
v60QVOnbBYST6sbASxFDBqSWqgG8VvT05qTmta1fsvmEDq2TCu3F9VZdLn4nM0xd
HeAjmzeuqJ9kNOnH6EPRWzYUH+/4KJcha5l6o7uiPjByfTdngvHmWm65aCtXGugv
xwIDAQAB';


-- Quality assurance

CREATE ROLE haven_dbt_transform_qat;

create role _haven_dbt_transform_qat_warehouse_xsmall__operator;
create role _haven_dbt_transform_qat_warehouse_xsmall__usage;

CREATE ROLE _haven_store_qat__usage;
CREATE ROLE _haven_store_qat__schema;

CREATE ROLE _haven_staging_qat__usage;
CREATE ROLE _haven_staging_qat__schema;

CREATE ROLE _haven_pipeline_qat__usage;
CREATE ROLE _haven_pipelin_qat__schema;

--create user haven_dbt_transform_qat
--login_name = 'haven.dbt.transform.qat'
--display_name = 'Haven DBT QAT'
--email = 'sarunas.jatautis@bourne-leisure.co.uk'
--comment = 'Haven DBT Development Model QAT pipelines'
--default_role = haven_dbt_transform_qat
--default_warehouse = haven_dbt_transform_qat_warehouse_xsmall
--RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxNVUWO+0odZmyvPrIBfQ
--f3y/8kHvKlq8UsbxIq8byQMyR3RcXiwfx9lKiE+NEFXOJsR6FplH6moVsyAk8pk4
--DsG8YQ4A2Fuoix72ABCisS8GjdiFRTEq0KxsoZVtKDUYTMLxIDtbJbWfOUEf+6IH
--HQ4Q4nB8dAs58QzMEkat0mXV8EK5RG1SGiwZMAXh5kipaezcxMOPjNq1uzgMRoNp
--NoQX+wyflzR953v0wP5eG7DEomherwCoVMec1SlJ5ME9LR65lBgRbCjDpeC5X88o
--dOOVlCiw84vBCqse85QKLwaNjEaOdaLEbFqcxdjJ+JyB+IUZAOv8+xmk5I3I0BeY
--qQIDAQAB';

alter user haven_dbt_transform_qat
SET email = 'sarunas.jatautis@bourne-leisure.co.uk',
comment = 'Haven DBT Development Model QAT pipelines',
default_role = haven_dbt_transform_qat,
default_warehouse = haven_dbt_transform_qat_warehouse_xsmall,
RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxNVUWO+0odZmyvPrIBfQ
f3y/8kHvKlq8UsbxIq8byQMyR3RcXiwfx9lKiE+NEFXOJsR6FplH6moVsyAk8pk4
DsG8YQ4A2Fuoix72ABCisS8GjdiFRTEq0KxsoZVtKDUYTMLxIDtbJbWfOUEf+6IH
HQ4Q4nB8dAs58QzMEkat0mXV8EK5RG1SGiwZMAXh5kipaezcxMOPjNq1uzgMRoNp
NoQX+wyflzR953v0wP5eG7DEomherwCoVMec1SlJ5ME9LR65lBgRbCjDpeC5X88o
dOOVlCiw84vBCqse85QKLwaNjEaOdaLEbFqcxdjJ+JyB+IUZAOv8+xmk5I3I0BeY
qQIDAQAB';

-- Production

CREATE ROLE haven_dbt_transform_prod;

create role _haven_dbt_transform_prod_warehouse_xsmall__operator;
create role _haven_dbt_transform_prod_warehouse_xsmall__usage;

CREATE ROLE _haven_store_prod__usage;
CREATE ROLE _haven_store_prod__schema;

CREATE ROLE _haven_staging_prod__usage;
CREATE ROLE _haven_staging_prod__schema;

CREATE ROLE _haven_pipeline_prod__usage;
CREATE ROLE _haven_pipelin_prod__schema;

create user haven_dbt_transform_prod
login_name = 'haven.dbt.transform.prod'
display_name = 'Haven DBT Prod'
email = 'sarunas.jatautis@bourne-leisure.co.uk'
comment = 'Haven DBT Development Model Production pipelines'
default_role = haven_dbt_transform_prod
default_warehouse = haven_dbt_transform_prod_warehouse_xsmall
RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA06J+ibFFZyuI7nHh5Iwm
5H5g22uzY3ygiF1CnoHS0K/Go9bnx22UP5MivF6SKYN8JuSaLFVyrw+zNG+5laG+
33Gryk5OOLywZkpmxIdpZrRttMbrSZeOHlG1KR5rF5uriHCrXw8KDq3ILOvNar1K
T6dvXYpErmBMR145QZzEivj7PfMvXye+hiMiFdlesDmm+sEpKWzMU5U6yK2D72a9
+6uBQ5fB3l6hh94u9MmIarNcnUy5Pd8Qm1kJyOWWSFmpqxA4zgweZAEQI+D/ymBj
hSuY6Wx4VjRc+YBRT47WZ4V8CD7abgSE0xm1xILRB/MuGfkvsGBT4L4gwSJ8iB5D
1QIDAQAB';


USE ROLE securityadmin;

-- Development

grant usage, monitor on warehouse haven_dbt_transform_dev_warehouse_xsmall to role _haven_dbt_transform_dev_warehouse_xsmall__usage;
grant role _haven_dbt_transform_dev_warehouse_xsmall__usage to role _haven_dbt_transform_dev_warehouse_xsmall__operator;
grant operate, modify on warehouse haven_dbt_transform_dev_warehouse_xsmall to role _haven_dbt_transform_dev_warehouse_xsmall__operator;

GRANT USAGE ON DATABASE haven_store_dev TO ROLE _haven_store_dev__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_store_dev TO ROLE _haven_store_dev__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_store_dev TO ROLE _haven_store_dev__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_store_dev TO ROLE _haven_store_dev__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_store_dev TO ROLE _haven_store_dev__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_store_dev TO ROLE _haven_store_dev__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_store_dev TO ROLE _haven_store_dev__usage;
GRANT ROLE _haven_store_dev__usage TO ROLE _haven_store_dev__schema;
GRANT CREATE SCHEMA ON DATABASE haven_store_dev TO ROLE _haven_store_dev__schema;

GRANT USAGE ON DATABASE haven_staging_dev TO ROLE _haven_staging_dev__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_staging_dev TO ROLE _haven_staging_dev__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_staging_dev TO ROLE _haven_staging_dev__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_staging_dev TO ROLE _haven_staging_dev__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_staging_dev TO ROLE _haven_staging_dev__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_staging_dev TO ROLE _haven_staging_dev__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_staging_dev TO ROLE _haven_staging_dev__usage;
GRANT ROLE _haven_staging_dev__usage TO ROLE _haven_staging_dev__schema;
GRANT CREATE SCHEMA ON DATABASE haven_staging_dev TO ROLE _haven_staging_dev__schema;

GRANT USAGE ON DATABASE haven_pipeline_dev TO ROLE _haven_pipeline_dev__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_pipeline_dev TO ROLE _haven_pipeline_dev__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_pipeline_dev TO ROLE _haven_pipeline_dev__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_pipeline_dev TO ROLE _haven_pipeline_dev__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_pipeline_dev TO ROLE _haven_pipeline_dev__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_pipeline_dev TO ROLE _haven_pipeline_dev__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_pipeline_dev TO ROLE _haven_pipeline_dev__usage;
GRANT ROLE _haven_pipeline_dev__usage TO ROLE _haven_pipeline_dev__schema;
GRANT CREATE SCHEMA ON DATABASE haven_pipeline_dev TO ROLE _haven_pipeline_dev__schema;

GRANT ROLE _haven_dbt_transform_dev_warehouse_xsmall__usage TO ROLE haven_dbt_transform_dev; 

GRANT ROLE _haven_store_dev__schema TO ROLE haven_dbt_transform_dev;
GRANT ROLE _haven_store_dev__usage TO ROLE haven_data_transform;

GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_ABDULKAHARE;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_ANDREWDAWSON;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_DANIELCARTER;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_DONATASGEDGAUDAS;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_GARYRANSON;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_GREGTAYLOR;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_IANMCKAY;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JOHNPERING;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JONATHANMANLEY;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JOSEPHMCDONALD;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JUDYSHAO;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_MARLONGILL;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_NARAYANAVELAGA;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_PAULWALLER;
GRANT ROLE _haven_store_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_SARUNASJATAUTIS;

GRANT ROLE _haven_staging_dev__schema TO ROLE haven_dbt_transform_dev;
GRANT ROLE _haven_staging_dev__usage TO ROLE haven_data_transform;

GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_ABDULKAHARE;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_ANDREWDAWSON;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_DANIELCARTER;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_DONATASGEDGAUDAS;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_GARYRANSON;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_GREGTAYLOR;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_IANMCKAY;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JOHNPERING;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JONATHANMANLEY;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JOSEPHMCDONALD;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JUDYSHAO;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_MARLONGILL;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_NARAYANAVELAGA;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_PAULWALLER;
GRANT ROLE _haven_staging_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_SARUNASJATAUTIS;

GRANT ROLE _haven_pipeline_dev__schema TO ROLE haven_dbt_transform_dev;
GRANT ROLE _haven_pipeline_dev__usage TO ROLE haven_data_transform;

GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_ABDULKAHARE;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_ANDREWDAWSON;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_DANIELCARTER;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_DONATASGEDGAUDAS;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_GARYRANSON;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_GREGTAYLOR;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_IANMCKAY;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JOHNPERING;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JONATHANMANLEY;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JOSEPHMCDONALD;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_JUDYSHAO;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_MARLONGILL;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_NARAYANAVELAGA;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_PAULWALLER;
GRANT ROLE _haven_pipeline_dev__schema TO ROLE HAVEN_DATA_TRANSFORM_SARUNASJATAUTIS;

GRANT ROLE haven_dbt_transform_dev TO user haven_dbt_transform_dev;
GRANT ROLE haven_data_transform TO ROLE haven_dbt_transform_dev;


-- Quality assurance

grant usage, monitor on warehouse haven_dbt_transform_qat_warehouse_xsmall to role _haven_dbt_transform_qat_warehouse_xsmall__usage;
grant role _haven_dbt_transform_qat_warehouse_xsmall__usage to role _haven_dbt_transform_qat_warehouse_xsmall__operator;
grant operate, modify on warehouse haven_dbt_transform_qat_warehouse_xsmall to role _haven_dbt_transform_qat_warehouse_xsmall__operator;

GRANT USAGE ON DATABASE haven_store_qat TO ROLE _haven_store_qat__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_store_qat TO ROLE _haven_store_qat__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_store_qat TO ROLE _haven_store_qat__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_store_qat TO ROLE _haven_store_qat__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_store_qat TO ROLE _haven_store_qat__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_store_qat TO ROLE _haven_store_qat__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_store_qat TO ROLE _haven_store_qat__usage;
GRANT ROLE _haven_store_qat__usage TO ROLE _haven_store_qat__schema;
GRANT CREATE SCHEMA ON DATABASE haven_store_qat TO ROLE _haven_store_qat__schema;

GRANT USAGE ON DATABASE haven_staging_qat TO ROLE _haven_staging_qat__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_staging_qat TO ROLE _haven_staging_qat__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_staging_qat TO ROLE _haven_staging_qat__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_staging_qat TO ROLE _haven_staging_qat__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_staging_qat TO ROLE _haven_staging_qat__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_staging_qat TO ROLE _haven_staging_qat__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_staging_qat TO ROLE _haven_staging_qat__usage;
GRANT ROLE _haven_staging_qat__usage TO ROLE _haven_staging_qat__schema;
GRANT CREATE SCHEMA ON DATABASE haven_staging_qat TO ROLE _haven_staging_qat__schema;

GRANT USAGE ON DATABASE haven_pipeline_qat TO ROLE _haven_pipeline_qat__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_pipeline_qat TO ROLE _haven_pipeline_qat__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_pipeline_qat TO ROLE _haven_pipeline_qat__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_pipeline_qat TO ROLE _haven_pipeline_qat__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_pipeline_qat TO ROLE _haven_pipeline_qat__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_pipeline_qat TO ROLE _haven_pipeline_qat__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_pipeline_qat TO ROLE _haven_pipeline_qat__usage;
GRANT ROLE _haven_pipeline_qat__usage TO ROLE _haven_pipeline_qat__schema;
GRANT CREATE SCHEMA ON DATABASE haven_pipeline_qat TO ROLE _haven_pipeline_qat__schema;

GRANT ROLE _haven_dbt_transform_qat_warehouse_xsmall__usage TO ROLE haven_dbt_transform_qat;

GRANT ROLE _haven_store_qat__schema TO ROLE haven_dbt_transform_qat;
GRANT ROLE _haven_store_qat__usage TO ROLE haven_data_transform;

GRANT ROLE _haven_staging_qat__schema TO ROLE haven_dbt_transform_qat;
GRANT ROLE _haven_staging_qat__usage TO ROLE haven_data_transform;

GRANT ROLE _haven_pipeline_qat__schema TO ROLE haven_dbt_transform_qat;
GRANT ROLE _haven_pipeline_qat__usage TO ROLE haven_data_transform;

GRANT ROLE haven_dbt_transform_qat TO USER haven_dbt_transform_qat;
GRANT ROLE haven_data_transform TO ROLE haven_dbt_transform_qat;


-- Production

grant usage, monitor on warehouse haven_dbt_transform_prod_warehouse_xsmall to role _haven_dbt_transform_prod_warehouse_xsmall__usage;
grant role _haven_dbt_transform_prod_warehouse_xsmall__usage to role _haven_dbt_transform_prod_warehouse_xsmall__operator;
grant operate, modify on warehouse haven_dbt_transform_prod_warehouse_xsmall to role _haven_dbt_transform_prod_warehouse_xsmall__operator;

GRANT USAGE ON DATABASE haven_store_prod TO ROLE _haven_store_prod__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_store_prod TO ROLE _haven_store_prod__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_store_prod TO ROLE _haven_store_prod__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_store_prod TO ROLE _haven_store_prod__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_store_prod TO ROLE _haven_store_prod__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_store_prod TO ROLE _haven_store_prod__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_store_prod TO ROLE _haven_store_prod__usage;
GRANT ROLE _haven_store_prod__usage TO ROLE _haven_store_prod__schema;
GRANT CREATE SCHEMA ON DATABASE haven_store_prod TO ROLE _haven_store_prod__schema;

GRANT USAGE ON DATABASE haven_staging_prod TO ROLE _haven_staging_prod__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_staging_prod TO ROLE _haven_staging_prod__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_staging_prod TO ROLE _haven_staging_prod__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_staging_prod TO ROLE _haven_staging_prod__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_staging_prod TO ROLE _haven_staging_prod__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_staging_prod TO ROLE _haven_staging_prod__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_staging_prod TO ROLE _haven_staging_prod__usage;
GRANT ROLE _haven_staging_prod__usage TO ROLE _haven_staging_prod__schema;
GRANT CREATE SCHEMA ON DATABASE haven_staging_prod TO ROLE _haven_staging_prod__schema;

GRANT USAGE ON DATABASE haven_pipeline_prod TO ROLE _haven_pipeline_prod__usage;
GRANT USAGE ON future SCHEMAS IN DATABASE haven_pipeline_prod TO ROLE _haven_pipeline_prod__usage;
GRANT SELECT ON future TABLES IN DATABASE haven_pipeline_prod TO ROLE _haven_pipeline_prod__usage;
GRANT SELECT ON future VIEWS IN DATABASE haven_pipeline_prod TO ROLE _haven_pipeline_prod__usage;
GRANT SELECT ON future MATERIALIZED VIEWS IN DATABASE haven_pipeline_prod TO ROLE _haven_pipeline_prod__usage;
GRANT USAGE ON future STAGES IN DATABASE haven_pipeline_prod TO ROLE _haven_pipeline_prod__usage;
GRANT USAGE ON future FILE FORMATS IN DATABASE haven_pipeline_prod TO ROLE _haven_pipeline_prod__usage;
GRANT ROLE _haven_pipeline_prod__usage TO ROLE _haven_pipeline_prod__schema;
GRANT CREATE SCHEMA ON DATABASE haven_pipeline_prod TO ROLE _haven_pipeline_prod__schema;

GRANT ROLE _haven_dbt_transform_prod_warehouse_xsmall__usage TO ROLE haven_dbt_transform_prod;

GRANT ROLE _haven_store_prod__schema TO ROLE haven_dbt_transform_prod;
GRANT ROLE _haven_store_prod__usage TO ROLE haven_data_transform;

GRANT ROLE _haven_staging_prod__schema TO ROLE haven_dbt_transform_prod;
GRANT ROLE _haven_staging_prod__usage TO ROLE haven_data_transform;

GRANT ROLE _haven_pipeline_prod__schema TO ROLE haven_dbt_transform_prod;
GRANT ROLE _haven_pipeline_prod__usage TO ROLE haven_data_transform;

GRANT ROLE haven_dbt_transform_prod TO USER haven_dbt_transform_prod;

-- 13/11/2024

USE ROLE SECURITYADMIN;

GRANT DATABASE ROLE	SNOWFLAKE.CORTEX_USER TO ROLE HAVEN_DBT_TRANSFORM_PROD;

GRANT USAGE ON INTEGRATION	AWS_LAMBDA_SERVICE_INTEGRATION_DEV TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	AWS_S3_BLOOMREACH_TARGET_DEV TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	AWS_S3_BLOOMREACH_TARGET_PROD TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	AWS_S3_CONSENT_AND_PREFERENCE_DEV TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	AWS_S3_CONSENT_AND_PREFERENCE_PROD TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	AWS_S3_SKUUUDLE_CLIENT TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_DEV_BLAPI_S3_INTEGRATION_DEV TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVDEVSERV_AWIN_S3_INTEGRATION_DEV TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVDEVSERV_BLAPI_S3_TECHNET_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVDEVSERV_BLUEYONDER_S3_INTEGRATION_DEV TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVDEVSERV_ERPX_FPA_S3_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVDEVSERV_RETAIL_SALES_EXPORT_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVDEVSERV_SEG_S3_INTEGRATION_DEV TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVDEVSERV_SNOWFLAKE_LETTINGS_DATA_EXPORT_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVPRODSERV_AWIN_S3_INTEGRATION_PROD TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVPRODSERV_BLAPI_S3_TECHNET_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVPRODSERV_BLUEYONDER_S3_INTEGRATION_PROD TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVPRODSERV_FREEDOMPAY_SFTP_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVPRODSERV_RETAIL_SALES_EXPORT_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_HAVPRODSERV_SEG_S3_INTEGRATION_PROD TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_RMS_STATIC_DATA_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	BLG_SANDBOX_QUALTRICS_S3_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	GCS_BLG_TARGET_ESSENCEMEDIA_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT USAGE ON INTEGRATION	HAVEN_CHOPSTIX_AZURE_INTEGRATION TO ROLE HAVEN_DBT_TRANSFORM_PROD;

GRANT ROLE	_BOURNE_STORE__SAS_COMMON__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_BOURNE_STORE__SAS_SCV__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ACTIVITIES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ADTHENA__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__AMPLITUDE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ARCADES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__AWIN__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__AZTECACTIVITYMANAGEMENT_COMPLEX__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__AZTEC_COMPLEX__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__AZTEC_RETAIL__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__BIGQUERY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__BLAPI_HID__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__BLOOMREACH_INTEGRATION__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__BLOOMREACH__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__BLUEYONDER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__BRAINTREE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__COMMON__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__COMPETITOR__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__CONSENT_AND_PREFERENCE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__COUPA__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__CYHH__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_AAC_ONPARKWIFI__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_ACCEPTANCE_OF_RISK__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_ACTIVITIES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_ARRIVALS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_BOOKINGS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_CAPACITY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_FB_EAGLEEYE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_FB_ENTERTAINMENT__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_FB_TABLE_BOOKING__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_OWNERS_ARRIVALS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_PAYMENTS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_PLAYPASS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DIG_PRICING__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DREAM_EVERGREEN__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DREAM_ROCKLEYBOATPARK__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__DREAM__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ECLIENT__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__EQUALISER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ERPX__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__EXPERIAN__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__FACEBOOK_CARAVAN_SALES_LEADS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__FACEBOOK_CARAVAN_SALES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__FACEBOOK_HOLIDAY_SALES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__FINANCIAL_CUBE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__FRESHSALES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__GOOGLE_INTEGRATION__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ICLEAN__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__IDENTITY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__JDAADMIN__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__KMSREPORTING_COMPLEX__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__MARINER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__MATTERPORT_IMAGES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__PLOT_ARCHIVE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__PLOT_DREAM__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__PLOT__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__PRICER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__QUALTRICS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__SAGACITY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__SAS_COMMON__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__SAS_SCV__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__SEAWARE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__SKI_LIFT__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__TIKTOK_ADS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__WETHERSPOONS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__WORKFORCE_SAM__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ZBSDATA_COMPLEX__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ZBSDATA_RETAIL__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_BASE__ZONAL__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_MASTER__REVENUE_MANAGEMENT_STORAGE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_MASTER__REVENUE_MANAGEMENT_STORAGE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_PIPELINE__BLUEYONDER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_PIPELINE__CRM_DATA__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_PIPELINE__PX0006_BLUEYONDER_PRICER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_PIPELINE__RETAIL_SALES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_PIPELINE__SURVEY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STAGING__REVENUE_MANAGEMENT_OUTPUT__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STAGING__REVENUE_MANAGEMENT_STAGING__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STAGING__TROOPER2__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__ACTIVITIES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__ALIGN_ALYTICS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__AVAILABILITY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__CARAVANS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__CARAVAN_SALES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__COMMERCIAL__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__COMMON_RESTRICTED__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__COMMON__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__COMPETITOR__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__CONSENT_AND_PREFERENCE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__DIGITAL__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__FINANCE_SHARED_SERVICES__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__FINANCIAL_CUBE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__HAVEN_ACCOUNTANTS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__HAVEN_STAGING__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__HOLIDAY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__IDENTITY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__INTEGRATION__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__JDAADMIN__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__JDAPREP__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__KMSREPORTING_COMPLEX__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__MA_MART__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__OCANDC__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PARK_OPERATIONS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PAYMENTS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PERFORMANCE_MARKETING__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PITCH_PERFECT__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PLAYPASS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PLOTREPRS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PLOT_REPORTING__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PRICER_DECISION_MATRIX__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PRICER_FORECAST__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PRICER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__PROSPECTS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__RETAIL__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__REVENUE_MANAGEMENT_REPORTING__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__REVENUE_MANAGEMENT__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__SALES_PLANNER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__SASMART__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__SAS_SCV__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__SEAWARE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__SURVEY__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__TROOPER2__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__TROOPER__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__TRPREPRS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__WORKFORCE__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__ZBSDATA_COMPLEX__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__ZBSDATA_RETAIL__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__ZBSDATA__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;
GRANT ROLE	_HAVEN_STORE__ZONAL_STOCK_REPORTS__READER TO ROLE HAVEN_DBT_TRANSFORM_PROD;


-- 05/02/2025

use role useradmin;

desc user haven_pipeline_transform_uat;

alter user haven_pipeline_transform_uat set type = service;

alter user haven_pipeline_transform_uat
set RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAradDnaTSt3CcIWkqlFft
1QUzKXHoOX5JY8SDtriqmKXJeX6dDGJ5cTAUQtmPw5IIwpFBTDmomURH5tFx6r0f
bPstMX3K4E/M3bZtOSOG2P/ZaXkLZ9dnwsXo85VhSs9ZoPFFyLLwhg3x2KSD8Nl4
FbpnlfomXa3G0IZRtxuxAs700KCrU24PzmvpK/0wVxqu7zOeeoeOL0HE2YbQiyaO
whL5M3Ox+Gu4kMzluxm7hF/jo01aq9oIgE4PXkpJc17cvTY9MvH/tpwUXAr8Wbx/
Z5J0D9NUi6bn6fJNErlqx2hlhGs6qYQMrYRxWKLPfas0sQr72BSGdc1L+Wt9kYU5
9wIDAQAB';


-- 06/02/2025

use ROLE dba;

SHOW GRANTS TO ROLE haven_data_transform;

use role securityadmin;

REVOKE ROLE _BOURNE_STORE_DEV__FINANCE_SHARED_SERVICES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_DEV__KMSREPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_DEV__SAS_COMMON__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_DEV__SAS_SCV__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_DEV__ZBSDATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_PROD__FINANCE_SHARED_SERVICES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_PROD__KMSREPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_PROD__SAS_COMMON__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_PROD__SAS_SCV__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_PROD__ZBSDATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_QAT__FINANCE_SHARED_SERVICES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_QAT__KMSREPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_QAT__SAS_COMMON__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_QAT__SAS_SCV__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_QAT__ZBSDATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_TEST__FINANCE_SHARED_SERVICES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_TEST__KMSREPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_TEST__SAS_COMMON__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_TEST__SAS_SCV__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _BOURNE_STORE_TEST__ZBSDATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;

REVOKE ROLE _HAVEN_PIPELINE_DEV__BLOOMREACH__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__BLUEYONDER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__COMMON_DBT_RETAIL_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__COMMON_DBT_RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__COMMON_DBT_SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__CRM_DATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__ESSENCEMEDIA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__FINANCE_CUBE_ERPX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__FRESHSALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__HAVEN_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__PX0006_BLUEYONDER_PRICER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__PX0007_PITCH_PERFECT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__RETAIL_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__SAGACITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_DEV__SYSTEM_FUNCTIONS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__BLOOMREACH__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__BLUEYONDER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__COMMON_DBT_RETAIL_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__COMMON_DBT_RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__COMMON_DBT_SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__CRM_DATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__ESSENCEMEDIA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__FINANCE_CUBE_ERPX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__FRESHSALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__HAVEN_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__PX0006_BLUEYONDER_PRICER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__PX0007_PITCH_PERFECT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__RETAIL_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__SAGACITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_PROD__SYSTEM_FUNCTIONS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__BLOOMREACH__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__BLUEYONDER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__COMMON_DBT_RETAIL_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__COMMON_DBT_RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__COMMON_DBT_SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__CRM_DATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__ESSENCEMEDIA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__FINANCE_CUBE_ERPX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__FRESHSALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__HAVEN_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__PX0006_BLUEYONDER_PRICER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__PX0007_PITCH_PERFECT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__RETAIL_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__SAGACITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_QAT__SYSTEM_FUNCTIONS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__BLOOMREACH__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__BLUEYONDER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__COMMON_DBT_RETAIL_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__COMMON_DBT_RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__COMMON_DBT_SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__CRM_DATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__ESSENCEMEDIA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__FINANCE_CUBE_ERPX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__FRESHSALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__HAVEN_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__PX0006_BLUEYONDER_PRICER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__PX0007_PITCH_PERFECT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__RETAIL_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__SAGACITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_PIPELINE_TEST__SYSTEM_FUNCTIONS__READER FROM ROLE HAVEN_DATA_TRANSFORM;

REVOKE ROLE _HAVEN_STAGING_DEV__DECISION_MATRIX_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_DEV__DMS_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_DEV__REVENUE_MANAGEMENT_OUTPUT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_DEV__REVENUE_MANAGEMENT_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_DEV__RM_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_DEV__SEAWARE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_DEV__TROOPER2__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_DEV__TROOPER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_PROD__DECISION_MATRIX_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_PROD__DMS_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_PROD__REVENUE_MANAGEMENT_OUTPUT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_PROD__REVENUE_MANAGEMENT_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_PROD__RM_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_PROD__SEAWARE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_PROD__TROOPER2__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_PROD__TROOPER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_QAT__DECISION_MATRIX_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_QAT__DMS_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_QAT__REVENUE_MANAGEMENT_OUTPUT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_QAT__REVENUE_MANAGEMENT_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_QAT__RM_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_QAT__SEAWARE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_QAT__TROOPER2__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_QAT__TROOPER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_TEST__DECISION_MATRIX_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_TEST__DMS_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_TEST__REVENUE_MANAGEMENT_OUTPUT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_TEST__REVENUE_MANAGEMENT_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_TEST__RM_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_TEST__SEAWARE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_TEST__TROOPER2__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STAGING_TEST__TROOPER__READER FROM ROLE HAVEN_DATA_TRANSFORM;

REVOKE ROLE _HAVEN_STORE_DEV__ACTIVITIES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__ALIGN_ALYTICS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__AVAILABILITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__BUDGET_DATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__CARAVANS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__CARAVAN_SALES_FUNNEL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__CARAVAN_SALES_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__CARAVAN_SALES_TEST__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__CARAVAN_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__COMMERCIAL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__COMMON_RESTRICTED__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__COMMON__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__COMPETITOR__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__CONSENT_AND_PREFERENCE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__COUPA_CUBE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__DIGITAL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__EXPERIAN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__FINANCE_CUBE_ERPX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__FINANCE_SHARED_SERVICES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__FINANCE_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__FINANCIAL_CUBE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__HAVEN_ACCOUNTANTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__HAVEN_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__HOLIDAY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__IDENTITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__INTEGRATION__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__JDAADMIN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__JDAPREP__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__KMSREPORTING_COMPLEX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__KPMG_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__KPMG_VIEWS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__MA_MART__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__OCANDC__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__OUTPUT_HISTORY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PARK_OPERATIONS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PAYMENTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PERFORMANCE_MARKETING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PITCH_PERFECT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PLAYPASS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PLOTREPRS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PLOT_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PRICER_DECISION_MATRIX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PRICER_FORECAST__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PRICER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__PROSPECTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__REVENUE_MANAGEMENT_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__REVENUE_MANAGEMENT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__RM_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__SALES_PLANNER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__SASMART__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__SAS_SCV__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__SEAWARE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__STORAGE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__TROOPER2__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__TROOPER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__TRPREPRS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__WORKFORCE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__ZBSDATA_COMPLEX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__ZBSDATA_RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__ZBSDATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_DEV__ZONAL_STOCK_REPORTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__ACTIVITIES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__ALIGN_ALYTICS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__AVAILABILITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__BUDGET_DATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__CARAVANS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__CARAVAN_SALES_FUNNEL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__CARAVAN_SALES_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__CARAVAN_SALES_TEST__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__CARAVAN_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__COMMERCIAL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__COMMON_RESTRICTED__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__COMMON__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__COMPETITOR__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__CONSENT_AND_PREFERENCE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__COUPA_CUBE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__DIGITAL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__EXPERIAN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__FINANCE_CUBE_ERPX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__FINANCE_SHARED_SERVICES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__FINANCE_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__FINANCIAL_CUBE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__HAVEN_ACCOUNTANTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__HAVEN_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__HOLIDAYS_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__HOLIDAY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__IDENTITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__INTEGRATION__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__JDAADMIN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__JDAPREP__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__KMSREPORTING_COMPLEX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__KPMG_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__KPMG_VIEWS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__MA_MART__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__OCANDC__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__OUTPUT_HISTORY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PARK_OPERATIONS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PAYMENTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PERFORMANCE_MARKETING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PITCH_PERFECT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PLAYPASS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PLOTREPRS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PLOT_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PRICER_DECISION_MATRIX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PRICER_FORECAST__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PRICER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__PROSPECTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__REVENUE_MANAGEMENT_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__REVENUE_MANAGEMENT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__RM_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__SALES_PLANNER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__SASMART__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__SAS_SCV__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__SEAWARE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__STORAGE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__TROOPER2__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__TROOPER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__TRPREPRS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__WORKFORCE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__ZBSDATA_COMPLEX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__ZBSDATA_RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__ZBSDATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_PROD__ZONAL_STOCK_REPORTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__ACTIVITIES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__ALIGN_ALYTICS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__AVAILABILITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__BUDGET_DATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__CARAVANS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__CARAVAN_SALES_FUNNEL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__CARAVAN_SALES_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__CARAVAN_SALES_TEST__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__CARAVAN_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__COMMERCIAL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__COMMON_RESTRICTED__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__COMMON__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__COMPETITOR__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__CONSENT_AND_PREFERENCE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__COUPA_CUBE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__DIGITAL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__EXPERIAN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__FINANCE_CUBE_ERPX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__FINANCE_SHARED_SERVICES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__FINANCE_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__FINANCIAL_CUBE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__HAVEN_ACCOUNTANTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__HAVEN_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__HOLIDAY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__IDENTITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__INTEGRATION__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__JDAADMIN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__JDAPREP__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__KMSREPORTING_COMPLEX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__KPMG_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__KPMG_VIEWS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__MA_MART__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__OCANDC__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__OUTPUT_HISTORY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PARK_OPERATIONS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PAYMENTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PERFORMANCE_MARKETING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PITCH_PERFECT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PLAYPASS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PLOTREPRS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PLOT_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PRICER_DECISION_MATRIX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PRICER_FORECAST__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PRICER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__PROSPECTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__REVENUE_MANAGEMENT_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__REVENUE_MANAGEMENT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__RM_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__SALES_PLANNER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__SASMART__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__SAS_SCV__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__SEAWARE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__STORAGE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__TROOPER2__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__TROOPER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__TRPREPRS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__WORKFORCE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__ZBSDATA_COMPLEX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__ZBSDATA_RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__ZBSDATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_QAT__ZONAL_STOCK_REPORTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__ACTIVITIES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__ALIGN_ALYTICS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__AVAILABILITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__BUDGET_DATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__CARAVANS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__CARAVAN_SALES_FUNNEL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__CARAVAN_SALES_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__CARAVAN_SALES_TEST__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__CARAVAN_SALES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__COMMERCIAL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__COMMON_RESTRICTED__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__COMMON__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__COMPETITOR__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__CONSENT_AND_PREFERENCE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__COUPA_CUBE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__DIGITAL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__EXPERIAN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__FINANCE_CUBE_ERPX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__FINANCE_SHARED_SERVICES__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__FINANCE_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__FINANCIAL_CUBE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__HAVEN_ACCOUNTANTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__HAVEN_STAGING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__HOLIDAYS_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__HOLIDAY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__IDENTITY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__INTEGRATION__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__JDAADMIN__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__JDAPREP__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__KMSREPORTING_COMPLEX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__KPMG_UAT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__KPMG_VIEWS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__MA_MART__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__OCANDC__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__OUTPUT_HISTORY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PARK_OPERATIONS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PAYMENTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PERFORMANCE_MARKETING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PITCH_PERFECT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PLAYPASS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PLOTREPRS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PLOT_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PRICER_DECISION_MATRIX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PRICER_FORECAST__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PRICER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__PROSPECTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__REVENUE_MANAGEMENT_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__REVENUE_MANAGEMENT__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__RM_REPORTING__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__SALES_PLANNER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__SASMART__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__SAS_SCV__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__SEAWARE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__STORAGE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__SURVEY__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__TROOPER2__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__TROOPER__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__TRPREPRS__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__WORKFORCE__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__ZBSDATA_COMPLEX__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__ZBSDATA_RETAIL__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__ZBSDATA__READER FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE ROLE _HAVEN_STORE_TEST__ZONAL_STOCK_REPORTS__READER FROM ROLE HAVEN_DATA_TRANSFORM;

REVOKE operate on TASK HAVEN_STORE_DEV.DIGITAL.PX0001_DIGITAL_EXTRACT  FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE operate on TASK  HAVEN_STORE_PROD.DIGITAL.PX0001_DIGITAL_EXTRACT  FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE operate on TASK  HAVEN_STORE_QAT.DIGITAL.PX0001_DIGITAL_EXTRACT  FROM ROLE HAVEN_DATA_TRANSFORM;
REVOKE operate on TASK  HAVEN_STORE_TEST.DIGITAL.PX0001_DIGITAL_EXTRACT  FROM ROLE HAVEN_DATA_TRANSFORM;

show grants to role HAVEN_DATA_TRANSFORM;

-- 27/02/2025

USE ROLE dba;

-- finance warehouse

use role sysadmin;

CREATE WAREHOUSE haven_dbt_transform_finance_dev_warehouse_medium WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE haven_dbt_transform_finance_qat_warehouse_medium WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE haven_dbt_transform_finance_prod_warehouse_medium WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

use role useradmin;

create role _haven_dbt_transform_finance_dev_warehouse_medium__operator;
create role _haven_dbt_transform_finance_dev_warehouse_medium__usage;
create role _haven_dbt_transform_finance_qat_warehouse_medium__operator;
create role _haven_dbt_transform_finance_qat_warehouse_medium__usage;
create role _haven_dbt_transform_finance_prod_warehouse_medium__operator;
create role _haven_dbt_transform_finance_prod_warehouse_medium__usage;

USE ROLE securityadmin;

grant usage, monitor on warehouse haven_dbt_transform_finance_dev_warehouse_medium to role _haven_dbt_transform_finance_dev_warehouse_medium__usage;
grant role _haven_dbt_transform_finance_dev_warehouse_medium__usage to role _haven_dbt_transform_finance_dev_warehouse_medium__operator;
grant operate, modify on warehouse haven_dbt_transform_finance_dev_warehouse_medium to role _haven_dbt_transform_finance_dev_warehouse_medium__operator;
grant usage, monitor on warehouse haven_dbt_transform_finance_qat_warehouse_medium to role _haven_dbt_transform_finance_qat_warehouse_medium__usage;
grant role _haven_dbt_transform_finance_qat_warehouse_medium__usage to role _haven_dbt_transform_finance_qat_warehouse_medium__operator;
grant operate, modify on warehouse haven_dbt_transform_finance_qat_warehouse_medium to role _haven_dbt_transform_finance_qat_warehouse_medium__operator;
grant usage, monitor on warehouse haven_dbt_transform_finance_prod_warehouse_medium to role _haven_dbt_transform_finance_prod_warehouse_medium__usage;
grant role _haven_dbt_transform_finance_prod_warehouse_medium__usage to role _haven_dbt_transform_finance_prod_warehouse_medium__operator;
grant operate, modify on warehouse haven_dbt_transform_finance_prod_warehouse_medium to role _haven_dbt_transform_finance_prod_warehouse_medium__operator;

-- SHOW ROLES LIKE '%finance%';

grant role _haven_dbt_transform_finance_dev_warehouse_medium__usage to role haven_dbt_transform_finance_dev;
grant role _haven_dbt_transform_finance_qat_warehouse_medium__usage to role haven_dbt_transform_finance_qat;
grant role _haven_dbt_transform_finance_prod_warehouse_medium__usage to role haven_dbt_transform_finance_prod;

-- pipeline warehouse


use role sysadmin;

CREATE WAREHOUSE haven_dbt_transform_pipelines_dev_warehouse_medium WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE haven_dbt_transform_pipelines_qat_warehouse_medium WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE haven_dbt_transform_pipelines_prod_warehouse_medium WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD' 
	AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

use role useradmin;

create role _haven_dbt_transform_pipelines_dev_warehouse_medium__operator;
create role _haven_dbt_transform_pipelines_dev_warehouse_medium__usage;
create role _haven_dbt_transform_pipelines_qat_warehouse_medium__operator;
create role _haven_dbt_transform_pipelines_qat_warehouse_medium__usage;
create role _haven_dbt_transform_pipelines_prod_warehouse_medium__operator;
create role _haven_dbt_transform_pipelines_prod_warehouse_medium__usage;

USE ROLE securityadmin;

grant usage, monitor on warehouse haven_dbt_transform_pipelines_dev_warehouse_medium to role _haven_dbt_transform_pipelines_dev_warehouse_medium__usage;
grant role _haven_dbt_transform_pipelines_dev_warehouse_medium__usage to role _haven_dbt_transform_pipelines_dev_warehouse_medium__operator;
grant operate, modify on warehouse haven_dbt_transform_pipelines_dev_warehouse_medium to role _haven_dbt_transform_pipelines_dev_warehouse_medium__operator;
grant usage, monitor on warehouse haven_dbt_transform_pipelines_qat_warehouse_medium to role _haven_dbt_transform_pipelines_qat_warehouse_medium__usage;
grant role _haven_dbt_transform_pipelines_qat_warehouse_medium__usage to role _haven_dbt_transform_pipelines_qat_warehouse_medium__operator;
grant operate, modify on warehouse haven_dbt_transform_pipelines_qat_warehouse_medium to role _haven_dbt_transform_pipelines_qat_warehouse_medium__operator;
grant usage, monitor on warehouse haven_dbt_transform_pipelines_prod_warehouse_medium to role _haven_dbt_transform_pipelines_prod_warehouse_medium__usage;
grant role _haven_dbt_transform_pipelines_prod_warehouse_medium__usage to role _haven_dbt_transform_pipelines_prod_warehouse_medium__operator;
grant operate, modify on warehouse haven_dbt_transform_pipelines_prod_warehouse_medium to role _haven_dbt_transform_pipelines_prod_warehouse_medium__operator;

SHOW ROLES LIKE '%pipelines%';

grant role _haven_dbt_transform_pipelines_dev_warehouse_medium__usage to role haven_dbt_transform_pipelines_dev;
grant role _haven_dbt_transform_pipelines_qat_warehouse_medium__usage to role haven_dbt_transform_pipelines_qat;
grant role _haven_dbt_transform_pipelines_prod_warehouse_medium__usage to role haven_dbt_transform_pipelines_prod;

