-- HAVEN_BASE.FINANCIAL_CUBE.DIM_ANALYSIS_ELEMENT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_ANALYSIS_ELEMENT(
	ANALYSIS_ELEMENT_REF,
	ANALYSIS_ELEMENT
) as select ANALYSIS_ELEMENT_REF,ANALYSIS_ELEMENT from BOURNE_RAW.FINANCIAL_CUBE.DIM_ANALYSIS_ELEMENT;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD(
	ARRIVAL_PERIOD_REF,
	ARRIVAL_PERIOD_NUMBER,
	ARRIVAL_PERIOD_NAME
) as select ARRIVAL_PERIOD_REF,ARRIVAL_PERIOD_NUMBER,ARRIVAL_PERIOD_NAME from BOURNE_RAW.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD_CP source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD_CP(
	ARRIVAL_PERIOD_REF,
	ARRIVAL_PERIOD_NUMBER,
	ARRIVAL_PERIOD_NAME
) as select ARRIVAL_PERIOD_REF,ARRIVAL_PERIOD_NUMBER,ARRIVAL_PERIOD_NAME from BOURNE_RAW.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD_CP;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_STATUS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_STATUS(
	ARRIVAL_STATUS_REF,
	ARRIVAL_STATUS
) as select ARRIVAL_STATUS_REF,ARRIVAL_STATUS from BOURNE_RAW.FINANCIAL_CUBE.DIM_ARRIVAL_STATUS;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_BOOKINGSOURCE source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_BOOKINGSOURCE(
	BOOKINGSOURCE_REF,
	BOOKINGSOURCE,
	BOOKINGSOURCE_TITLE
) as select BOOKINGSOURCE_REF,BOOKINGSOURCE,BOOKINGSOURCE_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_BOOKINGSOURCE;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_BRAND source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_BRAND(
	BRAND_REF,
	BRAND_TITLE
) as select BRAND_REF,BRAND_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_BRAND  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_CALENDAR source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_CALENDAR(
	DAY_IDX,
	CALENDAR_DATE,
	CALENDAR_WEEK,
	CALENDAR_MONTH,
	CALENDAR_QUATER,
	CALENDAR_YEAR,
	STAT_WEEK_END_DATE,
	STAT_PERIOD,
	STAT_MONTH,
	STAT_YEAR
) as select DAY_IDX,CALENDAR_DATE,CALENDAR_WEEK,CALENDAR_MONTH,CALENDAR_QUATER,CALENDAR_YEAR,STAT_WEEK_END_DATE,STAT_PERIOD,STAT_MONTH,STAT_YEAR from BOURNE_RAW.FINANCIAL_CUBE.DIM_CALENDAR;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_CASHFLOW source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_CASHFLOW(
	CASHFLOW_REF,
	CASHFLOW,
	CASHFLOW_TITLE
) as select CASHFLOW_REF,CASHFLOW,CASHFLOW_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_CASHFLOW;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_CPARKPL source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_CPARKPL(
	CPARKPL_REF,
	CPARKPL,
	CPARKPL_TITLE
) as select CPARKPL_REF,CPARKPL,CPARKPL_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_CPARKPL;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_DEBT_RANGE source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_DEBT_RANGE(
	DEBT_RANGE_REF,
	MIN_VALUE,
	MAX_VALUE,
	DEBT_RANGE_TITLE
) as select DEBT_RANGE_REF,MIN_VALUE,MAX_VALUE,DEBT_RANGE_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_DEBT_RANGE;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_DEPARTMENT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_DEPARTMENT(
	DEPARTMENT_REF,
	DEPARTMENT,
	DEPARTMENT_TITLE
) as select DEPARTMENT_REF,DEPARTMENT,DEPARTMENT_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_DEPARTMENT;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_PRODUCT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_PRODUCT(
	HOLIDAY_PRODUCT_REF,
	HOLIDAY_PRODUCT
) as select HOLIDAY_PRODUCT_REF,HOLIDAY_PRODUCT from BOURNE_RAW.FINANCIAL_CUBE.DIM_HOLIDAY_PRODUCT;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_YEAR source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_YEAR(
	HOLIDAY_YEAR_REF,
	HOLIDAY_YEAR,
	TROOPER_SEASON
) as select HOLIDAY_YEAR_REF,HOLIDAY_YEAR,TROOPER_SEASON from BOURNE_RAW.FINANCIAL_CUBE.DIM_HOLIDAY_YEAR;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_HOLIDAYDURATION source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_HOLIDAYDURATION(
	HOLIDAYDURATION_REF,
	HOLIDAYDURATION,
	HOLIDAYDURATION_TITLE
) as select HOLIDAYDURATION_REF,HOLIDAYDURATION,HOLIDAYDURATION_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_HOLIDAYDURATION;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_LEDGER source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_LEDGER(
	LEDGER_REF,
	BRAND_REF,
	LEDGER,
	LEDGER_TITLE
) as select LEDGER_REF,BRAND_REF,LEDGER,LEDGER_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_LEDGER  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_LEDGER_ACCOUNT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_LEDGER_ACCOUNT(
	LEDGER_ACCOUNT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT,
	LEDGER_ACCOUNT_TITLE
) as select LEDGER_ACCOUNT_REF,LEDGER_REF,LEDGER_ACCOUNT,LEDGER_ACCOUNT_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_LEDGER_ACCOUNT;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_LIMBO source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_LIMBO(
	LIMBO_REF,
	LIMBO_VALUE,
	LIMBO_DESCRIPTION
) as select LIMBO_REF,LIMBO_VALUE,LIMBO_DESCRIPTION from BOURNE_RAW.FINANCIAL_CUBE.DIM_LIMBO;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_LOCATION source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_LOCATION(
	LOCATION_REF,
	BRAND_REF,
	BRAND_TITLE,
	SITE_REF,
	SITE_CODE,
	SITE_NAME,
	SITE_OPS_DIRECTOR,
	AREA_CODE,
	AREA_NAME,
	ZONE_CODE,
	ZONE_NAME,
	PLOT_PITCH_ID,
	PITCH_NAME
) as select LOCATION_REF,BRAND_REF,BRAND_TITLE,SITE_REF,SITE_CODE,SITE_NAME,SITE_OPS_DIRECTOR,AREA_CODE,AREA_NAME,ZONE_CODE,ZONE_NAME,PLOT_PITCH_ID,PITCH_NAME from BOURNE_RAW.FINANCIAL_CUBE.DIM_LOCATION  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_NOMINAL source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_NOMINAL(
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER3_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	NOMINAL,
	NOMINAL_CODE,
	NOMINAL_TITLE,
	DISABLE,
	CPARKPL_REF
) as select NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER3_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,NOMINAL,NOMINAL_CODE,NOMINAL_TITLE,DISABLE,CPARKPL_REF from BOURNE_RAW.FINANCIAL_CUBE.DIM_NOMINAL  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PERIOD source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PERIOD(
	PERIOD_REF,
	STATYEAR,
	STATMONTH,
	STATPERIOD,
	STATPERIODLY,
	WEEKENDDATE
) as select PERIOD_REF,STATYEAR,STATMONTH,STATPERIOD,STATPERIODLY,WEEKENDDATE from BOURNE_RAW.FINANCIAL_CUBE.DIM_PERIOD;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_CARAVAN_SALES source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_CARAVAN_SALES(
	CARAVAN_SALES_REF,
	BRAND_REF,
	SALES_CSI_NO,
	SALES_TYPE
) as select CARAVAN_SALES_REF,BRAND_REF,SALES_CSI_NO,SALES_TYPE from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_CARAVAN_SALES  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_LETTING_CATAGORY source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_LETTING_CATAGORY(
	LETTING_CATAGORY_REF,
	BRAND_REF,
	LETTING_CATAGORY_CODE,
	LETTING_CATAGORY_TITLE
) as select LETTING_CATAGORY_REF,BRAND_REF,LETTING_CATAGORY_CODE,LETTING_CATAGORY_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_LETTING_CATAGORY  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT(
	OWNER_ACCOUNT_REF,
	BRAND_REF,
	ACCOUNT_NO,
	OWNER_ID,
	OWNER_NAME,
	OWNER_ADDRESS1,
	OWNER_ADDRESS2,
	OWNER_ADDRESS3,
	OWNER_ADDRESS4,
	OWNER_POSTCODE
) as select OWNER_ACCOUNT_REF,BRAND_REF,ACCOUNT_NO,OWNER_ID,OWNER_NAME,OWNER_ADDRESS1,OWNER_ADDRESS2,OWNER_ADDRESS3,OWNER_ADDRESS4,OWNER_POSTCODE from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT_NEW source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT_NEW(
	OWNER_ACCOUNT_REF,
	BRAND_REF,
	ACCOUNT_NO,
	OWNER_ID,
	OWNER_NAME,
	OWNER_ADDRESS1,
	OWNER_ADDRESS2,
	OWNER_ADDRESS3,
	OWNER_ADDRESS4,
	OWNER_POSTCODE,
	SITE_FEES
) as select OWNER_ACCOUNT_REF,BRAND_REF,ACCOUNT_NO,OWNER_ID,OWNER_NAME,OWNER_ADDRESS1,OWNER_ADDRESS2,OWNER_ADDRESS3,OWNER_ADDRESS4,OWNER_POSTCODE,SITE_FEES from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT_NEW  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH(
	PITCH_REF,
	BRAND_REF,
	SITE_REF,
	PITCH_NO,
	AREA_CODE,
	AREA_NAME,
	ZONE_CODE,
	ZONE_NAME,
	PITCH_TYPE,
	PLOT_PITCH_ID
) as select PITCH_REF,BRAND_REF,SITE_REF,PITCH_NO,AREA_CODE,AREA_NAME,ZONE_CODE,ZONE_NAME,PITCH_TYPE,PLOT_PITCH_ID from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_PITCH  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS(
	PITCH_STATUS_REF,
	BRAND_REF,
	PITCH_STATUS_CODE,
	PITCH_STATUS_TITLE
) as select PITCH_STATUS_REF,BRAND_REF,PITCH_STATUS_CODE,PITCH_STATUS_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS_NEW source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS_NEW(
	PITCH_STATUS_REF,
	PITCH_STATUS_CODE,
	PITCH_STATUS_TITLE
) as select PITCH_STATUS_REF,PITCH_STATUS_CODE,PITCH_STATUS_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS_NEW;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_VAN source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_VAN(
	VAN_REF,
	BRAND_REF,
	VAN_NO,
	VAN_MAKE,
	VAN_MODEL,
	VAN_YEAR_MADE,
	VAN_LENGTH,
	VAN_WIDTH,
	VAN_TYPE
) as select VAN_REF,BRAND_REF,VAN_NO,VAN_MAKE,VAN_MODEL,VAN_YEAR_MADE,VAN_LENGTH,VAN_WIDTH,VAN_TYPE from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_VAN  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_VAN_DELIVERED_STATUS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PLOT_VAN_DELIVERED_STATUS(
	VAN_DELIVERY_REF,
	VAN_DELIVERY_STATUS
) as select VAN_DELIVERY_REF,VAN_DELIVERY_STATUS from BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_VAN_DELIVERED_STATUS;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_PRODUCT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_PRODUCT(
	PRODUCT_REF,
	PRODUCT
) as select PRODUCT_REF,PRODUCT from BOURNE_RAW.FINANCIAL_CUBE.DIM_PRODUCT;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_RETAIL_INCOME_GROUP source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_RETAIL_INCOME_GROUP(
	RETAIL_INCOME_GROUP_REF,
	NAME,
	LEVEL1_NAME
) as select RETAIL_INCOME_GROUP_REF,NAME,LEVEL1_NAME from BOURNE_RAW.FINANCIAL_CUBE.DIM_RETAIL_INCOME_GROUP;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_RETAIL_WEEKS_TYPE source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_RETAIL_WEEKS_TYPE(
	RETAIL_SPEND_TYPE_REF,
	DESCRIPTION
) as select RETAIL_SPEND_TYPE_REF,DESCRIPTION from BOURNE_RAW.FINANCIAL_CUBE.DIM_RETAIL_WEEKS_TYPE;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_SALES_CHANNEL source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_SALES_CHANNEL(
	SALES_CHANNEL_REF,
	SALES_CHANNEL,
	TROOPER_CHANNEL,
	BUTLINS_CHANNEL,
	BUTLINS_CHANNEL_2,
	WARNER_CHANNEL,
	WARNER_CHANNEL_2
) as select SALES_CHANNEL_REF,SALES_CHANNEL,TROOPER_CHANNEL,BUTLINS_CHANNEL,BUTLINS_CHANNEL_2,WARNER_CHANNEL,WARNER_CHANNEL_2 from BOURNE_RAW.FINANCIAL_CUBE.DIM_SALES_CHANNEL;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_SITE source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_SITE(
	SITE_REF,
	BRAND_REF,
	SITE_CODE,
	SITE_TROOPER_CODE,
	SITE_NAME,
	SITE_REGION_REF,
	SITE_OPS_DIRECTOR,
	SITE_GENERAL_MANAGER,
	SITE_SALES_MANAGER,
	SITE_COMPLEX_MANAGER,
	SITE_SHOP_MANAGER,
	SITE_SPORTS_MANAGER,
	SITE_ENTS_MANAGER,
	SITE_HOLIDAY_SALES_MANAGER,
	SITE_CATERING_MANAGER,
	SITE_STATUS_REF,
	SITE_ACCOMODATION_MANAGER,
	STATUTORY_CO_1,
	STATUTORY_CO_2,
	STATUTORY_CO_3,
	STATUTORY_CO_4,
	STATUTORY_CO_5,
	STATUTORY_CO_6,
	COMPANY_CODE
) as select SITE_REF,BRAND_REF,SITE_CODE,SITE_TROOPER_CODE,SITE_NAME,SITE_REGION_REF,SITE_OPS_DIRECTOR,SITE_GENERAL_MANAGER,SITE_SALES_MANAGER,SITE_COMPLEX_MANAGER,SITE_SHOP_MANAGER,SITE_SPORTS_MANAGER,SITE_ENTS_MANAGER,SITE_HOLIDAY_SALES_MANAGER,SITE_CATERING_MANAGER,SITE_STATUS_REF,SITE_ACCOMODATION_MANAGER,STATUTORY_CO_1,STATUTORY_CO_2,STATUTORY_CO_3,STATUTORY_CO_4,STATUTORY_CO_5,STATUTORY_CO_6,COMPANY_CODE from BOURNE_RAW.FINANCIAL_CUBE.DIM_SITE  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_SITE_FEE_BANDS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_SITE_FEE_BANDS(
	SITE_FEE_BAND_REF,
	SITE_FEE_BAND_NAME,
	MIN_VALUE,
	MAX_VALUE
) as select SITE_FEE_BAND_REF,SITE_FEE_BAND_NAME,MIN_VALUE,MAX_VALUE from BOURNE_RAW.FINANCIAL_CUBE.DIM_SITE_FEE_BANDS;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_STATSSUM source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_STATSSUM(
	STATSSUM_REF,
	STATSSUM_PAGE,
	STATSSUM_SUBSECTION,
	STATSSUM_TITLE,
	STATSSUM,
	STATSSUM_ORDERBY
) as select STATSSUM_REF,STATSSUM_PAGE,STATSSUM_SUBSECTION,STATSSUM_TITLE,STATSSUM,STATSSUM_ORDERBY from BOURNE_RAW.FINANCIAL_CUBE.DIM_STATSSUM;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_SUB_DEPARTMENT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_SUB_DEPARTMENT(
	SUB_DEPARTMENT_REF,
	SUB_DEPARTMENT,
	SUB_DEPARTMENT_TITLE
) as select SUB_DEPARTMENT_REF,SUB_DEPARTMENT,SUB_DEPARTMENT_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_SUB_DEPARTMENT;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_TRADITIONAL_P_AND_L source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_TRADITIONAL_P_AND_L(
	TRADITIONAL_P_AND_L_REF,
	TRADITIONAL_P_AND_L,
	TRADITIONAL_P_AND_L_TITLE
) as select TRADITIONAL_P_AND_L_REF,TRADITIONAL_P_AND_L,TRADITIONAL_P_AND_L_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_TRADITIONAL_P_AND_L;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_VERSION source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_VERSION(
	VERSION_REF,
	VERSION_TITLE
) as select VERSION_REF,VERSION_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_VERSION;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_WAGES_ANALYSIS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_WAGES_ANALYSIS(
	WAGES_ANALYSIS_REF,
	WAGES_ANALYSIS,
	WAGES_ANALYSIS_TITLE
) as select WAGES_ANALYSIS_REF,WAGES_ANALYSIS,WAGES_ANALYSIS_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_WAGES_ANALYSIS;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_WAGES_STAFFCONTRACT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_WAGES_STAFFCONTRACT(
	WAGES_STAFFCONTRACT_REF,
	WAGES_STAFFCONTRACT,
	WAGES_STAFFCONTRACT_TITLE
) as select WAGES_STAFFCONTRACT_REF,WAGES_STAFFCONTRACT,WAGES_STAFFCONTRACT_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_WAGES_STAFFCONTRACT;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_WAGES_SUMMARY source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_WAGES_SUMMARY(
	WAGES_SUMMARY_REF,
	WAGES_SUMMARY,
	WAGES_SUMMARY_TITLE
) as select WAGES_SUMMARY_REF,WAGES_SUMMARY,WAGES_SUMMARY_TITLE from BOURNE_RAW.FINANCIAL_CUBE.DIM_WAGES_SUMMARY;


-- HAVEN_BASE.FINANCIAL_CUBE.DIM_YESNO source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIM_YESNO(
	REF,
	YESNOVALUE,
	YESNOTEXT
) as select REF,YESNOVALUE,YESNOTEXT from BOURNE_RAW.FINANCIAL_CUBE.DIM_YESNO;


-- HAVEN_BASE.FINANCIAL_CUBE.DIMTIME source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.DIMTIME(
	PK_DATE,
	DATE_NAME,
	YEAR,
	YEAR_NAME,
	MONTH,
	MONTH_NAME,
	WEEK,
	WEEK_NAME,
	DAY_OF_YEAR,
	DAY_OF_YEAR_NAME,
	DAY_OF_MONTH,
	DAY_OF_MONTH_NAME,
	DAY_OF_WEEK,
	DAY_OF_WEEK_NAME,
	WEEK_OF_YEAR,
	WEEK_OF_YEAR_NAME,
	MONTH_OF_YEAR,
	MONTH_OF_YEAR_NAME,
	STATYEAR,
	STATPERIOD,
	STATMONTH
) as select PK_DATE,DATE_NAME,YEAR,YEAR_NAME,MONTH,MONTH_NAME,WEEK,WEEK_NAME,DAY_OF_YEAR,DAY_OF_YEAR_NAME,DAY_OF_MONTH,DAY_OF_MONTH_NAME,DAY_OF_WEEK,DAY_OF_WEEK_NAME,WEEK_OF_YEAR,WEEK_OF_YEAR_NAME,MONTH_OF_YEAR,MONTH_OF_YEAR_NAME,STATYEAR,STATPERIOD,STATMONTH from BOURNE_RAW.FINANCIAL_CUBE.DIMTIME;


-- HAVEN_BASE.FINANCIAL_CUBE.ETL_CONTROL source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.ETL_CONTROL(
	LAST_TRANSFER,
	LAST_DURATION
) as select LAST_TRANSFER,LAST_DURATION from BOURNE_RAW.FINANCIAL_CUBE.ETL_CONTROL;


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_BILLINGS_ANALYSIS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_BILLINGS_ANALYSIS(
	BUSINESSKEY,
	BRAND_REF,
	SITE_REF,
	HOLIDAY_PRODUCT_REF,
	VERSION_REF,
	PERIOD_REF,
	HOLIDAY_YEAR_REF,
	ANALYSIS_ELEMENT_REF,
	ARRIVAL_STATUS_REF,
	WEEK_BILLINGS_PRIORSEASON,
	WEEK_BILLINGS_CURRENTSEASON,
	YTD_BILLINGS_PRIORSEASON,
	YTD_BILLINGS_CURRENTSEASON,
	YEAR_BILLINGS_PRIORSEASON,
	WEEK_BILLINGS_BUDGET,
	YTD_BILLINGS_BUDGET,
	YEAR_BILLINGS_BUDGET,
	WEEK_WEEKS_PRIORSEASON,
	WEEK_WEEKS_CURRENTSEASON,
	YTD_WEEKS_PRIORSEASON,
	YTD_WEEKS_CURRENTSEASON,
	YEAR_WEEKS_PRIORSEASON,
	WEEK_WEEKS_BUDGET,
	YTD_WEEKS_BUDGET,
	YEAR_WEEKS_BUDGET
) as select BUSINESSKEY,BRAND_REF,SITE_REF,HOLIDAY_PRODUCT_REF,VERSION_REF,PERIOD_REF,HOLIDAY_YEAR_REF,ANALYSIS_ELEMENT_REF,ARRIVAL_STATUS_REF,WEEK_BILLINGS_PRIORSEASON,WEEK_BILLINGS_CURRENTSEASON,YTD_BILLINGS_PRIORSEASON,YTD_BILLINGS_CURRENTSEASON,YEAR_BILLINGS_PRIORSEASON,WEEK_BILLINGS_BUDGET,YTD_BILLINGS_BUDGET,YEAR_BILLINGS_BUDGET,WEEK_WEEKS_PRIORSEASON,WEEK_WEEKS_CURRENTSEASON,YTD_WEEKS_PRIORSEASON,YTD_WEEKS_CURRENTSEASON,YEAR_WEEKS_PRIORSEASON,WEEK_WEEKS_BUDGET,YTD_WEEKS_BUDGET,YEAR_WEEKS_BUDGET from BOURNE_RAW.FINANCIAL_CUBE.FACT_BILLINGS_ANALYSIS  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_BUDGET_TB source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_BUDGET_TB(
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT_REF,
	LEDGER3_REF,
	LEDGER3_ACCOUNT_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	VERSION_REF,
	PERIOD_REF,
	WEEK_VALUE,
	WEEK_USERVALUE,
	YTD_VALUE,
	YTD_USERVALUE,
	CPARKPL_REF
) as select NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER_ACCOUNT_REF,LEDGER3_REF,LEDGER3_ACCOUNT_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,VERSION_REF,PERIOD_REF,WEEK_VALUE,WEEK_USERVALUE,YTD_VALUE,YTD_USERVALUE,CPARKPL_REF from BOURNE_RAW.FINANCIAL_CUBE.FACT_BUDGET_TB  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_COMPLETEDHOLIDAYS_TB source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_COMPLETEDHOLIDAYS_TB(
	BRAND_REF,
	SITE_REF,
	VERSION_REF,
	PERIOD_REF,
	LETTING_CATAGORY_REF,
	HOLIDAY_PRODUCT_REF,
	BOOKINGSOURCE_REF,
	WEEK_ARRIVAL_DATE_REF,
	WEEK_DEPARTURE_DATE_REF,
	WEEK_DURATION_REF,
	LYPERIODLAG,
	UNIT_WEEK_VALUE,
	GUEST_WEEK_VALUE
) as select BRAND_REF,SITE_REF,VERSION_REF,PERIOD_REF,LETTING_CATAGORY_REF,HOLIDAY_PRODUCT_REF,BOOKINGSOURCE_REF,WEEK_ARRIVAL_DATE_REF,WEEK_DEPARTURE_DATE_REF,WEEK_DURATION_REF,LYPERIODLAG,UNIT_WEEK_VALUE,GUEST_WEEK_VALUE from BOURNE_RAW.FINANCIAL_CUBE.FACT_COMPLETEDHOLIDAYS_TB  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_HEAD_COUNTS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_HEAD_COUNTS(
	IDENT,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	PERIOD_REF,
	WAGES_SUMMARY_REF,
	ACTUAL_PERMANENTFTES,
	ACTUAL_SEASONALFTES,
	ACTUAL_TOTALFTES,
	BUDGET_PERMANENTFTES,
	BUDGET_SEASONALFTES,
	BUDGET_TOTALFTES,
	LASTYEAR_PERMANENTFTES,
	LASTYEAR_SEASONALFTES,
	LASTYEAR_TOTALFTES
) as select IDENT,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,PERIOD_REF,WAGES_SUMMARY_REF,ACTUAL_PERMANENTFTES,ACTUAL_SEASONALFTES,ACTUAL_TOTALFTES,BUDGET_PERMANENTFTES,BUDGET_SEASONALFTES,BUDGET_TOTALFTES,LASTYEAR_PERMANENTFTES,LASTYEAR_SEASONALFTES,LASTYEAR_TOTALFTES from BOURNE_RAW.FINANCIAL_CUBE.FACT_HEAD_COUNTS  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_HISTORIC_TB source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_HISTORIC_TB(
	IDENT,
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT_REF,
	LEDGER3_REF,
	LEDGER3_ACCOUNT_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	VERSION_REF,
	PERIOD_REF,
	WEEK_VALUE,
	WEEK_USERVALUE,
	WEEK_USERVALUEFIELD1,
	WEEK_USERVALUEFIELD2,
	WEEK_USERVALUEFIELD3,
	WEEK_USERVALUEFIELD4,
	LAST_4_WEEKS_VALUE,
	LAST_4__USERVALUE,
	LAST_4__USERVALUEFIELD1,
	LAST_4__USERVALUEFIELD2,
	LAST_4__USERVALUEFIELD3,
	LAST_4__USERVALUEFIELD4,
	YTD_VALUE,
	YTD_USERVALUE,
	YTD_USERVALUEFIELD1,
	YTD_USERVALUEFIELD2,
	YTD_USERVALUEFIELD3,
	YTD_USERVALUEFIELD4,
	CPARKPL_REF
) as select IDENT,NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER_ACCOUNT_REF,LEDGER3_REF,LEDGER3_ACCOUNT_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,VERSION_REF,PERIOD_REF,WEEK_VALUE,WEEK_USERVALUE,WEEK_USERVALUEFIELD1,WEEK_USERVALUEFIELD2,WEEK_USERVALUEFIELD3,WEEK_USERVALUEFIELD4,LAST_4_WEEKS_VALUE,LAST_4__USERVALUE,LAST_4__USERVALUEFIELD1,LAST_4__USERVALUEFIELD2,LAST_4__USERVALUEFIELD3,LAST_4__USERVALUEFIELD4,YTD_VALUE,YTD_USERVALUE,YTD_USERVALUEFIELD1,YTD_USERVALUEFIELD2,YTD_USERVALUEFIELD3,YTD_USERVALUEFIELD4,CPARKPL_REF from BOURNE_RAW.FINANCIAL_CUBE.FACT_HISTORIC_TB  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_HOLIDAY_PERIODS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_HOLIDAY_PERIODS(
	BUSINESSKEY,
	BRAND_REF,
	SITE_REF,
	HOLIDAY_PRODUCT_REF,
	VERSION_REF,
	PERIOD_REF,
	HOLIDAY_YEAR_REF,
	ARRIVAL_PERIOD_REF,
	ARRIVAL_PERIOD_REF_7,
	UNITWEEKS_CURRENTSEASON,
	GUESTWEEKS_CURRENTSEASON,
	BILLINGS_CURRENTSEASON,
	UNITWEEKS_BUDGET,
	GUESTWEEKS_BUDGET,
	BILLINGS_BUDGET,
	UNITWEEKS_PRIORSEASON,
	GUESTWEEKS_PRIORSEASON,
	BILLINGS_PRIORSEASON,
	UNITWEEKS_YEAREND_PRIORSEASON,
	GUESTWEEKS_YEAREND_PRIORSEASON,
	BILLINGS_YEAREND_PRIORSEASON,
	UNITS_CAPACITY,
	UNITS_SOLD
) as select BUSINESSKEY,BRAND_REF,SITE_REF,HOLIDAY_PRODUCT_REF,VERSION_REF,PERIOD_REF,HOLIDAY_YEAR_REF,ARRIVAL_PERIOD_REF,ARRIVAL_PERIOD_REF_7,UNITWEEKS_CURRENTSEASON,GUESTWEEKS_CURRENTSEASON,BILLINGS_CURRENTSEASON,UNITWEEKS_BUDGET,GUESTWEEKS_BUDGET,BILLINGS_BUDGET,UNITWEEKS_PRIORSEASON,GUESTWEEKS_PRIORSEASON,BILLINGS_PRIORSEASON,UNITWEEKS_YEAREND_PRIORSEASON,GUESTWEEKS_YEAREND_PRIORSEASON,BILLINGS_YEAREND_PRIORSEASON,UNITS_CAPACITY,UNITS_SOLD from BOURNE_RAW.FINANCIAL_CUBE.FACT_HOLIDAY_PERIODS  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_HOLIDAYS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_HOLIDAYS(
	IDENT,
	BUSINESSKEY,
	BRAND_REF,
	SITE_REF,
	HOLIDAY_PRODUCT_REF,
	VERSION_REF,
	PERIOD_REF,
	HOLIDAY_YEAR_REF,
	SALES_CHANNEL_REF,
	WEEK_NETTBILLINGS_CURRENTSEASON,
	WEEK_COMMISSIONS_CURRENTSEASON,
	WEEK_GROSSBILLINGS_CURRENTSEASON,
	WEEK_UNITWEEKS_CURRENTSEASON,
	WEEK_GUESTWEEKS_CURRENTSEASON,
	WEEK_NETTBILLINGS_BUDGET_CURRENTSEASON,
	WEEK_UNITWEEKS_BUDGET_CURRENTSEASON,
	WEEK_GUESTWEEKS_BUDGET_CURRENTSEASON,
	YTD_NETTBILLINGS_CURRENTSEASON,
	YTD_COMMISSIONS_CURRENTSEASON,
	YTD_GROSSBILLINGS_CURRENTSEASON,
	YTD_UNITWEEKS_CURRENTSEASON,
	YTD_GUESTWEEKS_CURRENTSEASON,
	YTD_NETTBILLINGS_BUDGET_CURRENTSEASON,
	YTD_UNITWEEKS_BUDGET_CURRENTSEASON,
	YTD_GUESTWEEKS_BUDGET_CURRENTSEASON,
	YEAR_NETTBILLINGS_BUDGET_CURRENTSEASON,
	YEAR_UNITWEEKS_BUDGET_CURRENTSEASON,
	YEAR_GUESTWEEKS_BUDGET_CURRENTSEASON,
	WEEK_NETTBILLINGS_PRIORSEASON,
	WEEK_COMMISSIONS_PRIORSEASON,
	WEEK_GROSSBILLINGS_PRIORSEASON,
	WEEK_UNITWEEKS_PRIORSEASON,
	WEEK_GUESTWEEKS_PRIORSEASON,
	YTD_NETTBILLINGS_PRIORSEASON,
	YTD_COMMISSIONS_PRIORSEASON,
	YTD_GROSSBILLINGS_PRIORSEASON,
	YTD_UNITWEEKS_PRIORSEASON,
	YTD_GUESTWEEKS_PRIORSEASON,
	YEAR_NETTBILLINGS_PRIORSEASON,
	YEAR_UNITWEEKS_PRIORSEASON,
	YEAR_GUESTWEEKS_PRIORSEASON,
	CARRIEDFORWARD_NETTBILLINGS_CURRENTSEASON,
	CARRIEDFORWARD_UNITWEEKS_CURRENTSEASON,
	CARRIEDFORWARD_GUESTWEEKS_CURRENTSEASON,
	CARRIEDFORWARD_NETTBILLINGS_PRIORSEASON,
	CARRIEDFORWARD_UNITWEEKS_PRIORSEASON,
	CARRIEDFORWARD_GUESTWEEKS_PRIORSEASON,
	CARRIEDFORWARD_NETTBILLINGS_BUDGET,
	CARRIEDFORWARD_UNITWEEKS_BUDGET,
	CARRIEDFORWARD_GUESTWEEKS_BUDGET
) as select IDENT,BUSINESSKEY,BRAND_REF,SITE_REF,HOLIDAY_PRODUCT_REF,VERSION_REF,PERIOD_REF,HOLIDAY_YEAR_REF,SALES_CHANNEL_REF,WEEK_NETTBILLINGS_CURRENTSEASON,WEEK_COMMISSIONS_CURRENTSEASON,WEEK_GROSSBILLINGS_CURRENTSEASON,WEEK_UNITWEEKS_CURRENTSEASON,WEEK_GUESTWEEKS_CURRENTSEASON,WEEK_NETTBILLINGS_BUDGET_CURRENTSEASON,WEEK_UNITWEEKS_BUDGET_CURRENTSEASON,WEEK_GUESTWEEKS_BUDGET_CURRENTSEASON,YTD_NETTBILLINGS_CURRENTSEASON,YTD_COMMISSIONS_CURRENTSEASON,YTD_GROSSBILLINGS_CURRENTSEASON,YTD_UNITWEEKS_CURRENTSEASON,YTD_GUESTWEEKS_CURRENTSEASON,YTD_NETTBILLINGS_BUDGET_CURRENTSEASON,YTD_UNITWEEKS_BUDGET_CURRENTSEASON,YTD_GUESTWEEKS_BUDGET_CURRENTSEASON,YEAR_NETTBILLINGS_BUDGET_CURRENTSEASON,YEAR_UNITWEEKS_BUDGET_CURRENTSEASON,YEAR_GUESTWEEKS_BUDGET_CURRENTSEASON,WEEK_NETTBILLINGS_PRIORSEASON,WEEK_COMMISSIONS_PRIORSEASON,WEEK_GROSSBILLINGS_PRIORSEASON,WEEK_UNITWEEKS_PRIORSEASON,WEEK_GUESTWEEKS_PRIORSEASON,YTD_NETTBILLINGS_PRIORSEASON,YTD_COMMISSIONS_PRIORSEASON,YTD_GROSSBILLINGS_PRIORSEASON,YTD_UNITWEEKS_PRIORSEASON,YTD_GUESTWEEKS_PRIORSEASON,YEAR_NETTBILLINGS_PRIORSEASON,YEAR_UNITWEEKS_PRIORSEASON,YEAR_GUESTWEEKS_PRIORSEASON,CARRIEDFORWARD_NETTBILLINGS_CURRENTSEASON,CARRIEDFORWARD_UNITWEEKS_CURRENTSEASON,CARRIEDFORWARD_GUESTWEEKS_CURRENTSEASON,CARRIEDFORWARD_NETTBILLINGS_PRIORSEASON,CARRIEDFORWARD_UNITWEEKS_PRIORSEASON,CARRIEDFORWARD_GUESTWEEKS_PRIORSEASON,CARRIEDFORWARD_NETTBILLINGS_BUDGET,CARRIEDFORWARD_UNITWEEKS_BUDGET,CARRIEDFORWARD_GUESTWEEKS_BUDGET from BOURNE_RAW.FINANCIAL_CUBE.FACT_HOLIDAYS  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_OWNERSPERSITE_TB source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_OWNERSPERSITE_TB(
	BRAND_REF,
	SITE_REF,
	PERIOD_REF,
	VERSION_REF,
	ACCOUNT_REF,
	LETTING_STATUS,
	LYPERIODLAG,
	UNIT_WEEK_VALUE
) as select BRAND_REF,SITE_REF,PERIOD_REF,VERSION_REF,ACCOUNT_REF,LETTING_STATUS,LYPERIODLAG,UNIT_WEEK_VALUE from BOURNE_RAW.FINANCIAL_CUBE.FACT_OWNERSPERSITE_TB  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_PITCHES source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_PITCHES(
	BRAND_REF,
	SITE_REF,
	PITCH_REF,
	PITCH_STATUS_REF,
	PERIOD_REF,
	VAN_REF,
	OWNER_ACCOUNT_REF,
	NEW_CUSTOMER_SITE_FEE
) as select BRAND_REF,SITE_REF,PITCH_REF,PITCH_STATUS_REF,PERIOD_REF,VAN_REF,OWNER_ACCOUNT_REF,NEW_CUSTOMER_SITE_FEE from BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_PITCHES  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER(
	BRAND_REF,
	OWNER_ACCOUNT_REF,
	NOMINAL_REF,
	PERIOD_REF,
	SITE_REF,
	VAN_REF,
	VERSION_REF,
	PITCH_REF,
	PITCH_STATUS_REF,
	RENT_LEDGER_BALANCE,
	RENT_LEDGER_WEEK_CASH,
	RENT_LEDGER_WEEK_BILLING,
	RENT_LEDGER_WEEK_OTHER
) as select BRAND_REF,OWNER_ACCOUNT_REF,NOMINAL_REF,PERIOD_REF,SITE_REF,VAN_REF,VERSION_REF,PITCH_REF,PITCH_STATUS_REF,RENT_LEDGER_BALANCE,RENT_LEDGER_WEEK_CASH,RENT_LEDGER_WEEK_BILLING,RENT_LEDGER_WEEK_OTHER from BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER_NEW source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER_NEW(
	LOCATION_REF,
	OWNER_ACCOUNT_REF,
	NOMINAL_REF,
	WEEKENDDATE,
	VAN_REF,
	VERSION_REF,
	PITCH_STATUS_REF,
	DEBT_RANGE_REF,
	LIMBO_REF,
	SITE_FEE_BAND_REF,
	RENT_LEDGER_BALANCE,
	RENT_LEDGER_WEEK_CASH,
	RENT_LEDGER_WEEK_BILLING,
	RENT_LEDGER_WEEK_OTHER,
	TOTAL_SITE_FEES
) as select LOCATION_REF,OWNER_ACCOUNT_REF,NOMINAL_REF,WEEKENDDATE,VAN_REF,VERSION_REF,PITCH_STATUS_REF,DEBT_RANGE_REF,LIMBO_REF,SITE_FEE_BAND_REF,RENT_LEDGER_BALANCE,RENT_LEDGER_WEEK_CASH,RENT_LEDGER_WEEK_BILLING,RENT_LEDGER_WEEK_OTHER,TOTAL_SITE_FEES from BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER_NEW;


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_SALES_LEDGER source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_SALES_LEDGER(
	BRAND_REF,
	CARAVAN_SALES_REF,
	OWNER_ACCOUNT_REF,
	NOMINAL_REF,
	PERIOD_REF,
	PERIOD_REF_DATE_SOLD,
	PERIOD_REF_DATE_CANCELLED,
	PERIOD_REF_DATE_COMPLETED,
	SITE_REF,
	VAN_REF_SOLD,
	VAN_REF_PEX1,
	VAN_REF_PEX2,
	SALES_VALUE,
	SALES_COST_OF_SALE,
	SALES_MARGIN,
	SALES_LEDGER_BALANCE,
	SALES_PEX1_BOTTOM_BOOK_VALUE,
	SALES_PEX1_DISCOUNT,
	SALES_PEX2_BOTTOM_BOOK_VALUE,
	SALES_PEX2_DISCOUNT,
	SALES_GLB_AMOUNT,
	SALES_RL_AMOUNT,
	SALES_DUE_ON_ACCOUNT,
	SALES_SUBLET_AMOUNT,
	SALES_FINANCE_AMOUNT,
	SALES_DEPOSIT_AMOUNT,
	SALES_SVL_PRICE_SUB_TOTAL,
	SALES_SVL_VAT_AMOUNT,
	SALES_ORIGINAL_COST,
	SALES_VALUE_STANDARD_RATED,
	SALES_VALUE_ZERO_RATED,
	SALES_GROSS_PRICE_TOTAL
) as select BRAND_REF,CARAVAN_SALES_REF,OWNER_ACCOUNT_REF,NOMINAL_REF,PERIOD_REF,PERIOD_REF_DATE_SOLD,PERIOD_REF_DATE_CANCELLED,PERIOD_REF_DATE_COMPLETED,SITE_REF,VAN_REF_SOLD,VAN_REF_PEX1,VAN_REF_PEX2,SALES_VALUE,SALES_COST_OF_SALE,SALES_MARGIN,SALES_LEDGER_BALANCE,SALES_PEX1_BOTTOM_BOOK_VALUE,SALES_PEX1_DISCOUNT,SALES_PEX2_BOTTOM_BOOK_VALUE,SALES_PEX2_DISCOUNT,SALES_GLB_AMOUNT,SALES_RL_AMOUNT,SALES_DUE_ON_ACCOUNT,SALES_SUBLET_AMOUNT,SALES_FINANCE_AMOUNT,SALES_DEPOSIT_AMOUNT,SALES_SVL_PRICE_SUB_TOTAL,SALES_SVL_VAT_AMOUNT,SALES_ORIGINAL_COST,SALES_VALUE_STANDARD_RATED,SALES_VALUE_ZERO_RATED,SALES_GROSS_PRICE_TOTAL from BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_SALES_LEDGER  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_VANS source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_PLOT_VANS(
	BRAND_REF,
	VAN_REF,
	PERIOD_REF,
	SITE_REF,
	PITCH_REF,
	NOMINAL_REF,
	PITCH_STATUS_REF,
	LETTING_CATAGORY_REF,
	VAN_EST_COST,
	VAN_TRANSP_EST_COST,
	VAN_HF_DEPREC_EST_COST,
	VAN_TOTAL_VAT_COST,
	VAN_TOTAL_EST_COST,
	VAN_VAN_PRICE_TOTAL,
	VAN_NEW_YN,
	VAN_GLASSES_GUIDE_PRICE,
	VAN_DELIVERY_STATUS_REF
) as select BRAND_REF,VAN_REF,PERIOD_REF,SITE_REF,PITCH_REF,NOMINAL_REF,PITCH_STATUS_REF,LETTING_CATAGORY_REF,VAN_EST_COST,VAN_TRANSP_EST_COST,VAN_HF_DEPREC_EST_COST,VAN_TOTAL_VAT_COST,VAN_TOTAL_EST_COST,VAN_VAN_PRICE_TOTAL,VAN_NEW_YN,VAN_GLASSES_GUIDE_PRICE,VAN_DELIVERY_STATUS_REF from BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_VANS  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_RETAIL_TRADING source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_RETAIL_TRADING(
	BUSINESSKEY,
	PERIOD_REF,
	BRAND_REF,
	SITE_REF,
	VERSION_REF,
	LINEDESCRIPTION,
	COLUMN1,
	COLUMN2,
	COLUMN3,
	COLUMN5,
	COLUMN6,
	COLUMN8,
	COLUMN9,
	COLUMN10,
	COLUMN11
) as select BUSINESSKEY,PERIOD_REF,BRAND_REF,SITE_REF,VERSION_REF,LINEDESCRIPTION,COLUMN1,COLUMN2,COLUMN3,COLUMN5,COLUMN6,COLUMN8,COLUMN9,COLUMN10,COLUMN11 from BOURNE_RAW.FINANCIAL_CUBE.FACT_RETAIL_TRADING  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_TB source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_TB(
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT_REF,
	LEDGER3_REF,
	LEDGER3_ACCOUNT_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	VERSION_REF,
	PERIOD_REF,
	WEEK_VALUE,
	WEEK_USERVALUE,
	WEEK_USERVALUEFIELD1,
	WEEK_USERVALUEFIELD2,
	WEEK_USERVALUEFIELD3,
	WEEK_USERVALUEFIELD4,
	YTD_VALUE,
	YTD_USERVALUE,
	YTD_USERVALUEFIELD1,
	YTD_USERVALUEFIELD2,
	YTD_USERVALUEFIELD3,
	YTD_USERVALUEFIELD4,
	CPARKPL_REF
) as select NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER_ACCOUNT_REF,LEDGER3_REF,LEDGER3_ACCOUNT_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,VERSION_REF,PERIOD_REF,WEEK_VALUE,WEEK_USERVALUE,WEEK_USERVALUEFIELD1,WEEK_USERVALUEFIELD2,WEEK_USERVALUEFIELD3,WEEK_USERVALUEFIELD4,YTD_VALUE,YTD_USERVALUE,YTD_USERVALUEFIELD1,YTD_USERVALUEFIELD2,YTD_USERVALUEFIELD3,YTD_USERVALUEFIELD4,CPARKPL_REF from BOURNE_RAW.FINANCIAL_CUBE.FACT_TB  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_TB_X source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_TB_X(
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT_REF,
	LEDGER3_REF,
	LEDGER3_ACCOUNT_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	VERSION_REF,
	PERIOD_REF,
	WEEK_VALUE,
	WEEK_USERVALUE,
	WEEK_USERVALUEFIELD1,
	WEEK_USERVALUEFIELD2,
	WEEK_USERVALUEFIELD3,
	WEEK_USERVALUEFIELD4,
	YTD_VALUE,
	YTD_USERVALUE,
	YTD_USERVALUEFIELD1,
	YTD_USERVALUEFIELD2,
	YTD_USERVALUEFIELD3,
	YTD_USERVALUEFIELD4,
	CPARKPL_REF
) as select NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER_ACCOUNT_REF,LEDGER3_REF,LEDGER3_ACCOUNT_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,VERSION_REF,PERIOD_REF,WEEK_VALUE,WEEK_USERVALUE,WEEK_USERVALUEFIELD1,WEEK_USERVALUEFIELD2,WEEK_USERVALUEFIELD3,WEEK_USERVALUEFIELD4,YTD_VALUE,YTD_USERVALUE,YTD_USERVALUEFIELD1,YTD_USERVALUEFIELD2,YTD_USERVALUEFIELD3,YTD_USERVALUEFIELD4,CPARKPL_REF from BOURNE_RAW.FINANCIAL_CUBE.FACT_TB_X  where brand_ref in (2, 4, 7);


-- HAVEN_BASE.FINANCIAL_CUBE.FACT_VAT source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.FACT_VAT(
	PERIOD_REF,
	VAT_RATE
) as select PERIOD_REF,VAT_RATE from BOURNE_RAW.FINANCIAL_CUBE.FACT_VAT;


-- HAVEN_BASE.FINANCIAL_CUBE.INFOR_BUDGET source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.INFOR_BUDGET(
	STAGE_BUDGET_IMPORT_REF,
	BRAND_REF,
	BUDGETCODE,
	NEW_NOMINAL,
	NEW_LEDGER,
	NEW_L3LEDGER,
	VALUE,
	USERVALUE,
	STATYEAR,
	STATPERIOD,
	USERVALUEFIELD1,
	USERVALUEFIELD2,
	USERVALUEFIELD4
) as
select 
STAGE_BUDGET_IMPORT_REF,
BRAND_REF,
BUDGETCODE,
NEW_NOMINAL,
NEW_LEDGER,
NEW_L3LEDGER,
VALUE,
USERVALUE,
STATYEAR,
STATPERIOD,
USERVALUEFIELD1,
USERVALUEFIELD2,
USERVALUEFIELD3
USERVALUEFIELD4
from haven_raw.financial_cube.infor_budget;


-- HAVEN_BASE.FINANCIAL_CUBE.STAGE_FACT_CARAVAN_SALES source

create or replace view HAVEN_BASE.FINANCIAL_CUBE.STAGE_FACT_CARAVAN_SALES(
	STATYEAR,
	STATPERIOD,
	SITE_CODE,
	BRAND,
	CSI_NO,
	DREAM_DOC_DATE,
	DREAM_DOC_TYPE,
	ACCOUNT_ID,
	ACCOUNT_NO,
	SALE_ROW_TYPE,
	PLOT_SALE_ID,
	SOURCE_ID,
	DATE_SOLD,
	VALIDATION_DATE,
	COMPLETION_DATE,
	CANCELLATION_DATE,
	ACCOUNT_LEDGER,
	LEDGER_TYPE_CODE,
	NEWPEX,
	SALE_TYPE_CODE,
	SALE_TYPE_DESC,
	CSP_ID,
	CSP_DESC,
	USER_VALUE,
	VALUE,
	MARGIN
) as select STATYEAR,STATPERIOD,SITE_CODE,BRAND,CSI_NO,DREAM_DOC_DATE,DREAM_DOC_TYPE,ACCOUNT_ID,ACCOUNT_NO,SALE_ROW_TYPE,PLOT_SALE_ID,SOURCE_ID,DATE_SOLD,VALIDATION_DATE,COMPLETION_DATE,CANCELLATION_DATE,ACCOUNT_LEDGER,LEDGER_TYPE_CODE,NEWPEX,SALE_TYPE_CODE,SALE_TYPE_DESC,CSP_ID,CSP_DESC,USER_VALUE,VALUE,MARGIN from BOURNE_RAW.FINANCIAL_CUBE.STAGE_FACT_CARAVAN_SALES;