use ROLE dba;

use SCHEMA haven_base.plot;

SELECT get_ddl('view', 'owners');


use ROLE dba;

use SCHEMA haven_base.plot;

SELECT * FROM OWNERS LIMIT 20;

create or replace view haven_base.plot.OWNERS_MASKED (
	OWNER_ID,
	OWNER_NO,
	PROSPECT_ID,
	NAMESORT WITH TAG (haven_master.tag_admin.lastname = 'last name'),
	NAME WITH TAG (haven_master.tag_admin.fullname = 'full name'),
	ADD_1 WITH TAG (haven_master.tag_admin.street = 'street name'),
	ADD_2 WITH TAG (haven_master.tag_admin.town = 'town'),
	ADD_3 WITH TAG (haven_master.tag_admin.town = 'town'),
	ADD_4 WITH TAG (haven_master.tag_admin.county = 'county'),
	POST_CODE WITH TAG (haven_master.tag_admin.postcode = 'postcode'),
	NUMDAY WITH TAG (haven_master.tag_admin.telephone = 'work'),
	NUMEVE WITH TAG (haven_master.tag_admin.telephone = 'home'),
	NUMMOB WITH TAG (haven_master.tag_admin.telephone = 'mobile'),
	EMAIL WITH TAG (haven_master.tag_admin.email = 'email_address'),
	SALUTATION WITH TAG (haven_master.tag_admin.title = 'title'),
	CREATED_BY,
	CREATED_DT,
	EDIT_BY,
	EDIT_DT,
	DOB WITH TAG (haven_master.tag_admin.dateofbirth = 'date of birth'),
	OCCUPATION_ID,
	WEB_EMAIL WITH TAG (haven_master.tag_admin.email = 'email_address'),
	WEB_ACTIVATION_CODE,
	WEB_PASSWORD,
	WEB_EMAIL_MARKETING_YN,
	WEB_EMAIL_MARKETING_DT,
	WEB_REGISTRATION_DT,
	WEB_LAST_LOGIN_DT,
	ACT_LET_SENT_DT,
	TRADER_YN,
	OVERSEAS_ADD_YN,
	RESPONSE_ID,
	SOURCE_ID,
	SOURCE_SUB_CODE_ID,
	PRINTED,
	IS_PROSPECT_YN,
	RECEIVE_MAILING_YN,
	MPS_STATUS,
	MPS_STATUS_DT,
	MAIL_PREFERENCE_YN,
	MAIL_PREFERENCE_DT,
	RECEIVE_TELEPHONE_YN,
	TPS_STATUS,
	TPS_STATUS_DT,
	TELEPHONE_PREFERENCE_IN_YN,
	TELEPHONE_PREFERENCE_DT,
	DELETED_YN,
	ADDRESS_CAREOF_REASONS_ID,
	NO_VALID_EMAIL_YN,
	MANAGED_SUBLET_YN,
	NO_OF_BEDROOMS,
	BUDGET_CASH_DEPOSIT,
	BUDGET_MONTHLY,
	PREFERRED_CONTACT_METHOD_ENUM,
	EMAIL_ADDRESS_VERIFICATION_STATUS_ENUM,
	EMAIL_GUID,
	EMAIL_VERIFY_REQUEST_DT,
	EMAIL_VERIFIED_DT,
	FORENAME WITH TAG (haven_master.tag_admin.firstname = 'first name'),
	SURNAME WITH TAG (haven_master.tag_admin.lastname = 'last name'),
	PREFERRED_FORENAME WITH TAG (haven_master.tag_admin.firstname = 'first name'),
	MIDDLE_INITIAL WITH TAG (haven_master.tag_admin.middlename = 'middle initial'),
	TITLE_ID,
	CONTACT_STATUS_TEL_DAY_PREFERENCE_ENUM,
	CONTACT_STATUS_TEL_EVE_PREFERENCE_ENUM,
	ROW_VERSION_NUMBER,
	DEDUPE,
	CHERISHED_ADDRESS_YN,
	SURNAME_SOUNDEX,
	LAST_DEDUPE_DATE,
	CREATED_IN_PROSPECTS_PHASE1_YN,
	WEB_SOURCE_UID,
	CARAVAN_SALES_EMAIL_OPT_IN_YN,
	NUMDAY_TEXT,
	NUMEVE_TEXT,
	NUMMOB_TEXT,
	WEB_PASSWORD_RESET_GUID,
	WEB_PASSWORD_RESET_DT,
	DENY_RTBF_REQUEST_YN,
	OWNER_TYPE_ENUM
) as SELECT OWNER_ID, OWNER_NO, PROSPECT_ID, NAMESORT, NAME, ADD_1, ADD_2, ADD_3, ADD_4, POST_CODE, NUMDAY, NUMEVE, NUMMOB, EMAIL, SALUTATION, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT, DOB, OCCUPATION_ID, WEB_EMAIL, WEB_ACTIVATION_CODE, WEB_PASSWORD, WEB_EMAIL_MARKETING_YN, WEB_EMAIL_MARKETING_DT, WEB_REGISTRATION_DT, WEB_LAST_LOGIN_DT, ACT_LET_SENT_DT, TRADER_YN, OVERSEAS_ADD_YN, RESPONSE_ID, SOURCE_ID, SOURCE_SUB_CODE_ID, PRINTED, IS_PROSPECT_YN, RECEIVE_MAILING_YN, MPS_STATUS, MPS_STATUS_DT, MAIL_PREFERENCE_YN, MAIL_PREFERENCE_DT, RECEIVE_TELEPHONE_YN, TPS_STATUS, TPS_STATUS_DT, TELEPHONE_PREFERENCE_IN_YN, TELEPHONE_PREFERENCE_DT, DELETED_YN, ADDRESS_CAREOF_REASONS_ID, NO_VALID_EMAIL_YN, MANAGED_SUBLET_YN, NO_OF_BEDROOMS, BUDGET_CASH_DEPOSIT, BUDGET_MONTHLY, PREFERRED_CONTACT_METHOD_ENUM, EMAIL_ADDRESS_VERIFICATION_STATUS_ENUM, EMAIL_GUID, EMAIL_VERIFY_REQUEST_DT, EMAIL_VERIFIED_DT, FORENAME, SURNAME, PREFERRED_FORENAME, MIDDLE_INITIAL, TITLE_ID, CONTACT_STATUS_TEL_DAY_PREFERENCE_ENUM, CONTACT_STATUS_TEL_EVE_PREFERENCE_ENUM, ROW_VERSION_NUMBER, DEDUPE, CHERISHED_ADDRESS_YN, RTRIM(SURNAME_SOUNDEX), LAST_DEDUPE_DATE, CREATED_IN_PROSPECTS_PHASE1_YN, RTRIM(WEB_SOURCE_UID), CARAVAN_SALES_EMAIL_OPT_IN_YN, NUMDAY_TEXT, NUMEVE_TEXT, NUMMOB_TEXT, WEB_PASSWORD_RESET_GUID, WEB_PASSWORD_RESET_DT, DENY_RTBF_REQUEST_YN, OWNER_TYPE_ENUM FROM HAVEN_RAW.PLOT_RDS_TEST.OWNERS;


use ROLE securityadmin;

grant role __street_masking_policy_role to role haven_dbt_development;
grant role __town_masking_policy_role to role haven_dbt_development;
grant role __county_masking_policy_role to role haven_dbt_development;
grant role __country_masking_policy_role to role haven_dbt_development;
grant role __postcode_masking_policy_role to role haven_dbt_development;
grant role __postcode_masking_policy_area_role to role haven_dbt_development;
grant role __postcode_masking_policy_region_role to role haven_dbt_development;
grant role __postcode_masking_policy_sector_role to role haven_dbt_development;
grant role __location_masking_policy_role to role haven_dbt_development;
grant role __first_name_masking_policy_role to role haven_dbt_development;
grant role __last_name_masking_policy_role to role haven_dbt_development;
grant role __middle_name_masking_policy_role to role haven_dbt_development;
grant role __full_name_masking_policy_role to role haven_dbt_development;
grant role __telephone_masking_policy_role to role haven_dbt_development;
grant role __age_masking_policy_role to role haven_dbt_development;
grant role __date_of_birth_masking_policy_role to role haven_dbt_development;
grant role __date_of_birth_masking_policy_age_data_role to role haven_dbt_development;
grant role __date_of_birth_masking_policy_age_data_range_role to role haven_dbt_development;
grant role __gender_masking_policy_role to role haven_dbt_development;
grant role __title_masking_policy_role to role haven_dbt_development;
grant role __email_masking_policy_role to role haven_dbt_development;
grant role __email_masking_policy_provider_role to role haven_dbt_development;
grant role __car_registration_masking_policy_role to role haven_dbt_development;
grant role __car_registration_masking_policy_location_role to role haven_dbt_development;
grant role __car_registration_masking_policy_location_year_role to role haven_dbt_development;
grant role __car_registration_masking_policy_year_role to role haven_dbt_development;

-- 11/09/2025

use role dba;

drop VIEW haven_base.plot.OWNERS_MASKED;

use SCHEMA haven_raw.plot_rds_test;

CREATE TABLE owners_masked AS SELECT * FROM owners;

SELECT count(*) FROM owners_masked;

ALTER TABLE owners_masked ALTER column
	NAMESORT SET TAG haven_master.tag_admin.lastname = 'last name';

ALTER TABLE owners_masked ALTER column
	NAME SET TAG haven_master.tag_admin.fullname = 'full name';

ALTER TABLE owners_masked ALTER column
	ADD_1 SET TAG haven_master.tag_admin.street = 'street name';

ALTER TABLE owners_masked ALTER column
	ADD_2 SET TAG haven_master.tag_admin.town = 'town';

ALTER TABLE owners_masked ALTER column
	ADD_3 SET TAG haven_master.tag_admin.town = 'town';

ALTER TABLE owners_masked ALTER column
	ADD_4 SET TAG haven_master.tag_admin.county = 'county';

ALTER TABLE owners_masked ALTER column
	POST_CODE SET TAG haven_master.tag_admin.postcode = 'postcode';

ALTER TABLE owners_masked ALTER column
	NUMDAY SET TAG haven_master.tag_admin.telephone = 'work';

ALTER TABLE owners_masked ALTER column
	NUMEVE SET TAG haven_master.tag_admin.telephone = 'home';

ALTER TABLE owners_masked ALTER column
	NUMMOB SET TAG haven_master.tag_admin.telephone = 'mobile';

ALTER TABLE owners_masked ALTER column
	EMAIL SET TAG haven_master.tag_admin.email = 'email_address';

ALTER TABLE owners_masked ALTER column
	SALUTATION SET TAG haven_master.tag_admin.title = 'title';

ALTER TABLE owners_masked ALTER column
	DOB SET TAG haven_master.tag_admin.dateofbirth = 'date of birth';

ALTER TABLE owners_masked ALTER column
	WEB_EMAIL SET TAG haven_master.tag_admin.email = 'email_address';

ALTER TABLE owners_masked ALTER column
	FORENAME SET TAG haven_master.tag_admin.firstname = 'first name';

ALTER TABLE owners_masked ALTER column
	SURNAME SET TAG haven_master.tag_admin.lastname = 'last name';

ALTER TABLE owners_masked ALTER column
	PREFERRED_FORENAME SET TAG haven_master.tag_admin.firstname = 'first name';

ALTER TABLE owners_masked ALTER column
	MIDDLE_INITIAL SET TAG haven_master.tag_admin.middlename = 'middle initial';

SELECT * FROM owners_masked LIMIT 10;

use ROLE dba;

use SCHEMA haven_base.plot;

SELECT get_ddl('view', 'owners');


create or replace view OWNERS_masked (
	OWNER_ID,
	OWNER_NO,
	PROSPECT_ID,
	NAMESORT,
	NAME,
	ADD_1,
	ADD_2,
	ADD_3,
	ADD_4,
	POST_CODE,
	NUMDAY,
	NUMEVE,
	NUMMOB,
	EMAIL,
	SALUTATION,
	CREATED_BY,
	CREATED_DT,
	EDIT_BY,
	EDIT_DT,
	DOB,
	OCCUPATION_ID,
	WEB_EMAIL,
	WEB_ACTIVATION_CODE,
	WEB_PASSWORD,
	WEB_EMAIL_MARKETING_YN,
	WEB_EMAIL_MARKETING_DT,
	WEB_REGISTRATION_DT,
	WEB_LAST_LOGIN_DT,
	ACT_LET_SENT_DT,
	TRADER_YN,
	OVERSEAS_ADD_YN,
	RESPONSE_ID,
	SOURCE_ID,
	SOURCE_SUB_CODE_ID,
	PRINTED,
	IS_PROSPECT_YN,
	RECEIVE_MAILING_YN,
	MPS_STATUS,
	MPS_STATUS_DT,
	MAIL_PREFERENCE_YN,
	MAIL_PREFERENCE_DT,
	RECEIVE_TELEPHONE_YN,
	TPS_STATUS,
	TPS_STATUS_DT,
	TELEPHONE_PREFERENCE_IN_YN,
	TELEPHONE_PREFERENCE_DT,
	DELETED_YN,
	ADDRESS_CAREOF_REASONS_ID,
	NO_VALID_EMAIL_YN,
	MANAGED_SUBLET_YN,
	NO_OF_BEDROOMS,
	BUDGET_CASH_DEPOSIT,
	BUDGET_MONTHLY,
	PREFERRED_CONTACT_METHOD_ENUM,
	EMAIL_ADDRESS_VERIFICATION_STATUS_ENUM,
	EMAIL_GUID,
	EMAIL_VERIFY_REQUEST_DT,
	EMAIL_VERIFIED_DT,
	FORENAME,
	SURNAME,
	PREFERRED_FORENAME,
	MIDDLE_INITIAL,
	TITLE_ID,
	CONTACT_STATUS_TEL_DAY_PREFERENCE_ENUM,
	CONTACT_STATUS_TEL_EVE_PREFERENCE_ENUM,
	ROW_VERSION_NUMBER,
	DEDUPE,
	CHERISHED_ADDRESS_YN,
	SURNAME_SOUNDEX,
	LAST_DEDUPE_DATE,
	CREATED_IN_PROSPECTS_PHASE1_YN,
	WEB_SOURCE_UID,
	CARAVAN_SALES_EMAIL_OPT_IN_YN,
	NUMDAY_TEXT,
	NUMEVE_TEXT,
	NUMMOB_TEXT,
	WEB_PASSWORD_RESET_GUID,
	WEB_PASSWORD_RESET_DT,
	DENY_RTBF_REQUEST_YN,
	OWNER_TYPE_ENUM
) as 
SELECT "OWNER_ID", "OWNER_NO", "PROSPECT_ID", "NAMESORT", "NAME", "ADD_1", "ADD_2", "ADD_3", "ADD_4", "POST_CODE", "NUMDAY", "NUMEVE", "NUMMOB", "EMAIL", "SALUTATION", "CREATED_BY", "CREATED_DT", "EDIT_BY", "EDIT_DT", "DOB", "OCCUPATION_ID", "WEB_EMAIL", "WEB_ACTIVATION_CODE", "WEB_PASSWORD", "WEB_EMAIL_MARKETING_YN", "WEB_EMAIL_MARKETING_DT", "WEB_REGISTRATION_DT", "WEB_LAST_LOGIN_DT", "ACT_LET_SENT_DT", "TRADER_YN", "OVERSEAS_ADD_YN", "RESPONSE_ID", "SOURCE_ID", "SOURCE_SUB_CODE_ID", "PRINTED", "IS_PROSPECT_YN", "RECEIVE_MAILING_YN", "MPS_STATUS", "MPS_STATUS_DT", "MAIL_PREFERENCE_YN", "MAIL_PREFERENCE_DT", "RECEIVE_TELEPHONE_YN", "TPS_STATUS", "TPS_STATUS_DT", "TELEPHONE_PREFERENCE_IN_YN", "TELEPHONE_PREFERENCE_DT", "DELETED_YN", "ADDRESS_CAREOF_REASONS_ID", "NO_VALID_EMAIL_YN", "MANAGED_SUBLET_YN", "NO_OF_BEDROOMS", "BUDGET_CASH_DEPOSIT", "BUDGET_MONTHLY", "PREFERRED_CONTACT_METHOD_ENUM", "EMAIL_ADDRESS_VERIFICATION_STATUS_ENUM", "EMAIL_GUID", "EMAIL_VERIFY_REQUEST_DT", "EMAIL_VERIFIED_DT", "FORENAME", "SURNAME", "PREFERRED_FORENAME", "MIDDLE_INITIAL", "TITLE_ID", "CONTACT_STATUS_TEL_DAY_PREFERENCE_ENUM", "CONTACT_STATUS_TEL_EVE_PREFERENCE_ENUM", "ROW_VERSION_NUMBER", "DEDUPE", "CHERISHED_ADDRESS_YN", RTRIM("SURNAME_SOUNDEX"), "LAST_DEDUPE_DATE", "CREATED_IN_PROSPECTS_PHASE1_YN", RTRIM("WEB_SOURCE_UID"), "CARAVAN_SALES_EMAIL_OPT_IN_YN", "NUMDAY_TEXT", "NUMEVE_TEXT", "NUMMOB_TEXT", "WEB_PASSWORD_RESET_GUID", "WEB_PASSWORD_RESET_DT", "DENY_RTBF_REQUEST_YN", "OWNER_TYPE_ENUM" 
FROM "HAVEN_RAW"."PLOT_RDS_TEST"."OWNERS_MASKED";

USE ROLE HAVEN_DATA_ENGINEERING;

SHOW WAREHOUSES;

USE WAREHOUSE HAVEN_DATA_ENGINEERING_WAREHOUSE_XSMALL;

SELECT * FROM HAVEN_BASE.PLOT.OWNERS_MASKED LIMIT 10;

USE ROLE HAVEN_DBT_DEVELOPMENT;

SHOW WAREHOUSES;

USE WAREHOUSE HAVEN_DBT_DEVELOPMENT_WAREHOUSE_XSMALL;

SELECT * FROM HAVEN_BASE.PLOT.OWNERS_MASKED LIMIT 10;

USE ROLE DBA;

CREATE SCHEMA HAVEN_STORE_DEV.DELETEME;

CREATE TABLE HAVEN_STORE_DEV.DELETEME.TEST_TABLE
AS SELECT * FROM HAVEN_BASE.PLOT.OWNERS_MASKED;

CREATE VIEW HAVEN_STORE_DEV.DELETEME.TEST_VIEW
AS SELECT * FROM HAVEN_BASE.PLOT.OWNERS_MASKED;

USE ROLE HAVEN_DATA_ENGINEERING;
USE WAREHOUSE HAVEN_DATA_ENGINEERING_WAREHOUSE_XSMALL;

SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_TABLE LIMIT 10;
SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_VIEW LIMIT 10;

USE ROLE HAVEN_DBT_DEVELOPMENT;

USE WAREHOUSE HAVEN_DBT_DEVELOPMENT_WAREHOUSE_XSMALL;

SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_TABLE LIMIT 10;
SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_VIEW LIMIT 10;

-- create a view only

use ROLE dba;

use SCHEMA haven_base.plot;

create or replace view haven_base.plot.OWNERS_MASKED_view (
	OWNER_ID,
	OWNER_NO,
	PROSPECT_ID,
	NAMESORT WITH TAG (haven_master.tag_admin.lastname = 'last name'),
	NAME WITH TAG (haven_master.tag_admin.fullname = 'full name'),
	ADD_1 WITH TAG (haven_master.tag_admin.street = 'street name'),
	ADD_2 WITH TAG (haven_master.tag_admin.town = 'town'),
	ADD_3 WITH TAG (haven_master.tag_admin.town = 'town'),
	ADD_4 WITH TAG (haven_master.tag_admin.county = 'county'),
	POST_CODE WITH TAG (haven_master.tag_admin.postcode = 'postcode'),
	NUMDAY WITH TAG (haven_master.tag_admin.telephone = 'work'),
	NUMEVE WITH TAG (haven_master.tag_admin.telephone = 'home'),
	NUMMOB WITH TAG (haven_master.tag_admin.telephone = 'mobile'),
	EMAIL WITH TAG (haven_master.tag_admin.email = 'email_address'),
	SALUTATION WITH TAG (haven_master.tag_admin.title = 'title'),
	CREATED_BY,
	CREATED_DT,
	EDIT_BY,
	EDIT_DT,
	DOB WITH TAG (haven_master.tag_admin.dateofbirth = 'date of birth'),
	OCCUPATION_ID,
	WEB_EMAIL WITH TAG (haven_master.tag_admin.email = 'email_address'),
	WEB_ACTIVATION_CODE,
	WEB_PASSWORD,
	WEB_EMAIL_MARKETING_YN,
	WEB_EMAIL_MARKETING_DT,
	WEB_REGISTRATION_DT,
	WEB_LAST_LOGIN_DT,
	ACT_LET_SENT_DT,
	TRADER_YN,
	OVERSEAS_ADD_YN,
	RESPONSE_ID,
	SOURCE_ID,
	SOURCE_SUB_CODE_ID,
	PRINTED,
	IS_PROSPECT_YN,
	RECEIVE_MAILING_YN,
	MPS_STATUS,
	MPS_STATUS_DT,
	MAIL_PREFERENCE_YN,
	MAIL_PREFERENCE_DT,
	RECEIVE_TELEPHONE_YN,
	TPS_STATUS,
	TPS_STATUS_DT,
	TELEPHONE_PREFERENCE_IN_YN,
	TELEPHONE_PREFERENCE_DT,
	DELETED_YN,
	ADDRESS_CAREOF_REASONS_ID,
	NO_VALID_EMAIL_YN,
	MANAGED_SUBLET_YN,
	NO_OF_BEDROOMS,
	BUDGET_CASH_DEPOSIT,
	BUDGET_MONTHLY,
	PREFERRED_CONTACT_METHOD_ENUM,
	EMAIL_ADDRESS_VERIFICATION_STATUS_ENUM,
	EMAIL_GUID,
	EMAIL_VERIFY_REQUEST_DT,
	EMAIL_VERIFIED_DT,
	FORENAME WITH TAG (haven_master.tag_admin.firstname = 'first name'),
	SURNAME WITH TAG (haven_master.tag_admin.lastname = 'last name'),
	PREFERRED_FORENAME WITH TAG (haven_master.tag_admin.firstname = 'first name'),
	MIDDLE_INITIAL WITH TAG (haven_master.tag_admin.middlename = 'middle initial'),
	TITLE_ID,
	CONTACT_STATUS_TEL_DAY_PREFERENCE_ENUM,
	CONTACT_STATUS_TEL_EVE_PREFERENCE_ENUM,
	ROW_VERSION_NUMBER,
	DEDUPE,
	CHERISHED_ADDRESS_YN,
	SURNAME_SOUNDEX,
	LAST_DEDUPE_DATE,
	CREATED_IN_PROSPECTS_PHASE1_YN,
	WEB_SOURCE_UID,
	CARAVAN_SALES_EMAIL_OPT_IN_YN,
	NUMDAY_TEXT,
	NUMEVE_TEXT,
	NUMMOB_TEXT,
	WEB_PASSWORD_RESET_GUID,
	WEB_PASSWORD_RESET_DT,
	DENY_RTBF_REQUEST_YN,
	OWNER_TYPE_ENUM
) as SELECT OWNER_ID, OWNER_NO, PROSPECT_ID, NAMESORT, NAME, ADD_1, ADD_2, ADD_3, ADD_4, POST_CODE, NUMDAY, NUMEVE, NUMMOB, EMAIL, SALUTATION, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT, DOB, OCCUPATION_ID, WEB_EMAIL, WEB_ACTIVATION_CODE, WEB_PASSWORD, WEB_EMAIL_MARKETING_YN, WEB_EMAIL_MARKETING_DT, WEB_REGISTRATION_DT, WEB_LAST_LOGIN_DT, ACT_LET_SENT_DT, TRADER_YN, OVERSEAS_ADD_YN, RESPONSE_ID, SOURCE_ID, SOURCE_SUB_CODE_ID, PRINTED, IS_PROSPECT_YN, RECEIVE_MAILING_YN, MPS_STATUS, MPS_STATUS_DT, MAIL_PREFERENCE_YN, MAIL_PREFERENCE_DT, RECEIVE_TELEPHONE_YN, TPS_STATUS, TPS_STATUS_DT, TELEPHONE_PREFERENCE_IN_YN, TELEPHONE_PREFERENCE_DT, DELETED_YN, ADDRESS_CAREOF_REASONS_ID, NO_VALID_EMAIL_YN, MANAGED_SUBLET_YN, NO_OF_BEDROOMS, BUDGET_CASH_DEPOSIT, BUDGET_MONTHLY, PREFERRED_CONTACT_METHOD_ENUM, EMAIL_ADDRESS_VERIFICATION_STATUS_ENUM, EMAIL_GUID, EMAIL_VERIFY_REQUEST_DT, EMAIL_VERIFIED_DT, FORENAME, SURNAME, PREFERRED_FORENAME, MIDDLE_INITIAL, TITLE_ID, CONTACT_STATUS_TEL_DAY_PREFERENCE_ENUM, CONTACT_STATUS_TEL_EVE_PREFERENCE_ENUM, ROW_VERSION_NUMBER, DEDUPE, CHERISHED_ADDRESS_YN, RTRIM(SURNAME_SOUNDEX), LAST_DEDUPE_DATE, CREATED_IN_PROSPECTS_PHASE1_YN, RTRIM(WEB_SOURCE_UID), CARAVAN_SALES_EMAIL_OPT_IN_YN, NUMDAY_TEXT, NUMEVE_TEXT, NUMMOB_TEXT, WEB_PASSWORD_RESET_GUID, WEB_PASSWORD_RESET_DT, DENY_RTBF_REQUEST_YN, OWNER_TYPE_ENUM FROM HAVEN_RAW.PLOT_RDS_TEST.OWNERS;

SELECT * FROM owners_masked LIMIT 10;
SELECT * FROM owners_masked_view LIMIT 10;

CREATE VIEW haven_store_dev.DELETEme.test_view_on_tagged_view
AS SELECT * FROM haven_base.plot.owners_masked_view;

use ROLE dba;

CREATE TABLE haven_store_dev.DELETEme.test_table_on_tagged_view
AS SELECT * FROM haven_base.plot.owners_masked_view;

USE ROLE HAVEN_DATA_ENGINEERING;
USE WAREHOUSE HAVEN_DATA_ENGINEERING_WAREHOUSE_XSMALL;

SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_TABLE LIMIT 10;
SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_VIEW LIMIT 10;
SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_VIEW_ON_TAGGED_VIEW LIMIT 10;
SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_table_ON_TAGGED_VIEW LIMIT 10;
SELECT * FROM haven_base.plot.owners_masked LIMIT 10;
SELECT * FROM haven_base.plot.owners_masked_view LIMIT 10;
SELECT * FROM haven_base.plot.owners LIMIT 10;

USE ROLE HAVEN_DBT_DEVELOPMENT;

USE WAREHOUSE HAVEN_DBT_DEVELOPMENT_WAREHOUSE_XSMALL;

SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_TABLE LIMIT 10;
SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_VIEW LIMIT 10;
SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_VIEW_ON_TAGGED_VIEW LIMIT 10;
SELECT * FROM HAVEN_STORE_DEV.DELETEME.TEST_table_ON_TAGGED_VIEW LIMIT 10;
SELECT * FROM haven_base.plot.owners_masked LIMIT 10;
SELECT * FROM haven_base.plot.owners_masked_view LIMIT 10;


USE ROLE DBA;

USE SCHEMA HAVEN_BASE.PLOT;

SHOW VIEWS LIKE 'OWNERS%';

DROP VIEW HAVEN_BASE.PLOT.OWNERS_MASKED;

create or replace view OWNERS_MASKED (
	OWNER_ID,
	OWNER_NO,
	PROSPECT_ID,
	NAMESORT WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='last name'),
	NAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.FULLNAME='full name'),
	ADD_1 WITH TAG (HAVEN_MASTER.TAG_ADMIN.STREET='street name'),
	ADD_2 WITH TAG (HAVEN_MASTER.TAG_ADMIN.TOWN='town'),
	ADD_3 WITH TAG (HAVEN_MASTER.TAG_ADMIN.TOWN='town'),
	ADD_4 WITH TAG (HAVEN_MASTER.TAG_ADMIN.COUNTY='county'),
	POST_CODE WITH TAG (HAVEN_MASTER.TAG_ADMIN.POSTCODE='postcode'),
	NUMDAY WITH TAG (HAVEN_MASTER.TAG_ADMIN.TELEPHONE='work'),
	NUMEVE WITH TAG (HAVEN_MASTER.TAG_ADMIN.TELEPHONE='home'),
	NUMMOB WITH TAG (HAVEN_MASTER.TAG_ADMIN.TELEPHONE='mobile'),
	EMAIL WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address'),
	SALUTATION WITH TAG (HAVEN_MASTER.TAG_ADMIN.TITLE='title'),
	CREATED_BY,
	CREATED_DT,
	EDIT_BY,
	EDIT_DT,
	DOB WITH TAG (HAVEN_MASTER.TAG_ADMIN.DATEOFBIRTH='date of birth'),
	OCCUPATION_ID,
	WEB_EMAIL WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address'),
	WEB_ACTIVATION_CODE,
	WEB_PASSWORD,
	WEB_EMAIL_MARKETING_YN,
	WEB_EMAIL_MARKETING_DT,
	WEB_REGISTRATION_DT,
	WEB_LAST_LOGIN_DT,
	ACT_LET_SENT_DT,
	TRADER_YN,
	OVERSEAS_ADD_YN,
	RESPONSE_ID,
	SOURCE_ID,
	SOURCE_SUB_CODE_ID,
	PRINTED,
	IS_PROSPECT_YN,
	RECEIVE_MAILING_YN,
	MPS_STATUS,
	MPS_STATUS_DT,
	MAIL_PREFERENCE_YN,
	MAIL_PREFERENCE_DT,
	RECEIVE_TELEPHONE_YN,
	TPS_STATUS,
	TPS_STATUS_DT,
	TELEPHONE_PREFERENCE_IN_YN,
	TELEPHONE_PREFERENCE_DT,
	DELETED_YN,
	ADDRESS_CAREOF_REASONS_ID,
	NO_VALID_EMAIL_YN,
	MANAGED_SUBLET_YN,
	NO_OF_BEDROOMS,
	BUDGET_CASH_DEPOSIT,
	BUDGET_MONTHLY,
	PREFERRED_CONTACT_METHOD_ENUM,
	EMAIL_ADDRESS_VERIFICATION_STATUS_ENUM,
	EMAIL_GUID,
	EMAIL_VERIFY_REQUEST_DT,
	EMAIL_VERIFIED_DT,
	FORENAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.FIRSTNAME='first name'),
	SURNAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='last name'),
	PREFERRED_FORENAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.FIRSTNAME='first name'),
	MIDDLE_INITIAL WITH TAG (HAVEN_MASTER.TAG_ADMIN.MIDDLENAME='middle initial'),
	TITLE_ID,
	CONTACT_STATUS_TEL_DAY_PREFERENCE_ENUM,
	CONTACT_STATUS_TEL_EVE_PREFERENCE_ENUM,
	ROW_VERSION_NUMBER,
	DEDUPE,
	CHERISHED_ADDRESS_YN,
	SURNAME_SOUNDEX,
	LAST_DEDUPE_DATE,
	CREATED_IN_PROSPECTS_PHASE1_YN,
	WEB_SOURCE_UID,
	CARAVAN_SALES_EMAIL_OPT_IN_YN,
	NUMDAY_TEXT,
	NUMEVE_TEXT,
	NUMMOB_TEXT,
	WEB_PASSWORD_RESET_GUID,
	WEB_PASSWORD_RESET_DT,
	DENY_RTBF_REQUEST_YN,
	OWNER_TYPE_ENUM
) as SELECT OWNER_ID, OWNER_NO, PROSPECT_ID, NAMESORT, NAME, ADD_1, ADD_2, ADD_3, ADD_4, POST_CODE, NUMDAY, NUMEVE, NUMMOB, EMAIL, SALUTATION, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT, DOB, OCCUPATION_ID, WEB_EMAIL, WEB_ACTIVATION_CODE, WEB_PASSWORD, WEB_EMAIL_MARKETING_YN, WEB_EMAIL_MARKETING_DT, WEB_REGISTRATION_DT, WEB_LAST_LOGIN_DT, ACT_LET_SENT_DT, TRADER_YN, OVERSEAS_ADD_YN, RESPONSE_ID, SOURCE_ID, SOURCE_SUB_CODE_ID, PRINTED, IS_PROSPECT_YN, RECEIVE_MAILING_YN, MPS_STATUS, MPS_STATUS_DT, MAIL_PREFERENCE_YN, MAIL_PREFERENCE_DT, RECEIVE_TELEPHONE_YN, TPS_STATUS, TPS_STATUS_DT, TELEPHONE_PREFERENCE_IN_YN, TELEPHONE_PREFERENCE_DT, DELETED_YN, ADDRESS_CAREOF_REASONS_ID, NO_VALID_EMAIL_YN, MANAGED_SUBLET_YN, NO_OF_BEDROOMS, BUDGET_CASH_DEPOSIT, BUDGET_MONTHLY, PREFERRED_CONTACT_METHOD_ENUM, EMAIL_ADDRESS_VERIFICATION_STATUS_ENUM, EMAIL_GUID, EMAIL_VERIFY_REQUEST_DT, EMAIL_VERIFIED_DT, FORENAME, SURNAME, PREFERRED_FORENAME, MIDDLE_INITIAL, TITLE_ID, CONTACT_STATUS_TEL_DAY_PREFERENCE_ENUM, CONTACT_STATUS_TEL_EVE_PREFERENCE_ENUM, ROW_VERSION_NUMBER, DEDUPE, CHERISHED_ADDRESS_YN, RTRIM(SURNAME_SOUNDEX), LAST_DEDUPE_DATE, CREATED_IN_PROSPECTS_PHASE1_YN, RTRIM(WEB_SOURCE_UID), CARAVAN_SALES_EMAIL_OPT_IN_YN, NUMDAY_TEXT, NUMEVE_TEXT, NUMMOB_TEXT, WEB_PASSWORD_RESET_GUID, WEB_PASSWORD_RESET_DT, DENY_RTBF_REQUEST_YN, OWNER_TYPE_ENUM 
FROM HAVEN_RAW.PLOT_RDS_TEST.OWNERS;

select CURRENT_role();

use ROLE dba;
SELECT get_ddl('view', 'haven_base.plot.owners_masked');