use ROLE dba;

use SCHEMA haven_base.hit_admin;

CREATE VIEW HAVEN_BASE.HIT_ADMIN.VRES_CYHH_PITCH_COST
( ID, PARKCODE, ARRIVALDATE, DURATION, PITCHCODE, PITCHCOST, DATECREATED, DATEMODIFIED )
AS SELECT ID, PARKCODE, ARRIVALDATE, DURATION, PITCHCODE, PITCHCOST, DATECREATED, DATEMODIFIED
FROM HAVEN_RAW.HIT_ADMIN_ETLEAP.VRES_CYHH_PITCH_COST;

show grants TO ROLE haven_revenue_management_pricer;