USE ROLE dba;

USE SCHEMA haven_base.dream;

CREATE VIEW HAVEN_BASE.DREAM.D_ALLOCATION
( COMPANYCODE, ALLOCTYPE, ALLOCNUM, ALLOCREFNO, REFNO, DOCTYPE, DOCNUM, VALUE, NOMCURRENCY, ACCCURRENCY, DOCCURRENCY, ALTHOMEVAL, L3CURRENCY, DESCRIPTION, NARRATIVE, USERVALUE, PAYLIST, DISCOUNT, HIGHDATE, HIGHYEAR, HIGHPERIOD, CREATEDDATETIME, ALLOCSTATUS, INPUTDATE, INPUTTIME )
AS SELECT COMPANYCODE, ALLOCTYPE, ALLOCNUM, ALLOCREFNO, REFNO, DOCTYPE, DOCNUM, VALUE, NOMCURRENCY, ACCCURRENCY, DOCCURRENCY, ALTHOMEVAL, L3CURRENCY, DESCRIPTION, NARRATIVE, USERVALUE, PAYLIST, DISCOUNT, HIGHDATE, HIGHYEAR, HIGHPERIOD, CREATEDDATETIME, ALLOCSTATUS, INPUTDATE, INPUTTIME
FROM HAVEN_RAW.DREAM.D_ALLOCATION;

CREATE VIEW HAVEN_BASE.DREAM.D_KEYLISTKEY
( KEYLIST, KEYLISTKEY, TITLE, KEYLISTNUMBER, KEYLISTVALUE, KEYLISTTEXT )
AS SELECT KEYLIST, KEYLISTKEY, TITLE, KEYLISTNUMBER, KEYLISTVALUE, KEYLISTTEXT
FROM HAVEN_RAW.DREAM.D_KEYLISTKEY;

CREATE VIEW HAVEN_BASE.DREAM.D_NAMEBANKINFO
( LEDGER, ACCOUNT, SORTCODE, ACCOUNTTYPE, ACCOUNTNUMBER, PAYEE, USERNID, INPUTTIME, CUSTOMFIELD1, CUSTOMFIELD2, CUSTOMFIELD3, CUSTOMFIELD4, CUSTOMFIELD5, CUSTOMFIELD6, CUSTOMFIELD7, CUSTOMFIELD8, CUSTOMFIELD9, CUSTOMFIELD10, CUSTOMFIELD11, CUSTOMFIELD12, BANKFORMAT, FACTORLEDGER, FACTORACCOUNT, ACCESSID, SQSACCESS )
AS SELECT LEDGER, "ACCOUNT", SORTCODE, ACCOUNTTYPE, ACCOUNTNUMBER, PAYEE, USERNID, INPUTTIME, CUSTOMFIELD1, CUSTOMFIELD2, CUSTOMFIELD3, CUSTOMFIELD4, CUSTOMFIELD5, CUSTOMFIELD6, CUSTOMFIELD7, CUSTOMFIELD8, CUSTOMFIELD9, CUSTOMFIELD10, CUSTOMFIELD11, CUSTOMFIELD12, BANKFORMAT, FACTORLEDGER, FACTORACCOUNT, ACCESSID, SQSACCESS
FROM HAVEN_RAW.DREAM.D_NAMEBANKINFO;

CREATE VIEW HAVEN_BASE.DREAM.D_NAMETERMS
( LEDGER, ACCOUNT, TERMS, TERMMONTHS, TERMDAYS, TERMRATE, TERMTYPE, USERNID, INPUTTIME )
AS SELECT LEDGER, "ACCOUNT", TERMS, TERMMONTHS, TERMDAYS, TERMRATE, TERMTYPE, USERNID, INPUTTIME
FROM HAVEN_RAW.DREAM.D_NAMETERMS;

CREATE VIEW HAVEN_BASE.DREAM.M_ALLOCATION
( COMPANYCODE, ALLOCTYPE, ALLOCNUM, NOMINAL, ACCOUNT, PAYLIST )
AS SELECT COMPANYCODE, ALLOCTYPE, ALLOCNUM, NOMINAL, "ACCOUNT", PAYLIST
FROM HAVEN_RAW.DREAM.M_ALLOCATION;

CREATE VIEW HAVEN_BASE.DREAM.M_BALANCE
( COMPANYCODE, TRANTYPE, YEARCODE, PERIOD, NOMINAL, LEDGER, ACCOUNT, L3LEDGER, L3ACCOUNT, DETCOUNT, USERVALUE, BALANCE, ALTHOMEBAL, NOMCURRENCY, ACCCURRENCY, L3CURRENCY )
AS SELECT COMPANYCODE, TRANTYPE, YEARCODE, PERIOD, NOMINAL, LEDGER, "ACCOUNT", L3LEDGER, L3ACCOUNT, DETCOUNT, USERVALUE, BALANCE, ALTHOMEBAL, NOMCURRENCY, ACCCURRENCY, L3CURRENCY
FROM HAVEN_RAW.DREAM.M_BALANCE;

CREATE VIEW HAVEN_BASE.DREAM.M_DOCUMENT
( DOCTYPE, DOCNUM, DOCDATE, YEARCODE, PERIOD, MODIFIEDDATETIME, CURRENCY, AUTHDATETIME, CREATEDDATETIME, COMPANYCODE, CREATEDBY, AUTHNID, AUTHORISED, DOCUMENTID, MODIFIEDBY, INPUTDATE, INPUTTIME, PREVIOUSDATE, PREVIOUSTIME, USERNID )
AS SELECT DOCTYPE, DOCNUM, DOCDATE, YEARCODE, PERIOD, MODIFIEDDATETIME, CURRENCY, AUTHDATETIME, CREATEDDATETIME, COMPANYCODE, CREATEDBY, AUTHNID, AUTHORISED, DOCUMENTID, MODIFIEDBY, INPUTDATE, INPUTTIME, PREVIOUSDATE, PREVIOUSTIME, USERNID
FROM HAVEN_RAW.DREAM.M_DOCUMENT;

CREATE VIEW HAVEN_BASE.DREAM.M_NAMEACCOUNT
( LEDGER, ACCOUNT, PRENAME, ADDRESSNAME, ADDRESS1, ADDRESS2, ADDRESS3, POSTTOWN, COUNTY, POSTCODE1, POSTCODE2, COUNTRY, TELEPHONE, FAXNO, CONTACT, SALUTATION, RSCOMMENT, ADDRESSFORMAT, USERNID, INPUTTIME, EMAILADDRESS, URL, TELEPHONE2, ADDRESSTYPE, ADDRESSCODE, DEFAULTADDRESS, SQSACCESS )
AS SELECT LEDGER, "ACCOUNT", PRENAME, ADDRESSNAME, ADDRESS1, ADDRESS2, ADDRESS3, POSTTOWN, COUNTY, POSTCODE1, POSTCODE2, COUNTRY, TELEPHONE, FAXNO, CONTACT, SALUTATION, RSCOMMENT, ADDRESSFORMAT, USERNID, INPUTTIME, EMAILADDRESS, URL, TELEPHONE2, ADDRESSTYPE, ADDRESSCODE, DEFAULTADDRESS, SQSACCESS
FROM HAVEN_RAW.DREAM.M_NAMEACCOUNT;

CREATE VIEW HAVEN_BASE.DREAM.M_PERIOD
( YEARCODE, PERIOD, TITLE, PERIODEND, SQSACCESS, MNEMONIC, COLUMNNAME, ACCESSID, COMPANYCODE, WEIGHTING, PERIODTYPE, PERIODID, PERIODSTART )
AS SELECT YEARCODE, PERIOD, TITLE, PERIODEND, SQSACCESS, MNEMONIC, COLUMNNAME, ACCESSID, COMPANYCODE, WEIGHTING, PERIODTYPE, PERIODID, PERIODSTART
FROM HAVEN_RAW.DREAM.M_PERIOD;

CREATE VIEW HAVEN_BASE.DREAM.M_USER
( USERNID, SQSUSERGROUP, TITLE, PWLASTCHANGE, PWLASTPW, LANGUAGE, TYPE, EMAILADDRESS, LONGUSERNAME, USERIDENTITY )
AS SELECT USERNID, SQSUSERGROUP, TITLE, PWLASTCHANGE, PWLASTPW, "LANGUAGE", "TYPE", EMAILADDRESS, LONGUSERNAME, USERIDENTITY
FROM HAVEN_RAW.DREAM.M_USER;