USE ROLE dba;

use SCHEMA haven_base.plot;

CREATE OR REPLACE VIEW HAVEN_BASE.PLOT.PITCH_LPG_INSPECTION_PROPERTY_DEFINITIONS
( PITCH_LPG_INSPECTION_PROPERTY_DEFINITION_ID, PROPERTY_NAME, PROPERTY_LABEL, VIEW_RIGHT_ENUM, EDIT_RIGHT_ENUM, PROPERTY_DATA_TYPE_ENUM, PROPERTY_DATA_TYPE_LIST_ID, PITCH_LPG_INSPECTION_PROPERTY_GROUP_ID, PITCH_LPG_INSPECTION_DEFINITION_ORDER, MAXIMUM_LENGTH, DELETED_YN, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT, MANDATORY_YN )
AS SELECT PITCH_LPG_INSPECTION_PROPERTY_DEFINITION_ID, PROPERTY_NAME, PROPERTY_LABEL, VIEW_RIGHT_ENUM, EDIT_RIGHT_ENUM, PROPERTY_DATA_TYPE_ENUM, PROPERTY_DATA_TYPE_LIST_ID, PITCH_LPG_INSPECTION_PROPERTY_GROUP_ID, PITCH_LPG_INSPECTION_DEFINITION_ORDER, MAXIMUM_LENGTH, DELETED_YN, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT, MANDATORY_YN
FROM HAVEN_RAW.PLOT.PITCH_LPG_INSPECTION_PROPERTY_DEFINITIONS;

CREATE VIEW HAVEN_BASE.PLOT.PITCH_LPG_INSPECTION_PROPERTY_VALUES
( PITCH_LPG_INSPECTION_PROPERTY_VALUE_ID, PITCH_INSPECTION_ID, PITCH_LPG_INSPECTION_PROPERTY_DEFINITION_ID, PITCH_LPG_INSPECTION_PROPERTY_VALUE, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT )
AS SELECT PITCH_LPG_INSPECTION_PROPERTY_VALUE_ID, PITCH_INSPECTION_ID, PITCH_LPG_INSPECTION_PROPERTY_DEFINITION_ID, PITCH_LPG_INSPECTION_PROPERTY_VALUE, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT
FROM HAVEN_RAW.PLOT.PITCH_LPG_INSPECTION_PROPERTY_VALUES;

CREATE VIEW HAVEN_BASE.PLOT.PROPERTY_DATA_TYPE_LIST_ITEMS
( PROPERTY_DATA_TYPE_LIST_ITEM_ID, PROPERTY_DATA_TYPE_LIST_ID, PROPERTY_DATA_TYPE_LIST_ITEM_DESC, PROPERTY_DATA_TYPE_LIST_ITEM_ORDER, DELETED_YN, CREATED_DT, CREATED_BY, EDIT_DT, EDIT_BY )
AS SELECT PROPERTY_DATA_TYPE_LIST_ITEM_ID, PROPERTY_DATA_TYPE_LIST_ID, PROPERTY_DATA_TYPE_LIST_ITEM_DESC, PROPERTY_DATA_TYPE_LIST_ITEM_ORDER, DELETED_YN, CREATED_DT, CREATED_BY, EDIT_DT, EDIT_BY
FROM HAVEN_RAW.PLOT.PROPERTY_DATA_TYPE_LIST_ITEMS;

--03/06/2024

CREATE VIEW HAVEN_BASE.PLOT.LET2OWN_SCRIPT_RUNS_PLAN_B
( LET2OWN_SCRIPT_RUN_PLAN_B_ID, RUN_DT, YEAR_VALUE, EXCLUDED_PITCH_STATUSES )
AS SELECT LET2OWN_SCRIPT_RUN_PLAN_B_ID, RUN_DT, YEAR_VALUE, EXCLUDED_PITCH_STATUSES
FROM HAVEN_RAW.PLOT.LET2OWN_SCRIPT_RUNS_PLAN_B;

CREATE VIEW HAVEN_BASE.PLOT.LET2OWN_SCRIPT_RUN_ACCOUNTS
( LET2OWN_SCRIPT_RUN_ACCOUNT_ID, LET2OWN_SCRIPT_RUN_ID, ACCOUNT_NO, ACCOUNT_ID, PITCH_STATUS_CODE, LETTING_CAT_CODE, LETTING_CAT_DESC, LETTING_CAT_ID, LATEST_SALE_STATUS, LATEST_SALE_TYPE, LATEST_SALE_CSI, LATEST_SALE_KEY_HANDOVER_DT, MINIMUM_OFF_PEAK_BREAKS_4, MINIMUM_OFF_PEAK_BREAKS_3, MINIMUM_PEAK_BREAKS_4, MINIMUM_PEAK_BREAKS_3, MINIMUM_SUPER_PEAK_BREAKS_4, MINIMUM_SUPER_PEAK_BREAKS_3, MINIMUM_TOTAL_BREAKS, MINIMUM_LETTING_INCOME, OFF_PEAK_BREAKS_AT_HANDOVER_4, OFF_PEAK_BREAKS_AT_HANDOVER_3, PEAK_BREAKS_AT_HANDOVER_4, PEAK_BREAKS_AT_HANDOVER_3, SUPER_PEAK_BREAKS_AT_HANDOVER_4, SUPER_PEAK_BREAKS_AT_HANDOVER_3, MINIMUM_MONTHLY_LETTING_INCOME, MINIMUM_OFF_PEAK_BREAKS_NOV_4, MINIMUM_OFF_PEAK_BREAKS_NOV_3, MINIMUM_PEAK_BREAKS_NOV_4, MINIMUM_PEAK_BREAKS_NOV_3, MINIMUM_SUPER_PEAK_BREAKS_NOV_4, MINIMUM_SUPER_PEAK_BREAKS_NOV_3, MINIMUM_BREAKS_NOV, MINIMUM_LETTING_INCOME_NOV, MINIMUM_MONTHLY_LETTING_INCOME_NOV, FINANCE_MONTHLY_AMOUNT, ANNUAL_SITE_FEE_CHARGE, ANNUAL_RENT_REDUCTION, ANNUAL_SITE_FEE_CHARGE_MONTHLY, ANNUAL_RENT_REDUCTION_MONTHLY, ANNUAL_GROSS_SITE_FEE, SITE_FEE_PRO_RATA_DISCOUNT, ANNUAL_NET_SITE_FEE_CHARGE, MONTHLY_NET_SITE_FEE_CHARGE, NUMBER_OF_MONTHS, MONTHLY_FEE_NOV, SITE_FEE_CONTRIBUTION_ACTUAL, SITE_FEE_CONTRIBUTION_ACTUAL_MONTHLY, SITE_FEE_CONTRIBUTION_INVOICE_NO )
AS SELECT LET2OWN_SCRIPT_RUN_ACCOUNT_ID, LET2OWN_SCRIPT_RUN_ID, ACCOUNT_NO, ACCOUNT_ID, PITCH_STATUS_CODE, LETTING_CAT_CODE, LETTING_CAT_DESC, LETTING_CAT_ID, LATEST_SALE_STATUS, LATEST_SALE_TYPE, LATEST_SALE_CSI, LATEST_SALE_KEY_HANDOVER_DT, MINIMUM_OFF_PEAK_BREAKS_4, MINIMUM_OFF_PEAK_BREAKS_3, MINIMUM_PEAK_BREAKS_4, MINIMUM_PEAK_BREAKS_3, MINIMUM_SUPER_PEAK_BREAKS_4, MINIMUM_SUPER_PEAK_BREAKS_3, MINIMUM_TOTAL_BREAKS, MINIMUM_LETTING_INCOME, OFF_PEAK_BREAKS_AT_HANDOVER_4, OFF_PEAK_BREAKS_AT_HANDOVER_3, PEAK_BREAKS_AT_HANDOVER_4, PEAK_BREAKS_AT_HANDOVER_3, SUPER_PEAK_BREAKS_AT_HANDOVER_4, SUPER_PEAK_BREAKS_AT_HANDOVER_3, MINIMUM_MONTHLY_LETTING_INCOME, MINIMUM_OFF_PEAK_BREAKS_NOV_4, MINIMUM_OFF_PEAK_BREAKS_NOV_3, MINIMUM_PEAK_BREAKS_NOV_4, MINIMUM_PEAK_BREAKS_NOV_3, MINIMUM_SUPER_PEAK_BREAKS_NOV_4, MINIMUM_SUPER_PEAK_BREAKS_NOV_3, MINIMUM_BREAKS_NOV, MINIMUM_LETTING_INCOME_NOV, MINIMUM_MONTHLY_LETTING_INCOME_NOV, FINANCE_MONTHLY_AMOUNT, ANNUAL_SITE_FEE_CHARGE, ANNUAL_RENT_REDUCTION, ANNUAL_SITE_FEE_CHARGE_MONTHLY, ANNUAL_RENT_REDUCTION_MONTHLY, ANNUAL_GROSS_SITE_FEE, SITE_FEE_PRO_RATA_DISCOUNT, ANNUAL_NET_SITE_FEE_CHARGE, MONTHLY_NET_SITE_FEE_CHARGE, NUMBER_OF_MONTHS, MONTHLY_FEE_NOV, SITE_FEE_CONTRIBUTION_ACTUAL, SITE_FEE_CONTRIBUTION_ACTUAL_MONTHLY, SITE_FEE_CONTRIBUTION_INVOICE_NO
FROM HAVEN_RAW.PLOT.LET2OWN_SCRIPT_RUN_ACCOUNTS;

CREATE VIEW HAVEN_BASE.PLOT.LET2OWN_SCRIPT_RUN_ACCOUNTS_PLAN_B
( LET2OWN_SCRIPT_RUN_ACCOUNT_PLAN_B_ID, LET2OWN_SCRIPT_RUN_PLAN_B_ID, ACCOUNT_NO, ACCOUNT_ID, PITCH_STATUS_CODE, LETTING_CAT_CODE, LETTING_CAT_DESC, LETTING_CAT_ID, LATEST_SALE_STATUS, LATEST_SALE_TYPE, LATEST_SALE_CSI, LATEST_SALE_KEY_HANDOVER_DT, MINIMUM_OFF_PEAK_BREAKS_4, MINIMUM_OFF_PEAK_BREAKS_3, MINIMUM_PEAK_BREAKS_4, MINIMUM_PEAK_BREAKS_3, MINIMUM_SUPER_PEAK_BREAKS_4, MINIMUM_SUPER_PEAK_BREAKS_3, MINIMUM_TOTAL_BREAKS, MINIMUM_LETTING_INCOME, OFF_PEAK_BREAKS_4, OFF_PEAK_BREAKS_3, PEAK_BREAKS_4, PEAK_BREAKS_3, SUPER_PEAK_BREAKS_4, SUPER_PEAK_BREAKS_3, MINIMUM_MONTHLY_LETTING_INCOME, MINIMUM_OFF_PEAK_BREAKS_NOV_4, MINIMUM_OFF_PEAK_BREAKS_NOV_3, MINIMUM_PEAK_BREAKS_NOV_4, MINIMUM_PEAK_BREAKS_NOV_3, MINIMUM_SUPER_PEAK_BREAKS_NOV_4, MINIMUM_SUPER_PEAK_BREAKS_NOV_3, MINIMUM_BREAKS_NOV, MINIMUM_LETTING_INCOME_NOV, MINIMUM_MONTHLY_LETTING_INCOME_NOV, FINANCE_MONTHLY_AMOUNT, ANNUAL_SITE_FEE_CHARGE, ANNUAL_RENT_REDUCTION, ANNUAL_SITE_FEE_CHARGE_MONTHLY, ANNUAL_RENT_REDUCTION_MONTHLY, ANNUAL_GROSS_SITE_FEE, SITE_FEE_PRO_RATA_DISCOUNT, SITE_FEE_PRO_RATA_DISCOUNT_MONTHLY, ANNUAL_NET_SITE_FEE_CHARGE, MONTHLY_NET_SITE_FEE_CHARGE, NUMBER_OF_MONTHS, MONTHLY_FEE_NOV, SITE_FEE_CONTRIBUTION_ACTUAL, SITE_FEE_CONTRIBUTION_ACTUAL_MONTHLY, SITE_FEE_CONTRIBUTION_INVOICE_NO, YEAR_VALUE, LETTING_INCOME_VALUE, LETTING_INCOME_VALUE_MONTHLY, FROZEN_YN )
AS SELECT LET2OWN_SCRIPT_RUN_ACCOUNT_PLAN_B_ID, LET2OWN_SCRIPT_RUN_PLAN_B_ID, ACCOUNT_NO, ACCOUNT_ID, PITCH_STATUS_CODE, LETTING_CAT_CODE, LETTING_CAT_DESC, LETTING_CAT_ID, LATEST_SALE_STATUS, LATEST_SALE_TYPE, LATEST_SALE_CSI, LATEST_SALE_KEY_HANDOVER_DT, MINIMUM_OFF_PEAK_BREAKS_4, MINIMUM_OFF_PEAK_BREAKS_3, MINIMUM_PEAK_BREAKS_4, MINIMUM_PEAK_BREAKS_3, MINIMUM_SUPER_PEAK_BREAKS_4, MINIMUM_SUPER_PEAK_BREAKS_3, MINIMUM_TOTAL_BREAKS, MINIMUM_LETTING_INCOME, OFF_PEAK_BREAKS_4, OFF_PEAK_BREAKS_3, PEAK_BREAKS_4, PEAK_BREAKS_3, SUPER_PEAK_BREAKS_4, SUPER_PEAK_BREAKS_3, MINIMUM_MONTHLY_LETTING_INCOME, MINIMUM_OFF_PEAK_BREAKS_NOV_4, MINIMUM_OFF_PEAK_BREAKS_NOV_3, MINIMUM_PEAK_BREAKS_NOV_4, MINIMUM_PEAK_BREAKS_NOV_3, MINIMUM_SUPER_PEAK_BREAKS_NOV_4, MINIMUM_SUPER_PEAK_BREAKS_NOV_3, MINIMUM_BREAKS_NOV, MINIMUM_LETTING_INCOME_NOV, MINIMUM_MONTHLY_LETTING_INCOME_NOV, FINANCE_MONTHLY_AMOUNT, ANNUAL_SITE_FEE_CHARGE, ANNUAL_RENT_REDUCTION, ANNUAL_SITE_FEE_CHARGE_MONTHLY, ANNUAL_RENT_REDUCTION_MONTHLY, ANNUAL_GROSS_SITE_FEE, SITE_FEE_PRO_RATA_DISCOUNT, SITE_FEE_PRO_RATA_DISCOUNT_MONTHLY, ANNUAL_NET_SITE_FEE_CHARGE, MONTHLY_NET_SITE_FEE_CHARGE, NUMBER_OF_MONTHS, MONTHLY_FEE_NOV, SITE_FEE_CONTRIBUTION_ACTUAL, SITE_FEE_CONTRIBUTION_ACTUAL_MONTHLY, SITE_FEE_CONTRIBUTION_INVOICE_NO, YEAR_VALUE, LETTING_INCOME_VALUE, LETTING_INCOME_VALUE_MONTHLY, FROZEN_YN
FROM HAVEN_RAW.PLOT.LET2OWN_SCRIPT_RUN_ACCOUNTS_PLAN_B;

SELECT * FROM HAVEN_BASE.PLOT.LET2OWN_SCRIPT_RUN_ACCOUNTS_PLAN_B;

USE ROLE dba;

USE SCHEMA haven_raw.plot;

DESCRIBE TABLE VANS_AUDIT ;

USE SCHEMA haven_base.plot;

--19/06/2024

USE ROLE dba;

CREATE VIEW HAVEN_BASE.PLOT.PRICES_AUDIT
( CHANGE_DT, CHANGE_TYPE, PRICE_ID, PRICE_TYPE_ENUM, VAN_ID, SALE_ID, GROSS_PRICE, VAT_AMOUNT_NON_SVL, OTHER_TYPE_DESC, EDIT_BY, EDIT_DT, SVL_VAT_AMOUNT, PRICE_DEFAULT_ID, NEW_PRICE_YN, CREATED_BY, CREATED_DT, SALES_QUOTE_ID, DISCOUNT_AMOUNT, PRICE_AUDIT_ID )
AS SELECT CHANGE_DT, CHANGE_TYPE, PRICE_ID, PRICE_TYPE_ENUM, VAN_ID, SALE_ID, GROSS_PRICE, VAT_AMOUNT_NON_SVL, OTHER_TYPE_DESC, EDIT_BY, EDIT_DT, SVL_VAT_AMOUNT, PRICE_DEFAULT_ID, NEW_PRICE_YN, CREATED_BY, CREATED_DT, SALES_QUOTE_ID, DISCOUNT_AMOUNT, PRICE_AUDIT_ID
FROM HAVEN_RAW.PLOT.PRICES_AUDIT;

SELECT COUNT(*) FROM HAVEN_BASE.PLOT.PRICES_AUDIT;

--27/06/2024

USE ROLE dba;

USE SCHEMA haven_raw.plot;

CREATE VIEW HAVEN_BASE.PLOT.OWNER_TYPES
( OWNER_TYPE_ENUM, OWNER_TYPE_DESC, CAN_HAVE_BLG_INSURANCE_YN, ACTIVE_YN )
AS SELECT OWNER_TYPE_ENUM, OWNER_TYPE_DESC, CAN_HAVE_BLG_INSURANCE_YN, ACTIVE_YN
FROM HAVEN_RAW.PLOT.OWNER_TYPES;

