USE ROLE dba;

USE SCHEMA warner_base.seaware_aps;

CREATE VIEW WARNER_BASE.SEAWARE_APS.RES_STATUS
( RES_STATUS, RES_STATUS_NAME, COMMENTS, RES_STATUS_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_STATUS, RES_STATUS_NAME, COMMENTS, RES_STATUS_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_STATUS;

CREATE VIEW WARNER_BASE.SEAWARE_APS.USER_LOGIN
( USER_ID, USER_LOGIN_NAME, USER_PASSWORD, USER_FIRST_NAME, USER_MIDDLE_NAME, USER_LAST_NAME, USER_FULL_NAME, COMMENTS, OFFICE_CODE, ADMINISTRATIVE_OFFICE, OFFICE_LOCATION_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT USER_ID, USER_LOGIN_NAME, USER_PASSWORD, USER_FIRST_NAME, USER_MIDDLE_NAME, USER_LAST_NAME, USER_FULL_NAME, COMMENTS, OFFICE_CODE, ADMINISTRATIVE_OFFICE, OFFICE_LOCATION_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.USER_LOGIN;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_PAY_DUE_ITEM
( RECORD_ID, GROUP_ID, PMNT_DUE_ITEM_TYPE, DUE_DATE, GRACE_PERIOD, AMOUNT, ACTIVITY_TYPE, ACTIVITY_DATE, ACTIVITY_EFFECTIVE_DATE, ACTIVITY_INFO, DELEGATE_RES_ID, CABIN_NUMBER, IS_ADJUSTMENT, CABIN_CATEGORY, OCCUPANCY, SHIP_CODE, EXPIRATION_DATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_ID, PMNT_DUE_ITEM_TYPE, DUE_DATE, GRACE_PERIOD, AMOUNT, ACTIVITY_TYPE, ACTIVITY_DATE, ACTIVITY_EFFECTIVE_DATE, ACTIVITY_INFO, DELEGATE_RES_ID, CABIN_NUMBER, IS_ADJUSTMENT, CABIN_CATEGORY, OCCUPANCY, SHIP_CODE, EXPIRATION_DATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_PAY_DUE_ITEM;

USE SCHEMA warner_store.seaware_aps;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_STATUS
( RES_STATUS, RES_STATUS_NAME, COMMENTS, RES_STATUS_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_STATUS, RES_STATUS_NAME, COMMENTS, RES_STATUS_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_STATUS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.USER_LOGIN
( USER_ID, USER_LOGIN_NAME, USER_PASSWORD, USER_FIRST_NAME, USER_MIDDLE_NAME, USER_LAST_NAME, USER_FULL_NAME, COMMENTS, OFFICE_CODE, ADMINISTRATIVE_OFFICE, OFFICE_LOCATION_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT USER_ID, USER_LOGIN_NAME, USER_PASSWORD, USER_FIRST_NAME, USER_MIDDLE_NAME, USER_LAST_NAME, USER_FULL_NAME, COMMENTS, OFFICE_CODE, ADMINISTRATIVE_OFFICE, OFFICE_LOCATION_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.USER_LOGIN;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_PAY_DUE_ITEM
( RECORD_ID, GROUP_ID, PMNT_DUE_ITEM_TYPE, DUE_DATE, GRACE_PERIOD, AMOUNT, ACTIVITY_TYPE, ACTIVITY_DATE, ACTIVITY_EFFECTIVE_DATE, ACTIVITY_INFO, DELEGATE_RES_ID, CABIN_NUMBER, IS_ADJUSTMENT, CABIN_CATEGORY, OCCUPANCY, SHIP_CODE, EXPIRATION_DATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_ID, PMNT_DUE_ITEM_TYPE, DUE_DATE, GRACE_PERIOD, AMOUNT, ACTIVITY_TYPE, ACTIVITY_DATE, ACTIVITY_EFFECTIVE_DATE, ACTIVITY_INFO, DELEGATE_RES_ID, CABIN_NUMBER, IS_ADJUSTMENT, CABIN_CATEGORY, OCCUPANCY, SHIP_CODE, EXPIRATION_DATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_PAY_DUE_ITEM;

USE ROLE securityadmin;
GRANT SELECT ON  VIEW WARNER_STORE.SEAWARE_APS.RES_STATUS to database role warner_store.aps_share;
GRANT SELECT ON  VIEW WARNER_STORE.SEAWARE_APS.USER_LOGIN to database role warner_store.aps_share;
GRANT SELECT ON  VIEW WARNER_STORE.SEAWARE_APS.GROUP_PAY_DUE_ITEM to database role warner_store.aps_share;

USE ROLE dba;
USE SCHEMA warner_base.seaware_aps;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_AMENITY_REQUEST
( RECORD_ID, GROUP_ID, AMENITY_CODE, ORDER_BASIS, REQUESTED_QTY, EFFECTIVE_DATE, ORDER_BASIS_QTY, IS_AUTO, GROUP_SHIP_REQ_ID, RESTRICTED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_ID, AMENITY_CODE, ORDER_BASIS, REQUESTED_QTY, EFFECTIVE_DATE, ORDER_BASIS_QTY, IS_AUTO, GROUP_SHIP_REQ_ID, RESTRICTED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_AMENITY_REQUEST;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_COMMISSION_DETAIL
( RECORD_ID, AMOUNT, COMMISS_FARE, COMMISS_CODE, COMMISS_SOURCE, INVOICE_ITEM_TYPE, PERCENT, GROUP_ID, PACKAGE_ID, IS_MANUAL_ADJUSTMENT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, AMOUNT, COMMISS_FARE, COMMISS_CODE, COMMISS_SOURCE, INVOICE_ITEM_TYPE, "PERCENT", GROUP_ID, PACKAGE_ID, IS_MANUAL_ADJUSTMENT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_COMMISSION_DETAIL;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_INVOICE_ITEM
( RECORD_ID, GROUP_ID, REC_SEQN, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, QUANTITY, EFF_DATE, BROCHURE_PRICE, EBD_PRICE, GROUP_PRICE, TOTAL_PRICE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, IS_MANUAL_ADJUSTMENT, PROMO_CODE, GROUP_SHIP_REQ_ID, GROUP_HOTEL_REQ_ID, GROUP_PACKAGE_ID, GROUP_AIR_REQ_ID, PACKAGE_ID, COMMISSION_PERCENT, DUMMY_RES_SEQN, GUEST_SEQN, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_ID, REC_SEQN, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, QUANTITY, EFF_DATE, BROCHURE_PRICE, EBD_PRICE, GROUP_PRICE, TOTAL_PRICE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, IS_MANUAL_ADJUSTMENT, PROMO_CODE, GROUP_SHIP_REQ_ID, GROUP_HOTEL_REQ_ID, GROUP_PACKAGE_ID, GROUP_AIR_REQ_ID, PACKAGE_ID, COMMISSION_PERCENT, DUMMY_RES_SEQN, GUEST_SEQN, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_INVOICE_ITEM;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_PROMOTION
( GROUP_PROMOTION_ID, GROUP_ID, GROUP_SHIP_REQ_ID, PROMO_CODE, GUEST_MASK, REQUESTED_COUNT, UNASSIGNED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE)
AS SELECT GROUP_PROMOTION_ID, GROUP_ID, GROUP_SHIP_REQ_ID, PROMO_CODE, GUEST_MASK, REQUESTED_COUNT, UNASSIGNED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_PROMOTION;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_SHIP_REQUEST
( RECORD_ID, CABIN_CATEGORY, OCCUPANCY, QUANTITY, PRODUCT_TYPE, CABIN_CATEGORY_BERTH, PACKAGE_TYPE, SHIP_CODE, GROUP_ID, EFFECTIVE_DATE, PACKAGE_ID, ROLLAWAY_BEDS_REQUESTED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, CABIN_CATEGORY, OCCUPANCY, QUANTITY, PRODUCT_TYPE, CABIN_CATEGORY_BERTH, PACKAGE_TYPE, SHIP_CODE, GROUP_ID, EFFECTIVE_DATE, PACKAGE_ID, ROLLAWAY_BEDS_REQUESTED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_SHIP_REQUEST;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_SHIP_UNIT_ATTR
( RECORD_ID, GROUP_ID, GROUP_SHIP_REQ_ID, REQUEST_TYPE, ATTRIBUTE_CODE, STR_VALUE, INT_VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_ID, GROUP_SHIP_REQ_ID, REQUEST_TYPE, ATTRIBUTE_CODE, STR_VALUE, INT_VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_SHIP_UNIT_ATTR;

USE ROLE dba;
USE SCHEMA warner_STORE.seaware_aps;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_AMENITY_REQUEST
( RECORD_ID, GROUP_ID, AMENITY_CODE, ORDER_BASIS, REQUESTED_QTY, EFFECTIVE_DATE, ORDER_BASIS_QTY, IS_AUTO, GROUP_SHIP_REQ_ID, RESTRICTED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_ID, AMENITY_CODE, ORDER_BASIS, REQUESTED_QTY, EFFECTIVE_DATE, ORDER_BASIS_QTY, IS_AUTO, GROUP_SHIP_REQ_ID, RESTRICTED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_AMENITY_REQUEST;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_COMMISSION_DETAIL
( RECORD_ID, AMOUNT, COMMISS_FARE, COMMISS_CODE, COMMISS_SOURCE, INVOICE_ITEM_TYPE, PERCENT, GROUP_ID, PACKAGE_ID, IS_MANUAL_ADJUSTMENT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, AMOUNT, COMMISS_FARE, COMMISS_CODE, COMMISS_SOURCE, INVOICE_ITEM_TYPE, "PERCENT", GROUP_ID, PACKAGE_ID, IS_MANUAL_ADJUSTMENT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_COMMISSION_DETAIL;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_INVOICE_ITEM
( RECORD_ID, GROUP_ID, REC_SEQN, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, QUANTITY, EFF_DATE, BROCHURE_PRICE, EBD_PRICE, GROUP_PRICE, TOTAL_PRICE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, IS_MANUAL_ADJUSTMENT, PROMO_CODE, GROUP_SHIP_REQ_ID, GROUP_HOTEL_REQ_ID, GROUP_PACKAGE_ID, GROUP_AIR_REQ_ID, PACKAGE_ID, COMMISSION_PERCENT, DUMMY_RES_SEQN, GUEST_SEQN, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_ID, REC_SEQN, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, QUANTITY, EFF_DATE, BROCHURE_PRICE, EBD_PRICE, GROUP_PRICE, TOTAL_PRICE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, IS_MANUAL_ADJUSTMENT, PROMO_CODE, GROUP_SHIP_REQ_ID, GROUP_HOTEL_REQ_ID, GROUP_PACKAGE_ID, GROUP_AIR_REQ_ID, PACKAGE_ID, COMMISSION_PERCENT, DUMMY_RES_SEQN, GUEST_SEQN, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_INVOICE_ITEM;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_PROMOTION
( GROUP_PROMOTION_ID, GROUP_ID, GROUP_SHIP_REQ_ID, PROMO_CODE, GUEST_MASK, REQUESTED_COUNT, UNASSIGNED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE)
AS SELECT GROUP_PROMOTION_ID, GROUP_ID, GROUP_SHIP_REQ_ID, PROMO_CODE, GUEST_MASK, REQUESTED_COUNT, UNASSIGNED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_PROMOTION;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_SHIP_REQUEST
( RECORD_ID, CABIN_CATEGORY, OCCUPANCY, QUANTITY, PRODUCT_TYPE, CABIN_CATEGORY_BERTH, PACKAGE_TYPE, SHIP_CODE, GROUP_ID, EFFECTIVE_DATE, PACKAGE_ID, ROLLAWAY_BEDS_REQUESTED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, CABIN_CATEGORY, OCCUPANCY, QUANTITY, PRODUCT_TYPE, CABIN_CATEGORY_BERTH, PACKAGE_TYPE, SHIP_CODE, GROUP_ID, EFFECTIVE_DATE, PACKAGE_ID, ROLLAWAY_BEDS_REQUESTED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_SHIP_REQUEST;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_SHIP_UNIT_ATTR
( RECORD_ID, GROUP_ID, GROUP_SHIP_REQ_ID, REQUEST_TYPE, ATTRIBUTE_CODE, STR_VALUE, INT_VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_ID, GROUP_SHIP_REQ_ID, REQUEST_TYPE, ATTRIBUTE_CODE, STR_VALUE, INT_VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_SHIP_UNIT_ATTR;

USE ROLE SECURITYADMIN;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_AMENITY_REQUEST to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_COMMISSION_DETAIL to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_INVOICE_ITEM to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_PROMOTION to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_SHIP_REQUEST to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_SHIP_UNIT_ATTR to database role warner_store.aps_share;

USE ROLE dba;
USE SCHEMA warner_base.seaware_aps;

CREATE VIEW WARNER_BASE.SEAWARE_APS.AGENT
( AGENT_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, SALUTATION, TITLE, SEX, BIRTHDAY, IATAN_NUMBER, IATAN_COMPANY_NAME, IATAN_HOLDER_NAME, IATAN_COMPANY_NUMBER, COMMENTS, IATAN_EXPIRATION_DATE, EMAIL, IS_DISTRICT_SM, IS_INCENTIVE_SM, WEB_PASSWORD, WEB_LOGIN_NAME, WEB_LAST_LOGIN, WEB_CANACCESAGENCYDATA, ALLOW_WEB_ACCESS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGENT_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, SALUTATION, TITLE, SEX, BIRTHDAY, IATAN_NUMBER, IATAN_COMPANY_NAME, IATAN_HOLDER_NAME, IATAN_COMPANY_NUMBER, COMMENTS, IATAN_EXPIRATION_DATE, EMAIL, IS_DISTRICT_SM, IS_INCENTIVE_SM, WEB_PASSWORD, WEB_LOGIN_NAME, WEB_LAST_LOGIN, WEB_CANACCESAGENCYDATA, ALLOW_WEB_ACCESS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.AGENT;

USE ROLE dba;
USE SCHEMA warner_store.seaware_aps;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.AGENT
( AGENT_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, SALUTATION, TITLE, SEX, BIRTHDAY, IATAN_NUMBER, IATAN_COMPANY_NAME, IATAN_HOLDER_NAME, IATAN_COMPANY_NUMBER, COMMENTS, IATAN_EXPIRATION_DATE, EMAIL, IS_DISTRICT_SM, IS_INCENTIVE_SM, WEB_PASSWORD, WEB_LOGIN_NAME, WEB_LAST_LOGIN, WEB_CANACCESAGENCYDATA, ALLOW_WEB_ACCESS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGENT_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, SALUTATION, TITLE, SEX, BIRTHDAY, IATAN_NUMBER, IATAN_COMPANY_NAME, IATAN_HOLDER_NAME, IATAN_COMPANY_NUMBER, COMMENTS, IATAN_EXPIRATION_DATE, EMAIL, IS_DISTRICT_SM, IS_INCENTIVE_SM, WEB_PASSWORD, WEB_LOGIN_NAME, WEB_LAST_LOGIN, WEB_CANACCESAGENCYDATA, ALLOW_WEB_ACCESS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.AGENT;

USE ROLE SECURITYADMIN;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.AGENT to database role warner_store.aps_share;

GRANT ROLE warner_store_dev_dbt_rw TO USER sunilshinde;

USE ROLE dba;
USE SCHEMA warner_base.seaware_aps;

CREATE VIEW WARNER_BASE.SEAWARE_APS.AGENCY_CONTACT
( AGENCY_CONTACT_ID, AGENCY_ID, AGENT_ID, DATE_FROM, DATE_TO, POSITION, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGENCY_CONTACT_ID, AGENCY_ID, AGENT_ID, DATE_FROM, DATE_TO, "POSITION", COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.AGENCY_CONTACT;

USE ROLE dba;
USE SCHEMA warner_store.seaware_aps;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.AGENCY_CONTACT
( AGENCY_CONTACT_ID, AGENCY_ID, AGENT_ID, DATE_FROM, DATE_TO, POSITION, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGENCY_CONTACT_ID, AGENCY_ID, AGENT_ID, DATE_FROM, DATE_TO, "POSITION", COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.AGENCY_CONTACT;

USE ROLE SECURITYADMIN;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.AGENCY_CONTACT TO DATABASE ROLE WARNER_STORE.APS_SHARE;

USE ROLE securityadmin;

GRANT ROLE WARNER_DATA_MANAGEMENT to role WARNER_DATA_MODELING;

SHOW ro