USE ROLE dba;

USE SCHEMA haven_base.plot;

CREATE VIEW HAVEN_BASE.PLOT.ACCOUNT_TYPE_HISTORY
( ACCOUNT_TYPE_HISTORY_ID, ACCOUNT_ID, ACCOUNT_TYPE_ENUM, EFFECTIVE_FROM_DT, ACCOUNT_TYPE_CHANGE_REASON_ID, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT )
AS SELECT ACCOUNT_TYPE_HISTORY_ID, ACCOUNT_ID, ACCOUNT_TYPE_ENUM, EFFECTIVE_FROM_DT, ACCOUNT_TYPE_CHANGE_REASON_ID, CREATED_BY, CREATED_DT, EDIT_BY, EDIT_DT
FROM HAVEN_RAW.PLOT.ACCOUNT_TYPE_HISTORY;

CREATE VIEW HAVEN_BASE.PLOT.ACCOUNT_TYPES
( ACCOUNT_TYPE_ENUM, ACCOUNT_TYPE_DESC, ACTIVE_YN, DEFAULT_YN )
AS SELECT ACCOUNT_TYPE_ENUM, ACCOUNT_TYPE_DESC, ACTIVE_YN, DEFAULT_YN
FROM HAVEN_RAW.PLOT.ACCOUNT_TYPES;