-- 03/03/2025

-- digital arrivals

USE ROLE dba;

USE SCHEMA haven_base.dig_arrivals_etleap;

SHOW views;

SELECT * FROM anpr_device;

-- 11/03/2025

-- dgital park area

USE ROLE dba;


CREATE VIEW HAVEN_BASE.DIG_PARK_AREAS.AREA
( ID, NAME, CODE, VISIBLE, PARK_ID, CREATED_AT, UPDATED_AT, COORDS, MAP_URL )
AS SELECT ID, "NAME", CODE, VISIBLE, PARK_ID, CREATED_AT, UPDATED_AT, COORDS, MAP_URL
FROM HAVEN_RAW.DIG_PARK_AREAS.AREA;

CREATE VIEW HAVEN_BASE.DIG_PARK_AREAS.PARK
( ID, NAME, CODE, PHONE, ADDRESS, GATE_COORDS, MAP_URL, VISIBLE, REGION_ID, CREATED_AT, UPDATED_AT, EMERGENCY_PHONE, CARAVAN_SALES_PHONE )
AS SELECT ID, "NAME", CODE, PHONE, ADDRESS, GATE_COORDS, MAP_URL, VISIBLE, REGION_ID, CREATED_AT, UPDATED_AT, EMERGENCY_PHONE, CARAVAN_SALES_PHONE
FROM HAVEN_RAW.DIG_PARK_AREAS.PARK;

CREATE VIEW HAVEN_BASE.DIG_PARK_AREAS.REGION
( ID, NAME, VISIBLE, CREATED_AT, UPDATED_AT )
AS SELECT ID, "NAME", VISIBLE, CREATED_AT, UPDATED_AT
FROM HAVEN_RAW.DIG_PARK_AREAS.REGION;

CREATE VIEW HAVEN_BASE.DIG_PARK_AREAS.ZONE
( ID, AREA_ID, CODE, NAME, SECTOR, VISIBLE, CREATED_AT, UPDATED_AT )
AS SELECT ID, AREA_ID, CODE, "NAME", SECTOR, VISIBLE, CREATED_AT, UPDATED_AT
FROM HAVEN_RAW.DIG_PARK_AREAS."ZONE";


