USE ROLE dba;

USE SCHEMA WARNER_BASE.SEAWARE_APS;

CREATE VIEW WARNER_BASE.SEAWARE_APS.RES_HIST_TRANS
( TRANS_ID, RES_ID, TRANS_DATE, PERFORMER, SUBJECT, COMMENTS, SOURCE_CODE, EXTERNAL_USER_ID1, EXTERNAL_USER_ID2, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TRANS_ID, RES_ID, TRANS_DATE, PERFORMER, SUBJECT, COMMENTS, SOURCE_CODE, EXTERNAL_USER_ID1, EXTERNAL_USER_ID2, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_HIST_TRANS;

CREATE VIEW WARNER_BASE.SEAWARE_APS.RES_HIST_TREE
( TREE_NODE_ID, NODE_LEVEL, NODE_NAME, TRANS_ID_INSERT, TRANS_ID_DELETE, KEY_LEVEL_1, KEY_LEVEL_2, KEY_LEVEL_3, KEY_LEVEL_4, KEY_LEVEL_5, KEY_LEVEL_6, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TREE_NODE_ID, NODE_LEVEL, NODE_NAME, TRANS_ID_INSERT, TRANS_ID_DELETE, KEY_LEVEL_1, KEY_LEVEL_2, KEY_LEVEL_3, KEY_LEVEL_4, KEY_LEVEL_5, KEY_LEVEL_6, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_HIST_TREE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.RES_HIST_VALUE
( TREE_NODE_ID, TRANS_ID, ACTION, IT_IS_PARM, FIELD_ID, FIELD_VALUE_OLD, FIELD_VALUE_NEW, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TREE_NODE_ID, TRANS_ID, "ACTION", IT_IS_PARM, FIELD_ID, FIELD_VALUE_OLD, FIELD_VALUE_NEW, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_HIST_VALUE;

USE SCHEMA WARNER_STORE.SEAWARE_APS

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_HIST_TRANS
( TRANS_ID, RES_ID, TRANS_DATE, PERFORMER, SUBJECT, COMMENTS, SOURCE_CODE, EXTERNAL_USER_ID1, EXTERNAL_USER_ID2, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TRANS_ID, RES_ID, TRANS_DATE, PERFORMER, SUBJECT, COMMENTS, SOURCE_CODE, EXTERNAL_USER_ID1, EXTERNAL_USER_ID2, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_HIST_TRANS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_HIST_TREE
( TREE_NODE_ID, NODE_LEVEL, NODE_NAME, TRANS_ID_INSERT, TRANS_ID_DELETE, KEY_LEVEL_1, KEY_LEVEL_2, KEY_LEVEL_3, KEY_LEVEL_4, KEY_LEVEL_5, KEY_LEVEL_6, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TREE_NODE_ID, NODE_LEVEL, NODE_NAME, TRANS_ID_INSERT, TRANS_ID_DELETE, KEY_LEVEL_1, KEY_LEVEL_2, KEY_LEVEL_3, KEY_LEVEL_4, KEY_LEVEL_5, KEY_LEVEL_6, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_HIST_TREE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_HIST_VALUE
( TREE_NODE_ID, TRANS_ID, ACTION, IT_IS_PARM, FIELD_ID, FIELD_VALUE_OLD, FIELD_VALUE_NEW, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TREE_NODE_ID, TRANS_ID, "ACTION", IT_IS_PARM, FIELD_ID, FIELD_VALUE_OLD, FIELD_VALUE_NEW, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_HIST_VALUE;

USE ROLE SECURITYADMIN;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_HIST_TRANS to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_HIST_TREE  to database role warner_store.aps_share;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_HIST_VALUE to database role warner_store.aps_share;

USE ROLE dba;

USE SCHEMA WARNER_BASE.SEAWARE_APS;

CREATE VIEW WARNER_BASE.SEAWARE_APS.HOUSEHOLD
( HOUSEHOLD_ID, HOUSEHOLD_NAME, LAST_NAME_TYPED, LAST_NAME, SALUTATION, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HOUSEHOLD_ID, HOUSEHOLD_NAME, LAST_NAME_TYPED, LAST_NAME, SALUTATION, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.HOUSEHOLD;

USE SCHEMA WARNER_STORE.SEAWARE_APS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.HOUSEHOLD
( HOUSEHOLD_ID, HOUSEHOLD_NAME, LAST_NAME_TYPED, LAST_NAME, SALUTATION, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HOUSEHOLD_ID, HOUSEHOLD_NAME, LAST_NAME_TYPED, LAST_NAME, SALUTATION, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.HOUSEHOLD;

USE ROLE SECURITYADMIN;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.HOUSEHOLD to database role warner_store.aps_share;

