USE ROLE dba;
USE SCHEMA haven_base.DIG_ACCEPTANCE_OF_RISK;

CREATE OR REPLACE VIEW HAVEN_BASE.DIG_ACCEPTANCE_OF_RISK.ACCEPTANCE
( ID, ACCEPTANCEID, RESERVATIONID, STATEMENT, EXPIREAT, USEDBY, SOURCE, CREATEDBY, CREATEDAT, UPDATEDAT, SCOPE, EVIDENCE )
AS SELECT ID, ACCEPTANCEID, RESERVATIONID, "STATEMENT", EXPIREAT, USEDBY, "SOURCE", CREATEDBY, CREATEDAT, UPDATEDAT, "SCOPE", EVIDENCE
FROM HAVEN_RAW.DIG_ACCEPTANCE_OF_RISK.ACCEPTANCE;

