USE ROLE DBA;
USE SCHEMA WARNER_STORE.APS_SHARE;

--SELECT RECORD_ID, AGENCY_ID, COMMISS_CODE, DATE_FROM, DATE_TO, USE_FOR_CHILDREN, USE_FROM_ABOVE FROM WARNER_BASE.SEAWARE.AGENCY_COMMISSION;
--SELECT AGENCY_TYPE_ID, AGENCY_TYPE, COMMENTS FROM WARNER_BASE.SEAWARE.AGENCY_TYPE;
--SELECT AM_DELVR_TYPE, RECORD_ID, COMMENTS FROM WARNER_BASE.SEAWARE.AM_DELVR_TYPE;
--SELECT AM_INVC_ITEM_TYPE, AM_INV_TYPE_ID, INVOICE_RANK FROM WARNER_BASE.SEAWARE.AM_INV_ITEM_TYPE;
--SELECT AM_ORDER_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, AM_REQSTER_TYPE, AGENCY_ID, AGENT_ID, CLIENT_ID, AM_BOOKING_TYPE, RES_ID, GROUP_ID, DISPATCHED_DATE, DISPATCHED_OK, GIFT_CARD_TO, GIFT_CARD_MSG, COMPLIMENTS_OF, ORDER_VALID, TERMINATION_COMPLETED, CREATED_FROM_ADDON, CANCEL_REFUND_DONE, FREE_OF_CHARGE, GROUP_DISTRIBUTION_OK, SHOW_ITEM_LIST, CURRENCY_CODE, AM_ENTITY_TYPE, INVOICE_VALID FROM WARNER_BASE.SEAWARE.AM_ORDER_HEADER;
--SELECT ORD_STATUS_CODE, RECORD_ID, COMMENTS FROM WARNER_BASE.SEAWARE.AM_ORDER_STATUS;
--SELECT RECORD_ID, AM_PLACE_CODE, COMPONENT_TYPE, COMMENTS FROM WARNER_BASE.SEAWARE.AM_PLACE_COMPTYPE_LINK;
--SELECT AM_REQ_TYPE, RECORD_ID, COMMENTS FROM WARNER_BASE.SEAWARE.AM_REQSTER_TYPE;
--SELECT PROVIDER_CODE, RECORD_ID, PROVIDER_TYPE, PROVIDER_NAME, COMMENTS, PROVIDER_CODE_EXTERNAL FROM WARNER_BASE.SEAWARE.AM_SRVCE_PROVIDER;
--SELECT DATE_, PARK_CODE, GRADE_CODE, PRODUCT_TYPE, PITCHES, NA_ABS, HELD, RSRV_UA, RSRV_OL, RSRV_OB, ALLOC, CAP, AVAIL, FIRM, ASGN_ABS, GTY_ABS, "TIMESTAMP", BK, OFR, RSRV_SP FROM WARNER_BASE.SEAWARE.BLL_INV_AVAILABILITY;
--SELECT COMMISS_CODE_ID, COMMISS_CODE, COMMISS_NAME, COMMISS_TYPE, BASIS_TYPE, EXPRESSION_ID, COMMENTS FROM WARNER_BASE.SEAWARE.COMMISSION_CODE;
--SELECT COMMISS_TYPE_ID, COMMISS_TYPE, COMMENTS FROM WARNER_BASE.SEAWARE.COMMISSION_TYPE;
--SELECT COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE FROM WARNER_BASE.SEAWARE.COMPONENT_TYPE;
--SELECT RECORD_ID, INVOICE_ITEM_TYPE, INV_ITEM_GROUP, COMMENTS, INV_ITEM_GROUP_TYPE, OFFICE_CODE FROM WARNER_BASE.SEAWARE.INV_ITEM_GROUP_MATCH;
--SELECT INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_GROUP;
--SELECT INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_GROUP_TYPE;
--SELECT INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_SUBTYPE;
--SELECT INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_TYPE;
--SELECT RES_ADDON_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, RES_ADDON_CODE, START_DATE, END_DATE, EFFECTIVE_DATE, AM_ORDER_ID, IS_DEFAULT, PAP_CODE, AMENITY_CODE, DELIVERY_PLACE, QUANTITY, IS_AUTO, COMMENTS, "TIMESTAMP" FROM WARNER_BASE.SEAWARE.RES_ADDON;
--SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID FROM WARNER_BASE.SEAWARE.RES_INVOICE_CANC;
--SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID FROM WARNER_BASE.SEAWARE.RES_INVOICE_ITEM;
--SELECT RECORD_ID, SHIP_CODE, CABIN_NUMBER, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, RESERVE_TYPE, COMMENTS, GUEST_COUNT FROM WARNER_BASE.SEAWARE.SHIP_CABIN_RESERVE;
--SELECT RECORD_ID, RESERVE_TYPE, DECREMENTS_INVENTORY, ALLOWS_BOOKING, IS_RESTRICTED, IS_SAIL_RESERVE FROM WARNER_BASE.SEAWARE.SHIP_CABIN_RESERVE_TYPE;
--SELECT SP_REQ_CODE, REQ_CODE_ID, SP_REQ_TYPE, PROVIDER_CODE, SP_REQ_NAME, COMMENTS, WDW_CODED_REMARK FROM WARNER_BASE.SEAWARE.SP_REQ_CODE;
--SELECT SP_ORD_ITEM_ID, SP_REQ_ID, SP_REQ_CODE, AM_PLACE_CODE, DELIVERY_DATE, DELIVERY_TIME, QUANTITY, COMMENTS, GUEST_FULL_NAME, GUEST_ID, ITEM_VALID FROM WARNER_BASE.SEAWARE.SP_REQ_ORD_ITEM;
--SELECT SP_REQ_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, ORDER_VALID, AM_BOOKING_TYPE, GROUP_ID, RES_ID, AM_REQ_TYPE, AGENCY_ID, CLIENT_ID, AM_PLACE_CODE, AGENT_ID, DELIVERY_TIME, DISPATCHED_DATE, DISPATCHED_OK, COMMENTS, TERMINATION_COMPLETED FROM WARNER_BASE.SEAWARE.SP_REQ_ORDER;
--SELECT SP_REQ_TYPE_ID, SP_REQ_TYPE, COMMENTS FROM WARNER_BASE.SEAWARE.SP_REQ_TYPE;
--SELECT RECORD_ID, USAGE_AREA, COMMENTS FROM WARNER_BASE.SEAWARE.SP_REQ_USAGE_AREA;


CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AGENCY_COMMISSION
( RECORD_ID, AGENCY_ID, COMMISS_CODE, DATE_FROM, DATE_TO, USE_FOR_CHILDREN, USE_FROM_ABOVE )
 AS SELECT RECORD_ID, AGENCY_ID, COMMISS_CODE, DATE_FROM, DATE_TO, USE_FOR_CHILDREN, USE_FROM_ABOVE
FROM WARNER_BASE.SEAWARE.AGENCY_COMMISSION;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AGENCY_TYPE
( AGENCY_TYPE_ID, AGENCY_TYPE, COMMENTS )
 AS SELECT AGENCY_TYPE_ID, AGENCY_TYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.AGENCY_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AM_DELVR_TYPE
( AM_DELVR_TYPE, RECORD_ID, COMMENTS )
 AS SELECT AM_DELVR_TYPE, RECORD_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.AM_DELVR_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AM_ORDER_HEADER
( AM_ORDER_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, AM_REQSTER_TYPE, AGENCY_ID, AGENT_ID, CLIENT_ID, AM_BOOKING_TYPE, RES_ID, GROUP_ID, DISPATCHED_DATE, DISPATCHED_OK, GIFT_CARD_TO, GIFT_CARD_MSG, COMPLIMENTS_OF, ORDER_VALID, TERMINATION_COMPLETED, CREATED_FROM_ADDON, CANCEL_REFUND_DONE, FREE_OF_CHARGE, GROUP_DISTRIBUTION_OK, SHOW_ITEM_LIST, CURRENCY_CODE, AM_ENTITY_TYPE, INVOICE_VALID )
 AS SELECT AM_ORDER_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, AM_REQSTER_TYPE, AGENCY_ID, AGENT_ID, CLIENT_ID, AM_BOOKING_TYPE, RES_ID, GROUP_ID, DISPATCHED_DATE, DISPATCHED_OK, GIFT_CARD_TO, GIFT_CARD_MSG, COMPLIMENTS_OF, ORDER_VALID, TERMINATION_COMPLETED, CREATED_FROM_ADDON, CANCEL_REFUND_DONE, FREE_OF_CHARGE, GROUP_DISTRIBUTION_OK, SHOW_ITEM_LIST, CURRENCY_CODE, AM_ENTITY_TYPE, INVOICE_VALID
FROM WARNER_BASE.SEAWARE.AM_ORDER_HEADER;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AM_INV_ITEM_TYPE
( AM_INVC_ITEM_TYPE, AM_INV_TYPE_ID, INVOICE_RANK )
AS SELECT AM_INVC_ITEM_TYPE, AM_INV_TYPE_ID, INVOICE_RANK 
FROM WARNER_BASE.SEAWARE.AM_INV_ITEM_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AM_ORDER_STATUS
( ORD_STATUS_CODE, RECORD_ID, COMMENTS )
 AS SELECT ORD_STATUS_CODE, RECORD_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.AM_ORDER_STATUS;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AM_PLACE_COMPTYPE_LINK
( RECORD_ID, AM_PLACE_CODE, COMPONENT_TYPE, COMMENTS )
 AS SELECT RECORD_ID, AM_PLACE_CODE, COMPONENT_TYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.AM_PLACE_COMPTYPE_LINK;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AM_REQSTER_TYPE
( AM_REQ_TYPE, RECORD_ID, COMMENTS )
 AS SELECT AM_REQ_TYPE, RECORD_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.AM_REQSTER_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.AM_SRVCE_PROVIDER
( PROVIDER_CODE, RECORD_ID, PROVIDER_TYPE, PROVIDER_NAME, COMMENTS, PROVIDER_CODE_EXTERNAL )
 AS SELECT PROVIDER_CODE, RECORD_ID, PROVIDER_TYPE, PROVIDER_NAME, COMMENTS, PROVIDER_CODE_EXTERNAL
FROM WARNER_BASE.SEAWARE.AM_SRVCE_PROVIDER;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.BLL_INV_AVAILABILITY
( DATE_, PARK_CODE, GRADE_CODE, PRODUCT_TYPE, PITCHES, NA_ABS, HELD, RSRV_UA, RSRV_OL, RSRV_OB, ALLOC, CAP, AVAIL, FIRM, ASGN_ABS, GTY_ABS, "TIMESTAMP", BK, OFR, RSRV_SP )
 AS SELECT DATE_, PARK_CODE, GRADE_CODE, PRODUCT_TYPE, PITCHES, NA_ABS, HELD, RSRV_UA, RSRV_OL, RSRV_OB, ALLOC, CAP, AVAIL, FIRM, ASGN_ABS, GTY_ABS, "TIMESTAMP", BK, OFR, RSRV_SP
FROM WARNER_BASE.SEAWARE.BLL_INV_AVAILABILITY;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.COMMISSION_CODE
( COMMISS_CODE_ID, COMMISS_CODE, COMMISS_NAME, COMMISS_TYPE, BASIS_TYPE, EXPRESSION_ID, COMMENTS )
 AS SELECT COMMISS_CODE_ID, COMMISS_CODE, COMMISS_NAME, COMMISS_TYPE, BASIS_TYPE, EXPRESSION_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.COMMISSION_CODE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.COMMISSION_TYPE
( COMMISS_TYPE_ID, COMMISS_TYPE, COMMENTS )
 AS SELECT COMMISS_TYPE_ID, COMMISS_TYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.COMMISSION_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.COMPONENT_TYPE
( COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE )
 AS SELECT COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE
FROM WARNER_BASE.SEAWARE.COMPONENT_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.INV_ITEM_GROUP_MATCH
( RECORD_ID, INVOICE_ITEM_TYPE, INV_ITEM_GROUP, COMMENTS, INV_ITEM_GROUP_TYPE, OFFICE_CODE )
 AS SELECT RECORD_ID, INVOICE_ITEM_TYPE, INV_ITEM_GROUP, COMMENTS, INV_ITEM_GROUP_TYPE, OFFICE_CODE
FROM WARNER_BASE.SEAWARE.INV_ITEM_GROUP_MATCH;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.INVOICE_ITEM_GROUP
( INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST )
 AS SELECT INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST
FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_GROUP;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.INVOICE_ITEM_GROUP_TYPE
( INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS )
 AS SELECT INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS
FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_GROUP_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.INVOICE_ITEM_SUBTYPE
( INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS )
 AS SELECT INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_SUBTYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.INVOICE_ITEM_TYPE
( INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC )
 AS SELECT INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC
FROM WARNER_BASE.SEAWARE.INVOICE_ITEM_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.RES_ADDON
( RES_ADDON_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, RES_ADDON_CODE, START_DATE, END_DATE, EFFECTIVE_DATE, AM_ORDER_ID, IS_DEFAULT, PAP_CODE, AMENITY_CODE, DELIVERY_PLACE, QUANTITY, IS_AUTO, COMMENTS, "TIMESTAMP" )
 AS SELECT RES_ADDON_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, RES_ADDON_CODE, START_DATE, END_DATE, EFFECTIVE_DATE, AM_ORDER_ID, IS_DEFAULT, PAP_CODE, AMENITY_CODE, DELIVERY_PLACE, QUANTITY, IS_AUTO, COMMENTS, "TIMESTAMP"
FROM WARNER_BASE.SEAWARE.RES_ADDON;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.RES_INVOICE_CANC
( RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID )
 AS SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID
FROM WARNER_BASE.SEAWARE.RES_INVOICE_CANC;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.RES_INVOICE_ITEM
( RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID )
 AS SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID
FROM WARNER_BASE.SEAWARE.RES_INVOICE_ITEM;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.SHIP_CABIN_RESERVE
( RECORD_ID, SHIP_CODE, CABIN_NUMBER, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, RESERVE_TYPE, COMMENTS, GUEST_COUNT )
 AS SELECT RECORD_ID, SHIP_CODE, CABIN_NUMBER, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, RESERVE_TYPE, COMMENTS, GUEST_COUNT
FROM WARNER_BASE.SEAWARE.SHIP_CABIN_RESERVE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.SHIP_CABIN_RESERVE_TYPE
( RECORD_ID, RESERVE_TYPE, DECREMENTS_INVENTORY, ALLOWS_BOOKING, IS_RESTRICTED, IS_SAIL_RESERVE )
 AS SELECT RECORD_ID, RESERVE_TYPE, DECREMENTS_INVENTORY, ALLOWS_BOOKING, IS_RESTRICTED, IS_SAIL_RESERVE
FROM WARNER_BASE.SEAWARE.SHIP_CABIN_RESERVE_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.SP_REQ_CODE
( SP_REQ_CODE, REQ_CODE_ID, SP_REQ_TYPE, PROVIDER_CODE, SP_REQ_NAME, COMMENTS, WDW_CODED_REMARK )
 AS SELECT SP_REQ_CODE, REQ_CODE_ID, SP_REQ_TYPE, PROVIDER_CODE, SP_REQ_NAME, COMMENTS, WDW_CODED_REMARK
FROM WARNER_BASE.SEAWARE.SP_REQ_CODE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.SP_REQ_ORD_ITEM
( SP_ORD_ITEM_ID, SP_REQ_ID, SP_REQ_CODE, AM_PLACE_CODE, DELIVERY_DATE, DELIVERY_TIME, QUANTITY, COMMENTS, GUEST_FULL_NAME, GUEST_ID, ITEM_VALID )
 AS SELECT SP_ORD_ITEM_ID, SP_REQ_ID, SP_REQ_CODE, AM_PLACE_CODE, DELIVERY_DATE, DELIVERY_TIME, QUANTITY, COMMENTS, GUEST_FULL_NAME, GUEST_ID, ITEM_VALID
FROM WARNER_BASE.SEAWARE.SP_REQ_ORD_ITEM;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.SP_REQ_ORDER
( SP_REQ_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, ORDER_VALID, AM_BOOKING_TYPE, GROUP_ID, RES_ID, AM_REQ_TYPE, AGENCY_ID, CLIENT_ID, AM_PLACE_CODE, AGENT_ID, DELIVERY_TIME, DISPATCHED_DATE, DISPATCHED_OK, COMMENTS, TERMINATION_COMPLETED )
 AS SELECT SP_REQ_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, ORDER_VALID, AM_BOOKING_TYPE, GROUP_ID, RES_ID, AM_REQ_TYPE, AGENCY_ID, CLIENT_ID, AM_PLACE_CODE, AGENT_ID, DELIVERY_TIME, DISPATCHED_DATE, DISPATCHED_OK, COMMENTS, TERMINATION_COMPLETED
FROM WARNER_BASE.SEAWARE.SP_REQ_ORDER;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.SP_REQ_TYPE
( SP_REQ_TYPE_ID, SP_REQ_TYPE, COMMENTS )
 AS SELECT SP_REQ_TYPE_ID, SP_REQ_TYPE, COMMENTS
FROM WARNER_BASE.SEAWARE.SP_REQ_TYPE;

CREATE OR REPLACE SECURE VIEW WARNER_STORE.APS_SHARE.SP_REQ_USAGE_AREA
( RECORD_ID, USAGE_AREA, COMMENTS )
 AS SELECT RECORD_ID, USAGE_AREA, COMMENTS
FROM WARNER_BASE.SEAWARE.SP_REQ_USAGE_AREA;


USE ROLE securityadmin;

GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AGENCY_COMMISSION TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AGENCY_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AM_DELVR_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AM_ORDER_HEADER TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AM_INV_ITEM_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AM_ORDER_STATUS TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AM_PLACE_COMPTYPE_LINK TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AM_REQSTER_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.AM_SRVCE_PROVIDER TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.BLL_INV_AVAILABILITY TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.COMMISSION_CODE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.COMMISSION_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.COMPONENT_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.INV_ITEM_GROUP_MATCH TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.INVOICE_ITEM_GROUP TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.INVOICE_ITEM_GROUP_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.INVOICE_ITEM_SUBTYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.INVOICE_ITEM_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.RES_ADDON TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.RES_INVOICE_CANC TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.RES_INVOICE_ITEM TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.SHIP_CABIN_RESERVE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.SHIP_CABIN_RESERVE_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.SP_REQ_CODE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.SP_REQ_ORD_ITEM TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.SP_REQ_ORDER TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.SP_REQ_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.APS_SHARE.SP_REQ_USAGE_AREA TO DATABASE ROLE WARNER_STORE.APS_SHARE;



