use ROLE dba;

use SCHEMA haven_base.dig_ownership_lettings;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.ACCOUNT
( ACCOUNTID, ACCOUNTNUMBER, NAME, EMAIL, PITCHAREANAME, PITCHNUMBER, PARKCODE, PARKNAME, PARKFULLNAME, VANID, OWNERID, CREATEDAT, UPDATEDAT, DELETEDAT, PITCHSTATUS, VANYEAR, ISRENEWING, READYFORRENEWAL, RENEWALEMAILGUID, ACCOUNTTYPE, ACCOUNTTYPEID )
AS SELECT ACCOUNTID, ACCOUNTNUMBER, NAME, EMAIL, PITCHAREANAME, PITCHNUMBER, PARKCODE, PARKNAME, PARKFULLNAME, VANID, OWNERID, CREATEDAT, UPDATEDAT, DELETEDAT, PITCHSTATUS, VANYEAR, ISRENEWING, READYFORRENEWAL, RENEWALEMAILGUID, ACCOUNTTYPE, ACCOUNTTYPEID
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS."ACCOUNT";

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.ACCOUNTCALCULATORLETTINGBREAKS
( ACCOUNTID, STARTDATE, STATUS )
AS SELECT ACCOUNTID, STARTDATE, STATUS
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.ACCOUNTCALCULATORLETTINGBREAKS;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.APPLICATION
( ID, ACCOUNTNUMBER, ISPETFRIENDLY, ISPRIVATELYLET, ISTERMSANDCONDITIONSACCEPTED, HASSAFETYTEST, HASREPAIRCOVERPLAN, ISACCEPTEDTOLET, STATUS, TYPE, CREATEDAT, UPDATEDAT, DELETEDAT, EMAIL, LASTCONTACTEDDATE, ISRENEWTACACCEPTED, RENEWEDAT, USERINTERACTION, HASMATTRESSPROTECTOR, DRAFTEMAILSENT, REPAIRPLANSENTTOPLOT, DRAFTEMAILUNIQUEID, SUBMITTEDEMAILUNIQUEID, REPAIRPLANALREADYINPLOT, ACCOUNTID )
AS SELECT ID, ACCOUNTNUMBER, ISPETFRIENDLY, ISPRIVATELYLET, ISTERMSANDCONDITIONSACCEPTED, HASSAFETYTEST, HASREPAIRCOVERPLAN, ISACCEPTEDTOLET, STATUS, "TYPE", CREATEDAT, UPDATEDAT, DELETEDAT, EMAIL, LASTCONTACTEDDATE, ISRENEWTACACCEPTED, RENEWEDAT, USERINTERACTION, HASMATTRESSPROTECTOR, DRAFTEMAILSENT, REPAIRPLANSENTTOPLOT, DRAFTEMAILUNIQUEID, SUBMITTEDEMAILUNIQUEID, REPAIRPLANALREADYINPLOT, ACCOUNTID
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.APPLICATION;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.APPLICATIONREVISION
( REVISIONID, APPLICATIONID, ACCOUNTNUMBER, ISPETFRIENDLY, ISPRIVATELYLET, ISTERMSANDCONDITIONSACCEPTED, HASSAFETYTEST, HASREPAIRCOVERPLAN, ISACCEPTEDTOLET, STATUS, TYPE, CREATEDAT, UPDATEDAT, DELETEDAT, EMAIL, LASTCONTACTEDDATE, ISRENEWTACACCEPTED, RENEWEDAT, HASMATTRESSPROTECTOR, DRAFTEMAILSENT, USERINTERACTION, REPAIRPLANSENTTOPLOT, DRAFTEMAILUNIQUEID, SUBMITTEDEMAILUNIQUEID, REPAIRPLANALREADYINPLOT )
AS SELECT REVISIONID, APPLICATIONID, ACCOUNTNUMBER, ISPETFRIENDLY, ISPRIVATELYLET, ISTERMSANDCONDITIONSACCEPTED, HASSAFETYTEST, HASREPAIRCOVERPLAN, ISACCEPTEDTOLET, STATUS, "TYPE", CREATEDAT, UPDATEDAT, DELETEDAT, EMAIL, LASTCONTACTEDDATE, ISRENEWTACACCEPTED, RENEWEDAT, HASMATTRESSPROTECTOR, DRAFTEMAILSENT, USERINTERACTION, REPAIRPLANSENTTOPLOT, DRAFTEMAILUNIQUEID, SUBMITTEDEMAILUNIQUEID, REPAIRPLANALREADYINPLOT
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.APPLICATIONREVISION;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.BEFOREFIRSTLETNOTIFICATION
( ACCOUNTID, YEAR, EARLIESTLETTINGBREAKSTARTDATE, NOTIFIEDAT, CREATEDAT, UPDATEDAT, DELETEDAT, EMAILGUID, DURATION )
AS SELECT ACCOUNTID, "YEAR", EARLIESTLETTINGBREAKSTARTDATE, NOTIFIEDAT, CREATEDAT, UPDATEDAT, DELETEDAT, EMAILGUID, DURATION
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.BEFOREFIRSTLETNOTIFICATION;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.LETTINGCONFIG
( NAME, VALUE, CREATEDAT, UPDATEDAT, DELETEDAT )
AS SELECT NAME, "value", CREATEDAT, UPDATEDAT, DELETEDAT
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.LETTINGCONFIG;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.PARK
( PARKCODE, PARKNAME, PARKREGION, CREATEDAT, UPDATEDAT )
AS SELECT PARKCODE, PARKNAME, PARKREGION, CREATEDAT, UPDATEDAT
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.PARK;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.PARKCONTACTPERSON
( PARKCODE, PARKNAME, NAME, EMAIL, CREATEDAT, UPDATEDAT, PHONENUMBER )
AS SELECT PARKCODE, PARKNAME, NAME, EMAIL, CREATEDAT, UPDATEDAT, PHONENUMBER
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.PARKCONTACTPERSON;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.RENEWALOPTOUT
( ACCOUNTID, ACCOUNTNUMBER, OPTOUTDATE, OPTOUTREASON, CREATEDAT, UPDATEDAT )
AS SELECT ACCOUNTID, ACCOUNTNUMBER, OPTOUTDATE, OPTOUTREASON, CREATEDAT, UPDATEDAT
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.RENEWALOPTOUT;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.REPAIRPLANCONFIRMATIONNOTIFICATION
( ACCOUNTID, YEAR, NOTIFIEDAT, EMAILGUID, CREATEDAT, UPDATEDAT, DELETEDAT )
AS SELECT ACCOUNTID, "YEAR", NOTIFIEDAT, EMAILGUID, CREATEDAT, UPDATEDAT, DELETEDAT
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.REPAIRPLANCONFIRMATIONNOTIFICATION;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.UPTOSTANDARDNOTIFICATION
( ACCOUNTID, SALUTATION, NOTIFIEDAT, EMAILADDRESS, TELEPHONEMOBILE, TELEPHONEMOBILEDAY, TELEPHONEMOBILEEVE, PARKCODE, PARKSHORTDESC, AREA, ZONE, PITCHNUMBER, PARKLETTINGMANAGERNAME, PARKLETTINGMANAGEREMAIL, CREATEDAT, UPDATEDAT, DELETEDAT )
AS SELECT ACCOUNTID, SALUTATION, NOTIFIEDAT, EMAILADDRESS, TELEPHONEMOBILE, TELEPHONEMOBILEDAY, TELEPHONEMOBILEEVE, PARKCODE, PARKSHORTDESC, AREA, "ZONE", PITCHNUMBER, PARKLETTINGMANAGERNAME, PARKLETTINGMANAGEREMAIL, CREATEDAT, UPDATEDAT, DELETEDAT
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.UPTOSTANDARDNOTIFICATION;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.VAN
( ID, ACCOUNTID, MAKE, MODEL, YEARMADE, LETTINGGRADEDESC, LETTINGGRADEID, ISCYHH, CURRENTPITCHNO, CURRENTPITCHAREANAME, CURRENTPITCHAREACODE, CURRENTPITCHZONENAME, CURRENTPITCHZONECODE, CURRENTPITCHID, DESTINATIONPITCHNO, DESTINATIONPITCHAREANAME, DESTINATIONPITCHAREACODE, DESTINATIONPITCHZONENAME, DESTINATIONPITCHZONECODE, DESTINATIONPITCHID, HANDOVERDATE, ISACTUALHANDOVERACTUAL )
AS SELECT ID, ACCOUNTID, MAKE, MODEL, YEARMADE, LETTINGGRADEDESC, LETTINGGRADEID, ISCYHH, CURRENTPITCHNO, CURRENTPITCHAREANAME, CURRENTPITCHAREACODE, CURRENTPITCHZONENAME, CURRENTPITCHZONECODE, CURRENTPITCHID, DESTINATIONPITCHNO, DESTINATIONPITCHAREANAME, DESTINATIONPITCHAREACODE, DESTINATIONPITCHZONENAME, DESTINATIONPITCHZONECODE, DESTINATIONPITCHID, HANDOVERDATE, ISACTUALHANDOVERACTUAL
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.VAN;

CREATE VIEW HAVEN_BASE.DIG_OWNERSHIP_LETTINGS.VANLETTINGSUMMARY
( ACCOUNTID, YEAR, ACCOUNTNUMBER, LETTINGGRADE, TOTALBREAKSINCOME, CREATEDAT, UPDATEDAT, ENDOFSEASONPROJECTEDINCOME, FROZENSUBLETINCOME, INCOMETRANSFERRED, PURCHASEDEBT, NAME, PITCHAREANAME, PITCHNUMBER, FIXEDORFLEXI, PETFRIENDLY, TYPEOFLETTING, ACCEPTEDFORLETTING, CANHAVEREPAIRPLAN, REPAIRPLANSTATUS )
AS SELECT ACCOUNTID, "YEAR", ACCOUNTNUMBER, LETTINGGRADE, TOTALBREAKSINCOME, CREATEDAT, UPDATEDAT, ENDOFSEASONPROJECTEDINCOME, FROZENSUBLETINCOME, INCOMETRANSFERRED, PURCHASEDEBT, NAME, PITCHAREANAME, PITCHNUMBER, FIXEDORFLEXI, PETFRIENDLY, TYPEOFLETTING, ACCEPTEDFORLETTING, CANHAVEREPAIRPLAN, REPAIRPLANSTATUS
FROM HAVEN_RAW.DIG_OWNERSHIP_LETTINGS.VANLETTINGSUMMARY;
