-- 22/07/2025

use role haven_etleap_dataload;

use warehouse haven_cdc_migration_wh;

use SCHEMA haven_raw.playsafe;

alter table crown_machine_collections_history rename to crown_machine_collections_history_pre_machineRef;

drop table crown_machine_collections_history;

create table crown_machine_collections_history like crown_machine_collections;

desc table crown_machine_collections_history;

copy into crown_machine_collections_history 
from @%crown_machine_collections_history
file_format = palysafe_data_load_file_format
validation_mode = return_errors;

copy into crown_machine_collections_history 
from @%crown_machine_collections_history
file_format = palysafe_data_load_file_format
;

ls @%crown_machine_collections_history;

select * from crown_machine_collections_history limit 50;

-- 25/07/2025

use role haven_etleap_dataload;

use warehouse haven_cdc_migration_wh;

use SCHEMA haven_raw.playsafe;

show tables;

truncate table crown_machine_collections_history;
drop table crown_machine_inventory_list_history;

drop table namco_machine_collections_history;
drop table namco_machine_inventory_list_history;

CREATE TABLE crown_machine_inventory_list_history LIKE crown_machine_inventory_list;

create table namco_machine_collections_history LIKE namco_machine_collections;
create table namco_machine_inventory_list_history LIKE namco_machine_inventory_list;

copy into crown_machine_collections_history 
from @%crown_machine_collections_history
file_format = palysafe_data_load_file_format
;

copy into crown_machine_inventory_list_history 
from @%crown_machine_inventory_list_history
file_format = palysafe_data_load_file_format
;

copy into namco_machine_collections_history 
from @%namco_machine_collections_history
file_format = palysafe_data_load_file_format
;

copy into namco_machine_inventory_list_history 
from @%namco_machine_inventory_list_history
file_format = palysafe_data_load_file_format
;

USE ROLE DBA;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, TYPE, NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_COLLECTIONS;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_COLLECTIONS_HISTORY
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, TYPE, NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_COLLECTIONS_HISTORY;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST_HISTORY
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST_HISTORY;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.NAMCO_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_COLLECTIONS;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.NAMCO_MACHINE_COLLECTIONS_HISTORY
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_COLLECTIONS_HISTORY;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST_HISTORY
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST_HISTORY;