USE ROLE dba;

CREATE VIEW HAVEN_BASE.PLAYSAFE.MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, MACHINES, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, MACHINES, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.MACHINE_COLLECTIONS;

CREATE VIEW HAVEN_BASE.PLAYSAFE.MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.MACHINE_INVENTORY_LIST;


-- 20/06/2025

use ROLE dba;

use SCHEMA haven_base.playsafe;

show views;

DROP VIEW NAMCO_MACHINE_COLLECTIONS_20250316_20250419;
DROP VIEW NAMCO_MACHINE_COLLECTIONS_20250330_20250426;

show views;

CREATE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST;

CREATE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST_HISTORY
( SITECODE, SITENAME, REGION, INDEX, MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST_HISTORY;

CREATE VIEW HAVEN_BASE.PLAYSAFE.PLAYNATION_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINE_COLLECTIONID, MACHINE_COLLECTIONDATETIME, MACHINE_PREVIOUSCOLLECTIONDATETIME, MACHINE_COLLECTIONDAYS, MACHINE_COLLECTIONTYPE, MACHINE_CLASS, MACHINE_TYPE, MACHINE_NAME, MACHINE_MANUFACTURER, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_GROSSCASH, MACHINE_REFILLS, MACHINE_HANDPAYS, MACHINE_ENGINEERSCREDITS, MACHINE_PROMOCASH, MACHINE_CASHLESSCARDIN, MACHINE_DEBITCARDIN, MACHINE_TICKETSIN, MACHINE_TICKETSOUT, MACHINE_NETCASH, MACHINE_RTP, MACHINE_VTP, MACHINE_WINS, MACHINE_CASHDIFFERANCE, MACHINE_NETEARNINGS, MACHINE_TAXTYPE, MACHINE_TAXRATE, MACHINE_TAXAMOUNT, MACHINE_NETLESSTAX, MACHINE_GROSSCASHBREAKDOWN_NOTES50, MACHINE_GROSSCASHBREAKDOWN_NOTES20, MACHINE_GROSSCASHBREAKDOWN_NOTES10, MACHINE_GROSSCASHBREAKDOWN_NOTES5, MACHINE_GROSSCASHBREAKDOWN_COINS200, MACHINE_GROSSCASHBREAKDOWN_COINS100, MACHINE_GROSSCASHBREAKDOWN_COINS50, MACHINE_GROSSCASHBREAKDOWN_COINS20, MACHINE_GROSSCASHBREAKDOWN_COINS10, MACHINE_GROSSCASHBREAKDOWN_COINS5, MACHINE_GROSSCASHBREAKDOWN_COINS2, MACHINE_GROSSCASHBREAKDOWN_COINS1, MACHINE_METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINE_COLLECTIONID, MACHINE_COLLECTIONDATETIME, MACHINE_PREVIOUSCOLLECTIONDATETIME, MACHINE_COLLECTIONDAYS, MACHINE_COLLECTIONTYPE, MACHINE_CLASS, MACHINE_TYPE, MACHINE_NAME, MACHINE_MANUFACTURER, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_GROSSCASH, MACHINE_REFILLS, MACHINE_HANDPAYS, MACHINE_ENGINEERSCREDITS, MACHINE_PROMOCASH, MACHINE_CASHLESSCARDIN, MACHINE_DEBITCARDIN, MACHINE_TICKETSIN, MACHINE_TICKETSOUT, MACHINE_NETCASH, MACHINE_RTP, MACHINE_VTP, MACHINE_WINS, MACHINE_CASHDIFFERANCE, MACHINE_NETEARNINGS, MACHINE_TAXTYPE, MACHINE_TAXRATE, MACHINE_TAXAMOUNT, MACHINE_NETLESSTAX, MACHINE_GROSSCASHBREAKDOWN_NOTES50, MACHINE_GROSSCASHBREAKDOWN_NOTES20, MACHINE_GROSSCASHBREAKDOWN_NOTES10, MACHINE_GROSSCASHBREAKDOWN_NOTES5, MACHINE_GROSSCASHBREAKDOWN_COINS200, MACHINE_GROSSCASHBREAKDOWN_COINS100, MACHINE_GROSSCASHBREAKDOWN_COINS50, MACHINE_GROSSCASHBREAKDOWN_COINS20, MACHINE_GROSSCASHBREAKDOWN_COINS10, MACHINE_GROSSCASHBREAKDOWN_COINS5, MACHINE_GROSSCASHBREAKDOWN_COINS2, MACHINE_GROSSCASHBREAKDOWN_COINS1, MACHINE_METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.PLAYNATION_MACHINE_COLLECTIONS;

CREATE VIEW HAVEN_BASE.PLAYSAFE.PLAYNATION_MACHINE_COLLECTIONS_HISTORY
( SITECODE, SITENAME, REGION, INDEX, MACHINE_COLLECTIONID, MACHINE_COLLECTIONDATETIME, MACHINE_PREVIOUSCOLLECTIONDATETIME, MACHINE_COLLECTIONDAYS, MACHINE_COLLECTIONTYPE, MACHINE_CLASS, MACHINE_TYPE, MACHINE_NAME, MACHINE_MANUFACTURER, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_GROSSCASH, MACHINE_REFILLS, MACHINE_HANDPAYS, MACHINE_ENGINEERSCREDITS, MACHINE_PROMOCASH, MACHINE_CASHLESSCARDIN, MACHINE_DEBITCARDIN, MACHINE_TICKETSIN, MACHINE_TICKETSOUT, MACHINE_NETCASH, MACHINE_RTP, MACHINE_VTP, MACHINE_WINS, MACHINE_CASHDIFFERANCE, MACHINE_NETEARNINGS, MACHINE_TAXTYPE, MACHINE_TAXRATE, MACHINE_TAXAMOUNT, MACHINE_NETLESSTAX, MACHINE_GROSSCASHBREAKDOWN_NOTES50, MACHINE_GROSSCASHBREAKDOWN_NOTES20, MACHINE_GROSSCASHBREAKDOWN_NOTES10, MACHINE_GROSSCASHBREAKDOWN_NOTES5, MACHINE_GROSSCASHBREAKDOWN_COINS200, MACHINE_GROSSCASHBREAKDOWN_COINS100, MACHINE_GROSSCASHBREAKDOWN_COINS50, MACHINE_GROSSCASHBREAKDOWN_COINS20, MACHINE_GROSSCASHBREAKDOWN_COINS10, MACHINE_GROSSCASHBREAKDOWN_COINS5, MACHINE_GROSSCASHBREAKDOWN_COINS2, MACHINE_GROSSCASHBREAKDOWN_COINS1, MACHINE_METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINE_COLLECTIONID, MACHINE_COLLECTIONDATETIME, MACHINE_PREVIOUSCOLLECTIONDATETIME, MACHINE_COLLECTIONDAYS, MACHINE_COLLECTIONTYPE, MACHINE_CLASS, MACHINE_TYPE, MACHINE_NAME, MACHINE_MANUFACTURER, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_GROSSCASH, MACHINE_REFILLS, MACHINE_HANDPAYS, MACHINE_ENGINEERSCREDITS, MACHINE_PROMOCASH, MACHINE_CASHLESSCARDIN, MACHINE_DEBITCARDIN, MACHINE_TICKETSIN, MACHINE_TICKETSOUT, MACHINE_NETCASH, MACHINE_RTP, MACHINE_VTP, MACHINE_WINS, MACHINE_CASHDIFFERANCE, MACHINE_NETEARNINGS, MACHINE_TAXTYPE, MACHINE_TAXRATE, MACHINE_TAXAMOUNT, MACHINE_NETLESSTAX, MACHINE_GROSSCASHBREAKDOWN_NOTES50, MACHINE_GROSSCASHBREAKDOWN_NOTES20, MACHINE_GROSSCASHBREAKDOWN_NOTES10, MACHINE_GROSSCASHBREAKDOWN_NOTES5, MACHINE_GROSSCASHBREAKDOWN_COINS200, MACHINE_GROSSCASHBREAKDOWN_COINS100, MACHINE_GROSSCASHBREAKDOWN_COINS50, MACHINE_GROSSCASHBREAKDOWN_COINS20, MACHINE_GROSSCASHBREAKDOWN_COINS10, MACHINE_GROSSCASHBREAKDOWN_COINS5, MACHINE_GROSSCASHBREAKDOWN_COINS2, MACHINE_GROSSCASHBREAKDOWN_COINS1, MACHINE_METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.PLAYNATION_MACHINE_COLLECTIONS_HISTORY;

CREATE VIEW HAVEN_BASE.PLAYSAFE.PLAYNATION_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.PLAYNATION_MACHINE_INVENTORY_LIST;

CREATE VIEW HAVEN_BASE.PLAYSAFE.PLAYNATION_MACHINE_INVENTORY_LIST_HISTORY
( SITECODE, SITENAME, REGION, INDEX, MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINE_MACHINEREF, MACHINE_MACHINENAME, MACHINE_CLASS, MACHINE_TYPE, MACHINE_POP, MACHINE_JACKPOT, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_SERIALNUMBER, MACHINE_INSTALLATIONDATE, MACHINE_REMOVALDATE, MACHINE_COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.PLAYNATION_MACHINE_INVENTORY_LIST_HISTORY;

SHOW VIEWS;

SELECT * FROM PLAYNATION_MACHINE_INVENTORY_LIST LIMIT 5;

SELECT * FROM PLAYNATION_MACHINE_INVENTORY_LIST_HISTORY LIMIT 5;


-- 05/09/2025

use ROLE dba;

use SCHEMA haven_base.playsafe;

SHOW views;

DROP VIEW CROWN_MACHINE_COLLECTIONS;
DROP VIEW CROWN_MACHINE_COLLECTIONS_HISTORY;
DROP VIEW CROWN_MACHINE_INVENTORY_LIST;
DROP VIEW CROWN_MACHINE_INVENTORY_LIST_HISTORY;
DROP VIEW NAMCO_MACHINE_COLLECTIONS;
DROP VIEW NAMCO_MACHINE_COLLECTIONS_HISTORY;
DROP VIEW NAMCO_MACHINE_INVENTORY_LIST;
DROP VIEW NAMCO_MACHINE_INVENTORY_LIST_HISTORY;
DROP VIEW PLAYNATION_MACHINE_COLLECTIONS;
DROP VIEW PLAYNATION_MACHINE_COLLECTIONS_HISTORY;
DROP VIEW PLAYNATION_MACHINE_INVENTORY_LIST;
DROP VIEW PLAYNATION_MACHINE_INVENTORY_LIST_HISTORY;

SHOW views;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, TYPE, GENERATESINCOME, NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_COLLECTIONS;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, GENERATESINCOME, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.NAMCO_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, TYPE, GENERATESINCOME, NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_COLLECTIONS;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, GENERATESINCOME, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.PLAYNATION_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, TYPE, GENERATESINCOME, NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.PLAYNATION_MACHINE_COLLECTIONS;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.PLAYNATION_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, GENERATESINCOME, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE, _ETLEAP_LOOKBACK_DATE
FROM HAVEN_RAW.PLAYSAFE.PLAYNATION_MACHINE_INVENTORY_LIST;

SHOW VIEWS;

SELECT * FROM CROWN_MACHINE_COLLECTIONS LIMIT 10;
SELECT * FROM CROWN_MACHINE_INVENTORY_LIST LIMIT 10;
SELECT * FROM NAMCO_MACHINE_COLLECTIONS LIMIT 10;
SELECT * FROM NAMCO_MACHINE_INVENTORY_LIST LIMIT 10;
SELECT * FROM PLAYNATION_MACHINE_COLLECTIONS LIMIT 10;
SELECT * FROM PLAYNATION_MACHINE_INVENTORY_LIST LIMIT 10;

SELECT * FROM haven_raw.playsafe.CROWN_MACHINE_COLLECTIONS_pre_merge LIMIT 10;

-- 21/10/2025

use ROLE dba;

use SCHEMA HAVEN_BASE.PLAYSAFE;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, TYPE, GENERATESINCOME, NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_COLLECTIONS
GROUP BY SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
;


CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, GENERATESINCOME, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE
FROM HAVEN_RAW.PLAYSAFE.CROWN_MACHINE_INVENTORY_LIST
GROUP BY SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE
;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.NAMCO_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, TYPE, GENERATESINCOME, NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_COLLECTIONS
GROUP BY SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, GENERATESINCOME, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE
FROM HAVEN_RAW.PLAYSAFE.NAMCO_MACHINE_INVENTORY_LIST
GROUP BY SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE
;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.PLAYNATION_MACHINE_COLLECTIONS
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, TYPE, GENERATESINCOME, NAME, MANUFACTURER, LOCATION, ZONE, GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
FROM HAVEN_RAW.PLAYSAFE.PLAYNATION_MACHINE_COLLECTIONS
GROUP BY SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, COLLECTIONID, COLLECTIONDATETIME, PREVIOUSCOLLECTIONDATETIME, COLLECTIONDAYS, COLLECTIONTYPE, CLASS, "TYPE", GENERATESINCOME, NAME, MANUFACTURER, LOCATION, "ZONE", GROSSCASH, REFILLS, HANDPAYS, ENGINEERSCREDITS, PROMOCASH, CASHLESSCARDIN, DEBITCARDIN, TICKETSIN, TICKETSOUT, NETCASH, RTP, VTP, WINS, CASHDIFFERENCE, NETEARNINGS, TAXTYPE, TAXRATE, TAXAMOUNT, NETLESSTAX, GROSSCASHBREAKDOWN_NOTES50, GROSSCASHBREAKDOWN_NOTES20, GROSSCASHBREAKDOWN_NOTES10, GROSSCASHBREAKDOWN_NOTES5, GROSSCASHBREAKDOWN_COINS200, GROSSCASHBREAKDOWN_COINS100, GROSSCASHBREAKDOWN_COINS50, GROSSCASHBREAKDOWN_COINS20, GROSSCASHBREAKDOWN_COINS10, GROSSCASHBREAKDOWN_COINS5, GROSSCASHBREAKDOWN_COINS2, GROSSCASHBREAKDOWN_COINS1, METERS
;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.PLAYNATION_MACHINE_INVENTORY_LIST
( SITECODE, SITENAME, REGION, INDEX, MACHINEREF, MACHINENAME, CLASS, TYPE, GENERATESINCOME, POP, JACKPOT, LOCATION, ZONE, SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE )
AS SELECT SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE
FROM HAVEN_RAW.PLAYSAFE.PLAYNATION_MACHINE_INVENTORY_LIST
GROUP BY SITECODE, SITENAME, REGION, "INDEX", MACHINEREF, MACHINENAME, CLASS, "TYPE", GENERATESINCOME, POP, JACKPOT, LOCATION, "ZONE", SERIALNUMBER, INSTALLATIONDATE, REMOVALDATE, COLLECTIONDAYSONSITE
;


