create or replace schema PLOT_DREAM;

create or replace view D_ACCTKEYS(
	LEDGER,
	ACCOUNT,
	KEYVALUE,
	KEYNAME
) as SELECT "LEDGER", "ACCOUNT", "KEYVALUE", "KEYNAME" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_ACCTKEYS";
create or replace view D_ALLOCATION(
	COMPANYCODE,
	ALLOCTYPE,
	ALLOCNUM,
	ALLOCREFNO,
	REFNO,
	DOCTYPE,
	DOCNUM,
	VALUE,
	NOMCURRENCY,
	ACCCURRENCY,
	DOCCURRENCY,
	ALTHOMEVAL,
	L3CURRENCY,
	DESCRIPTION,
	NARRATIVE,
	USERVALUE,
	PAYLIST,
	DISCOUNT,
	HIGHDATE,
	HIGHYEAR,
	HIGHPERIOD,
	INPUTDATE,
	INPUTTIME,
	ALLOCSTATUS
) as SELECT "COMPANYCODE", "ALLOCTYPE", "ALLOCNUM", "ALLOCREFNO", "REFNO", "DOCTYPE", "DOCNUM", "VALUE", "NOMCURRENCY", "ACCCURRENCY", "DOCCURRENCY", "ALTHOMEVAL", "L3CURRENCY", "DESCRIPTION", "NARRATIVE", "USERVALUE", "PAYLIST", "DISCOUNT", "HIGHDATE", "HIGHYEAR", "HIGHPERIOD", "INPUTDATE", "INPUTTIME", "ALLOCSTATUS" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_ALLOCATION";
create or replace view D_AUDIT(
	UKEY,
	GROUPNUMBER,
	TABLEID,
	COLUMNID,
	KEYFIELD,
	TYPENUMBER,
	USERNID,
	FUNCTIONID,
	AUDITTIME,
	PREVIOUSDATA,
	CURRENTDATA
) as SELECT "UKEY", "GROUPNUMBER", "TABLEID", "COLUMNID", "KEYFIELD", "TYPENUMBER", "USERNID", "FUNCTIONID", "AUDITTIME", "PREVIOUSDATA", "CURRENTDATA" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_AUDIT";
create or replace view D_AUDITCONFIG(
	FUNCTIONID,
	TYPENUMBER
) as SELECT "FUNCTIONID", "TYPENUMBER" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_AUDITCONFIG";
create or replace view D_COMPANY(
	COMPANYCODE,
	SQSUSERGROUP
) as SELECT "COMPANYCODE", "SQSUSERGROUP" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_COMPANY";
create or replace view D_DETAILS(
	NOMINAL,
	ACCOUNT,
	XLEDGER,
	XACCOUNT,
	DOCDATE,
	YEARCODE,
	PERIOD,
	VALUE,
	NOMCURRENCY,
	ACCCURRENCY,
	DOCCURRENCY,
	USERVALUE,
	DESCRIPTION,
	DOCTYPE,
	DOCNUM,
	DETAILSTATUS,
	REFNO,
	PAYLIST,
	ALLOCATION,
	DUEDATE,
	DISCOUNT,
	HIGHDATE,
	HIGHYEAR,
	HIGHPERIOD,
	LEDGER,
	INPUTDATE,
	INPUTTIME,
	USERFIELD1,
	USERFIELD2,
	USERFIELD3,
	COMPANYCODE,
	ALTHOMEVAL,
	L3LEDGER,
	L3ACCOUNT,
	L3CURRENCY,
	ROWNO,
	UNALLOCATED,
	RECTYPE,
	USERVALUEFIELD1,
	USERVALUEFIELD2,
	USERVALUEFIELD3,
	USERVALUEFIELD4,
	TRANTYPE,
	ROWNAME,
	PERIODDATE
) as SELECT "NOMINAL", "ACCOUNT", "XLEDGER", "XACCOUNT", "DOCDATE", "YEARCODE", "PERIOD", "VALUE", "NOMCURRENCY", "ACCCURRENCY", "DOCCURRENCY", "USERVALUE", "DESCRIPTION", "DOCTYPE", "DOCNUM", "DETAILSTATUS", "REFNO", "PAYLIST", "ALLOCATION", "DUEDATE", "DISCOUNT", "HIGHDATE", "HIGHYEAR", "HIGHPERIOD", "LEDGER", "INPUTDATE", "INPUTTIME", "USERFIELD1", "USERFIELD2", "USERFIELD3", "COMPANYCODE", "ALTHOMEVAL", "L3LEDGER", "L3ACCOUNT", "L3CURRENCY", "ROWNO", "UNALLOCATED", "RECTYPE", "USERVALUEFIELD1", "USERVALUEFIELD2", "USERVALUEFIELD3", "USERVALUEFIELD4", "TRANTYPE", "ROWNAME", "PERIODDATE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_DETAILS";
create or replace view D_DOCTYPE(
	DOCTYPE,
	FORMNAME,
	TYPE,
	PERIOD,
	FROMPERIOD,
	DEFAULTFORM
) as SELECT "DOCTYPE", "FORMNAME", "TYPE", "PERIOD", "FROMPERIOD", "DEFAULTFORM" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_DOCTYPE";
create or replace view D_DOCTYPEMAP(
	DOCTYPE,
	DISPLAYNAME,
	POSTING
) as SELECT "DOCTYPE", "DISPLAYNAME", "POSTING" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_DOCTYPEMAP";
create or replace view D_DOCTYPERANGE(
	DOCTYPE,
	RANGETYPE,
	DETAILSTATUS,
	CURRENCY,
	SQSACCESS,
	FIRSTNUMBER,
	NEXTNUMBER,
	LASTNUMBER,
	COMPANYCODE
) as SELECT "DOCTYPE", "RANGETYPE", "DETAILSTATUS", "CURRENCY", "SQSACCESS", "FIRSTNUMBER", "NEXTNUMBER", "LASTNUMBER", "COMPANYCODE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_DOCTYPERANGE";
create or replace view D_KEYVALUES(
	KEYNAME,
	KEYVALUE,
	TITLE
) as SELECT "KEYNAME", "KEYVALUE", "TITLE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_KEYVALUES";
create or replace view D_MAGICNUMBERS(
	MNTYPE,
	MNUMBER,
	MNCODE,
	TITLE
) as SELECT "MNTYPE", "MNUMBER", "MNCODE", "TITLE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_MAGICNUMBERS";
create or replace view D_NAMEBANKINFO(
	LEDGER,
	ACCOUNT,
	BANKNAME,
	SORTCODE,
	BANKTYPE,
	ACCOUNTTYPE,
	ACCOUNTNUMBER,
	TITLE,
	USERREF,
	USERNID,
	INPUTTIME,
	CUSTOMFIELD1,
	CUSTOMFIELD2,
	CUSTOMFIELD3,
	CUSTOMFIELD4,
	CUSTOMFIELD5,
	CUSTOMFIELD6,
	CUSTOMFIELD7,
	CUSTOMFIELD8,
	CUSTOMFIELD9,
	CUSTOMFIELD10,
	CUSTOMFIELD11,
	CUSTOMFIELD12,
	BANKFORMAT
) as SELECT "LEDGER", "ACCOUNT", "BANKNAME", "SORTCODE", "BANKTYPE", "ACCOUNTTYPE", "ACCOUNTNUMBER", "TITLE", "USERREF", "USERNID", "INPUTTIME", "CUSTOMFIELD1", "CUSTOMFIELD2", "CUSTOMFIELD3", "CUSTOMFIELD4", "CUSTOMFIELD5", "CUSTOMFIELD6", "CUSTOMFIELD7", "CUSTOMFIELD8", "CUSTOMFIELD9", "CUSTOMFIELD10", "CUSTOMFIELD11", "CUSTOMFIELD12", "BANKFORMAT" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_NAMEBANKINFO";
create or replace view D_NOMKEYS(
	NOMINAL,
	KEYVALUE,
	KEYNAME,
	COMPANYCODE
) as SELECT "NOMINAL", "KEYVALUE", "KEYNAME", "COMPANYCODE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_NOMKEYS";
create or replace view D_TABLEACCESS(
	TABLEID,
	SQSUSERGROUP,
	ACCESSID,
	ACCESSTYPE
) as SELECT "TABLEID", "SQSUSERGROUP", "ACCESSID", "ACCESSTYPE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_TABLEACCESS";
create or replace view D_UDIELEMENT(
	FORMNAME,
	TITLE,
	INTORDER,
	ELEMENTNAME,
	PARENTNAME,
	LEFTPOS,
	TOPPOS,
	WIDTH,
	HEIGHT,
	USERFUNCTION,
	READONLY,
	TABSTOP,
	VISIBLE,
	BCOLUMN,
	REQUIRED,
	TYPE,
	JUSTIFICATION,
	BACKCOLOUR,
	ELEMENTCOLOUR,
	TEXTLIMIT,
	BORDER,
	PROMPT,
	LFELEMHEIGHT,
	LFELEMWEIGHT,
	LFELEMFACENAME,
	LFELEMITALIC,
	LFVARHEIGHT,
	LFVARWEIGHT,
	LFVARFACENAME,
	LFVARITALIC,
	ACCESSID,
	PROPERTYEX,
	LFELEMUNDERLINE,
	LFELEMSTRIKEOUT,
	LFELEMCHARSET
) as SELECT "FORMNAME", "TITLE", "INTORDER", "ELEMENTNAME", "PARENTNAME", "LEFTPOS", "TOPPOS", "WIDTH", "HEIGHT", "USERFUNCTION", "READONLY", "TABSTOP", "VISIBLE", "BCOLUMN", "REQUIRED", "TYPE", "JUSTIFICATION", "BACKCOLOUR", "ELEMENTCOLOUR", "TEXTLIMIT", "BORDER", "PROMPT", "LFELEMHEIGHT", "LFELEMWEIGHT", "LFELEMFACENAME", "LFELEMITALIC", "LFVARHEIGHT", "LFVARWEIGHT", "LFVARFACENAME", "LFVARITALIC", "ACCESSID", "PROPERTYEX", "LFELEMUNDERLINE", "LFELEMSTRIKEOUT", "LFELEMCHARSET" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_UDIELEMENT";
create or replace view D_UDIJNLFMT(
	FORMNAME,
	ROWNAME,
	ROWORDER,
	INTORDER,
	TYPE,
	FORMATTYPE,
	FORMATFIELD,
	ELEMENTNAME
) as SELECT "FORMNAME", "ROWNAME", "ROWORDER", "INTORDER", "TYPE", "FORMATTYPE", "FORMATFIELD", "ELEMENTNAME" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_UDIJNLFMT";
create or replace view D_UGACCESS(
	SQSUSERGROUP,
	LEDGER,
	SQSACCESS
) as SELECT "SQSUSERGROUP", "LEDGER", "SQSACCESS" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_UGACCESS";
create or replace view D_USERGROUP(
	SQSUSERGROUP,
	USERNID
) as SELECT "SQSUSERGROUP", "USERNID" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_USERGROUP";
create or replace view D_USERGROUPMENU(
	SQSUSERGROUP,
	MENUTEXT,
	ITEMID
) as SELECT "SQSUSERGROUP", "MENUTEXT", "ITEMID" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."D_USERGROUPMENU";
create or replace view M_ACCOUNT(
	LEDGER,
	ACCOUNT,
	TITLE,
	TYPE,
	ALLOCATION,
	DETAILSTATUS,
	EXTERNALALLOC,
	CURRENCY,
	SQSACCESS,
	INPUTALLOWED,
	ACCESSID,
	USERNID,
	INPUTTIME,
	SELFBILL,
	DISPATCHORDER,
	SUPPLIERSTATUS,
	ACCOUNTID,
	ADDRESSCODE,
	ANALYSIS1,
	ANALYSIS2,
	ANALYSIS3,
	ANALYSIS4,
	ANALYSIS5,
	ANALYSIS6,
	ANALYSIS7,
	ANALYSIS8,
	ANALYSIS9,
	ANALYSIS10,
	ONEOFFSUPPLIER
) as SELECT "LEDGER", "ACCOUNT", "TITLE", "TYPE", "ALLOCATION", "DETAILSTATUS", "EXTERNALALLOC", "CURRENCY", "SQSACCESS", "INPUTALLOWED", "ACCESSID", "USERNID", "INPUTTIME", "SELFBILL", "DISPATCHORDER", "SUPPLIERSTATUS", "ACCOUNTID", "ADDRESSCODE", "ANALYSIS1", "ANALYSIS2", "ANALYSIS3", "ANALYSIS4", "ANALYSIS5", "ANALYSIS6", "ANALYSIS7", "ANALYSIS8", "ANALYSIS9", "ANALYSIS10", "ONEOFFSUPPLIER" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_ACCOUNT";
create or replace view M_ALLOCATION(
	COMPANYCODE,
	ALLOCTYPE,
	ALLOCNUM,
	NOMINAL,
	ACCOUNT,
	PAYLIST
) as SELECT "COMPANYCODE", "ALLOCTYPE", "ALLOCNUM", "NOMINAL", "ACCOUNT", "PAYLIST" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_ALLOCATION";
create or replace view M_ANALYSIS(
	PARENT,
	FIELDID,
	ANALYSISFIELDNAME,
	COMPULSORY,
	KEYNAME,
	SHADOWINDEX,
	STARTCHAR,
	ENDCHAR
) as SELECT "PARENT", "FIELDID", "ANALYSISFIELDNAME", "COMPULSORY", "KEYNAME", "SHADOWINDEX", "STARTCHAR", "ENDCHAR" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_ANALYSIS";
create or replace view M_BALANCE(
	COMPANYCODE,
	TRANTYPE,
	YEARCODE,
	PERIOD,
	NOMINAL,
	LEDGER,
	ACCOUNT,
	L3LEDGER,
	L3ACCOUNT,
	DETCOUNT,
	USERVALUE,
	BALANCE,
	ALTHOMEBAL,
	NOMCURRENCY,
	ACCCURRENCY,
	L3CURRENCY
) as SELECT "COMPANYCODE", "TRANTYPE", "YEARCODE", "PERIOD", "NOMINAL", "LEDGER", "ACCOUNT", "L3LEDGER", "L3ACCOUNT", "DETCOUNT", "USERVALUE", "BALANCE", "ALTHOMEBAL", "NOMCURRENCY", "ACCCURRENCY", "L3CURRENCY" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_BALANCE";
create or replace view M_COMMENT(
	COMMID,
	OBJECTID,
	SQSIDENTITY,
	INTORDER,
	CREATEDBY,
	CREATEDDATETIME,
	MODIFIEDBY,
	MODIFIEDDATETIME,
	SQSACCESS,
	TITLE,
	COMMTEXT
) as SELECT "COMMID", "OBJECTID", "SQSIDENTITY", "INTORDER", "CREATEDBY", "CREATEDDATETIME", "MODIFIEDBY", "MODIFIEDDATETIME", "SQSACCESS", "TITLE", "COMMTEXT" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_COMMENT";
create or replace view M_COMPANY(
	COMPANYCODE,
	TITLE,
	CURRENCY,
	ALTCURRENCY,
	BUDGETCODE,
	COMMBUDGET,
	ACCRUALNOMINAL,
	ADDCODE,
	DELADDCODE,
	COMPANYID
) as SELECT "COMPANYCODE", "TITLE", "CURRENCY", "ALTCURRENCY", "BUDGETCODE", "COMMBUDGET", "ACCRUALNOMINAL", "ADDCODE", "DELADDCODE", "COMPANYID" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_COMPANY";
create or replace view M_CURRENCY(
	CURRENCY,
	TITLE,
	SQSACCESS,
	SYMBOL,
	NODP,
	BASECURRENCY,
	FIXEDRATE,
	CONVERTMETHOD
) as SELECT "CURRENCY", "TITLE", "SQSACCESS", "SYMBOL", "NODP", "BASECURRENCY", "FIXEDRATE", "CONVERTMETHOD" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_CURRENCY";
create or replace view M_DBACCESS(
	USERNID,
	ACCESSDATE,
	ACCESSORDER,
	RESORDER,
	CONTYPE,
	CLIENT,
	CONNECTDATE,
	ACTIVITY,
	STATUS
) as SELECT "USERNID", "ACCESSDATE", "ACCESSORDER", "RESORDER", "CONTYPE", "CLIENT", "CONNECTDATE", "ACTIVITY", "STATUS" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_DBACCESS";
create or replace view M_DESTINATION(
	DESTINATION,
	DESTALLOW,
	DESTVALIDATE,
	DESTPOST,
	DESTEXPORT,
	DESTBALANCE
) as SELECT "DESTINATION", "DESTALLOW", "DESTVALIDATE", "DESTPOST", "DESTEXPORT", "DESTBALANCE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_DESTINATION";
create or replace view M_DOCTYPE(
	DOCTYPE,
	TITLE,
	RANGETYPE,
	DETAILSTATUS,
	CURRENCY,
	SQSACCESS,
	REVERSAL,
	REVERSALN,
	SHOWTURNOVER,
	DOCCOUNT,
	CALCDISCOUNTS,
	REGISTER,
	INPUTALLOWED,
	ACCESSID,
	CHECKDUPL,
	COMPANYRANGES,
	GENDOCTYPE,
	DOCTYPETYPE,
	DOCTYPEID,
	MULTICOMPANYDOC
) as SELECT "DOCTYPE", "TITLE", "RANGETYPE", "DETAILSTATUS", "CURRENCY", "SQSACCESS", "REVERSAL", "REVERSALN", "SHOWTURNOVER", "DOCCOUNT", "CALCDISCOUNTS", "REGISTER", "INPUTALLOWED", "ACCESSID", "CHECKDUPL", "COMPANYRANGES", "GENDOCTYPE", "DOCTYPETYPE", "DOCTYPEID", "MULTICOMPANYDOC" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_DOCTYPE";
create or replace view M_DOCUMENT(
	DOCTYPE,
	DOCNUM,
	DOCDATE,
	YEARCODE,
	PERIOD,
	INPUTDATE,
	INPUTTIME,
	CURRENCY,
	PREVIOUSDATE,
	PREVIOUSTIME,
	COMPANYCODE,
	USERNID,
	AUTHNID,
	AUTHORISED,
	DOCUMENTID
) as SELECT "DOCTYPE", "DOCNUM", "DOCDATE", "YEARCODE", "PERIOD", "INPUTDATE", "INPUTTIME", "CURRENCY", "PREVIOUSDATE", "PREVIOUSTIME", "COMPANYCODE", "USERNID", "AUTHNID", "AUTHORISED", "DOCUMENTID" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_DOCUMENT";
create or replace view M_KEYS(
	KEYNAME,
	TITLE,
	KEYLEDGER,
	LEDGER,
	KEYFIELD,
	KEYVALUE,
	KEYENTRIES,
	KEYSTATE
) as SELECT "KEYNAME", "TITLE", "KEYLEDGER", "LEDGER", "KEYFIELD", "KEYVALUE", "KEYENTRIES", "KEYSTATE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_KEYS";
create or replace view M_LEDGER(
	LEDGER,
	TITLE,
	TYPE,
	NOMINAL,
	ACCOUNTRANGE,
	FROMACCOUNT,
	TOACCOUNT,
	SQSACCESS,
	VATDEFCTRYCODE,
	ADDRESSFORMAT,
	CHANGEREF,
	DETAILSTATUS,
	EXTERNALALLOC,
	INPUTALLOWED,
	COMPANYCODE,
	CACHEID,
	LEDGERCLASS,
	SHADOWLEDGER,
	KEYLIST,
	LEDGERID
) as SELECT "LEDGER", "TITLE", "TYPE", "NOMINAL", "ACCOUNTRANGE", "FROMACCOUNT", "TOACCOUNT", "SQSACCESS", "VATDEFCTRYCODE", "ADDRESSFORMAT", "CHANGEREF", "DETAILSTATUS", "EXTERNALALLOC", "INPUTALLOWED", "COMPANYCODE", "CACHEID", "LEDGERCLASS", "SHADOWLEDGER", "KEYLIST", "LEDGERID" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_LEDGER";
create or replace view M_NAMEACCOUNT(
	LEDGER,
	ACCOUNT,
	PRENAME,
	ADDRESSNAME,
	ADDRESS1,
	ADDRESS2,
	ADDRESS3,
	POSTTOWN,
	COUNTY,
	POSTCODE1,
	POSTCODE2,
	COUNTRY,
	TELEPHONE,
	FAXNO,
	TAXNUMBER,
	CONTACT,
	SALUTATION,
	RSCOMMENT,
	FACTORLEDGER,
	FACTORACCOUNT,
	CREDITLIMIT,
	TAXCTRYCODE,
	ADDRESSFORMAT,
	TURNOVERLIMIT,
	USERNID,
	INPUTTIME,
	EMAILADDRESS,
	URL,
	TELEPHONE2,
	ADDRESSTYPE,
	ADDRESSCODE,
	DEFAULTADDRESS,
	SQSACCESS
) as SELECT "LEDGER", "ACCOUNT", "PRENAME", "ADDRESSNAME", "ADDRESS1", "ADDRESS2", "ADDRESS3", "POSTTOWN", "COUNTY", "POSTCODE1", "POSTCODE2", "COUNTRY", "TELEPHONE", "FAXNO", "TAXNUMBER", "CONTACT", "SALUTATION", "RSCOMMENT", "FACTORLEDGER", "FACTORACCOUNT", "CREDITLIMIT", "TAXCTRYCODE", "ADDRESSFORMAT", "TURNOVERLIMIT", "USERNID", "INPUTTIME", "EMAILADDRESS", "URL", "TELEPHONE2", "ADDRESSTYPE", "ADDRESSCODE", "DEFAULTADDRESS", "SQSACCESS" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_NAMEACCOUNT";
create or replace view M_NOMINAL(
	NOMINAL,
	TITLE,
	LEDGER,
	TYPE,
	TAXCODE,
	ALLOCATION,
	DETAILSTATUS,
	EXTERNALALLOC,
	SHOWUSERVALUE,
	CURRENCY,
	SQSACCESS,
	INPUTALLOWED,
	COMPANYCODE,
	ACCESSID,
	L3LEDGER,
	ACCOUNTREQ,
	ACCTBALREQ,
	L3ALLOCATION,
	COMMITMENTTYPE,
	FUTUREPERIODS,
	BUDGETUSE,
	USERNID,
	INPUTTIME,
	BUDGETINDEX,
	CHECKINDEXONLY,
	ANALYSIS1,
	ANALYSIS2,
	ANALYSIS3,
	ANALYSIS4,
	ANALYSIS5,
	ANALYSIS6,
	ANALYSIS7,
	ANALYSIS8,
	ANALYSIS9,
	ANALYSIS10,
	NOMINALID
) as SELECT "NOMINAL", "TITLE", "LEDGER", "TYPE", "TAXCODE", "ALLOCATION", "DETAILSTATUS", "EXTERNALALLOC", "SHOWUSERVALUE", "CURRENCY", "SQSACCESS", "INPUTALLOWED", "COMPANYCODE", "ACCESSID", "L3LEDGER", "ACCOUNTREQ", "ACCTBALREQ", "L3ALLOCATION", "COMMITMENTTYPE", "FUTUREPERIODS", "BUDGETUSE", "USERNID", "INPUTTIME", "BUDGETINDEX", "CHECKINDEXONLY", "ANALYSIS1", "ANALYSIS2", "ANALYSIS3", "ANALYSIS4", "ANALYSIS5", "ANALYSIS6", "ANALYSIS7", "ANALYSIS8", "ANALYSIS9", "ANALYSIS10", "NOMINALID" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_NOMINAL";
create or replace view M_PARAMNUMS(
	PARAMKEY,
	PARAMVALUE
) as SELECT "PARAMKEY", "PARAMVALUE" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_PARAMNUMS";
create or replace view M_PARAMSTRINGS(
	PARAMGROUP,
	PARAMSTRING,
	PARAMCHAR,
	PARAMDATE,
	PARAMTIME,
	PARAMINTEGER,
	PARAMDECIMAL
) as SELECT "PARAMGROUP", "PARAMSTRING", "PARAMCHAR", "PARAMDATE", "PARAMTIME", "PARAMINTEGER", "PARAMDECIMAL" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_PARAMSTRINGS";
create or replace view M_PARAMXML(
	PARAMGROUP,
	PARAMSTRING,
	PARAMINTEGER,
	PARAMXML
) as SELECT "PARAMGROUP", "PARAMSTRING", "PARAMINTEGER", "PARAMXML" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_PARAMXML";
create or replace view M_PERIOD(
	YEARCODE,
	PERIOD,
	TITLE,
	PERIODEND,
	SQSACCESS,
	MNEMONIC,
	COLUMNNAME,
	ACCESSID,
	COMPANYCODE,
	WEIGHTING,
	INCLUDEINBAL,
	PERIODID
) as SELECT "YEARCODE", "PERIOD", "TITLE", "PERIODEND", "SQSACCESS", "MNEMONIC", "COLUMNNAME", "ACCESSID", "COMPANYCODE", "WEIGHTING", "INCLUDEINBAL", "PERIODID" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_PERIOD";
create or replace view M_QRCOLUMN(
	COLNAME,
	TITLE,
	BASECOL,
	FROMPERIOD,
	TOPERIOD,
	KEYNAME,
	FROMITEM,
	TOITEM,
	RANGETYPE,
	COLUMNID,
	SQSACCESS,
	STRLEN,
	LEDGER,
	FROMACCOUNT,
	TOACCOUNT,
	CALCULATED,
	CRDR,
	COLTYPE,
	BASECOLONLY
) as SELECT "COLNAME", "TITLE", "BASECOL", "FROMPERIOD", "TOPERIOD", "KEYNAME", "FROMITEM", "TOITEM", "RANGETYPE", "COLUMNID", "SQSACCESS", "STRLEN", "LEDGER", "FROMACCOUNT", "TOACCOUNT", "CALCULATED", "CRDR", "COLTYPE", "BASECOLONLY" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_QRCOLUMN";
create or replace view M_TAXACCOUNT(
	LEDGER,
	ACCOUNT,
	TAXCODE,
	TAXRATE,
	STARTDATE,
	ENDDATE,
	TAXSTATUS,
	AUTOMATIC
) as SELECT "LEDGER", "ACCOUNT", "TAXCODE", "TAXRATE", "STARTDATE", "ENDDATE", "TAXSTATUS", "AUTOMATIC" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_TAXACCOUNT";
create or replace view M_TRANTYPE(
	TRANTYPE,
	TITLE,
	TRANTYPETYPE,
	USAGE,
	SQSACCESS,
	TRANTYPEID,
	POPSOP
) as SELECT "TRANTYPE", "TITLE", "TRANTYPETYPE", "USAGE", "SQSACCESS", "TRANTYPEID", "POPSOP" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_TRANTYPE";
create or replace view M_UOM(
	UOM,
	SYMBOL,
	NAME,
	CONTAINSUOM,
	CONTAINSQTY,
	DECPLACES
) as SELECT "UOM", "SYMBOL", "NAME", "CONTAINSUOM", "CONTAINSQTY", "DECPLACES" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_UOM";
create or replace view M_USER(
	USERNID,
	SQSUSERGROUP,
	TITLE,
	PWLASTCHANGE,
	PWLASTPW,
	LANGUAGE,
	TYPE,
	EMAILADDRESS,
	LONGUSERNAME,
	USERIDENTITY
) as SELECT "USERNID", "SQSUSERGROUP", "TITLE", "PWLASTCHANGE", "PWLASTPW", "LANGUAGE", "TYPE", "EMAILADDRESS", "LONGUSERNAME", "USERIDENTITY" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_USER";
create or replace view M_USERGROUP(
	SQSUSERGROUP,
	TITLE,
	SQSACCESS,
	PWEXP,
	WRITEACCESS,
	SUPERIORUSER,
	ORDERVALUELIMIT,
	ISRECEIVER,
	RECTOLPERCENT,
	RECTOLVALUE,
	ISMATCHER,
	MATCHTOLPERCENT,
	MATCHTOLVALUE,
	ISBUYER,
	BUYERDAYS,
	BUYERDEPUTYGROUP,
	ISAUTHORISE,
	AUTHDAYS,
	AUTHDEPUTYGROUP,
	DELADDCODE,
	USERGROUPID
) as SELECT "SQSUSERGROUP", "TITLE", "SQSACCESS", "PWEXP", "WRITEACCESS", "SUPERIORUSER", "ORDERVALUELIMIT", "ISRECEIVER", "RECTOLPERCENT", "RECTOLVALUE", "ISMATCHER", "MATCHTOLPERCENT", "MATCHTOLVALUE", "ISBUYER", "BUYERDAYS", "BUYERDEPUTYGROUP", "ISAUTHORISE", "AUTHDAYS", "AUTHDEPUTYGROUP", "DELADDCODE", "USERGROUPID" FROM "HAVEN_RAW"."PLOT_DREAM_ETLEAP"."M_USERGROUP";
