-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.CANCELLATIONS_DATA_HISTORY definition

USE ROLE haven_batch_dataload;

USE DATABASE haven_raw;
USE SCHEMA pricer;

SHOW TABLES;

create or replace TABLE haven_raw.pricer.CANCELLATIONS_DATA_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	BOOKING_STATUS VARCHAR(16777216),
	BREAK_DATE DATE,
	SHIP_CODE VARCHAR(16777216),
	LEAD_TIME_DAY NUMBER(38,0),
	RES_INIT_DATE DATE,
	CANCELLATION_DATE DATE,
	SOURCE VARCHAR(16777216),
	SAIL_FROM_DATE DATE,
	EDITED_HOLIDAY_DURATION NUMBER(38,0),
	TOTAL_RICHCORE FLOAT,
	TOTAL_TARIFF FLOAT,
	TOTAL_BOOKINGS FLOAT,
	DELUXE_6BERTH_RICHCORE FLOAT,
	DELUXE_6BERTH_BOOKINGS FLOAT,
	DELUXE_LIST_PRICE FLOAT
);


-- ALIGN_ALYTICS.TARGET_BREAK_INPUTS.DELUXE_PRICE_HISTORY definition

create or replace TABLE haven_raw.pricer.DELUXE_PRICE_HISTORY (
	DATA_VERSION_ID NUMBER(38,0),
	LOOKUP VARCHAR(16777216),
	PARK VARCHAR(16777216),
	WEEKDAY VARCHAR(16777216),
	PERIOD VARCHAR(16777216),
	OPTIMAL FLOAT,
	WEEKDAY_DOW NUMBER(38,0),
	PARK2 VARCHAR(16777216)
);