create or replace table HAVEN_STORE_AA_DEV.RMS_LAUNCH_PRICE_TOOL.SUPPLEMENTS_ADJUSTMENT as
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_LAUNCH_PRICE_TOOL.SUPPLEMENTS_ADJUSTMENT;

ALTER TABLE HAVEN_STORE_AA_DEV.RMS_LAUNCH_PRICE_TOOL.L1_PROCESS_CONTROL_HEADER
ADD COLUMN IS_ACTIVE_QAT BOOLEAN DEFAULT FALSE;

create table HAVEN_STORE_AA_DEV.RMS_REPORTING_GRADE.L1_PROCESS_CONTROL_HEADER as 
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_REPORTING_GRADE.L1_PROCESS_CONTROL_HEADER where parameter_id=1;

select * from HAVEN_STORE_AA_DEV.RMS_REPORTING_GRADE.CONFIG_UPLOAD_AUDIT as 
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_REPORTING_GRADE.CONFIG_UPLOAD_AUDIT where upload_description='Default';

select * from HAVEN_STORE_AA_DEV.RMS_REPORTING_GRADE.CONFIG_GRADE_GROUP_RULES as 
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_REPORTING_GRADE.CONFIG_GRADE_GROUP_RULES where upload_id=1;

select * from HAVEN_STORE_AA_DEV.RMS_REPORTING_GRADE.CONFIG_SUPPLEMENT_RULES as 
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_REPORTING_GRADE.CONFIG_SUPPLEMENT_RULES;

select * from HAVEN_STORE_AA_DEV.RMS_REPORTING_GRADE.CONFIG_DECISION_MATRIX as 
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_REPORTING_GRADE.CONFIG_DECISION_MATRIX;

select * from HAVEN_STORE_AA_DEV.RMS_REPORTING_GRADE.CONFIG_LOW_CAP_TIERS as 
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_REPORTING_GRADE.CONFIG_LOW_CAP_TIERS;

select * from HAVEN_STORE_AA_DEV.RMS_REPORTING_GRADE.CONFIG_ACTIVE_ENTITIES as 
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_REPORTING_GRADE.CONFIG_ACTIVE_ENTITIES where upload_id=1;

select * from HAVEN_STORE_AA_DEV.RMS_REPORTING_GRADE.CONFIG_MANUAL_ADJUSTMENTS  as 
select * from HAVEN_STORE_AA_DEV.DEV_DBT_RMS_REPORTING_GRADE.CONFIG_MANUAL_ADJUSTMENTS where upload_id=0;