use role sysadmin;

drop schema butlins_base.plot;

drop schema butlins_raw.plot;

drop schema butlins_store.sas_pims;
drop schema butlins_store.sas_scv;

show roles like '_butlins%plot%';

use role useradmin;

drop role _butlins_store__sas_pims__owner;
drop role _butlins_store__sas_pims__creator;
drop role _butlins_store__sas_pims__writer;
drop role _butlins_store__sas_pims__reader;
drop role _butlins_store__sas_pims__usage;

drop role _butlins_store__sas_scv__owner;
drop role _butlins_store__sas_scv__creator;
drop role _butlins_store__sas_scv__writer;
drop role _butlins_store__sas_scv__reader;
drop role _butlins_store__sas_scv__usage;

drop role _butlins_base__plot__owner;
drop role _butlins_base__plot__creator;
drop role _butlins_base__plot__writer;
drop role _butlins_base__plot__reader;
drop role _butlins_base__plot__usage;

drop role _butlins_raw__plot__owner;
drop role _butlins_raw__plot__creator;
drop role _butlins_raw__plot__writer;
drop role _butlins_raw__plot__reader;
drop role _butlins_raw__plot__usage;

DROP ROLE _BUTLINS_BASE__PLOT__POSTCODE_SECTOR	;	
DROP ROLE _BUTLINS_BASE__PLOT__ADDRESS;	
DROP ROLE _BUTLINS_BASE__PLOT__DERIVED;	
DROP ROLE _BUTLINS_BASE__PLOT__EMAIL;	
DROP ROLE _BUTLINS_BASE__PLOT__EMAIL_PROVIDER	;	
DROP ROLE _BUTLINS_BASE__PLOT__FINANCIAL;	
DROP ROLE _BUTLINS_BASE__PLOT__PERSONAL;	
DROP ROLE _BUTLINS_BASE__PLOT__POSTCODE;	
DROP ROLE _BUTLINS_BASE__PLOT__POSTCODE_AREA	;	
DROP ROLE _BUTLINS_BASE__PLOT__POSTCODE_REGION	;	
DROP ROLE _BUTLINS_BASE__PLOT__REGISTRATION;	
DROP ROLE _BUTLINS_BASE__PLOT__REGISTRATION_LOCATION	;	
DROP ROLE _BUTLINS_BASE__PLOT__REGISTRATION_LOCNYEAR	;	
DROP ROLE _BUTLINS_BASE__PLOT__REGISTRATION_YEAR	;	
DROP ROLE _BUTLINS_BASE__PLOT__SENSITIVE;	
DROP ROLE _BUTLINS_BASE__PLOT__TELEPHONE;	
DROP ROLE _BUTLINS_BASE__PLOT__THIRDPARTY;	

SHOW ROLES LIKE 'BUTLINS%';

DROP ROLE BUTLINS_COMMERCIAL;
DROP ROLE BUTLINS_QUALTRICS_DATALOAD;
DROP ROLE BUTLINS_ZENDESK_DATALOAD;
DROP ROLE BUTLINS_BATCH_DATALOAD;
DROP ROLE BUTLINS_BASE_TRANSFORM;

SHOW ROLES LIKE '_BUTLINS_BASE%';

DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__POSTCODE_SECTOR	;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__ADDRESS;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__DERIVED;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__EMAIL;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__EMAIL_PROVIDER	;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__FINANCIAL;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__PERSONAL;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__POSTCODE;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__POSTCODE_AREA	;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__POSTCODE_REGION	;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__REGISTRATION;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__REGISTRATION_LOCATION	;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__REGISTRATION_LOCNYEAR	;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__REGISTRATION_YEAR	;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__SENSITIVE;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__TELEPHONE;	
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__THIRDPARTY;

DROP ROLE _BUTLINS_BASE__AZTEC__POSTCODE_SECTOR	;	
DROP ROLE _BUTLINS_BASE__AZTEC__ADDRESS;	
DROP ROLE _BUTLINS_BASE__AZTEC__DERIVED;	
DROP ROLE _BUTLINS_BASE__AZTEC__EMAIL;	
DROP ROLE _BUTLINS_BASE__AZTEC__EMAIL_PROVIDER	;	
DROP ROLE _BUTLINS_BASE__AZTEC__FINANCIAL;	
DROP ROLE _BUTLINS_BASE__AZTEC__PERSONAL;	
DROP ROLE _BUTLINS_BASE__AZTEC__POSTCODE;	
DROP ROLE _BUTLINS_BASE__AZTEC__POSTCODE_AREA	;	
DROP ROLE _BUTLINS_BASE__AZTEC__POSTCODE_REGION	;	
--DROP ROLE _BUTLINS_BASE__AZTEC__REGISTRATION;	
--DROP ROLE _BUTLINS_BASE__AZTEC__REGISTRATION_LOCATION	;	
--DROP ROLE _BUTLINS_BASE__AZTEC__REGISTRATION_LOCNYEAR	;	
--DROP ROLE _BUTLINS_BASE__AZTEC__REGISTRATION_YEAR	;	
DROP ROLE _BUTLINS_BASE__AZTEC__SENSITIVE;	
DROP ROLE _BUTLINS_BASE__AZTEC__TELEPHONE;	
DROP ROLE _BUTLINS_BASE__AZTEC__THIRDPARTY;	


SHOW ROLES LIKE '_BUTLINS_BASE%';

DROP ROLE _BUTLINS_BASE__QUERY_LOG__OWNER;
DROP ROLE _BUTLINS_BASE__QUERY_LOG__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_BASE__QUERY_LOG__WRITER;
DROP ROLE _BUTLINS_BASE__QUERY_LOG__READER;
DROP ROLE _BUTLINS_BASE__QUERY_LOG__USAGE;

USE ROLE USERADMIN;
DROP ROLE _BUTLINS_BASE__AZTEC__OWNER;
DROP ROLE _BUTLINS_BASE__AZTEC__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_BASE__AZTEC__WRITER;
DROP ROLE _BUTLINS_BASE__AZTEC__READER;
DROP ROLE _BUTLINS_BASE__AZTEC__USAGE;

USE ROLE USERADMIN;
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__OWNER;
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__WRITER;
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__READER;
DROP ROLE _BUTLINS_BASE__AZTECACTIVITYMANAGEMENT__USAGE;



SHOW ROLES LIKE '_BUTLINS_BASE%';

USE ROLE SYSADMIN;

DROP SCHEMA BUTLINS_BASE.AZTECACTIVITYMANAGEMENT;
DROP SCHEMA BUTLINS_BASE.AZTEC;
DROP SCHEMA BUTLINS_BASE.QUERY_LOG;
DROP SCHEMA BUTLINS_RAW.QUALTRICS;
DROP SCHEMA BUTLINS_BASE.QUERY_LOG;
DROP SCHEMA BUTLINS_RAW.ZONAL;

USE ROLE SYSADMIN;
DROP SCHEMA BUTLINS_STORE.COMMON;
DROP SCHEMA BUTLINS_STORE.KMSREPORTING;
DROP SCHEMA BUTLINS_STORE.ZBSDATA;

USE ROLE DBA;

SHOW ROLES LIKE '_BUTLINS_STORE__%';

USE ROLE USERADMIN;
DROP ROLE _BUTLINS_STORE__COMMON__OWNER;
DROP ROLE _BUTLINS_STORE__COMMON__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_STORE__COMMON__WRITER;
DROP ROLE _BUTLINS_STORE__COMMON__READER;
DROP ROLE _BUTLINS_STORE__COMMON__USAGE;

USE ROLE USERADMIN;
DROP ROLE _BUTLINS_STORE__ZBSDATA__OWNER;
DROP ROLE _BUTLINS_STORE__ZBSDATA__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_STORE__ZBSDATA__WRITER;
DROP ROLE _BUTLINS_STORE__ZBSDATA__READER;
DROP ROLE _BUTLINS_STORE__ZBSDATA__USAGE;

USE ROLE USERADMIN;
DROP ROLE _BUTLINS_STORE__KMSREPORTING__OWNER;
DROP ROLE _BUTLINS_STORE__KMSREPORTING__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_STORE__KMSREPORTING__WRITER;
DROP ROLE _BUTLINS_STORE__KMSREPORTING__READER;
DROP ROLE _BUTLINS_STORE__KMSREPORTING__USAGE;

USE ROLE USERADMIN;
DROP ROLE _BUTLINS_STORE__KMSREPORTING_COMPLEX__OWNER;
DROP ROLE _BUTLINS_STORE__KMSREPORTING_COMPLEX__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_STORE__KMSREPORTING_COMPLEX__WRITER;
DROP ROLE _BUTLINS_STORE__KMSREPORTING_COMPLEX__READER;
DROP ROLE _BUTLINS_STORE__KMSREPORTING_COMPLEX__USAGE;

SHOW ROLES LIKE '_BUTLINS%';

USE ROLE SECURITYADMIN;
GRANT ROLE BOURNE_GOVERNANCE TO USER JOHNGOODWIN;

USE ROLE SYSADMIN;

USE ROLE USERADMIN;
DROP ROLE _BUTLINS_RAW__QUALTRICS__OWNER;
DROP ROLE _BUTLINS_RAW__QUALTRICS__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_RAW__QUALTRICS__WRITER;
DROP ROLE _BUTLINS_RAW__QUALTRICS__READER;
DROP ROLE _BUTLINS_RAW__QUALTRICS__USAGE;

USE ROLE USERADMIN;
DROP ROLE _BUTLINS_RAW__ZONAL__OWNER;
DROP ROLE _BUTLINS_RAW__ZONAL__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_RAW__ZONAL__WRITER;
DROP ROLE _BUTLINS_RAW__ZONAL__READER;
DROP ROLE _BUTLINS_RAW__ZONAL__USAGE;


USE ROLE USERADMIN;
DROP ROLE _BUTLINS_RAW__QUERY_LOG__OWNER;
DROP ROLE _BUTLINS_RAW__QUERY_LOG__CREATOR;
USE ROLE SECURITYADMIN;
DROP ROLE _BUTLINS_RAW__QUERY_LOG__WRITER;
DROP ROLE _BUTLINS_RAW__QUERY_LOG__READER;
DROP ROLE _BUTLINS_RAW__QUERY_LOG__USAGE;

DROP ROLE _BUTLINS_BASE__CREATE;
DROP ROLE _BUTLINS_BASE__USAGE;
DROP ROLE _BUTLINS_STORE__CREATE;
DROP ROLE _BUTLINS_STORE__USAGE;

SHOW GRANTS TO ROLE BOURNE_GOVERNANCE;

USE ROLE SYSADMIN;

DROP DATABASE BUTLINS_STORE;
DROP DATABASE BUTLINS_BASE;

use role dba;
describe table haven_raw.seaware.client;

use database haven_raw;
use schema seaware;
show tables like 'client';

select table_owner from haven_raw.information_schema.tables
where table_name = 'CLIENT'
and table_schema = 'SEAWARE'
and table_catalog = 'HAVEN_RAW';