USE ROLE securityadmin;

show GRANTS TO ROLE _haven_raw__pricer__usage;

USE ROLE sysadmin;
USE DATABASE haven_raw;
ALTER SCHEMA haven_raw.align_alytics RENAME TO haven_raw.pricer;
USE ROLE useradmin;
ALTER ROLE _haven_raw__align_alytics__usage RENAME TO _haven_raw__pricer__usage;
ALTER ROLE _haven_raw__align_alytics__reader RENAME TO _haven_raw__pricer__reader;
ALTER ROLE _haven_raw__align_alytics__writer RENAME TO _haven_raw__pricer__writer;
ALTER ROLE _haven_raw__align_alytics__creator RENAME TO _haven_raw__pricer__creator;
ALTER ROLE _haven_raw__align_alytics__owner RENAME TO _haven_raw__pricer__owner;

USE ROLE securityadmin;

show GRANTS TO ROLE _haven_raw__align_alytics__usage;
show GRANTS TO ROLE _haven_raw__pricer__creator;

USE ROLE sysadmin;
USE DATABASE haven_base;
ALTER SCHEMA haven_base.align_alytics RENAME TO haven_base.pricer;
USE ROLE useradmin;
ALTER ROLE _haven_base__align_alytics__usage RENAME TO _haven_base__pricer__usage;
ALTER ROLE _haven_base__align_alytics__reader RENAME TO _haven_base__pricer__reader;
ALTER ROLE _haven_base__align_alytics__writer RENAME TO _haven_base__pricer__writer;
ALTER ROLE _haven_base__align_alytics__creator RENAME TO _haven_base__pricer__creator;
ALTER ROLE _haven_base__align_alytics__owner RENAME TO _haven_base__pricer__owner;

USE ROLE securityadmin;

show GRANTS TO ROLE _haven_base__align_alytics__usage;
show GRANTS TO ROLE _haven_base__pricer__creator;

USE schema haven_base.pricer;

SHOW VIEWS;
USE ROLE dba;

CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.BREAK_LOOKUP_HISTORY ( DATA_VERSION_ID, BREAKID, RESORT_NAME, SHIP_CODE, BREAK_TYPE, TARGET_FILL_BREAK_SEGMENT, MATCHED_DATE, LOOKUP, MATCHED_LOOKUP, DELUXE_AVG_PRICE_ACHD ) AS SELECT "DATA_VERSION_ID", "BREAKID", "RESORT_NAME", "SHIP_CODE", "BREAK_TYPE", "TARGET_FILL_BREAK_SEGMENT", "MATCHED_DATE", "LOOKUP", "MATCHED_LOOKUP", "DELUXE_AVG_PRICE_ACHD" FROM "HAVEN_RAW"."PRICER"."BREAK_LOOKUP_HISTORY";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.BREAK_SEGMENTATION_LOOKUP_HISTORY ( DATA_VERSION_ID, BREAKID, RESORT_NAME, SHIP_CODE, BREAK_TYPE, TARGET_FILL_BREAK_SEGMENT, LOOKUP ) AS SELECT "DATA_VERSION_ID", "BREAKID", "RESORT_NAME", "SHIP_CODE", "BREAK_TYPE", "TARGET_FILL_BREAK_SEGMENT", "LOOKUP" FROM "HAVEN_RAW"."PRICER"."BREAK_SEGMENTATION_LOOKUP_HISTORY";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.BREAK_TARGET_OUTPUT_HISTORY ( VERSION_ID, BREAK_DATE, SHIP_CODE, TARGET_FILL_BREAK_SEGMENT, LEAD_TIME_WEEKS, LEAD_TIME_DAYS, ADJUSTED_GROSS_ROS, ADJUSTED_NET_ROS, PRICE, SILVER_PRICE, RICHCORE ) AS SELECT "VERSION_ID", "BREAK_DATE", "SHIP_CODE", "TARGET_FILL_BREAK_SEGMENT", "LEAD_TIME_WEEKS", "LEAD_TIME_DAYS", "ADJUSTED_GROSS_ROS", "ADJUSTED_NET_ROS", "PRICE", "SILVER_PRICE", "RICHCORE" FROM "HAVEN_RAW"."PRICER"."BREAK_TARGET_OUTPUT_HISTORY";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.BUDGET_INPUTS_HISTORY ( DATA_VERSION_ID, HAVEN_SHIP_CODE, SEASON, BREAK_DATE, WEEK_DATE, BREAK_AND_HAVEN_CODE, OCC_CODE, PERIOD, ARRIVAL_DAY, HIREFLEET_BREAKS, LETTING_BREAKS, FINAL_BILLINGS, FINAL_BREAKS, WEEKS, UNIT_CONVERSION, BREAK_AND_OCC_CODE, UNIT_NO, SUN_UNITS, SUN_REV, DIRECT_UNITS, DIRECT_REV ) AS SELECT "DATA_VERSION_ID", "HAVEN_SHIP_CODE", "SEASON", "BREAK_DATE", "WEEK_DATE", "BREAK_AND_HAVEN_CODE", "OCC_CODE", "PERIOD", "ARRIVAL_DAY", "HIREFLEET_BREAKS", "LETTING_BREAKS", "FINAL_BILLINGS", "FINAL_BREAKS", "WEEKS", "UNIT_CONVERSION", "BREAK_AND_OCC_CODE", "UNIT_NO", "SUN_UNITS", "SUN_REV", "DIRECT_UNITS", "DIRECT_REV" FROM "HAVEN_RAW"."PRICER"."BUDGET_INPUTS_HISTORY";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.CALENDAR_LOOKUP_HISTORY ( DATA_VERSION_ID, PERIOD, BREAKDATE_CURRENT, BREAKDATE_PRIOR, WEEKDAY, PERIOD2, DATE1, DATE2 ) AS SELECT "DATA_VERSION_ID", "PERIOD", "BREAKDATE_CURRENT", "BREAKDATE_PRIOR", "WEEKDAY", "PERIOD2", "DATE1", "DATE2" FROM "HAVEN_RAW"."PRICER"."CALENDAR_LOOKUP_HISTORY";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.INPUT_MODEL_META ( INPUT_NAME, DATA_VERSION_ID, DESCRIPTION, DATE_RANGE ) AS SELECT "INPUT_NAME", "DATA_VERSION_ID", "DESCRIPTION", "DATE_RANGE" FROM "HAVEN_RAW"."PRICER"."INPUT_MODEL_META";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.OPTIMISER_INPUTS_PRICE_SHAPE_CHANGE_HISTORY ( DATA_VERSION_ID, BREAK_SEGMENT, PERIOD_1, PERIOD_2, PERIOD_3, PERIOD_4, PERIOD_5, PERIOD_6, PERIOD_7, PERIOD_8, PERIOD_9, EBO, WEIGHTED_AVG ) AS SELECT "DATA_VERSION_ID", "BREAK_SEGMENT", "PERIOD_1", "PERIOD_2", "PERIOD_3", "PERIOD_4", "PERIOD_5", "PERIOD_6", "PERIOD_7", "PERIOD_8", "PERIOD_9", "EBO", "WEIGHTED_AVG" FROM "HAVEN_RAW"."PRICER"."OPTIMISER_INPUTS_PRICE_SHAPE_CHANGE_HISTORY";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.OPTIMISER_INPUTS_VOLUME_PERC_SHAPE_HISTORY ( DATA_VERSION_ID, SEGMENT, BREAK_DATE, LOOKUP, WEEK_60, WEEK_59, WEEK_58, WEEK_57, WEEK_56, WEEK_55, WEEK_54, WEEK_53, WEEK_52, WEEK_51, WEEK_50, WEEK_49, WEEK_48, WEEK_47, WEEK_46, WEEK_45, WEEK_44, WEEK_43, WEEK_42, WEEK_41, WEEK_40, WEEK_39, WEEK_38, WEEK_37, WEEK_36, WEEK_35, WEEK_34, WEEK_33, WEEK_32, WEEK_31, WEEK_30, WEEK_29, WEEK_28, WEEK_27, WEEK_26, WEEK_25, WEEK_24, WEEK_23, WEEK_22, WEEK_21, WEEK_20, WEEK_19, WEEK_18, WEEK_17, WEEK_16, WEEK_15, WEEK_14, WEEK_13, WEEK_12, WEEK_11, WEEK_10, WEEK_9, WEEK_8, WEEK_7, WEEK_6, WEEK_5, WEEK_4, WEEK_3, WEEK_2, WEEK_1, WEEK_0 ) AS SELECT "DATA_VERSION_ID", "SEGMENT", "BREAK_DATE", "LOOKUP", "WEEK_60", "WEEK_59", "WEEK_58", "WEEK_57", "WEEK_56", "WEEK_55", "WEEK_54", "WEEK_53", "WEEK_52", "WEEK_51", "WEEK_50", "WEEK_49", "WEEK_48", "WEEK_47", "WEEK_46", "WEEK_45", "WEEK_44", "WEEK_43", "WEEK_42", "WEEK_41", "WEEK_40", "WEEK_39", "WEEK_38", "WEEK_37", "WEEK_36", "WEEK_35", "WEEK_34", "WEEK_33", "WEEK_32", "WEEK_31", "WEEK_30", "WEEK_29", "WEEK_28", "WEEK_27", "WEEK_26", "WEEK_25", "WEEK_24", "WEEK_23", "WEEK_22", "WEEK_21", "WEEK_20", "WEEK_19", "WEEK_18", "WEEK_17", "WEEK_16", "WEEK_15", "WEEK_14", "WEEK_13", "WEEK_12", "WEEK_11", "WEEK_10", "WEEK_9", "WEEK_8", "WEEK_7", "WEEK_6", "WEEK_5", "WEEK_4", "WEEK_3", "WEEK_2", "WEEK_1", "WEEK_0" FROM "HAVEN_RAW"."PRICER"."OPTIMISER_INPUTS_VOLUME_PERC_SHAPE_HISTORY";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.PROCESS_CONTROL_HEADER ( VERSION_ID, RUN_DATE, PROPERTIES ) AS SELECT "VERSION_ID", "RUN_DATE", "PROPERTIES" FROM "HAVEN_RAW"."PRICER"."PROCESS_CONTROL_HEADER";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.S1_DIM_BREAKS_CORE ( PARK_CODE, BREAK_ID, BREAK_DATE_FROM, BREAK_DATE_TO, BREAK_SAMPLE_DATE, DURATION, RELATIVE_DATE, RELATIVE_OUTLOOK, BREAK_DOW, BREAK_YEAR_NUMBER, BREAK_YEAR, BREAK_MONTH, SEGMENT_SEASON, SEGMENT_BREAK, SEGMENT_GROUP, TARGET_FILL_BREAK_SEGMENT, BREAK_PERIOD, PACKAGE_DETAIL, CORE_PACKAGE_DETAIL ) AS SELECT "PARK_CODE", "BREAK_ID", "BREAK_DATE_FROM", "BREAK_DATE_TO", "BREAK_SAMPLE_DATE", "DURATION", "RELATIVE_DATE", "RELATIVE_OUTLOOK", "BREAK_DOW", "BREAK_YEAR_NUMBER", "BREAK_YEAR", "BREAK_MONTH", "SEGMENT_SEASON", "SEGMENT_BREAK", "SEGMENT_GROUP", "TARGET_FILL_BREAK_SEGMENT", "BREAK_PERIOD", "PACKAGE_DETAIL", "CORE_PACKAGE_DETAIL" FROM "HAVEN_RAW"."PRICER"."S1_DIM_BREAKS_CORE";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.SHIP_LOOKUP ( OC_C_CODES, OC_C_LOCATION, HAVEN_CODE, SAME ) AS SELECT "OC_C_CODES", "OC_C_LOCATION", "HAVEN_CODE", "SAME" FROM "HAVEN_RAW"."PRICER"."SHIP_LOOKUP";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.SOURCE_LOOKUP_HISTORY ( DATA_VERSION_ID, ORIGINALS, MAPPING ) AS SELECT "DATA_VERSION_ID", "ORIGINALS", "MAPPING" FROM "HAVEN_RAW"."PRICER"."SOURCE_LOOKUP_HISTORY";
CREATE OR REPLACE VIEW HAVEN_BASE.PRICER.STAY_PRICE_ADJUSTMENT_HISTORY ( DATA_VERSION_ID, LOOKUP, BASE_LOOKUP, OCC_PARK, RESORT_NAME, ARRIVAL, GRADE, PACKAGE, PARK, PLAY_UPGRADE_PRICE, STAY_DISCOUNT ) AS SELECT "DATA_VERSION_ID", "LOOKUP", "BASE_LOOKUP", "OCC_PARK", "RESORT_NAME", "ARRIVAL", "GRADE", "PACKAGE", "PARK", "PLAY_UPGRADE_PRICE", "STAY_DISCOUNT" FROM "HAVEN_RAW"."PRICER"."STAY_PRICE_ADJUSTMENT_HISTORY";

USE ROLE haven_data_transform;
USE WAREHOUSE haven_data_transform_warehouse_xsmall;
SELECT * FROM BREAK_LOOKUP_HISTORY ;


USE ROLE sysadmin;
USE DATABASE haven_STORE;
ALTER SCHEMA haven_store.pricing RENAME TO haven_store.pricer;
USE ROLE useradmin;
ALTER ROLE _haven_store__pricing__usage RENAME TO _haven_store__pricer__usage;
ALTER ROLE _haven_store__pricing__reader RENAME TO _haven_store__pricer__reader;
ALTER ROLE _haven_store__pricing__writer RENAME TO _haven_store__pricer__writer;
ALTER ROLE _haven_store__pricing__creator RENAME TO _haven_store__pricer__creator;
ALTER ROLE _haven_store__pricing__owner RENAME TO _haven_store__pricer__owner;

USE ROLE securityadmin;

show GRANTS TO ROLE _haven_store__pricer__usage;
show GRANTS TO ROLE _haven_store__pricer__creator;

USE ROLE dba;
USE schema haven_store.pricer;

SHOW VIEWS;
USE ROLE dba;

USE SCHEMA haven_base.pricer;

DROP VIEW HAVEN_BASE.PRICER.DELUXE_PRICE_HISTORY;
DROP VIEW HAVEN_BASE.PRICER.CANCELLATIONS_DATA_HISTORY;
DROP VIEW HAVEN_BASE.PRICER.DELUXE_PRICE_HISTORY;
DROP VIEW HAVEN_BASE.PRICER.INPUT_MODEL_META;

USE ROLE haven_batch_dataload;
USE SCHEMA haven_raw.pricer;
DROP TABLE HAVEN_RAW.PRICER.DELUXE_PRICE_HISTORY;
DROP TABLE HAVEN_RAW.PRICER.CANCELLATIONS_DATA_HISTORY;
DROP TABLE HAVEN_RAW.PRICER.DELUXE_PRICE_HISTORY;
DROP TABLE HAVEN_RAW.PRICER.INPUT_MODEL_META;

USE ROLE haven_dbt_transform;

USE ROLE dba;

CREATE VIEW HAVEN_BASE.PRICER.CANCELLATIONS_DATA_HISTORY
( DATA_VERSION_ID, BOOKING_STATUS, BREAK_DATE, SHIP_CODE, LEAD_TIME_DAY, RES_INIT_DATE, CANCELLATION_DATE, SOURCE, SAIL_FROM_DATE, EDITED_HOLIDAY_DURATION, TOTAL_RICHCORE, TOTAL_TARIFF, TOTAL_BOOKINGS, DELUXE_6BERTH_RICHCORE, DELUXE_6BERTH_BOOKINGS, DELUXE_LIST_PRICE )
AS SELECT DATA_VERSION_ID, BOOKING_STATUS, BREAK_DATE, SHIP_CODE, LEAD_TIME_DAY, RES_INIT_DATE, CANCELLATION_DATE, "SOURCE", SAIL_FROM_DATE, EDITED_HOLIDAY_DURATION, TOTAL_RICHCORE, TOTAL_TARIFF, TOTAL_BOOKINGS, DELUXE_6BERTH_RICHCORE, DELUXE_6BERTH_BOOKINGS, DELUXE_LIST_PRICE
FROM HAVEN_RAW.PRICER.CANCELLATIONS_DATA_HISTORY;

CREATE VIEW HAVEN_BASE.PRICER.DELUXE_PRICE_HISTORY
( DATA_VERSION_ID, LOOKUP, PARK, WEEKDAY, PERIOD, OPTIMAL, WEEKDAY_DOW, PARK2 )
AS SELECT DATA_VERSION_ID, LOOKUP, PARK, WEEKDAY, PERIOD, OPTIMAL, WEEKDAY_DOW, PARK2
FROM HAVEN_RAW.PRICER.DELUXE_PRICE_HISTORY;