use role dba;

USE SCHEMA HAVEN_STORE.RMS_PRICER_FORECAST;

SHOW TABLES;

use warehouse haven_cdc_migration_wh;

CREATE OR REPLACE TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_FORECAST_HISTORY_TRNDATE AS SELECT * FROM HAVEN_STAGING.REVENUE_MANAGEMENT_OUTPUT.DMS_FORECAST_HISTORY_TRNDATE ;

CREATE OR REPLACE TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_PROCESS_CONTROL_HEADER AS SELECT * FROM HAVEN_STAGING.REVENUE_MANAGEMENT_OUTPUT.DMS_PROCESS_CONTROL_HEADER;

CREATE OR REPLACE  TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_FORECAST_HISTORY_STAYID AS SELECT * FROM HAVEN_STAGING.REVENUE_MANAGEMENT_OUTPUT.DMS_FORECAST_HISTORY_STAYID;

SHOW roles LIKE '_haven_store__rms_pricer_forecast%';

SHOW roles LIKE 'haven%forecast%';

SHOW tables;

GRANT ownership ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_FORECAST_HISTORY_TRNDATE TO ROLE haven_dbt_transform REVOKE CURRENT grants;
GRANT ownership ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_PROCESS_CONTROL_HEADER TO ROLE haven_dbt_transform REVOKE CURRENT grants;
GRANT ownership ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_FORECAST_HISTORY_STAYID TO ROLE haven_dbt_transform REVOKE CURRENT grants;


use ROLE securityadmin;
GRANT select ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_FORECAST_HISTORY_TRNDATE TO ROLE _haven_store__rms_pricer_forecast__reader;
GRANT select ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_PROCESS_CONTROL_HEADER TO ROLE _haven_store__rms_pricer_forecast__reader;
GRANT select ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_FORECAST_HISTORY_STAYID TO ROLE _haven_store__rms_pricer_forecast__reader;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_FORECAST_HISTORY_TRNDATE TO ROLE _haven_store__rms_pricer_forecast__writer;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_PROCESS_CONTROL_HEADER TO ROLE _haven_store__rms_pricer_forecast__writer;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON TABLE HAVEN_STORE.RMS_PRICER_FORECAST.DMS_FORECAST_HISTORY_STAYID TO ROLE _haven_store__rms_pricer_forecast__writer;
