--14/11/2024

USE ROLE DBA;

USE SCHEMA haven_base.workforce_sam;

CREATE OR REPLACE VIEW HAVEN_BASE.WORKFORCE_SAM.TASK_STAFF_LINK
( TS_ID, TASK_ID, STAFF_ID, EXPERIENCE, YEARS_EXPERIENCE, DEFAULT_TASK, AWARD_LEVEL_ID, PAY_GROUP_ID, PRIORITY, EXCLUDE_FROM_OPTIMIZATION )
AS SELECT TS_ID, TASK_ID, STAFF_ID, EXPERIENCE, YEARS_EXPERIENCE, DEFAULT_TASK, AWARD_LEVEL_ID, PAY_GROUP_ID, PRIORITY, EXCLUDE_FROM_OPTIMIZATION
FROM HAVEN_RAW.WORKFORCE_SAM.TASK_STAFF_LINK;