USE ROLE dba;

USE SCHEMA warner_cust.ma_mart;

USE ROLE warner_terraform_transform_dev;

USE WAREHOUSE warner_terraform_transform_dev_warehouse_xsmall;

-- WARNER_CUST.MA_MART.D_WRN_BOOKING source

SELECT BOOKING_REFERENCE, PERSON_ID, SUBJECT_ID, DATE(ARRIVAL_DATE), date(DEPARTURE_DATE), DATE(BOOK_DATE), BREAK_DURATION, TOTAL_GUESTS, TOTAL_ROOMS, REFERRAL_SOURCE, BREAK_STYLE, BREAK_TYPE, BREAK_DESCRIPTION, HOTEL_NAME, HOTEL_CATEGORY, ROOM_TYPE, ROOM_CODE, BOOK_LEAD_TIME, MULTI_ROOM_BOOKING, MISSION, BOOKING_CANCELLED, BOARD_TYPE, EMAIL_ADDRESS, SITE_CD, STATUS, VALID_EMAIL, VALID_EMAIL_DOMAIN, PAF_VALID, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6
FROM WARNER_BASE.MA_MART.D_WRN_BOOKING;

create or replace view WARNER_CUST.MA_MART.D_WRN_BOOKING(
	BOOKING_REFERENCE,
	PERSON_ID,
	SUBJECT_ID,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	BOOK_DATE,
	BREAK_DURATION,
	TOTAL_GUESTS,
	TOTAL_ROOMS,
	REFERRAL_SOURCE,
	BREAK_STYLE,
	BREAK_TYPE,
	BREAK_DESCRIPTION,
	HOTEL_NAME,
	HOTEL_CATEGORY,
	ROOM_TYPE,
	ROOM_CODE,
	BOOK_LEAD_TIME,
	MULTI_ROOM_BOOKING,
	MISSION,
	BOOKING_CANCELLED,
	BOARD_TYPE,
	EMAIL_ADDRESS,
	SITE_CD,
	STATUS,
	VALID_EMAIL,
	VALID_EMAIL_DOMAIN,
	PAF_VALID,
	SPARE_1,
	SPARE_2,
	SPARE_3,
	SPARE_4,
	SPARE_5,
	SPARE_6
) as SELECT BOOKING_REFERENCE, PERSON_ID, SUBJECT_ID, DATE(ARRIVAL_DATE), DATE(DEPARTURE_DATE), DATE(BOOK_DATE), BREAK_DURATION, TOTAL_GUESTS, TOTAL_ROOMS, REFERRAL_SOURCE, BREAK_STYLE, BREAK_TYPE, BREAK_DESCRIPTION, HOTEL_NAME, HOTEL_CATEGORY, ROOM_TYPE, ROOM_CODE, BOOK_LEAD_TIME, MULTI_ROOM_BOOKING, MISSION, BOOKING_CANCELLED, BOARD_TYPE, EMAIL_ADDRESS, SITE_CD, STATUS, VALID_EMAIL, VALID_EMAIL_DOMAIN, PAF_VALID, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6
FROM WARNER_BASE.MA_MART.D_WRN_BOOKING;


-- WARNER_CUST.MA_MART.D_WRN_CONTACT_RESPONSE source

create or replace view WARNER_CUST.MA_MART.D_WRN_CONTACT_RESPONSE(
	TASK_NAME,
	TASK_CODE,
	CAMPAIGN_NAME,
	CAMPAIGN_CODE,
	OCCURRENCE,
	SEGMENT_NAME,
	SEGMENT_CODE,
	SEGMENT_MAP_NAME,
	CONTACT_DATE,
	CONTACT_DTTM,
	SUBJECT_ID,
	EMAIL_SEND_DTTM,
	EMAIL_OPEN_DTTM,
	EMAIL_CLICK_DTTM
) as SELECT TASK_NAME, TASK_CODE, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, SEGMENT_MAP_NAME, DATE(CONTACT_DATE), CONTACT_DTTM, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, EMAIL_CLICK_DTTM
FROM WARNER_BASE.MA_MART.D_WRN_CONTACT_RESPONSE;


-- WARNER_CUST.MA_MART.D_WRN_EMAIL_SEEDS source

create or replace view WARNER_CUST.MA_MART.D_WRN_EMAIL_SEEDS(
	ADDRESS_ID,
	ARRIVAL_DATE,
	BOOKING_REFERENCE,
	DELEGATE1,
	DELEGATE2,
	DELEGATE3,
	DELEGATE4,
	EMAIL_ADDRESS,
	FIRSTNAME,
	HOTEL_NAME,
	MULTI_UNIT_BOOKING,
	NUMBER_GUESTS,
	NUMBER_ROOMS,
	PERSON_ID,
	SITE_CODE,
	SUBJECT_ID,
	SURNAME,
	TITLE
) as SELECT ADDRESS_ID, DATE(ARRIVAL_DATE), BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE
FROM WARNER_BASE.MA_MART.D_WRN_EMAIL_SEEDS;


-- WARNER_CUST.MA_MART.D_WRN_GUEST source

create or replace view WARNER_CUST.MA_MART.D_WRN_GUEST(
	PERSON_ID,
	SUBJECT_ID,
	ADDRESS_ID,
	TITLE,
	FIRSTNAME,
	SURNAME,
	EMAIL_ADDRESS,
	FIRST_LINE_ADDRESS,
	SECOND_LINE_ADDRESS,
	THIRD_LINE_ADDRESS,
	FOURTH_LINE_ADDRESS,
	FIFTH_LINE_ADDRESS,
	SIXTH_LINE_ADDRESS,
	POSTCODE,
	RFSEGMENT2022,
	FSEGMENT2022,
	RSEGMENT2022,
	PROSPECT_DATE,
	CLUB_MEMBER,
	NON_CLUB_MEMBER,
	ACTIVE,
	FTALLY,
	NEAREST_HOTEL_UNDER_TWO_HOURS,
	DRIVE_TIME_TO_ALVASTON_HALL,
	DRIVE_TIME_TO_BODELWYDDAN_CASTLE,
	DRIVE_TIME_TO_BEMBRIDGE_COAST,
	DRIVE_TIME_TO_CRICKET_ST_THOMAS,
	DRIVE_TIME_TO_CORTON,
	DRIVE_TIME_TO_GUNTON_HALL,
	DRIVE_TIME_TO_HOLME_LACY_HOUSE,
	DRIVE_TIME_TO_LITTLECOTE_HOUSE,
	DRIVE_TIME_TO_LAKESIDE,
	DRIVE_TIME_TO_NORTON_GRANGE,
	DRIVE_TIME_TO_NIDD_HALL,
	DRIVE_TIME_TO_SINAH_WARREN,
	DRIVE_TIME_TO_THORESBY_HALL,
	DRIVE_TIME_TO_STUDLEY_CASTLE,
	DRIVE_TIME_TO_HEYTHROP_PARK,
	LATE_BOOKER,
	PROSPECT_TYPE,
	LAST_ENEWS_SIGN_UP_DATE,
	LAST_BROCHURE_REQUEST_DATE,
	LAST_CANCELLED_DATE,
	LAST_QUOTE_DATE,
	OPTED_IN_TO_EMAIL,
	OPTED_IN_TO_DM,
	NUMBER_BOOKINGS_LAST_2_MONTH_HH,
	NUMBER_OF_PREVIOUS_STAYS_HH,
	NUMBER_OF_FUTURE_BOOKINGS_HH,
	NUMBER_OF_STAYS_LAST_6_MONTH_HH,
	NUMBER_OF_STAYS_LAST_12_MONTH_HH,
	NUMBER_OF_STAYS_LAST_2_YEARS_HH,
	NUMBER_OF_STAYS_LAST_3_YEARS_HH,
	NUMBER_OF_STAYS_LAST_5_YEARS_HH,
	DECEASED,
	VALID_EMAIL,
	VALID_EMAIL_DOMAIN,
	PAF_VALID,
	FLAG_GUEST,
	SPARE_1,
	SPARE_2,
	SPARE_3,
	SPARE_4,
	SPARE_5,
	SPARE_6
) as SELECT PERSON_ID, SUBJECT_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, FIRST_LINE_ADDRESS, SECOND_LINE_ADDRESS, THIRD_LINE_ADDRESS, FOURTH_LINE_ADDRESS, FIFTH_LINE_ADDRESS, SIXTH_LINE_ADDRESS, POSTCODE, RFSEGMENT2022, FSEGMENT2022, RSEGMENT2022, DATE(PROSPECT_DATE), CLUB_MEMBER, NON_CLUB_MEMBER, ACTIVE, FTALLY, NEAREST_HOTEL_UNDER_TWO_HOURS, DRIVE_TIME_TO_ALVASTON_HALL, DRIVE_TIME_TO_BODELWYDDAN_CASTLE, DRIVE_TIME_TO_BEMBRIDGE_COAST, DRIVE_TIME_TO_CRICKET_ST_THOMAS, DRIVE_TIME_TO_CORTON, DRIVE_TIME_TO_GUNTON_HALL, DRIVE_TIME_TO_HOLME_LACY_HOUSE, DRIVE_TIME_TO_LITTLECOTE_HOUSE, DRIVE_TIME_TO_LAKESIDE, DRIVE_TIME_TO_NORTON_GRANGE, DRIVE_TIME_TO_NIDD_HALL, DRIVE_TIME_TO_SINAH_WARREN, DRIVE_TIME_TO_THORESBY_HALL, DRIVE_TIME_TO_STUDLEY_CASTLE, DRIVE_TIME_TO_HEYTHROP_PARK, LATE_BOOKER, PROSPECT_TYPE, DATE(LAST_ENEWS_SIGN_UP_DATE), DATE(LAST_BROCHURE_REQUEST_DATE), DATE(LAST_CANCELLED_DATE), DATE(LAST_QUOTE_DATE), OPTED_IN_TO_EMAIL, OPTED_IN_TO_DM, NUMBER_BOOKINGS_LAST_2_MONTH_HH, NUMBER_OF_PREVIOUS_STAYS_HH, NUMBER_OF_FUTURE_BOOKINGS_HH, NUMBER_OF_STAYS_LAST_6_MONTH_HH, NUMBER_OF_STAYS_LAST_12_MONTH_HH, NUMBER_OF_STAYS_LAST_2_YEARS_HH, NUMBER_OF_STAYS_LAST_3_YEARS_HH, NUMBER_OF_STAYS_LAST_5_YEARS_HH, DECEASED, VALID_EMAIL, VALID_EMAIL_DOMAIN, PAF_VALID, FLAG_GUEST, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6
FROM WARNER_BASE.MA_MART.D_WRN_GUEST;



SELECT PERSON_ID, SUBJECT_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, FIRST_LINE_ADDRESS, SECOND_LINE_ADDRESS, THIRD_LINE_ADDRESS, FOURTH_LINE_ADDRESS, FIFTH_LINE_ADDRESS, SIXTH_LINE_ADDRESS, POSTCODE, RFSEGMENT2022, FSEGMENT2022, RSEGMENT2022, DATE(PROSPECT_DATE), CLUB_MEMBER, NON_CLUB_MEMBER, ACTIVE, FTALLY, NEAREST_HOTEL_UNDER_TWO_HOURS, DRIVE_TIME_TO_ALVASTON_HALL, DRIVE_TIME_TO_BODELWYDDAN_CASTLE, DRIVE_TIME_TO_BEMBRIDGE_COAST, DRIVE_TIME_TO_CRICKET_ST_THOMAS, DRIVE_TIME_TO_CORTON, DRIVE_TIME_TO_GUNTON_HALL, DRIVE_TIME_TO_HOLME_LACY_HOUSE, DRIVE_TIME_TO_LITTLECOTE_HOUSE, DRIVE_TIME_TO_LAKESIDE, DRIVE_TIME_TO_NORTON_GRANGE, DRIVE_TIME_TO_NIDD_HALL, DRIVE_TIME_TO_SINAH_WARREN, DRIVE_TIME_TO_THORESBY_HALL, DRIVE_TIME_TO_STUDLEY_CASTLE, DRIVE_TIME_TO_HEYTHROP_PARK, LATE_BOOKER, PROSPECT_TYPE, DATE(LAST_ENEWS_SIGN_UP_DATE), DATE(LAST_BROCHURE_REQUEST_DATE), DATE(LAST_CANCELLED_DATE), DATE(LAST_QUOTE_DATE), OPTED_IN_TO_EMAIL, OPTED_IN_TO_DM, NUMBER_BOOKINGS_LAST_2_MONTH_HH, NUMBER_OF_PREVIOUS_STAYS_HH, NUMBER_OF_FUTURE_BOOKINGS_HH, NUMBER_OF_STAYS_LAST_6_MONTH_HH, NUMBER_OF_STAYS_LAST_12_MONTH_HH, NUMBER_OF_STAYS_LAST_2_YEARS_HH, NUMBER_OF_STAYS_LAST_3_YEARS_HH, NUMBER_OF_STAYS_LAST_5_YEARS_HH, DECEASED, VALID_EMAIL, VALID_EMAIL_DOMAIN, PAF_VALID, FLAG_GUEST, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6
FROM WARNER_BASE.MA_MART.D_WRN_GUEST
WHERE PROSPECT_DATE IS NOT null;

SELECT *
FROM WARNER_BASE.MA_MART.D_WRN_GUEST
WHERE PROSPECT_DATE IS NOT null;

----
SHOW ROLES LIKE '%sas%';


GRANT SELECT on view WARNER_CUST.MA_MART.D_WRN_BOOKING TO ROLE WARNER_CUST_SAS; 


-- WARNER_CUST.MA_MART.D_WRN_CONTACT_RESPONSE source

GRANT SELECT ON view WARNER_CUST.MA_MART.D_WRN_CONTACT_RESPONSE TO ROLE WARNER_CUST_SAS;


-- WARNER_CUST.MA_MART.D_WRN_EMAIL_SEEDS source

GRANT SELECT ON view WARNER_CUST.MA_MART.D_WRN_EMAIL_SEEDS TO ROLE WARNER_CUST_SAS;

-- WARNER_CUST.MA_MART.D_WRN_GUEST source

GRANT SELECT ON view WARNER_CUST.MA_MART.D_WRN_GUEST TO ROLE WARNER_CUST_SAS;

USE ROLE WARNER_CUST_SAS;

SHOW WAREHOUSES;

USE WAREHOUSE WARNER_SAS_warehouse;

SELECT * FROM WARNER_CUST.MA_MART.D_WRN_GUEST LIMIT 20;