USE ROLE securityadmin;

GRANT USAGE ON SCHEMA warner_store.SEAWARE_APS TO DATABASE ROLE warner_store.aps_share;

USE ROLE DBA;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.ACC_TRANS_DETAIL
( TRANS_ID, TRANS_STATUS, FORM_OF_TRANS, TRANS_TYPE, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID, DEST_ENTITY_TYPE, DEST_ENTITY_ID, EXTERNAL_IDENT, BATCH_HDR_ID, CURRENCY_CODE, TRANS_AMOUNT, TRANS_AMOUNT_LEFT, TRANS_TIME_STAMP, TRANS_GROUP_ID, AMOUNT_ORIG_CURRENCY, COMMENTS, USER_ID, FIRST_TRANS_ID, PREV_TRANS_ID, VOIDED_TIME_STAMP, VOIDED_BY_USER_ID, APPROVED_TIME_STAMP, APPROVED_BY_USER_ID, TRANS_STATUS_TIME_STAMP, AMOUNT_ORIG_CURRENCY_LEFT, EXCHANGE_RATE, USE_EXTENDED_PAY, DUE_DATE, INSUR_PAID, CC_AUTH_CODE, OFFICE_CODE, AR_AP_SEQ_ID, AR_AP_TIME_STAMP, REF_TRANS_ID, AR_AP_DUE_DATE, MERCHANT_NUMBER, ACT_HIST_ID, INTERN_BALANCED_COM, FPR_ID, OFFICE_LOCATION, IS_MANUAL, BASE_ENTITY_TYPE, BASE_ENTITY_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT TRANS_ID, TRANS_STATUS, FORM_OF_TRANS, TRANS_TYPE, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID, DEST_ENTITY_TYPE, DEST_ENTITY_ID, EXTERNAL_IDENT, BATCH_HDR_ID, CURRENCY_CODE, TRANS_AMOUNT, TRANS_AMOUNT_LEFT, TRANS_TIME_STAMP, TRANS_GROUP_ID, AMOUNT_ORIG_CURRENCY, COMMENTS, USER_ID, FIRST_TRANS_ID, PREV_TRANS_ID, VOIDED_TIME_STAMP, VOIDED_BY_USER_ID, APPROVED_TIME_STAMP, APPROVED_BY_USER_ID, TRANS_STATUS_TIME_STAMP, AMOUNT_ORIG_CURRENCY_LEFT, EXCHANGE_RATE, USE_EXTENDED_PAY, DUE_DATE, INSUR_PAID, CC_AUTH_CODE, OFFICE_CODE, AR_AP_SEQ_ID, AR_AP_TIME_STAMP, REF_TRANS_ID, AR_AP_DUE_DATE, MERCHANT_NUMBER, ACT_HIST_ID, INTERN_BALANCED_COM, FPR_ID, OFFICE_LOCATION, IS_MANUAL, BASE_ENTITY_TYPE, BASE_ENTITY_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.ACC_TRANS_DETAIL;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.AGENCY
( AGENCY_ID, AGENCY_NAME_TYPED, AGENCY_NAME, ARC_NUMBER, IATA_NUMBER, CLIA_NUMBER, IS_ACTIVE, IS_DOMESTIC, IS_INTERNAL, USE_GUEST_ADDR, COMMENTS, MARKETING_MSG, IS_GSA, CONSORTIUM_TYPE, IS_CONSORTIUM, AGENCY_TYPE, DEFAULT_CURRENCY, VENDOR_NUMBER, USE_DFLT_CONSORTIUM, BC_TYPE_ID, TAXPAYER_TYPE, TAXPAYER_NUMBER, CONTACT_NAME, WEB_ADDRESS, AGENCY_NAME_ESSENTIAL, FLOATING_DEPOSIT, LANGUAGE_CODE, COUNTRY_CODE, OFFICE_CODE, AG_ENTITY_TYPE, IS_FAX_EMAIL_SECURED, ABTA_NUMBER, NOTIF_DFLT_DISTR_TYPE, FPR_AT_GROSS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGENCY_ID, AGENCY_NAME_TYPED, AGENCY_NAME, ARC_NUMBER, IATA_NUMBER, CLIA_NUMBER, IS_ACTIVE, IS_DOMESTIC, IS_INTERNAL, USE_GUEST_ADDR, COMMENTS, MARKETING_MSG, IS_GSA, CONSORTIUM_TYPE, IS_CONSORTIUM, AGENCY_TYPE, DEFAULT_CURRENCY, VENDOR_NUMBER, USE_DFLT_CONSORTIUM, BC_TYPE_ID, TAXPAYER_TYPE, TAXPAYER_NUMBER, CONTACT_NAME, WEB_ADDRESS, AGENCY_NAME_ESSENTIAL, FLOATING_DEPOSIT, LANGUAGE_CODE, COUNTRY_CODE, OFFICE_CODE, AG_ENTITY_TYPE, IS_FAX_EMAIL_SECURED, ABTA_NUMBER, NOTIF_DFLT_DISTR_TYPE, FPR_AT_GROSS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.AGENCY;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.AGENCY_ADDRESS
( AGENCY_ID, SEQ_NUMBER, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, IS_ADDRESS_MAILING, IS_ADDRESS_SHIPPING, COMMENTS, AGENCY_ADDR_ID, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_ESSENTIAL, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGENCY_ID, SEQ_NUMBER, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, IS_ADDRESS_MAILING, IS_ADDRESS_SHIPPING, COMMENTS, AGENCY_ADDR_ID, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_ESSENTIAL, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.AGENCY_ADDRESS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.AGENCY_PHONE
( AGENCY_ID, SEQ_NUMBER, PHONE_TYPE, INTL_CODE, PHONE_NUMBER, IS_PHONE_PRIMARY, IS_PHONE_SECONDARY, IS_PHONE_FAX, FAX_ATTENTION_LINE, COMMENTS, AGENCY_PHONE_ID, PHONE_EXT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT AGENCY_ID, SEQ_NUMBER, PHONE_TYPE, INTL_CODE, PHONE_NUMBER, IS_PHONE_PRIMARY, IS_PHONE_SECONDARY, IS_PHONE_FAX, FAX_ATTENTION_LINE, COMMENTS, AGENCY_PHONE_ID, PHONE_EXT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.AGENCY_PHONE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.BLL_RM_PRICE
( RM_PRICE_ID, PARK_CODE, ARRIVAL_DATE, PACKAGE_TYPE, GRADE, PRICE, EFFECTIVE_FROM, INSERT_DATE, BLL_RM_PRICE_TYPE, PERCENT, GENERIC_GRADE, DESCRIPTION, ATTRIBUTE_CODE, ATTRIBUTE_VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RM_PRICE_ID, PARK_CODE, ARRIVAL_DATE, PACKAGE_TYPE, GRADE, PRICE, EFFECTIVE_FROM, INSERT_DATE, BLL_RM_PRICE_TYPE, "PERCENT", GENERIC_GRADE, DESCRIPTION, ATTRIBUTE_CODE, ATTRIBUTE_VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.BLL_RM_PRICE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.BLL_RM_PRICE_TYPE
( BLL_RM_PRICE_TYPE, BLL_RM_PRICE_TYPE_DESCRIPTION, BLL_RM_PRICE_TYPE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT BLL_RM_PRICE_TYPE, BLL_RM_PRICE_TYPE_DESCRIPTION, BLL_RM_PRICE_TYPE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.BLL_RM_PRICE_TYPE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CANCELLATION_CASE
( CASE_ID, CASE_NAME, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CASE_ID, CASE_NAME, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CANCELLATION_CASE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CC_CLIENT
( CC_ACC_NUMBER, CC_ACC_ID, CC_EXP_DATE, IS_CC_ACTIVE, IS_CC_BLACKLISTED, COMMENTS, CC_NAME_ON_CARD, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_CITY, STATE_CODE, CC_ADDRESS, ZIP, COUNTRY_CODE, ISSUER_BANK, CC_START_DATE, CC_ISSUE_NUMBER, CC_TYPE, CC_TOKEN, TOKEN_TYPE, VALIDATION_LOG, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CC_ACC_NUMBER, CC_ACC_ID, CC_EXP_DATE, IS_CC_ACTIVE, IS_CC_BLACKLISTED, COMMENTS, CC_NAME_ON_CARD, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_CITY, STATE_CODE, CC_ADDRESS, ZIP, COUNTRY_CODE, ISSUER_BANK, CC_START_DATE, CC_ISSUE_NUMBER, CC_TYPE, CC_TOKEN, TOKEN_TYPE, VALIDATION_LOG, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CC_CLIENT;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CC_ENTITY_LINK
( ENTITY_TYPE, ENTITY_ID, CC_ACC_NUMBER, CC_LINK_ID, IS_CC_PREFERRED, CC_CLIENT_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ENTITY_TYPE, ENTITY_ID, CC_ACC_NUMBER, CC_LINK_ID, IS_CC_PREFERRED, CC_CLIENT_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CC_ENTITY_LINK;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CC_PENDING_TRANS
( CC_TRANS_ID, TRANS_ID, USE_EXTENDED_PAY, USE_ADDR_VERIFICATION, AUTH_CODE, IS_PENDING, CX_REQUEST, SUBMITED_TIME_STAMP, ATTEMPT_COUNT, LAST_ATTEMPT_TIME_STAMP, LAST_RESPONSE, OPERATOR, DONOTIFY, SHIP_TRANS_ID, CC_TRANS_STATUS, TERMINAL, TRANS_SERVER_REFNUM, ECOMMERCE_INDICATOR, IS_AUTH_MANUAL, IS_ACTIVE, CC_CONTROL_NUMBER, SENDER_GUID, CC_COMBINED_ID, AUDIT_DATA, TRANS_DATA, TRANS_TOKEN, TOKEN_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CC_TRANS_ID, TRANS_ID, USE_EXTENDED_PAY, USE_ADDR_VERIFICATION, AUTH_CODE, IS_PENDING, CX_REQUEST, SUBMITED_TIME_STAMP, ATTEMPT_COUNT, LAST_ATTEMPT_TIME_STAMP, LAST_RESPONSE, OPERATOR, DONOTIFY, SHIP_TRANS_ID, CC_TRANS_STATUS, TERMINAL, TRANS_SERVER_REFNUM, ECOMMERCE_INDICATOR, IS_AUTH_MANUAL, IS_ACTIVE, CC_CONTROL_NUMBER, SENDER_GUID, CC_COMBINED_ID, AUDIT_DATA, TRANS_DATA, TRANS_TOKEN, TOKEN_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CC_PENDING_TRANS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CLIENT
( CLIENT_ID, HOUSEHOLD_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, SALUTATION, TITLE, OCCUPATION, IS_ACTIVE, BIRTHDAY, BIRTH_PLACE, SEX, IS_HANDICAPPED, IS_SMOKER, SOUVENIR_FNAME, SOUVENIR_LNAME, LANGUAGE, PASSPORT_NUMBER, PASSPORT_ISSUE_PLACE, PASSPORT_ISSUE_DATE, PASSPORT_EXP_DATE, NATIONALITY, CITIZENSHIP, REFERRAL_TYPE, REFERRAL_DATE, REFERRAL_CLIENT_ID, REFERRAL_HOUSEHOLD_ID, REFERRAL_SOURCE, COMMENTS, CLIENT_TYPE, GUEST_TYPE, DIRECTORY_NAME, CLIENT_CLASS_CODE, EMAIL, COUNTRY_OF_BIRTH, WEB_PASSWORD, WEB_LOGIN_NAME, WEB_LAST_LOGIN, SSN, LANGUAGE_CODE, HISTORICAL_CRUISES_NUM, HISTORICAL_DAYS_NUM, ALLOW_WEB_ACCESS, CL_ENTITY_TYPE, SEND_PROMOTIONAL_MAIL, SEND_PROMOTIONAL_EMAIL, SEND_PROMOTIONAL_SMS, NOTIF_DFLT_DISTR_TYPE, LAST_NAME_UPPER, SEND_PROMOTIONAL_PHONE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT CLIENT_ID, HOUSEHOLD_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, SALUTATION, TITLE, OCCUPATION, IS_ACTIVE, BIRTHDAY, BIRTH_PLACE, SEX, IS_HANDICAPPED, IS_SMOKER, SOUVENIR_FNAME, SOUVENIR_LNAME, "LANGUAGE", PASSPORT_NUMBER, PASSPORT_ISSUE_PLACE, PASSPORT_ISSUE_DATE, PASSPORT_EXP_DATE, NATIONALITY, CITIZENSHIP, REFERRAL_TYPE, REFERRAL_DATE, REFERRAL_CLIENT_ID, REFERRAL_HOUSEHOLD_ID, REFERRAL_SOURCE, COMMENTS, CLIENT_TYPE, GUEST_TYPE, DIRECTORY_NAME, CLIENT_CLASS_CODE, EMAIL, COUNTRY_OF_BIRTH, WEB_PASSWORD, WEB_LOGIN_NAME, WEB_LAST_LOGIN, SSN, LANGUAGE_CODE, HISTORICAL_CRUISES_NUM, HISTORICAL_DAYS_NUM, ALLOW_WEB_ACCESS, CL_ENTITY_TYPE, SEND_PROMOTIONAL_MAIL, SEND_PROMOTIONAL_EMAIL, SEND_PROMOTIONAL_SMS, NOTIF_DFLT_DISTR_TYPE, LAST_NAME_UPPER, SEND_PROMOTIONAL_PHONE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CLIENT;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.CLIENT_PREFER
( COMMENTS, CLIENT_ID, PREFERENCE_TYPE, PREFERENCE_CODE, CLIENT_PREFER_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT COMMENTS, CLIENT_ID, PREFERENCE_TYPE, PREFERENCE_CODE, CLIENT_PREFER_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.CLIENT_PREFER;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GL_TRANS
( GL_TRANS_ID, TRANS_ID, GL_BATCH_ID, GL_TRANS_AMOUNT, TRANS_TIME_STAMP, COMMENTS, FULL_DBT_GL, FULL_CRD_GL, SEQ_NUMBER, GL_TRANS_TYPE, ENTITY_TYPE, GL_TRANS_SOURCE, N_OF_DAYS, ENTITY_ID, PERIOD_ID, CURRENCY_CODE, IS_COMPLETED, FULL_N_OF_DAYS, ORIG_ITEM_CODE, ORIG_ITEM_SUBCODE, ORIG_ITEM_REC_ID, DLGT_RES_ID, IS_LAST_FOR_TRANS, PRORATE_METHOD, TRANS_HIST_ID, LOGICAL_DATE, GL_PACKAGE_ID, GUEST_ID, OFFICE_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT GL_TRANS_ID, TRANS_ID, GL_BATCH_ID, GL_TRANS_AMOUNT, TRANS_TIME_STAMP, COMMENTS, FULL_DBT_GL, FULL_CRD_GL, SEQ_NUMBER, GL_TRANS_TYPE, ENTITY_TYPE, GL_TRANS_SOURCE, N_OF_DAYS, ENTITY_ID, PERIOD_ID, CURRENCY_CODE, IS_COMPLETED, FULL_N_OF_DAYS, ORIG_ITEM_CODE, ORIG_ITEM_SUBCODE, ORIG_ITEM_REC_ID, DLGT_RES_ID, IS_LAST_FOR_TRANS, PRORATE_METHOD, TRANS_HIST_ID, LOGICAL_DATE, GL_PACKAGE_ID, GUEST_ID, OFFICE_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GL_TRANS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_BOOKING
( GROUP_ID, COMMENTS, AGENCY_ID, AGENT_ID, GROUP_NAME, GROUP_TYPE, N_OF_GUESTS, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, SHIP_CODE, IS_ACTIVE, IS_VALID, PROBABILITY, GROUP_STATUS, ALLOW_DIFF_AGENCY, EXPIRATION_EXTENSION, GROUP_INIT_DATE, WDW_GROUP_ID, PRIORITY, TERMINATION_COMPLETED, GROUP_SIZE_OVERRIDE, PROBABILITY_ALLOCATED, IS_CONTRACT_RATE, CAN_PROCESS_GTB, GRP_COORD_NAME, USE_TC_FULLPAY, CURRENCY_CODE, SEC_AGENCY_ID, LANGUAGE_CODE, IS_INVOICE_VALID, ALLOW_AUTO_DISTR_FUNDS, ALLOW_AUTO_CANCEL_DLGT, IS_CHARTER, OFFICE_CODE, IS_PROB_MANUAL, ALLOW_UNBALANCE, TOUR_CREDIT_POLICY_OVR, CURRENCY_RATE, IS_UNBALANCED, GB_ENTITY_TYPE, INVOICE_VERSION, FIRST_FULL_PAYMENT_PROCESSED, ALLOW_AUTO_PROCESS_FPR, ALLOW_REFUND_CLIENT_MONEY, DEFAULT_INSURANCE, AM_ORDER_ID, FPR_IN_PROCESS, COMPANY_ID, UPDATE_VERSION, IS_PAYSCH_MANUAL, TERMS_CONFIRMED, SOURCE_CODE, LEAD_CLIENT_ID, USE_FIT_PAYSCH, IS_MULTI_UNIT, ALLOW_DIFF_SAILS, REFERRAL_SOURCE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT GROUP_ID, COMMENTS, AGENCY_ID, AGENT_ID, GROUP_NAME, GROUP_TYPE, N_OF_GUESTS, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, SHIP_CODE, IS_ACTIVE, IS_VALID, PROBABILITY, GROUP_STATUS, ALLOW_DIFF_AGENCY, EXPIRATION_EXTENSION, GROUP_INIT_DATE, WDW_GROUP_ID, PRIORITY, TERMINATION_COMPLETED, GROUP_SIZE_OVERRIDE, PROBABILITY_ALLOCATED, IS_CONTRACT_RATE, CAN_PROCESS_GTB, GRP_COORD_NAME, USE_TC_FULLPAY, CURRENCY_CODE, SEC_AGENCY_ID, LANGUAGE_CODE, IS_INVOICE_VALID, ALLOW_AUTO_DISTR_FUNDS, ALLOW_AUTO_CANCEL_DLGT, IS_CHARTER, OFFICE_CODE, IS_PROB_MANUAL, ALLOW_UNBALANCE, TOUR_CREDIT_POLICY_OVR, CURRENCY_RATE, IS_UNBALANCED, GB_ENTITY_TYPE, INVOICE_VERSION, FIRST_FULL_PAYMENT_PROCESSED, ALLOW_AUTO_PROCESS_FPR, ALLOW_REFUND_CLIENT_MONEY, DEFAULT_INSURANCE, AM_ORDER_ID, FPR_IN_PROCESS, COMPANY_ID, UPDATE_VERSION, IS_PAYSCH_MANUAL, TERMS_CONFIRMED, SOURCE_CODE, LEAD_CLIENT_ID, USE_FIT_PAYSCH, IS_MULTI_UNIT, ALLOW_DIFF_SAILS, REFERRAL_SOURCE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_BOOKING;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_EVENT
( RECORD_ID, GROUP_EVENT_TYPE, GROUP_ID, EVENT_TIMESTAMP, EVENT_DATE, OPERATOR_ID, OLD_STATUS, NEW_STATUS, OLD_SHIP_CODE, OLD_SAIL_FROM, OLD_SAIL_TO, NEW_SHIP_CODE, NEW_SAIL_FROM, NEW_SAIL_TO, OLD_CABINS, OLD_GUEST_COUNT, NEW_CABINS, NEW_GUEST_COUNT, OLD_PROBABILITY, NEW_PROBABILITY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, GROUP_EVENT_TYPE, GROUP_ID, EVENT_TIMESTAMP, EVENT_DATE, OPERATOR_ID, OLD_STATUS, NEW_STATUS, OLD_SHIP_CODE, OLD_SAIL_FROM, OLD_SAIL_TO, NEW_SHIP_CODE, NEW_SAIL_FROM, NEW_SAIL_TO, OLD_CABINS, OLD_GUEST_COUNT, NEW_CABINS, NEW_GUEST_COUNT, OLD_PROBABILITY, NEW_PROBABILITY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_EVENT;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.HOUSEHOLD_ADDRESS
( HOUSEHOLD_ID, SEQ_NUMBER, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, IS_ADDRESS_MAILING, IS_ADDRESS_SHIPPING, DATE_FROM, DATE_TO, ARE_DATES_EVERY_YEAR, COMMENTS, HOUSEHOLD_ADDR_ID, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_ESSENTIAL, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HOUSEHOLD_ID, SEQ_NUMBER, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, IS_ADDRESS_MAILING, IS_ADDRESS_SHIPPING, DATE_FROM, DATE_TO, ARE_DATES_EVERY_YEAR, COMMENTS, HOUSEHOLD_ADDR_ID, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_ESSENTIAL, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.HOUSEHOLD_ADDRESS;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.HOUSEHOLD_PHONE
( HOUSEHOLD_ID, SEQ_NUMBER, PHONE_TYPE, INTL_CODE, PHONE_NUMBER, IS_PHONE_PRIMARY, IS_PHONE_SECONDARY, IS_PHONE_FAX, IS_PHONE_EMERGENCY, FAX_ATTENTION_LINE, COMMENTS, HOUSEHOLD_PHONE_ID, PHONE_EXT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT HOUSEHOLD_ID, SEQ_NUMBER, PHONE_TYPE, INTL_CODE, PHONE_NUMBER, IS_PHONE_PRIMARY, IS_PHONE_SECONDARY, IS_PHONE_FAX, IS_PHONE_EMERGENCY, FAX_ATTENTION_LINE, COMMENTS, HOUSEHOLD_PHONE_ID, PHONE_EXT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.HOUSEHOLD_PHONE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.PACKAGE_DEFINITION
( PACKAGE_ID, PACKAGE_CODE, VACATION_DATE, PACKAGE_TYPE, SAIL_ID, SEASON_CODE, GEOG_AREA_CODE, IS_ACTIVE, COMMENTS, SORT_SEQN, SHOREX_MODE, SHOREX_TIMING, ALT_PACKAGE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT PACKAGE_ID, PACKAGE_CODE, VACATION_DATE, PACKAGE_TYPE, SAIL_ID, SEASON_CODE, GEOG_AREA_CODE, IS_ACTIVE, COMMENTS, SORT_SEQN, SHOREX_MODE, SHOREX_TIMING, ALT_PACKAGE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.PACKAGE_DEFINITION;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.PACKAGE_TYPE
( PACKAGE_TYPE_ID, PACKAGE_TYPE, LAND_DAYS, SAIL_DAYS, COMMENTS, PRODUCT_TYPE, TC_PACKAGE_TYPE, LAND_DAYS_POST, IS_LAND_ONLY, IS_MULTI_SAIL, IS_SHOREX, IS_SECONDARY, IS_ACTIVE, SHOREX_TIMING, EXTRA_SEAT_QUESTION, PRE_POST_MODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT PACKAGE_TYPE_ID, PACKAGE_TYPE, LAND_DAYS, SAIL_DAYS, COMMENTS, PRODUCT_TYPE, TC_PACKAGE_TYPE, LAND_DAYS_POST, IS_LAND_ONLY, IS_MULTI_SAIL, IS_SHOREX, IS_SECONDARY, IS_ACTIVE, SHOREX_TIMING, EXTRA_SEAT_QUESTION, PRE_POST_MODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.PACKAGE_TYPE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_ADDON
( RES_ADDON_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, RES_ADDON_CODE, START_DATE, END_DATE, EFFECTIVE_DATE, AM_ORDER_ID, IS_DEFAULT, PAP_CODE, AMENITY_CODE, DELIVERY_PLACE, QUANTITY, IS_AUTO, COMMENTS, TIMESTAMP, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_ADDON_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, RES_ADDON_CODE, START_DATE, END_DATE, EFFECTIVE_DATE, AM_ORDER_ID, IS_DEFAULT, PAP_CODE, AMENITY_CODE, DELIVERY_PLACE, QUANTITY, IS_AUTO, COMMENTS, "TIMESTAMP", HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_ADDON;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_CHARGEABLE_ACTION
( ACTION_ID, ENTITY_TYPE, ENTITY_ID, RES_ACTION_TYPE, ACTION_TIMESTAMP, IS_ADDED_MANUALLY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ACTION_ID, ENTITY_TYPE, ENTITY_ID, RES_ACTION_TYPE, ACTION_TIMESTAMP, IS_ADDED_MANUALLY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_CHARGEABLE_ACTION;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_COMMISSION_DETAIL
( RES_COMMISS_DETAIL_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, COMMISS_SOURCE, COMMISS_CODE, PERCENT, AMOUNT, INVOICE_ITEM_TYPE, COMMISS_FARE, IS_MANUAL_ADJUSTMENT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_COMMISS_DETAIL_ID, RES_PACKAGE_ID, GUEST_ID, RES_ID, COMMISS_SOURCE, COMMISS_CODE, "PERCENT", AMOUNT, INVOICE_ITEM_TYPE, COMMISS_FARE, IS_MANUAL_ADJUSTMENT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_COMMISSION_DETAIL;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_EVENT
( RECORD_ID, RES_EVENT_TYPE, RES_ID, EVENT_TIMESTAMP, OPERATOR_ID, OLD_STATUS, NEW_STATUS, OLD_SHIP_CODE, OLD_SAIL_FROM, OLD_SAIL_TO, NEW_SHIP_CODE, NEW_SAIL_FROM, NEW_SAIL_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, RES_EVENT_TYPE, RES_ID, EVENT_TIMESTAMP, OPERATOR_ID, OLD_STATUS, NEW_STATUS, OLD_SHIP_CODE, OLD_SAIL_FROM, OLD_SAIL_TO, NEW_SHIP_CODE, NEW_SAIL_FROM, NEW_SAIL_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_EVENT;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_GUEST
( GUEST_ID, GUEST_SEQN, OCCUPANCY_NUMBER, RES_ID, CLIENT_ID, GUEST_TYPE, AGE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE)
AS SELECT GUEST_ID, GUEST_SEQN, OCCUPANCY_NUMBER, RES_ID, CLIENT_ID, GUEST_TYPE, AGE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_GUEST;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_HEADER
( RES_ID, RES_INIT_DATE, RES_GUEST_COUNT, AGENCY_ID, AGENT_ID, CABIN_CATEGORY, RES_STATUS, PROBABILITY, GROUP_ID, DELEGATE_HEADER_ID, COMMENTS, CRS_STATUS, DPMS_STATUS, TERMINATION_COMPLETED, SHIP_CODE, PACKAGE_TYPE, SAIL_DATE_FROM, SAIL_DATE_TO, REL_DAY_FROM, REL_DAY_TO, SOURCE_CODE, ALT_RES_ID, SEC_AGENCY_ID, OFFICE_CODE, CURRENCY_RATE, CURRENCY_CODE, RH_ENTITY_TYPE, AM_ORDER_ID, CANCELLATION_CASE, OFFICE_LOCATION, CHANNEL_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_ID, RES_INIT_DATE, RES_GUEST_COUNT, AGENCY_ID, AGENT_ID, CABIN_CATEGORY, RES_STATUS, PROBABILITY, GROUP_ID, DELEGATE_HEADER_ID, COMMENTS, CRS_STATUS, DPMS_STATUS, TERMINATION_COMPLETED, SHIP_CODE, PACKAGE_TYPE, SAIL_DATE_FROM, SAIL_DATE_TO, REL_DAY_FROM, REL_DAY_TO, SOURCE_CODE, ALT_RES_ID, SEC_AGENCY_ID, OFFICE_CODE, CURRENCY_RATE, CURRENCY_CODE, RH_ENTITY_TYPE, AM_ORDER_ID, CANCELLATION_CASE, OFFICE_LOCATION, CHANNEL_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_HEADER;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_INVOICE_CANC
( RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, PRICE_PER_UNIT, N_OF_UNITS, PERCENT, AMOUNT, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_INVOICE_CANC;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_INVOICE_ITEM
( RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, PRICE_PER_UNIT, N_OF_UNITS, PERCENT, AMOUNT, INVOICE_ITEM_SUBTYPE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_INVOICE_ITEM_ID, RES_ID, GUEST_ID, RES_PACKAGE_ID, INVOICE_ITEM_TYPE, PRICE_PER_UNIT, N_OF_UNITS, "PERCENT", AMOUNT, INVOICE_ITEM_SUBTYPE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, PRICE_PROGRAM, HOTEL_REQUEST_ID, COMMISSION_PERCENT, SHIP_ROOM_REQUEST_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_INVOICE_ITEM;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_MANUAL_ADJ
( MANUAL_ADJ_ID, RES_ID, GUEST_ID, INVOICE_ITEM_TYPE, AMOUNT, COMMENTS, PRE_PAP_FLAG, IS_RATE_PROTECTION, INVOICE_ITEM_SUBTYPE, IS_ACTIVE, IS_FINAL, REASON, AUTHORIZED_BY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT MANUAL_ADJ_ID, RES_ID, GUEST_ID, INVOICE_ITEM_TYPE, AMOUNT, COMMENTS, PRE_PAP_FLAG, IS_RATE_PROTECTION, INVOICE_ITEM_SUBTYPE, IS_ACTIVE, IS_FINAL, REASON, AUTHORIZED_BY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_MANUAL_ADJ;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_PACKAGE
( RES_PACKAGE_ID, START_DATE, END_DATE, EFFECTIVE_DATE, RES_ID, GUEST_ID, PACKAGE_TYPE, PACKAGE_ID, IS_PRICEABLE, NEEDS_EXTRA_SEAT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_PACKAGE_ID, START_DATE, END_DATE, EFFECTIVE_DATE, RES_ID, GUEST_ID, PACKAGE_TYPE, PACKAGE_ID, IS_PRICEABLE, NEEDS_EXTRA_SEAT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_PACKAGE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_PAYMENT_DUE_ITEM
( RES_PAYMENT_DUE_ITEM_ID, PMNT_DUE_ITEM_TYPE, GUEST_ID, RES_ID, DUE_DATE, GRACE_PERIOD, AMOUNT, EXPIRATION_DATE, PAYMENT_SEQN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_PAYMENT_DUE_ITEM_ID, PMNT_DUE_ITEM_TYPE, GUEST_ID, RES_ID, DUE_DATE, GRACE_PERIOD, AMOUNT, EXPIRATION_DATE, PAYMENT_SEQN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_PAYMENT_DUE_ITEM;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_PROMOTION
( RES_PROMO_ID, RES_ID, GUEST_ID, PROMO_CODE, IS_EXCLUDED, IS_ACTIVE, RES_PACKAGE_ID, IS_MANUAL, DATE_APPLIED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RES_PROMO_ID, RES_ID, GUEST_ID, PROMO_CODE, IS_EXCLUDED, IS_ACTIVE, RES_PACKAGE_ID, IS_MANUAL, DATE_APPLIED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_PROMOTION;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.RES_UNIT_ATTR_REQ
( RECORD_ID, RES_ID, ATTRIBUTE_CODE, STR_VALUE, INT_VALUE, REQUEST_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, RES_ID, ATTRIBUTE_CODE, STR_VALUE, INT_VALUE, REQUEST_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.RES_UNIT_ATTR_REQ;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.SHIP
( SHIP_ID, SHIP_CODE, SHIP_NAME, SHIP_REGISTRY, SHIP_BUILT_DATE, SHIP_CREW_SIZE, SHIP_PAX_CAPACITY, SHIP_CRUISING_SPEED, SHIP_MAX_SPEED, SHIP_LENGTH, SHIP_BEAM, SHIP_DRAUGHT, SHIP_TONNAGE, SHIP_STABILIZER, COMMENTS, IMAGE_ID, CRUISE_LINE_CODE, SHIP_BRAND, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SHIP_ID, SHIP_CODE, SHIP_NAME, SHIP_REGISTRY, SHIP_BUILT_DATE, SHIP_CREW_SIZE, SHIP_PAX_CAPACITY, SHIP_CRUISING_SPEED, SHIP_MAX_SPEED, SHIP_LENGTH, SHIP_BEAM, SHIP_DRAUGHT, SHIP_TONNAGE, SHIP_STABILIZER, COMMENTS, IMAGE_ID, CRUISE_LINE_CODE, SHIP_BRAND, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.SHIP;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.SHIP_CABIN_RESERVE
( RECORD_ID, SHIP_CODE, CABIN_NUMBER, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, RESERVE_TYPE, COMMENTS, GUEST_COUNT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT RECORD_ID, SHIP_CODE, CABIN_NUMBER, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, RESERVE_TYPE, COMMENTS, GUEST_COUNT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.SHIP_CABIN_RESERVE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.SHIP_INVENTORY_ALLOC
( ALLOCATION_ID, ALLOCATION_OWNER_TYPE, ALLOCATION_OWNER_ID, OPERATOR_ID, ALLOCATION_TIMESTAMP, PRIORITY, SHIP_CODE, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, CABIN_CATEGORY, DEPENDS_ON_ID, INVENTORY_REQUEST_TYPE, INVENTORY_RESULT_TYPE, CABIN_NUMBER, PROBABILITY, DECLINE_REASON, RELEASE_TIMESTAMP, OCCUPANCY, PRICE_CATEGORY, ROLLAWAY_BEDS_REQUESTED, RESERVE_TYPE, WTL_OWNER_FLAG, DLGT_RES_ID, IS_DLGT_OBJ, OVERLAY_DAY_FROM, OVERLAY_DAY_TO, IS_SOFT_ASSIGN, IS_FIXED_ASSIGN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT ALLOCATION_ID, ALLOCATION_OWNER_TYPE, ALLOCATION_OWNER_ID, OPERATOR_ID, ALLOCATION_TIMESTAMP, PRIORITY, SHIP_CODE, REL_DAY_FROM, REL_DAY_TO, SAIL_DATE_FROM, SAIL_DATE_TO, CABIN_CATEGORY, DEPENDS_ON_ID, INVENTORY_REQUEST_TYPE, INVENTORY_RESULT_TYPE, CABIN_NUMBER, PROBABILITY, DECLINE_REASON, RELEASE_TIMESTAMP, OCCUPANCY, PRICE_CATEGORY, ROLLAWAY_BEDS_REQUESTED, RESERVE_TYPE, WTL_OWNER_FLAG, DLGT_RES_ID, IS_DLGT_OBJ, OVERLAY_DAY_FROM, OVERLAY_DAY_TO, IS_SOFT_ASSIGN, IS_FIXED_ASSIGN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.SHIP_INVENTORY_ALLOC;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.SP_REQ_ORD_ITEM
( SP_ORD_ITEM_ID, SP_REQ_ID, SP_REQ_CODE, AM_PLACE_CODE, DELIVERY_DATE, DELIVERY_TIME, QUANTITY, COMMENTS, GUEST_FULL_NAME, GUEST_ID, ITEM_VALID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SP_ORD_ITEM_ID, SP_REQ_ID, SP_REQ_CODE, AM_PLACE_CODE, DELIVERY_DATE, DELIVERY_TIME, QUANTITY, COMMENTS, GUEST_FULL_NAME, GUEST_ID, ITEM_VALID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.SP_REQ_ORD_ITEM;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.SP_REQ_ORDER
( SP_REQ_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, ORDER_VALID, AM_BOOKING_TYPE, GROUP_ID, RES_ID, AM_REQ_TYPE, AGENCY_ID, CLIENT_ID, AM_PLACE_CODE, AGENT_ID, DELIVERY_TIME, DISPATCHED_DATE, DISPATCHED_OK, COMMENTS, TERMINATION_COMPLETED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT SP_REQ_ID, ORDER_DATE, ORDER_DESCRIPT, ORD_STATUS_CODE, ORDER_VALID, AM_BOOKING_TYPE, GROUP_ID, RES_ID, AM_REQ_TYPE, AGENCY_ID, CLIENT_ID, AM_PLACE_CODE, AGENT_ID, DELIVERY_TIME, DISPATCHED_DATE, DISPATCHED_OK, COMMENTS, TERMINATION_COMPLETED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.SP_REQ_ORDER;

USE ROLE securityadmin;

GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.ACC_TRANS_DETAIL TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.AGENCY TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.AGENCY_ADDRESS TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.AGENCY_PHONE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.BLL_RM_PRICE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.BLL_RM_PRICE_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CANCELLATION_CASE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CC_CLIENT TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CC_ENTITY_LINK TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CC_PENDING_TRANS TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CLIENT TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.CLIENT_PREFER TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GL_TRANS TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_BOOKING TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.GROUP_EVENT TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.HOUSEHOLD_ADDRESS TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.HOUSEHOLD_PHONE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.PACKAGE_DEFINITION TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.PACKAGE_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_ADDON TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_CHARGEABLE_ACTION TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_COMMISSION_DETAIL TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_EVENT TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_GUEST TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_HEADER TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_INVOICE_CANC TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_INVOICE_ITEM TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_MANUAL_ADJ TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_PACKAGE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_PAYMENT_DUE_ITEM TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_PROMOTION TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.RES_UNIT_ATTR_REQ TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.SHIP TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.SHIP_CABIN_RESERVE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.SHIP_INVENTORY_ALLOC TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.SP_REQ_ORD_ITEM TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON VIEW WARNER_STORE.SEAWARE_APS.SP_REQ_ORDER TO DATABASE ROLE WARNER_STORE.APS_SHARE;

--

USE ROLE dba;

USE SCHEMA warner_raw.seaware_aps;

CREATE VIEW WARNER_BASE.SEAWARE_APS.GROUP_INVOICE_HISTORY
( GROUP_ID, GROUP_UPDATE_ID, INVOICE_ITEM_TYPE, PRICE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT GROUP_ID, GROUP_UPDATE_ID, INVOICE_ITEM_TYPE, PRICE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_INVOICE_HISTORY;

CREATE VIEW WARNER_BASE.SEAWARE_APS.INVOICE_ITEM_GROUP
( INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.INVOICE_ITEM_GROUP;

CREATE VIEW WARNER_BASE.SEAWARE_APS.INVOICE_ITEM_GROUP_TYPE
( INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.INVOICE_ITEM_GROUP_TYPE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.INVOICE_ITEM_SUBTYPE
( INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.INVOICE_ITEM_SUBTYPE;

CREATE VIEW WARNER_BASE.SEAWARE_APS.INVOICE_ITEM_TYPE
( INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.INVOICE_ITEM_TYPE;


CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.GROUP_INVOICE_HISTORY
( GROUP_ID, GROUP_UPDATE_ID, INVOICE_ITEM_TYPE, PRICE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT GROUP_ID, GROUP_UPDATE_ID, INVOICE_ITEM_TYPE, PRICE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.GROUP_INVOICE_HISTORY;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.INVOICE_ITEM_GROUP
( INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.INVOICE_ITEM_GROUP;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.INVOICE_ITEM_GROUP_TYPE
( INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.INVOICE_ITEM_GROUP_TYPE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.INVOICE_ITEM_SUBTYPE
( INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.INVOICE_ITEM_SUBTYPE;

CREATE SECURE VIEW WARNER_STORE.SEAWARE_APS.INVOICE_ITEM_TYPE
( INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE )
AS SELECT INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_BASE.SEAWARE_APS.INVOICE_ITEM_TYPE;

USE ROLE SECURITYADMIN;

GRANT SELECT ON WARNER_STORE.SEAWARE_APS.GROUP_INVOICE_HISTORY TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON WARNER_STORE.SEAWARE_APS.INVOICE_ITEM_GROUP TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON WARNER_STORE.SEAWARE_APS.INVOICE_ITEM_GROUP_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON WARNER_STORE.SEAWARE_APS.INVOICE_ITEM_SUBTYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;
GRANT SELECT ON WARNER_STORE.SEAWARE_APS.INVOICE_ITEM_TYPE TO DATABASE ROLE WARNER_STORE.APS_SHARE;



