use role accountadmin;

select SYSTEM$BEHAVIOR_CHANGE_BUNDLE_STATUS( '2023_08' );
select SYSTEM$DISABLE_BEHAVIOR_CHANGE_BUNDLE( '2023_08' );

-- 08/04/2025

select SYSTEM$SHOW_ACTIVE_BEHAVIOR_CHANGE_BUNDLES();
select SYSTEM$BEHAVIOR_CHANGE_BUNDLE_STATUS( '2025_01' );
select SYSTEM$BEHAVIOR_CHANGE_BUNDLE_STATUS( '2025_02' );

select SYSTEM$ENABLE_BEHAVIOR_CHANGE_BUNDLE( '2025_02' );
select SYSTEM$SHOW_ACTIVE_BEHAVIOR_CHANGE_BUNDLES();

SELECT CURRENT_VERSION();



select SYSTEM$DISABLE_BEHAVIOR_CHANGE_BUNDLE( '2023_08' );
