SHOW ROLES LIKE '%CARAVAN%';

SHOW GRANTS TO ROLE CARAVAN_SALES_PRICING_APPLICATION;

USE ROLE SECURITYADMIN;

--HAVEN_DATA_ENGINEERING.RMS_CARAVAN_PRICER_APP_DEV.

REVOKE ROLE _HAVEN_REVENUE_MANAGEMENT__CARAVAN_PRICING__USAGE FROM ROLE CARAVAN_SALES_PRICING_APPLICATION;
REVOKE USAGE ON STREAMLIT HAVEN_REVENUE_MANAGEMENT.CARAVAN_PRICING.E1XR1DY1U8T0DYM6 FROM ROLE CARAVAN_SALES_PRICING_APPLICATION;

grant role _haven_store_qat__activities__reader to role haven_commercial;
grant role _haven_store_qat__holiday__reader to role haven_commercial;
grant role _haven_store_qat__retail__reader to role haven_commercial;

grant role CARAVAN_SALES_PRICING_APPLICATION to user sarunasjatautis;

show roles like '_haven_data_engineering__%';

--show grants to role CARAVAN_SALES_PRICING_APPLICATION;

revoke role _HAVEN_DATA_ENGINEERING__RMS_CARAVAN_PRICER_APP_DEV__USAGE from role CARAVAN_SALES_PRICING_APPLICATION;

grant role _HAVEN_DATA_ENGINEERING__RMS_CARAVAN_PRICER_APP_DEV__USAGE to role CARAVAN_SALES_PRICING_APPLICATION;