-- HAVEN_RAW.DIG_ARRIVALS.CARAVAN definition

create or replace TABLE HAVEN_RAW.DIG_ARRIVALS.CARAVAN (
	CODE VARCHAR(8000) NOT NULL DEFAULT '',
	NUMBER VARCHAR(8000) NOT NULL DEFAULT '',
	STATUS VARCHAR(255) NOT NULL DEFAULT '',
	CREATED_AT TIMESTAMP_NTZ(6) NOT NULL DEFAULT CAST('0001-01-01 00:00:00' AS TIMESTAMP_NTZ(6)),
	UPDATED_AT TIMESTAMP_NTZ(6) NOT NULL DEFAULT CAST('0001-01-01 00:00:00' AS TIMESTAMP_NTZ(6)),
	ID VARCHAR(50) NOT NULL DEFAULT '',
	ARRIVAL_HOLDER_ID VARCHAR(8000) NOT NULL DEFAULT '',
	primary key (ID)
);