use ROLE dba;

use SCHEMA haven_base.dig_fb_eagleeye;

SELECT get_ddl('view', 'owner_card');
SELECT get_ddl('view', 'ownerscardholderdetails');

SELECT * FROM owner_card LIMIT 100;

use ROLE dba;

create or replace view OWNER_CARD_masked (
	ID,
	FIRST_NAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='last name'),
	LAST_NAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='last name'),
	DOB WITH TAG (HAVEN_MASTER.TAG_ADMIN.DATEOFBIRTH='date of birth'),
	EMAIL WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address'),
	PHONE_NUMBER WITH TAG (HAVEN_MASTER.TAG_ADMIN.TELEPHONE='home'),
	OWNER_ACCOUNT_NUMBER,
	EAGLEEYE_WALLET_ID,
	CREATED_AT,
	UPDATED_AT,
	PARK_CODE,
	CARD_HOLDER_TYPE,
	CARD_STATUS,
	PARENT_EAGLEEYE_WALLET_ID,
	CARD_NUMBER,
	MOBILE_WALLET_URL WITH TAG (HAVEN_MASTER.TAG_ADMIN.FREETEXT='url string'),
	PHYSICAL_CARD_STATUS,
	CARD_TYPE,
	PARENT_CARD_IDENTIFIER,
	EXPIRATION_DATE,
	RECEIVE_EMAIL_MARKETING,
	CARD_IDENTIFIER,
	IS_WALLET_REGISTERED,
	PITCH_NUMBER,
	AREA_CODE,
	ZONE_CODE
) as SELECT "ID", "FIRST_NAME", "LAST_NAME", "DOB", "EMAIL", "PHONE_NUMBER", "OWNER_ACCOUNT_NUMBER", "EAGLEEYE_WALLET_ID", "CREATED_AT", "UPDATED_AT", "PARK_CODE", "CARD_HOLDER_TYPE", "CARD_STATUS", "PARENT_EAGLEEYE_WALLET_ID", "CARD_NUMBER", "MOBILE_WALLET_URL", "PHYSICAL_CARD_STATUS", "CARD_TYPE", "PARENT_CARD_IDENTIFIER", "EXPIRATION_DATE", "RECEIVE_EMAIL_MARKETING", "CARD_IDENTIFIER", "IS_WALLET_REGISTERED", null as "PITCH_NUMBER", null "AREA_CODE", null "ZONE_CODE" FROM "HAVEN_RAW"."DIG_FB_EAGLEEYE"."OWNER_CARD"
where END_DATE is null;

SELECT * FROM OWNERSCARDHOLDERDETAILS LIMIT 100;

create or replace view OWNERSCARDHOLDERDETAILS_masked (
	ID,
	FIRSTNAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='last name'),
	LASTNAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='last name'),
	DOB WITH TAG (HAVEN_MASTER.TAG_ADMIN.DATEOFBIRTH='date of birth'),
	EMAIL WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address'),
	PHONE_NUMBER WITH TAG (HAVEN_MASTER.TAG_ADMIN.TELEPHONE='home'),
	OWNERACCOUNTNUMBER,
	EAGLEEYEWALLETID,
	CREATEDAT,
	UPDATEDAT,
	PARKCODE,
	CARDHOLDERTYPE,
	CARDSTATUS,
	PARENTEAGLEEYEWALLETID,
	CARDNUMBER,
	MOBILEWALLETURL WITH TAG (HAVEN_MASTER.TAG_ADMIN.FREETEXT='url string'),
	PHYSICALCARDSTATUS,
	CARDTYPE,
	PARENTCARDHOLDERDETAILSID,
	EXPIRATIONDATE,
	RECEIVEEMAILMARKETING,
	CARDIDENTIFIER,
	ISWALLETREGISTERED,
	PITCHNUMBER,
	AREACODE,
	ZONECODE
) as SELECT ID, FIRSTNAME, LASTNAME, DOB, EMAIL, PHONENUMBER, OWNERACCOUNTNUMBER, EAGLEEYEWALLETID, CREATEDAT, UPDATEDAT, PARKCODE, CARDHOLDERTYPE, CARDSTATUS, PARENTEAGLEEYEWALLETID, CARDNUMBER, MOBILEWALLETURL, PHYSICALCARDSTATUS, CARDTYPE, PARENTCARDHOLDERDETAILSID, EXPIRATIONDATE, RECEIVEEMAILMARKETING, CARDIDENTIFIER, ISWALLETREGISTERED, PITCHNUMBER, AREACODE, ZONECODE
FROM HAVEN_RAW.DIG_FB_EAGLEEYE.OWNERSCARDHOLDERDETAILS;


	NAMESORT WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='last name'),
	NAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.FULLNAME='full name'),
	ADD_1 WITH TAG (HAVEN_MASTER.TAG_ADMIN.STREET='street name'),
	ADD_2 WITH TAG (HAVEN_MASTER.TAG_ADMIN.TOWN='town'),
	ADD_3 WITH TAG (HAVEN_MASTER.TAG_ADMIN.TOWN='town'),
	ADD_4 WITH TAG (HAVEN_MASTER.TAG_ADMIN.COUNTY='county'),
	POST_CODE WITH TAG (HAVEN_MASTER.TAG_ADMIN.POSTCODE='postcode'),
	NUMDAY WITH TAG (HAVEN_MASTER.TAG_ADMIN.TELEPHONE='work'),
	NUMEVE WITH TAG (HAVEN_MASTER.TAG_ADMIN.TELEPHONE='home'),
	NUMMOB WITH TAG (HAVEN_MASTER.TAG_ADMIN.TELEPHONE='mobile'),
	EMAIL WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address'),
	SALUTATION WITH TAG (HAVEN_MASTER.TAG_ADMIN.TITLE='title'),
FORENAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.FIRSTNAME='first name'),
	SURNAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.LASTNAME='last name'),
	PREFERRED_FORENAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.FIRSTNAME='first name'),
	MIDDLE_INITIAL WITH TAG (HAVEN_MASTER.TAG_ADMIN.MIDDLENAME='middle initial'),
DOB WITH TAG (HAVEN_MASTER.TAG_ADMIN.DATEOFBIRTH='date of birth'),
	WEB_EMAIL WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address'),

	
use SCHEMA haven_base.dig_team_card;

SELECT get_ddl('view', 'teamcard');

SELECT * FROM teamcard LIMIT 100;

create or replace view TEAMCARD_masked(
	SSOID,
	PARKCODE,
	EMAIL WITH TAG (HAVEN_MASTER.TAG_ADMIN.EMAIL='email_address'),
	FULLNAME WITH TAG (HAVEN_MASTER.TAG_ADMIN.FULLNAME='full name'),
	COMPANY,
	PATHTOIMAGE,
	CREATEDAT,
	UPDATEDAT,
	DELETEDAT,
	EAGLEEYEWALLETID,
	JOBTITLE,
	CREATEDBY,
	UPDATEDBY,
	DELETEDBY,
	FILE_MODIFICATION_TIME,
	END_DATE
) as SELECT SSOID, PARKCODE, EMAIL, FULLNAME, COMPANY, PATHTOIMAGE, CREATEDAT, UPDATEDAT, DELETEDAT, EAGLEEYEWALLETID, JOBTITLE, CREATEDBY, UPDATEDBY, DELETEDBY, FILE_MODIFICATION_TIME, END_DATE
FROM HAVEN_RAW.DIG_TEAM_CARD.TEAMCARD;


use ROLE haven_data_engineering;
USE WAREHOUSE HAVEN_DATA_ENGINEERING_WAREHOUSE_XSMALL;

SELECT current_role();

SELECT * FROM haven_base.dig_team_card.teamcard_masked LIMIT 100;
SELECT * FROM haven_base.dig_fb_eagleeye.owner_card_masked LIMIT 100;
SELECT * FROM haven_base.dig_fb_eagleeye.OWNERSCARDHOLDERDETAILS_masked LIMIT 100;

USE ROLE HAVEN_DBT_DEVELOPMENT;
USE WAREHOUSE HAVEN_DBT_DEVELOPMENT_WAREHOUSE_XSMALL;

SELECT * FROM haven_base.dig_team_card.teamcard_masked LIMIT 100;
SELECT * FROM haven_base.dig_fb_eagleeye.owner_card_masked LIMIT 100;
SELECT * FROM haven_base.dig_fb_eagleeye.OWNERSCARDHOLDERDETAILS_masked LIMIT 100;

