USE ROLE securityadmin;

GRANT ROLE _haven_raw__tiktok_ads__creator TO ROLE haven_etleap_dataload;

USE ROLE haven_stitch_integration;

SHOW WAREHOUSES;

USE WAREHOUSE bourne_stitch_warehouse_xsmall;

USE SCHEMA haven_raw.tiktok_ads;

SHOW TABLES;

ALTER TABLE ADGROUPS RENAME TO _ADGROUPS_STITCH_14012025;
ALTER TABLE ADS RENAME TO _ADS_STITCH_14012025;
ALTER TABLE AD_INSIGHTS RENAME TO _AD_INSIGHTS_STITCH_14012025;
ALTER TABLE AD_INSIGHTS_BY_AGE_AND_GENDER RENAME TO _AD_INSIGHTS_BY_AGE_AND_GENDER_STITCH_14012025;
ALTER TABLE AD_INSIGHTS_BY_COUNTRY RENAME TO _AD_INSIGHTS_BY_COUNTRY_STITCH_14012025;
ALTER TABLE AD_INSIGHTS_BY_PLATFORM RENAME TO _AD_INSIGHTS_BY_PLATFORM_STITCH_14012025;
ALTER TABLE CAMPAIGNS RENAME TO _CAMPAIGNS_STITCH_14012025;
ALTER TABLE CAMPAIGN_INSIGHTS_BY_PROVINCE RENAME TO _CAMPAIGN_INSIGHTS_BY_PROVINCE_STITCH_14012025;
ALTER TABLE _SDC_REJECTED RENAME TO _SDC_REJECTED_STITCH_14012025;

USE ROLE haven_etleap_dataload;

SHOW WAREHOUSES;

USE WAREHOUSE HAVEN_ETLEAP_DATALOAD_WAREHOUSE_XSMALL;

create OR REPLACE table haven_raw.tiktok_ads.AD as select * from haven_raw.tiktok_etleap.AD;
create OR REPLACE table haven_raw.tiktok_ads.ADVERTISER as select * from haven_raw.tiktok_etleap.ADVERTISER;
create OR REPLACE table haven_raw.tiktok_ads.AD_GROUP as select * from haven_raw.tiktok_etleap.AD_GROUP;
create OR REPLACE table haven_raw.tiktok_ads.CAMPAIGN as select * from haven_raw.tiktok_etleap.CAMPAIGN;
create OR REPLACE table haven_raw.tiktok_ads.INSIGHTS_BY_AD as select * from haven_raw.tiktok_etleap.INSIGHTS_BY_AD;
create OR REPLACE table haven_raw.tiktok_ads."_etleap" as select * from haven_raw.tiktok_etleap."_etleap";



USE ROLE dba;

DROP table haven_raw.tiktok_ads.AD;
DROP table haven_raw.tiktok_ads.ADVERTISER;
DROP table haven_raw.tiktok_ads.AD_GROUP;
DROP table haven_raw.tiktok_ads.CAMPAIGN;
DROP table haven_raw.tiktok_ads.INSIGHTS_BY_AD;
DROP table haven_raw.tiktok_ads."_etleap";

ALTER table haven_raw.tiktok_ads.AD RENAME TO haven_raw.tiktok_ads.AD_etleap_16012025 ;

ALTER table haven_raw.tiktok_ads.ADVERTISER RENAME TO haven_raw.tiktok_ads.ADVERTISER_etleap_16012025 ;
ALTER table haven_raw.tiktok_ads.AD_GROUP rename TO haven_raw.tiktok_ads.AD_GROUP_etleap_16012025;

ALTER table haven_raw.tiktok_ads.CAMPAIGN rename TO haven_raw.tiktok_ads.CAMPAIGN_etleap_16012025 ;
ALTER table haven_raw.tiktok_ads.INSIGHTS_BY_AD rename TO haven_raw.tiktok_ads.INSIGHTS_BY_AD_etleap_16012025;

SHOW TABLES;

SELECT count(*) FROM haven_raw.tiktok_ads."_etleap";


SELECT MAX(MODIFY_TIME) FROM haven_raw.tiktok_ads.AD LIMIT 20;
SELECT * FROM haven_raw.tiktok_ads.AD_GROUP LIMIT 10;

USE ROLE dba;

USE WAREHOUSE dba_wh;

USE SCHEMA haven_base.tiktok_ads;

SHOW views;

DROP VIEW ADGROUPS;
DROP VIEW ADS;
DROP VIEW AD_INSIGHTS;
DROP VIEW AD_INSIGHTS_BY_AGE_AND_GENDER;
DROP VIEW AD_INSIGHTS_BY_COUNTRY;
DROP VIEW AD_INSIGHTS_BY_PLATFORM;
DROP VIEW CAMPAIGNS;
DROP VIEW CAMPAIGN_INSIGHTS_BY_PROVINCE;

CREATE view haven_base.tiktok_ads.AD
( ADVERTISER_ID, CAMPAIGN_ID, CAMPAIGN_NAME, ADGROUP_ID, ADGROUP_NAME, AD_ID, AD_NAME, TRACKING_PIXEL_ID, IDENTITY_ID, IDENTITY_TYPE, IDENTITY_AUTHORIZED_BC_ID, CALL_TO_ACTION, CALL_TO_ACTION_ID, CARD_ID, SECONDARY_STATUS, OPERATION_STATUS, IS_ACO, IMAGE_IDS, AD_FORMAT, AD_TEXT, AD_TEXTS, VIDEO_ID, TIKTOK_ITEM_ID, APP_NAME, LANDING_PAGE_URL, LANDING_PAGE_URLS, DISPLAY_NAME, PROFILE_IMAGE_URL, IMPRESSION_TRACKING_URL, CLICK_TRACKING_URL, DEEPLINK, DEEPLINK_TYPE, FALLBACK_TYPE, PLAYABLE_URL, PAGE_ID, VAST_MOAT_ENABLED, CREATIVE_AUTHORIZED, IS_NEW_STRUCTURE, CREATE_TIME, MODIFY_TIME, SHOPPING_ADS_FALLBACK_TYPE, SHOPPING_ADS__DEEPLINK_TYPE, SHOPPING_ADS_VIDEO_PACKAGE_ID, PROMOTIONAL_MUSIC_DISABLED, DARK_POST_STATUS, BRANDED_CONTENT_DISABLED, ITEM_DUET_STATUS, ITEM_STITCH_STATUS, BRAND_SAFETY_POSTBID_PARTNER, PRODUCT_SPECIFIC_TYPE, CATALOG_ID, ITEM_GROUP_IDS, PRODUCT_SET_ID, SKU_IDS, DYNAMIC_FORMAT, VERTICAL_VIDEO_STRATEGY, DYNAMIC_DESTINATION, OPTIMIZATION_EVENT, VIEWABILITY_VAST_URL, CAROUSEL_IMAGE_LABELS, CREATIVE_TYPE, AVATAR_ICON_WEB_URI, VIEWABILITY_POSTBID_PARTNER, AD_REF_PIXEL_ID, MUSIC_ID, BRAND_SAFETY_VAST_URL, AIGC_DISCLOSURE_TYPE )
AS SELECT ADVERTISER_ID, CAMPAIGN_ID, CAMPAIGN_NAME, ADGROUP_ID, ADGROUP_NAME, AD_ID, AD_NAME, TRACKING_PIXEL_ID, IDENTITY_ID, IDENTITY_TYPE, IDENTITY_AUTHORIZED_BC_ID, CALL_TO_ACTION, CALL_TO_ACTION_ID, CARD_ID, SECONDARY_STATUS, OPERATION_STATUS, IS_ACO, IMAGE_IDS, AD_FORMAT, AD_TEXT, AD_TEXTS, VIDEO_ID, TIKTOK_ITEM_ID, APP_NAME, LANDING_PAGE_URL, LANDING_PAGE_URLS, DISPLAY_NAME, PROFILE_IMAGE_URL, IMPRESSION_TRACKING_URL, CLICK_TRACKING_URL, DEEPLINK, DEEPLINK_TYPE, FALLBACK_TYPE, PLAYABLE_URL, PAGE_ID, VAST_MOAT_ENABLED, CREATIVE_AUTHORIZED, IS_NEW_STRUCTURE, CREATE_TIME, MODIFY_TIME, SHOPPING_ADS_FALLBACK_TYPE, SHOPPING_ADS__DEEPLINK_TYPE, SHOPPING_ADS_VIDEO_PACKAGE_ID, PROMOTIONAL_MUSIC_DISABLED, DARK_POST_STATUS, BRANDED_CONTENT_DISABLED, ITEM_DUET_STATUS, ITEM_STITCH_STATUS, BRAND_SAFETY_POSTBID_PARTNER, PRODUCT_SPECIFIC_TYPE, CATALOG_ID, ITEM_GROUP_IDS, PRODUCT_SET_ID, SKU_IDS, DYNAMIC_FORMAT, VERTICAL_VIDEO_STRATEGY, DYNAMIC_DESTINATION, OPTIMIZATION_EVENT, VIEWABILITY_VAST_URL, CAROUSEL_IMAGE_LABELS, CREATIVE_TYPE, AVATAR_ICON_WEB_URI, VIEWABILITY_POSTBID_PARTNER, AD_REF_PIXEL_ID, MUSIC_ID, BRAND_SAFETY_VAST_URL, AIGC_DISCLOSURE_TYPE
FROM haven_raw.tiktok_ads.AD;

CREATE view haven_base.tiktok_ads.AD_GROUP
( ADVERTISER_ID, CAMPAIGN_ID, ADGROUP_ID, ADGROUP_NAME, SPLIT_TEST_GROUP_ID, SPLIT_TEST_STATUS, SHARE_DISABLED, PLACEMENT_TYPE, PLACEMENTS, INVENTORY_FILTER_ENABLED, COMMENT_DISABLED, APP_ID, PROMOTION_TYPE, STORE_ID, STORE_AUTHORIZED_BC_ID, IDENTITY_ID, IDENTITY_TYPE, IDENTITY_AUTHORIZED_BC_ID, APP_DOWNLOAD_URL, PIXEL_ID, OPTIMIZATION_EVENT, SECONDARY_OPTIMIZATION_EVENT, CREATIVE_MATERIAL_MODE, AUDIENCE_IDS, AUDIENCE_TYPE, LOCATION_IDS, IS_HFSS, INTEREST_CATEGORY_IDS, INTEREST_KEYWORD_IDS, AGE_GROUPS, GENDER, LANGUAGES, OPERATING_SYSTEMS, NETWORK_TYPES, MIN_ANDROID_VERSION, MIN_IOS_VERSION, IOS14_TARGETING, DEVICE_MODEL_IDS, HOUSEHOLD_INCOME, BUDGET_MODE, BUDGET, SCHEDULED_BUDGET, SCHEDULE_TYPE, SCHEDULE_START_TIME, SCHEDULE_END_TIME, DAYPARTING, BID_DISPLAY_MODE, CPV_VIDEO_DURATION, CONVERSION_WINDOW, PACING, BILLING_EVENT, SKIP_LEARNING_PHASE, BID_TYPE, BID_PRICE, CONVERSION_BID_PRICE, DEEP_BID_TYPE, DEEP_CPA_BID, NEXT_DAY_RETENTION, SECONDARY_STATUS, OPERATION_STATUS, FREQUENCY, FREQUENCY_SCHEDULE, STATISTIC_TYPE, CARRIER_IDS, VIDEO_DOWNLOAD_DISABLED, BLOCKED_PANGLE_APP_IDS, ACTIONS, RF_PURCHASED_TYPE, PURCHASED_IMPRESSION, PURCHASED_REACH, RF_ESTIMATED_CPR, RF_ESTIMATED_FREQUENCY, INCLUDED_PANGLE_AUDIENCE_PACKAGE_IDS, EXCLUDED_PANGLE_AUDIENCE_PACKAGE_IDS, IS_NEW_STRUCTURE, CATALOG_ID, PRODUCT_SET_ID, CATALOG_AUTHORIZED_BC_ID, INCLUDED_CUSTOM_ACTIONS, EXCLUDED_CUSTOM_ACTIONS, SHOPPING_ADS_RETARGETING_TYPE, BRAND_SAFETY_TYPE, BRAND_SAFETY_PARTNER, PROMOTION_WEBSITE_TYPE, IOS14_QUOTA_TYPE, ROAS_BID, AUTO_TARGETING_ENABLED, TARGETING_EXPANSION, ADGROUP_APP_PROFILE_PAGE_STATE, SHOPPING_ADS_TYPE, PRODUCT_SOURCE, FEED_TYPE, DELIVERY_MODE, SCHEDULE_INFOS, CONTEXTUAL_TAG_IDS, PURCHASE_INTENTION_KEYWORD_IDS, SEARCH_RESULT_ENABLED, CATEGORY_EXCLUSION_IDS, OPTIMIZATION_GOAL, DEVICE_PRICE_RANGES, MODIFY_TIME, CATEGORY_ID, ATTRIBUTION_EVENT_COUNT, ISP_IDS, KEYWORDS, CLICK_ATTRIBUTION_WINDOW, VBO_WINDOW, EXCLUDED_AUDIENCE_IDS, APP_TYPE, CREATE_TIME, IS_SMART_PERFORMANCE_CAMPAIGN, SMART_INTEREST_BEHAVIOR_ENABLED, SPENDING_POWER, VIEW_ATTRIBUTION_WINDOW, SMART_AUDIENCE_ENABLED, CAMPAIGN_NAME, ZIPCODE_IDS, VERTICAL_SENSITIVITY_ID, TIKTOK_SUBPLACEMENTS, DEEP_FUNNEL_EVENT_SOURCE, DEEP_FUNNEL_OPTIMIZATION_EVENT, DEEP_FUNNEL_OPTIMIZATION_STATUS, DEEP_FUNNEL_EVENT_SOURCE_ID )
AS SELECT ADVERTISER_ID, CAMPAIGN_ID, ADGROUP_ID, ADGROUP_NAME, SPLIT_TEST_GROUP_ID, SPLIT_TEST_STATUS, SHARE_DISABLED, PLACEMENT_TYPE, PLACEMENTS, INVENTORY_FILTER_ENABLED, COMMENT_DISABLED, APP_ID, PROMOTION_TYPE, STORE_ID, STORE_AUTHORIZED_BC_ID, IDENTITY_ID, IDENTITY_TYPE, IDENTITY_AUTHORIZED_BC_ID, APP_DOWNLOAD_URL, PIXEL_ID, OPTIMIZATION_EVENT, SECONDARY_OPTIMIZATION_EVENT, CREATIVE_MATERIAL_MODE, AUDIENCE_IDS, AUDIENCE_TYPE, LOCATION_IDS, IS_HFSS, INTEREST_CATEGORY_IDS, INTEREST_KEYWORD_IDS, AGE_GROUPS, GENDER, LANGUAGES, OPERATING_SYSTEMS, NETWORK_TYPES, MIN_ANDROID_VERSION, MIN_IOS_VERSION, IOS14_TARGETING, DEVICE_MODEL_IDS, HOUSEHOLD_INCOME, BUDGET_MODE, BUDGET, SCHEDULED_BUDGET, SCHEDULE_TYPE, SCHEDULE_START_TIME, SCHEDULE_END_TIME, DAYPARTING, BID_DISPLAY_MODE, CPV_VIDEO_DURATION, CONVERSION_WINDOW, PACING, BILLING_EVENT, SKIP_LEARNING_PHASE, BID_TYPE, BID_PRICE, CONVERSION_BID_PRICE, DEEP_BID_TYPE, DEEP_CPA_BID, NEXT_DAY_RETENTION, SECONDARY_STATUS, OPERATION_STATUS, FREQUENCY, FREQUENCY_SCHEDULE, STATISTIC_TYPE, CARRIER_IDS, VIDEO_DOWNLOAD_DISABLED, BLOCKED_PANGLE_APP_IDS, ACTIONS, RF_PURCHASED_TYPE, PURCHASED_IMPRESSION, PURCHASED_REACH, RF_ESTIMATED_CPR, RF_ESTIMATED_FREQUENCY, INCLUDED_PANGLE_AUDIENCE_PACKAGE_IDS, EXCLUDED_PANGLE_AUDIENCE_PACKAGE_IDS, IS_NEW_STRUCTURE, CATALOG_ID, PRODUCT_SET_ID, CATALOG_AUTHORIZED_BC_ID, INCLUDED_CUSTOM_ACTIONS, EXCLUDED_CUSTOM_ACTIONS, SHOPPING_ADS_RETARGETING_TYPE, BRAND_SAFETY_TYPE, BRAND_SAFETY_PARTNER, PROMOTION_WEBSITE_TYPE, IOS14_QUOTA_TYPE, ROAS_BID, AUTO_TARGETING_ENABLED, TARGETING_EXPANSION, ADGROUP_APP_PROFILE_PAGE_STATE, SHOPPING_ADS_TYPE, PRODUCT_SOURCE, FEED_TYPE, DELIVERY_MODE, SCHEDULE_INFOS, CONTEXTUAL_TAG_IDS, PURCHASE_INTENTION_KEYWORD_IDS, SEARCH_RESULT_ENABLED, CATEGORY_EXCLUSION_IDS, OPTIMIZATION_GOAL, DEVICE_PRICE_RANGES, MODIFY_TIME, CATEGORY_ID, ATTRIBUTION_EVENT_COUNT, ISP_IDS, KEYWORDS, CLICK_ATTRIBUTION_WINDOW, VBO_WINDOW, EXCLUDED_AUDIENCE_IDS, APP_TYPE, CREATE_TIME, IS_SMART_PERFORMANCE_CAMPAIGN, SMART_INTEREST_BEHAVIOR_ENABLED, SPENDING_POWER, VIEW_ATTRIBUTION_WINDOW, SMART_AUDIENCE_ENABLED, CAMPAIGN_NAME, ZIPCODE_IDS, VERTICAL_SENSITIVITY_ID, TIKTOK_SUBPLACEMENTS, DEEP_FUNNEL_EVENT_SOURCE, DEEP_FUNNEL_OPTIMIZATION_EVENT, DEEP_FUNNEL_OPTIMIZATION_STATUS, DEEP_FUNNEL_EVENT_SOURCE_ID
FROM haven_raw.tiktok_ads.AD_GROUP;

CREATE view haven_base.tiktok_ads.ADVERTISER
( LICENSE_CITY, COMPANY, LICENSE_URL, REJECTION_REASON, TELEPHONE_NUMBER, PROMOTION_CENTER_CITY, DISPLAY_TIMEZONE, CREATE_TIME, DESCRIPTION, EMAIL, CONTACTER, "NAME", CURRENCY, COUNTRY, "ROLE", ADDRESS, CELLPHONE_NUMBER, INDUSTRY, ADVERTISER_ACCOUNT_TYPE, LICENSE_NO, ADVERTISER_ID, BRAND, BALANCE, PROMOTION_AREA, LICENSE_PROVINCE, "LANGUAGE", TIMEZONE, PROMOTION_CENTER_PROVINCE, STATUS, OWNER_BC_ID ) 
AS SELECT LICENSE_CITY, COMPANY, LICENSE_URL, REJECTION_REASON, TELEPHONE_NUMBER, PROMOTION_CENTER_CITY, DISPLAY_TIMEZONE, CREATE_TIME, DESCRIPTION, EMAIL, CONTACTER, "NAME", CURRENCY, COUNTRY, "ROLE", ADDRESS, CELLPHONE_NUMBER, INDUSTRY, ADVERTISER_ACCOUNT_TYPE, LICENSE_NO, ADVERTISER_ID, BRAND, BALANCE, PROMOTION_AREA, LICENSE_PROVINCE, "LANGUAGE", TIMEZONE, PROMOTION_CENTER_PROVINCE, STATUS, OWNER_BC_ID
FROM haven_raw.tiktok_ads.ADVERTISER;

CREATE view haven_base.tiktok_ads.CAMPAIGN 
( CAMPAIGN_ID, APP_ID, CAMPAIGN_NAME, CAMPAIGN_TYPE, IS_SMART_PERFORMANCE_CAMPAIGN, ADVERTISER_ID, BUDGET, BUDGET_MODE, SECONDARY_STATUS, OPERATION_STATUS, OBJECTIVE, OBJECTIVE_TYPE, APP_PROMOTION_TYPE, BUDGET_OPTIMIZE_ON, BID_TYPE, DEEP_BID_TYPE, ROAS_BID, OPTIMIZE_GOAL, IS_NEW_STRUCTURE, CREATE_TIME, MODIFY_TIME, CAMPAIGN_APP_PROFILE_PAGE_TYPE, SPECIAL_INDUSTRIES, RF_CAMPAIGN_TYPE, RTA_PRODUCT_SELECTION_ENABLED, CATALOG_ENABLED, IS_SEARCH_CAMPAIGN, IS_ADVANCED_DEDICATED_CAMPAIGN, RTA_ID, OPTIMIZATION_GOAL )
AS SELECT CAMPAIGN_ID, APP_ID, CAMPAIGN_NAME, CAMPAIGN_TYPE, IS_SMART_PERFORMANCE_CAMPAIGN, ADVERTISER_ID, BUDGET, BUDGET_MODE, SECONDARY_STATUS, OPERATION_STATUS, OBJECTIVE, OBJECTIVE_TYPE, APP_PROMOTION_TYPE, BUDGET_OPTIMIZE_ON, BID_TYPE, DEEP_BID_TYPE, ROAS_BID, OPTIMIZE_GOAL, IS_NEW_STRUCTURE, CREATE_TIME, MODIFY_TIME, CAMPAIGN_APP_PROFILE_PAGE_TYPE, SPECIAL_INDUSTRIES, RF_CAMPAIGN_TYPE, RTA_PRODUCT_SELECTION_ENABLED, CATALOG_ENABLED, IS_SEARCH_CAMPAIGN, IS_ADVANCED_DEDICATED_CAMPAIGN, RTA_ID, OPTIMIZATION_GOAL
FROM haven_raw.tiktok_ads.CAMPAIGN;

CREATE view haven_base.tiktok_ads.INSIGHTS_BY_AD
( DIMENSIONS_DATE, AD_ID, CAMPAIGN_ID, ADGROUP_ID, METRICS_GROSS_IMPRESSIONS, METRICS_IMPRESSIONS, METRICS_CLICKS, METRICS_COST, METRICS_AVERAGE_PLAY_TIME_PER_VIDEO_VIEW, METRICS_BID, METRICS_BID_STRATEGY, METRICS_AD_GROUP_BUDGET, METRICS_CONVERSIONS, METRICS_PAID_LIKES, METRICS_PAID_PROFILE_VISITS, METRICS_REACH, METRICS_RESULTS, METRICS_PAID_SHARES, METRICS_OPTIMIZATION_GOAL, METRICS_VIDEO_VIEWS, METRICS_VIDEO_VIEWS_AT_25PCT, METRICS_VIDEO_VIEWS_AT_50PCT, METRICS_VIDEO_VIEWS_AT_75PCT, METRICS_VIDEO_VIEWS_AT_100PCT, METRICS_2_SECOND_VIDEO_VIEWS, METRICS_6_SECOND_VIDEO_VIEWS )
AS SELECT DIMENSIONS_DATE, AD_ID, CAMPAIGN_ID, ADGROUP_ID, METRICS_GROSS_IMPRESSIONS, METRICS_IMPRESSIONS, METRICS_CLICKS, METRICS_COST, METRICS_AVERAGE_PLAY_TIME_PER_VIDEO_VIEW, METRICS_BID, METRICS_BID_STRATEGY, METRICS_AD_GROUP_BUDGET, METRICS_CONVERSIONS, METRICS_PAID_LIKES, METRICS_PAID_PROFILE_VISITS, METRICS_REACH, METRICS_RESULTS, METRICS_PAID_SHARES, METRICS_OPTIMIZATION_GOAL, METRICS_VIDEO_VIEWS, METRICS_VIDEO_VIEWS_AT_25PCT, METRICS_VIDEO_VIEWS_AT_50PCT, METRICS_VIDEO_VIEWS_AT_75PCT, METRICS_VIDEO_VIEWS_AT_100PCT, METRICS_2_SECOND_VIDEO_VIEWS, METRICS_6_SECOND_VIDEO_VIEWS
FROM haven_raw.tiktok_ads.INSIGHTS_BY_AD;



-- 16/01/2025

USE SCHEMA haven_raw.tiktok_etleap;

USE ROLE dba;

SHOW TABLES;

SELECT table_id,
  table_name,
  table_schema,
  table_catalog,
  created,
  deleted,
  comment
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
WHERE table_catalog = 'HAVEN_RAW'
AND table_schema = 'TIKTOK_ETLEAP'
AND table_name = 'AD'
AND deleted IS NOT NULL
ORDER BY deleted;

UNDROP TABLE IDENTIFIER(17191509);

SHOW TABLES;

USE ROLE haven_etleap_dataload;
USE SCHEMA haven_raw.tiktok_ads;

SELECT count(*) FROM insights_by_ad;

SELECT count(*) FROM insights_by_ad AT(TIMESTAMP => 'Thu, 16 Jan 2025 13:29:00'::timestamp);

SELECT max(dimensions_date) FROM insights_by_ad;

