USE ROLE dba;
CREATE OR REPLACE VIEW haven_store.commercial.TRANSACTIONS_BY_DATE AS
SELECT "DATE" AS trans_date, FULLVISITORID, VISITID, VISITSTARTTIME, HIT_TIME, TRANSACTIONID, TRANSACTIONREVENUE, HOL_BOOKING_ID, TIMESTAMP_RAW, BUSINESS_AREA, FRIENDLY_PAGE_NAME, PARK_NAME, PARK_CODE, HOLIDAY_PACKAGE, DURATION, ARRIVAL_DATE, GUEST_NEW_REPEAT, GUESTS_ADULTS, GUESTS_CHILDREN, GUESTS_INFANTS, GUESTS_DOGS, 
GUESTS_TOTAL, GUEST_TYPE, ACT_CATEGORY, ACT_NAME, ACT_DATE, ACT_TIME
FROM HAVEN_RAW.BIGQUERY.HAV001_TABLES04_TRANSACTIONS_BY_DATE;

CREATE OR REPLACE VIEW haven_store.commercial.sessions_BY_DATE AS
SELECT "DATE" AS session_date, FULLVISITORID, VISITID, VISITNUMBER, VISITSTARTTIME, PAGEVIEWS, TIMEONSITE, BOUNCES, "TRANSACTIONS" AS session_transactions, TOTALTRANSACTIONREVENUE, NEWVISITS, ISTRUEDIRECT, REFERRALPATH, "SOURCE" AS session_source, MEDIUM, CAMPAIGN, KEYWORD, LANDING_PAGE, DEVICECATEGORY, BROWSER, BROWSERSIZE, BROWSERVERSION, OPERATINGSYSTEM, OPERATINGSYSTEMVERSION, COUNTRY, LATITUDE, LONGITUDE, OWNERSHIP_FLAG, TOURING_FLAG, TRANSACTIONAL_FLAG, SEARCH_FLAG_HOLS, SEARCH_FLAG_OWNERSHIP, SEARCH_FLAG_TOURING, HOME_DETAILS_FLAG_OWNERSHIP
FROM HAVEN_RAW.BIGQUERY.HAV001_TABLES01_SESSIONS_BY_DATE;

SELECT session_date, count(*) FROM haven_store.commercial.sessions_BY_DATE
GROUP BY 1 ORDER BY 1 desc;

SHOW STAGES;