USE schema haven_store_uat.trooper;

USE ROLE haven_dbt_transform_uat;

SHOW WAREHOUSES;
USE WAREHOUSE haven_dbt_transform_uat_xsmall;

USE ROLE haven_batch_dataload;

SHOW WAREHOUSES;
USE WAREHOUSE bourne_batch_dataload_xsmall;

USE ROLE sysadmin;
USE schema haven_store_uat.trooper;
DROP TABLE haven_store_uat.trooper.cancellations_currentseason;
DROP TABLE haven_store_uat.trooper.grade_mapping;

USE ROLE dba;

CREATE view HAVEN_STORE_UAT.TROOPER.CANCELLATIONS_CURRENTSEASON
( REF, LOAD_REF, RES_ID, BOOK_DATE, ARRIVAL_DATE, PARK_CODE, PRODUCT, CHANNEL, AGENCY_TYPE, REFERRAL_SOURCE, CANCELLATION_CASE, REASON_IS_CORONA, COMMENT_HAS_CORONA, REFUND_TO_CLIENT_BANK, CLIENT_BANK_SINCE_MARCH, CLIENT_BANK_BALANCE, REFUND_CASH, CASH_SINCE_MARCH, CASH_SINCE_MARCH_PENDING, REFUND_TO_AGENCY_BANK, AGENCY_BANK_SINCE_MARCH, CANCELLATION_DATE, PERFORMER, "LOCATION", HAS_HPP, PRE_CANCELLATION_BILLINGS, FLAGGED_AS_REFUND, REFUND_REQUEST_DATE, FLAGGED_AS_ADJUST, ADJUST_REQUEST_DATE, CHARGES, PAID, CHARGES_PAID, PENDING_REFUNDS, CLIENT_ID, ZENDATA_CHOICE, REBOOKED, REBOOKED_RES_ID, ZENDATA_CHOICE_DATE, REFUND_MANUAL, REFUND_AUTO, CASH_PAID, ALT_RES_ID, REFUND_PROCESSED_DATE, GROUP_ID, RECEIVED_CASH, RECEIVED_CHEQUES, RECEIVED_CARD, GROUP_FUNDS_REST, GROUP_TO_AGENCY_BANK, GROUP_FUNDS_OUT, LAST_TRANSFER_TO_CLIENT_BANK, CANCELLATION_REFUND_REQUEST_DATE, SUN_REQUEST_DATE, SUN_REQUEST_ACTION, GROUP_CHARGES, TERMS_CONFIRMED, PURE_CASH_REFUNDS, FIRST_ZENDESK_CHOICE, FIRST_ZENDESK_DATE, EMAIL_ADDRESS, MOBILE_NUMBER, HIDEAWAY_TYPE, HAVEN10, PRE_CANCELLATION_COMMISSION, GROUP_FULLY_PAID, POOL10, PASSES_PRESENT, PASSES_ADDED, SUB_PRODUCT, ACTIVITY_COUNT, WHOSE_DEBT, AGENCY_NAME, TRANSFER_YN )
AS SELECT REF, LOAD_REF, RES_ID, BOOK_DATE, ARRIVAL_DATE, PARK_CODE, PRODUCT, CHANNEL, AGENCY_TYPE, REFERRAL_SOURCE, CANCELLATION_CASE, REASON_IS_CORONA, COMMENT_HAS_CORONA, REFUND_TO_CLIENT_BANK, CLIENT_BANK_SINCE_MARCH, CLIENT_BANK_BALANCE, REFUND_CASH, CASH_SINCE_MARCH, CASH_SINCE_MARCH_PENDING, REFUND_TO_AGENCY_BANK, AGENCY_BANK_SINCE_MARCH, CANCELLATION_DATE, PERFORMER, "LOCATION", HAS_HPP, PRE_CANCELLATION_BILLINGS, FLAGGED_AS_REFUND, REFUND_REQUEST_DATE, FLAGGED_AS_ADJUST, ADJUST_REQUEST_DATE, CHARGES, PAID, CHARGES_PAID, PENDING_REFUNDS, CLIENT_ID, ZENDATA_CHOICE, REBOOKED, REBOOKED_RES_ID, ZENDATA_CHOICE_DATE, REFUND_MANUAL, REFUND_AUTO, CASH_PAID, ALT_RES_ID, REFUND_PROCESSED_DATE, GROUP_ID, RECEIVED_CASH, RECEIVED_CHEQUES, RECEIVED_CARD, GROUP_FUNDS_REST, GROUP_TO_AGENCY_BANK, GROUP_FUNDS_OUT, LAST_TRANSFER_TO_CLIENT_BANK, CANCELLATION_REFUND_REQUEST_DATE, SUN_REQUEST_DATE, SUN_REQUEST_ACTION, GROUP_CHARGES, TERMS_CONFIRMED, PURE_CASH_REFUNDS, FIRST_ZENDESK_CHOICE, FIRST_ZENDESK_DATE, EMAIL_ADDRESS, MOBILE_NUMBER, HIDEAWAY_TYPE, HAVEN10, PRE_CANCELLATION_COMMISSION, GROUP_FULLY_PAID, POOL10, PASSES_PRESENT, PASSES_ADDED, SUB_PRODUCT, ACTIVITY_COUNT, WHOSE_DEBT, AGENCY_NAME, TRANSFER_YN
FROM HAVEN_STORE.TROOPER.CANCELLATIONS_CURRENTSEASON;

CREATE VIEW HAVEN_STORE_UAT.TROOPER.GRADE_MAPPING
( REF, PARK, NEW_GRADE, OLD_GRADE, ATTRIBUTE)
AS SELECT REF, PARK, NEW_GRADE, OLD_GRADE, ATTRIBUTE
FROM HAVEN_STORE.TROOPER.GRADE_MAPPING;

USE ROLE useradmin;

SHOW ROLES LIKE '%_haven_revenue_management_%';

SHOW GRANTS TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE_UAT__TROOPER__READER;

USE ROLE securityadmin;

GRANT SELECT ON VIEW HAVEN_STORE_UAT.TROOPER.CANCELLATIONS_CURRENTSEASON TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE_UAT__TROOPER__READER;
GRANT SELECT ON VIEW HAVEN_STORE_UAT.TROOPER.GRADE_MAPPING TO ROLE _HAVEN_REVENUE_MANAGEMENT_PRICER__HAVEN_STORE_UAT__TROOPER__READER;

USE ROLE haven_revenue_management_pricer_validation;

SHOW WAREHOUSES;

USE WAREHOUSE HAVEN_REVENUE_MANAGEMENT_PRICER_UAT_WAREHOUSE_XSMALL;

SELECT count(*) FROM HAVEN_STORE.TROOPER.CANCELLATIONS_CURRENTSEASON;


