USE ROLE dba;

USE SCHEMA training.training;

select * from dim_customers;

create table dim_cust_a as select * from dim_customers;
create table dim_cust_b as select * from dim_customers;

select * from dim_customers;

delete from dim_cust_a where customer_id in (15, 45, 60);
delete from dim_cust_b where customer_id in (11, 33, 99);



SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER_DATE, MOST_RECENT_ORDER_DATE, NUMBER_OF_ORDERS 
FROM (
	SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER_DATE, MOST_RECENT_ORDER_DATE, NUMBER_OF_ORDERS
	FROM DIM_CUST_A
	UNION ALL
	SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER_DATE, MOST_RECENT_ORDER_DATE, NUMBER_OF_ORDERS
	FROM DIM_CUST_B
)
GROUP BY 1,2,3,4,5,6
HAVING count(*) = 1
ORDER BY 1,2,3,4,5,6
;

SELECT 'A', CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER_DATE, MOST_RECENT_ORDER_DATE, NUMBER_OF_ORDERS
FROM DIM_CUST_A
UNION ALL
SELECT 'B', CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER_DATE, MOST_RECENT_ORDER_DATE, NUMBER_OF_ORDERS
FROM DIM_CUST_B
ORDER BY 2,3,4,5,6,7,1;

WITH taba AS (
	SELECT GUEST_ID, GUEST_SEQN, OCCUPANCY_NUMBER, RES_ID, CLIENT_ID, GUEST_TYPE, AGE
	FROM (
		SELECT GUEST_ID, GUEST_SEQN, OCCUPANCY_NUMBER, RES_ID, CLIENT_ID, GUEST_TYPE, AGE
		FROM WARNER_RAW.SEAWARE.RES_GUEST
		UNION ALL 
		SELECT GUEST_ID, GUEST_SEQN, OCCUPANCY_NUMBER, RES_ID, CLIENT_ID, GUEST_TYPE, AGE
		FROM WARNER_RAW.SEAWARE_APS.RES_GUEST
		)
	GROUP BY 1,2,3,4,5,6,7
	HAVING count(*) = 1
	ORDER BY 1,2,3,4,5,6,7
	)
SELECT GUEST_ID, GUEST_SEQN, OCCUPANCY_NUMBER, RES_ID, CLIENT_ID, GUEST_TYPE, AGE
FROM (
	SELECT GUEST_ID, GUEST_SEQN, OCCUPANCY_NUMBER, RES_ID, CLIENT_ID, GUEST_TYPE, AGE
	FROM WARNER_RAW.SEAWARE.RES_GUEST
	UNION ALL 
	SELECT GUEST_ID, GUEST_SEQN, OCCUPANCY_NUMBER, RES_ID, CLIENT_ID, GUEST_TYPE, AGE
	FROM TABA
	)
GROUP BY 1,2,3,4,5,6,7
HAVING count(*) = 2
ORDER BY 4
;


