--COND_RULE_TABLE
--COND_RULE_TEMPLATE_DEF
--COND_TEMPLATE_CUST_LINK
--COND_TEMPLATE_SQL_PARAMS
 
USE ROLE dba;

CREATE VIEW WARNER_BASE.SEAWARE.COND_RULE_TABLE
( RESULT_TYPE, ROW_TYPE_CODE, RULE_TABLE_ID, RULE_NAME, TEMPLATE_TYPE, TEMPLATE_DEF, RTT_INF, RULE_PLAN_ID, ASSOC_SELL_LIM_ID, CREATION_DATE )
AS SELECT RESULT_TYPE, ROW_TYPE_CODE, RULE_TABLE_ID, RULE_NAME, TEMPLATE_TYPE, TEMPLATE_DEF, RTT_INF, RULE_PLAN_ID, ASSOC_SELL_LIM_ID, CREATION_DATE
FROM WARNER_RAW.SEAWARE.COND_RULE_TABLE;

CREATE VIEW WARNER_BASE.SEAWARE.COND_RULE_TEMPLATE
( RECORD_ID, TEMPLATE_TYPE, COMMENTS )
AS SELECT RECORD_ID, TEMPLATE_TYPE, COMMENTS
FROM WARNER_RAW.SEAWARE.COND_RULE_TEMPLATE;

CREATE VIEW WARNER_BASE.SEAWARE.COND_TEMPLATE_CUST_LINK
( RECORD_ID, TEMPLATE_TYPE, TEMPLATE_DEF, CUSTOMER )
AS SELECT RECORD_ID, TEMPLATE_TYPE, TEMPLATE_DEF, CUSTOMER
FROM WARNER_RAW.SEAWARE.COND_TEMPLATE_CUST_LINK;

CREATE VIEW WARNER_BASE.SEAWARE.COND_TEMPLATE_SQL_PARAMS
( SQL_PARAM_ID, TEMPLATE_TYPE, TEMPLATE_DEF, SQL_AREA_CODE, SQL_MACROS )
AS SELECT SQL_PARAM_ID, TEMPLATE_TYPE, TEMPLATE_DEF, SQL_AREA_CODE, SQL_MACROS
FROM WARNER_RAW.SEAWARE.COND_TEMPLATE_SQL_PARAMS;