USE ROLE securityadmin;

SHOW GRANTS TO USER dionfragkoulis;

grant ROLE _warner_cust__ma_mart__reader TO ROLE warner_data_management;

USE ROLE dba;

USE SCHEMA warner_cust.ma_mart;

CREATE VIEW WARNER_CUST.MA_MART.D_ML_WRN_ITG_CANOPY_BKG_TEST
( BOOKING_REFERENCE, PERSON_ID, ARRIVAL_DATE, DEPARTURE_DATE, BOOK_DATE, BREAK_DURATION, TOTAL_GUESTS, TOTAL_ROOMS, REFERRAL_SOURCE, BREAK_STYLE, BREAK_TYPE, BREAK_DESCRIPTION, HOTEL_NAME, HOTEL_CATEGORY, ROOM_TYPE, ROOM_CODE, BOOK_LEAD_TIME, MULTI_ROOM_BOOKING, MISSION, BOOKING_CANCELLED, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6 ) 
AS SELECT BOOKING_REFERENCE, PERSON_ID, ARRIVAL_DATE, DEPARTURE_DATE, BOOK_DATE, BREAK_DURATION, TOTAL_GUESTS, TOTAL_ROOMS, REFERRAL_SOURCE, BREAK_STYLE, BREAK_TYPE, BREAK_DESCRIPTION, HOTEL_NAME, HOTEL_CATEGORY, ROOM_TYPE, ROOM_CODE, BOOK_LEAD_TIME, MULTI_ROOM_BOOKING, MISSION, BOOKING_CANCELLED, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6
FROM WARNER_BASE.MA_MART.D_ML_WRN_ITG_CANOPY_BKG_TEST;

CREATE VIEW WARNER_CUST.MA_MART.D_ML_WRN_ITG_CANOPY_BKGCHANGE
( BOOKING_REFERENCE, PERSON_ID )
AS SELECT BOOKING_REFERENCE, PERSON_ID
FROM WARNER_BASE.MA_MART.D_ML_WRN_ITG_CANOPY_BKGCHANGE;

CREATE VIEW WARNER_CUST.MA_MART.D_ML_WRN_ITG_CANOPY_DELETIONS
( PERSON_ID )
AS SELECT PERSON_ID
FROM WARNER_BASE.MA_MART.D_ML_WRN_ITG_CANOPY_DELETIONS;

CREATE VIEW WARNER_CUST.MA_MART.D_ML_WRN_ITG_CANOPY_GUEST_TEST
( PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, FIRST_LINE_ADDRESS, SECOND_LINE_ADDRESS, THIRD_LINE_ADDRESS, FOURTH_LINE_ADDRESS, FIFTH_LINE_ADDRESS, SIXTH_LINE_ADDRESS, POSTCODE, RFSEGMENT2022, FSEGMENT2022, RSEGMENT2022, PROSPECT_DATE, CLUB_MEMBER, NON_CLUB_MEMBER, ACTIVE, FTALLY, NEAREST_HOTEL_UNDER_TWO_HOURS, DRIVE_TIME_TO_ALVASTON_HALL, DRIVE_TIME_TO_BODELWYDDAN_CASTLE, DRIVE_TIME_TO_BEMBRIDGE_COAST, DRIVE_TIME_TO_CRICKET_ST_THOMAS, DRIVE_TIME_TO_CORTON, DRIVE_TIME_TO_GUNTON_HALL, DRIVE_TIME_TO_HOLME_LACY_HOUSE, DRIVE_TIME_TO_LITTLECOTE_HOUSE, DRIVE_TIME_TO_LAKESIDE, DRIVE_TIME_TO_NORTON_GRANGE, DRIVE_TIME_TO_NIDD_HALL, DRIVE_TIME_TO_SINAH_WARREN, DRIVE_TIME_TO_THORESBY_HALL, DRIVE_TIME_TO_STUDLEY_CASTLE, DRIVE_TIME_TO_HEYTHROP_PARK, LATE_BOOKER, PROSPECT_TYPE, LAST_ENEWS_SIGN_UP_DATE, LAST_BROCHURE_REQUEST_DATE, LAST_CANCELLED_DATE, LAST_QUOTE_DATE, OPTED_IN_TO_EMAIL, OPTED_IN_TO_DM, NUMBER_BOOKINGS_LAST_2_MONTH_HH, NUMBER_OF_PREVIOUS_STAYS_HH, NUMBER_OF_FUTURE_BOOKINGS_HH, NUMBER_OF_STAYS_LAST_6_MONTH_HH, NUMBER_OF_STAYS_LAST_12_MONTH_HH, NUMBER_OF_STAYS_LAST_2_YEARS_HH, NUMBER_OF_STAYS_LAST_3_YEARS_HH, NUMBER_OF_STAYS_LAST_5_YEARS_HH, DECEASED, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6 )
AS SELECT PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, FIRST_LINE_ADDRESS, SECOND_LINE_ADDRESS, THIRD_LINE_ADDRESS, FOURTH_LINE_ADDRESS, FIFTH_LINE_ADDRESS, SIXTH_LINE_ADDRESS, POSTCODE, RFSEGMENT2022, FSEGMENT2022, RSEGMENT2022, PROSPECT_DATE, CLUB_MEMBER, NON_CLUB_MEMBER, ACTIVE, FTALLY, NEAREST_HOTEL_UNDER_TWO_HOURS, DRIVE_TIME_TO_ALVASTON_HALL, DRIVE_TIME_TO_BODELWYDDAN_CASTLE, DRIVE_TIME_TO_BEMBRIDGE_COAST, DRIVE_TIME_TO_CRICKET_ST_THOMAS, DRIVE_TIME_TO_CORTON, DRIVE_TIME_TO_GUNTON_HALL, DRIVE_TIME_TO_HOLME_LACY_HOUSE, DRIVE_TIME_TO_LITTLECOTE_HOUSE, DRIVE_TIME_TO_LAKESIDE, DRIVE_TIME_TO_NORTON_GRANGE, DRIVE_TIME_TO_NIDD_HALL, DRIVE_TIME_TO_SINAH_WARREN, DRIVE_TIME_TO_THORESBY_HALL, DRIVE_TIME_TO_STUDLEY_CASTLE, DRIVE_TIME_TO_HEYTHROP_PARK, LATE_BOOKER, PROSPECT_TYPE, LAST_ENEWS_SIGN_UP_DATE, LAST_BROCHURE_REQUEST_DATE, LAST_CANCELLED_DATE, LAST_QUOTE_DATE, OPTED_IN_TO_EMAIL, OPTED_IN_TO_DM, NUMBER_BOOKINGS_LAST_2_MONTH_HH, NUMBER_OF_PREVIOUS_STAYS_HH, NUMBER_OF_FUTURE_BOOKINGS_HH, NUMBER_OF_STAYS_LAST_6_MONTH_HH, NUMBER_OF_STAYS_LAST_12_MONTH_HH, NUMBER_OF_STAYS_LAST_2_YEARS_HH, NUMBER_OF_STAYS_LAST_3_YEARS_HH, NUMBER_OF_STAYS_LAST_5_YEARS_HH, DECEASED, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6
FROM WARNER_BASE.MA_MART.D_ML_WRN_ITG_CANOPY_GUEST_TEST;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_BOOKING
( BOOKING_REFERENCE, PERSON_ID, SUBJECT_ID, ARRIVAL_DATE, DEPARTURE_DATE, BOOK_DATE, BREAK_DURATION, TOTAL_GUESTS, TOTAL_ROOMS, REFERRAL_SOURCE, BREAK_STYLE, BREAK_TYPE, BREAK_DESCRIPTION, HOTEL_NAME, HOTEL_CATEGORY, ROOM_TYPE, ROOM_CODE, BOOK_LEAD_TIME, MULTI_ROOM_BOOKING, MISSION, BOOKING_CANCELLED, BOARD_TYPE, EMAIL_ADDRESS, SITE_CD, STATUS, VALID_EMAIL, VALID_EMAIL_DOMAIN, PAF_VALID, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6 )
AS SELECT BOOKING_REFERENCE, PERSON_ID, SUBJECT_ID, ARRIVAL_DATE, DEPARTURE_DATE, BOOK_DATE, BREAK_DURATION, TOTAL_GUESTS, TOTAL_ROOMS, REFERRAL_SOURCE, BREAK_STYLE, BREAK_TYPE, BREAK_DESCRIPTION, HOTEL_NAME, HOTEL_CATEGORY, ROOM_TYPE, ROOM_CODE, BOOK_LEAD_TIME, MULTI_ROOM_BOOKING, MISSION, BOOKING_CANCELLED, BOARD_TYPE, EMAIL_ADDRESS, SITE_CD, STATUS, VALID_EMAIL, VALID_EMAIL_DOMAIN, PAF_VALID, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6
FROM WARNER_BASE.MA_MART.D_WRN_BOOKING;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_CANOPY_SEEDS
( ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE )
AS SELECT ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE
FROM WARNER_BASE.MA_MART.D_WRN_CANOPY_SEEDS;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_CONTENT_MATRIX
( SITE_CODE, HOTEL_NAME, HOTEL, HOTEL_ADDRESS, EXPLORE_THE_AREA, HERO_IMAGE, HERO_CTA, ARRIVAL_DAY_IMAGE, ARRIVAL_DAY_COPY, USEFUL_INFO_IMAGE, USEFUL_INFO_COPY, DINING_IMAGE, DINING_COPY, DINING_CTA, PHONE_NUMBER, EXCURSION_ONE_HERO_IMAGE, EXCURSION_ONE_COPY, EXCURSION_ONE_CTA, EXCURSION_TWO_HERO_COPY, EXCURSION_TWO_HERO_IMAGE, EXCURSION_TWO_HERO_CTA, EXCURSION_THREE_HERO_IMAGE, EXCURSION_THREE_HERO_COPY, EXCURSION_THREE_HERO_CTA)
AS SELECT SITE_CODE, HOTEL_NAME, HOTEL, HOTEL_ADDRESS, EXPLORE_THE_AREA, HERO_IMAGE, HERO_CTA, ARRIVAL_DAY_IMAGE, ARRIVAL_DAY_COPY, USEFUL_INFO_IMAGE, USEFUL_INFO_COPY, DINING_IMAGE, DINING_COPY, DINING_CTA, PHONE_NUMBER, EXCURSION_ONE_HERO_IMAGE, EXCURSION_ONE_COPY, EXCURSION_ONE_CTA, EXCURSION_TWO_HERO_COPY, EXCURSION_TWO_HERO_IMAGE, EXCURSION_TWO_HERO_CTA, EXCURSION_THREE_HERO_IMAGE, EXCURSION_THREE_HERO_COPY, EXCURSION_THREE_HERO_CTA
FROM WARNER_BASE.MA_MART.D_WRN_CONTENT_MATRIX;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_CONTENT_MATRIX_SEEDS
( SITE_CODE, HOTEL_NAME, HOTEL, HOTEL_ADDRESS, EXPLORE_THE_AREA, HERO_IMAGE, HERO_CTA, ARRIVAL_DAY_IMAGE, ARRIVAL_DAY_COPY, USEFUL_INFO_IMAGE, USEFUL_INFO_COPY, DINING_IMAGE, DINING_COPY, DINING_CTA, PHONE_NUMBER, EXCURSION_ONE_HERO_IMAGE, EXCURSION_ONE_COPY, EXCURSION_ONE_CTA, EXCURSION_TWO_HERO_COPY, EXCURSION_TWO_HERO_IMAGE, EXCURSION_TWO_HERO_CTA, EXCURSION_THREE_HERO_IMAGE, EXCURSION_THREE_HERO_COPY, EXCURSION_THREE_HERO_CTA )
AS SELECT SITE_CODE, HOTEL_NAME, HOTEL, HOTEL_ADDRESS, EXPLORE_THE_AREA, HERO_IMAGE, HERO_CTA, ARRIVAL_DAY_IMAGE, ARRIVAL_DAY_COPY, USEFUL_INFO_IMAGE, USEFUL_INFO_COPY, DINING_IMAGE, DINING_COPY, DINING_CTA, PHONE_NUMBER, EXCURSION_ONE_HERO_IMAGE, EXCURSION_ONE_COPY, EXCURSION_ONE_CTA, EXCURSION_TWO_HERO_COPY, EXCURSION_TWO_HERO_IMAGE, EXCURSION_TWO_HERO_CTA, EXCURSION_THREE_HERO_IMAGE, EXCURSION_THREE_HERO_COPY, EXCURSION_THREE_HERO_CTA
FROM WARNER_BASE.MA_MART.D_WRN_CONTENT_MATRIX_SEEDS;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_EM_BAU_SEEDS
( SUBJECT_ID, PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS)
AS SELECT SUBJECT_ID, PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS
FROM WARNER_BASE.MA_MART.D_WRN_EM_BAU_SEEDS;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_EMAIL_SEEDS
( ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE )
AS SELECT ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE
FROM WARNER_BASE.MA_MART.D_WRN_EMAIL_SEEDS;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_GUEST
( PERSON_ID, SUBJECT_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, FIRST_LINE_ADDRESS, SECOND_LINE_ADDRESS, THIRD_LINE_ADDRESS, FOURTH_LINE_ADDRESS, FIFTH_LINE_ADDRESS, SIXTH_LINE_ADDRESS, POSTCODE, RFSEGMENT2022, FSEGMENT2022, RSEGMENT2022, PROSPECT_DATE, CLUB_MEMBER, NON_CLUB_MEMBER, ACTIVE, FTALLY, NEAREST_HOTEL_UNDER_TWO_HOURS, DRIVE_TIME_TO_ALVASTON_HALL, DRIVE_TIME_TO_BODELWYDDAN_CASTLE, DRIVE_TIME_TO_BEMBRIDGE_COAST, DRIVE_TIME_TO_CRICKET_ST_THOMAS, DRIVE_TIME_TO_CORTON, DRIVE_TIME_TO_GUNTON_HALL, DRIVE_TIME_TO_HOLME_LACY_HOUSE, DRIVE_TIME_TO_LITTLECOTE_HOUSE, DRIVE_TIME_TO_LAKESIDE, DRIVE_TIME_TO_NORTON_GRANGE, DRIVE_TIME_TO_NIDD_HALL, DRIVE_TIME_TO_SINAH_WARREN, DRIVE_TIME_TO_THORESBY_HALL, DRIVE_TIME_TO_STUDLEY_CASTLE, DRIVE_TIME_TO_HEYTHROP_PARK, LATE_BOOKER, PROSPECT_TYPE, LAST_ENEWS_SIGN_UP_DATE, LAST_BROCHURE_REQUEST_DATE, LAST_CANCELLED_DATE, LAST_QUOTE_DATE, OPTED_IN_TO_EMAIL, OPTED_IN_TO_DM, NUMBER_BOOKINGS_LAST_2_MONTH_HH, NUMBER_OF_PREVIOUS_STAYS_HH, NUMBER_OF_FUTURE_BOOKINGS_HH, NUMBER_OF_STAYS_LAST_6_MONTH_HH, NUMBER_OF_STAYS_LAST_12_MONTH_HH, NUMBER_OF_STAYS_LAST_2_YEARS_HH, NUMBER_OF_STAYS_LAST_3_YEARS_HH, NUMBER_OF_STAYS_LAST_5_YEARS_HH, DECEASED, VALID_EMAIL, VALID_EMAIL_DOMAIN, PAF_VALID, FLAG_GUEST, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6 )
AS SELECT PERSON_ID, SUBJECT_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, FIRST_LINE_ADDRESS, SECOND_LINE_ADDRESS, THIRD_LINE_ADDRESS, FOURTH_LINE_ADDRESS, FIFTH_LINE_ADDRESS, SIXTH_LINE_ADDRESS, POSTCODE, RFSEGMENT2022, FSEGMENT2022, RSEGMENT2022, PROSPECT_DATE, CLUB_MEMBER, NON_CLUB_MEMBER, ACTIVE, FTALLY, NEAREST_HOTEL_UNDER_TWO_HOURS, DRIVE_TIME_TO_ALVASTON_HALL, DRIVE_TIME_TO_BODELWYDDAN_CASTLE, DRIVE_TIME_TO_BEMBRIDGE_COAST, DRIVE_TIME_TO_CRICKET_ST_THOMAS, DRIVE_TIME_TO_CORTON, DRIVE_TIME_TO_GUNTON_HALL, DRIVE_TIME_TO_HOLME_LACY_HOUSE, DRIVE_TIME_TO_LITTLECOTE_HOUSE, DRIVE_TIME_TO_LAKESIDE, DRIVE_TIME_TO_NORTON_GRANGE, DRIVE_TIME_TO_NIDD_HALL, DRIVE_TIME_TO_SINAH_WARREN, DRIVE_TIME_TO_THORESBY_HALL, DRIVE_TIME_TO_STUDLEY_CASTLE, DRIVE_TIME_TO_HEYTHROP_PARK, LATE_BOOKER, PROSPECT_TYPE, LAST_ENEWS_SIGN_UP_DATE, LAST_BROCHURE_REQUEST_DATE, LAST_CANCELLED_DATE, LAST_QUOTE_DATE, OPTED_IN_TO_EMAIL, OPTED_IN_TO_DM, NUMBER_BOOKINGS_LAST_2_MONTH_HH, NUMBER_OF_PREVIOUS_STAYS_HH, NUMBER_OF_FUTURE_BOOKINGS_HH, NUMBER_OF_STAYS_LAST_6_MONTH_HH, NUMBER_OF_STAYS_LAST_12_MONTH_HH, NUMBER_OF_STAYS_LAST_2_YEARS_HH, NUMBER_OF_STAYS_LAST_3_YEARS_HH, NUMBER_OF_STAYS_LAST_5_YEARS_HH, DECEASED, VALID_EMAIL, VALID_EMAIL_DOMAIN, PAF_VALID, FLAG_GUEST, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6
FROM WARNER_BASE.MA_MART.D_WRN_GUEST;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_GUESTSEGMENTS
( SEGMENT_YEAR, ADDRESS_ID, DISTINCT_YEARS, BOOKINGS, GUEST_WEEKS, GROSS_TARIFF, LAST_ARRIVAL_YEAR, SEG )
AS SELECT SEGMENT_YEAR, ADDRESS_ID, DISTINCT_YEARS, BOOKINGS, GUEST_WEEKS, GROSS_TARIFF, LAST_ARRIVAL_YEAR, SEG
FROM WARNER_BASE.MA_MART.D_WRN_GUESTSEGMENTS;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_ITG_CANOPY_GUEST_TEST_ERR
( PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, FIRST_LINE_ADDRESS, SECOND_LINE_ADDRESS, THIRD_LINE_ADDRESS, FOURTH_LINE_ADDRESS, FIFTH_LINE_ADDRESS, SIXTH_LINE_ADDRESS, POSTCODE, RFSEGMENT2022, FSEGMENT2022, RSEGMENT2022, PROSPECT_DATE, CLUB_MEMBER, NON_CLUB_MEMBER, ACTIVE, FTALLY, NEAREST_HOTEL_UNDER_TWO_HOURS, DRIVE_TIME_TO_ALVASTON_HALL, DRIVE_TIME_TO_BODELWYDDAN_CASTLE, DRIVE_TIME_TO_BEMBRIDGE_COAST, DRIVE_TIME_TO_CRICKET_ST_THOMAS, DRIVE_TIME_TO_CORTON, DRIVE_TIME_TO_GUNTON_HALL, DRIVE_TIME_TO_HOLME_LACY_HOUSE, DRIVE_TIME_TO_LITTLECOTE_HOUSE, DRIVE_TIME_TO_LAKESIDE, DRIVE_TIME_TO_NORTON_GRANGE, DRIVE_TIME_TO_NIDD_HALL, DRIVE_TIME_TO_SINAH_WARREN, DRIVE_TIME_TO_THORESBY_HALL, DRIVE_TIME_TO_STUDLEY_CASTLE, DRIVE_TIME_TO_HEYTHROP_PARK, LATE_BOOKER, PROSPECT_TYPE, LAST_ENEWS_SIGN_UP_DATE, LAST_BROCHURE_REQUEST_DATE, LAST_CANCELLED_DATE, LAST_QUOTE_DATE, OPTED_IN_TO_EMAIL, OPTED_IN_TO_DM, NUMBER_BOOKINGS_LAST_2_MONTH_HH, NUMBER_OF_PREVIOUS_STAYS_HH, NUMBER_OF_FUTURE_BOOKINGS_HH, NUMBER_OF_STAYS_LAST_6_MONTH_HH, NUMBER_OF_STAYS_LAST_12_MONTH_HH, NUMBER_OF_STAYS_LAST_2_YEARS_HH, NUMBER_OF_STAYS_LAST_3_YEARS_HH, NUMBER_OF_STAYS_LAST_5_YEARS_HH, DECEASED, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6, PROCESSED_DTTM )
AS SELECT PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS, FIRST_LINE_ADDRESS, SECOND_LINE_ADDRESS, THIRD_LINE_ADDRESS, FOURTH_LINE_ADDRESS, FIFTH_LINE_ADDRESS, SIXTH_LINE_ADDRESS, POSTCODE, RFSEGMENT2022, FSEGMENT2022, RSEGMENT2022, PROSPECT_DATE, CLUB_MEMBER, NON_CLUB_MEMBER, ACTIVE, FTALLY, NEAREST_HOTEL_UNDER_TWO_HOURS, DRIVE_TIME_TO_ALVASTON_HALL, DRIVE_TIME_TO_BODELWYDDAN_CASTLE, DRIVE_TIME_TO_BEMBRIDGE_COAST, DRIVE_TIME_TO_CRICKET_ST_THOMAS, DRIVE_TIME_TO_CORTON, DRIVE_TIME_TO_GUNTON_HALL, DRIVE_TIME_TO_HOLME_LACY_HOUSE, DRIVE_TIME_TO_LITTLECOTE_HOUSE, DRIVE_TIME_TO_LAKESIDE, DRIVE_TIME_TO_NORTON_GRANGE, DRIVE_TIME_TO_NIDD_HALL, DRIVE_TIME_TO_SINAH_WARREN, DRIVE_TIME_TO_THORESBY_HALL, DRIVE_TIME_TO_STUDLEY_CASTLE, DRIVE_TIME_TO_HEYTHROP_PARK, LATE_BOOKER, PROSPECT_TYPE, LAST_ENEWS_SIGN_UP_DATE, LAST_BROCHURE_REQUEST_DATE, LAST_CANCELLED_DATE, LAST_QUOTE_DATE, OPTED_IN_TO_EMAIL, OPTED_IN_TO_DM, NUMBER_BOOKINGS_LAST_2_MONTH_HH, NUMBER_OF_PREVIOUS_STAYS_HH, NUMBER_OF_FUTURE_BOOKINGS_HH, NUMBER_OF_STAYS_LAST_6_MONTH_HH, NUMBER_OF_STAYS_LAST_12_MONTH_HH, NUMBER_OF_STAYS_LAST_2_YEARS_HH, NUMBER_OF_STAYS_LAST_3_YEARS_HH, NUMBER_OF_STAYS_LAST_5_YEARS_HH, DECEASED, SPARE_1, SPARE_2, SPARE_3, SPARE_4, SPARE_5, SPARE_6, PROCESSED_DTTM
FROM WARNER_BASE.MA_MART.D_WRN_ITG_CANOPY_GUEST_TEST_ERR;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_MULTI_UNIT
( BOOKING_REFERENCE, DELEGATE_1, DELEGATE_2, DELEGATE_3, DELEGATE_4, DELEGATE_5, DELEGATE_6, DELEGATE_7, DELEGATE_8, DELEGATE_9, DELEGATE_10, DELEGATE_11, DELEGATE_12, DELEGATE_13, DELEGATE_14, DELEGATE_15, DELEGATE_16, DELEGATE_17, DELEGATE_18, DELEGATE_19, DELEGATE_20, DELEGATE_21, DELEGATE_22, DELEGATE_23, DELEGATE_24, DELEGATE_25, DELEGATE_26, DELEGATE_27, DELEGATE_28, DELEGATE_29, DELEGATE_30 )
AS SELECT BOOKING_REFERENCE, DELEGATE_1, DELEGATE_2, DELEGATE_3, DELEGATE_4, DELEGATE_5, DELEGATE_6, DELEGATE_7, DELEGATE_8, DELEGATE_9, DELEGATE_10, DELEGATE_11, DELEGATE_12, DELEGATE_13, DELEGATE_14, DELEGATE_15, DELEGATE_16, DELEGATE_17, DELEGATE_18, DELEGATE_19, DELEGATE_20, DELEGATE_21, DELEGATE_22, DELEGATE_23, DELEGATE_24, DELEGATE_25, DELEGATE_26, DELEGATE_27, DELEGATE_28, DELEGATE_29, DELEGATE_30
FROM WARNER_BASE.MA_MART.D_WRN_MULTI_UNIT;

CREATE VIEW WARNER_CUST.MA_MART.D_WRN_REDLIST_ADDRESS
( NAME, ADDRESS_1, ADDRESS_2, ADDRESS_3, ADDRESS_4, ADDRESS_5, ADDRESS_6, POST_CODE, ADDRESS_ID )
AS SELECT "NAME", ADDRESS_1, ADDRESS_2, ADDRESS_3, ADDRESS_4, ADDRESS_5, ADDRESS_6, POST_CODE, ADDRESS_ID
FROM WARNER_BASE.MA_MART.D_WRN_REDLIST_ADDRESS;


