USE ROLE dba;
USE SCHEMA haven_base.sas_scv;

-- WARNER_BASE.SAS_SCV.ACCOM_CODES_INSIGHTMAP source

create or replace view WARNER_BASE.SAS_SCV.ACCOM_CODES_INSIGHTMAP(
	SW_ROOM_GROUP,
	INSIGHT_ROOM_GROUP
) as SELECT "SW_ROOM_GROUP", "INSIGHT_ROOM_GROUP" FROM "WARNER_RAW"."SAS_SCV"."ACCOM_CODES_INSIGHTMAP";


-- WARNER_BASE.SAS_SCV.ACCOMMODATION_CODES source

create or replace view WARNER_BASE.SAS_SCV.ACCOMMODATION_CODES(
	REF,
	SITE_REF,
	SW_ROOM_TYPE,
	ROOM_GROUP,
	ROOM_TYPE,
	ROOM_NAME,
	AREA,
	FLOOR,
	BEDCONFIG,
	ROOM_CAPACITY,
	RESERVE_TYPE,
	VALID_FROM_DTTM,
	VALID_TO_DTTM,
	EFF_SAIL_FROM,
	EFF_SAIL_TO,
	IS_ACTIVE,
	PROCESSED_DTTM
) as SELECT "REF", "SITE_REF", "SW_ROOM_TYPE", "ROOM_GROUP", "ROOM_TYPE", "ROOM_NAME", "AREA", "FLOOR", "BEDCONFIG", "ROOM_CAPACITY", "RESERVE_TYPE", "VALID_FROM_DTTM", "VALID_TO_DTTM", "EFF_SAIL_FROM", "EFF_SAIL_TO", "IS_ACTIVE", "PROCESSED_DTTM" FROM "WARNER_RAW"."SAS_SCV"."ACCOMMODATION_CODES";


-- WARNER_BASE.SAS_SCV.ACCOMMODATION_CODES_BAK source

create or replace view WARNER_BASE.SAS_SCV.ACCOMMODATION_CODES_BAK(
	REF,
	SITE_REF,
	SW_ROOM_TYPE,
	ROOM_GROUP,
	ROOM_TYPE,
	ROOM_NAME,
	AREA,
	FLOOR,
	BEDCONFIG,
	ROOM_CAPACITY,
	RESERVE_TYPE,
	VALID_FROM_DTTM,
	VALID_TO_DTTM
) as SELECT "REF", "SITE_REF", "SW_ROOM_TYPE", "ROOM_GROUP", "ROOM_TYPE", "ROOM_NAME", "AREA", "FLOOR", "BEDCONFIG", "ROOM_CAPACITY", "RESERVE_TYPE", "VALID_FROM_DTTM", "VALID_TO_DTTM" FROM "WARNER_RAW"."SAS_SCV"."ACCOMMODATION_CODES_BAK";


-- WARNER_BASE.SAS_SCV.AK_DIST_EM_ACTIVITY source

create or replace view WARNER_BASE.SAS_SCV.AK_DIST_EM_ACTIVITY(
	EMAIL_ID,
	BROADCASTID,
	CAMPAIGNNAME,
	CUSTOMER_ID,
	EXTERNALID,
	ACTIVITY,
	ACTIVITY_DATE,
	DESCRIPTION,
	URL_DESCRIPTION,
	OS,
	BROWSER,
	MOBILE,
	TAGS,
	CAMPAIGN_TYPE,
	SEGMENT_NAME,
	CODE,
	DOUBLE_CLICK_REF,
	UTM_SOURCE,
	PROMO_CODE,
	CUSTOM7,
	CUSTOM8,
	CUSTOM9,
	CUSTOM10,
	SOURCE,
	PROCESSED_DTTM,
	CUSTOM1,
	CUSTOM2,
	CUSTOM3,
	CUSTOM4,
	CUSTOM5,
	CUSTOM6,
	IP,
	USER_AGENT,
	DEVICE_INFO
) as SELECT "EMAIL_ID", "BROADCASTID", "CAMPAIGNNAME", "CUSTOMER_ID", "EXTERNALID", "ACTIVITY", "ACTIVITY_DATE", "DESCRIPTION", "URL_DESCRIPTION", "OS", "BROWSER", "MOBILE", "TAGS", "CAMPAIGN_TYPE", "SEGMENT_NAME", "CODE", "DOUBLE_CLICK_REF", "UTM_SOURCE", "PROMO_CODE", "CUSTOM7", "CUSTOM8", "CUSTOM9", "CUSTOM10", "SOURCE", "PROCESSED_DTTM", "CUSTOM1", "CUSTOM2", "CUSTOM3", "CUSTOM4", "CUSTOM5", "CUSTOM6", "IP", "USER_AGENT", "DEVICE_INFO" FROM "WARNER_RAW"."SAS_SCV"."AK_DIST_EM_ACTIVITY";


-- WARNER_BASE.SAS_SCV.AK_DIST_EM_BROADCAST source

create or replace view WARNER_BASE.SAS_SCV.AK_DIST_EM_BROADCAST(
	BROADCASTID,
	BROADCASTTYPE,
	CAMPAIGNID,
	CAMPAIGNNAME,
	CONTENT_NAME,
	SUBJECT,
	MAILING_TYPE,
	SEND_AT,
	SELECTION,
	MAILED,
	ACCEPTED,
	BOUNCES,
	COMPLAINT,
	UNIQUE_OPENS,
	CLICKS,
	UNIQUE_CLICKS,
	DESKTOP_RATIO,
	MOBILE_RATIO,
	SOURCE,
	PROCESSED_DTTM,
	HARDBOUNCES,
	SOFTBOUNCES
) as SELECT "BROADCASTID", "BROADCASTTYPE", "CAMPAIGNID", "CAMPAIGNNAME", "CONTENT_NAME", "SUBJECT", "MAILING_TYPE", "SEND_AT", "SELECTION", "MAILED", "ACCEPTED", "BOUNCES", "COMPLAINT", "UNIQUE_OPENS", "CLICKS", "UNIQUE_CLICKS", "DESKTOP_RATIO", "MOBILE_RATIO", "SOURCE", "PROCESSED_DTTM", "HARDBOUNCES", "SOFTBOUNCES" FROM "WARNER_RAW"."SAS_SCV"."AK_DIST_EM_BROADCAST";


-- WARNER_BASE.SAS_SCV.BK_CTL_BOOKING_TYPE_CONTROL source

create or replace view WARNER_BASE.SAS_SCV.BK_CTL_BOOKING_TYPE_CONTROL(
	SWBOOKINGSOURCE,
	SWAGENCYTYPE,
	DWBOOKINGTYPECODE
) as SELECT "SWBOOKINGSOURCE", "SWAGENCYTYPE", "DWBOOKINGTYPECODE" FROM "WARNER_RAW"."SAS_SCV"."BK_CTL_BOOKING_TYPE_CONTROL";


-- WARNER_BASE.SAS_SCV.BK_DW_ADDON source

create or replace view WARNER_BASE.SAS_SCV.BK_DW_ADDON(
	HOLIDAYYEAR,
	ADDONCODE,
	SWRECORDID,
	SWADDONCATEGORY,
	ADDONTYPE,
	ADDONNAME,
	ADDONCOMMENTS
) as SELECT "HOLIDAYYEAR", "ADDONCODE", "SWRECORDID", "SWADDONCATEGORY", "ADDONTYPE", "ADDONNAME", "ADDONCOMMENTS" FROM "WARNER_RAW"."SAS_SCV"."BK_DW_ADDON";


-- WARNER_BASE.SAS_SCV.BK_DW_INVOICE_ITEM_TYPE source

create or replace view WARNER_BASE.SAS_SCV.BK_DW_INVOICE_ITEM_TYPE(
	HOLIDAYYEAR,
	INVOICEITEMTYPE,
	INVOICEITEMTYPEID,
	COMMENTS,
	ISCOMMISSIONABLE,
	CANUSEFORCHARGES,
	ALWAYSREFUNDABLE,
	USEDINTERNALLY,
	USEDFORAIRDEVIATION,
	ALLOWRATEPROTECTION,
	CHARGECOMPONENTCODE,
	CLASSIFICATIONFORGROUP,
	INCLUDEINQUOTEDPRICE,
	USEDFORPROJECTIONS,
	USEINPERFORMANCECALC,
	ISTARIFFINCLUDED,
	SUPPALLOWGROUP,
	SUPPALLOWGROUP2,
	HASVAT
) as SELECT "HOLIDAYYEAR", "INVOICEITEMTYPE", "INVOICEITEMTYPEID", "COMMENTS", "ISCOMMISSIONABLE", "CANUSEFORCHARGES", "ALWAYSREFUNDABLE", "USEDINTERNALLY", "USEDFORAIRDEVIATION", "ALLOWRATEPROTECTION", "CHARGECOMPONENTCODE", "CLASSIFICATIONFORGROUP", "INCLUDEINQUOTEDPRICE", "USEDFORPROJECTIONS", "USEINPERFORMANCECALC", "ISTARIFFINCLUDED", "SUPPALLOWGROUP", "SUPPALLOWGROUP2", "HASVAT" FROM "WARNER_RAW"."SAS_SCV"."BK_DW_INVOICE_ITEM_TYPE";


-- WARNER_BASE.SAS_SCV.BOOKING_ALLOCATION source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_ALLOCATION(
	REF,
	BOOKING_REF,
	ARRIVAL_DT,
	DEPARTURE_DT,
	SITE_REF,
	DECK_NAME,
	UNIT_NAME,
	UNIT_NUMBER,
	UNIT_TYPE,
	ALLOCATED_UNIT_TYPE,
	PRICE_UNIT_TYPE,
	ROOMS_HELD,
	GROUP_ID
) as SELECT "REF", "BOOKING_REF", "ARRIVAL_DT", "DEPARTURE_DT", "SITE_REF", "DECK_NAME", "UNIT_NAME", "UNIT_NUMBER", "UNIT_TYPE", "ALLOCATED_UNIT_TYPE", "PRICE_UNIT_TYPE", "ROOMS_HELD", "GROUP_ID" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_ALLOCATION";


-- WARNER_BASE.SAS_SCV.BOOKING_ATTRIBUTE source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_ATTRIBUTE(
	REF,
	BOOKING_REF,
	RECORD_ID,
	ATTRIBUTE_CODE,
	STR_VALUE,
	INT_VALUE,
	REQUEST_TYPE
) as SELECT "REF", "BOOKING_REF", "RECORD_ID", "ATTRIBUTE_CODE", "STR_VALUE", "INT_VALUE", "REQUEST_TYPE" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_ATTRIBUTE";


-- WARNER_BASE.SAS_SCV.BOOKING_CURRENT source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_CURRENT(
	REF,
	BOOKING_ID,
	GROUP_ID,
	PRODUCT_REF,
	SITE_REF,
	PERSON_ID,
	ADDRESS_ID,
	ORGANISATION_REF,
	HOUSEHOLD_REF,
	ORIG_BOOKING_REF,
	SRC_SYS_NAME,
	SRC_SYS_BK_NO,
	SRC_SYS_GRP_IND,
	BOOK_DT,
	STATUS,
	ARRIVAL_DT,
	DEPARTURE_DT,
	DURATION,
	GROSS_PRICE,
	NETT_PRICE,
	BALANCE_DUE,
	BALANCE_PAID_DT,
	TOTAL_GUESTS,
	CANX_DT,
	EXPIRY_DT,
	BOOK_LOCATION,
	FIRM_DT,
	USER_LOGIN,
	ACCOUNTING_PERIOD,
	REFERRAL_SOURCE,
	EMAIL_REF,
	GENERIC_GRADE,
	AGENT_COMMISSION,
	PACKAGE_TYPE,
	ROOM_NUMBER,
	ALLOCATED_UNIT_TYPE,
	PRICE_UNIT_TYPE,
	NO_OF_ROOMS_ALLOCATED,
	BOOKING_SOURCE_TYPE,
	BOOKED_GRADE,
	AVAILABLE_GRADE,
	REQUESTED_GRADE,
	SW_CLIENT_ID,
	SW_HOUSEHOLD_ID,
	GROUP_TYPE,
	PROCESSED_DTTM,
	RUN_DT,
	MWT_BOOKED_YN
) as SELECT "REF", "BOOKING_ID", "GROUP_ID", "PRODUCT_REF", "SITE_REF", "PERSON_ID", "ADDRESS_ID", "ORGANISATION_REF", "HOUSEHOLD_REF", "ORIG_BOOKING_REF", "SRC_SYS_NAME", "SRC_SYS_BK_NO", "SRC_SYS_GRP_IND", "BOOK_DT", "STATUS", "ARRIVAL_DT", "DEPARTURE_DT", "DURATION", "GROSS_PRICE", "NETT_PRICE", "BALANCE_DUE", "BALANCE_PAID_DT", "TOTAL_GUESTS", "CANX_DT", "EXPIRY_DT", "BOOK_LOCATION", "FIRM_DT", "USER_LOGIN", "ACCOUNTING_PERIOD", "REFERRAL_SOURCE", "EMAIL_REF", "GENERIC_GRADE", "AGENT_COMMISSION", "PACKAGE_TYPE", "ROOM_NUMBER", "ALLOCATED_UNIT_TYPE", "PRICE_UNIT_TYPE", "NO_OF_ROOMS_ALLOCATED", "BOOKING_SOURCE_TYPE", "BOOKED_GRADE", "AVAILABLE_GRADE", "REQUESTED_GRADE", "SW_CLIENT_ID", "SW_HOUSEHOLD_ID", "GROUP_TYPE", "PROCESSED_DTTM", "RUN_DT", "MWT_BOOKED_YN" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_CURRENT";


-- WARNER_BASE.SAS_SCV.BOOKING_GROUP_UNITS source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_GROUP_UNITS(
	REF,
	BOOKING_REF,
	ACCOM_BOOKED,
	ACCOM_AVAIL,
	ACCOM_REQUESTED,
	UNITROWID,
	BOOKROWID
) as SELECT "REF", "BOOKING_REF", "ACCOM_BOOKED", "ACCOM_AVAIL", "ACCOM_REQUESTED", "UNITROWID", "BOOKROWID" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_GROUP_UNITS";


-- WARNER_BASE.SAS_SCV.BOOKING_GROUP_UNITS_HIST source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_GROUP_UNITS_HIST(
	REF,
	BOOKING_REF,
	ACCOM_BOOKED,
	ACCOM_AVAIL,
	ACCOM_REQUESTED
) as SELECT "REF", "BOOKING_REF", "ACCOM_BOOKED", "ACCOM_AVAIL", "ACCOM_REQUESTED" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_GROUP_UNITS_HIST";


-- WARNER_BASE.SAS_SCV.BOOKING_HIST source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_HIST(
	REF,
	BOOKING_ID,
	GROUP_ID,
	PRODUCT_REF,
	SITE_REF,
	PERSON_ID,
	ADDRESS_ID,
	ORGANISATION_REF,
	HOUSEHOLD_REF,
	ORIG_BOOKING_REF,
	SRC_SYS_NAME,
	SRC_SYS_BK_NO,
	SRC_SYS_GRP_IND,
	BOOK_DT,
	STATUS,
	ARRIVAL_DT,
	DEPARTURE_DT,
	DURATION,
	GROSS_PRICE,
	NETT_PRICE,
	TOTAL_GUESTS,
	CANX_DT,
	EXPIRY_DT,
	BOOK_LOCATION,
	FIRM_DT,
	USER_LOGIN,
	ACCOUNTING_PERIOD,
	REFERRAL_SOURCE,
	EMAIL_REF,
	GENERIC_GRADE,
	AGENT_COMMISSION,
	PACKAGE_TYPE,
	ROOM_NUMBER,
	ALLOCATED_UNIT_TYPE,
	PRICE_UNIT_TYPE,
	NO_OF_ROOMS_ALLOCATED,
	BOOKING_SOURCE_TYPE,
	VALID_FROM_DT,
	VALID_TO_DT,
	PROCESSED_DTTM,
	RUN_DT,
	BOOKED_GRADE,
	AVAILABLE_GRADE,
	REQUESTED_GRADE,
	FIRST_VERSION,
	BALANCE_DUE,
	BALANCE_PAID_DT,
	CHANNEL,
	SW_CLIENT_ID,
	SW_HOUSEHOLD_ID,
	GROUP_TYPE,
	MWT_BOOKED_YN
) as SELECT "REF", "BOOKING_ID", "GROUP_ID", "PRODUCT_REF", "SITE_REF", "PERSON_ID", "ADDRESS_ID", "ORGANISATION_REF", "HOUSEHOLD_REF", "ORIG_BOOKING_REF", "SRC_SYS_NAME", "SRC_SYS_BK_NO", "SRC_SYS_GRP_IND", "BOOK_DT", "STATUS", "ARRIVAL_DT", "DEPARTURE_DT", "DURATION", "GROSS_PRICE", "NETT_PRICE", "TOTAL_GUESTS", "CANX_DT", "EXPIRY_DT", "BOOK_LOCATION", "FIRM_DT", "USER_LOGIN", "ACCOUNTING_PERIOD", "REFERRAL_SOURCE", "EMAIL_REF", "GENERIC_GRADE", "AGENT_COMMISSION", "PACKAGE_TYPE", "ROOM_NUMBER", "ALLOCATED_UNIT_TYPE", "PRICE_UNIT_TYPE", "NO_OF_ROOMS_ALLOCATED", "BOOKING_SOURCE_TYPE", "VALID_FROM_DT", "VALID_TO_DT", "PROCESSED_DTTM", "RUN_DT", "BOOKED_GRADE", "AVAILABLE_GRADE", "REQUESTED_GRADE", "FIRST_VERSION", "BALANCE_DUE", "BALANCE_PAID_DT", "CHANNEL", "SW_CLIENT_ID", "SW_HOUSEHOLD_ID", "GROUP_TYPE", "MWT_BOOKED_YN" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_HIST";


-- WARNER_BASE.SAS_SCV.BOOKING_HISTORIC_CHANNEL source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_HISTORIC_CHANNEL(
	SRC_SYS_BK_NO,
	CHANNEL,
	HOLIDAY_YEAR
) as SELECT "SRC_SYS_BK_NO", "CHANNEL", "HOLIDAY_YEAR" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_HISTORIC_CHANNEL";


-- WARNER_BASE.SAS_SCV.BOOKING_INVOICE_ITEM source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_INVOICE_ITEM(
	REF,
	BOOKING_REF,
	INVOICE_ITEM_TYPE,
	INVOICE_ITEM_SUBTYPE,
	INVOICE_ITEM_SUBTYPE2,
	INVOICE_ITEM_SUBTYPE3,
	PRICE_PROGRAM,
	PRICE_PER_UNIT,
	NO_OF_UNITS,
	QUANTITY,
	EFF_DATE,
	BROCHURE_PRICE,
	EBD_PRICE,
	GROUP_PRICE,
	TOTAL_PRICE,
	IS_MANUAL_ADJUSTMENT,
	PROMO_CODE,
	HOTEL_REQUEST_ID,
	SHIP_ROOM_REQUEST_ID,
	GROUP_SHIP_REQ_ID,
	GROUP_HOTEL_REQ_ID,
	GROUP_PACKAGE_ID,
	GROUP_AIR_REQ_ID,
	PACKAGE_ID,
	COMMISSION_PERCENT,
	DUMMY_RES_SEQN,
	GUEST_SEQN,
	PERSON_ID
) as SELECT "REF", "BOOKING_REF", "INVOICE_ITEM_TYPE", "INVOICE_ITEM_SUBTYPE", "INVOICE_ITEM_SUBTYPE2", "INVOICE_ITEM_SUBTYPE3", "PRICE_PROGRAM", "PRICE_PER_UNIT", "NO_OF_UNITS", "QUANTITY", "EFF_DATE", "BROCHURE_PRICE", "EBD_PRICE", "GROUP_PRICE", "TOTAL_PRICE", "IS_MANUAL_ADJUSTMENT", "PROMO_CODE", "HOTEL_REQUEST_ID", "SHIP_ROOM_REQUEST_ID", "GROUP_SHIP_REQ_ID", "GROUP_HOTEL_REQ_ID", "GROUP_PACKAGE_ID", "GROUP_AIR_REQ_ID", "PACKAGE_ID", "COMMISSION_PERCENT", "DUMMY_RES_SEQN", "GUEST_SEQN", "PERSON_ID" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_INVOICE_ITEM";


-- WARNER_BASE.SAS_SCV.BOOKING_LOCATION source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_LOCATION(
	REF,
	WRN_BOOKING_LOCATION,
	LOCATION_DESCRIPTION,
	LOCATION_GROUP,
	SW_BOOKING_SOURCE,
	SW_BOOKING_LOCATION
) as SELECT "REF", "WRN_BOOKING_LOCATION", "LOCATION_DESCRIPTION", "LOCATION_GROUP", "SW_BOOKING_SOURCE", "SW_BOOKING_LOCATION" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_LOCATION";


-- WARNER_BASE.SAS_SCV.BOOKING_ORIGINAL source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_ORIGINAL(
	REF,
	BOOKING_ID,
	GROUP_ID,
	PRODUCT_REF,
	SITE_REF,
	PERSON_ID,
	ADDRESS_ID,
	ORGANISATION_REF,
	HOUSEHOLD_REF,
	ORIG_BOOKING_REF,
	SRC_SYS_NAME,
	SRC_SYS_BK_NO,
	SRC_SYS_GRP_IND,
	BOOK_DT,
	STATUS,
	ARRIVAL_DT,
	DEPARTURE_DT,
	DURATION,
	GROSS_PRICE,
	NETT_PRICE,
	TOTAL_GUESTS,
	CANX_DT,
	EXPIRY_DT,
	BOOK_LOCATION,
	FIRM_DT,
	USER_LOGIN,
	ACCOUNTING_PERIOD,
	REFERRAL_SOURCE,
	EMAIL_REF,
	GENERIC_GRADE,
	AGENT_COMMISSION,
	PACKAGE_TYPE,
	ROOM_NUMBER,
	ALLOCATED_UNIT_TYPE,
	PRICE_UNIT_TYPE,
	NO_OF_ROOMS_ALLOCATED,
	BOOKING_SOURCE_TYPE,
	BOOKED_GRADE,
	AVAILABLE_GRADE,
	REQUESTED_GRADE,
	SW_CLIENT_ID,
	SW_HOUSEHOLD_ID,
	GROUP_TYPE,
	PROCESSED_DTTM,
	RUN_DT
) as SELECT "REF", "BOOKING_ID", "GROUP_ID", "PRODUCT_REF", "SITE_REF", "PERSON_ID", "ADDRESS_ID", "ORGANISATION_REF", "HOUSEHOLD_REF", "ORIG_BOOKING_REF", "SRC_SYS_NAME", "SRC_SYS_BK_NO", "SRC_SYS_GRP_IND", "BOOK_DT", "STATUS", "ARRIVAL_DT", "DEPARTURE_DT", "DURATION", "GROSS_PRICE", "NETT_PRICE", "TOTAL_GUESTS", "CANX_DT", "EXPIRY_DT", "BOOK_LOCATION", "FIRM_DT", "USER_LOGIN", "ACCOUNTING_PERIOD", "REFERRAL_SOURCE", "EMAIL_REF", "GENERIC_GRADE", "AGENT_COMMISSION", "PACKAGE_TYPE", "ROOM_NUMBER", "ALLOCATED_UNIT_TYPE", "PRICE_UNIT_TYPE", "NO_OF_ROOMS_ALLOCATED", "BOOKING_SOURCE_TYPE", "BOOKED_GRADE", "AVAILABLE_GRADE", "REQUESTED_GRADE", "SW_CLIENT_ID", "SW_HOUSEHOLD_ID", "GROUP_TYPE", "PROCESSED_DTTM", "RUN_DT" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_ORIGINAL";


-- WARNER_BASE.SAS_SCV.BOOKING_PARTY_PERSON source

create or replace view WARNER_BASE.SAS_SCV.BOOKING_PARTY_PERSON(
	REF,
	BOOKING_REF,
	PERSON_ID,
	GUEST_SEQN,
	EMAIL_REF,
	SW_CLIENT_ID,
	SW_HOUSEHOLD_ID
) as SELECT "REF", "BOOKING_REF", "PERSON_ID", "GUEST_SEQN", "EMAIL_REF", "SW_CLIENT_ID", "SW_HOUSEHOLD_ID" FROM "WARNER_RAW"."SAS_SCV"."BOOKING_PARTY_PERSON";


-- WARNER_BASE.SAS_SCV.BROCHURE_REQUEST source

create or replace view WARNER_BASE.SAS_SCV.BROCHURE_REQUEST(
	REF,
	NARRATIVE_REF,
	PERSON_ID,
	ADDRESS_ID,
	SRC_SYS_REF,
	SRC_SYS_NAME,
	BROCHURE_CODE,
	REQUEST_LOCATION,
	ORDER_ID,
	REFERRAL_SRC,
	REQUEST_TYPE,
	REQUEST_DTTM,
	FULFILLED,
	PACK_CODE,
	FULFIL_DATE,
	FULFIL_BATCH,
	FULFIL_USER,
	FULFIL_LOCATION,
	PROVIDER_CODE,
	PROCESSED_DTTM,
	RUN_DT,
	DELIVERY_CODE,
	EMAIL_REF,
	WEBPAGE_URL,
	AGENCY_NAME,
	BRO_ADD_NVR
) as SELECT "REF", "NARRATIVE_REF", "PERSON_ID", "ADDRESS_ID", "SRC_SYS_REF", "SRC_SYS_NAME", "BROCHURE_CODE", "REQUEST_LOCATION", "ORDER_ID", "REFERRAL_SRC", "REQUEST_TYPE", "REQUEST_DTTM", "FULFILLED", "PACK_CODE", "FULFIL_DATE", "FULFIL_BATCH", "FULFIL_USER", "FULFIL_LOCATION", "PROVIDER_CODE", "PROCESSED_DTTM", "RUN_DT", "DELIVERY_CODE", "EMAIL_REF", "WEBPAGE_URL", "AGENCY_NAME", "BRO_ADD_NVR" FROM "WARNER_RAW"."SAS_SCV"."BROCHURE_REQUEST";


-- WARNER_BASE.SAS_SCV.COMPLAINTS source

create or replace view WARNER_BASE.SAS_SCV.COMPLAINTS(
	REF,
	BRAND_REF,
	PERSON_ID,
	ADDRESS_ID,
	BOOKING_ID,
	ORGANISATION_ID,
	NAME,
	RECORD_DATE,
	SEAWARE_REF,
	PRIME_STATUS,
	CATEGORY,
	DATE_IMPORTED,
	COMPLIMENT,
	COMPLAINT_ID,
	COMPLAINT_TEXT,
	VISIT_DATE,
	CUST_TYPE,
	INFORMED_BY,
	GOODWILL,
	CLASSIFICATION,
	ACC_ADDRESS1,
	ACC_ADDRESS2,
	PROCESSED_DTTM
) as SELECT "REF", "BRAND_REF", "PERSON_ID", "ADDRESS_ID", "BOOKING_ID", "ORGANISATION_ID", "NAME", "RECORD_DATE", "SEAWARE_REF", "PRIME_STATUS", "CATEGORY", "DATE_IMPORTED", "COMPLIMENT", "COMPLAINT_ID", "COMPLAINT_TEXT", "VISIT_DATE", "CUST_TYPE", "INFORMED_BY", "GOODWILL", "CLASSIFICATION", "ACC_ADDRESS1", "ACC_ADDRESS2", "PROCESSED_DTTM" FROM "WARNER_RAW"."SAS_SCV"."COMPLAINTS";


-- WARNER_BASE.SAS_SCV.CTL_BOOKING_TYPE source

create or replace view WARNER_BASE.SAS_SCV.CTL_BOOKING_TYPE(
	REPTGYEAR,
	BOOKINGTYPECODE,
	BOOKINGTYPE,
	BOOKINGTYPEGROUP,
	BOOKINGTYPEGROUP2,
	BOOKINGTYPEGROUP3,
	BOOKINGTYPEORDER,
	OPTIMUMGROUP,
	FINANCEGROUP
) as SELECT "REPTGYEAR", "BOOKINGTYPECODE", "BOOKINGTYPE", "BOOKINGTYPEGROUP", "BOOKINGTYPEGROUP2", "BOOKINGTYPEGROUP3", "BOOKINGTYPEORDER", "OPTIMUMGROUP", "FINANCEGROUP" FROM "WARNER_RAW"."SAS_SCV"."CTL_BOOKING_TYPE";


-- WARNER_BASE.SAS_SCV.CTL_BOOKING_TYPE_CONTROL_HIST source

create or replace view WARNER_BASE.SAS_SCV.CTL_BOOKING_TYPE_CONTROL_HIST(
	SWBOOKINGSOURCE,
	SWAGENCYTYPE,
	DWBOOKINGTYPECODE,
	REF,
	VALID_FROM_DTTM,
	VALID_TO_DTTM
) as SELECT "SWBOOKINGSOURCE", "SWAGENCYTYPE", "DWBOOKINGTYPECODE", "REF", "VALID_FROM_DTTM", "VALID_TO_DTTM" FROM "WARNER_RAW"."SAS_SCV"."CTL_BOOKING_TYPE_CONTROL_HIST";


-- WARNER_BASE.SAS_SCV.CTL_DW_ADVISOR source

create or replace view WARNER_BASE.SAS_SCV.CTL_DW_ADVISOR(
	RECORDID,
	AVAYAUSER,
	SEAWAREUSER,
	INFORMUSER,
	NETWORKUSER,
	DISPLAYNAME,
	TEAM,
	ADVISORLOCATION,
	DEPARTMENT,
	VALIDFROM,
	VALIDUNTIL,
	CHANGEID
) as SELECT "RECORDID", "AVAYAUSER", "SEAWAREUSER", "INFORMUSER", "NETWORKUSER", "DISPLAYNAME", "TEAM", "ADVISORLOCATION", "DEPARTMENT", "VALIDFROM", "VALIDUNTIL", "CHANGEID" FROM "WARNER_RAW"."SAS_SCV"."CTL_DW_ADVISOR";


-- WARNER_BASE.SAS_SCV.CTL_MASTER_CALENDAR source

create or replace view WARNER_BASE.SAS_SCV.CTL_MASTER_CALENDAR(
	REPTGYEAR,
	SITECODE,
	PERIOD,
	BREAKNO,
	BREAKSTART,
	BREAKEND,
	DURATION,
	REPTGYEAR_PRIOR,
	BREAKNO_PRIOR,
	BREAKTYPE,
	BREAKTYPE2,
	BREAKDESCRIPTION,
	BROCHUREPRICE,
	WEEKNO,
	SEASON,
	BREAKSTYLE,
	BREAKSTART_PRIOR
) as SELECT "REPTGYEAR", "SITECODE", "PERIOD", "BREAKNO", "BREAKSTART", "BREAKEND", "DURATION", "REPTGYEAR_PRIOR", "BREAKNO_PRIOR", "BREAKTYPE", "BREAKTYPE2", "BREAKDESCRIPTION", "BROCHUREPRICE", "WEEKNO", "SEASON", "BREAKSTYLE", "BREAKSTART_PRIOR" FROM "WARNER_RAW"."SAS_SCV"."CTL_MASTER_CALENDAR";


-- WARNER_BASE.SAS_SCV.CTL_ROOMTYPE2 source

create or replace view WARNER_BASE.SAS_SCV.CTL_ROOMTYPE2(
	UNITTYPEKEY,
	SOURCEKEY,
	UNITTYPE,
	UNITDESC,
	UNITGROUP
) as SELECT "UNITTYPEKEY", "SOURCEKEY", "UNITTYPE", "UNITDESC", "UNITGROUP" FROM "WARNER_RAW"."SAS_SCV"."CTL_ROOMTYPE2";


-- WARNER_BASE.SAS_SCV.DW_ADDON_HIST source

create or replace view WARNER_BASE.SAS_SCV.DW_ADDON_HIST(
	HOLIDAYYEAR,
	ADDONCODE,
	SWRECORDID,
	SWADDONCATEGORY,
	ADDONTYPE,
	ADDONNAME,
	ADDONCOMMENTS,
	REF,
	VALID_FROM_DTTM,
	VALID_TO_DTTM
) as SELECT "HOLIDAYYEAR", "ADDONCODE", "SWRECORDID", "SWADDONCATEGORY", "ADDONTYPE", "ADDONNAME", "ADDONCOMMENTS", "REF", "VALID_FROM_DTTM", "VALID_TO_DTTM" FROM "WARNER_RAW"."SAS_SCV"."DW_ADDON_HIST";


-- WARNER_BASE.SAS_SCV.DW_INVOICE_ITEM_TYPE_HIST source

create or replace view WARNER_BASE.SAS_SCV.DW_INVOICE_ITEM_TYPE_HIST(
	HOLIDAYYEAR,
	INVOICEITEMTYPE,
	INVOICEITEMTYPEID,
	COMMENTS,
	ISCOMMISSIONABLE,
	CANUSEFORCHARGES,
	ALWAYSREFUNDABLE,
	USEDINTERNALLY,
	USEDFORAIRDEVIATION,
	ALLOWRATEPROTECTION,
	CHARGECOMPONENTCODE,
	CLASSIFICATIONFORGROUP,
	INCLUDEINQUOTEDPRICE,
	USEDFORPROJECTIONS,
	USEINPERFORMANCECALC,
	ISTARIFFINCLUDED,
	SUPPALLOWGROUP,
	SUPPALLOWGROUP2,
	HASVAT,
	REF,
	VALID_FROM_DTTM,
	VALID_TO_DTTM,
	TARIFFDEDUCTEDAMOUNT,
	NETTARIFFDEDUCTEDAMOUNT
) as SELECT "HOLIDAYYEAR", "INVOICEITEMTYPE", "INVOICEITEMTYPEID", "COMMENTS", "ISCOMMISSIONABLE", "CANUSEFORCHARGES", "ALWAYSREFUNDABLE", "USEDINTERNALLY", "USEDFORAIRDEVIATION", "ALLOWRATEPROTECTION", "CHARGECOMPONENTCODE", "CLASSIFICATIONFORGROUP", "INCLUDEINQUOTEDPRICE", "USEDFORPROJECTIONS", "USEINPERFORMANCECALC", "ISTARIFFINCLUDED", "SUPPALLOWGROUP", "SUPPALLOWGROUP2", "HASVAT", "REF", "VALID_FROM_DTTM", "VALID_TO_DTTM", "TARIFFDEDUCTEDAMOUNT", "NETTARIFFDEDUCTEDAMOUNT" FROM "WARNER_RAW"."SAS_SCV"."DW_INVOICE_ITEM_TYPE_HIST";


-- WARNER_BASE.SAS_SCV.KA_BOOKING_INVOICE_ITEM source

create or replace view WARNER_BASE.SAS_SCV.KA_BOOKING_INVOICE_ITEM(
	BOOKING_REF,
	USE_BOOKING_REF,
	BASE_COUNTER,
	BASE_PRICE,
	USE_COUNTER,
	USE_PRICE
) as SELECT "BOOKING_REF", "USE_BOOKING_REF", "BASE_COUNTER", "BASE_PRICE", "USE_COUNTER", "USE_PRICE" FROM "WARNER_RAW"."SAS_SCV"."KA_BOOKING_INVOICE_ITEM";


-- WARNER_BASE.SAS_SCV.KA_FIX_INVOICEITEMS source

create or replace view WARNER_BASE.SAS_SCV.KA_FIX_INVOICEITEMS(
	REF,
	SRC_SYS_BK_NO,
	VALID_FROM_DT,
	SAS_COUNT,
	SAS_TOTAL_PRICE,
	WH_RESID,
	WH_VALID_FROM_DT,
	WH_COUNT,
	WH_TOTAL_PRICE,
	USE_FROM,
	USE_REF
) as SELECT "REF", "SRC_SYS_BK_NO", "VALID_FROM_DT", "SAS_COUNT", "SAS_TOTAL_PRICE", "WH_RESID", "WH_VALID_FROM_DT", "WH_COUNT", "WH_TOTAL_PRICE", "USE_FROM", "USE_REF" FROM "WARNER_RAW"."SAS_SCV"."KA_FIX_INVOICEITEMS";


-- WARNER_BASE.SAS_SCV.KA_FIX_INVOICEITEMS_CURR source

create or replace view WARNER_BASE.SAS_SCV.KA_FIX_INVOICEITEMS_CURR(
	REF,
	SRC_SYS_BK_NO,
	VALID_FROM_DT,
	SAS_COUNT,
	SAS_TOTAL_PRICE,
	WH_RESID,
	WH_VALID_FROM_DT,
	WH_COUNT,
	WH_TOTAL_PRICE,
	USE_FROM,
	USE_REF
) as SELECT "REF", "SRC_SYS_BK_NO", "VALID_FROM_DT", "SAS_COUNT", "SAS_TOTAL_PRICE", "WH_RESID", "WH_VALID_FROM_DT", "WH_COUNT", "WH_TOTAL_PRICE", "USE_FROM", "USE_REF" FROM "WARNER_RAW"."SAS_SCV"."KA_FIX_INVOICEITEMS_CURR";


-- WARNER_BASE.SAS_SCV.KA_SAS_INVOICEITEMS source

create or replace view WARNER_BASE.SAS_SCV.KA_SAS_INVOICEITEMS(
	SRC_SYS_BK_NO,
	VALID_FROM_DT,
	COUNTER,
	TOTAL_PRICE
) as SELECT "SRC_SYS_BK_NO", "VALID_FROM_DT", "COUNTER", "TOTAL_PRICE" FROM "WARNER_RAW"."SAS_SCV"."KA_SAS_INVOICEITEMS";


-- WARNER_BASE.SAS_SCV.KA_WH_INVOICE_ITEMS source

create or replace view WARNER_BASE.SAS_SCV.KA_WH_INVOICE_ITEMS(
	RESID,
	VALIDFROM,
	TOTAL_PRICE,
	COUNTER
) as SELECT "RESID", "VALIDFROM", "TOTAL_PRICE", "COUNTER" FROM "WARNER_RAW"."SAS_SCV"."KA_WH_INVOICE_ITEMS";


-- WARNER_BASE.SAS_SCV.LAKESTAR source

create or replace view WARNER_BASE.SAS_SCV.LAKESTAR(
	START_DATE,
	ACTIVITY,
	ADVERTISER,
	CAMPAIGN,
	LOCATION,
	DATE_FROM,
	BREAK_TYPE,
	SRC_SYS_BK_NO,
	PLACEMENT,
	TRANSACTION_COUNT,
	TOTAL_CONVERSIONS,
	TOTAL_REVENUE,
	PROCESSED_DTTM
) as SELECT "START_DATE", "ACTIVITY", "ADVERTISER", "CAMPAIGN", "LOCATION", "DATE_FROM", "BREAK_TYPE", "SRC_SYS_BK_NO", "PLACEMENT", "TRANSACTION_COUNT", "TOTAL_CONVERSIONS", "TOTAL_REVENUE", "PROCESSED_DTTM" FROM "WARNER_RAW"."SAS_SCV"."LAKESTAR";


-- WARNER_BASE.SAS_SCV.MA_CAMPAIGN source

create or replace view WARNER_BASE.SAS_SCV.MA_CAMPAIGN(
	REF,
	BRAND_REF,
	CAMPAIGN_ID,
	CAMPAIGN_CD,
	CAMPAIGN_NAME,
	CAMPAIGN_DESCRIPTION,
	CAMPAIGN_MODIFIED_USER,
	CAMPAIGN_START_DATE,
	CAMPAIGN_END_DATE,
	CAMPAIGN_TOTAL_COUNT,
	CAMPAIGN_DATE_CREATED,
	CAMPAIGN_DATE_MODIFIED,
	CAMPAIGN_LAST_RUN_DATE,
	OWNER_PARK_CODE,
	DATE_REQUESTED,
	PRODUCT,
	SEEDS,
	DATA_OWNER,
	TOTAL_QTY_REQD,
	MAILER_QTY_REQD,
	TELE_QTY_REQD,
	EMAIL_QTY_REQD,
	ACTUAL_QTY,
	FULFILMENT_DATE,
	SUB_DIVISION,
	SEASON,
	NEWREPEAT,
	LEAD_IN_PRICE,
	MARKETING_PERIOD,
	UMBRELLA_CAMPAIGN,
	CAMPAIGN_TYPE
) as SELECT "REF", "BRAND_REF", "CAMPAIGN_ID", "CAMPAIGN_CD", "CAMPAIGN_NAME", "CAMPAIGN_DESCRIPTION", "CAMPAIGN_MODIFIED_USER", "CAMPAIGN_START_DATE", "CAMPAIGN_END_DATE", "CAMPAIGN_TOTAL_COUNT", "CAMPAIGN_DATE_CREATED", "CAMPAIGN_DATE_MODIFIED", "CAMPAIGN_LAST_RUN_DATE", "OWNER_PARK_CODE", "DATE_REQUESTED", "PRODUCT", "SEEDS", "DATA_OWNER", "TOTAL_QTY_REQD", "MAILER_QTY_REQD", "TELE_QTY_REQD", "EMAIL_QTY_REQD", "ACTUAL_QTY", "FULFILMENT_DATE", "SUB_DIVISION", "SEASON", "NEWREPEAT", "LEAD_IN_PRICE", "MARKETING_PERIOD", "UMBRELLA_CAMPAIGN", "CAMPAIGN_TYPE" FROM "WARNER_RAW"."SAS_SCV"."MA_CAMPAIGN";


-- WARNER_BASE.SAS_SCV.MA_COMMUNICATION source

create or replace view WARNER_BASE.SAS_SCV.MA_COMMUNICATION(
	REF,
	CAMPAIGN_REF,
	COMMUNICATION_CODE,
	COMMUNICATION_NAME,
	COMMUNICATION_DATE_MODIFIED,
	COMMUNICATION_DATE_CREATED,
	COMMUNICATION_TOTAL_COUNT,
	COMMUNICATION_LAST_RUN_DATE,
	DATA_REQUIRED_DATE,
	FILE_FORMAT,
	EXPORT_DEFINITION,
	ADDITIONAL_FIELDS,
	MAILING_HOUSE_NAME,
	MAILING_HOUSE_INVOICE_NUMBER,
	MAILING_HOUSE_COST,
	PRINTER_NAME,
	PRINTER_COST,
	PRINTER_INVOICE_NUMBER,
	POSTAGE_COST,
	PO_NUMBER,
	TOTAL_COST,
	LAND_DATE_ESTIMATED,
	LAND_DATE_ACTUAL,
	END_DATE,
	MAILER_DESCRIPTION,
	CONV_RATE,
	EPRO_REF,
	QUANTITY,
	QUOTE_CODE,
	OFFER_END_DATE,
	DOCKET_NUMBER,
	RM_SERVICE,
	RM_INVOICE_NUMBER,
	PRODUCT,
	PACK_CODE,
	CONV_BKG_DAYS,
	CONV_BOOKINGS,
	CONV_NETT_BILLING,
	CHANNEL,
	MARKETING_PERIOD,
	CAMPAIGN_ID,
	COMMUNICATION_ID,
	COMMUNICATION_DESCRIPTION,
	VALIDATED_YN
) as SELECT "REF", "CAMPAIGN_REF", "COMMUNICATION_CODE", "COMMUNICATION_NAME", "COMMUNICATION_DATE_MODIFIED", "COMMUNICATION_DATE_CREATED", "COMMUNICATION_TOTAL_COUNT", "COMMUNICATION_LAST_RUN_DATE", "DATA_REQUIRED_DATE", "FILE_FORMAT", "EXPORT_DEFINITION", "ADDITIONAL_FIELDS", "MAILING_HOUSE_NAME", "MAILING_HOUSE_INVOICE_NUMBER", "MAILING_HOUSE_COST", "PRINTER_NAME", "PRINTER_COST", "PRINTER_INVOICE_NUMBER", "POSTAGE_COST", "PO_NUMBER", "TOTAL_COST", "LAND_DATE_ESTIMATED", "LAND_DATE_ACTUAL", "END_DATE", "MAILER_DESCRIPTION", "CONV_RATE", "EPRO_REF", "QUANTITY", "QUOTE_CODE", "OFFER_END_DATE", "DOCKET_NUMBER", "RM_SERVICE", "RM_INVOICE_NUMBER", "PRODUCT", "PACK_CODE", "CONV_BKG_DAYS", "CONV_BOOKINGS", "CONV_NETT_BILLING", "CHANNEL", "MARKETING_PERIOD", "CAMPAIGN_ID", "COMMUNICATION_ID", "COMMUNICATION_DESCRIPTION", "VALIDATED_YN" FROM "WARNER_RAW"."SAS_SCV"."MA_COMMUNICATION";


-- WARNER_BASE.SAS_SCV.MA_CONTACT_HISTORY source

create or replace view WARNER_BASE.SAS_SCV.MA_CONTACT_HISTORY(
	REF,
	EMAIL_REF,
	CONTACT_INFO_REF,
	COMMUNICATION_REF,
	COMM_OCCUR_ID,
	PERSON_ID,
	CAMPAIGN_OCCUR_ID,
	CONTACT_CREATION_DTTM,
	CONTACT_CREATION_BY_NM,
	COMM_OCCUR_PLAN_DTTM,
	CONTACT_EXECUTED_DTTM,
	CONTACT_EXECUTED_BY_NM,
	CONTACT_EXPORTED_DTTM,
	CONTACT_EXPORTED_BY_NM,
	ORIGINAL_ADDRESS_ID,
	CURRENT_ADDRESS_ID,
	DELETED_YN
) as SELECT "REF", "EMAIL_REF", "CONTACT_INFO_REF", "COMMUNICATION_REF", "COMM_OCCUR_ID", "PERSON_ID", "CAMPAIGN_OCCUR_ID", "CONTACT_CREATION_DTTM", "CONTACT_CREATION_BY_NM", "COMM_OCCUR_PLAN_DTTM", "CONTACT_EXECUTED_DTTM", "CONTACT_EXECUTED_BY_NM", "CONTACT_EXPORTED_DTTM", "CONTACT_EXPORTED_BY_NM", "ORIGINAL_ADDRESS_ID", "CURRENT_ADDRESS_ID", "DELETED_YN" FROM "WARNER_RAW"."SAS_SCV"."MA_CONTACT_HISTORY";


-- WARNER_BASE.SAS_SCV.MWT_BOOKED_ZONE source

create or replace view WARNER_BASE.SAS_SCV.MWT_BOOKED_ZONE(
	SRC_SYS_BK_NO,
	BOOKINGDATETIME,
	HOLIDAYSTARTDATE,
	NIGHTS,
	TRANSACTIONTYPE,
	ZONE,
	ZONEPAX,
	HOTELCODE
) as SELECT "SRC_SYS_BK_NO", "BOOKINGDATETIME", "HOLIDAYSTARTDATE", "NIGHTS", "TRANSACTIONTYPE", "ZONE", "ZONEPAX", "HOTELCODE" FROM "WARNER_RAW"."SAS_SCV"."MWT_BOOKED_ZONE";


-- WARNER_BASE.SAS_SCV.REDEYE_CLICKS source

create or replace view WARNER_BASE.SAS_SCV.REDEYE_CLICKS(
	EMAIL_ADDRESS,
	CLICKED_DTTM,
	LINK_NAME,
	PROCESSED_DTTM
) as SELECT "EMAIL_ADDRESS", "CLICKED_DTTM", "LINK_NAME", "PROCESSED_DTTM" FROM "WARNER_RAW"."SAS_SCV"."REDEYE_CLICKS";


-- WARNER_BASE.SAS_SCV.REDEYE_LEGACY source

create or replace view WARNER_BASE.SAS_SCV.REDEYE_LEGACY(
	EMAIL_ID,
	EMAIL_ADDRESS,
	CAMPAIGN_DTTM,
	RESPONSE_DTTM
) as SELECT "EMAIL_ID", "EMAIL_ADDRESS", "CAMPAIGN_DTTM", "RESPONSE_DTTM" FROM "WARNER_RAW"."SAS_SCV"."REDEYE_LEGACY";


-- WARNER_BASE.SAS_SCV.REDEYE_OPENS source

create or replace view WARNER_BASE.SAS_SCV.REDEYE_OPENS(
	EMAIL_ADDRESS,
	OPENED_DTTM,
	PROCESSED_DTTM
) as SELECT "EMAIL_ADDRESS", "OPENED_DTTM", "PROCESSED_DTTM" FROM "WARNER_RAW"."SAS_SCV"."REDEYE_OPENS";


-- WARNER_BASE.SAS_SCV.REDEYE_TRANSMISSION source

create or replace view WARNER_BASE.SAS_SCV.REDEYE_TRANSMISSION(
	SCHEDULE,
	TARGET_LIST,
	DATA_TYPE,
	EMAIL_ADDRESS,
	RESULT,
	START_DATE,
	PROCESSED_DTTM,
	SOURCE
) as SELECT "SCHEDULE", "TARGET_LIST", "DATA_TYPE", "EMAIL_ADDRESS", "RESULT", "START_DATE", "PROCESSED_DTTM", "SOURCE" FROM "WARNER_RAW"."SAS_SCV"."REDEYE_TRANSMISSION";


-- WARNER_BASE.SAS_SCV.REDEYE_WEEKLY_HISTORIC source

create or replace view WARNER_BASE.SAS_SCV.REDEYE_WEEKLY_HISTORIC(
	WEEKBEG,
	CAMPAIGN,
	SCHEDULE,
	EMAIL_TYPE,
	SUBJECT_LINE,
	TOTAL_SENT,
	DELIVERED,
	DELIVERED___OF_SENT,
	UNIQUE_OPENS,
	OPENS___OF_DELIVERED,
	UNIQUE_CLICKS,
	CLICKS___OF_OPENED,
	UNSUB,
	UNSUB___OF_DELIVERED,
	FAILED,
	FAILS___OF_SENT,
	DC_LAST_CLICK_BOOKING,
	DC_LAST_CLICK_REVENUE,
	DC_LAST_CLICK_AOV,
	DC_CLICK_TO_BOOK_CONV
) as SELECT "WEEKBEG", "CAMPAIGN", "SCHEDULE", "EMAIL_TYPE", "SUBJECT_LINE", "TOTAL_SENT", "DELIVERED", "DELIVERED___OF_SENT", "UNIQUE_OPENS", "OPENS___OF_DELIVERED", "UNIQUE_CLICKS", "CLICKS___OF_OPENED", "UNSUB", "UNSUB___OF_DELIVERED", "FAILED", "FAILS___OF_SENT", "DC_LAST_CLICK_BOOKING", "DC_LAST_CLICK_REVENUE", "DC_LAST_CLICK_AOV", "DC_CLICK_TO_BOOK_CONV" FROM "WARNER_RAW"."SAS_SCV"."REDEYE_WEEKLY_HISTORIC";


-- WARNER_BASE.SAS_SCV.REDEYE_WEEKLY_SUMMARY source

create or replace view WARNER_BASE.SAS_SCV.REDEYE_WEEKLY_SUMMARY(
	WEEKBEG,
	CAMPAIGN,
	SCHEDULE,
	EMAIL_TYPE,
	SUBJECT_LINE,
	TOTAL_SENT,
	DELIVERED,
	DELIVERED___OF_SENT,
	UNIQUE_OPENS,
	OPENS___OF_DELIVERED,
	UNIQUE_CLICKS,
	CLICKS___OF_OPENED,
	UNSUB,
	UNSUB___OF_DELIVERED,
	FAILED,
	FAILS___OF_SENT,
	DC_LAST_CLICK_BOOKING,
	DC_LAST_CLICK_REVENUE,
	DC_LAST_CLICK_AOV,
	DC_CLICK_TO_BOOK_CONV
) as SELECT "WEEKBEG", "CAMPAIGN", "SCHEDULE", "EMAIL_TYPE", "SUBJECT_LINE", "TOTAL_SENT", "DELIVERED", "DELIVERED___OF_SENT", "UNIQUE_OPENS", "OPENS___OF_DELIVERED", "UNIQUE_CLICKS", "CLICKS___OF_OPENED", "UNSUB", "UNSUB___OF_DELIVERED", "FAILED", "FAILS___OF_SENT", "DC_LAST_CLICK_BOOKING", "DC_LAST_CLICK_REVENUE", "DC_LAST_CLICK_AOV", "DC_CLICK_TO_BOOK_CONV" FROM "WARNER_RAW"."SAS_SCV"."REDEYE_WEEKLY_SUMMARY";


-- WARNER_BASE.SAS_SCV.REFERRAL_SOURCES source

create or replace view WARNER_BASE.SAS_SCV.REFERRAL_SOURCES(
	REF,
	REFERRAL_SOURCE,
	REFERRAL_TYPE,
	REFERRAL_GROUP,
	PHC,
	REFERRAL_SOURCE_DESC,
	VALID_FROM_DTTM,
	VALID_TO_DTTM
) as SELECT "REF", "REFERRAL_SOURCE", "REFERRAL_TYPE", "REFERRAL_GROUP", "PHC", "REFERRAL_SOURCE_DESC", "VALID_FROM_DTTM", "VALID_TO_DTTM" FROM "WARNER_RAW"."SAS_SCV"."REFERRAL_SOURCES";


-- WARNER_BASE.SAS_SCV.SDM_REDEYE_RESPONSE source

create or replace view WARNER_BASE.SAS_SCV.SDM_REDEYE_RESPONSE(
	RESPONSE_EVENT,
	EMAIL_ADDRESS,
	RESPONSE_DATE,
	LINK,
	PROCESSED_DTTM,
	SOURCE
) as SELECT "RESPONSE_EVENT", "EMAIL_ADDRESS", "RESPONSE_DATE", "LINK", "PROCESSED_DTTM", "SOURCE" FROM "WARNER_RAW"."SAS_SCV"."SDM_REDEYE_RESPONSE";


-- WARNER_BASE.SAS_SCV.WAREHOUSE_ORIGINAL_SOURCE source

create or replace view WARNER_BASE.SAS_SCV.WAREHOUSE_ORIGINAL_SOURCE(
	PERSON_ID,
	ORIGINAL_SOURCE,
	ORIGINAL_SOURCE_DTTM
) as SELECT "PERSON_ID", "ORIGINAL_SOURCE", "ORIGINAL_SOURCE_DTTM" FROM "WARNER_RAW"."SAS_SCV"."WAREHOUSE_ORIGINAL_SOURCE";


-- WARNER_BASE.SAS_SCV.WRN_CONTROL_ID_LIST source

create or replace view WARNER_BASE.SAS_SCV.WRN_CONTROL_ID_LIST(
	CC_DIRECT_MEMB,
	LOYALTY_CALC_DT,
	LOYALTY_MEMB,
	LOYALTY_LAUNCH_DT,
	CC_CLOSE_DT
) as SELECT "CC_DIRECT_MEMB", "LOYALTY_CALC_DT", "LOYALTY_MEMB", "LOYALTY_LAUNCH_DT", "CC_CLOSE_DT" FROM "WARNER_RAW"."SAS_SCV"."WRN_CONTROL_ID_LIST";


-- WARNER_BASE.SAS_SCV.WRN_DEMOGRAPHIC source

create or replace view WARNER_BASE.SAS_SCV.WRN_DEMOGRAPHIC(
	POSTCODE,
	INGRES_POSTCODE,
	POSTAREA,
	POSTDIST,
	SECTOR,
	ADMIN_AREA,
	MOSAIC_TYPE,
	MOSAIC_GROUP,
	ALVASTON_HALL_DT_MINS,
	BEMBRIDGE_COAST_DT_MINS,
	BODELWYDDAN_DT_MINS,
	CORTON_DT_MINS,
	COTSWOLD_WATER_PARK_DT_MINS,
	CRICKET_ST_THOMAS_DT_MINS,
	GUNTON_HALL_DT_MINS,
	HEMEL_HEMPSTEAD_DT_MINS,
	HOLME_LACY_DT_MINS,
	LAKESIDE_DT_MINS,
	LITTLECOTE_DT_MINS,
	NIDD_HALL_DT_MINS,
	NORTON_GRANGE_DT_MINS,
	SINAH_WARREN_DT_MINS,
	THORESBY_HALL_DT_MINS,
	ALVASTON_HALL_MILES,
	BEMBRIDGE_COAST_MILES,
	BODELWYDDAN_MILES,
	CORTON_MILES,
	COTSWOLD_WATER_PARK_MILES,
	CRICKET_ST_THOMAS_MILES,
	GUNTON_HALL_MILES,
	HEMEL_HEMPSTEAD_MILES,
	HOLME_LACY_MILES,
	LAKESIDE_MILES,
	LITTLECOTE_MILES,
	NIDD_HALL_MILES,
	NORTON_GRANGE_MILES,
	SINAH_WARREN_MILES,
	THORESBY_HALL_MILES,
	HOUSEHOLDS,
	POPULATION,
	ADULTS,
	ITV_REGION,
	ITV_SUBREGION
) as SELECT "POSTCODE", "INGRES_POSTCODE", "POSTAREA", "POSTDIST", "SECTOR", "ADMIN_AREA", "MOSAIC_TYPE", "MOSAIC_GROUP", "ALVASTON_HALL_DT_MINS", "BEMBRIDGE_COAST_DT_MINS", "BODELWYDDAN_DT_MINS", "CORTON_DT_MINS", "COTSWOLD_WATER_PARK_DT_MINS", "CRICKET_ST_THOMAS_DT_MINS", "GUNTON_HALL_DT_MINS", "HEMEL_HEMPSTEAD_DT_MINS", "HOLME_LACY_DT_MINS", "LAKESIDE_DT_MINS", "LITTLECOTE_DT_MINS", "NIDD_HALL_DT_MINS", "NORTON_GRANGE_DT_MINS", "SINAH_WARREN_DT_MINS", "THORESBY_HALL_DT_MINS", "ALVASTON_HALL_MILES", "BEMBRIDGE_COAST_MILES", "BODELWYDDAN_MILES", "CORTON_MILES", "COTSWOLD_WATER_PARK_MILES", "CRICKET_ST_THOMAS_MILES", "GUNTON_HALL_MILES", "HEMEL_HEMPSTEAD_MILES", "HOLME_LACY_MILES", "LAKESIDE_MILES", "LITTLECOTE_MILES", "NIDD_HALL_MILES", "NORTON_GRANGE_MILES", "SINAH_WARREN_MILES", "THORESBY_HALL_MILES", "HOUSEHOLDS", "POPULATION", "ADULTS", "ITV_REGION", "ITV_SUBREGION" FROM "WARNER_RAW"."SAS_SCV"."WRN_DEMOGRAPHIC";


-- WARNER_BASE.SAS_SCV.WRN_EMAIL_ACTIVITY source

create or replace view WARNER_BASE.SAS_SCV.WRN_EMAIL_ACTIVITY(
	EMAIL_ID,
	BROADCASTID,
	CAMPAIGNNAME,
	CUSTOMER_ID,
	EXTERNALID,
	ACTIVITY,
	ACTIVITY_DATE,
	DESCRIPTION,
	URL_DESCRIPTION,
	OS,
	BROWSER,
	MOBILE,
	TAGS,
	CAMPAIGN_TYPE,
	SEGMENT_NAME,
	CODE,
	DOUBLE_CLICK_REF,
	UTM_SOURCE,
	PROMO_CODE,
	CUSTOM7,
	CUSTOM8,
	CUSTOM9,
	CUSTOM10,
	SOURCE,
	PROCESSED_DTTM,
	CUSTOM1,
	CUSTOM2,
	CUSTOM3,
	CUSTOM4,
	CUSTOM5,
	CUSTOM6,
	IP,
	USER_AGENT,
	DEVICE_INFO
) as SELECT "EMAIL_ID", "BROADCASTID", "CAMPAIGNNAME", "CUSTOMER_ID", "EXTERNALID", "ACTIVITY", "ACTIVITY_DATE", "DESCRIPTION", "URL_DESCRIPTION", "OS", "BROWSER", "MOBILE", "TAGS", "CAMPAIGN_TYPE", "SEGMENT_NAME", "CODE", "DOUBLE_CLICK_REF", "UTM_SOURCE", "PROMO_CODE", "CUSTOM7", "CUSTOM8", "CUSTOM9", "CUSTOM10", "SOURCE", "PROCESSED_DTTM", "CUSTOM1", "CUSTOM2", "CUSTOM3", "CUSTOM4", "CUSTOM5", "CUSTOM6", "IP", "USER_AGENT", "DEVICE_INFO" FROM "WARNER_RAW"."SAS_SCV"."WRN_EMAIL_ACTIVITY";


-- WARNER_BASE.SAS_SCV.WRN_EMAIL_BROADCAST source

create or replace view WARNER_BASE.SAS_SCV.WRN_EMAIL_BROADCAST(
	BROADCASTID,
	BROADCASTTYPE,
	CAMPAIGNID,
	CAMPAIGNNAME,
	CONTENT_NAME,
	SUBJECT,
	MAILING_TYPE,
	SEND_AT,
	SELECTION,
	MAILED,
	ACCEPTED,
	BOUNCES,
	COMPLAINT,
	UNIQUE_OPENS,
	CLICKS,
	UNIQUE_CLICKS,
	DESKTOP_RATIO,
	MOBILE_RATIO,
	SOURCE,
	PROCESSED_DTTM,
	HARDBOUNCES,
	SOFTBOUNCES
) as SELECT "BROADCASTID", "BROADCASTTYPE", "CAMPAIGNID", "CAMPAIGNNAME", "CONTENT_NAME", "SUBJECT", "MAILING_TYPE", "SEND_AT", "SELECTION", "MAILED", "ACCEPTED", "BOUNCES", "COMPLAINT", "UNIQUE_OPENS", "CLICKS", "UNIQUE_CLICKS", "DESKTOP_RATIO", "MOBILE_RATIO", "SOURCE", "PROCESSED_DTTM", "HARDBOUNCES", "SOFTBOUNCES" FROM "WARNER_RAW"."SAS_SCV"."WRN_EMAIL_BROADCAST";


-- WARNER_BASE.SAS_SCV.WRN_EQ_AGENCY source

create or replace view WARNER_BASE.SAS_SCV.WRN_EQ_AGENCY(
	AGENCY_ID,
	PARENT_AGENCY_ID,
	AGENCY_NAME,
	AGENCY_TYPE,
	IS_ACTIVE,
	IS_INTERNAL,
	CONTACT_NAME,
	ABTA_NUMBER,
	EMAIL_YN,
	PHONE_YN,
	FAX_YN,
	MAIL_YN
) as SELECT "AGENCY_ID", "PARENT_AGENCY_ID", "AGENCY_NAME", "AGENCY_TYPE", "IS_ACTIVE", "IS_INTERNAL", "CONTACT_NAME", "ABTA_NUMBER", "EMAIL_YN", "PHONE_YN", "FAX_YN", "MAIL_YN" FROM "WARNER_RAW"."SAS_SCV"."WRN_EQ_AGENCY";


-- WARNER_BASE.SAS_SCV.WRN_SCV_VOUCHER_CUST source

create or replace view WARNER_BASE.SAS_SCV.WRN_SCV_VOUCHER_CUST(
	PERSON_ID,
	ADDRESS_ID,
	EMAIL_ID,
	COMPANY,
	PHONE,
	TOTAL_SPENT,
	TOTAL_ORDERS,
	TAGS,
	NOTE,
	TAX_EXEMPT,
	DATE_LOAD,
	NEW,
	VALID_FROM_DTTM
) as SELECT "PERSON_ID", "ADDRESS_ID", "EMAIL_ID", "COMPANY", "PHONE", "TOTAL_SPENT", "TOTAL_ORDERS", "TAGS", "NOTE", "TAX_EXEMPT", "DATE_LOAD", "NEW", "VALID_FROM_DTTM" FROM "WARNER_RAW"."SAS_SCV"."WRN_SCV_VOUCHER_CUST";


-- WARNER_BASE.SAS_SCV.WRN_SCV_VOUCHER_ORDER source

create or replace view WARNER_BASE.SAS_SCV.WRN_SCV_VOUCHER_ORDER(
	NAME,
	FINANCIAL_STATUS,
	PAID_AT,
	FULFILLMENT_STATUS,
	FULFILLED_AT,
	ACCEPTS_MARKETING,
	CURRENCY,
	SUBTOTAL,
	SHIPPING,
	TAXES,
	TOTAL,
	DISCOUNT_CODE,
	DISCOUNT_AMOUNT,
	SHIPPING_METHOD,
	CREATED_AT,
	LINEITEM_QUANTITY,
	LINEITEM_NAME,
	LINEITEM_PRICE,
	LINEITEM_COMPARE_AT_PRICE,
	LINEITEM_SKU,
	LINEITEM_REQUIRES_SHIPPING,
	LINEITEM_TAXABLE,
	LINEITEM_FULFILLMENT_STATUS,
	BILLING_PERSON_ID,
	BILLING_ADDRESS_ID,
	BILLING_PHONE,
	SHIPPING_PERSON_ID,
	SHIPPING_ADDRESS_ID,
	SHIPPING_PHONE,
	NOTES,
	NOTE_ATTRIBUTES,
	CANCELLED_AT,
	PAYMENT_METHOD,
	PAYMENT_REFERENCE,
	REFUNDED_AMOUNT,
	VENDOR,
	ID,
	TAGS,
	RISK_LEVEL,
	SOURCE,
	LINEITEM_DISCOUNT,
	TAX_1_NAME,
	TAX_1_VALUE,
	TAX_2_NAME,
	TAX_2_VALUE,
	TAX_3_NAME,
	TAX_3_VALUE,
	TAX_4_NAME,
	TAX_4_VALUE,
	TAX_5_NAME,
	TAX_5_VALUE,
	PHONE
) as SELECT "NAME", "FINANCIAL_STATUS", "PAID_AT", "FULFILLMENT_STATUS", "FULFILLED_AT", "ACCEPTS_MARKETING", "CURRENCY", "SUBTOTAL", "SHIPPING", "TAXES", "TOTAL", "DISCOUNT_CODE", "DISCOUNT_AMOUNT", "SHIPPING_METHOD", "CREATED_AT", "LINEITEM_QUANTITY", "LINEITEM_NAME", "LINEITEM_PRICE", "LINEITEM_COMPARE_AT_PRICE", "LINEITEM_SKU", "LINEITEM_REQUIRES_SHIPPING", "LINEITEM_TAXABLE", "LINEITEM_FULFILLMENT_STATUS", "BILLING_PERSON_ID", "BILLING_ADDRESS_ID", "BILLING_PHONE", "SHIPPING_PERSON_ID", "SHIPPING_ADDRESS_ID", "SHIPPING_PHONE", "NOTES", "NOTE_ATTRIBUTES", "CANCELLED_AT", "PAYMENT_METHOD", "PAYMENT_REFERENCE", "REFUNDED_AMOUNT", "VENDOR", "ID", "TAGS", "RISK_LEVEL", "SOURCE", "LINEITEM_DISCOUNT", "TAX_1_NAME", "TAX_1_VALUE", "TAX_2_NAME", "TAX_2_VALUE", "TAX_3_NAME", "TAX_3_VALUE", "TAX_4_NAME", "TAX_4_VALUE", "TAX_5_NAME", "TAX_5_VALUE", "PHONE" FROM "WARNER_RAW"."SAS_SCV"."WRN_SCV_VOUCHER_ORDER";