USE ROLE sysadmin;

CREATE WAREHOUSE warner_account_information_warehouse_xsmall WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

use role useradmin;

create role _warner_account_information_warehouse_xsmall__operator;
create role _warner_account_information_warehouse_xsmall__usage;

-- Create a new role intended to monitor Snowflake usage.
create role warner_account_information;

USE ROLE securityadmin;

grant usage, monitor on warehouse warner_account_information_warehouse_xsmall to role _warner_account_information_warehouse_xsmall__usage;
grant role _warner_account_information_warehouse_xsmall__usage to role _warner_account_information_warehouse_xsmall__operator;
grant operate, modify on warehouse warner_account_information_warehouse_xsmall to role _warner_account_information_warehouse_xsmall__operator;

GRANT ROLE _warner_account_information_warehouse_xsmall__usage TO ROLE warner_account_information;
GRANT ROLE _WARNER_WORK__COMMON__READER TO ROLE  warner_account_information;

USE ROLE warner_account_information;

USE ROLE DBA;

USE SCHEMA warner_work.common;

SELECT * FROM snowflake.ACCOUNT_USAGE.ACCESS_HISTORY LIMIT 30;

SELECT * FROM snowflake.ACCOUNT_USAGE.COPY_HISTORY 
WHERE TABLE_CATALOG_name LIKE 'WARNER_%'
LIMIT 10;

USE ROLE dba;

DROP VIEW WARNER_WORK.COMMON.COPY_HISTORY;

CREATE TABLE WARNER_WORK.COMMON.COPY_HISTORY LIKE SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY;

INSERT INTO WARNER_WORK.COMMON.COPY_HISTORY 
SELECT FILE_NAME, STAGE_LOCATION, LAST_LOAD_TIME, ROW_COUNT, ROW_PARSED, FILE_SIZE, FIRST_ERROR_MESSAGE, FIRST_ERROR_LINE_NUMBER, FIRST_ERROR_CHARACTER_POS, FIRST_ERROR_COLUMN_NAME, ERROR_COUNT, ERROR_LIMIT, STATUS, TABLE_ID, TABLE_NAME, TABLE_SCHEMA_ID, TABLE_SCHEMA_NAME, TABLE_CATALOG_ID, TABLE_CATALOG_NAME, PIPE_CATALOG_NAME, PIPE_SCHEMA_NAME, PIPE_NAME, PIPE_RECEIVED_TIME, FIRST_COMMIT_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
WHERE TABLE_CATALOG_NAME LIKE 'WARNER_%';

--WITH taba AS (SELECT MAX(LAST_LOAD_TIME) as max_load_datetime
--FROM WARNER_WORK.COMMON.COPY_HISTORY) 

INSERT INTO WARNER_WORK.COMMON.COPY_HISTORY
SELECT FILE_NAME, STAGE_LOCATION, LAST_LOAD_TIME, ROW_COUNT, ROW_PARSED, FILE_SIZE, FIRST_ERROR_MESSAGE, FIRST_ERROR_LINE_NUMBER, FIRST_ERROR_CHARACTER_POS, FIRST_ERROR_COLUMN_NAME, ERROR_COUNT, ERROR_LIMIT, STATUS, TABLE_ID, TABLE_NAME, TABLE_SCHEMA_ID, TABLE_SCHEMA_NAME, TABLE_CATALOG_ID, TABLE_CATALOG_NAME, PIPE_CATALOG_NAME, PIPE_SCHEMA_NAME, PIPE_NAME, PIPE_RECEIVED_TIME, FIRST_COMMIT_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY 
WHERE TABLE_CATALOG_name LIKE 'WARNER_%'
and LAST_LOAD_TIME > (SELECT MAX(LAST_LOAD_TIME) FROM WARNER_WORK.COMMON.COPY_HISTORY);


USE ROLE securityadmin;

GRANT ROLE _WARNER_WORK__COMMON__READER TO ROLE WARNER_TERRAFORM_TRANSFORM_DEV;
GRANT ROLE _WARNER_WORK__COMMON__READER TO ROLE WARNER_DBT_TRANSFORM_DEV;

USE ROLE DBA;

USE SCHEMA WARNER_WORK.COMMON;

CREATE TASK WARNER_COPY_HISTORY
WAREHOUSE = WARNER_ACCOUNT_INFORMATION_WAREHOUSE_XSMALL
SCHEDULE = 'USING CRON 0 6 * * * UTC'
COMMENT = 'Task to populate COPY_HISTORY table for Warners'
AS
INSERT INTO WARNER_WORK.COMMON.COPY_HISTORY
SELECT FILE_NAME, STAGE_LOCATION, LAST_LOAD_TIME, ROW_COUNT, ROW_PARSED, FILE_SIZE, FIRST_ERROR_MESSAGE, FIRST_ERROR_LINE_NUMBER, FIRST_ERROR_CHARACTER_POS, FIRST_ERROR_COLUMN_NAME, ERROR_COUNT, ERROR_LIMIT, STATUS, TABLE_ID, TABLE_NAME, TABLE_SCHEMA_ID, TABLE_SCHEMA_NAME, TABLE_CATALOG_ID, TABLE_CATALOG_NAME, PIPE_CATALOG_NAME, PIPE_SCHEMA_NAME, PIPE_NAME, PIPE_RECEIVED_TIME, FIRST_COMMIT_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY 
WHERE TABLE_CATALOG_name LIKE 'WARNER_%'
and LAST_LOAD_TIME > (SELECT MAX(LAST_LOAD_TIME) FROM WARNER_WORK.COMMON.COPY_HISTORY);

SHOW TASKS;

EXECUTE TASK WARNER_COPY_HISTORY;

SELECT *
  FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(ROOT_TASK_ID=>'01b4d95c-4ec8-e2f4-0000-00000000022f'))
  ORDER BY SCHEDULED_TIME;
