USE ROLE sysadmin;

CREATE WAREHOUSE warner_insights_analytics_warehouse_xsmall WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

USE ROLE useradmin;

create role warner_insights_analytics;

create role _warner_insights_analytics_warehouse_xsmall__warehouse__operator;
create role _warner_insights_analytics_warehouse_xsmall__warehouse__usage;

--Webb, Matthew 
--Matthew.Webb@bourne-leisure.co.uk

create user MatthewWebb
login_name = 'Matthew.Webb@bourne-leisure.co.uk'
display_name = 'Matthew Webb'
email = 'Matthew.Webb@bourne-leisure.co.uk'
comment = 'Warner Head of Insight & Analytics - Holiday Sales & Marketing'
default_role = warner_insights_analytics
default_warehouse = warner_insights_analytics_warehouse_xsmall;

--Davies, Rhiannon 
--Rhiannon.Davies1@bourne-leisure.co.uk

DROP USER RhiannonDavies1;
create user RhiannonDavies
login_name = 'Rhiannon.Davies@bourne-leisure.co.uk'
display_name = 'Rhiannon Davies'
email = 'Rhiannon.Davies@bourne-leisure.co.uk'
comment = 'Senior Analyst - Holiday Sales & Marketing'
default_role = warner_insights_analytics
default_warehouse = warner_insights_analytics_warehouse_xsmall;

USE ROLE securityadmin;

grant usage, monitor on warehouse warner_insights_analytics_warehouse_xsmall to role _warner_insights_analytics_warehouse_xsmall__warehouse__usage;
grant role _warner_insights_analytics_warehouse_xsmall__warehouse__usage to role _warner_insights_analytics_warehouse_xsmall__warehouse__operator;
grant operate, modify on warehouse warner_insights_analytics_warehouse_xsmall to role _warner_insights_analytics_warehouse_xsmall__warehouse__operator;

GRANT role _warner_insights_analytics_warehouse_xsmall__warehouse__usage TO ROLE warner_insights_analytics;
GRANT ROLE _warner_base__ma_mart__reader TO ROLE warner_insights_analytics;

GRANT ROLE warner_insights_analytics TO USER MatthewWebb;
GRANT ROLE warner_insights_analytics TO USER RhiannonDavies;
GRANT ROLE warner_insights_analytics TO USER RodPestell;
GRANT ROLE warner_insights_analytics TO ROLE dba;

USE ROLE dba;

USE ROLE warner_insights_analytics;


USE ROLE DBA;

USE SCHEMA warner_base.ma_mart;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_BOOKING_HISTORY_EVENTS
( BOOKING_ID, EMAIL_ID, GUEST_WEEKS, GROSS_TARIFF, GATA, ROOMS_BOOKED, SITE_CD, BREAK_TYPE_REF, BOOKED_ACCOM_REF, BOOKING_CHANNEL_CD, BOOKING_SOURCE_TYPE, SRC_SYS_BK_NO, ADDRESS_ID, BOOK_DT, TOTAL_GUESTS, ARRIVAL_DT, DEPARTURE_DT, STATUS, BOOKING_CHANNEL_GROUP, VALID_FROM_DTTM, VALID_TO_DTTM, RECORD_CLASS, ACCOM_GROSS, BOOK_STATUS, BREAK_TYPE2, ROOM_TYPE, EVENT_TYPE, FLAG_BOOKING, CHANGE_BOOK_DT, CHANGE_ARRIVAL_DT, CHANGE_SITE_CD, CHANGE_GUEST_WEEKS, CHANGE_GROSS_TARIFF, CHANGE_ADDRESS_ID, CHANGE_BOOKING_CHANNEL_CD, ARRIVAL_YEAR, ARRIVAL_MONTH, HOUSEHOLD, BOOK_COUNTER, BOOK_TYPE, SEG, NEW_REPEAT )
AS SELECT BOOKING_ID, EMAIL_ID, GUEST_WEEKS, GROSS_TARIFF, GATA, ROOMS_BOOKED, SITE_CD, BREAK_TYPE_REF, BOOKED_ACCOM_REF, BOOKING_CHANNEL_CD, BOOKING_SOURCE_TYPE, SRC_SYS_BK_NO, ADDRESS_ID, BOOK_DT, TOTAL_GUESTS, ARRIVAL_DT, DEPARTURE_DT, STATUS, BOOKING_CHANNEL_GROUP, VALID_FROM_DTTM, VALID_TO_DTTM, RECORD_CLASS, ACCOM_GROSS, BOOK_STATUS, BREAK_TYPE2, ROOM_TYPE, EVENT_TYPE, FLAG_BOOKING, CHANGE_BOOK_DT, CHANGE_ARRIVAL_DT, CHANGE_SITE_CD, CHANGE_GUEST_WEEKS, CHANGE_GROSS_TARIFF, CHANGE_ADDRESS_ID, CHANGE_BOOKING_CHANNEL_CD, ARRIVAL_YEAR, ARRIVAL_MONTH, HOUSEHOLD, BOOK_COUNTER, BOOK_TYPE, SEG, NEW_REPEAT
FROM WARNER_RAW.MA_MART.D_WRN_BOOKING_HISTORY_EVENTS;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_BOOKINGTYPES
( BOOKING_ID, GUEST_WEEKS, GROSS_TARIFF, LEAD_TIME, BOOK_DT, ARRIVAL_DT, VALID_FROM_DTTM, VALID_TO_DTTM, EMAIL_ID, BOOKING_CHANNEL_CD, SITE_CD, ADDRESS_ID, ARRIVAL_YEAR, ARRIVAL_MONTH, BOOK_YEAR, BOOK_MONTH, ADDRESS_BARCODE, POSTCODE_SECTOR, BOOK_COUNTER, BOOK_TYPE )
AS SELECT BOOKING_ID, GUEST_WEEKS, GROSS_TARIFF, LEAD_TIME, BOOK_DT, ARRIVAL_DT, VALID_FROM_DTTM, VALID_TO_DTTM, EMAIL_ID, BOOKING_CHANNEL_CD, SITE_CD, ADDRESS_ID, ARRIVAL_YEAR, ARRIVAL_MONTH, BOOK_YEAR, BOOK_MONTH, ADDRESS_BARCODE, POSTCODE_SECTOR, BOOK_COUNTER, BOOK_TYPE
FROM WARNER_RAW.MA_MART.D_WRN_BOOKINGTYPES;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_CAMPAIGN_REPORTING
( TASK_NAME, TASK_CODE, CHANNEL, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, FLAG_CONTROL_CELL_EM, SEGMENT_MAP_NAME, CONTACT_DATE, CONTACT_DTTM, DROP_DATE, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, NB_EMAIL_OPENS, EMAIL_CLICK_DTTM, NB_EMAIL_CLICKS, FLAG_EMAIL_SEND, FLAG_EMAIL_OPEN, FLAG_EMAIL_CLICK, FLAG_UNSUBSCRIBE, FLAG_DM_SEND, ADDRESS_ID, PERSON_ID, PERSON_EMAIL_ID, GUEST_SEGMENT, CONTACT_YEAR, CONTACT_PERIOD, CONTACT_WEEK, CONTACT_WEEK_START_DT, CONTACT_WEEK_END_DT, BOOKING_ID, GUEST_WEEKS, GROSS_TARIFF, LEAD_TIME, BOOK_DT, ARRIVAL_DT, VALID_FROM_DTTM, VALID_TO_DTTM, BOOKING_EMAIL_ID, BOOKING_CHANNEL_CD, PRE_BOOK_DT, SITE_CD, ARRIVAL_MONTH, ARRIVAL_YEAR, BOOK_YEAR, PREVIEW, BOOK_TYPE, HOTEL_NAME, NEW_REPEAT, FLAG_BOOKING, BOOKING_GUEST_WEEKS, BOOKING_GROSS_TARIFF, FLAG_DISTINCT_BOOKING, DISTINCT_BOOKING_GUEST_WEEKS, DISTINCT_BOOKING_GROSS_TARIFF ) 
AS SELECT TASK_NAME, TASK_CODE, CHANNEL, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, FLAG_CONTROL_CELL_EM, SEGMENT_MAP_NAME, CONTACT_DATE, CONTACT_DTTM, DROP_DATE, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, NB_EMAIL_OPENS, EMAIL_CLICK_DTTM, NB_EMAIL_CLICKS, FLAG_EMAIL_SEND, FLAG_EMAIL_OPEN, FLAG_EMAIL_CLICK, FLAG_UNSUBSCRIBE, FLAG_DM_SEND, ADDRESS_ID, PERSON_ID, PERSON_EMAIL_ID, GUEST_SEGMENT, CONTACT_YEAR, CONTACT_PERIOD, CONTACT_WEEK, CONTACT_WEEK_START_DT, CONTACT_WEEK_END_DT, BOOKING_ID, GUEST_WEEKS, GROSS_TARIFF, LEAD_TIME, BOOK_DT, ARRIVAL_DT, VALID_FROM_DTTM, VALID_TO_DTTM, BOOKING_EMAIL_ID, BOOKING_CHANNEL_CD, PRE_BOOK_DT, SITE_CD, ARRIVAL_MONTH, ARRIVAL_YEAR, BOOK_YEAR, PREVIEW, BOOK_TYPE, HOTEL_NAME, NEW_REPEAT, FLAG_BOOKING, BOOKING_GUEST_WEEKS, BOOKING_GROSS_TARIFF, FLAG_DISTINCT_BOOKING, DISTINCT_BOOKING_GUEST_WEEKS, DISTINCT_BOOKING_GROSS_TARIFF
FROM WARNER_RAW.MA_MART.D_WRN_CAMPAIGN_REPORTING;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_CONTACT_RESPONSE
( TASK_NAME, TASK_CODE, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, SEGMENT_MAP_NAME, CONTACT_DATE, CONTACT_DTTM, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, EMAIL_CLICK_DTTM )
AS SELECT TASK_NAME, TASK_CODE, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, SEGMENT_MAP_NAME, CONTACT_DATE, CONTACT_DTTM, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, EMAIL_CLICK_DTTM
FROM WARNER_RAW.MA_MART.D_WRN_CONTACT_RESPONSE;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_HOUSEHOLD
( ADDRESS_ID )
AS SELECT ADDRESS_ID
FROM WARNER_RAW.MA_MART.D_WRN_HOUSEHOLD;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_KPIS_OUTPUT_DASHBOARD 
( ARRIVAL_PERIOD, SEG, RELATIVE_EVENT_PERIOD, RELATIVE_EVENT_WEEK, BOOK_TYPE, EVENT_TIME, GROSS_HOUSEHOLDS, GROSS_BOOKINGS, GROSS_GUEST_WEEKS, GROSS_GROSS_TARIFF, GROSS_BOOKINGS_ACTUAL, GROSS_HOUSEHOLDS_ACTUAL, GROSS_GUEST_WEEKS_ACTUAL, GROSS_GROSS_TARIFF_ACTUAL, CANCEL_BOOKINGS_ACTUAL, CANCEL_HOUSEHOLDS_ACTUAL, CANCEL_GUEST_WEEKS_ACTUAL, CANCEL_GROSS_TARIFF_ACTUAL, SITE_NAME, CHANNEL, GROSS_BOOKINGS_BASE, GROSS_HOUSEHOLDS_BASE, GROSS_GUEST_WEEKS_BASE, GROSS_GROSS_TARIFF_BASE, FLG_UPTO_WEEK, BOOKING_CHANNEL_CD, SITE_CD, EVENT_WEEK_YEAR, NET_BOOKINGS_ACTUAL, NET_HOUSEHOLDS_ACTUAL, NET_GUEST_WEEKS_ACTUAL, NET_GROSS_TARIFF_ACTUAL, STARTING_HOUSEHOLDS, GROSS_RETENTION_BASE, GROSS_RETENTION_ACTUAL, FLG_52_WEEK, EVENT_YEAR )
AS SELECT ARRIVAL_PERIOD, SEG, RELATIVE_EVENT_PERIOD, RELATIVE_EVENT_WEEK, BOOK_TYPE, EVENT_TIME, GROSS_HOUSEHOLDS, GROSS_BOOKINGS, GROSS_GUEST_WEEKS, GROSS_GROSS_TARIFF, GROSS_BOOKINGS_ACTUAL, GROSS_HOUSEHOLDS_ACTUAL, GROSS_GUEST_WEEKS_ACTUAL, GROSS_GROSS_TARIFF_ACTUAL, CANCEL_BOOKINGS_ACTUAL, CANCEL_HOUSEHOLDS_ACTUAL, CANCEL_GUEST_WEEKS_ACTUAL, CANCEL_GROSS_TARIFF_ACTUAL, SITE_NAME, CHANNEL, GROSS_BOOKINGS_BASE, GROSS_HOUSEHOLDS_BASE, GROSS_GUEST_WEEKS_BASE, GROSS_GROSS_TARIFF_BASE, FLG_UPTO_WEEK, BOOKING_CHANNEL_CD, SITE_CD, EVENT_WEEK_YEAR, NET_BOOKINGS_ACTUAL, NET_HOUSEHOLDS_ACTUAL, NET_GUEST_WEEKS_ACTUAL, NET_GROSS_TARIFF_ACTUAL, STARTING_HOUSEHOLDS, GROSS_RETENTION_BASE, GROSS_RETENTION_ACTUAL, FLG_52_WEEK, EVENT_YEAR
FROM WARNER_RAW.MA_MART.D_WRN_KPIS_OUTPUT_DASHBOARD;

CREATE VIEW WARNER_BASE.MA_MART.D_WRN_KPIS_SUMMARY
( ARRIVAL_YEAR, ARRIVAL_PERIOD, EVENT_YEAR, EVENT_PERIOD, EVENT_WEEK, SEG, SITE_CD, NEW_REPEAT, BOOKING_CHANNEL_CD, BOOK_TYPE, EVENT_TYPE, FESTIVE_FLAG, NB_EVENTS, BOOKINGS, GUEST_WEEKS, GROSS_TARIFF, HOUSEHOLDS, SITE_NAME, CHANNEL, F_YEAR, A_YEAR, EVENT_WEEK_YEAR, FLG_UPTO_WEEK, FLG_52_WEEK, BY_DAY1, BY_P01, BY_P02, BY_P03, BY_P04, BY_P05, BY_P06, BY_P07, BY_P08, BY_P09, BY_P10, BY_P11, BY_P12, HH_RETENTION )
AS SELECT ARRIVAL_YEAR, ARRIVAL_PERIOD, EVENT_YEAR, EVENT_PERIOD, EVENT_WEEK, SEG, SITE_CD, NEW_REPEAT, BOOKING_CHANNEL_CD, BOOK_TYPE, EVENT_TYPE, FESTIVE_FLAG, NB_EVENTS, BOOKINGS, GUEST_WEEKS, GROSS_TARIFF, HOUSEHOLDS, SITE_NAME, CHANNEL, F_YEAR, A_YEAR, EVENT_WEEK_YEAR, FLG_UPTO_WEEK, FLG_52_WEEK, BY_DAY1, BY_P01, BY_P02, BY_P03, BY_P04, BY_P05, BY_P06, BY_P07, BY_P08, BY_P09, BY_P10, BY_P11, BY_P12, HH_RETENTION
FROM WARNER_RAW.MA_MART.D_WRN_KPIS_SUMMARY;

--11/06/2024

USE ROLE useradmin;

SHOW USERS LIKE 'david%';

SHOW GRANTS TO USER DAVIDPARSONS;

USE ROLE securityadmin;

GRANT ROLE HAVEN_COMMERCIAL_DAVIDPARSONS TO USER DAVIDPARSONS;
GRANT ROLE HAVEN_PEOPLE_DATA_RESTRICTED TO USER DAVIDPARSONS;

REVOKE ROLE HAVEN_COMMERCIAL_DAVIDPARSONS FROM USER DAVIDPARSONS;
REVOKE ROLE HAVEN_PEOPLE_DATA_RESTRICTED FROM USER DAVIDPARSONS;
GRANT ROLE warner_insights_analytics TO USER DAVIDPARSONS;
