USE ROLE DBA;

-- WARNER_BASE.FINANCIAL_CUBE.DIM_ANALYSIS_ELEMENT source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_ANALYSIS_ELEMENT (
	ANALYSIS_ELEMENT_REF,
	ANALYSIS_ELEMENT
) as select ANALYSIS_ELEMENT_REF,ANALYSIS_ELEMENT 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_ANALYSIS_ELEMENT;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD (
	ARRIVAL_PERIOD_REF,
	ARRIVAL_PERIOD_NUMBER,
	ARRIVAL_PERIOD_NAME
) as select ARRIVAL_PERIOD_REF,ARRIVAL_PERIOD_NUMBER,ARRIVAL_PERIOD_NAME 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD_CP source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD_CP (
	ARRIVAL_PERIOD_REF,
	ARRIVAL_PERIOD_NUMBER,
	ARRIVAL_PERIOD_NAME
) as select ARRIVAL_PERIOD_REF,ARRIVAL_PERIOD_NUMBER,ARRIVAL_PERIOD_NAME 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD_CP;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_STATUS source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_STATUS (
	ARRIVAL_STATUS_REF,
	ARRIVAL_STATUS
) as select ARRIVAL_STATUS_REF,ARRIVAL_STATUS 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_ARRIVAL_STATUS;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_BOOKINGSOURCE source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_BOOKINGSOURCE (
	BOOKINGSOURCE_REF,
	BOOKINGSOURCE,
	BOOKINGSOURCE_TITLE
) as select BOOKINGSOURCE_REF,BOOKINGSOURCE,BOOKINGSOURCE_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_BOOKINGSOURCE;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_BRAND source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_BRAND (
	BRAND_REF,
	BRAND_TITLE
) as select BRAND_REF,BRAND_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_BRAND  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_CALENDAR source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_CALENDAR (
	DAY_IDX,
	CALENDAR_DATE,
	CALENDAR_WEEK,
	CALENDAR_MONTH,
	CALENDAR_QUATER,
	CALENDAR_YEAR,
	STAT_WEEK_END_DATE,
	STAT_PERIOD,
	STAT_MONTH,
	STAT_YEAR
) as select DAY_IDX,CALENDAR_DATE,CALENDAR_WEEK,CALENDAR_MONTH,CALENDAR_QUATER,CALENDAR_YEAR,STAT_WEEK_END_DATE,STAT_PERIOD,STAT_MONTH,STAT_YEAR 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_CALENDAR;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_CASHFLOW source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_CASHFLOW (
	CASHFLOW_REF,
	CASHFLOW,
	CASHFLOW_TITLE
) as select CASHFLOW_REF,CASHFLOW,CASHFLOW_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_CASHFLOW;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_CPARKPL source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_CPARKPL (
	CPARKPL_REF,
	CPARKPL,
	CPARKPL_TITLE
) as select CPARKPL_REF,CPARKPL,CPARKPL_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_CPARKPL;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_DEBT_RANGE source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_DEBT_RANGE (
	DEBT_RANGE_REF,
	MIN_VALUE,
	MAX_VALUE,
	DEBT_RANGE_TITLE
) as select DEBT_RANGE_REF,MIN_VALUE,MAX_VALUE,DEBT_RANGE_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_DEBT_RANGE;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_DEPARTMENT source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_DEPARTMENT (
	DEPARTMENT_REF,
	DEPARTMENT,
	DEPARTMENT_TITLE
) as select DEPARTMENT_REF,DEPARTMENT,DEPARTMENT_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_DEPARTMENT;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_PRODUCT source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_PRODUCT (
	HOLIDAY_PRODUCT_REF,
	HOLIDAY_PRODUCT
) as select HOLIDAY_PRODUCT_REF,HOLIDAY_PRODUCT 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_HOLIDAY_PRODUCT;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_YEAR source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_YEAR (
	HOLIDAY_YEAR_REF,
	HOLIDAY_YEAR,
	TROOPER_SEASON
) as select HOLIDAY_YEAR_REF,HOLIDAY_YEAR,TROOPER_SEASON 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_HOLIDAY_YEAR;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAYDURATION source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAYDURATION (
	HOLIDAYDURATION_REF,
	HOLIDAYDURATION,
	HOLIDAYDURATION_TITLE
) as select HOLIDAYDURATION_REF,HOLIDAYDURATION,HOLIDAYDURATION_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_HOLIDAYDURATION;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_LEDGER source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_LEDGER (
	LEDGER_REF,
	BRAND_REF,
	LEDGER,
	LEDGER_TITLE
) as select LEDGER_REF,BRAND_REF,LEDGER,LEDGER_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_LEDGER  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_LEDGER_ACCOUNT source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_LEDGER_ACCOUNT (
	LEDGER_ACCOUNT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT,
	LEDGER_ACCOUNT_TITLE
) as select LEDGER_ACCOUNT_REF,LEDGER_REF,LEDGER_ACCOUNT,LEDGER_ACCOUNT_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_LEDGER_ACCOUNT;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_LIMBO source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_LIMBO (
	LIMBO_REF,
	LIMBO_VALUE,
	LIMBO_DESCRIPTION
) as select LIMBO_REF,LIMBO_VALUE,LIMBO_DESCRIPTION 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_LIMBO;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_LOCATION source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_LOCATION (
	LOCATION_REF,
	BRAND_REF,
	BRAND_TITLE,
	SITE_REF,
	SITE_CODE,
	SITE_NAME,
	SITE_OPS_DIRECTOR,
	AREA_CODE,
	AREA_NAME,
	ZONE_CODE,
	ZONE_NAME,
	PLOT_PITCH_ID,
	PITCH_NAME
) as select LOCATION_REF,BRAND_REF,BRAND_TITLE,SITE_REF,SITE_CODE,SITE_NAME,SITE_OPS_DIRECTOR,AREA_CODE,AREA_NAME,ZONE_CODE,ZONE_NAME,PLOT_PITCH_ID,PITCH_NAME 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_LOCATION  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_NOMINAL source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_NOMINAL (
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER3_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	NOMINAL,
	NOMINAL_CODE,
	NOMINAL_TITLE,
	DISABLE,
	CPARKPL_REF
) as select NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER3_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,NOMINAL,NOMINAL_CODE,NOMINAL_TITLE,DISABLE,CPARKPL_REF 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_NOMINAL  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PERIOD source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_PERIOD (
	PERIOD_REF,
	STATYEAR,
	STATMONTH,
	STATPERIOD,
	STATPERIODLY,
	WEEKENDDATE
) as select PERIOD_REF,STATYEAR,STATMONTH,STATPERIOD,STATPERIODLY,WEEKENDDATE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PERIOD;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_CARAVAN_SALES source

--	CARAVAN_SALES_REF,
--	BRAND_REF,
--	SALES_CSI_NO,
--	SALES_TYPE
--) as select CARAVAN_SALES_REF,BRAND_REF,SALES_CSI_NO,SALES_TYPE 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_CARAVAN_SALES  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_LETTING_CATAGORY source

--	LETTING_CATAGORY_REF,
--	BRAND_REF,
--	LETTING_CATAGORY_CODE,
--	LETTING_CATAGORY_TITLE
--) as select LETTING_CATAGORY_REF,BRAND_REF,LETTING_CATAGORY_CODE,LETTING_CATAGORY_TITLE 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_LETTING_CATAGORY  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT source

--	OWNER_ACCOUNT_REF,
--	BRAND_REF,
--	ACCOUNT_NO,
--	OWNER_ID,
--	OWNER_NAME,
--	OWNER_ADDRESS1,
--	OWNER_ADDRESS2,
--	OWNER_ADDRESS3,
--	OWNER_ADDRESS4,
--	OWNER_POSTCODE
--) as select OWNER_ACCOUNT_REF,BRAND_REF,ACCOUNT_NO,OWNER_ID,OWNER_NAME,OWNER_ADDRESS1,OWNER_ADDRESS2,OWNER_ADDRESS3,OWNER_ADDRESS4,OWNER_POSTCODE 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT_NEW source

--	OWNER_ACCOUNT_REF,
--	BRAND_REF,
--	ACCOUNT_NO,
--	OWNER_ID,
--	OWNER_NAME,
--	OWNER_ADDRESS1,
--	OWNER_ADDRESS2,
--	OWNER_ADDRESS3,
--	OWNER_ADDRESS4,
--	OWNER_POSTCODE,
--	SITE_FEES
--) as select OWNER_ACCOUNT_REF,BRAND_REF,ACCOUNT_NO,OWNER_ID,OWNER_NAME,OWNER_ADDRESS1,OWNER_ADDRESS2,OWNER_ADDRESS3,OWNER_ADDRESS4,OWNER_POSTCODE,SITE_FEES 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_OWNER_ACCOUNT_NEW  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH source

--	PITCH_REF,
--	BRAND_REF,
--	SITE_REF,
--	PITCH_NO,
--	AREA_CODE,
--	AREA_NAME,
--	ZONE_CODE,
--	ZONE_NAME,
--	PITCH_TYPE,
--	PLOT_PITCH_ID
--) as select PITCH_REF,BRAND_REF,SITE_REF,PITCH_NO,AREA_CODE,AREA_NAME,ZONE_CODE,ZONE_NAME,PITCH_TYPE,PLOT_PITCH_ID 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_PITCH  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS source

--	PITCH_STATUS_REF,
--	BRAND_REF,
--	PITCH_STATUS_CODE,
--	PITCH_STATUS_TITLE
--) as select PITCH_STATUS_REF,BRAND_REF,PITCH_STATUS_CODE,PITCH_STATUS_TITLE 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS_NEW source

--	PITCH_STATUS_REF,
--	PITCH_STATUS_CODE,
--	PITCH_STATUS_TITLE
--) as select PITCH_STATUS_REF,PITCH_STATUS_CODE,PITCH_STATUS_TITLE 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_PITCH_STATUS_NEW;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_VAN source

--	VAN_REF,
--	BRAND_REF,
--	VAN_NO,
--	VAN_MAKE,
--	VAN_MODEL,
--	VAN_YEAR_MADE,
--	VAN_LENGTH,
--	VAN_WIDTH,
--	VAN_TYPE
--) as select VAN_REF,BRAND_REF,VAN_NO,VAN_MAKE,VAN_MODEL,VAN_YEAR_MADE,VAN_LENGTH,VAN_WIDTH,VAN_TYPE 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_VAN  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PLOT_VAN_DELIVERED_STATUS source

--	VAN_DELIVERY_REF,
--	VAN_DELIVERY_STATUS
--) as select VAN_DELIVERY_REF,VAN_DELIVERY_STATUS 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PLOT_VAN_DELIVERED_STATUS;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_PRODUCT source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_PRODUCT (
	PRODUCT_REF,
	PRODUCT
) as select PRODUCT_REF,PRODUCT 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_PRODUCT;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_RETAIL_INCOME_GROUP source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_RETAIL_INCOME_GROUP (
	RETAIL_INCOME_GROUP_REF,
	NAME,
	LEVEL1_NAME
) as select RETAIL_INCOME_GROUP_REF,NAME,LEVEL1_NAME 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_RETAIL_INCOME_GROUP;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_RETAIL_WEEKS_TYPE source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_RETAIL_WEEKS_TYPE (
	RETAIL_SPEND_TYPE_REF,
	DESCRIPTION
) as select RETAIL_SPEND_TYPE_REF,DESCRIPTION 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_RETAIL_WEEKS_TYPE;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_SALES_CHANNEL source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_SALES_CHANNEL (
	SALES_CHANNEL_REF,
	SALES_CHANNEL,
	TROOPER_CHANNEL,
	BUTLINS_CHANNEL,
	BUTLINS_CHANNEL_2,
	WARNER_CHANNEL,
	WARNER_CHANNEL_2
) as select SALES_CHANNEL_REF,SALES_CHANNEL,TROOPER_CHANNEL,BUTLINS_CHANNEL,BUTLINS_CHANNEL_2,WARNER_CHANNEL,WARNER_CHANNEL_2 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_SALES_CHANNEL;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_SITE source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_SITE (
	SITE_REF,
	BRAND_REF,
	SITE_CODE,
	SITE_TROOPER_CODE,
	SITE_NAME,
	SITE_REGION_REF,
	SITE_OPS_DIRECTOR,
	SITE_GENERAL_MANAGER,
	SITE_SALES_MANAGER,
	SITE_COMPLEX_MANAGER,
	SITE_SHOP_MANAGER,
	SITE_SPORTS_MANAGER,
	SITE_ENTS_MANAGER,
	SITE_HOLIDAY_SALES_MANAGER,
	SITE_CATERING_MANAGER,
	SITE_STATUS_REF,
	SITE_ACCOMODATION_MANAGER,
	STATUTORY_CO_1,
	STATUTORY_CO_2,
	STATUTORY_CO_3,
	STATUTORY_CO_4,
	STATUTORY_CO_5,
	STATUTORY_CO_6,
	COMPANY_CODE
) as select SITE_REF,BRAND_REF,SITE_CODE,SITE_TROOPER_CODE,SITE_NAME,SITE_REGION_REF,SITE_OPS_DIRECTOR,SITE_GENERAL_MANAGER,SITE_SALES_MANAGER,SITE_COMPLEX_MANAGER,SITE_SHOP_MANAGER,SITE_SPORTS_MANAGER,SITE_ENTS_MANAGER,SITE_HOLIDAY_SALES_MANAGER,SITE_CATERING_MANAGER,SITE_STATUS_REF,SITE_ACCOMODATION_MANAGER,STATUTORY_CO_1,STATUTORY_CO_2,STATUTORY_CO_3,STATUTORY_CO_4,STATUTORY_CO_5,STATUTORY_CO_6,COMPANY_CODE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_SITE  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_SITE_FEE_BANDS source

--	SITE_FEE_BAND_REF,
--	SITE_FEE_BAND_NAME,
--	MIN_VALUE,
--	MAX_VALUE
--) as select SITE_FEE_BAND_REF,SITE_FEE_BAND_NAME,MIN_VALUE,MAX_VALUE 
--FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_SITE_FEE_BANDS;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_STATSSUM source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_STATSSUM (
	STATSSUM_REF,
	STATSSUM_PAGE,
	STATSSUM_SUBSECTION,
	STATSSUM_TITLE,
	STATSSUM,
	STATSSUM_ORDERBY
) as select STATSSUM_REF,STATSSUM_PAGE,STATSSUM_SUBSECTION,STATSSUM_TITLE,STATSSUM,STATSSUM_ORDERBY 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_STATSSUM;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_SUB_DEPARTMENT source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_SUB_DEPARTMENT (
	SUB_DEPARTMENT_REF,
	SUB_DEPARTMENT,
	SUB_DEPARTMENT_TITLE
) as select SUB_DEPARTMENT_REF,SUB_DEPARTMENT,SUB_DEPARTMENT_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_SUB_DEPARTMENT;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_TRADITIONAL_P_AND_L source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_TRADITIONAL_P_AND_L (
	TRADITIONAL_P_AND_L_REF,
	TRADITIONAL_P_AND_L,
	TRADITIONAL_P_AND_L_TITLE
) as select TRADITIONAL_P_AND_L_REF,TRADITIONAL_P_AND_L,TRADITIONAL_P_AND_L_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_TRADITIONAL_P_AND_L;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_VERSION source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_VERSION (
	VERSION_REF,
	VERSION_TITLE
) as select VERSION_REF,VERSION_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_VERSION;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_ANALYSIS source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_ANALYSIS (
	WAGES_ANALYSIS_REF,
	WAGES_ANALYSIS,
	WAGES_ANALYSIS_TITLE
) as select WAGES_ANALYSIS_REF,WAGES_ANALYSIS,WAGES_ANALYSIS_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_WAGES_ANALYSIS;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_STAFFCONTRACT source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_STAFFCONTRACT (
	WAGES_STAFFCONTRACT_REF,
	WAGES_STAFFCONTRACT,
	WAGES_STAFFCONTRACT_TITLE
) as select WAGES_STAFFCONTRACT_REF,WAGES_STAFFCONTRACT,WAGES_STAFFCONTRACT_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_WAGES_STAFFCONTRACT;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_SUMMARY source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_SUMMARY (
	WAGES_SUMMARY_REF,
	WAGES_SUMMARY,
	WAGES_SUMMARY_TITLE
) as select WAGES_SUMMARY_REF,WAGES_SUMMARY,WAGES_SUMMARY_TITLE 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_WAGES_SUMMARY;


-- WARNER_BASE.FINANCIAL_CUBE.DIM_YESNO source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIM_YESNO (
	REF,
	YESNOVALUE,
	YESNOTEXT
) as select REF,YESNOVALUE,YESNOTEXT 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIM_YESNO;


-- WARNER_BASE.FINANCIAL_CUBE.DIMTIME source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.DIMTIME (
	PK_DATE,
	DATE_NAME,
	YEAR,
	YEAR_NAME,
	MONTH,
	MONTH_NAME,
	WEEK,
	WEEK_NAME,
	DAY_OF_YEAR,
	DAY_OF_YEAR_NAME,
	DAY_OF_MONTH,
	DAY_OF_MONTH_NAME,
	DAY_OF_WEEK,
	DAY_OF_WEEK_NAME,
	WEEK_OF_YEAR,
	WEEK_OF_YEAR_NAME,
	MONTH_OF_YEAR,
	MONTH_OF_YEAR_NAME,
	STATYEAR,
	STATPERIOD,
	STATMONTH
) as select PK_DATE,DATE_NAME,YEAR,YEAR_NAME,MONTH,MONTH_NAME,WEEK,WEEK_NAME,DAY_OF_YEAR,DAY_OF_YEAR_NAME,DAY_OF_MONTH,DAY_OF_MONTH_NAME,DAY_OF_WEEK,DAY_OF_WEEK_NAME,WEEK_OF_YEAR,WEEK_OF_YEAR_NAME,MONTH_OF_YEAR,MONTH_OF_YEAR_NAME,STATYEAR,STATPERIOD,STATMONTH 
FROM BOURNE_RAW.FINANCIAL_CUBE.DIMTIME;


-- WARNER_BASE.FINANCIAL_CUBE.ETL_CONTROL source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.ETL_CONTROL (
	LAST_TRANSFER,
	LAST_DURATION
) as select LAST_TRANSFER,LAST_DURATION 
FROM BOURNE_RAW.FINANCIAL_CUBE.ETL_CONTROL;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_BILLINGS_ANALYSIS source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_BILLINGS_ANALYSIS (
	BUSINESSKEY,
	BRAND_REF,
	SITE_REF,
	HOLIDAY_PRODUCT_REF,
	VERSION_REF,
	PERIOD_REF,
	HOLIDAY_YEAR_REF,
	ANALYSIS_ELEMENT_REF,
	ARRIVAL_STATUS_REF,
	WEEK_BILLINGS_PRIORSEASON,
	WEEK_BILLINGS_CURRENTSEASON,
	YTD_BILLINGS_PRIORSEASON,
	YTD_BILLINGS_CURRENTSEASON,
	YEAR_BILLINGS_PRIORSEASON,
	WEEK_BILLINGS_BUDGET,
	YTD_BILLINGS_BUDGET,
	YEAR_BILLINGS_BUDGET,
	WEEK_WEEKS_PRIORSEASON,
	WEEK_WEEKS_CURRENTSEASON,
	YTD_WEEKS_PRIORSEASON,
	YTD_WEEKS_CURRENTSEASON,
	YEAR_WEEKS_PRIORSEASON,
	WEEK_WEEKS_BUDGET,
	YTD_WEEKS_BUDGET,
	YEAR_WEEKS_BUDGET
) as select BUSINESSKEY,BRAND_REF,SITE_REF,HOLIDAY_PRODUCT_REF,VERSION_REF,PERIOD_REF,HOLIDAY_YEAR_REF,ANALYSIS_ELEMENT_REF,ARRIVAL_STATUS_REF,WEEK_BILLINGS_PRIORSEASON,WEEK_BILLINGS_CURRENTSEASON,YTD_BILLINGS_PRIORSEASON,YTD_BILLINGS_CURRENTSEASON,YEAR_BILLINGS_PRIORSEASON,WEEK_BILLINGS_BUDGET,YTD_BILLINGS_BUDGET,YEAR_BILLINGS_BUDGET,WEEK_WEEKS_PRIORSEASON,WEEK_WEEKS_CURRENTSEASON,YTD_WEEKS_PRIORSEASON,YTD_WEEKS_CURRENTSEASON,YEAR_WEEKS_PRIORSEASON,WEEK_WEEKS_BUDGET,YTD_WEEKS_BUDGET,YEAR_WEEKS_BUDGET 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_BILLINGS_ANALYSIS  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_BUDGET_TB source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_BUDGET_TB (
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT_REF,
	LEDGER3_REF,
	LEDGER3_ACCOUNT_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	VERSION_REF,
	PERIOD_REF,
	WEEK_VALUE,
	WEEK_USERVALUE,
	YTD_VALUE,
	YTD_USERVALUE,
	CPARKPL_REF
) as select NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER_ACCOUNT_REF,LEDGER3_REF,LEDGER3_ACCOUNT_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,VERSION_REF,PERIOD_REF,WEEK_VALUE,WEEK_USERVALUE,YTD_VALUE,YTD_USERVALUE,CPARKPL_REF 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_BUDGET_TB  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_COMPLETEDHOLIDAYS_TB source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_COMPLETEDHOLIDAYS_TB (
	BRAND_REF,
	SITE_REF,
	VERSION_REF,
	PERIOD_REF,
	LETTING_CATAGORY_REF,
	HOLIDAY_PRODUCT_REF,
	BOOKINGSOURCE_REF,
	WEEK_ARRIVAL_DATE_REF,
	WEEK_DEPARTURE_DATE_REF,
	WEEK_DURATION_REF,
	LYPERIODLAG,
	UNIT_WEEK_VALUE,
	GUEST_WEEK_VALUE
) as select BRAND_REF,SITE_REF,VERSION_REF,PERIOD_REF,LETTING_CATAGORY_REF,HOLIDAY_PRODUCT_REF,BOOKINGSOURCE_REF,WEEK_ARRIVAL_DATE_REF,WEEK_DEPARTURE_DATE_REF,WEEK_DURATION_REF,LYPERIODLAG,UNIT_WEEK_VALUE,GUEST_WEEK_VALUE 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_COMPLETEDHOLIDAYS_TB  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_HEAD_COUNTS source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_HEAD_COUNTS (
	IDENT,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	PERIOD_REF,
	WAGES_SUMMARY_REF,
	ACTUAL_PERMANENTFTES,
	ACTUAL_SEASONALFTES,
	ACTUAL_TOTALFTES,
	BUDGET_PERMANENTFTES,
	BUDGET_SEASONALFTES,
	BUDGET_TOTALFTES,
	LASTYEAR_PERMANENTFTES,
	LASTYEAR_SEASONALFTES,
	LASTYEAR_TOTALFTES
) as select IDENT,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,PERIOD_REF,WAGES_SUMMARY_REF,ACTUAL_PERMANENTFTES,ACTUAL_SEASONALFTES,ACTUAL_TOTALFTES,BUDGET_PERMANENTFTES,BUDGET_SEASONALFTES,BUDGET_TOTALFTES,LASTYEAR_PERMANENTFTES,LASTYEAR_SEASONALFTES,LASTYEAR_TOTALFTES 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_HEAD_COUNTS  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_HISTORIC_TB source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_HISTORIC_TB (
	IDENT,
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT_REF,
	LEDGER3_REF,
	LEDGER3_ACCOUNT_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	VERSION_REF,
	PERIOD_REF,
	WEEK_VALUE,
	WEEK_USERVALUE,
	WEEK_USERVALUEFIELD1,
	WEEK_USERVALUEFIELD2,
	WEEK_USERVALUEFIELD3,
	WEEK_USERVALUEFIELD4,
	LAST_4_WEEKS_VALUE,
	LAST_4__USERVALUE,
	LAST_4__USERVALUEFIELD1,
	LAST_4__USERVALUEFIELD2,
	LAST_4__USERVALUEFIELD3,
	LAST_4__USERVALUEFIELD4,
	YTD_VALUE,
	YTD_USERVALUE,
	YTD_USERVALUEFIELD1,
	YTD_USERVALUEFIELD2,
	YTD_USERVALUEFIELD3,
	YTD_USERVALUEFIELD4,
	CPARKPL_REF
) as select IDENT,NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER_ACCOUNT_REF,LEDGER3_REF,LEDGER3_ACCOUNT_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,VERSION_REF,PERIOD_REF,WEEK_VALUE,WEEK_USERVALUE,WEEK_USERVALUEFIELD1,WEEK_USERVALUEFIELD2,WEEK_USERVALUEFIELD3,WEEK_USERVALUEFIELD4,LAST_4_WEEKS_VALUE,LAST_4__USERVALUE,LAST_4__USERVALUEFIELD1,LAST_4__USERVALUEFIELD2,LAST_4__USERVALUEFIELD3,LAST_4__USERVALUEFIELD4,YTD_VALUE,YTD_USERVALUE,YTD_USERVALUEFIELD1,YTD_USERVALUEFIELD2,YTD_USERVALUEFIELD3,YTD_USERVALUEFIELD4,CPARKPL_REF 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_HISTORIC_TB  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_HOLIDAY_PERIODS source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_HOLIDAY_PERIODS (
	BUSINESSKEY,
	BRAND_REF,
	SITE_REF,
	HOLIDAY_PRODUCT_REF,
	VERSION_REF,
	PERIOD_REF,
	HOLIDAY_YEAR_REF,
	ARRIVAL_PERIOD_REF,
	ARRIVAL_PERIOD_REF_7,
	UNITWEEKS_CURRENTSEASON,
	GUESTWEEKS_CURRENTSEASON,
	BILLINGS_CURRENTSEASON,
	UNITWEEKS_BUDGET,
	GUESTWEEKS_BUDGET,
	BILLINGS_BUDGET,
	UNITWEEKS_PRIORSEASON,
	GUESTWEEKS_PRIORSEASON,
	BILLINGS_PRIORSEASON,
	UNITWEEKS_YEAREND_PRIORSEASON,
	GUESTWEEKS_YEAREND_PRIORSEASON,
	BILLINGS_YEAREND_PRIORSEASON,
	UNITS_CAPACITY,
	UNITS_SOLD
) as select BUSINESSKEY,BRAND_REF,SITE_REF,HOLIDAY_PRODUCT_REF,VERSION_REF,PERIOD_REF,HOLIDAY_YEAR_REF,ARRIVAL_PERIOD_REF,ARRIVAL_PERIOD_REF_7,UNITWEEKS_CURRENTSEASON,GUESTWEEKS_CURRENTSEASON,BILLINGS_CURRENTSEASON,UNITWEEKS_BUDGET,GUESTWEEKS_BUDGET,BILLINGS_BUDGET,UNITWEEKS_PRIORSEASON,GUESTWEEKS_PRIORSEASON,BILLINGS_PRIORSEASON,UNITWEEKS_YEAREND_PRIORSEASON,GUESTWEEKS_YEAREND_PRIORSEASON,BILLINGS_YEAREND_PRIORSEASON,UNITS_CAPACITY,UNITS_SOLD 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_HOLIDAY_PERIODS  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_HOLIDAYS source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_HOLIDAYS (
	IDENT,
	BUSINESSKEY,
	BRAND_REF,
	SITE_REF,
	HOLIDAY_PRODUCT_REF,
	VERSION_REF,
	PERIOD_REF,
	HOLIDAY_YEAR_REF,
	SALES_CHANNEL_REF,
	WEEK_NETTBILLINGS_CURRENTSEASON,
	WEEK_COMMISSIONS_CURRENTSEASON,
	WEEK_GROSSBILLINGS_CURRENTSEASON,
	WEEK_UNITWEEKS_CURRENTSEASON,
	WEEK_GUESTWEEKS_CURRENTSEASON,
	WEEK_NETTBILLINGS_BUDGET_CURRENTSEASON,
	WEEK_UNITWEEKS_BUDGET_CURRENTSEASON,
	WEEK_GUESTWEEKS_BUDGET_CURRENTSEASON,
	YTD_NETTBILLINGS_CURRENTSEASON,
	YTD_COMMISSIONS_CURRENTSEASON,
	YTD_GROSSBILLINGS_CURRENTSEASON,
	YTD_UNITWEEKS_CURRENTSEASON,
	YTD_GUESTWEEKS_CURRENTSEASON,
	YTD_NETTBILLINGS_BUDGET_CURRENTSEASON,
	YTD_UNITWEEKS_BUDGET_CURRENTSEASON,
	YTD_GUESTWEEKS_BUDGET_CURRENTSEASON,
	YEAR_NETTBILLINGS_BUDGET_CURRENTSEASON,
	YEAR_UNITWEEKS_BUDGET_CURRENTSEASON,
	YEAR_GUESTWEEKS_BUDGET_CURRENTSEASON,
	WEEK_NETTBILLINGS_PRIORSEASON,
	WEEK_COMMISSIONS_PRIORSEASON,
	WEEK_GROSSBILLINGS_PRIORSEASON,
	WEEK_UNITWEEKS_PRIORSEASON,
	WEEK_GUESTWEEKS_PRIORSEASON,
	YTD_NETTBILLINGS_PRIORSEASON,
	YTD_COMMISSIONS_PRIORSEASON,
	YTD_GROSSBILLINGS_PRIORSEASON,
	YTD_UNITWEEKS_PRIORSEASON,
	YTD_GUESTWEEKS_PRIORSEASON,
	YEAR_NETTBILLINGS_PRIORSEASON,
	YEAR_UNITWEEKS_PRIORSEASON,
	YEAR_GUESTWEEKS_PRIORSEASON,
	CARRIEDFORWARD_NETTBILLINGS_CURRENTSEASON,
	CARRIEDFORWARD_UNITWEEKS_CURRENTSEASON,
	CARRIEDFORWARD_GUESTWEEKS_CURRENTSEASON,
	CARRIEDFORWARD_NETTBILLINGS_PRIORSEASON,
	CARRIEDFORWARD_UNITWEEKS_PRIORSEASON,
	CARRIEDFORWARD_GUESTWEEKS_PRIORSEASON,
	CARRIEDFORWARD_NETTBILLINGS_BUDGET,
	CARRIEDFORWARD_UNITWEEKS_BUDGET,
	CARRIEDFORWARD_GUESTWEEKS_BUDGET
) as select IDENT,BUSINESSKEY,BRAND_REF,SITE_REF,HOLIDAY_PRODUCT_REF,VERSION_REF,PERIOD_REF,HOLIDAY_YEAR_REF,SALES_CHANNEL_REF,WEEK_NETTBILLINGS_CURRENTSEASON,WEEK_COMMISSIONS_CURRENTSEASON,WEEK_GROSSBILLINGS_CURRENTSEASON,WEEK_UNITWEEKS_CURRENTSEASON,WEEK_GUESTWEEKS_CURRENTSEASON,WEEK_NETTBILLINGS_BUDGET_CURRENTSEASON,WEEK_UNITWEEKS_BUDGET_CURRENTSEASON,WEEK_GUESTWEEKS_BUDGET_CURRENTSEASON,YTD_NETTBILLINGS_CURRENTSEASON,YTD_COMMISSIONS_CURRENTSEASON,YTD_GROSSBILLINGS_CURRENTSEASON,YTD_UNITWEEKS_CURRENTSEASON,YTD_GUESTWEEKS_CURRENTSEASON,YTD_NETTBILLINGS_BUDGET_CURRENTSEASON,YTD_UNITWEEKS_BUDGET_CURRENTSEASON,YTD_GUESTWEEKS_BUDGET_CURRENTSEASON,YEAR_NETTBILLINGS_BUDGET_CURRENTSEASON,YEAR_UNITWEEKS_BUDGET_CURRENTSEASON,YEAR_GUESTWEEKS_BUDGET_CURRENTSEASON,WEEK_NETTBILLINGS_PRIORSEASON,WEEK_COMMISSIONS_PRIORSEASON,WEEK_GROSSBILLINGS_PRIORSEASON,WEEK_UNITWEEKS_PRIORSEASON,WEEK_GUESTWEEKS_PRIORSEASON,YTD_NETTBILLINGS_PRIORSEASON,YTD_COMMISSIONS_PRIORSEASON,YTD_GROSSBILLINGS_PRIORSEASON,YTD_UNITWEEKS_PRIORSEASON,YTD_GUESTWEEKS_PRIORSEASON,YEAR_NETTBILLINGS_PRIORSEASON,YEAR_UNITWEEKS_PRIORSEASON,YEAR_GUESTWEEKS_PRIORSEASON,CARRIEDFORWARD_NETTBILLINGS_CURRENTSEASON,CARRIEDFORWARD_UNITWEEKS_CURRENTSEASON,CARRIEDFORWARD_GUESTWEEKS_CURRENTSEASON,CARRIEDFORWARD_NETTBILLINGS_PRIORSEASON,CARRIEDFORWARD_UNITWEEKS_PRIORSEASON,CARRIEDFORWARD_GUESTWEEKS_PRIORSEASON,CARRIEDFORWARD_NETTBILLINGS_BUDGET,CARRIEDFORWARD_UNITWEEKS_BUDGET,CARRIEDFORWARD_GUESTWEEKS_BUDGET 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_HOLIDAYS  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_OWNERSPERSITE_TB source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_OWNERSPERSITE_TB (
	BRAND_REF,
	SITE_REF,
	PERIOD_REF,
	VERSION_REF,
	ACCOUNT_REF,
	LETTING_STATUS,
	LYPERIODLAG,
	UNIT_WEEK_VALUE
) as select BRAND_REF,SITE_REF,PERIOD_REF,VERSION_REF,ACCOUNT_REF,LETTING_STATUS,LYPERIODLAG,UNIT_WEEK_VALUE 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_OWNERSPERSITE_TB  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_PLOT_PITCHES source

--	BRAND_REF,
--	SITE_REF,
--	PITCH_REF,
--	PITCH_STATUS_REF,
--	PERIOD_REF,
--	VAN_REF,
--	OWNER_ACCOUNT_REF,
--	NEW_CUSTOMER_SITE_FEE
--) as select BRAND_REF,SITE_REF,PITCH_REF,PITCH_STATUS_REF,PERIOD_REF,VAN_REF,OWNER_ACCOUNT_REF,NEW_CUSTOMER_SITE_FEE 
--FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_PITCHES  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER source

--	BRAND_REF,
--	OWNER_ACCOUNT_REF,
--	NOMINAL_REF,
--	PERIOD_REF,
--	SITE_REF,
--	VAN_REF,
--	VERSION_REF,
--	PITCH_REF,
--	PITCH_STATUS_REF,
--	RENT_LEDGER_BALANCE,
--	RENT_LEDGER_WEEK_CASH,
--	RENT_LEDGER_WEEK_BILLING,
--	RENT_LEDGER_WEEK_OTHER
--) as select BRAND_REF,OWNER_ACCOUNT_REF,NOMINAL_REF,PERIOD_REF,SITE_REF,VAN_REF,VERSION_REF,PITCH_REF,PITCH_STATUS_REF,RENT_LEDGER_BALANCE,RENT_LEDGER_WEEK_CASH,RENT_LEDGER_WEEK_BILLING,RENT_LEDGER_WEEK_OTHER 
--FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER_NEW source

--	LOCATION_REF,
--	OWNER_ACCOUNT_REF,
--	NOMINAL_REF,
--	WEEKENDDATE,
--	VAN_REF,
--	VERSION_REF,
--	PITCH_STATUS_REF,
--	DEBT_RANGE_REF,
--	LIMBO_REF,
--	SITE_FEE_BAND_REF,
--	RENT_LEDGER_BALANCE,
--	RENT_LEDGER_WEEK_CASH,
--	RENT_LEDGER_WEEK_BILLING,
--	RENT_LEDGER_WEEK_OTHER,
--	TOTAL_SITE_FEES
--) as select LOCATION_REF,OWNER_ACCOUNT_REF,NOMINAL_REF,WEEKENDDATE,VAN_REF,VERSION_REF,PITCH_STATUS_REF,DEBT_RANGE_REF,LIMBO_REF,SITE_FEE_BAND_REF,RENT_LEDGER_BALANCE,RENT_LEDGER_WEEK_CASH,RENT_LEDGER_WEEK_BILLING,RENT_LEDGER_WEEK_OTHER,TOTAL_SITE_FEES 
--FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_RENT_LEDGER_NEW;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_PLOT_SALES_LEDGER source

--	BRAND_REF,
--	CARAVAN_SALES_REF,
--	OWNER_ACCOUNT_REF,
--	NOMINAL_REF,
--	PERIOD_REF,
--	PERIOD_REF_DATE_SOLD,
--	PERIOD_REF_DATE_CANCELLED,
--	PERIOD_REF_DATE_COMPLETED,
--	SITE_REF,
--	VAN_REF_SOLD,
--	VAN_REF_PEX1,
--	VAN_REF_PEX2,
--	SALES_VALUE,
--	SALES_COST_OF_SALE,
--	SALES_MARGIN,
--	SALES_LEDGER_BALANCE,
--	SALES_PEX1_BOTTOM_BOOK_VALUE,
--	SALES_PEX1_DISCOUNT,
--	SALES_PEX2_BOTTOM_BOOK_VALUE,
--	SALES_PEX2_DISCOUNT,
--	SALES_GLB_AMOUNT,
--	SALES_RL_AMOUNT,
--	SALES_DUE_ON_ACCOUNT,
--	SALES_SUBLET_AMOUNT,
--	SALES_FINANCE_AMOUNT,
--	SALES_DEPOSIT_AMOUNT,
--	SALES_SVL_PRICE_SUB_TOTAL,
--	SALES_SVL_VAT_AMOUNT,
--	SALES_ORIGINAL_COST,
--	SALES_VALUE_STANDARD_RATED,
--	SALES_VALUE_ZERO_RATED,
--	SALES_GROSS_PRICE_TOTAL
--) as select BRAND_REF,CARAVAN_SALES_REF,OWNER_ACCOUNT_REF,NOMINAL_REF,PERIOD_REF,PERIOD_REF_DATE_SOLD,PERIOD_REF_DATE_CANCELLED,PERIOD_REF_DATE_COMPLETED,SITE_REF,VAN_REF_SOLD,VAN_REF_PEX1,VAN_REF_PEX2,SALES_VALUE,SALES_COST_OF_SALE,SALES_MARGIN,SALES_LEDGER_BALANCE,SALES_PEX1_BOTTOM_BOOK_VALUE,SALES_PEX1_DISCOUNT,SALES_PEX2_BOTTOM_BOOK_VALUE,SALES_PEX2_DISCOUNT,SALES_GLB_AMOUNT,SALES_RL_AMOUNT,SALES_DUE_ON_ACCOUNT,SALES_SUBLET_AMOUNT,SALES_FINANCE_AMOUNT,SALES_DEPOSIT_AMOUNT,SALES_SVL_PRICE_SUB_TOTAL,SALES_SVL_VAT_AMOUNT,SALES_ORIGINAL_COST,SALES_VALUE_STANDARD_RATED,SALES_VALUE_ZERO_RATED,SALES_GROSS_PRICE_TOTAL 
--FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_SALES_LEDGER  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_PLOT_VANS source

--	BRAND_REF,
--	VAN_REF,
--	PERIOD_REF,
--	SITE_REF,
--	PITCH_REF,
--	NOMINAL_REF,
--	PITCH_STATUS_REF,
--	LETTING_CATAGORY_REF,
--	VAN_EST_COST,
--	VAN_TRANSP_EST_COST,
--	VAN_HF_DEPREC_EST_COST,
--	VAN_TOTAL_VAT_COST,
--	VAN_TOTAL_EST_COST,
--	VAN_VAN_PRICE_TOTAL,
--	VAN_NEW_YN,
--	VAN_GLASSES_GUIDE_PRICE,
--	VAN_DELIVERY_STATUS_REF
--) as select BRAND_REF,VAN_REF,PERIOD_REF,SITE_REF,PITCH_REF,NOMINAL_REF,PITCH_STATUS_REF,LETTING_CATAGORY_REF,VAN_EST_COST,VAN_TRANSP_EST_COST,VAN_HF_DEPREC_EST_COST,VAN_TOTAL_VAT_COST,VAN_TOTAL_EST_COST,VAN_VAN_PRICE_TOTAL,VAN_NEW_YN,VAN_GLASSES_GUIDE_PRICE,VAN_DELIVERY_STATUS_REF 
--FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_PLOT_VANS  
--WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_RETAIL_TRADING source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_RETAIL_TRADING (
	BUSINESSKEY,
	PERIOD_REF,
	BRAND_REF,
	SITE_REF,
	VERSION_REF,
	LINEDESCRIPTION,
	COLUMN1,
	COLUMN2,
	COLUMN3,
	COLUMN5,
	COLUMN6,
	COLUMN8,
	COLUMN9,
	COLUMN10,
	COLUMN11
) as select BUSINESSKEY,PERIOD_REF,BRAND_REF,SITE_REF,VERSION_REF,LINEDESCRIPTION,COLUMN1,COLUMN2,COLUMN3,COLUMN5,COLUMN6,COLUMN8,COLUMN9,COLUMN10,COLUMN11 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_RETAIL_TRADING  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_TB source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_TB (
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT_REF,
	LEDGER3_REF,
	LEDGER3_ACCOUNT_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	VERSION_REF,
	PERIOD_REF,
	WEEK_VALUE,
	WEEK_USERVALUE,
	WEEK_USERVALUEFIELD1,
	WEEK_USERVALUEFIELD2,
	WEEK_USERVALUEFIELD3,
	WEEK_USERVALUEFIELD4,
	YTD_VALUE,
	YTD_USERVALUE,
	YTD_USERVALUEFIELD1,
	YTD_USERVALUEFIELD2,
	YTD_USERVALUEFIELD3,
	YTD_USERVALUEFIELD4,
	CPARKPL_REF
) as select NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER_ACCOUNT_REF,LEDGER3_REF,LEDGER3_ACCOUNT_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,VERSION_REF,PERIOD_REF,WEEK_VALUE,WEEK_USERVALUE,WEEK_USERVALUEFIELD1,WEEK_USERVALUEFIELD2,WEEK_USERVALUEFIELD3,WEEK_USERVALUEFIELD4,YTD_VALUE,YTD_USERVALUE,YTD_USERVALUEFIELD1,YTD_USERVALUEFIELD2,YTD_USERVALUEFIELD3,YTD_USERVALUEFIELD4,CPARKPL_REF 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_TB  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_TB_X source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_TB_X (
	NOMINAL_REF,
	BRAND_REF,
	SITE_REF,
	DEPARTMENT_REF,
	SUB_DEPARTMENT_REF,
	LEDGER_REF,
	LEDGER_ACCOUNT_REF,
	LEDGER3_REF,
	LEDGER3_ACCOUNT_REF,
	STATSSUM_REF,
	CASHFLOW_REF,
	WAGES_ANALYSIS_REF,
	WAGES_SUMMARY_REF,
	TRADITIONAL_P_AND_L_REF,
	VERSION_REF,
	PERIOD_REF,
	WEEK_VALUE,
	WEEK_USERVALUE,
	WEEK_USERVALUEFIELD1,
	WEEK_USERVALUEFIELD2,
	WEEK_USERVALUEFIELD3,
	WEEK_USERVALUEFIELD4,
	YTD_VALUE,
	YTD_USERVALUE,
	YTD_USERVALUEFIELD1,
	YTD_USERVALUEFIELD2,
	YTD_USERVALUEFIELD3,
	YTD_USERVALUEFIELD4,
	CPARKPL_REF
) as select NOMINAL_REF,BRAND_REF,SITE_REF,DEPARTMENT_REF,SUB_DEPARTMENT_REF,LEDGER_REF,LEDGER_ACCOUNT_REF,LEDGER3_REF,LEDGER3_ACCOUNT_REF,STATSSUM_REF,CASHFLOW_REF,WAGES_ANALYSIS_REF,WAGES_SUMMARY_REF,TRADITIONAL_P_AND_L_REF,VERSION_REF,PERIOD_REF,WEEK_VALUE,WEEK_USERVALUE,WEEK_USERVALUEFIELD1,WEEK_USERVALUEFIELD2,WEEK_USERVALUEFIELD3,WEEK_USERVALUEFIELD4,YTD_VALUE,YTD_USERVALUE,YTD_USERVALUEFIELD1,YTD_USERVALUEFIELD2,YTD_USERVALUEFIELD3,YTD_USERVALUEFIELD4,CPARKPL_REF 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_TB_X  
WHERE brand_ref = 3;


-- WARNER_BASE.FINANCIAL_CUBE.FACT_VAT source

create or replace secure view WARNER_BASE.FINANCIAL_CUBE.FACT_VAT (
	PERIOD_REF,
	VAT_RATE
) as select PERIOD_REF,VAT_RATE 
FROM BOURNE_RAW.FINANCIAL_CUBE.FACT_VAT;


-- WARNER_BASE.FINANCIAL_CUBE.STAGE_FACT_CARAVAN_SALES source

-- set up share of financial cube

USE ROLE useradmin;

CREATE ROLE warner_financial_cube_share;

USE ROLE accountadmin;

SHOW ACCOUNTS;

SHOW SHARES;

CREATE SHARE warner_financial_cube_share;

CREATE DATABASE ROLE warner_base.financial_cube_share;

GRANT USAGE ON DATABASE warner_base TO DATABASE ROLE warner_base.financial_cube_share;


GRANT USAGE ON SCHEMA warner_base.financial_cube TO DATABASE ROLE warner_base.financial_cube_share;

revoke SELECT ON VIEW WARNER_BASE.FINANCIAL_CUBE.FACT_TB from DATABASE ROLE warner_base.financial_cube_share;

GRANT USAGE ON DATABASE warner_base TO SHARE warner_financial_cube_share;
REVOKE REFERENCE_USAGE ON DATABASE warner_raw FROM SHARE warner_financial_cube_share;
GRANT REFERENCE_USAGE ON DATABASE bourne_raw TO SHARE warner_financial_cube_share;

GRANT DATABASE ROLE warner_base.financial_cube_share TO SHARE warner_financial_cube_share;

SHOW SHARES;

DROP DATABASE ROLE warner_base.financial_cube_share;
DROP SHARE warner_financial_cube_share;

USE ROLE securityadmin;

grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_ANALYSIS_ELEMENT  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_PERIOD_CP  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_ARRIVAL_STATUS  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_BOOKINGSOURCE  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_BRAND  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_CALENDAR  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_CASHFLOW  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_CPARKPL  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_DEBT_RANGE  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_DEPARTMENT  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_PRODUCT  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAY_YEAR  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_HOLIDAYDURATION  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_LEDGER  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_LEDGER_ACCOUNT  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_LIMBO  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_LOCATION  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_NOMINAL  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_PERIOD  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_PRODUCT  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_RETAIL_INCOME_GROUP  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_RETAIL_WEEKS_TYPE  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_SALES_CHANNEL  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_SITE  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_STATSSUM  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_SUB_DEPARTMENT  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_TRADITIONAL_P_AND_L  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_VERSION  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_ANALYSIS  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_STAFFCONTRACT  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_WAGES_SUMMARY  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIM_YESNO  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.DIMTIME  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.ETL_CONTROL  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_BILLINGS_ANALYSIS  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_BUDGET_TB  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_COMPLETEDHOLIDAYS_TB  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_HEAD_COUNTS  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_HISTORIC_TB  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_HOLIDAY_PERIODS  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_HOLIDAYS  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_OWNERSPERSITE_TB  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_RETAIL_TRADING  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_TB  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_TB_X  TO DATABASE ROLE warner_base.financial_cube_share;
grant select on view WARNER_BASE.FINANCIAL_CUBE.FACT_VAT  TO DATABASE ROLE warner_base.financial_cube_share;


USE ROLE accountadmin;

SHOW ACCOUNTS;

ALTER SHARE warner_financial_cube_share ADD ACCOUNTS = RL61979;

