create or replace schema SEAWARE_APS;

create or replace TABLE RES_GUEST_SEAWARE (
	GUEST_ID NUMBER(9,0) NOT NULL DEFAULT 0,
	GUEST_SEQN NUMBER(5,0) NOT NULL DEFAULT 0,
	OCCUPANCY_NUMBER NUMBER(2,0),
	RES_ID NUMBER(9,0) NOT NULL DEFAULT 0,
	CLIENT_ID NUMBER(9,0),
	GUEST_TYPE VARCHAR(20) NOT NULL DEFAULT '',
	AGE NUMBER(3,0),
	primary key (GUEST_ID)
);
create or replace view ACC_FORM_OF_TRANS(
	FORM_OF_TRANS,
	FORM_OF_TRANS_ID,
	COMMENTS,
	CLASS_OF_TRANS,
	FORM_OF_TRANS_NAME,
	IS_DEFAULT_FOR_CLASS,
	PROGRAM_NAME,
	PARAMS,
	SEQN,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT FORM_OF_TRANS, FORM_OF_TRANS_ID, COMMENTS, CLASS_OF_TRANS, FORM_OF_TRANS_NAME, IS_DEFAULT_FOR_CLASS, PROGRAM_NAME, PARAMS, SEQN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.ACC_FORM_OF_TRANS;
create or replace view ACC_INVOICE_DETAIL(
	ENTITY_TYPE,
	ENTITY_ID,
	PARAM_NAME,
	PARAM_VALUE,
	TIMESTAMP,
	RECORD_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT ENTITY_TYPE, ENTITY_ID, PARAM_NAME, PARAM_VALUE, "TIMESTAMP", RECORD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.ACC_INVOICE_DETAIL;
create or replace view ACC_TRANS_DETAIL(
	TRANS_ID,
	TRANS_STATUS,
	FORM_OF_TRANS,
	TRANS_TYPE,
	SOURCE_ENTITY_TYPE,
	SOURCE_ENTITY_ID,
	DEST_ENTITY_TYPE,
	DEST_ENTITY_ID,
	EXTERNAL_IDENT,
	BATCH_HDR_ID,
	CURRENCY_CODE,
	TRANS_AMOUNT,
	TRANS_AMOUNT_LEFT,
	TRANS_TIME_STAMP,
	TRANS_GROUP_ID,
	AMOUNT_ORIG_CURRENCY,
	COMMENTS,
	USER_ID,
	FIRST_TRANS_ID,
	PREV_TRANS_ID,
	VOIDED_TIME_STAMP,
	VOIDED_BY_USER_ID,
	APPROVED_TIME_STAMP,
	APPROVED_BY_USER_ID,
	TRANS_STATUS_TIME_STAMP,
	AMOUNT_ORIG_CURRENCY_LEFT,
	EXCHANGE_RATE,
	USE_EXTENDED_PAY,
	DUE_DATE,
	INSUR_PAID,
	CC_AUTH_CODE,
	OFFICE_CODE,
	AR_AP_SEQ_ID,
	AR_AP_TIME_STAMP,
	REF_TRANS_ID,
	AR_AP_DUE_DATE,
	MERCHANT_NUMBER,
	ACT_HIST_ID,
	INTERN_BALANCED_COM,
	FPR_ID,
	OFFICE_LOCATION,
	IS_MANUAL,
	BASE_ENTITY_TYPE,
	BASE_ENTITY_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "TRANS_ID", "TRANS_STATUS", "FORM_OF_TRANS", "TRANS_TYPE", "SOURCE_ENTITY_TYPE", "SOURCE_ENTITY_ID", "DEST_ENTITY_TYPE", "DEST_ENTITY_ID", "EXTERNAL_IDENT", "BATCH_HDR_ID", "CURRENCY_CODE", "TRANS_AMOUNT", "TRANS_AMOUNT_LEFT", "TRANS_TIME_STAMP", "TRANS_GROUP_ID", "AMOUNT_ORIG_CURRENCY", "COMMENTS", "USER_ID", "FIRST_TRANS_ID", "PREV_TRANS_ID", "VOIDED_TIME_STAMP", "VOIDED_BY_USER_ID", "APPROVED_TIME_STAMP", "APPROVED_BY_USER_ID", "TRANS_STATUS_TIME_STAMP", "AMOUNT_ORIG_CURRENCY_LEFT", "EXCHANGE_RATE", "USE_EXTENDED_PAY", "DUE_DATE", "INSUR_PAID", "CC_AUTH_CODE", "OFFICE_CODE", "AR_AP_SEQ_ID", "AR_AP_TIME_STAMP", "REF_TRANS_ID", "AR_AP_DUE_DATE", "MERCHANT_NUMBER", "ACT_HIST_ID", "INTERN_BALANCED_COM", "FPR_ID", "OFFICE_LOCATION", "IS_MANUAL", "BASE_ENTITY_TYPE", "BASE_ENTITY_ID", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."ACC_TRANS_DETAIL";
create or replace view ACC_TRANS_ENTITY_TYPE(
	ENTITY_TYPE,
	ENTITY_TYPE_ID,
	COMMENTS,
	TABLE_NAME,
	PMNT_DEST_FILTER,
	IS_EXTERNAL,
	BALANCE_CALC,
	CURRENCY_FILTER,
	SERVICE_NAME,
	IS_FINAL,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT ENTITY_TYPE, ENTITY_TYPE_ID, COMMENTS, TABLE_NAME, PMNT_DEST_FILTER, IS_EXTERNAL, BALANCE_CALC, CURRENCY_FILTER, SERVICE_NAME, IS_FINAL, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.ACC_TRANS_ENTITY_TYPE;
create or replace view ACC_TRANS_STATUS(
	TRANS_STATUS,
	TRANS_STATUS_ID,
	COMMENTS,
	TRANS_STATUS_CLASS,
	IS_BATCH,
	IS_CC_QUEUE,
	IS_REFUND_QUEUE,
	IS_CHECK_QUEUE,
	IS_INTERNAL,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT TRANS_STATUS, TRANS_STATUS_ID, COMMENTS, TRANS_STATUS_CLASS, IS_BATCH, IS_CC_QUEUE, IS_REFUND_QUEUE, IS_CHECK_QUEUE, IS_INTERNAL, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.ACC_TRANS_STATUS;
create or replace view ACC_TRANS_TYPE(
	TRANS_TYPE,
	TRANS_TYPE_ID,
	COMMENTS,
	TRANS_TYPE_CLASS,
	COMMISS_TYPE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT TRANS_TYPE, TRANS_TYPE_ID, COMMENTS, TRANS_TYPE_CLASS, COMMISS_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.ACC_TRANS_TYPE;
create or replace view AGENCY(
	AGENCY_ID,
	AGENCY_NAME_TYPED,
	AGENCY_NAME,
	ARC_NUMBER,
	IATA_NUMBER,
	CLIA_NUMBER,
	IS_ACTIVE,
	IS_DOMESTIC,
	IS_INTERNAL,
	USE_GUEST_ADDR,
	COMMENTS,
	MARKETING_MSG,
	IS_GSA,
	CONSORTIUM_TYPE,
	IS_CONSORTIUM,
	AGENCY_TYPE,
	DEFAULT_CURRENCY,
	VENDOR_NUMBER,
	USE_DFLT_CONSORTIUM,
	BC_TYPE_ID,
	TAXPAYER_TYPE,
	TAXPAYER_NUMBER,
	CONTACT_NAME,
	WEB_ADDRESS,
	AGENCY_NAME_ESSENTIAL,
	FLOATING_DEPOSIT,
	LANGUAGE_CODE,
	COUNTRY_CODE,
	OFFICE_CODE,
	AG_ENTITY_TYPE,
	IS_FAX_EMAIL_SECURED,
	ABTA_NUMBER,
	NOTIF_DFLT_DISTR_TYPE,
	FPR_AT_GROSS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "AGENCY_ID", "AGENCY_NAME_TYPED", "AGENCY_NAME", "ARC_NUMBER", "IATA_NUMBER", "CLIA_NUMBER", "IS_ACTIVE", "IS_DOMESTIC", "IS_INTERNAL", "USE_GUEST_ADDR", "COMMENTS", "MARKETING_MSG", "IS_GSA", "CONSORTIUM_TYPE", "IS_CONSORTIUM", "AGENCY_TYPE", "DEFAULT_CURRENCY", "VENDOR_NUMBER", "USE_DFLT_CONSORTIUM", "BC_TYPE_ID", "TAXPAYER_TYPE", "TAXPAYER_NUMBER", "CONTACT_NAME", "WEB_ADDRESS", "AGENCY_NAME_ESSENTIAL", "FLOATING_DEPOSIT", "LANGUAGE_CODE", "COUNTRY_CODE", "OFFICE_CODE", "AG_ENTITY_TYPE", "IS_FAX_EMAIL_SECURED", "ABTA_NUMBER", "NOTIF_DFLT_DISTR_TYPE", "FPR_AT_GROSS", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."AGENCY";
create or replace view AGENCY_ADDRESS(
	AGENCY_ID,
	SEQ_NUMBER,
	ADDRESS_TYPE,
	ADDRESS_LINE1,
	ADDRESS_LINE2,
	ADDRESS_CITY,
	STATE_CODE,
	ZIP,
	COUNTRY_CODE,
	IS_ADDRESS_MAILING,
	IS_ADDRESS_SHIPPING,
	COMMENTS,
	AGENCY_ADDR_ID,
	ADDRESS_LINE3,
	ADDRESS_LINE4,
	ADDRESS_ESSENTIAL,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "AGENCY_ID", "SEQ_NUMBER", "ADDRESS_TYPE", "ADDRESS_LINE1", "ADDRESS_LINE2", "ADDRESS_CITY", "STATE_CODE", "ZIP", "COUNTRY_CODE", "IS_ADDRESS_MAILING", "IS_ADDRESS_SHIPPING", "COMMENTS", "AGENCY_ADDR_ID", "ADDRESS_LINE3", "ADDRESS_LINE4", "ADDRESS_ESSENTIAL", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."AGENCY_ADDRESS";
create or replace view AGENCY_CONTACT(
	AGENCY_CONTACT_ID,
	AGENCY_ID,
	AGENT_ID,
	DATE_FROM,
	DATE_TO,
	POSITION,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT AGENCY_CONTACT_ID, AGENCY_ID, AGENT_ID, DATE_FROM, DATE_TO, "POSITION", COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.AGENCY_CONTACT;
create or replace view AGENCY_PHONE(
	AGENCY_ID,
	SEQ_NUMBER,
	PHONE_TYPE,
	INTL_CODE,
	PHONE_NUMBER,
	IS_PHONE_PRIMARY,
	IS_PHONE_SECONDARY,
	IS_PHONE_FAX,
	FAX_ATTENTION_LINE,
	COMMENTS,
	AGENCY_PHONE_ID,
	PHONE_EXT,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "AGENCY_ID", "SEQ_NUMBER", "PHONE_TYPE", "INTL_CODE", "PHONE_NUMBER", "IS_PHONE_PRIMARY", "IS_PHONE_SECONDARY", "IS_PHONE_FAX", "FAX_ATTENTION_LINE", "COMMENTS", "AGENCY_PHONE_ID", "PHONE_EXT", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."AGENCY_PHONE";
create or replace view AGENT(
	AGENT_ID,
	LAST_NAME,
	FIRST_NAME,
	MIDDLE_NAME,
	FULL_NAME,
	SALUTATION,
	TITLE,
	SEX,
	BIRTHDAY,
	IATAN_NUMBER,
	IATAN_COMPANY_NAME,
	IATAN_HOLDER_NAME,
	IATAN_COMPANY_NUMBER,
	COMMENTS,
	IATAN_EXPIRATION_DATE,
	EMAIL,
	IS_DISTRICT_SM,
	IS_INCENTIVE_SM,
	WEB_PASSWORD,
	WEB_LOGIN_NAME,
	WEB_LAST_LOGIN,
	WEB_CANACCESAGENCYDATA,
	ALLOW_WEB_ACCESS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT AGENT_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, SALUTATION, TITLE, SEX, BIRTHDAY, IATAN_NUMBER, IATAN_COMPANY_NAME, IATAN_HOLDER_NAME, IATAN_COMPANY_NUMBER, COMMENTS, IATAN_EXPIRATION_DATE, EMAIL, IS_DISTRICT_SM, IS_INCENTIVE_SM, WEB_PASSWORD, WEB_LOGIN_NAME, WEB_LAST_LOGIN, WEB_CANACCESAGENCYDATA, ALLOW_WEB_ACCESS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.AGENT;
create or replace view AM_BOOKING_TYPE(
	AM_BOOKING_TYPE,
	RECORD_ID,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT AM_BOOKING_TYPE, RECORD_ID, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.AM_BOOKING_TYPE;
create or replace view AM_CODE(
	AMENITY_CODE,
	RECORD_ID,
	AM_CATEGORY,
	AMENITY_TYPE,
	PROVIDER_CODE,
	AMENITY_NAME,
	COMMENTS,
	USE_TAX,
	SUBCODE_MANDATORY,
	MANDATORY_BEFORE_DLV,
	CODE_ACTIVE,
	ADDON_RESTRICTED,
	ADDON_ORDER_BASIS,
	ADDON_INV_ITEM_TYPE,
	ADDON_COMPONENT_TYPE,
	INCLUDE_IN_ORDER,
	DISPLAY_PER_PACKAGE,
	IMAGE_ID,
	APPLY_TO_ALL_GUESTS,
	SELL_LIMIT_WEIGHT,
	VEHICLE_TYPE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT AMENITY_CODE, RECORD_ID, AM_CATEGORY, AMENITY_TYPE, PROVIDER_CODE, AMENITY_NAME, COMMENTS, USE_TAX, SUBCODE_MANDATORY, MANDATORY_BEFORE_DLV, CODE_ACTIVE, ADDON_RESTRICTED, ADDON_ORDER_BASIS, ADDON_INV_ITEM_TYPE, ADDON_COMPONENT_TYPE, INCLUDE_IN_ORDER, DISPLAY_PER_PACKAGE, IMAGE_ID, APPLY_TO_ALL_GUESTS, SELL_LIMIT_WEIGHT, VEHICLE_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.AM_CODE;
create or replace view BLL_RM_PRICE(
	RM_PRICE_ID,
	PARK_CODE,
	ARRIVAL_DATE,
	PACKAGE_TYPE,
	GRADE,
	PRICE,
	EFFECTIVE_FROM,
	INSERT_DATE,
	BLL_RM_PRICE_TYPE,
	PERCENT,
	GENERIC_GRADE,
	DESCRIPTION,
	ATTRIBUTE_CODE,
	ATTRIBUTE_VALUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RM_PRICE_ID", "PARK_CODE", "ARRIVAL_DATE", "PACKAGE_TYPE", "GRADE", "PRICE", "EFFECTIVE_FROM", "INSERT_DATE", "BLL_RM_PRICE_TYPE", "PERCENT", "GENERIC_GRADE", "DESCRIPTION", "ATTRIBUTE_CODE", "ATTRIBUTE_VALUE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."BLL_RM_PRICE";
create or replace view BLL_RM_PRICE_TYPE(
	BLL_RM_PRICE_TYPE,
	BLL_RM_PRICE_TYPE_DESCRIPTION,
	BLL_RM_PRICE_TYPE_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "BLL_RM_PRICE_TYPE", "BLL_RM_PRICE_TYPE_DESCRIPTION", "BLL_RM_PRICE_TYPE_ID", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."BLL_RM_PRICE_TYPE";
create or replace view CABIN_ATTRIBUTE(
	CABIN_ATTR_ID,
	CABIN_ATTR_CODE,
	CABIN_ATTR_NAME,
	IS_ATTR_UNIQUE,
	IS_ATTR_COUNTABLE,
	IS_ATTR_EXTENDED,
	IS_ATTR_MANDATORY,
	COMMENTS,
	IMAGE_ID,
	USE_FOR_SHOPPING,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT CABIN_ATTR_ID, CABIN_ATTR_CODE, CABIN_ATTR_NAME, IS_ATTR_UNIQUE, IS_ATTR_COUNTABLE, IS_ATTR_EXTENDED, IS_ATTR_MANDATORY, COMMENTS, IMAGE_ID, USE_FOR_SHOPPING, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_ATTRIBUTE;
create or replace view CABIN_ATTRIBUTE_LINK(
	SHIP_CODE,
	CABIN_NUMBER,
	CABIN_ATTR_ID,
	SEQ_NUMBER,
	CABIN_ATTR_COUNTER,
	CABIN_ATTR_EXT_INFO,
	RECORD_ID,
	EFF_SAIL_FROM,
	EFF_SAIL_TO,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT SHIP_CODE, CABIN_NUMBER, CABIN_ATTR_ID, SEQ_NUMBER, CABIN_ATTR_COUNTER, CABIN_ATTR_EXT_INFO, RECORD_ID, EFF_SAIL_FROM, EFF_SAIL_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_ATTRIBUTE_LINK;
create or replace view CABIN_CATEGORY(
	CABIN_CATEGORY,
	CABIN_CATEGORY_ID,
	COMMENTS,
	IMAGE_ID,
	CABIN_CAPACITY,
	CABIN_CATEGORY_RANK,
	SHIP_CODE,
	IS_ACTIVE,
	ALLOW_AUTO_ASGN,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT CABIN_CATEGORY, CABIN_CATEGORY_ID, COMMENTS, IMAGE_ID, CABIN_CAPACITY, CABIN_CATEGORY_RANK, SHIP_CODE, IS_ACTIVE, ALLOW_AUTO_ASGN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_CATEGORY;
create or replace view CABIN_CATEGORY_COMMENTS(
	RECORD_ID,
	SHIP_CODE,
	CABIN_CATEGORY,
	EFF_FROM,
	EFF_TO,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, SHIP_CODE, CABIN_CATEGORY, EFF_FROM, EFF_TO, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_CATEGORY_COMMENTS;
create or replace view CABIN_CATEGORY_GENERIC(
	RECORD_ID,
	CABIN_CATEGORY_GENERIC,
	COMMENTS,
	RANK,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, CABIN_CATEGORY_GENERIC, COMMENTS, "RANK", HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_CATEGORY_GENERIC;
create or replace view CABIN_CAT_GEN_LNK_CABIN_CAT(
	RECORD_ID,
	CABIN_CATEGORY_GENERIC,
	SHIP_CODE,
	CABIN_CATEGORY,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, CABIN_CATEGORY_GENERIC, SHIP_CODE, CABIN_CATEGORY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_CAT_GEN_LNK_CABIN_CAT;
create or replace view CABIN_LAYOUT(
	CABIN_LAYOUT_ID,
	DECK_ID,
	OBJECT,
	CABIN_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT CABIN_LAYOUT_ID, DECK_ID, "OBJECT", CABIN_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CABIN_LAYOUT;
create or replace view CANCELLATION_CASE(
	CASE_ID,
	CASE_NAME,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "CASE_ID", "CASE_NAME", "COMMENTS", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."CANCELLATION_CASE";
create or replace view CC_CLIENT(
	CC_ACC_NUMBER,
	CC_ACC_ID,
	CC_EXP_DATE,
	IS_CC_ACTIVE,
	IS_CC_BLACKLISTED,
	COMMENTS,
	CC_NAME_ON_CARD,
	ADDRESS_LINE1,
	ADDRESS_LINE2,
	ADDRESS_LINE3,
	ADDRESS_LINE4,
	ADDRESS_CITY,
	STATE_CODE,
	CC_ADDRESS,
	ZIP,
	COUNTRY_CODE,
	ISSUER_BANK,
	CC_START_DATE,
	CC_ISSUE_NUMBER,
	CC_TYPE,
	CC_TOKEN,
	TOKEN_TYPE,
	VALIDATION_LOG,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "CC_ACC_NUMBER", "CC_ACC_ID", "CC_EXP_DATE", "IS_CC_ACTIVE", "IS_CC_BLACKLISTED", "COMMENTS", "CC_NAME_ON_CARD", "ADDRESS_LINE1", "ADDRESS_LINE2", "ADDRESS_LINE3", "ADDRESS_LINE4", "ADDRESS_CITY", "STATE_CODE", "CC_ADDRESS", "ZIP", "COUNTRY_CODE", "ISSUER_BANK", "CC_START_DATE", "CC_ISSUE_NUMBER", "CC_TYPE", "CC_TOKEN", "TOKEN_TYPE", "VALIDATION_LOG", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."CC_CLIENT";
create or replace view CC_ENTITY_LINK(
	ENTITY_TYPE,
	ENTITY_ID,
	CC_ACC_NUMBER,
	CC_LINK_ID,
	IS_CC_PREFERRED,
	CC_CLIENT_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "ENTITY_TYPE", "ENTITY_ID", "CC_ACC_NUMBER", "CC_LINK_ID", "IS_CC_PREFERRED", "CC_CLIENT_ID", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."CC_ENTITY_LINK";
create or replace view CC_PENDING_TRANS(
	CC_TRANS_ID,
	TRANS_ID,
	USE_EXTENDED_PAY,
	USE_ADDR_VERIFICATION,
	AUTH_CODE,
	IS_PENDING,
	CX_REQUEST,
	SUBMITED_TIME_STAMP,
	ATTEMPT_COUNT,
	LAST_ATTEMPT_TIME_STAMP,
	LAST_RESPONSE,
	OPERATOR,
	DONOTIFY,
	SHIP_TRANS_ID,
	CC_TRANS_STATUS,
	TERMINAL,
	TRANS_SERVER_REFNUM,
	ECOMMERCE_INDICATOR,
	IS_AUTH_MANUAL,
	IS_ACTIVE,
	CC_CONTROL_NUMBER,
	SENDER_GUID,
	CC_COMBINED_ID,
	AUDIT_DATA,
	TRANS_DATA,
	TRANS_TOKEN,
	TOKEN_TYPE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "CC_TRANS_ID", "TRANS_ID", "USE_EXTENDED_PAY", "USE_ADDR_VERIFICATION", "AUTH_CODE", "IS_PENDING", "CX_REQUEST", "SUBMITED_TIME_STAMP", "ATTEMPT_COUNT", "LAST_ATTEMPT_TIME_STAMP", "LAST_RESPONSE", "OPERATOR", "DONOTIFY", "SHIP_TRANS_ID", "CC_TRANS_STATUS", "TERMINAL", "TRANS_SERVER_REFNUM", "ECOMMERCE_INDICATOR", "IS_AUTH_MANUAL", "IS_ACTIVE", "CC_CONTROL_NUMBER", "SENDER_GUID", "CC_COMBINED_ID", "AUDIT_DATA", "TRANS_DATA", "TRANS_TOKEN", "TOKEN_TYPE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."CC_PENDING_TRANS";
create or replace view CLIENT(
	CLIENT_ID,
	HOUSEHOLD_ID,
	LAST_NAME,
	FIRST_NAME,
	MIDDLE_NAME,
	FULL_NAME,
	SALUTATION,
	TITLE,
	OCCUPATION,
	IS_ACTIVE,
	BIRTHDAY,
	BIRTH_PLACE,
	SEX,
	IS_HANDICAPPED,
	IS_SMOKER,
	SOUVENIR_FNAME,
	SOUVENIR_LNAME,
	LANGUAGE,
	PASSPORT_NUMBER,
	PASSPORT_ISSUE_PLACE,
	PASSPORT_ISSUE_DATE,
	PASSPORT_EXP_DATE,
	NATIONALITY,
	CITIZENSHIP,
	REFERRAL_TYPE,
	REFERRAL_DATE,
	REFERRAL_CLIENT_ID,
	REFERRAL_HOUSEHOLD_ID,
	REFERRAL_SOURCE,
	COMMENTS,
	CLIENT_TYPE,
	GUEST_TYPE,
	DIRECTORY_NAME,
	CLIENT_CLASS_CODE,
	EMAIL,
	COUNTRY_OF_BIRTH,
	WEB_PASSWORD,
	WEB_LOGIN_NAME,
	WEB_LAST_LOGIN,
	SSN,
	LANGUAGE_CODE,
	HISTORICAL_CRUISES_NUM,
	HISTORICAL_DAYS_NUM,
	ALLOW_WEB_ACCESS,
	CL_ENTITY_TYPE,
	SEND_PROMOTIONAL_MAIL,
	SEND_PROMOTIONAL_EMAIL,
	SEND_PROMOTIONAL_SMS,
	NOTIF_DFLT_DISTR_TYPE,
	LAST_NAME_UPPER,
	SEND_PROMOTIONAL_PHONE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "CLIENT_ID", "HOUSEHOLD_ID", "LAST_NAME", "FIRST_NAME", "MIDDLE_NAME", "FULL_NAME", "SALUTATION", "TITLE", "OCCUPATION", "IS_ACTIVE", "BIRTHDAY", "BIRTH_PLACE", "SEX", "IS_HANDICAPPED", "IS_SMOKER", "SOUVENIR_FNAME", "SOUVENIR_LNAME", "LANGUAGE", "PASSPORT_NUMBER", "PASSPORT_ISSUE_PLACE", "PASSPORT_ISSUE_DATE", "PASSPORT_EXP_DATE", "NATIONALITY", "CITIZENSHIP", "REFERRAL_TYPE", "REFERRAL_DATE", "REFERRAL_CLIENT_ID", "REFERRAL_HOUSEHOLD_ID", "REFERRAL_SOURCE", "COMMENTS", "CLIENT_TYPE", "GUEST_TYPE", "DIRECTORY_NAME", "CLIENT_CLASS_CODE", "EMAIL", "COUNTRY_OF_BIRTH", "WEB_PASSWORD", "WEB_LOGIN_NAME", "WEB_LAST_LOGIN", "SSN", "LANGUAGE_CODE", "HISTORICAL_CRUISES_NUM", "HISTORICAL_DAYS_NUM", "ALLOW_WEB_ACCESS", "CL_ENTITY_TYPE", "SEND_PROMOTIONAL_MAIL", "SEND_PROMOTIONAL_EMAIL", "SEND_PROMOTIONAL_SMS", "NOTIF_DFLT_DISTR_TYPE", "LAST_NAME_UPPER", "SEND_PROMOTIONAL_PHONE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."CLIENT";
create or replace view CLIENT_PREFER(
	COMMENTS,
	CLIENT_ID,
	PREFERENCE_TYPE,
	PREFERENCE_CODE,
	CLIENT_PREFER_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "COMMENTS", "CLIENT_ID", "PREFERENCE_TYPE", "PREFERENCE_CODE", "CLIENT_PREFER_ID", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."CLIENT_PREFER";
create or replace view CLIENT_TYPE(
	CLIENT_TYPE,
	COMMENTS,
	CLIENT_TYPE_ID,
	POINTS_REQUIRED,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT CLIENT_TYPE, COMMENTS, CLIENT_TYPE_ID, POINTS_REQUIRED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.CLIENT_TYPE;
create or replace view COMPONENT_TYPE(
	COMPONENT_TYPE,
	COMPONENT_TYPE_ID,
	COMMENTS,
	MAY_BE_ADDON,
	CAN_OVERLAP,
	USE_FOR_ITINERARY,
	USE_FOR_SHOREX,
	USE_FOR_LAND_PROGRAMS,
	PART_OF_ITINERARY,
	ORIGINAL_TYPE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT COMPONENT_TYPE, COMPONENT_TYPE_ID, COMMENTS, MAY_BE_ADDON, CAN_OVERLAP, USE_FOR_ITINERARY, USE_FOR_SHOREX, USE_FOR_LAND_PROGRAMS, PART_OF_ITINERARY, ORIGINAL_TYPE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.COMPONENT_TYPE;
create or replace view FERRY_REQUEST(
	REQUEST_ID,
	ENTITY_TYPE,
	ENTITY_ID,
	STATUS,
	CONFIRMATION_NUMBER,
	PROVIDER_ID,
	VEHICLE_TYPE,
	N_OF_PEOPLE,
	ROUTE_DEP,
	ROUTE_RET,
	DATE_DEP,
	DATE_RET,
	TIME_DEP,
	TIME_RET,
	VEHICLE_MAKE,
	VEHICLE_LENGTH,
	VEHICLE_REGISTRATION,
	CHANGES,
	COMMENTS,
	COST,
	COST_CURRENCY,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT REQUEST_ID, ENTITY_TYPE, ENTITY_ID, STATUS, CONFIRMATION_NUMBER, PROVIDER_ID, VEHICLE_TYPE, N_OF_PEOPLE, ROUTE_DEP, ROUTE_RET, DATE_DEP, DATE_RET, TIME_DEP, TIME_RET, VEHICLE_MAKE, VEHICLE_LENGTH, VEHICLE_REGISTRATION, CHANGES, COMMENTS, COST, COST_CURRENCY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.FERRY_REQUEST;
create or replace view FERRY_ROUTE(
	ROUTE_ID,
	ROUTE_CODE,
	PORT_FROM,
	PORT_TO,
	COMMENTS,
	DISPLAY_ORDER,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT ROUTE_ID, ROUTE_CODE, PORT_FROM, PORT_TO, COMMENTS, DISPLAY_ORDER, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.FERRY_ROUTE;
create or replace view GL_TRANS(
	GL_TRANS_ID,
	TRANS_ID,
	GL_BATCH_ID,
	GL_TRANS_AMOUNT,
	TRANS_TIME_STAMP,
	COMMENTS,
	FULL_DBT_GL,
	FULL_CRD_GL,
	SEQ_NUMBER,
	GL_TRANS_TYPE,
	ENTITY_TYPE,
	GL_TRANS_SOURCE,
	N_OF_DAYS,
	ENTITY_ID,
	PERIOD_ID,
	CURRENCY_CODE,
	IS_COMPLETED,
	FULL_N_OF_DAYS,
	ORIG_ITEM_CODE,
	ORIG_ITEM_SUBCODE,
	ORIG_ITEM_REC_ID,
	DLGT_RES_ID,
	IS_LAST_FOR_TRANS,
	PRORATE_METHOD,
	TRANS_HIST_ID,
	LOGICAL_DATE,
	GL_PACKAGE_ID,
	GUEST_ID,
	OFFICE_CODE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "GL_TRANS_ID", "TRANS_ID", "GL_BATCH_ID", "GL_TRANS_AMOUNT", "TRANS_TIME_STAMP", "COMMENTS", "FULL_DBT_GL", "FULL_CRD_GL", "SEQ_NUMBER", "GL_TRANS_TYPE", "ENTITY_TYPE", "GL_TRANS_SOURCE", "N_OF_DAYS", "ENTITY_ID", "PERIOD_ID", "CURRENCY_CODE", "IS_COMPLETED", "FULL_N_OF_DAYS", "ORIG_ITEM_CODE", "ORIG_ITEM_SUBCODE", "ORIG_ITEM_REC_ID", "DLGT_RES_ID", "IS_LAST_FOR_TRANS", "PRORATE_METHOD", "TRANS_HIST_ID", "LOGICAL_DATE", "GL_PACKAGE_ID", "GUEST_ID", "OFFICE_CODE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."GL_TRANS";
create or replace view GROUP_AMENITY_REQUEST(
	RECORD_ID,
	GROUP_ID,
	AMENITY_CODE,
	ORDER_BASIS,
	REQUESTED_QTY,
	EFFECTIVE_DATE,
	ORDER_BASIS_QTY,
	IS_AUTO,
	GROUP_SHIP_REQ_ID,
	RESTRICTED_QTY,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, GROUP_ID, AMENITY_CODE, ORDER_BASIS, REQUESTED_QTY, EFFECTIVE_DATE, ORDER_BASIS_QTY, IS_AUTO, GROUP_SHIP_REQ_ID, RESTRICTED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_AMENITY_REQUEST;
create or replace view GROUP_BOOKING(
	GROUP_ID,
	COMMENTS,
	AGENCY_ID,
	AGENT_ID,
	GROUP_NAME,
	GROUP_TYPE,
	N_OF_GUESTS,
	REL_DAY_FROM,
	REL_DAY_TO,
	SAIL_DATE_FROM,
	SAIL_DATE_TO,
	SHIP_CODE,
	IS_ACTIVE,
	IS_VALID,
	PROBABILITY,
	GROUP_STATUS,
	ALLOW_DIFF_AGENCY,
	EXPIRATION_EXTENSION,
	GROUP_INIT_DATE,
	WDW_GROUP_ID,
	PRIORITY,
	TERMINATION_COMPLETED,
	GROUP_SIZE_OVERRIDE,
	PROBABILITY_ALLOCATED,
	IS_CONTRACT_RATE,
	CAN_PROCESS_GTB,
	GRP_COORD_NAME,
	USE_TC_FULLPAY,
	CURRENCY_CODE,
	SEC_AGENCY_ID,
	LANGUAGE_CODE,
	IS_INVOICE_VALID,
	ALLOW_AUTO_DISTR_FUNDS,
	ALLOW_AUTO_CANCEL_DLGT,
	IS_CHARTER,
	OFFICE_CODE,
	IS_PROB_MANUAL,
	ALLOW_UNBALANCE,
	TOUR_CREDIT_POLICY_OVR,
	CURRENCY_RATE,
	IS_UNBALANCED,
	GB_ENTITY_TYPE,
	INVOICE_VERSION,
	FIRST_FULL_PAYMENT_PROCESSED,
	ALLOW_AUTO_PROCESS_FPR,
	ALLOW_REFUND_CLIENT_MONEY,
	DEFAULT_INSURANCE,
	AM_ORDER_ID,
	FPR_IN_PROCESS,
	COMPANY_ID,
	UPDATE_VERSION,
	IS_PAYSCH_MANUAL,
	TERMS_CONFIRMED,
	SOURCE_CODE,
	LEAD_CLIENT_ID,
	USE_FIT_PAYSCH,
	IS_MULTI_UNIT,
	ALLOW_DIFF_SAILS,
	REFERRAL_SOURCE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "GROUP_ID", "COMMENTS", "AGENCY_ID", "AGENT_ID", "GROUP_NAME", "GROUP_TYPE", "N_OF_GUESTS", "REL_DAY_FROM", "REL_DAY_TO", "SAIL_DATE_FROM", "SAIL_DATE_TO", "SHIP_CODE", "IS_ACTIVE", "IS_VALID", "PROBABILITY", "GROUP_STATUS", "ALLOW_DIFF_AGENCY", "EXPIRATION_EXTENSION", "GROUP_INIT_DATE", "WDW_GROUP_ID", "PRIORITY", "TERMINATION_COMPLETED", "GROUP_SIZE_OVERRIDE", "PROBABILITY_ALLOCATED", "IS_CONTRACT_RATE", "CAN_PROCESS_GTB", "GRP_COORD_NAME", "USE_TC_FULLPAY", "CURRENCY_CODE", "SEC_AGENCY_ID", "LANGUAGE_CODE", "IS_INVOICE_VALID", "ALLOW_AUTO_DISTR_FUNDS", "ALLOW_AUTO_CANCEL_DLGT", "IS_CHARTER", "OFFICE_CODE", "IS_PROB_MANUAL", "ALLOW_UNBALANCE", "TOUR_CREDIT_POLICY_OVR", "CURRENCY_RATE", "IS_UNBALANCED", "GB_ENTITY_TYPE", "INVOICE_VERSION", "FIRST_FULL_PAYMENT_PROCESSED", "ALLOW_AUTO_PROCESS_FPR", "ALLOW_REFUND_CLIENT_MONEY", "DEFAULT_INSURANCE", "AM_ORDER_ID", "FPR_IN_PROCESS", "COMPANY_ID", "UPDATE_VERSION", "IS_PAYSCH_MANUAL", "TERMS_CONFIRMED", "SOURCE_CODE", "LEAD_CLIENT_ID", "USE_FIT_PAYSCH", "IS_MULTI_UNIT", "ALLOW_DIFF_SAILS", "REFERRAL_SOURCE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."GROUP_BOOKING";
create or replace view GROUP_COMMISSION_DETAIL(
	RECORD_ID,
	AMOUNT,
	COMMISS_FARE,
	COMMISS_CODE,
	COMMISS_SOURCE,
	INVOICE_ITEM_TYPE,
	PERCENT,
	GROUP_ID,
	PACKAGE_ID,
	IS_MANUAL_ADJUSTMENT,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, AMOUNT, COMMISS_FARE, COMMISS_CODE, COMMISS_SOURCE, INVOICE_ITEM_TYPE, "PERCENT", GROUP_ID, PACKAGE_ID, IS_MANUAL_ADJUSTMENT, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_COMMISSION_DETAIL;
create or replace view GROUP_EVENT(
	RECORD_ID,
	GROUP_EVENT_TYPE,
	GROUP_ID,
	EVENT_TIMESTAMP,
	EVENT_DATE,
	OPERATOR_ID,
	OLD_STATUS,
	NEW_STATUS,
	OLD_SHIP_CODE,
	OLD_SAIL_FROM,
	OLD_SAIL_TO,
	NEW_SHIP_CODE,
	NEW_SAIL_FROM,
	NEW_SAIL_TO,
	OLD_CABINS,
	OLD_GUEST_COUNT,
	NEW_CABINS,
	NEW_GUEST_COUNT,
	OLD_PROBABILITY,
	NEW_PROBABILITY,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RECORD_ID", "GROUP_EVENT_TYPE", "GROUP_ID", "EVENT_TIMESTAMP", "EVENT_DATE", "OPERATOR_ID", "OLD_STATUS", "NEW_STATUS", "OLD_SHIP_CODE", "OLD_SAIL_FROM", "OLD_SAIL_TO", "NEW_SHIP_CODE", "NEW_SAIL_FROM", "NEW_SAIL_TO", "OLD_CABINS", "OLD_GUEST_COUNT", "NEW_CABINS", "NEW_GUEST_COUNT", "OLD_PROBABILITY", "NEW_PROBABILITY", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."GROUP_EVENT";
create or replace view GROUP_HISTORY_HEADER(
	GROUP_ID,
	GROUP_UPDATE_ID,
	OPERATOR_ID,
	TIME_STAMP,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT GROUP_ID, GROUP_UPDATE_ID, OPERATOR_ID, TIME_STAMP, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_HISTORY_HEADER;
create or replace view GROUP_INVOICE_HISTORY(
	GROUP_ID,
	GROUP_UPDATE_ID,
	INVOICE_ITEM_TYPE,
	PRICE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT GROUP_ID, GROUP_UPDATE_ID, INVOICE_ITEM_TYPE, PRICE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_INVOICE_HISTORY;
create or replace view GROUP_INVOICE_ITEM(
	RECORD_ID,
	GROUP_ID,
	REC_SEQN,
	INVOICE_ITEM_TYPE,
	INVOICE_ITEM_SUBTYPE,
	QUANTITY,
	EFF_DATE,
	BROCHURE_PRICE,
	EBD_PRICE,
	GROUP_PRICE,
	TOTAL_PRICE,
	INVOICE_ITEM_SUBTYPE2,
	INVOICE_ITEM_SUBTYPE3,
	IS_MANUAL_ADJUSTMENT,
	PROMO_CODE,
	GROUP_SHIP_REQ_ID,
	GROUP_HOTEL_REQ_ID,
	GROUP_PACKAGE_ID,
	GROUP_AIR_REQ_ID,
	PACKAGE_ID,
	COMMISSION_PERCENT,
	DUMMY_RES_SEQN,
	GUEST_SEQN,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, GROUP_ID, REC_SEQN, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, QUANTITY, EFF_DATE, BROCHURE_PRICE, EBD_PRICE, GROUP_PRICE, TOTAL_PRICE, INVOICE_ITEM_SUBTYPE2, INVOICE_ITEM_SUBTYPE3, IS_MANUAL_ADJUSTMENT, PROMO_CODE, GROUP_SHIP_REQ_ID, GROUP_HOTEL_REQ_ID, GROUP_PACKAGE_ID, GROUP_AIR_REQ_ID, PACKAGE_ID, COMMISSION_PERCENT, DUMMY_RES_SEQN, GUEST_SEQN, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_INVOICE_ITEM;
create or replace view GROUP_PAY_DUE_ITEM(
	RECORD_ID,
	GROUP_ID,
	PMNT_DUE_ITEM_TYPE,
	DUE_DATE,
	GRACE_PERIOD,
	AMOUNT,
	ACTIVITY_TYPE,
	ACTIVITY_DATE,
	ACTIVITY_EFFECTIVE_DATE,
	ACTIVITY_INFO,
	DELEGATE_RES_ID,
	CABIN_NUMBER,
	IS_ADJUSTMENT,
	CABIN_CATEGORY,
	OCCUPANCY,
	SHIP_CODE,
	EXPIRATION_DATE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, GROUP_ID, PMNT_DUE_ITEM_TYPE, DUE_DATE, GRACE_PERIOD, AMOUNT, ACTIVITY_TYPE, ACTIVITY_DATE, ACTIVITY_EFFECTIVE_DATE, ACTIVITY_INFO, DELEGATE_RES_ID, CABIN_NUMBER, IS_ADJUSTMENT, CABIN_CATEGORY, OCCUPANCY, SHIP_CODE, EXPIRATION_DATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_PAY_DUE_ITEM;
create or replace view GROUP_PROMOTION(
	GROUP_PROMOTION_ID,
	GROUP_ID,
	GROUP_SHIP_REQ_ID,
	PROMO_CODE,
	GUEST_MASK,
	REQUESTED_COUNT,
	UNASSIGNED_QTY,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT GROUP_PROMOTION_ID, GROUP_ID, GROUP_SHIP_REQ_ID, PROMO_CODE, GUEST_MASK, REQUESTED_COUNT, UNASSIGNED_QTY, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_PROMOTION;
create or replace view GROUP_SHIP_REQUEST(
	RECORD_ID,
	CABIN_CATEGORY,
	OCCUPANCY,
	QUANTITY,
	PRODUCT_TYPE,
	CABIN_CATEGORY_BERTH,
	PACKAGE_TYPE,
	SHIP_CODE,
	GROUP_ID,
	EFFECTIVE_DATE,
	PACKAGE_ID,
	ROLLAWAY_BEDS_REQUESTED,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, CABIN_CATEGORY, OCCUPANCY, QUANTITY, PRODUCT_TYPE, CABIN_CATEGORY_BERTH, PACKAGE_TYPE, SHIP_CODE, GROUP_ID, EFFECTIVE_DATE, PACKAGE_ID, ROLLAWAY_BEDS_REQUESTED, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_SHIP_REQUEST;
create or replace view GROUP_SHIP_UNIT_ATTR(
	RECORD_ID,
	GROUP_ID,
	GROUP_SHIP_REQ_ID,
	REQUEST_TYPE,
	ATTRIBUTE_CODE,
	STR_VALUE,
	INT_VALUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, GROUP_ID, GROUP_SHIP_REQ_ID, REQUEST_TYPE, ATTRIBUTE_CODE, STR_VALUE, INT_VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.GROUP_SHIP_UNIT_ATTR;
create or replace view GROUP_USER_NOTES(
	RECORD_ID,
	GROUP_ID,
	SUBJECT,
	NOTES,
	TIME_STAMP_CREATED,
	TIME_STAMP_CHANGED,
	USER_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as
select * 
from warner_raw.seaware_aps.group_user_notes
;
create or replace view HOUSEHOLD(
	HOUSEHOLD_ID,
	HOUSEHOLD_NAME,
	LAST_NAME_TYPED,
	LAST_NAME,
	SALUTATION,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT HOUSEHOLD_ID, HOUSEHOLD_NAME, LAST_NAME_TYPED, LAST_NAME, SALUTATION, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.HOUSEHOLD;
create or replace view HOUSEHOLD_ADDRESS(
	HOUSEHOLD_ID,
	SEQ_NUMBER,
	ADDRESS_TYPE,
	ADDRESS_LINE1,
	ADDRESS_LINE2,
	ADDRESS_CITY,
	STATE_CODE,
	ZIP,
	COUNTRY_CODE,
	IS_ADDRESS_MAILING,
	IS_ADDRESS_SHIPPING,
	DATE_FROM,
	DATE_TO,
	ARE_DATES_EVERY_YEAR,
	COMMENTS,
	HOUSEHOLD_ADDR_ID,
	ADDRESS_LINE3,
	ADDRESS_LINE4,
	ADDRESS_ESSENTIAL,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "HOUSEHOLD_ID", "SEQ_NUMBER", "ADDRESS_TYPE", "ADDRESS_LINE1", "ADDRESS_LINE2", "ADDRESS_CITY", "STATE_CODE", "ZIP", "COUNTRY_CODE", "IS_ADDRESS_MAILING", "IS_ADDRESS_SHIPPING", "DATE_FROM", "DATE_TO", "ARE_DATES_EVERY_YEAR", "COMMENTS", "HOUSEHOLD_ADDR_ID", "ADDRESS_LINE3", "ADDRESS_LINE4", "ADDRESS_ESSENTIAL", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."HOUSEHOLD_ADDRESS";
create or replace view HOUSEHOLD_PHONE(
	HOUSEHOLD_ID,
	SEQ_NUMBER,
	PHONE_TYPE,
	INTL_CODE,
	PHONE_NUMBER,
	IS_PHONE_PRIMARY,
	IS_PHONE_SECONDARY,
	IS_PHONE_FAX,
	IS_PHONE_EMERGENCY,
	FAX_ATTENTION_LINE,
	COMMENTS,
	HOUSEHOLD_PHONE_ID,
	PHONE_EXT,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "HOUSEHOLD_ID", "SEQ_NUMBER", "PHONE_TYPE", "INTL_CODE", "PHONE_NUMBER", "IS_PHONE_PRIMARY", "IS_PHONE_SECONDARY", "IS_PHONE_FAX", "IS_PHONE_EMERGENCY", "FAX_ATTENTION_LINE", "COMMENTS", "HOUSEHOLD_PHONE_ID", "PHONE_EXT", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."HOUSEHOLD_PHONE";
create or replace view INVOICE_ITEM_GROUP(
	INV_ITEM_GROUP,
	INV_ITEM_GROUP_ID,
	COMMENTS,
	SORT_SEQN,
	APPLY_TO_FIRST_GUEST,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT INV_ITEM_GROUP, INV_ITEM_GROUP_ID, COMMENTS, SORT_SEQN, APPLY_TO_FIRST_GUEST, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.INVOICE_ITEM_GROUP;
create or replace view INVOICE_ITEM_GROUP_TYPE(
	INV_ITEM_GROUP_TYPE,
	INV_ITEM_GROUP_TYPE_ID,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT INV_ITEM_GROUP_TYPE, INV_ITEM_GROUP_TYPE_ID, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.INVOICE_ITEM_GROUP_TYPE;
create or replace view INVOICE_ITEM_SUBTYPE(
	INVOICE_ITEM_SUBTYPE_ID,
	INVOICE_ITEM_TYPE,
	INVOICE_ITEM_SUBTYPE,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT INVOICE_ITEM_SUBTYPE_ID, INVOICE_ITEM_TYPE, INVOICE_ITEM_SUBTYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.INVOICE_ITEM_SUBTYPE;
create or replace view INVOICE_ITEM_TYPE(
	INVOICE_ITEM_TYPE,
	INVOICE_ITEM_TYPE_ID,
	COMMENTS,
	IS_COMMISSIONABLE,
	CAN_USE_FOR_CHARGES,
	ALWAYS_REFUNDABLE,
	USED_INTERNALLY,
	USED_FOR_AIR_DEVIATION,
	ALLOW_RATE_PROTECTION,
	CHARGE_COMPONENT_CODE,
	CLASSIFICATION_FOR_GROUP,
	INCLUDE_IN_QUOTED_PRICE,
	USED_FOR_PROJECTIONS,
	USE_IN_PERFORMANCE_CALC,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT INVOICE_ITEM_TYPE, INVOICE_ITEM_TYPE_ID, COMMENTS, IS_COMMISSIONABLE, CAN_USE_FOR_CHARGES, ALWAYS_REFUNDABLE, USED_INTERNALLY, USED_FOR_AIR_DEVIATION, ALLOW_RATE_PROTECTION, CHARGE_COMPONENT_CODE, CLASSIFICATION_FOR_GROUP, INCLUDE_IN_QUOTED_PRICE, USED_FOR_PROJECTIONS, USE_IN_PERFORMANCE_CALC, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.INVOICE_ITEM_TYPE;
create or replace view MV_ACC_RES_GRP_CONSORTIUM_ID(
	AGRID,
	CRID,
	ALRID,
	ARID,
	HRID,
	UNIONID,
	TRANS_ID,
	SEASON,
	U_CONSORTIUM_ID,
	U_ABTA_NUMBER,
	U_CONSORTIUM_NAME,
	AGENCY_ID,
	ABTA_NUMBER,
	AGENCY_TYPE,
	AGENCY_NAME,
	CONSORTIUM_ABTA,
	CONSORTIUM_TYPE,
	CONSORTIUM_NAME,
	AGENCY_LINK_ID,
	CONSORTIUM_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT AGRID, CRID, ALRID, ARID, HRID, UNIONID, TRANS_ID, SEASON, U_CONSORTIUM_ID, U_ABTA_NUMBER, U_CONSORTIUM_NAME, AGENCY_ID, ABTA_NUMBER, AGENCY_TYPE, AGENCY_NAME, CONSORTIUM_ABTA, CONSORTIUM_TYPE, CONSORTIUM_NAME, AGENCY_LINK_ID, CONSORTIUM_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_ACC_RES_GRP_CONSORTIUM_ID;
create or replace view MV_ACC_TRANS_AGEN_TERMS(
	TRANS_ID,
	AGENCY_ID,
	IS_VALID_TERMS,
	IS_VALID_TERMS_F,
	IS_VALID_TERMS_G,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT TRANS_ID, AGENCY_ID, IS_VALID_TERMS, IS_VALID_TERMS_F, IS_VALID_TERMS_G, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_ACC_TRANS_AGEN_TERMS;
create or replace view MV_ACC_TRANS_DETAIL_AGENBNK(
	ARID,
	UNION_ID,
	TRANS_ID,
	TRANS_TIME_STAMP,
	TRANS_TYPE,
	AR_AP_SEQ_ID,
	AR_AP_DUE_DATE,
	RES_ID,
	AGENCY_ID,
	GROUP_ID,
	SOURCE_ENTITY_TYPE,
	SOURCE_ENTITY_ID,
	ENTITY_TYPE,
	ENTITY_ID,
	SOURCE_ENTITY_KEY,
	ENTITY_KEY,
	JOIN_KEY,
	JOIN_TRANS_TYPE_KEY,
	DEBIT,
	DEBIT_LEFT,
	CREDIT,
	CREDIT_LEFT,
	DEBIT_BASE,
	CREDIT_BASE,
	BALANCE,
	NET_DEPTOR,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT ARID, UNION_ID, TRANS_ID, TRANS_TIME_STAMP, TRANS_TYPE, AR_AP_SEQ_ID, AR_AP_DUE_DATE, RES_ID, AGENCY_ID, GROUP_ID, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID, ENTITY_TYPE, ENTITY_ID, SOURCE_ENTITY_KEY, ENTITY_KEY, JOIN_KEY, JOIN_TRANS_TYPE_KEY, DEBIT, DEBIT_LEFT, CREDIT, CREDIT_LEFT, DEBIT_BASE, CREDIT_BASE, BALANCE, NET_DEPTOR, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_ACC_TRANS_DETAIL_AGENBNK;
create or replace view MV_AGENCY_ADDRESS(
	ARID,
	AARID,
	ERID,
	PRID,
	FRID,
	RID2,
	RID3,
	RID4,
	RID5,
	AGENCY_ID,
	AGENCY_NAME,
	AGENCY_NAME_TYPED,
	AGENCY_TYPE,
	ADDRESS_TYPE,
	ADDRESS_LINE1,
	ADDRESS_LINE2,
	ADDRESS_LINE3,
	ADDRESS_LINE4,
	ADDRESS_CITY,
	STATE_CODE,
	ZIP,
	COUNTRY_CODE,
	COMMENTS,
	AGENCY_EMAIL,
	AGENCY_PHONE,
	AGENCY_FAX,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT ARID, AARID, ERID, PRID, FRID, RID2, RID3, RID4, RID5, AGENCY_ID, AGENCY_NAME, AGENCY_NAME_TYPED, AGENCY_TYPE, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_CITY, STATE_CODE, ZIP, COUNTRY_CODE, COMMENTS, AGENCY_EMAIL, AGENCY_PHONE, AGENCY_FAX, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_AGENCY_ADDRESS;
create or replace view MV_GRP_CHG_BY_SEASON(
	HRID,
	ARID,
	URID,
	GROUP_ID,
	GROUP_STATUS,
	SEASON,
	VALUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_GRP_CHG_BY_SEASON;
create or replace view MV_GRP_INV_BY_SEASON(
	HRID,
	ARID,
	URID,
	GROUP_ID,
	GROUP_STATUS,
	SEASON,
	VALUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_GRP_INV_BY_SEASON;
create or replace view MV_GRP_NET_DUE_BY_SEASON(
	HRID,
	ARID,
	URID,
	GROUP_ID,
	GROUP_STATUS,
	SEASON,
	VALUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT HRID, ARID, URID, GROUP_ID, GROUP_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_GRP_NET_DUE_BY_SEASON;
create or replace view MV_GRP_PAYMENT_DUE(
	GROUP_ID,
	DUE_DATE,
	AMOUNT_DUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT GROUP_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_GRP_PAYMENT_DUE;
create or replace view MV_RES_CHG_BY_SEASON(
	HRID,
	ARID,
	URID,
	RES_ID,
	RES_STATUS,
	SEASON,
	VALUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_CHG_BY_SEASON;
create or replace view MV_RES_FIRST_CLIENT(
	GRID,
	CRID,
	RES_ID,
	GUEST_ID,
	GUEST_SEQN,
	CLIENT_ID,
	FULL_NAME,
	LAST_NAME,
	FIRST_NAME,
	MIDDLE_NAME,
	TITLE,
	HOUSEHOLD_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT GRID, CRID, RES_ID, GUEST_ID, GUEST_SEQN, CLIENT_ID, FULL_NAME, LAST_NAME, FIRST_NAME, MIDDLE_NAME, TITLE, HOUSEHOLD_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_FIRST_CLIENT;
create or replace view MV_RES_INV_BY_SEASON(
	HRID,
	ARID,
	URID,
	RES_ID,
	RES_STATUS,
	SEASON,
	VALUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_INV_BY_SEASON;
create or replace view MV_RES_NET_DUE_BY_SEASON(
	HRID,
	ARID,
	URID,
	RES_ID,
	RES_STATUS,
	SEASON,
	VALUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT HRID, ARID, URID, RES_ID, RES_STATUS, SEASON, VALUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_NET_DUE_BY_SEASON;
create or replace view MV_RES_PAYMENT_DUE(
	RES_ID,
	DUE_DATE,
	AMOUNT_DUE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RES_ID, DUE_DATE, AMOUNT_DUE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.MV_RES_PAYMENT_DUE;
create or replace view PACKAGE_DEFINITION(
	PACKAGE_ID,
	PACKAGE_CODE,
	VACATION_DATE,
	PACKAGE_TYPE,
	SAIL_ID,
	SEASON_CODE,
	GEOG_AREA_CODE,
	IS_ACTIVE,
	COMMENTS,
	SORT_SEQN,
	SHOREX_MODE,
	SHOREX_TIMING,
	ALT_PACKAGE_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "PACKAGE_ID", "PACKAGE_CODE", "VACATION_DATE", "PACKAGE_TYPE", "SAIL_ID", "SEASON_CODE", "GEOG_AREA_CODE", "IS_ACTIVE", "COMMENTS", "SORT_SEQN", "SHOREX_MODE", "SHOREX_TIMING", "ALT_PACKAGE_ID", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."PACKAGE_DEFINITION";
create or replace view PACKAGE_ITINERARY(
	ITIN_RECORD_ID,
	PACKAGE_TYPE,
	DAY_NUM_FROM,
	TIME_FROM,
	DAY_NUM_TO,
	TIME_TO,
	LOCATION_TYPE_FROM,
	LOCATION_CODE_FROM,
	LOCATION_TYPE_TO,
	LOCATION_CODE_TO,
	COMPONENT_TYPE,
	COMPONENT_CODE,
	COMPONENT_SUBCODE1,
	COMPONENT_SUBCODE2,
	COMPONENT_SUBCODE3,
	CAN_BE_EXCLUDED,
	IS_OPTIONAL,
	PACKAGE_LINKS_INCLUSIVE,
	COMMENTS,
	DESCRIPTION,
	SEQ_NUM,
	CITY_FROM,
	CITY_TO,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT ITIN_RECORD_ID, PACKAGE_TYPE, DAY_NUM_FROM, TIME_FROM, DAY_NUM_TO, TIME_TO, LOCATION_TYPE_FROM, LOCATION_CODE_FROM, LOCATION_TYPE_TO, LOCATION_CODE_TO, COMPONENT_TYPE, COMPONENT_CODE, COMPONENT_SUBCODE1, COMPONENT_SUBCODE2, COMPONENT_SUBCODE3, CAN_BE_EXCLUDED, IS_OPTIONAL, PACKAGE_LINKS_INCLUSIVE, COMMENTS, DESCRIPTION, SEQ_NUM, CITY_FROM, CITY_TO, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.PACKAGE_ITINERARY;
create or replace view PACKAGE_TYPE(
	PACKAGE_TYPE_ID,
	PACKAGE_TYPE,
	LAND_DAYS,
	SAIL_DAYS,
	COMMENTS,
	PRODUCT_TYPE,
	TC_PACKAGE_TYPE,
	LAND_DAYS_POST,
	IS_LAND_ONLY,
	IS_MULTI_SAIL,
	IS_SHOREX,
	IS_SECONDARY,
	IS_ACTIVE,
	SHOREX_TIMING,
	EXTRA_SEAT_QUESTION,
	PRE_POST_MODE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "PACKAGE_TYPE_ID", "PACKAGE_TYPE", "LAND_DAYS", "SAIL_DAYS", "COMMENTS", "PRODUCT_TYPE", "TC_PACKAGE_TYPE", "LAND_DAYS_POST", "IS_LAND_ONLY", "IS_MULTI_SAIL", "IS_SHOREX", "IS_SECONDARY", "IS_ACTIVE", "SHOREX_TIMING", "EXTRA_SEAT_QUESTION", "PRE_POST_MODE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."PACKAGE_TYPE";
create or replace view PREFERENCE_TYPE(
	PREFERENCE_TYPE,
	COMMENTS,
	PREFERENCE_TYPE_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT PREFERENCE_TYPE, COMMENTS, PREFERENCE_TYPE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.PREFERENCE_TYPE;
create or replace view PRODUCT_TYPE(
	PRODUCT_TYPE_ID,
	PRODUCT_TYPE,
	COMMENTS,
	IS_DAILY,
	IS_ACTIVE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE, COMMENTS, IS_DAILY, IS_ACTIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.PRODUCT_TYPE;
create or replace view REFERRAL_SOURCE(
	REFERRAL_SOURCE_ID,
	REFERRAL_SOURCE,
	REFERRAL_TYPE,
	COMMENTS,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT REFERRAL_SOURCE_ID, REFERRAL_SOURCE, REFERRAL_TYPE, COMMENTS, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.REFERRAL_SOURCE;
create or replace view RES_ADDON(
	RES_ADDON_ID,
	RES_PACKAGE_ID,
	GUEST_ID,
	RES_ID,
	RES_ADDON_CODE,
	START_DATE,
	END_DATE,
	EFFECTIVE_DATE,
	AM_ORDER_ID,
	IS_DEFAULT,
	PAP_CODE,
	AMENITY_CODE,
	DELIVERY_PLACE,
	QUANTITY,
	IS_AUTO,
	COMMENTS,
	TIMESTAMP,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RES_ADDON_ID", "RES_PACKAGE_ID", "GUEST_ID", "RES_ID", "RES_ADDON_CODE", "START_DATE", "END_DATE", "EFFECTIVE_DATE", "AM_ORDER_ID", "IS_DEFAULT", "PAP_CODE", "AMENITY_CODE", "DELIVERY_PLACE", "QUANTITY", "IS_AUTO", "COMMENTS", "TIMESTAMP", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_ADDON";
create or replace view RES_CHARGEABLE_ACTION(
	ACTION_ID,
	ENTITY_TYPE,
	ENTITY_ID,
	RES_ACTION_TYPE,
	ACTION_TIMESTAMP,
	IS_ADDED_MANUALLY,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "ACTION_ID", "ENTITY_TYPE", "ENTITY_ID", "RES_ACTION_TYPE", "ACTION_TIMESTAMP", "IS_ADDED_MANUALLY", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_CHARGEABLE_ACTION";
create or replace view RES_COMMISSION_DETAIL(
	RES_COMMISS_DETAIL_ID,
	RES_PACKAGE_ID,
	GUEST_ID,
	RES_ID,
	COMMISS_SOURCE,
	COMMISS_CODE,
	PERCENT,
	AMOUNT,
	INVOICE_ITEM_TYPE,
	COMMISS_FARE,
	IS_MANUAL_ADJUSTMENT,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RES_COMMISS_DETAIL_ID", "RES_PACKAGE_ID", "GUEST_ID", "RES_ID", "COMMISS_SOURCE", "COMMISS_CODE", "PERCENT", "AMOUNT", "INVOICE_ITEM_TYPE", "COMMISS_FARE", "IS_MANUAL_ADJUSTMENT", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_COMMISSION_DETAIL";
create or replace view RES_EVENT(
	RECORD_ID,
	RES_EVENT_TYPE,
	RES_ID,
	EVENT_TIMESTAMP,
	OPERATOR_ID,
	OLD_STATUS,
	NEW_STATUS,
	OLD_SHIP_CODE,
	OLD_SAIL_FROM,
	OLD_SAIL_TO,
	NEW_SHIP_CODE,
	NEW_SAIL_FROM,
	NEW_SAIL_TO,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RECORD_ID", "RES_EVENT_TYPE", "RES_ID", "EVENT_TIMESTAMP", "OPERATOR_ID", "OLD_STATUS", "NEW_STATUS", "OLD_SHIP_CODE", "OLD_SAIL_FROM", "OLD_SAIL_TO", "NEW_SHIP_CODE", "NEW_SAIL_FROM", "NEW_SAIL_TO", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_EVENT";
create or replace view RES_GUEST(
	GUEST_ID,
	GUEST_SEQN,
	OCCUPANCY_NUMBER,
	RES_ID,
	CLIENT_ID,
	GUEST_TYPE,
	AGE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "GUEST_ID", "GUEST_SEQN", "OCCUPANCY_NUMBER", "RES_ID", "CLIENT_ID", "GUEST_TYPE", "AGE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_GUEST";
create or replace view RES_HEADER(
	RES_ID,
	RES_INIT_DATE,
	RES_GUEST_COUNT,
	AGENCY_ID,
	AGENT_ID,
	CABIN_CATEGORY,
	RES_STATUS,
	PROBABILITY,
	GROUP_ID,
	DELEGATE_HEADER_ID,
	COMMENTS,
	CRS_STATUS,
	DPMS_STATUS,
	TERMINATION_COMPLETED,
	SHIP_CODE,
	PACKAGE_TYPE,
	SAIL_DATE_FROM,
	SAIL_DATE_TO,
	REL_DAY_FROM,
	REL_DAY_TO,
	SOURCE_CODE,
	ALT_RES_ID,
	SEC_AGENCY_ID,
	OFFICE_CODE,
	CURRENCY_RATE,
	CURRENCY_CODE,
	RH_ENTITY_TYPE,
	AM_ORDER_ID,
	CANCELLATION_CASE,
	OFFICE_LOCATION,
	CHANNEL_CODE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RES_ID", "RES_INIT_DATE", "RES_GUEST_COUNT", "AGENCY_ID", "AGENT_ID", "CABIN_CATEGORY", "RES_STATUS", "PROBABILITY", "GROUP_ID", "DELEGATE_HEADER_ID", "COMMENTS", "CRS_STATUS", "DPMS_STATUS", "TERMINATION_COMPLETED", "SHIP_CODE", "PACKAGE_TYPE", "SAIL_DATE_FROM", "SAIL_DATE_TO", "REL_DAY_FROM", "REL_DAY_TO", "SOURCE_CODE", "ALT_RES_ID", "SEC_AGENCY_ID", "OFFICE_CODE", "CURRENCY_RATE", "CURRENCY_CODE", "RH_ENTITY_TYPE", "AM_ORDER_ID", "CANCELLATION_CASE", "OFFICE_LOCATION", "CHANNEL_CODE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_HEADER";
create or replace view RES_HIST_TRANS(
	TRANS_ID,
	RES_ID,
	TRANS_DATE,
	PERFORMER,
	SUBJECT,
	COMMENTS,
	SOURCE_CODE,
	EXTERNAL_USER_ID1,
	EXTERNAL_USER_ID2,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT TRANS_ID, RES_ID, TRANS_DATE, PERFORMER, SUBJECT, COMMENTS, SOURCE_CODE, EXTERNAL_USER_ID1, EXTERNAL_USER_ID2, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_HIST_TRANS;
create or replace view RES_HIST_TREE(
	TREE_NODE_ID,
	NODE_LEVEL,
	NODE_NAME,
	TRANS_ID_INSERT,
	TRANS_ID_DELETE,
	KEY_LEVEL_1,
	KEY_LEVEL_2,
	KEY_LEVEL_3,
	KEY_LEVEL_4,
	KEY_LEVEL_5,
	KEY_LEVEL_6,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT TREE_NODE_ID, NODE_LEVEL, NODE_NAME, TRANS_ID_INSERT, TRANS_ID_DELETE, KEY_LEVEL_1, KEY_LEVEL_2, KEY_LEVEL_3, KEY_LEVEL_4, KEY_LEVEL_5, KEY_LEVEL_6, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_HIST_TREE;
create or replace view RES_HIST_VALUE(
	TREE_NODE_ID,
	TRANS_ID,
	ACTION,
	IT_IS_PARM,
	FIELD_ID,
	FIELD_VALUE_OLD,
	FIELD_VALUE_NEW,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT TREE_NODE_ID, TRANS_ID, "ACTION", IT_IS_PARM, FIELD_ID, FIELD_VALUE_OLD, FIELD_VALUE_NEW, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_HIST_VALUE;
create or replace view RES_INVOICE_CANC(
	RES_INVOICE_ITEM_ID,
	RES_ID,
	GUEST_ID,
	RES_PACKAGE_ID,
	INVOICE_ITEM_TYPE,
	INVOICE_ITEM_SUBTYPE,
	PRICE_PER_UNIT,
	N_OF_UNITS,
	PERCENT,
	AMOUNT,
	INVOICE_ITEM_SUBTYPE2,
	INVOICE_ITEM_SUBTYPE3,
	PRICE_PROGRAM,
	HOTEL_REQUEST_ID,
	COMMISSION_PERCENT,
	SHIP_ROOM_REQUEST_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RES_INVOICE_ITEM_ID", "RES_ID", "GUEST_ID", "RES_PACKAGE_ID", "INVOICE_ITEM_TYPE", "INVOICE_ITEM_SUBTYPE", "PRICE_PER_UNIT", "N_OF_UNITS", "PERCENT", "AMOUNT", "INVOICE_ITEM_SUBTYPE2", "INVOICE_ITEM_SUBTYPE3", "PRICE_PROGRAM", "HOTEL_REQUEST_ID", "COMMISSION_PERCENT", "SHIP_ROOM_REQUEST_ID", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_INVOICE_CANC";
create or replace view RES_INVOICE_ITEM(
	RES_INVOICE_ITEM_ID,
	RES_ID,
	GUEST_ID,
	RES_PACKAGE_ID,
	INVOICE_ITEM_TYPE,
	PRICE_PER_UNIT,
	N_OF_UNITS,
	PERCENT,
	AMOUNT,
	INVOICE_ITEM_SUBTYPE,
	INVOICE_ITEM_SUBTYPE2,
	INVOICE_ITEM_SUBTYPE3,
	PRICE_PROGRAM,
	HOTEL_REQUEST_ID,
	COMMISSION_PERCENT,
	SHIP_ROOM_REQUEST_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RES_INVOICE_ITEM_ID", "RES_ID", "GUEST_ID", "RES_PACKAGE_ID", "INVOICE_ITEM_TYPE", "PRICE_PER_UNIT", "N_OF_UNITS", "PERCENT", "AMOUNT", "INVOICE_ITEM_SUBTYPE", "INVOICE_ITEM_SUBTYPE2", "INVOICE_ITEM_SUBTYPE3", "PRICE_PROGRAM", "HOTEL_REQUEST_ID", "COMMISSION_PERCENT", "SHIP_ROOM_REQUEST_ID", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_INVOICE_ITEM";
create or replace view RES_MANUAL_ADJ(
	MANUAL_ADJ_ID,
	RES_ID,
	GUEST_ID,
	INVOICE_ITEM_TYPE,
	AMOUNT,
	COMMENTS,
	PRE_PAP_FLAG,
	IS_RATE_PROTECTION,
	INVOICE_ITEM_SUBTYPE,
	IS_ACTIVE,
	IS_FINAL,
	REASON,
	AUTHORIZED_BY,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "MANUAL_ADJ_ID", "RES_ID", "GUEST_ID", "INVOICE_ITEM_TYPE", "AMOUNT", "COMMENTS", "PRE_PAP_FLAG", "IS_RATE_PROTECTION", "INVOICE_ITEM_SUBTYPE", "IS_ACTIVE", "IS_FINAL", "REASON", "AUTHORIZED_BY", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_MANUAL_ADJ";
create or replace view RES_PACKAGE(
	RES_PACKAGE_ID,
	START_DATE,
	END_DATE,
	EFFECTIVE_DATE,
	RES_ID,
	GUEST_ID,
	PACKAGE_TYPE,
	PACKAGE_ID,
	IS_PRICEABLE,
	NEEDS_EXTRA_SEAT,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RES_PACKAGE_ID", "START_DATE", "END_DATE", "EFFECTIVE_DATE", "RES_ID", "GUEST_ID", "PACKAGE_TYPE", "PACKAGE_ID", "IS_PRICEABLE", "NEEDS_EXTRA_SEAT", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_PACKAGE";
create or replace view RES_PARAM(
	RES_PARAM_ID,
	PARAM_VALUE,
	RES_ID,
	PARAM_CODE,
	IS_CASE_SENSITIVE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RES_PARAM_ID, PARAM_VALUE, RES_ID, PARAM_CODE, IS_CASE_SENSITIVE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_PARAM;
create or replace view RES_PAYMENT_DUE_ITEM(
	RES_PAYMENT_DUE_ITEM_ID,
	PMNT_DUE_ITEM_TYPE,
	GUEST_ID,
	RES_ID,
	DUE_DATE,
	GRACE_PERIOD,
	AMOUNT,
	EXPIRATION_DATE,
	PAYMENT_SEQN,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RES_PAYMENT_DUE_ITEM_ID", "PMNT_DUE_ITEM_TYPE", "GUEST_ID", "RES_ID", "DUE_DATE", "GRACE_PERIOD", "AMOUNT", "EXPIRATION_DATE", "PAYMENT_SEQN", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_PAYMENT_DUE_ITEM";
create or replace view RES_PROMOTION(
	RES_PROMO_ID,
	RES_ID,
	GUEST_ID,
	PROMO_CODE,
	IS_EXCLUDED,
	IS_ACTIVE,
	RES_PACKAGE_ID,
	IS_MANUAL,
	DATE_APPLIED,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RES_PROMO_ID", "RES_ID", "GUEST_ID", "PROMO_CODE", "IS_EXCLUDED", "IS_ACTIVE", "RES_PACKAGE_ID", "IS_MANUAL", "DATE_APPLIED", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_PROMOTION";
create or replace view RES_STATUS(
	RES_STATUS,
	RES_STATUS_NAME,
	COMMENTS,
	RES_STATUS_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RES_STATUS, RES_STATUS_NAME, COMMENTS, RES_STATUS_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.RES_STATUS;
create or replace view RES_UNIT_ATTR_REQ(
	RECORD_ID,
	RES_ID,
	ATTRIBUTE_CODE,
	STR_VALUE,
	INT_VALUE,
	REQUEST_TYPE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RECORD_ID", "RES_ID", "ATTRIBUTE_CODE", "STR_VALUE", "INT_VALUE", "REQUEST_TYPE", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."RES_UNIT_ATTR_REQ";
create or replace view SHIP(
	SHIP_ID,
	SHIP_CODE,
	SHIP_NAME,
	SHIP_REGISTRY,
	SHIP_BUILT_DATE,
	SHIP_CREW_SIZE,
	SHIP_PAX_CAPACITY,
	SHIP_CRUISING_SPEED,
	SHIP_MAX_SPEED,
	SHIP_LENGTH,
	SHIP_BEAM,
	SHIP_DRAUGHT,
	SHIP_TONNAGE,
	SHIP_STABILIZER,
	COMMENTS,
	IMAGE_ID,
	CRUISE_LINE_CODE,
	SHIP_BRAND,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "SHIP_ID", "SHIP_CODE", "SHIP_NAME", "SHIP_REGISTRY", "SHIP_BUILT_DATE", "SHIP_CREW_SIZE", "SHIP_PAX_CAPACITY", "SHIP_CRUISING_SPEED", "SHIP_MAX_SPEED", "SHIP_LENGTH", "SHIP_BEAM", "SHIP_DRAUGHT", "SHIP_TONNAGE", "SHIP_STABILIZER", "COMMENTS", "IMAGE_ID", "CRUISE_LINE_CODE", "SHIP_BRAND", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."SHIP";
create or replace view SHIP_CABIN(
	SHIP_CODE,
	CABIN_NUMBER,
	CABIN_ID,
	DECK_NUMBER,
	CABIN_NAME,
	COMMENTS,
	IMAGE_ID,
	CABIN_RANK,
	FIREZONE_CODE,
	EXT_CABIN_ID,
	RECORD_ADDED_MANUALLY,
	IS_SPARE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT SHIP_CODE, CABIN_NUMBER, CABIN_ID, DECK_NUMBER, CABIN_NAME, COMMENTS, IMAGE_ID, CABIN_RANK, FIREZONE_CODE, EXT_CABIN_ID, RECORD_ADDED_MANUALLY, IS_SPARE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.SHIP_CABIN;
create or replace view SHIP_CABIN_CTG_LINK(
	RECORD_ID,
	SHIP_CODE,
	CABIN_NUMBER,
	CABIN_CATEGORY,
	EFF_SAIL_FROM,
	EFF_SAIL_TO,
	ROLLAWAY_BEDS,
	CABIN_CAPACITY,
	IS_ACTIVE,
	EXT_CABIN_CONTRACT_TYPE,
	ACCOUNT_NUMBER,
	DUPLEX_STATE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, SHIP_CODE, CABIN_NUMBER, CABIN_CATEGORY, EFF_SAIL_FROM, EFF_SAIL_TO, ROLLAWAY_BEDS, CABIN_CAPACITY, IS_ACTIVE, EXT_CABIN_CONTRACT_TYPE, ACCOUNT_NUMBER, DUPLEX_STATE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.SHIP_CABIN_CTG_LINK;
create or replace view SHIP_CABIN_RESERVE(
	RECORD_ID,
	SHIP_CODE,
	CABIN_NUMBER,
	REL_DAY_FROM,
	REL_DAY_TO,
	SAIL_DATE_FROM,
	SAIL_DATE_TO,
	RESERVE_TYPE,
	COMMENTS,
	GUEST_COUNT,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "RECORD_ID", "SHIP_CODE", "CABIN_NUMBER", "REL_DAY_FROM", "REL_DAY_TO", "SAIL_DATE_FROM", "SAIL_DATE_TO", "RESERVE_TYPE", "COMMENTS", "GUEST_COUNT", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."SHIP_CABIN_RESERVE";
create or replace view SHIP_DECK(
	SHIP_CODE,
	DECK_NUMBER,
	DECK_ID,
	DECK_NAME,
	IS_DECK_PAX,
	IMAGE_ID,
	DECK_CODE,
	LAYOUT_IMAGE_ID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT SHIP_CODE, DECK_NUMBER, DECK_ID, DECK_NAME, IS_DECK_PAX, IMAGE_ID, DECK_CODE, LAYOUT_IMAGE_ID, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.SHIP_DECK;
create or replace view SHIP_INVENTORY_ALLOC(
	ALLOCATION_ID,
	ALLOCATION_OWNER_TYPE,
	ALLOCATION_OWNER_ID,
	OPERATOR_ID,
	ALLOCATION_TIMESTAMP,
	PRIORITY,
	SHIP_CODE,
	REL_DAY_FROM,
	REL_DAY_TO,
	SAIL_DATE_FROM,
	SAIL_DATE_TO,
	CABIN_CATEGORY,
	DEPENDS_ON_ID,
	INVENTORY_REQUEST_TYPE,
	INVENTORY_RESULT_TYPE,
	CABIN_NUMBER,
	PROBABILITY,
	DECLINE_REASON,
	RELEASE_TIMESTAMP,
	OCCUPANCY,
	PRICE_CATEGORY,
	ROLLAWAY_BEDS_REQUESTED,
	RESERVE_TYPE,
	WTL_OWNER_FLAG,
	DLGT_RES_ID,
	IS_DLGT_OBJ,
	OVERLAY_DAY_FROM,
	OVERLAY_DAY_TO,
	IS_SOFT_ASSIGN,
	IS_FIXED_ASSIGN,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "ALLOCATION_ID", "ALLOCATION_OWNER_TYPE", "ALLOCATION_OWNER_ID", "OPERATOR_ID", "ALLOCATION_TIMESTAMP", "PRIORITY", "SHIP_CODE", "REL_DAY_FROM", "REL_DAY_TO", "SAIL_DATE_FROM", "SAIL_DATE_TO", "CABIN_CATEGORY", "DEPENDS_ON_ID", "INVENTORY_REQUEST_TYPE", "INVENTORY_RESULT_TYPE", "CABIN_NUMBER", "PROBABILITY", "DECLINE_REASON", "RELEASE_TIMESTAMP", "OCCUPANCY", "PRICE_CATEGORY", "ROLLAWAY_BEDS_REQUESTED", "RESERVE_TYPE", "WTL_OWNER_FLAG", "DLGT_RES_ID", "IS_DLGT_OBJ", "OVERLAY_DAY_FROM", "OVERLAY_DAY_TO", "IS_SOFT_ASSIGN", "IS_FIXED_ASSIGN", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."SHIP_INVENTORY_ALLOC";
create or replace view SP_REQ_ORDER(
	SP_REQ_ID,
	ORDER_DATE,
	ORDER_DESCRIPT,
	ORD_STATUS_CODE,
	ORDER_VALID,
	AM_BOOKING_TYPE,
	GROUP_ID,
	RES_ID,
	AM_REQ_TYPE,
	AGENCY_ID,
	CLIENT_ID,
	AM_PLACE_CODE,
	AGENT_ID,
	DELIVERY_TIME,
	DISPATCHED_DATE,
	DISPATCHED_OK,
	COMMENTS,
	TERMINATION_COMPLETED,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "SP_REQ_ID", "ORDER_DATE", "ORDER_DESCRIPT", "ORD_STATUS_CODE", "ORDER_VALID", "AM_BOOKING_TYPE", "GROUP_ID", "RES_ID", "AM_REQ_TYPE", "AGENCY_ID", "CLIENT_ID", "AM_PLACE_CODE", "AGENT_ID", "DELIVERY_TIME", "DISPATCHED_DATE", "DISPATCHED_OK", "COMMENTS", "TERMINATION_COMPLETED", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."SP_REQ_ORDER";
create or replace view SP_REQ_ORD_ITEM(
	SP_ORD_ITEM_ID,
	SP_REQ_ID,
	SP_REQ_CODE,
	AM_PLACE_CODE,
	DELIVERY_DATE,
	DELIVERY_TIME,
	QUANTITY,
	COMMENTS,
	GUEST_FULL_NAME,
	GUEST_ID,
	ITEM_VALID,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT "SP_ORD_ITEM_ID", "SP_REQ_ID", "SP_REQ_CODE", "AM_PLACE_CODE", "DELIVERY_DATE", "DELIVERY_TIME", "QUANTITY", "COMMENTS", "GUEST_FULL_NAME", "GUEST_ID", "ITEM_VALID", "HVR_CAPTURE_TIMESTAMP", "HVR_INTEGRATE_TIMESTAMP", "HVR_OPERATION_CODE" FROM "WARNER_RAW"."SEAWARE_APS"."SP_REQ_ORD_ITEM";
create or replace view UNIT_CATEGORY_ATTR_LINK(
	RECORD_ID,
	SHIP_CODE,
	CABIN_CATEGORY,
	ATTRIBUTE_CODE,
	ATTRIBUTE_VALUE_STR,
	ATTRIBUTE_VALUE_INT,
	VALUE_SEQN,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT RECORD_ID, SHIP_CODE, CABIN_CATEGORY, ATTRIBUTE_CODE, ATTRIBUTE_VALUE_STR, ATTRIBUTE_VALUE_INT, VALUE_SEQN, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.UNIT_CATEGORY_ATTR_LINK;
create or replace view USER_LOGIN(
	USER_ID,
	USER_LOGIN_NAME,
	USER_PASSWORD,
	USER_FIRST_NAME,
	USER_MIDDLE_NAME,
	USER_LAST_NAME,
	USER_FULL_NAME,
	COMMENTS,
	OFFICE_CODE,
	ADMINISTRATIVE_OFFICE,
	OFFICE_LOCATION_CODE,
	HVR_CAPTURE_TIMESTAMP,
	HVR_INTEGRATE_TIMESTAMP,
	HVR_OPERATION_CODE
) as SELECT USER_ID, USER_LOGIN_NAME, USER_PASSWORD, USER_FIRST_NAME, USER_MIDDLE_NAME, USER_LAST_NAME, USER_FULL_NAME, COMMENTS, OFFICE_CODE, ADMINISTRATIVE_OFFICE, OFFICE_LOCATION_CODE, HVR_CAPTURE_TIMESTAMP, HVR_INTEGRATE_TIMESTAMP, HVR_OPERATION_CODE
FROM WARNER_RAW.SEAWARE_APS.USER_LOGIN;