USE ROLE dba;

USE SCHEMA warner_base.ma_mart;

-- WARNER_BASE.MA_MART.D_WRN_BOOKING source

create or replace view WARNER_BASE.MA_MART.D_WRN_BOOKING(
	BOOKING_REFERENCE,
	PERSON_ID,
	SUBJECT_ID,
	ARRIVAL_DATE,
	DEPARTURE_DATE,
	BOOK_DATE,
	BREAK_DURATION,
	TOTAL_GUESTS,
	TOTAL_ROOMS,
	REFERRAL_SOURCE,
	BREAK_STYLE,
	BREAK_TYPE,
	BREAK_DESCRIPTION,
	HOTEL_NAME,
	HOTEL_CATEGORY,
	ROOM_TYPE,
	ROOM_CODE,
	BOOK_LEAD_TIME,
	MULTI_ROOM_BOOKING,
	MISSION,
	BOOKING_CANCELLED,
	BOARD_TYPE,
	EMAIL_ADDRESS,
	SITE_CD,
	STATUS,
	VALID_EMAIL,
	VALID_EMAIL_DOMAIN,
	PAF_VALID,
	SPARE_1,
	SPARE_2,
	SPARE_3,
	SPARE_4,
	SPARE_5,
	SPARE_6
) as SELECT "BOOKING_REFERENCE", "PERSON_ID", "SUBJECT_ID", "ARRIVAL_DATE", "DEPARTURE_DATE", "BOOK_DATE", "BREAK_DURATION", "TOTAL_GUESTS", "TOTAL_ROOMS", "REFERRAL_SOURCE", "BREAK_STYLE", "BREAK_TYPE", "BREAK_DESCRIPTION", "HOTEL_NAME", "HOTEL_CATEGORY", "ROOM_TYPE", "ROOM_CODE", "BOOK_LEAD_TIME", "MULTI_ROOM_BOOKING", "MISSION", "BOOKING_CANCELLED", "BOARD_TYPE", "EMAIL_ADDRESS", "SITE_CD", "STATUS", "VALID_EMAIL", "VALID_EMAIL_DOMAIN", "PAF_VALID", "SPARE_1", "SPARE_2", "SPARE_3", "SPARE_4", "SPARE_5", "SPARE_6" FROM "WARNER_RAW"."MA_MART"."D_WRN_BOOKING";


-- WARNER_BASE.MA_MART.D_WRN_BOOKING_HISTORY_EVENTS source

create or replace view WARNER_BASE.MA_MART.D_WRN_BOOKING_HISTORY_EVENTS(
	BOOKING_ID,
	EMAIL_ID,
	GUEST_WEEKS,
	GROSS_TARIFF,
	GATA,
	ROOMS_BOOKED,
	SITE_CD,
	BREAK_TYPE_REF,
	BOOKED_ACCOM_REF,
	BOOKING_CHANNEL_CD,
	BOOKING_SOURCE_TYPE,
	SRC_SYS_BK_NO,
	ADDRESS_ID,
	BOOK_DT,
	TOTAL_GUESTS,
	ARRIVAL_DT,
	DEPARTURE_DT,
	STATUS,
	BOOKING_CHANNEL_GROUP,
	VALID_FROM_DTTM,
	VALID_TO_DTTM,
	RECORD_CLASS,
	ACCOM_GROSS,
	BOOK_STATUS,
	BREAK_TYPE2,
	ROOM_TYPE,
	EVENT_TYPE,
	FLAG_BOOKING,
	CHANGE_BOOK_DT,
	CHANGE_ARRIVAL_DT,
	CHANGE_SITE_CD,
	CHANGE_GUEST_WEEKS,
	CHANGE_GROSS_TARIFF,
	CHANGE_ADDRESS_ID,
	CHANGE_BOOKING_CHANNEL_CD,
	ARRIVAL_YEAR,
	ARRIVAL_MONTH,
	HOUSEHOLD,
	BOOK_COUNTER,
	BOOK_TYPE,
	SEG,
	NEW_REPEAT
) as SELECT BOOKING_ID, EMAIL_ID, GUEST_WEEKS, GROSS_TARIFF, GATA, ROOMS_BOOKED, SITE_CD, BREAK_TYPE_REF, BOOKED_ACCOM_REF, BOOKING_CHANNEL_CD, BOOKING_SOURCE_TYPE, SRC_SYS_BK_NO, ADDRESS_ID, BOOK_DT, TOTAL_GUESTS, ARRIVAL_DT, DEPARTURE_DT, STATUS, BOOKING_CHANNEL_GROUP, VALID_FROM_DTTM, VALID_TO_DTTM, RECORD_CLASS, ACCOM_GROSS, BOOK_STATUS, BREAK_TYPE2, ROOM_TYPE, EVENT_TYPE, FLAG_BOOKING, CHANGE_BOOK_DT, CHANGE_ARRIVAL_DT, CHANGE_SITE_CD, CHANGE_GUEST_WEEKS, CHANGE_GROSS_TARIFF, CHANGE_ADDRESS_ID, CHANGE_BOOKING_CHANNEL_CD, ARRIVAL_YEAR, ARRIVAL_MONTH, HOUSEHOLD, BOOK_COUNTER, BOOK_TYPE, SEG, NEW_REPEAT
FROM WARNER_RAW.MA_MART.D_WRN_BOOKING_HISTORY_EVENTS;


-- WARNER_BASE.MA_MART.D_WRN_BOOKINGTYPES source

create or replace view WARNER_BASE.MA_MART.D_WRN_BOOKINGTYPES(
	BOOKING_ID,
	GUEST_WEEKS,
	GROSS_TARIFF,
	LEAD_TIME,
	BOOK_DT,
	ARRIVAL_DT,
	VALID_FROM_DTTM,
	VALID_TO_DTTM,
	EMAIL_ID,
	BOOKING_CHANNEL_CD,
	SITE_CD,
	ADDRESS_ID,
	ARRIVAL_YEAR,
	ARRIVAL_MONTH,
	BOOK_YEAR,
	BOOK_MONTH,
	ADDRESS_BARCODE,
	POSTCODE_SECTOR,
	BOOK_COUNTER,
	BOOK_TYPE
) as SELECT BOOKING_ID, GUEST_WEEKS, GROSS_TARIFF, LEAD_TIME, BOOK_DT, ARRIVAL_DT, VALID_FROM_DTTM, VALID_TO_DTTM, EMAIL_ID, BOOKING_CHANNEL_CD, SITE_CD, ADDRESS_ID, ARRIVAL_YEAR, ARRIVAL_MONTH, BOOK_YEAR, BOOK_MONTH, ADDRESS_BARCODE, POSTCODE_SECTOR, BOOK_COUNTER, BOOK_TYPE
FROM WARNER_RAW.MA_MART.D_WRN_BOOKINGTYPES;


-- WARNER_BASE.MA_MART.D_WRN_CAMPAIGN_REPORTING source

create or replace view WARNER_BASE.MA_MART.D_WRN_CAMPAIGN_REPORTING(
	TASK_NAME,
	TASK_CODE,
	CHANNEL,
	CAMPAIGN_NAME,
	CAMPAIGN_CODE,
	OCCURRENCE,
	SEGMENT_NAME,
	SEGMENT_CODE,
	FLAG_CONTROL_CELL_EM,
	SEGMENT_MAP_NAME,
	CONTACT_DATE,
	CONTACT_DTTM,
	DROP_DATE,
	SUBJECT_ID,
	EMAIL_SEND_DTTM,
	EMAIL_OPEN_DTTM,
	NB_EMAIL_OPENS,
	EMAIL_CLICK_DTTM,
	NB_EMAIL_CLICKS,
	FLAG_EMAIL_SEND,
	FLAG_EMAIL_OPEN,
	FLAG_EMAIL_CLICK,
	FLAG_UNSUBSCRIBE,
	FLAG_DM_SEND,
	ADDRESS_ID,
	PERSON_ID,
	PERSON_EMAIL_ID,
	GUEST_SEGMENT,
	CONTACT_YEAR,
	CONTACT_PERIOD,
	CONTACT_WEEK,
	CONTACT_WEEK_START_DT,
	CONTACT_WEEK_END_DT,
	BOOKING_ID,
	GUEST_WEEKS,
	GROSS_TARIFF,
	LEAD_TIME,
	BOOK_DT,
	ARRIVAL_DT,
	VALID_FROM_DTTM,
	VALID_TO_DTTM,
	BOOKING_EMAIL_ID,
	BOOKING_CHANNEL_CD,
	PRE_BOOK_DT,
	SITE_CD,
	ARRIVAL_MONTH,
	ARRIVAL_YEAR,
	BOOK_YEAR,
	PREVIEW,
	BOOK_TYPE,
	HOTEL_NAME,
	NEW_REPEAT,
	FLAG_BOOKING,
	BOOKING_GUEST_WEEKS,
	BOOKING_GROSS_TARIFF,
	FLAG_DISTINCT_BOOKING,
	DISTINCT_BOOKING_GUEST_WEEKS,
	DISTINCT_BOOKING_GROSS_TARIFF
) as SELECT TASK_NAME, TASK_CODE, CHANNEL, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, FLAG_CONTROL_CELL_EM, SEGMENT_MAP_NAME, CONTACT_DATE, CONTACT_DTTM, DROP_DATE, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, NB_EMAIL_OPENS, EMAIL_CLICK_DTTM, NB_EMAIL_CLICKS, FLAG_EMAIL_SEND, FLAG_EMAIL_OPEN, FLAG_EMAIL_CLICK, FLAG_UNSUBSCRIBE, FLAG_DM_SEND, ADDRESS_ID, PERSON_ID, PERSON_EMAIL_ID, GUEST_SEGMENT, CONTACT_YEAR, CONTACT_PERIOD, CONTACT_WEEK, CONTACT_WEEK_START_DT, CONTACT_WEEK_END_DT, BOOKING_ID, GUEST_WEEKS, GROSS_TARIFF, LEAD_TIME, BOOK_DT, ARRIVAL_DT, VALID_FROM_DTTM, VALID_TO_DTTM, BOOKING_EMAIL_ID, BOOKING_CHANNEL_CD, PRE_BOOK_DT, SITE_CD, ARRIVAL_MONTH, ARRIVAL_YEAR, BOOK_YEAR, PREVIEW, BOOK_TYPE, HOTEL_NAME, NEW_REPEAT, FLAG_BOOKING, BOOKING_GUEST_WEEKS, BOOKING_GROSS_TARIFF, FLAG_DISTINCT_BOOKING, DISTINCT_BOOKING_GUEST_WEEKS, DISTINCT_BOOKING_GROSS_TARIFF
FROM WARNER_RAW.MA_MART.D_WRN_CAMPAIGN_REPORTING;


-- WARNER_BASE.MA_MART.D_WRN_CANOPY_SEEDS source

create or replace view WARNER_BASE.MA_MART.D_WRN_CANOPY_SEEDS(
	ADDRESS_ID,
	ARRIVAL_DATE,
	BOOKING_REFERENCE,
	DELEGATE1,
	DELEGATE2,
	DELEGATE3,
	DELEGATE4,
	EMAIL_ADDRESS,
	FIRSTNAME,
	HOTEL_NAME,
	MULTI_UNIT_BOOKING,
	NUMBER_GUESTS,
	NUMBER_ROOMS,
	PERSON_ID,
	SITE_CODE,
	SUBJECT_ID,
	SURNAME,
	TITLE
) as SELECT ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE
FROM WARNER_RAW.MA_MART.D_WRN_CANOPY_SEEDS;


-- WARNER_BASE.MA_MART.D_WRN_CONTACT_RESPONSE source

create or replace view WARNER_BASE.MA_MART.D_WRN_CONTACT_RESPONSE(
	TASK_NAME,
	TASK_CODE,
	CAMPAIGN_NAME,
	CAMPAIGN_CODE,
	OCCURRENCE,
	SEGMENT_NAME,
	SEGMENT_CODE,
	SEGMENT_MAP_NAME,
	CONTACT_DATE,
	CONTACT_DTTM,
	SUBJECT_ID,
	EMAIL_SEND_DTTM,
	EMAIL_OPEN_DTTM,
	EMAIL_CLICK_DTTM
) as SELECT TASK_NAME, TASK_CODE, CAMPAIGN_NAME, CAMPAIGN_CODE, OCCURRENCE, SEGMENT_NAME, SEGMENT_CODE, SEGMENT_MAP_NAME, CONTACT_DATE, CONTACT_DTTM, SUBJECT_ID, EMAIL_SEND_DTTM, EMAIL_OPEN_DTTM, EMAIL_CLICK_DTTM
FROM WARNER_RAW.MA_MART.D_WRN_CONTACT_RESPONSE;


-- WARNER_BASE.MA_MART.D_WRN_CONTENT_MATRIX source

create or replace view WARNER_BASE.MA_MART.D_WRN_CONTENT_MATRIX(
	SITE_CODE,
	HOTEL_NAME,
	HOTEL,
	HOTEL_ADDRESS,
	EXPLORE_THE_AREA,
	HERO_IMAGE,
	HERO_CTA,
	ARRIVAL_DAY_IMAGE,
	ARRIVAL_DAY_COPY,
	USEFUL_INFO_IMAGE,
	USEFUL_INFO_COPY,
	DINING_IMAGE,
	DINING_COPY,
	DINING_CTA,
	PHONE_NUMBER,
	EXCURSION_ONE_HERO_IMAGE,
	EXCURSION_ONE_COPY,
	EXCURSION_ONE_CTA,
	EXCURSION_TWO_HERO_COPY,
	EXCURSION_TWO_HERO_IMAGE,
	EXCURSION_TWO_HERO_CTA,
	EXCURSION_THREE_HERO_IMAGE,
	EXCURSION_THREE_HERO_COPY,
	EXCURSION_THREE_HERO_CTA
) as SELECT "SITE_CODE", "HOTEL_NAME", "HOTEL", "HOTEL_ADDRESS", "EXPLORE_THE_AREA", "HERO_IMAGE", "HERO_CTA", "ARRIVAL_DAY_IMAGE", "ARRIVAL_DAY_COPY", "USEFUL_INFO_IMAGE", "USEFUL_INFO_COPY", "DINING_IMAGE", "DINING_COPY", "DINING_CTA", "PHONE_NUMBER", "EXCURSION_ONE_HERO_IMAGE", "EXCURSION_ONE_COPY", "EXCURSION_ONE_CTA", "EXCURSION_TWO_HERO_COPY", "EXCURSION_TWO_HERO_IMAGE", "EXCURSION_TWO_HERO_CTA", "EXCURSION_THREE_HERO_IMAGE", "EXCURSION_THREE_HERO_COPY", "EXCURSION_THREE_HERO_CTA" FROM "WARNER_RAW"."MA_MART"."D_WRN_CONTENT_MATRIX";


-- WARNER_BASE.MA_MART.D_WRN_CONTENT_MATRIX_SEEDS source

create or replace view WARNER_BASE.MA_MART.D_WRN_CONTENT_MATRIX_SEEDS(
	SITE_CODE,
	HOTEL_NAME,
	HOTEL,
	HOTEL_ADDRESS,
	EXPLORE_THE_AREA,
	HERO_IMAGE,
	HERO_CTA,
	ARRIVAL_DAY_IMAGE,
	ARRIVAL_DAY_COPY,
	USEFUL_INFO_IMAGE,
	USEFUL_INFO_COPY,
	DINING_IMAGE,
	DINING_COPY,
	DINING_CTA,
	PHONE_NUMBER,
	EXCURSION_ONE_HERO_IMAGE,
	EXCURSION_ONE_COPY,
	EXCURSION_ONE_CTA,
	EXCURSION_TWO_HERO_COPY,
	EXCURSION_TWO_HERO_IMAGE,
	EXCURSION_TWO_HERO_CTA,
	EXCURSION_THREE_HERO_IMAGE,
	EXCURSION_THREE_HERO_COPY,
	EXCURSION_THREE_HERO_CTA
) as SELECT "SITE_CODE", "HOTEL_NAME", "HOTEL", "HOTEL_ADDRESS", "EXPLORE_THE_AREA", "HERO_IMAGE", "HERO_CTA", "ARRIVAL_DAY_IMAGE", "ARRIVAL_DAY_COPY", "USEFUL_INFO_IMAGE", "USEFUL_INFO_COPY", "DINING_IMAGE", "DINING_COPY", "DINING_CTA", "PHONE_NUMBER", "EXCURSION_ONE_HERO_IMAGE", "EXCURSION_ONE_COPY", "EXCURSION_ONE_CTA", "EXCURSION_TWO_HERO_COPY", "EXCURSION_TWO_HERO_IMAGE", "EXCURSION_TWO_HERO_CTA", "EXCURSION_THREE_HERO_IMAGE", "EXCURSION_THREE_HERO_COPY", "EXCURSION_THREE_HERO_CTA" FROM "WARNER_RAW"."MA_MART"."D_WRN_CONTENT_MATRIX_SEEDS";


-- WARNER_BASE.MA_MART.D_WRN_EM_BAU_SEEDS source

create or replace view WARNER_BASE.MA_MART.D_WRN_EM_BAU_SEEDS(
	SUBJECT_ID,
	PERSON_ID,
	ADDRESS_ID,
	TITLE,
	FIRSTNAME,
	SURNAME,
	EMAIL_ADDRESS
) as SELECT SUBJECT_ID, PERSON_ID, ADDRESS_ID, TITLE, FIRSTNAME, SURNAME, EMAIL_ADDRESS
FROM WARNER_RAW.MA_MART.D_WRN_EM_BAU_SEEDS;


-- WARNER_BASE.MA_MART.D_WRN_EMAIL_SEEDS source

create or replace view WARNER_BASE.MA_MART.D_WRN_EMAIL_SEEDS(
	ADDRESS_ID,
	ARRIVAL_DATE,
	BOOKING_REFERENCE,
	DELEGATE1,
	DELEGATE2,
	DELEGATE3,
	DELEGATE4,
	EMAIL_ADDRESS,
	FIRSTNAME,
	HOTEL_NAME,
	MULTI_UNIT_BOOKING,
	NUMBER_GUESTS,
	NUMBER_ROOMS,
	PERSON_ID,
	SITE_CODE,
	SUBJECT_ID,
	SURNAME,
	TITLE
) as SELECT ADDRESS_ID, ARRIVAL_DATE, BOOKING_REFERENCE, DELEGATE1, DELEGATE2, DELEGATE3, DELEGATE4, EMAIL_ADDRESS, FIRSTNAME, HOTEL_NAME, MULTI_UNIT_BOOKING, NUMBER_GUESTS, NUMBER_ROOMS, PERSON_ID, SITE_CODE, SUBJECT_ID, SURNAME, TITLE
FROM WARNER_RAW.MA_MART.D_WRN_EMAIL_SEEDS;


-- WARNER_BASE.MA_MART.D_WRN_GUEST source

create or replace view WARNER_BASE.MA_MART.D_WRN_GUEST(
	PERSON_ID,
	SUBJECT_ID,
	ADDRESS_ID,
	TITLE,
	FIRSTNAME,
	SURNAME,
	EMAIL_ADDRESS,
	FIRST_LINE_ADDRESS,
	SECOND_LINE_ADDRESS,
	THIRD_LINE_ADDRESS,
	FOURTH_LINE_ADDRESS,
	FIFTH_LINE_ADDRESS,
	SIXTH_LINE_ADDRESS,
	POSTCODE,
	RFSEGMENT2022,
	FSEGMENT2022,
	RSEGMENT2022,
	PROSPECT_DATE,
	CLUB_MEMBER,
	NON_CLUB_MEMBER,
	ACTIVE,
	FTALLY,
	NEAREST_HOTEL_UNDER_TWO_HOURS,
	DRIVE_TIME_TO_ALVASTON_HALL,
	DRIVE_TIME_TO_BODELWYDDAN_CASTLE,
	DRIVE_TIME_TO_BEMBRIDGE_COAST,
	DRIVE_TIME_TO_CRICKET_ST_THOMAS,
	DRIVE_TIME_TO_CORTON,
	DRIVE_TIME_TO_GUNTON_HALL,
	DRIVE_TIME_TO_HOLME_LACY_HOUSE,
	DRIVE_TIME_TO_LITTLECOTE_HOUSE,
	DRIVE_TIME_TO_LAKESIDE,
	DRIVE_TIME_TO_NORTON_GRANGE,
	DRIVE_TIME_TO_NIDD_HALL,
	DRIVE_TIME_TO_SINAH_WARREN,
	DRIVE_TIME_TO_THORESBY_HALL,
	DRIVE_TIME_TO_STUDLEY_CASTLE,
	DRIVE_TIME_TO_HEYTHROP_PARK,
	LATE_BOOKER,
	PROSPECT_TYPE,
	LAST_ENEWS_SIGN_UP_DATE,
	LAST_BROCHURE_REQUEST_DATE,
	LAST_CANCELLED_DATE,
	LAST_QUOTE_DATE,
	OPTED_IN_TO_EMAIL,
	OPTED_IN_TO_DM,
	NUMBER_BOOKINGS_LAST_2_MONTH_HH,
	NUMBER_OF_PREVIOUS_STAYS_HH,
	NUMBER_OF_FUTURE_BOOKINGS_HH,
	NUMBER_OF_STAYS_LAST_6_MONTH_HH,
	NUMBER_OF_STAYS_LAST_12_MONTH_HH,
	NUMBER_OF_STAYS_LAST_2_YEARS_HH,
	NUMBER_OF_STAYS_LAST_3_YEARS_HH,
	NUMBER_OF_STAYS_LAST_5_YEARS_HH,
	DECEASED,
	VALID_EMAIL,
	VALID_EMAIL_DOMAIN,
	PAF_VALID,
	FLAG_GUEST,
	SPARE_1,
	SPARE_2,
	SPARE_3,
	SPARE_4,
	SPARE_5,
	SPARE_6
) as SELECT "PERSON_ID", "SUBJECT_ID", "ADDRESS_ID", "TITLE", "FIRSTNAME", "SURNAME", "EMAIL_ADDRESS", "FIRST_LINE_ADDRESS", "SECOND_LINE_ADDRESS", "THIRD_LINE_ADDRESS", "FOURTH_LINE_ADDRESS", "FIFTH_LINE_ADDRESS", "SIXTH_LINE_ADDRESS", "POSTCODE", "RFSEGMENT2022", "FSEGMENT2022", "RSEGMENT2022", "PROSPECT_DATE", "CLUB_MEMBER", "NON_CLUB_MEMBER", "ACTIVE", "FTALLY", "NEAREST_HOTEL_UNDER_TWO_HOURS", "DRIVE_TIME_TO_ALVASTON_HALL", "DRIVE_TIME_TO_BODELWYDDAN_CASTLE", "DRIVE_TIME_TO_BEMBRIDGE_COAST", "DRIVE_TIME_TO_CRICKET_ST_THOMAS", "DRIVE_TIME_TO_CORTON", "DRIVE_TIME_TO_GUNTON_HALL", "DRIVE_TIME_TO_HOLME_LACY_HOUSE", "DRIVE_TIME_TO_LITTLECOTE_HOUSE", "DRIVE_TIME_TO_LAKESIDE", "DRIVE_TIME_TO_NORTON_GRANGE", "DRIVE_TIME_TO_NIDD_HALL", "DRIVE_TIME_TO_SINAH_WARREN", "DRIVE_TIME_TO_THORESBY_HALL", "DRIVE_TIME_TO_STUDLEY_CASTLE", "DRIVE_TIME_TO_HEYTHROP_PARK", "LATE_BOOKER", "PROSPECT_TYPE", "LAST_ENEWS_SIGN_UP_DATE", "LAST_BROCHURE_REQUEST_DATE", "LAST_CANCELLED_DATE", "LAST_QUOTE_DATE", "OPTED_IN_TO_EMAIL", "OPTED_IN_TO_DM", "NUMBER_BOOKINGS_LAST_2_MONTH_HH", "NUMBER_OF_PREVIOUS_STAYS_HH", "NUMBER_OF_FUTURE_BOOKINGS_HH", "NUMBER_OF_STAYS_LAST_6_MONTH_HH", "NUMBER_OF_STAYS_LAST_12_MONTH_HH", "NUMBER_OF_STAYS_LAST_2_YEARS_HH", "NUMBER_OF_STAYS_LAST_3_YEARS_HH", "NUMBER_OF_STAYS_LAST_5_YEARS_HH", "DECEASED", "VALID_EMAIL", "VALID_EMAIL_DOMAIN", "PAF_VALID", "FLAG_GUEST", "SPARE_1", "SPARE_2", "SPARE_3", "SPARE_4", "SPARE_5", "SPARE_6" FROM "WARNER_RAW"."MA_MART"."D_WRN_GUEST";


-- WARNER_BASE.MA_MART.D_WRN_GUESTSEGMENTS source

create or replace view WARNER_BASE.MA_MART.D_WRN_GUESTSEGMENTS(
	SEGMENT_YEAR,
	ADDRESS_ID,
	DISTINCT_YEARS,
	BOOKINGS,
	GUEST_WEEKS,
	GROSS_TARIFF,
	LAST_ARRIVAL_YEAR,
	SEG
) as SELECT "SEGMENT_YEAR", "ADDRESS_ID", "DISTINCT_YEARS", "BOOKINGS", "GUEST_WEEKS", "GROSS_TARIFF", "LAST_ARRIVAL_YEAR", "SEG" FROM "WARNER_RAW"."MA_MART"."D_WRN_GUESTSEGMENTS";


-- WARNER_BASE.MA_MART.D_WRN_HOUSEHOLD source

create or replace view WARNER_BASE.MA_MART.D_WRN_HOUSEHOLD(
	ADDRESS_ID
) as SELECT ADDRESS_ID
FROM WARNER_RAW.MA_MART.D_WRN_HOUSEHOLD;


-- WARNER_BASE.MA_MART.D_WRN_ITG_CANOPY_GUEST_TEST_ERR source

create or replace view WARNER_BASE.MA_MART.D_WRN_ITG_CANOPY_GUEST_TEST_ERR(
	PERSON_ID,
	ADDRESS_ID,
	TITLE,
	FIRSTNAME,
	SURNAME,
	EMAIL_ADDRESS,
	FIRST_LINE_ADDRESS,
	SECOND_LINE_ADDRESS,
	THIRD_LINE_ADDRESS,
	FOURTH_LINE_ADDRESS,
	FIFTH_LINE_ADDRESS,
	SIXTH_LINE_ADDRESS,
	POSTCODE,
	RFSEGMENT2022,
	FSEGMENT2022,
	RSEGMENT2022,
	PROSPECT_DATE,
	CLUB_MEMBER,
	NON_CLUB_MEMBER,
	ACTIVE,
	FTALLY,
	NEAREST_HOTEL_UNDER_TWO_HOURS,
	DRIVE_TIME_TO_ALVASTON_HALL,
	DRIVE_TIME_TO_BODELWYDDAN_CASTLE,
	DRIVE_TIME_TO_BEMBRIDGE_COAST,
	DRIVE_TIME_TO_CRICKET_ST_THOMAS,
	DRIVE_TIME_TO_CORTON,
	DRIVE_TIME_TO_GUNTON_HALL,
	DRIVE_TIME_TO_HOLME_LACY_HOUSE,
	DRIVE_TIME_TO_LITTLECOTE_HOUSE,
	DRIVE_TIME_TO_LAKESIDE,
	DRIVE_TIME_TO_NORTON_GRANGE,
	DRIVE_TIME_TO_NIDD_HALL,
	DRIVE_TIME_TO_SINAH_WARREN,
	DRIVE_TIME_TO_THORESBY_HALL,
	DRIVE_TIME_TO_STUDLEY_CASTLE,
	DRIVE_TIME_TO_HEYTHROP_PARK,
	LATE_BOOKER,
	PROSPECT_TYPE,
	LAST_ENEWS_SIGN_UP_DATE,
	LAST_BROCHURE_REQUEST_DATE,
	LAST_CANCELLED_DATE,
	LAST_QUOTE_DATE,
	OPTED_IN_TO_EMAIL,
	OPTED_IN_TO_DM,
	NUMBER_BOOKINGS_LAST_2_MONTH_HH,
	NUMBER_OF_PREVIOUS_STAYS_HH,
	NUMBER_OF_FUTURE_BOOKINGS_HH,
	NUMBER_OF_STAYS_LAST_6_MONTH_HH,
	NUMBER_OF_STAYS_LAST_12_MONTH_HH,
	NUMBER_OF_STAYS_LAST_2_YEARS_HH,
	NUMBER_OF_STAYS_LAST_3_YEARS_HH,
	NUMBER_OF_STAYS_LAST_5_YEARS_HH,
	DECEASED,
	SPARE_1,
	SPARE_2,
	SPARE_3,
	SPARE_4,
	SPARE_5,
	SPARE_6,
	PROCESSED_DTTM
) as SELECT "PERSON_ID", "ADDRESS_ID", "TITLE", "FIRSTNAME", "SURNAME", "EMAIL_ADDRESS", "FIRST_LINE_ADDRESS", "SECOND_LINE_ADDRESS", "THIRD_LINE_ADDRESS", "FOURTH_LINE_ADDRESS", "FIFTH_LINE_ADDRESS", "SIXTH_LINE_ADDRESS", "POSTCODE", "RFSEGMENT2022", "FSEGMENT2022", "RSEGMENT2022", "PROSPECT_DATE", "CLUB_MEMBER", "NON_CLUB_MEMBER", "ACTIVE", "FTALLY", "NEAREST_HOTEL_UNDER_TWO_HOURS", "DRIVE_TIME_TO_ALVASTON_HALL", "DRIVE_TIME_TO_BODELWYDDAN_CASTLE", "DRIVE_TIME_TO_BEMBRIDGE_COAST", "DRIVE_TIME_TO_CRICKET_ST_THOMAS", "DRIVE_TIME_TO_CORTON", "DRIVE_TIME_TO_GUNTON_HALL", "DRIVE_TIME_TO_HOLME_LACY_HOUSE", "DRIVE_TIME_TO_LITTLECOTE_HOUSE", "DRIVE_TIME_TO_LAKESIDE", "DRIVE_TIME_TO_NORTON_GRANGE", "DRIVE_TIME_TO_NIDD_HALL", "DRIVE_TIME_TO_SINAH_WARREN", "DRIVE_TIME_TO_THORESBY_HALL", "DRIVE_TIME_TO_STUDLEY_CASTLE", "DRIVE_TIME_TO_HEYTHROP_PARK", "LATE_BOOKER", "PROSPECT_TYPE", "LAST_ENEWS_SIGN_UP_DATE", "LAST_BROCHURE_REQUEST_DATE", "LAST_CANCELLED_DATE", "LAST_QUOTE_DATE", "OPTED_IN_TO_EMAIL", "OPTED_IN_TO_DM", "NUMBER_BOOKINGS_LAST_2_MONTH_HH", "NUMBER_OF_PREVIOUS_STAYS_HH", "NUMBER_OF_FUTURE_BOOKINGS_HH", "NUMBER_OF_STAYS_LAST_6_MONTH_HH", "NUMBER_OF_STAYS_LAST_12_MONTH_HH", "NUMBER_OF_STAYS_LAST_2_YEARS_HH", "NUMBER_OF_STAYS_LAST_3_YEARS_HH", "NUMBER_OF_STAYS_LAST_5_YEARS_HH", "DECEASED", "SPARE_1", "SPARE_2", "SPARE_3", "SPARE_4", "SPARE_5", "SPARE_6", "PROCESSED_DTTM" FROM "WARNER_RAW"."MA_MART"."D_WRN_ITG_CANOPY_GUEST_TEST_ERR";


-- WARNER_BASE.MA_MART.D_WRN_KPIS_OUTPUT_DASHBOARD source

create or replace view WARNER_BASE.MA_MART.D_WRN_KPIS_OUTPUT_DASHBOARD(
	ARRIVAL_PERIOD,
	SEG,
	RELATIVE_EVENT_PERIOD,
	RELATIVE_EVENT_WEEK,
	BOOK_TYPE,
	EVENT_TIME,
	GROSS_HOUSEHOLDS,
	GROSS_BOOKINGS,
	GROSS_GUEST_WEEKS,
	GROSS_GROSS_TARIFF,
	GROSS_BOOKINGS_ACTUAL,
	GROSS_HOUSEHOLDS_ACTUAL,
	GROSS_GUEST_WEEKS_ACTUAL,
	GROSS_GROSS_TARIFF_ACTUAL,
	CANCEL_BOOKINGS_ACTUAL,
	CANCEL_HOUSEHOLDS_ACTUAL,
	CANCEL_GUEST_WEEKS_ACTUAL,
	CANCEL_GROSS_TARIFF_ACTUAL,
	SITE_NAME,
	CHANNEL,
	GROSS_BOOKINGS_BASE,
	GROSS_HOUSEHOLDS_BASE,
	GROSS_GUEST_WEEKS_BASE,
	GROSS_GROSS_TARIFF_BASE,
	FLG_UPTO_WEEK,
	BOOKING_CHANNEL_CD,
	SITE_CD,
	EVENT_WEEK_YEAR,
	NET_BOOKINGS_ACTUAL,
	NET_HOUSEHOLDS_ACTUAL,
	NET_GUEST_WEEKS_ACTUAL,
	NET_GROSS_TARIFF_ACTUAL,
	STARTING_HOUSEHOLDS,
	GROSS_RETENTION_BASE,
	GROSS_RETENTION_ACTUAL,
	FLG_52_WEEK,
	EVENT_YEAR
) as SELECT ARRIVAL_PERIOD, SEG, RELATIVE_EVENT_PERIOD, RELATIVE_EVENT_WEEK, BOOK_TYPE, EVENT_TIME, GROSS_HOUSEHOLDS, GROSS_BOOKINGS, GROSS_GUEST_WEEKS, GROSS_GROSS_TARIFF, GROSS_BOOKINGS_ACTUAL, GROSS_HOUSEHOLDS_ACTUAL, GROSS_GUEST_WEEKS_ACTUAL, GROSS_GROSS_TARIFF_ACTUAL, CANCEL_BOOKINGS_ACTUAL, CANCEL_HOUSEHOLDS_ACTUAL, CANCEL_GUEST_WEEKS_ACTUAL, CANCEL_GROSS_TARIFF_ACTUAL, SITE_NAME, CHANNEL, GROSS_BOOKINGS_BASE, GROSS_HOUSEHOLDS_BASE, GROSS_GUEST_WEEKS_BASE, GROSS_GROSS_TARIFF_BASE, FLG_UPTO_WEEK, BOOKING_CHANNEL_CD, SITE_CD, EVENT_WEEK_YEAR, NET_BOOKINGS_ACTUAL, NET_HOUSEHOLDS_ACTUAL, NET_GUEST_WEEKS_ACTUAL, NET_GROSS_TARIFF_ACTUAL, STARTING_HOUSEHOLDS, GROSS_RETENTION_BASE, GROSS_RETENTION_ACTUAL, FLG_52_WEEK, EVENT_YEAR
FROM WARNER_RAW.MA_MART.D_WRN_KPIS_OUTPUT_DASHBOARD;


-- WARNER_BASE.MA_MART.D_WRN_KPIS_SUMMARY source

create or replace view WARNER_BASE.MA_MART.D_WRN_KPIS_SUMMARY(
	ARRIVAL_YEAR,
	ARRIVAL_PERIOD,
	EVENT_YEAR,
	EVENT_PERIOD,
	EVENT_WEEK,
	SEG,
	SITE_CD,
	NEW_REPEAT,
	BOOKING_CHANNEL_CD,
	BOOK_TYPE,
	EVENT_TYPE,
	FESTIVE_FLAG,
	NB_EVENTS,
	BOOKINGS,
	GUEST_WEEKS,
	GROSS_TARIFF,
	HOUSEHOLDS,
	SITE_NAME,
	CHANNEL,
	F_YEAR,
	A_YEAR,
	EVENT_WEEK_YEAR,
	FLG_UPTO_WEEK,
	FLG_52_WEEK,
	BY_DAY1,
	BY_P01,
	BY_P02,
	BY_P03,
	BY_P04,
	BY_P05,
	BY_P06,
	BY_P07,
	BY_P08,
	BY_P09,
	BY_P10,
	BY_P11,
	BY_P12,
	HH_RETENTION
) as SELECT ARRIVAL_YEAR, ARRIVAL_PERIOD, EVENT_YEAR, EVENT_PERIOD, EVENT_WEEK, SEG, SITE_CD, NEW_REPEAT, BOOKING_CHANNEL_CD, BOOK_TYPE, EVENT_TYPE, FESTIVE_FLAG, NB_EVENTS, BOOKINGS, GUEST_WEEKS, GROSS_TARIFF, HOUSEHOLDS, SITE_NAME, CHANNEL, F_YEAR, A_YEAR, EVENT_WEEK_YEAR, FLG_UPTO_WEEK, FLG_52_WEEK, BY_DAY1, BY_P01, BY_P02, BY_P03, BY_P04, BY_P05, BY_P06, BY_P07, BY_P08, BY_P09, BY_P10, BY_P11, BY_P12, HH_RETENTION
FROM WARNER_RAW.MA_MART.D_WRN_KPIS_SUMMARY;


-- WARNER_BASE.MA_MART.D_WRN_MULTI_UNIT source

create or replace view WARNER_BASE.MA_MART.D_WRN_MULTI_UNIT(
	BOOKING_REFERENCE,
	DELEGATE_1,
	DELEGATE_2,
	DELEGATE_3,
	DELEGATE_4,
	DELEGATE_5,
	DELEGATE_6,
	DELEGATE_7,
	DELEGATE_8,
	DELEGATE_9,
	DELEGATE_10,
	DELEGATE_11,
	DELEGATE_12,
	DELEGATE_13,
	DELEGATE_14,
	DELEGATE_15,
	DELEGATE_16,
	DELEGATE_17,
	DELEGATE_18,
	DELEGATE_19,
	DELEGATE_20,
	DELEGATE_21,
	DELEGATE_22,
	DELEGATE_23,
	DELEGATE_24,
	DELEGATE_25,
	DELEGATE_26,
	DELEGATE_27,
	DELEGATE_28,
	DELEGATE_29,
	DELEGATE_30
) as SELECT "BOOKING_REFERENCE", "DELEGATE_1", "DELEGATE_2", "DELEGATE_3", "DELEGATE_4", "DELEGATE_5", "DELEGATE_6", "DELEGATE_7", "DELEGATE_8", "DELEGATE_9", "DELEGATE_10", "DELEGATE_11", "DELEGATE_12", "DELEGATE_13", "DELEGATE_14", "DELEGATE_15", "DELEGATE_16", "DELEGATE_17", "DELEGATE_18", "DELEGATE_19", "DELEGATE_20", "DELEGATE_21", "DELEGATE_22", "DELEGATE_23", "DELEGATE_24", "DELEGATE_25", "DELEGATE_26", "DELEGATE_27", "DELEGATE_28", "DELEGATE_29", "DELEGATE_30" FROM "WARNER_RAW"."MA_MART"."D_WRN_MULTI_UNIT";


-- WARNER_BASE.MA_MART.D_WRN_REDLIST_ADDRESS source

create or replace view WARNER_BASE.MA_MART.D_WRN_REDLIST_ADDRESS(
	NAME,
	ADDRESS_1,
	ADDRESS_2,
	ADDRESS_3,
	ADDRESS_4,
	ADDRESS_5,
	ADDRESS_6,
	POST_CODE,
	ADDRESS_ID
) as SELECT "NAME", "ADDRESS_1", "ADDRESS_2", "ADDRESS_3", "ADDRESS_4", "ADDRESS_5", "ADDRESS_6", "POST_CODE", "ADDRESS_ID" FROM "WARNER_RAW"."MA_MART"."D_WRN_REDLIST_ADDRESS";

DESCRIBE VIEW d_wrn_guest;


