use database haven_raw;
use schema bigquery;
use warehouse bourne_batch_dataload_xsmall;
use role haven_batch_dataload;
 
create or replace TABLE HAVEN_RAW.BIGQUERY.SEARCHES_AND_BOOKINGS_SUMMARY (
	bookings NUMBER(38,0),
	arrival_date VARCHAR(16777216),
	park_code VARCHAR(16777216),
	searches NUMBER(38,0),
	arrival_period VARCHAR(16777216),
	searches_and_bookings_date VARCHAR(16777216),
	holiday_type VARCHAR(16777216)
);

insert into HAVEN_RAW.BIGQUERY.SEARCHES_AND_BOOKINGS_SUMMARY 
(BOOKINGS, ARRIVAL_DATE, PARK_CODE, SEARCHES, ARRIVAL_PERIOD, SEARCHES_AND_BOOKINGS_DATE, HOLIDAY_TYPE)
SELECT "bookings", "arrival_date", "park_code", "searches", "arrival_period", "date", "holiday_type"
FROM HAVEN_RAW.BIGQUERY.STAGE_01_SEARCHES_AND_BOOKINGS_SUMMARY
order by "date";

-- HAVEN_RAW.BIGQUERY.STAGE_02_WEEKLY_SUMMARY definition

create or replace TABLE HAVEN_RAW.BIGQUERY.WEEKLY_SUMMARY (
	Arrival_Week VARCHAR(16777216),
	ParkCode VARCHAR(16777216),
	Searches NUMBER(38,0),
	Book_Week VARCHAR(16777216),
	Holiday_Type VARCHAR(16777216),
	Bookings NUMBER(38,0)
);

INSERT INTO HAVEN_RAW.BIGQUERY.WEEKLY_SUMMARY
(ARRIVAL_WEEK, PARKCODE, SEARCHES, BOOK_WEEK, HOLIDAY_TYPE, BOOKINGS)
SELECT "Arrival_Week", "ParkCode", "Searches", "Book_Week", "Holiday_Type", "Bookings"
FROM HAVEN_RAW.BIGQUERY.STAGE_02_WEEKLY_SUMMARY;

-- HAVEN_RAW.BIGQUERY.STAGE_03_BOOKING_IDS_BY_CHANNEL definition

create or replace TABLE HAVEN_RAW.BIGQUERY.BOOKING_IDS_BY_CHANNEL (
	booking_id_by_channel_date VARCHAR(16777216),
	channel_level_3 VARCHAR(16777216),
	channel VARCHAR(16777216),
	channel_level_2 VARCHAR(16777216),
	hol_booking_id VARCHAR(16777216),
	revenue FLOAT
);

insert into HAVEN_RAW.BIGQUERY.BOOKING_IDS_BY_CHANNEL 
(BOOKING_ID_BY_CHANNEL_DATE, CHANNEL_LEVEL_3, CHANNEL, CHANNEL_LEVEL_2, HOL_BOOKING_ID, REVENUE)
SELECT "date", "channel_level_3", "channel", "channel_level_2", "hol_booking_id", "revenue"
FROM HAVEN_RAW.BIGQUERY.STAGE_03_BOOKING_IDS_BY_CHANNEL
order by "date";

-- HAVEN_RAW.BIGQUERY.STAGE_05A_PRODUCT_IMPRESSIONS_PERIOD_ONLY_QA definition

create or replace TABLE HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_PERIOD_ONLY_QA (
	product_list_name VARCHAR(16777216),
	bookings NUMBER(38,0),
	arrival_period VARCHAR(16777216),
	holiday_type VARCHAR(16777216),
	searches NUMBER(38,0),
	book_week VARCHAR(16777216)
);

insert into  HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_PERIOD_ONLY_QA
(PRODUCT_LIST_NAME, BOOKINGS, ARRIVAL_PERIOD, HOLIDAY_TYPE, SEARCHES, BOOK_WEEK)
SELECT "product_list_name", "bookings", "arrival_period", "holiday_type", "searches", "book_week"
FROM HAVEN_RAW.BIGQUERY.STAGE_05A_PRODUCT_IMPRESSIONS_PERIOD_ONLY_QA;



-- HAVEN_RAW.BIGQUERY.STAGE_06_PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_WEEK definition

create or replace TABLE HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_WEEK (
	book_week VARCHAR(16777216),
	channel VARCHAR(16777216),
	holiday_type VARCHAR(16777216),
	searches NUMBER(38,0),
	arrival_week VARCHAR(16777216),
	product_list_name VARCHAR(16777216),
	bookings NUMBER(38,0),
	park_code VARCHAR(16777216)
);

INSERT INTO HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_WEEK
(BOOK_WEEK, CHANNEL, HOLIDAY_TYPE, SEARCHES, ARRIVAL_WEEK, PRODUCT_LIST_NAME, BOOKINGS, PARK_CODE)
SELECT "book_week", "channel", "holiday_type", "searches", "arrival_week", "product_list_name", "bookings", "park_code"
FROM HAVEN_RAW.BIGQUERY.STAGE_06_PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_WEEK;

-- HAVEN_RAW.BIGQUERY.STAGE_07_PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_PERIOD definition

create or replace TABLE HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_PERIOD (
	book_week VARCHAR(16777216),
	holiday_type VARCHAR(16777216),
	channel VARCHAR(16777216),
	arrival_period VARCHAR(16777216),
	product_list_name VARCHAR(16777216),
	searches NUMBER(38,0),
	bookings NUMBER(38,0)
);

INSERT INTO HAVEN_RAW.BIGQUERY.PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_PERIOD 
(BOOK_WEEK, HOLIDAY_TYPE, CHANNEL, ARRIVAL_PERIOD, PRODUCT_LIST_NAME, SEARCHES, BOOKINGS)
SELECT "book_week", "holiday_type", "channel", "arrival_period", "product_list_name", "searches", "bookings"
FROM HAVEN_RAW.BIGQUERY.STAGE_07_PRODUCT_IMPRESSIONS_AND_BOOKINGS_BY_PERIOD;
