use ROLE dba;

CREATE VIEW HAVEN_BASE.HIT_ADMIN.HIT_ARRIVALS_LIST
( RESID, ALTRESID, PARKCODE, PITCHNUMBER, RESSTATUS, VANTYPE, LASTMINUTE, ARRIVALDATE, DURATION, ARRIVALGROUP, ARRIVAL_FOREGROUND, ARRIVAL_BACKGROUND, NAME )
AS SELECT RESID, ALTRESID, PARKCODE, PITCHNUMBER, RESSTATUS, VANTYPE, LASTMINUTE, ARRIVALDATE, DURATION, ARRIVALGROUP, ARRIVAL_FOREGROUND, ARRIVAL_BACKGROUND, NAME
FROM HAVEN_RAW.HIT_ADMIN_ETLEAP.HIT_ARRIVALS_LIST;

use SCHEMA haven_base.hit_admin;

use ROLE dba;

use SCHEMA haven_base.playsafe;

CREATE OR REPLACE VIEW HAVEN_BASE.PLAYSAFE.MACHINE_COLLECTIONS
(SITECODE, SITENAME, REGION, MACHINE_COLLECTIONID, MACHINE_COLLECTIONDATETIME, MACHINE_PREVIOUSCOLLECTIONDATETIME, MACHINE_COLLECTIONDAYS, MACHINE_COLLECTIONTYPE, MACHINE_CLASS, MACHINE_TYPE, MACHINE_NAME, MACHINE_MANUFACTURER, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_GROSSCASH, MACHINE_REFILLS, MACHINE_HANDPAYS, MACHINE_ENGINEERSCREDITS, MACHINE_PROMOCASH, MACHINE_CASHLESSCARDIN, MACHINE_DEBITCARDIN, MACHINE_TICKETSIN, MACHINE_TICKETSOUT, MACHINE_NETCASH, MACHINE_RTP, MACHINE_VTP, MACHINE_WINS, MACHINE_CASHDIFFERANCE, MACHINE_NETEARNINGS, MACHINE_TAXTYPE, MACHINE_TAXRATE, MACHINE_TAXAMOUNT, MACHINE_NETLESSTAX, MACHINE_GROSSCASHBREAKDOWN_NOTES50, MACHINE_GROSSCASHBREAKDOWN_NOTES20, MACHINE_GROSSCASHBREAKDOWN_NOTES10, MACHINE_GROSSCASHBREAKDOWN_NOTES5, MACHINE_GROSSCASHBREAKDOWN_COINS200, MACHINE_GROSSCASHBREAKDOWN_COINS100, MACHINE_GROSSCASHBREAKDOWN_COINS50, MACHINE_GROSSCASHBREAKDOWN_COINS20, MACHINE_GROSSCASHBREAKDOWN_COINS10, MACHINE_GROSSCASHBREAKDOWN_COINS5, MACHINE_GROSSCASHBREAKDOWN_COINS2, MACHINE_GROSSCASHBREAKDOWN_COINS1, MACHINE_METERS)
AS SELECT SITECODE, SITENAME, REGION, MACHINE_COLLECTIONID, MACHINE_COLLECTIONDATETIME, MACHINE_PREVIOUSCOLLECTIONDATETIME, MACHINE_COLLECTIONDAYS, MACHINE_COLLECTIONTYPE, MACHINE_CLASS, MACHINE_TYPE, MACHINE_NAME, MACHINE_MANUFACTURER, MACHINE_LOCATION, MACHINE_ZONE, MACHINE_GROSSCASH, MACHINE_REFILLS, MACHINE_HANDPAYS, MACHINE_ENGINEERSCREDITS, MACHINE_PROMOCASH, MACHINE_CASHLESSCARDIN, MACHINE_DEBITCARDIN, MACHINE_TICKETSIN, MACHINE_TICKETSOUT, MACHINE_NETCASH, MACHINE_RTP, MACHINE_VTP, MACHINE_WINS, MACHINE_CASHDIFFERANCE, MACHINE_NETEARNINGS, MACHINE_TAXTYPE, MACHINE_TAXRATE, MACHINE_TAXAMOUNT, MACHINE_NETLESSTAX, MACHINE_GROSSCASHBREAKDOWN_NOTES50, MACHINE_GROSSCASHBREAKDOWN_NOTES20, MACHINE_GROSSCASHBREAKDOWN_NOTES10, MACHINE_GROSSCASHBREAKDOWN_NOTES5, MACHINE_GROSSCASHBREAKDOWN_COINS200, MACHINE_GROSSCASHBREAKDOWN_COINS100, MACHINE_GROSSCASHBREAKDOWN_COINS50, MACHINE_GROSSCASHBREAKDOWN_COINS20, MACHINE_GROSSCASHBREAKDOWN_COINS10, MACHINE_GROSSCASHBREAKDOWN_COINS5, MACHINE_GROSSCASHBREAKDOWN_COINS2, MACHINE_GROSSCASHBREAKDOWN_COINS1, MACHINE_METERS
FROM HAVEN_RAW.PLAYSAFE.MACHINE_COLLECTIONS;

SELECT * FROM HAVEN_BASE.PLAYSAFE.MACHINE_COLLECTIONS LIMIT 20;

use ROLE dba;
use SCHEMA haven_base.energy_meters;

CREATE VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES_ESTIMATES
( CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED )
AS SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES_ESTIMATES;

CREATE VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY_ESTIMATES
( CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED )
AS SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY_ESTIMATES;

CREATE VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER_ESTIMATES
( CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED )
AS SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER_ESTIMATES;

SELECT * FROM HAVEN_BASE.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES_ESTIMATES LIMIT 10;
SELECT * FROM HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY_ESTIMATES LIMIT 10;
SELECT * FROM HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER_ESTIMATES LIMIT 10;

-- 10/04/2025

use ROLE haven_batch_dataload;

alter table haven_raw.energy_meters.metered_usage_ecbourneLodges 
rename to haven_raw.energy_meters.metered_usage_ecbourneLodges_five;

alter table haven_raw.energy_meters.metered_usage_HALF_HOURLY_USAGE_Bourne_Commercial_Electricity 
rename to haven_raw.energy_meters.metered_usage_HALF_HOURLY_USAGE_Bourne_Commercial_Electricity_five;

alter table haven_raw.energy_meters.metered_usage_HALF_HOURLY_USAGE_Bourne_Gas_Heat_Water 
rename to haven_raw.energy_meters.metered_usage_HALF_HOURLY_USAGE_Bourne_Gas_Heat_Water_five;

-- 

alter table haven_raw.energy_meters.METERED_USAGE_ECBOURNELODGES_ESTIMATES 
rename to haven_raw.energy_meters.metered_usage_ecbourneLodges;

alter table haven_raw.energy_meters.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY_ESTIMATES 
rename to haven_raw.energy_meters.metered_usage_HALF_HOURLY_USAGE_Bourne_Commercial_Electricity;

alter table haven_raw.energy_meters.metered_usage_HALF_HOURLY_USAGE_Bourne_Gas_Heat_Water_estimates 
rename to haven_raw.energy_meters.metered_usage_HALF_HOURLY_USAGE_Bourne_Gas_Heat_Water;

use ROLE dba;

DROP VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES_ESTIMATES;
DROP VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY_ESTIMATES;
DROP VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER_ESTIMATES;


CREATE VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES
( CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED )
AS SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES;

CREATE VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY
( CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED )
AS SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY;

CREATE VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER
( CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED )
AS SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER;

SELECT * FROM HAVEN_BASE.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES LIMIT 10;
SELECT * FROM HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY LIMIT 10;
SELECT * FROM HAVEN_BASE.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER LIMIT 10;

use ROLE haven_batch_dataload;

use SCHEMA haven_raw.energy_meters;

show warehouses;

use warehouse BOURNE_BATCH_DATALOAD_XSMALL;

show tables;


READING_EXTRACT_BOURNE_EVC

-- BOURNE LODGES

-- TARGET: ECBOURNELODGES
-- SOURCE: ECBOURNELODGES_FIVE

SELECT CURRENT_ROLE();

INSERT INTO HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, NULL
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNELODGES_FIVE
ORDER BY METER_TIMESTAMP;

-- BOURNE_GAS_HEAT_WATER

-- TARGET: HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER
-- SOURCE: ECBOURNEGAS
-- SOURCE: ECBOURNEWATER
-- SOURCE: HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER_FIVE

INSERT INTO HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, NULL
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER_FIVE
ORDER BY METER_TIMESTAMP;

INSERT INTO HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, NULL
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNEGAS
ORDER BY METER_TIMESTAMP;

INSERT INTO HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_GAS_HEAT_WATER
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, NULL
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_ECBOURNEWATER
ORDER BY METER_TIMESTAMP;

-- COMMERCIAL_ELECTRICITY

-- TARGET: HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY
-- SOURCE: HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_GAS
-- SOURCE: HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_WATER
-- SOURCE: HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY_FIVE


INSERT INTO HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, NULL
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY_FIVE
ORDER BY METER_TIMESTAMP;


INSERT INTO HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, NULL
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_GAS
ORDER BY METER_TIMESTAMP;

INSERT INTO HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_ELECTRICITY
SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, NULL
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_HALF_HOURLY_USAGE_BOURNE_COMMERCIAL_WATER
ORDER BY METER_TIMESTAMP;

-- READING_EXTRACT_BOURNE_EVC

USE ROLE DBA;

CREATE VIEW HAVEN_BASE.ENERGY_METERS.METERED_USAGE_READING_EXTRACT_BOURNE_EVC
( CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, ESTIMATED )
AS SELECT CUSTOMER, METER, CHANNEL_TYPE, METER_TIMESTAMP, A_PLUS, A_MINUS, NULL
FROM HAVEN_RAW.ENERGY_METERS.METERED_USAGE_READING_EXTRACT_BOURNE_EVC
ORDER BY METER_TIMESTAMP;

