use ROLE dba;

-- HAVEN_BASE.ZBSDATA_COMPLEX.RPT_SALESTRANSACTIONS source

use SCHEMA HAVEN_BASE.ZBSDATA_COMPLEX;

SHOW views;

use SCHEMA HAVEN_RAW.ZBSDATA_COMPLEX_ETLEAP;

SHOW tables;

use SCHEMA HAVEN_BASE.ZBSDATA_COMPLEX;

create or replace view HAVEN_BASE.ZBSDATA_COMPLEX.RPT_SALESTRANSACTIONS
( TRANSACTIONID, TERMINALID, ACCOUNTID, ACCOUNTNO, "Order", ORDERLINE, TRANSDATETIME, TRANSDATE, TRANSTIME, HALFHOUR, PRODCODE, PORTIONTYPEID, EMPCODE, OWNERCODE, AUTHCODE, CORRCODE, DISCCODE, PROMOCODE, EVENTCODE, CORRREASONCODE, CARDNUMBER, PROMOCARDNUMBER, IZONECARDNUMBER, DISCOUNTBARCODE, PROMOBARCODE, DESTINATIONCODE, RATIO, QUANTITY, GROSS, INCTAX, EXCTAX, SERVICE, TARIFF, COST, FIFOCOST, DISCOUNT, PROMOTION, VOLUME, LMDT, REFUNDMODE, QUANTITYPROMOTED, DISCOUNTREASON )
AS SELECT TRANSACTIONID, TERMINALID, ACCOUNTID, ACCOUNTNO, "Order", ORDERLINE, TRANSDATETIME, TRANSDATE, TRANSTIME, HALFHOUR, PRODCODE, PORTIONTYPEID, EMPCODE, OWNERCODE, AUTHCODE, CORRCODE, DISCCODE, PROMOCODE, EVENTCODE, CORRREASONCODE, CARDNUMBER, PROMOCARDNUMBER, IZONECARDNUMBER, DISCOUNTBARCODE, PROMOBARCODE, DESTINATIONCODE, RATIO, QUANTITY, GROSS, INCTAX, EXCTAX, SERVICE, TARIFF, COST, FIFOCOST, DISCOUNT, PROMOTION, VOLUME, LMDT, REFUNDMODE, QUANTITYPROMOTED, DISCOUNTREASON
FROM HAVEN_RAW.ZBSDATA_COMPLEX_ETLEAP.RPT_SALESTRANSACTIONS;

create or replace view HAVEN_BASE.ZBSDATA_COMPLEX.IORDER_TBL_MO_ORDER2
( MO_ORDER_ID, MO_ORDER_BRAND_ID, MO_ORDER_SITE_ID, MO_ORDER_SA_ID, MO_ORDER_TABLE_NO, MO_ORDER_BUSINESS, MO_ORDER_UNIQUE_REFERENCE, MO_ORDER_FIRST_NAME, MO_ORDER_LAST_NAME, MO_ORDER_IPN_TRACK_ID, MO_ORDER_ITEM_NUMBER, MO_ORDER_MC_FEE, MO_ORDER_MC_GROSS, MO_ORDER_PAYMENT_STATUS, MO_ORDER_PAYER_EMAIL, MO_ORDER_PAYER_ID, MO_ORDER_PAYER_STATUS, MO_ORDER_PAYMENT_TYPE, MO_ORDER_TXN_ID, MO_ORDER_TXN_TYPE, MO_ORDER_BRAINTREE_TRANSACTION_ID, MO_ORDER_BRAINTREE_PAYMENT_TYPE, MO_ORDER_VERIFY_SIGN, MO_ORDER_PAYMENT_DATE, MO_ORDER_ACCOUNT_ID, MO_ORDER_ACCOUNT_NUMBER, MO_ORDER_SENT_TILL, MO_ORDER_QR_CODE, MO_ORDER_PP_PING, MO_ORDER_AZTEC_PING, MO_ORDER_TIME_STAMP, MO_ORDER_DEVICE_IDENTIFIER, MO_ORDER_USER_EMAIL, MO_ORDER_REFUND_ID, MO_ORDER_RATING, MO_ORDER_ACCOUNT_CUSTOMER_NAME, MO_ORDER_PAYMENT_METHOD_ID, MO_ORDER_WEBFORM_USER_ID, MO_ORDER_USER_ID, MO_ORDER_PAYPAL_TOKEN, INSERTDT, MODIFIEDDT, API_USERNAME )
AS SELECT MO_ORDER_ID, MO_ORDER_BRAND_ID, MO_ORDER_SITE_ID, MO_ORDER_SA_ID, MO_ORDER_TABLE_NO, MO_ORDER_BUSINESS, MO_ORDER_UNIQUE_REFERENCE, MO_ORDER_FIRST_NAME, MO_ORDER_LAST_NAME, MO_ORDER_IPN_TRACK_ID, MO_ORDER_ITEM_NUMBER, MO_ORDER_MC_FEE, MO_ORDER_MC_GROSS, MO_ORDER_PAYMENT_STATUS, MO_ORDER_PAYER_EMAIL, MO_ORDER_PAYER_ID, MO_ORDER_PAYER_STATUS, MO_ORDER_PAYMENT_TYPE, MO_ORDER_TXN_ID, MO_ORDER_TXN_TYPE, MO_ORDER_BRAINTREE_TRANSACTION_ID, MO_ORDER_BRAINTREE_PAYMENT_TYPE, MO_ORDER_VERIFY_SIGN, MO_ORDER_PAYMENT_DATE, MO_ORDER_ACCOUNT_ID, MO_ORDER_ACCOUNT_NUMBER, MO_ORDER_SENT_TILL, MO_ORDER_QR_CODE, MO_ORDER_PP_PING, MO_ORDER_AZTEC_PING, MO_ORDER_TIME_STAMP, MO_ORDER_DEVICE_IDENTIFIER, MO_ORDER_USER_EMAIL, MO_ORDER_REFUND_ID, MO_ORDER_RATING, MO_ORDER_ACCOUNT_CUSTOMER_NAME, MO_ORDER_PAYMENT_METHOD_ID, MO_ORDER_WEBFORM_USER_ID, MO_ORDER_USER_ID, MO_ORDER_PAYPAL_TOKEN, INSERTDT, MODIFIEDDT, API_USERNAME
FROM HAVEN_RAW.ZBSDATA_COMPLEX_ETLEAP.IORDER_TBL_MO_ORDER2;

DROP VIEW HAVEN_BASE.ZBSDATA_COMPLEX.IORDER_TBL_MO_ORDER2;