use ROLE dba;

-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.productline
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.payments
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.accountnumberassigned
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.orderlinediscounted
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.orderlinepromoted
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.delayedorderpickuptimeset
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.billdiscountline
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.promotionline   
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.loyaltyaccountassigned
-- HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.draweropened

use SCHEMA haven_base.aztec_complex;

CREATE OR replace VIEW haven_base.aztec_complex.ACCOUNTNUMBERASSIGNED
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, ACCOUNT_NUMBER, SEAT_NUMBER, ISDRIVETHRUACCOUNT, ISDELAYEDORDERACCOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, ACCOUNT_NUMBER, SEAT_NUMBER, ISDRIVETHRUACCOUNT, ISDELAYEDORDERACCOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.ACCOUNTNUMBERASSIGNED;

CREATE OR replace VIEW haven_base.aztec_complex.BILLDISCOUNTLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", MOVETYPE, BILLDISCOUNTLINE, BILLPROMOTION, AMOUNT, CORRECTEDORDER, ACCOUNTNUMBER, AUTHORISATIONREFERENCE, MANUALLYKEYED, EXTERNALMODEID, EXTERNALQUALIFYINGPRODUCT, PERCENTAGE, CANCELLINGINCREASEBALANCEDISCOUNT, LMDT, OWNERID, AUTHORISER, ORIGINALDATETIME, DISCOUNTREASON, APPLIESTOORDERLINEFAMILY )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", MOVETYPE, BILLDISCOUNTLINE, BILLPROMOTION, AMOUNT, CORRECTEDORDER, ACCOUNTNUMBER, AUTHORISATIONREFERENCE, MANUALLYKEYED, EXTERNALMODEID, EXTERNALQUALIFYINGPRODUCT, PERCENTAGE, CANCELLINGINCREASEBALANCEDISCOUNT, LMDT, OWNERID, AUTHORISER, ORIGINALDATETIME, DISCOUNTREASON, APPLIESTOORDERLINEFAMILY
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.BILLDISCOUNTLINE;

CREATE OR replace VIEW haven_base.aztec_complex.DRAWEROPENED
( TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, ACCOUNTID, LMDT, AUTHORISER, TRAINING )
AS SELECT TRANSACTIONID, "DATE", TERMINALID, EMPLOYEEID, ACCOUNTID, LMDT, AUTHORISER, TRAINING
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.DRAWEROPENED;

CREATE OR replace VIEW haven_base.aztec_complex.LOYALTYACCOUNTASSIGNED
( TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, LOYALTYACCOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, LOYALTYACCOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.LOYALTYACCOUNTASSIGNED;

CREATE OR replace VIEW haven_base.aztec_complex.DELAYEDORDERPICKUPTIMESET
( TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, AUTHORISER, ACCOUNTID, TRANSACTION_NUMBER, PICKUPTIME, LMDT )
AS SELECT TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, AUTHORISER, ACCOUNTID, TRANSACTION_NUMBER, PICKUPTIME, LMDT
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.DELAYEDORDERPICKUPTIMESET;

CREATE OR replace VIEW haven_base.aztec_complex.ORDERLINEDISCOUNTED
( TRANSACTIONID, DATE, BUSINESSDATE, EMPLOYEEID, AUTHORISER, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, BILLDISCOUNTLINE, ORDERLINE, AMOUNTDISCOUNTED, LMDT )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, EMPLOYEEID, AUTHORISER, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, BILLDISCOUNTLINE, ORDERLINE, AMOUNTDISCOUNTED, LMDT
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.ORDERLINEDISCOUNTED;

CREATE OR replace VIEW haven_base.aztec_complex.ORDERLINEPROMOTED
( TRANSACTIONID, DATE, BUSINESSDATE, EMPLOYEEID, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, PROMOTIONLINE, ORDERLINE, DISTRIBUTEDQUANTITY, AMOUNTDISCOUNTED, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, EMPLOYEEID, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, PROMOTIONLINE, ORDERLINE, DISTRIBUTEDQUANTITY, AMOUNTDISCOUNTED, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.ORDERLINEPROMOTED;

CREATE OR replace VIEW haven_base.aztec_complex.PAYMENTS
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", PAYMENT, AMOUNT, "CHANGE", PAYMENTMETHOD, RECEIPTNO, CORRECTEDORDER, MOVETYPE, TIP, PAYMENTCOUNT, LMDT, CASH_BACK, ISEFT, PROCESSED, PAYOUT, ISCASHBACK, OWNERID, AUTHORISER, ACCOUNTNUMBER, REPORTINGEMPLOYEEID, AMOUNTINTENDEREDCURRENCY, FORFEITAMOUNT, TERMINALSESSIONID, MONEYBELTPAYMENT, ORIGINALDATETIME )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", PAYMENT, AMOUNT, "CHANGE", PAYMENTMETHOD, RECEIPTNO, CORRECTEDORDER, MOVETYPE, TIP, PAYMENTCOUNT, LMDT, CASH_BACK, ISEFT, PROCESSED, PAYOUT, ISCASHBACK, OWNERID, AUTHORISER, ACCOUNTNUMBER, REPORTINGEMPLOYEEID, AMOUNTINTENDEREDCURRENCY, FORFEITAMOUNT, TERMINALSESSIONID, MONEYBELTPAYMENT, ORIGINALDATETIME
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.PAYMENTS;

CREATE OR replace VIEW haven_base.aztec_complex.PRODUCTLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", ORDERLINE, CORRECTEDORDERLINE, QUANTITY, PRICE, MOVETYPE, PRODUCT, HALF, RATIO, PORTION, CORRECTIONMETHOD, CORRECTIONREASON, TARIFFPRICE, LMDT, OWNERID, UNITPRICE, AUTHORISER, SPECIALVOUCHERSALE, ORDERDESTINATION, MULTICHOICEMODE, PRICETYPE, ORIGINALDATETIME )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", ORDERLINE, CORRECTEDORDERLINE, QUANTITY, PRICE, MOVETYPE, PRODUCT, HALF, RATIO, PORTION, CORRECTIONMETHOD, CORRECTIONREASON, TARIFFPRICE, LMDT, OWNERID, UNITPRICE, AUTHORISER, SPECIALVOUCHERSALE, ORDERDESTINATION, MULTICHOICEMODE, PRICETYPE, ORIGINALDATETIME
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.PRODUCTLINE;

CREATE OR replace VIEW haven_base.aztec_complex.PROMOTIONLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, PROMOTIONLINE, PROMOTION, AMOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, PROMOTIONLINE, PROMOTION, AMOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.PROMOTIONLINE;

-- KMS Reporting

use ROLE dba;

-- KIQ_HISTORY_KITCHENSERVER
-- KIQ_EVENT_ORDERLINE
-- KIQ_INFO_ORDERLINE
-- KIQ_INFO_ACCOUNT
-- KIQ_HISTORY_KITCHEN
-- KIQ_EVENT_ACCOUNT

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_EVENT_ACCOUNT
( ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTACTIONID, TABLENUMBER, COVERS, CUSTOMERNAME, ACCOUNTOWNERNAME, ISDELAYEDORDER, DELIVERYTIME, COMMSLMDT, ETLEAP_UPDATE_TIMESTAMP )
AS SELECT ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTACTIONID, TABLENUMBER, COVERS, CUSTOMERNAME, ACCOUNTOWNERNAME, ISDELAYEDORDER, DELIVERYTIME, COMMSLMDT, ETLEAP_UPDATE_TIMESTAMP
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_EVENT_ACCOUNT;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_EVENT_ORDERLINE
( ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ORDERLINEID, ORDERLINEACTIONID, CAUSEDBYTYPEID, ACCOUNTID, DISPLAYQUANTITY, TILLUSERNAME, ISTARGETTIMEEXCEEDED, EXTERNALCORRECTIONMETHODNAME, STATIONIDS, ORDERSTAGEID, ORDERLINESTATUSID, TICKETID, COMMSLMDT, ETLEAP_UPDATE_TIMESTAMP )
AS SELECT ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ORDERLINEID, ORDERLINEACTIONID, CAUSEDBYTYPEID, ACCOUNTID, DISPLAYQUANTITY, TILLUSERNAME, ISTARGETTIMEEXCEEDED, EXTERNALCORRECTIONMETHODNAME, STATIONIDS, ORDERSTAGEID, ORDERLINESTATUSID, TICKETID, COMMSLMDT, ETLEAP_UPDATE_TIMESTAMP
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_EVENT_ORDERLINE;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_HISTORY_KITCHEN
( AUDITTIME, AUDITTIMELONG, KITCHENID, NAME, SITEGROUPNAME, UTCOFFSETMINS, ROLLOVERTIMEMINS, COMMSLMDT )
AS SELECT AUDITTIME, AUDITTIMELONG, KITCHENID, NAME, SITEGROUPNAME, UTCOFFSETMINS, ROLLOVERTIMEMINS, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_HISTORY_KITCHEN;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_HISTORY_KITCHENSERVER
( AUDITTIME, AUDITTIMELONG, KITCHENID, NAME, SOFTWAREVERSION, ISACTIVE, COMMSLMDT )
AS SELECT AUDITTIME, AUDITTIMELONG, KITCHENID, NAME, SOFTWAREVERSION, ISACTIVE, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_HISTORY_KITCHENSERVER;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_INFO_ACCOUNT
( NAUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTNUMBER, COMMSLMDT, ETLEAP_UPDATE_TIMESTAMP )
AS SELECT AUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTNUMBER, COMMSLMDT, ETLEAP_UPDATE_TIMESTAMP
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_INFO_ACCOUNT;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_INFO_ORDERLINE
( AUDITTIMELONG, KITCHENID, ORDERLINEID, EXTERNALORDERLINEIDS, PARENTORDERLINEID, PRIMARYTEXT, COURSEID, COURSENAME, LINEPRICENUMERIC, ORDERLINETYPEID, ORIGINALORDERLINEID, COMMSLMDT, ETLEAP_UPDATE_TIMESTAMP )
AS SELECT AUDITTIMELONG, KITCHENID, ORDERLINEID, EXTERNALORDERLINEIDS, PARENTORDERLINEID, PRIMARYTEXT, COURSEID, COURSENAME, LINEPRICENUMERIC, ORDERLINETYPEID, ORIGINALORDERLINEID, COMMSLMDT, ETLEAP_UPDATE_TIMESTAMP
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_INFO_ORDERLINE;


-- 10/10/2025

use role dba;
use SCHEMA haven_base.aztec_complex;


CREATE OR replace VIEW haven_base.aztec_complex.ACCOUNTNUMBERASSIGNED
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, ACCOUNT_NUMBER, SEAT_NUMBER, ISDRIVETHRUACCOUNT, ISDELAYEDORDERACCOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, ACCOUNT_NUMBER, SEAT_NUMBER, ISDRIVETHRUACCOUNT, ISDELAYEDORDERACCOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.ACCOUNTNUMBERASSIGNED;

CREATE OR replace VIEW haven_base.aztec_complex.DRAWEROPENED
( TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, ACCOUNTID, LMDT, AUTHORISER, TRAINING )
AS SELECT TRANSACTIONID, "DATE", TERMINALID, EMPLOYEEID, ACCOUNTID, LMDT, AUTHORISER, TRAINING
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.DRAWEROPENED;

CREATE OR replace VIEW haven_base.aztec_complex.LOYALTYACCOUNTASSIGNED
( TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, LOYALTYACCOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, LOYALTYACCOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.LOYALTYACCOUNTASSIGNED;

CREATE OR replace VIEW haven_base.aztec_complex.DELAYEDORDERPICKUPTIMESET
( TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, AUTHORISER, ACCOUNTID, TRANSACTION_NUMBER, PICKUPTIME, LMDT )
AS SELECT TRANSACTIONID, DATE, TERMINALID, EMPLOYEEID, AUTHORISER, ACCOUNTID, TRANSACTION_NUMBER, PICKUPTIME, LMDT
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.DELAYEDORDERPICKUPTIMESET;

CREATE OR replace VIEW haven_base.aztec_complex.ORDERLINEDISCOUNTED
( TRANSACTIONID, DATE, BUSINESSDATE, EMPLOYEEID, AUTHORISER, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, BILLDISCOUNTLINE, ORDERLINE, AMOUNTDISCOUNTED, LMDT )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, EMPLOYEEID, AUTHORISER, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, BILLDISCOUNTLINE, ORDERLINE, AMOUNTDISCOUNTED, LMDT
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.ORDERLINEDISCOUNTED;

CREATE OR replace VIEW haven_base.aztec_complex.ORDERLINEPROMOTED
( TRANSACTIONID, DATE, BUSINESSDATE, EMPLOYEEID, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, PROMOTIONLINE, ORDERLINE, DISTRIBUTEDQUANTITY, AMOUNTDISCOUNTED, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, EMPLOYEEID, ACCOUNTID, TERMINALID, TRANSACTION_NUMBER, PROMOTIONLINE, ORDERLINE, DISTRIBUTEDQUANTITY, AMOUNTDISCOUNTED, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.ORDERLINEPROMOTED;

CREATE OR replace VIEW haven_base.aztec_complex.PROMOTIONLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, PROMOTIONLINE, PROMOTION, AMOUNT, LMDT, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, PROMOTIONLINE, PROMOTION, AMOUNT, LMDT, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.PROMOTIONLINE;


CREATE OR replace VIEW haven_base.aztec_complex.PAYMENTS
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", PAYMENT, AMOUNT, "CHANGE", PAYMENTMETHOD, RECEIPTNO, CORRECTEDORDER, MOVETYPE, TIP, PAYMENTCOUNT, LMDT, CASH_BACK, ISEFT, PROCESSED, PAYOUT, ISCASHBACK, OWNERID, AUTHORISER, ACCOUNTNUMBER, REPORTINGEMPLOYEEID, AMOUNTINTENDEREDCURRENCY, FORFEITAMOUNT, TERMINALSESSIONID, MONEYBELTPAYMENT, ORIGINALDATETIME )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", PAYMENT, AMOUNT, "CHANGE", PAYMENTMETHOD, RECEIPTNO, CORRECTEDORDER, MOVETYPE, TIP, PAYMENTCOUNT, LMDT, CASH_BACK, ISEFT, PROCESSED, PAYOUT, ISCASHBACK, OWNERID, AUTHORISER, ACCOUNTNUMBER, REPORTINGEMPLOYEEID, AMOUNTINTENDEREDCURRENCY, FORFEITAMOUNT, TERMINALSESSIONID, MONEYBELTPAYMENT, ORIGINALDATETIME
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.PAYMENTS;

CREATE OR replace VIEW haven_base.aztec_complex.PRODUCTLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", ORDERLINE, CORRECTEDORDERLINE, QUANTITY, PRICE, MOVETYPE, PRODUCT, HALF, RATIO, PORTION, CORRECTIONMETHOD, CORRECTIONREASON, TARIFFPRICE, LMDT, OWNERID, UNITPRICE, AUTHORISER, SPECIALVOUCHERSALE, ORDERDESTINATION, MULTICHOICEMODE, PRICETYPE, ORIGINALDATETIME )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", ORDERLINE, CORRECTEDORDERLINE, QUANTITY, PRICE, MOVETYPE, PRODUCT, HALF, RATIO, PORTION, CORRECTIONMETHOD, CORRECTIONREASON, TARIFFPRICE, LMDT, OWNERID, UNITPRICE, AUTHORISER, SPECIALVOUCHERSALE, ORDERDESTINATION, MULTICHOICEMODE, PRICETYPE, ORIGINALDATETIME
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.PRODUCTLINE;

CREATE OR replace VIEW haven_base.aztec_complex.BILLDISCOUNTLINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", MOVETYPE, BILLDISCOUNTLINE, BILLPROMOTION, AMOUNT, CORRECTEDORDER, ACCOUNTNUMBER, AUTHORISATIONREFERENCE, MANUALLYKEYED, EXTERNALMODEID, EXTERNALQUALIFYINGPRODUCT, PERCENTAGE, CANCELLINGINCREASEBALANCEDISCOUNT, LMDT, OWNERID, AUTHORISER, ORIGINALDATETIME, DISCOUNTREASON, APPLIESTOORDERLINEFAMILY )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", MOVETYPE, BILLDISCOUNTLINE, BILLPROMOTION, AMOUNT, CORRECTEDORDER, ACCOUNTNUMBER, AUTHORISATIONREFERENCE, MANUALLYKEYED, EXTERNALMODEID, EXTERNALQUALIFYINGPRODUCT, PERCENTAGE, CANCELLINGINCREASEBALANCEDISCOUNT, LMDT, OWNERID, AUTHORISER, ORIGINALDATETIME, DISCOUNTREASON, APPLIESTOORDERLINEFAMILY
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.BILLDISCOUNTLINE;



CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_EVENT_ACCOUNT
( ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTACTIONID, TABLENUMBER, COVERS, CUSTOMERNAME, ACCOUNTOWNERNAME, ISDELAYEDORDER, DELIVERYTIME, COMMSLMDT )
AS SELECT ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTACTIONID, TABLENUMBER, COVERS, CUSTOMERNAME, ACCOUNTOWNERNAME, ISDELAYEDORDER, DELIVERYTIME, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_EVENT_ACCOUNT;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_EVENT_ORDERLINE
( ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ORDERLINEID, ORDERLINEACTIONID, CAUSEDBYTYPEID, ACCOUNTID, DISPLAYQUANTITY, TILLUSERNAME, ISTARGETTIMEEXCEEDED, EXTERNALCORRECTIONMETHODNAME, STATIONIDS, ORDERSTAGEID, ORDERLINESTATUSID, TICKETID, COMMSLMDT )
AS SELECT ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ORDERLINEID, ORDERLINEACTIONID, CAUSEDBYTYPEID, ACCOUNTID, DISPLAYQUANTITY, TILLUSERNAME, ISTARGETTIMEEXCEEDED, EXTERNALCORRECTIONMETHODNAME, STATIONIDS, ORDERSTAGEID, ORDERLINESTATUSID, TICKETID, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_EVENT_ORDERLINE;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_HISTORY_KITCHEN
( AUDITTIME, AUDITTIMELONG, KITCHENID, NAME, SITEGROUPNAME, UTCOFFSETMINS, ROLLOVERTIMEMINS, COMMSLMDT )
AS SELECT AUDITTIME, AUDITTIMELONG, KITCHENID, NAME, SITEGROUPNAME, UTCOFFSETMINS, ROLLOVERTIMEMINS, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_HISTORY_KITCHEN;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_HISTORY_KITCHENSERVER
( AUDITTIME, AUDITTIMELONG, KITCHENID, NAME, SOFTWAREVERSION, ISACTIVE, COMMSLMDT )
AS SELECT AUDITTIME, AUDITTIMELONG, KITCHENID, NAME, SOFTWAREVERSION, ISACTIVE, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_HISTORY_KITCHENSERVER;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_INFO_ACCOUNT
( NAUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTNUMBER, COMMSLMDT )
AS SELECT AUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTNUMBER, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_INFO_ACCOUNT;

CREATE OR REPLACE VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_INFO_ORDERLINE
( AUDITTIMELONG, KITCHENID, ORDERLINEID, EXTERNALORDERLINEIDS, PARENTORDERLINEID, PRIMARYTEXT, COURSEID, COURSENAME, LINEPRICENUMERIC, ORDERLINETYPEID, ORIGINALORDERLINEID, COMMSLMDT )
AS SELECT AUDITTIMELONG, KITCHENID, ORDERLINEID, EXTERNALORDERLINEIDS, PARENTORDERLINEID, PRIMARYTEXT, COURSEID, COURSENAME, LINEPRICENUMERIC, ORDERLINETYPEID, ORIGINALORDERLINEID, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_INFO_ORDERLINE;




-- Aztec Complex

use role dba;
use SCHEMA haven_base.aztec_complex;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_COMPLEX.MESSAGELINE
( TRANSACTIONID, DATE, BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "ORDER", ORDERLINE, CORRECTEDORDERLINE, MOVETYPE, MESSAGELINE, LMDT, OWNERID, AUTHORISER )
AS SELECT TRANSACTIONID, "DATE", BUSINESSDATE, TERMINALID, EMPLOYEEID, ACCOUNTID, TRANSACTION_NUMBER, "Order", ORDERLINE, CORRECTEDORDERLINE, MOVETYPE, MESSAGELINE, LMDT, OWNERID, AUTHORISER
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.MESSAGELINE;

CREATE OR REPLACE VIEW HAVEN_BASE.AZTEC_COMPLEX.APPORTIONEDTAX
( TERMINALID, ORDERLINE, TAX, TRANSACTION_NUMBER, ACCOUNTID, DATE, TAXPAID, EXCLUSIVE, SERVICECHARGE, TAXONSERVICECHARGE, LMDT )
AS SELECT TERMINALID, ORDERLINE, TAX, TRANSACTION_NUMBER, ACCOUNTID, "DATE", TAXPAID, "Exclusive", SERVICECHARGE, TAXONSERVICECHARGE, LMDT
FROM HAVEN_RAW.AZTEC_COMPLEX_ETLEAP.APPORTIONEDTAX;


create or replace view HAVEN_BASE.AZTEC_COMPLEX.PRODUCTS
( ENTITYCODE, RETAIL_NAME, RETAIL_DESCRIPTION, ENTITY_TYPE,	IMPORT_EXPORT_REFERENCE,	SUB_CATEGORY_NAME,	DEFAULT_PRINTER_STREAM,	PERCENT_ALCOHOL,	WHETHER_SALES_TAXABLE,	WHETHER_OPEN_PRICED,	PURCHASE_NAME,	PURCHASE_UNIT,	DEFAULT_SUPPLIER,	BUDGETED_COST_PRICE,	LMDT,	MODIFIED_BY,	CREATION_DATE,	DELETED,	AZTECEPOSBUTTON1,	AZTECEPOSBUTTON2,	AZTECEPOSBUTTON3,	EXTENDED_RTL_NAME,	SPECIALRECIPE,	TRUEHALFALLOWED,	COURSEID,	PRINTSTREAMWHENCHILD,	ROLLUPPRICEWHENCHILD,	FOLLOWCOURSEWHENCHILD,	ISGIFTCARD,	DISCONTINUE,	SOLDBYWEIGHT,	B2BNAME) 
as SELECT "ENTITYCODE", "RETAIL_NAME", "RETAIL_DESCRIPTION", "ENTITY_TYPE", "Import/Export_Reference", "Sub-Category_Name", "DEFAULT_PRINTER_STREAM", "%_Alcohol", "WHETHER_SALES_TAXABLE", "WHETHER_OPEN_PRICED", "PURCHASE_NAME", "PURCHASE_UNIT", "DEFAULT_SUPPLIER", "BUDGETED_COST_PRICE", "LMDT", "MODIFIED_BY", "CREATION_DATE", "DELETED", "AZTECEPOSBUTTON1", "AZTECEPOSBUTTON2", "AZTECEPOSBUTTON3", "EXTENDED_RTL_NAME", "SPECIALRECIPE", "TRUEHALFALLOWED", "COURSEID", "PRINTSTREAMWHENCHILD", "ROLLUPPRICEWHENCHILD", "FOLLOWCOURSEWHENCHILD", "ISGIFTCARD", "DISCONTINUE", "SOLDBYWEIGHT", "B2BNAME" 
FROM "HAVEN_RAW"."AZTEC_COMPLEX_ETLEAP"."PRODUCTS";

-- 14/10/2025

-- KMS KIQ Reporting

use ROLE dba;

use SCHEMA HAVEN_BASE.KMSREPORTING_COMPLEX;

CREATE OR replace VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_EVENT_ACCOUNT
( ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTACTIONID, TABLENUMBER, COVERS, CUSTOMERNAME, ACCOUNTOWNERID, ACCOUNTOWNERNAME, ISDELAYEDORDER, DELIVERYTIME, COMMSLMDT )
AS SELECT ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ACCOUNTID, ACCOUNTACTIONID, TABLENUMBER, COVERS, CUSTOMERNAME, ACCOUNTOWNERID, ACCOUNTOWNERNAME, ISDELAYEDORDER, DELIVERYTIME, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_EVENT_ACCOUNT;

CREATE OR replace VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_EVENT_ORDERLINE
( ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ORDERLINEID, ORDERLINEACTIONID, CAUSEDBYTYPEID, ACCOUNTID, DISPLAYQUANTITY, TILLUSERID, TILLUSERNAME, ISTARGETTIMEEXCEEDED, EXTERNALCORRECTIONMETHODID, EXTERNALCORRECTIONMETHODNAME, STATIONIDS, ORDERSTAGEID, ORDERLINESTATUSID, TICKETID, COMMSLMDT )
AS SELECT ID, AUDITTIME, AUDITTIMELONG, KITCHENID, ORDERLINEID, ORDERLINEACTIONID, CAUSEDBYTYPEID, ACCOUNTID, DISPLAYQUANTITY, TILLUSERID, TILLUSERNAME, ISTARGETTIMEEXCEEDED, EXTERNALCORRECTIONMETHODID, EXTERNALCORRECTIONMETHODNAME, STATIONIDS, ORDERSTAGEID, ORDERLINESTATUSID, TICKETID, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_EVENT_ORDERLINE;

CREATE OR replace VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_HISTORY_KITCHEN
( AUDITTIME, AUDITTIMELONG, KITCHENID, EXTERNALSITEID, EXTERNALSITEREF, NAME, SITEGROUPNAME, UTCOFFSETMINS, ROLLOVERTIMEMINS, COMMSLMDT )
AS SELECT AUDITTIME, AUDITTIMELONG, KITCHENID, EXTERNALSITEID, EXTERNALSITEREF, NAME, SITEGROUPNAME, UTCOFFSETMINS, ROLLOVERTIMEMINS, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_HISTORY_KITCHEN;
 
CREATE OR replace VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_HISTORY_KITCHENSERVER
(AUDITTIME, AUDITTIMELONG, KITCHENID, KITCHENSERVERID, NAME, SOFTWAREVERSION, ISACTIVE, COMMSLMDT )
AS SELECT AUDITTIME, AUDITTIMELONG, KITCHENID, KITCHENSERVERID, NAME, SOFTWAREVERSION, ISACTIVE, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_HISTORY_KITCHENSERVER;

CREATE OR replace VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_INFO_ACCOUNT
( AUDITTIMELONG, KITCHENID, ACCOUNTID, EXTERNALACCOUNTID, ACCOUNTNUMBER, COMMSLMDT )
AS SELECT AUDITTIMELONG, KITCHENID, ACCOUNTID, EXTERNALACCOUNTID, ACCOUNTNUMBER, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_INFO_ACCOUNT;

CREATE OR replace VIEW HAVEN_BASE.KMSREPORTING_COMPLEX.KIQ_INFO_ORDERLINE
( AUDITTIMELONG, KITCHENID, ORDERLINEID, EXTERNALORDERLINEIDS, PARENTORDERLINEID, PRODUCTID, PRIMARYTEXT, COURSEID, COURSENAME, LINEPRICENUMERIC, ORDERLINETYPEID, ORIGINALORDERLINEID, COMMSLMDT )
AS SELECT AUDITTIMELONG, KITCHENID, ORDERLINEID, EXTERNALORDERLINEIDS, PARENTORDERLINEID, PRODUCTID, PRIMARYTEXT, COURSEID, COURSENAME, LINEPRICENUMERIC, ORDERLINETYPEID, ORIGINALORDERLINEID, COMMSLMDT
FROM HAVEN_RAW.KMSREPORTING_COMPLEX_ETLEAP.KIQ_INFO_ORDERLINE;

